


-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA>
-- CREATE DATE: <CREATE DATE,,01122016>
-- DESCRIPTION:	<DESCRIPTION,,01122016>
---23/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0200_TRAINING_BOND_RECOVER]
@TRAN_ID AS NUMERIC(18,0),
@EMP_ID AS NUMERIC(18,0),
@TRAINING_APR_ID AS NUMERIC(18,0),
@RECOVER_AMOUNT AS  NUMERIC(18,2)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	IF ISNULL(@TRAN_ID,0) = 0 
		BEGIN
					IF EXISTS(SELECT 1 FROM T0200_TRAINING_BOND_RECOVER WITH (NOLOCK) WHERE TRAINING_APR_ID = @TRAINING_APR_ID AND  EMP_ID = @EMP_ID)
						BEGIN
							SELECT @TRAN_ID = TRAN_ID FROM T0200_TRAINING_BOND_RECOVER WITH (NOLOCK)
							WHERE TRAINING_APR_ID = @TRAINING_APR_ID AND  EMP_ID = @EMP_ID
							
							UPDATE T0200_TRAINING_BOND_RECOVER SET RECOVER_AMOUNT = @RECOVER_AMOUNT
							WHERE TRAINING_APR_ID = @TRAINING_APR_ID AND  EMP_ID = @EMP_ID
						END
					ELSE
						BEGIN
							SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0)+ 1 FROM T0200_TRAINING_BOND_RECOVER WITH (NOLOCK)
							INSERT INTO T0200_TRAINING_BOND_RECOVER(TRAN_ID,EMP_ID,TRAINING_APR_ID,RECOVER_AMOUNT)
							VALUES(@TRAN_ID,@EMP_ID,@TRAINING_APR_ID,@RECOVER_AMOUNT)	
						END						
		END	
	ELSE
		BEGIN
				IF EXISTS(SELECT 1 FROM T0200_TRAINING_BOND_RECOVER WITH (NOLOCK) WHERE TRAN_ID = @TRAN_ID)
						BEGIN
							UPDATE T0200_TRAINING_BOND_RECOVER SET RECOVER_AMOUNT = @RECOVER_AMOUNT,
							TRAINING_APR_ID = @TRAINING_APR_ID
							WHERE  TRAN_ID = @TRAN_ID AND EMP_ID = @EMP_ID	
						END
					ELSE
						BEGIN
							SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0)+ 1 FROM T0200_TRAINING_BOND_RECOVER WITH (NOLOCK)
							INSERT INTO T0200_TRAINING_BOND_RECOVER(TRAN_ID,EMP_ID,TRAINING_APR_ID,RECOVER_AMOUNT)
							VALUES(@TRAN_ID,@EMP_ID,@TRAINING_APR_ID,@RECOVER_AMOUNT)
						END
		END
		
	
END

