


-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,17082016>
-- DESCRIPTION:	<DESCRIPTION,,QUESTION EXIT ANALYSIS ADD/UPDATE/DELETE>
---02/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0200_QUESTION_EXIT_ANALYSIS_MASTER]
@QUEST_ID NUMERIC(18,0) OUTPUT,
@CMP_ID NUMERIC(18,0),
@QUESTION NVARCHAR(MAX),
@QUESTION_TYPE NUMERIC(18,0),
@QUESTION_OPTION NVARCHAR(MAX),
@DESIGN_IDS NVARCHAR(MAX),
@SORTINGNO NUMERIC(18,0),
@AUTO_ASSIGN TINYINT,
@TRAN_TYPE CHAR,
@Group_ID numeric(18,0) = 0  --Added by Jaina 05-06-2018
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


    -- Insert statements for procedure here
	IF @TRAN_TYPE = 'I'
		BEGIN
					IF EXISTS(SELECT 1 FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK) WHERE UPPER(QUESTION) = UPPER(@QUESTION) AND CMP_ID = @CMP_ID)
						BEGIN
								RAISERROR('@@THIS QUESTION ALREADY EXISTS@@', 16, 1)
								SET @QUEST_ID = 0
								RETURN
						END
					
					SELECT @QUEST_ID = ISNULL(MAX(QUEST_ID),0) + 1 FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK)
					INSERT INTO T0200_QUESTION_EXIT_ANALYSIS_MASTER(QUEST_ID,CMP_ID,QUESTION,QUESTION_TYPE,QUESTION_OPTIONS,STRDESIG_ID,SORTING_NO,AUTOASSIGN,Group_Id)
					VALUES(@QUEST_ID,@CMP_ID,@QUESTION,@QUESTION_TYPE,@QUESTION_OPTION,@DESIGN_IDS,@SORTINGNO,@AUTO_ASSIGN,@Group_Id)
					
						
		END
	ELSE IF @TRAN_TYPE = 'U'
		BEGIN
				--IF NOT EXISTS(SELECT 1 FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID)
				IF NOT EXISTS(SELECT 1 FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK) WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID AND UPPER(QUESTION) = UPPER(@QUESTION))
						BEGIN
								RAISERROR('@@THIS QUESTION NOT AVAILABLE FOR UPDATE@@', 16, 1)
								SET @QUEST_ID = 0
								RETURN
						END
						
				IF EXISTS (SELECT 1 FROM
							T0200_Question_Exit_Analysis_Master Q  WITH (NOLOCK) INNER JOIN
							T0200_Exit_Interview I WITH (NOLOCK) ON I.Question_Id = Q.Quest_ID
							WHERE Q.Cmp_Id=@Cmp_Id and Q.QUEST_ID = @QUEST_ID )
				BEGIN
					--Added by Jaina 17-06-2020 for designation update
					declare @Desig_Id varchar(max) = ''

					SELECT @Desig_Id = strDesig_ID FROM
							T0200_Question_Exit_Analysis_Master Q WITH (NOLOCK) INNER JOIN
							T0200_Exit_Interview I WITH (NOLOCK) ON I.Question_Id = Q.Quest_ID
							WHERE Q.Cmp_Id=@Cmp_Id and Q.QUEST_ID = @QUEST_ID
					if ( @Desig_Id = @DESIGN_IDS )
						begin
								RAISERROR('@@Question is assigned for feedback, Can''t Updated@@', 16, 1)
								SET @Group_Id = 0
								RETURN
						end
					else
						begin
								UPDATE T0200_QUESTION_EXIT_ANALYSIS_MASTER
								set STRDESIG_ID = @DESIGN_IDS
								WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID	
						end
					
				END
				UPDATE T0200_QUESTION_EXIT_ANALYSIS_MASTER
					SET QUESTION = @QUESTION,
					QUESTION_TYPE = @QUESTION_TYPE,
					QUESTION_OPTIONS =@QUESTION_OPTION, 
					SORTING_NO =@SORTINGNO,
					STRDESIG_ID = @DESIGN_IDS,
					AUTOASSIGN = @AUTO_ASSIGN,
					Group_Id = @Group_Id
				WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID	
							
						
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
				IF NOT EXISTS(SELECT 1 FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK) WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID)
						BEGIN
								RAISERROR('@@THIS QUESTION NOT AVAILABLE FOR DELETE@@', 16, 1)
								SET @QUEST_ID = 0
								RETURN
						END
				IF EXISTS(SELECT 1 FROM  T0200_EXIT_INTERVIEW WITH (NOLOCK) WHERE QUESTION_ID = @QUEST_ID)	
						BEGIN
						RAISERROR('@@Reference Exists, Can''t Deleted@@', 16, 1)
								SET @QUEST_ID = 0
								RETURN
						END
							
				DELETE FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WHERE QUEST_ID = @QUEST_ID AND CMP_ID = @CMP_ID
		END
		
END

