




--------------------------------------
-- ALTER BY : NILAY (WEEKLY OR DAILY BASIC EMPLOYE
-- ALTER DATE : 20-OCT-2010
-----------------------------------
---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---

CREATE PROCEDURE [dbo].[P0200_MONTHLY_SALARY_DELETE_DAILY]
	@SAL_TRAN_ID		NUMERIC ,
	@EMP_ID				NUMERIC,
	@CMP_ID				NUMERIC,
	@From_Date 	datetime,
	@to_date	Datetime,
	@ErrString	varchar(500) output
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	

	DELETE FROM T0210_PAYSLIP_DATA_DAILY	WHERE SAL_TRAN_ID = @SAL_TRAN_ID
	DELETE FROM T0210_MONTHLY_LOAN_PAYMENT WHERE SAL_TRAN_ID = @SAL_TRAN_ID 
	--DELETE FROM T0210_MONTHLY_CLAIM_PAYMENT WHERE SAL_TRAN_ID = @SAL_TRAN_ID
	exec SP_CALCULATE_CLAIM_TRANSACTION @Cmp_ID,@EMP_ID,@From_Date,0,@From_Date,@to_date,0,'D'
	DELETE FROM T0210_MONTHLY_AD_DETAIL_DAILY WHERE SAL_TRAN_ID = @SAL_TRAN_ID AND EMP_ID =@EMP_id 
	DELETE FROM T0210_MONTHLY_LEAVE_DETAIL WHERE SAL_TRAN_ID = @SAL_TRAN_ID AND EMP_ID =@EMP_id 
	DELETE FROM T0200_MONTHLY_SALARY_DAILY WHERE SAL_TRAN_ID = @SAL_TRAN_ID AND EMP_ID =@EMP_id 
	DELETE FROM t0100_Anual_bonus WHERE SAL_TRAN_ID = @SAL_TRAN_ID AND EMP_ID =@EMP_id 
	DELETE FROM T0210_MONTHLY_AD_DETAIL_DAILY WHERE isnull(SAL_TRAN_ID,0) = 0 AND EMP_ID =@EMP_id
	Delete from T0200_MONTHLY_SALARY_LEAVE where  sal_tran_ID=@SAL_TRAN_ID   AND EMP_ID =@EMP_id 

	
	if exists(Select emp_ID from T0160_late_Approval WITH (NOLOCK) where emp_id=@EMP_ID and Month_Date =@From_Date)
	  Begin
	    
			delete from T0160_late_Approval where emp_id=@EMP_ID  
			
	  End
	
	
	
RETURN




