



---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0200_MONTHLY_SALARY_LEAVE_DELETE]
	@L_SAL_TRAN_ID		NUMERIC ,
	@EMP_ID				NUMERIC,
	@CMP_ID				NUMERIC,
	@From_Date 	datetime,
	@to_date	Datetime,
	@ErrString	varchar(500) output
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	IF EXISTS(SELECT EMP_ID FROM  T0200_MONTHLY_SALARY_LEAVE WITH (NOLOCK) WHERE EMP_ID =@EMP_ID AND  L_Month_St_Date >= @To_Date )
		Begin
			Raiserror('Next Months salary Exists',16,2)
			return -1
		End
		
	
	DELETE FROM T0210_MONTHLY_AD_DETAIL WHERE L_SAL_TRAN_ID = @L_SAL_TRAN_ID AND EMP_ID =@EMP_id 
	DELETE FROM T0200_MONTHLY_SALARY_LEAVE WHERE L_SAL_TRAN_ID = @L_SAL_TRAN_ID AND EMP_ID =@EMP_id 
	
	RETURN




