


---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0210_MONTHLY_BOND_PAYMENT_INSERT]

	 @BOND_PAY_ID			NUMERIC OUTPUT
	,@BOND_APR_ID			NUMERIC
	,@CMP_ID				NUMERIC
	,@SAL_TRAN_ID			NUMERIC 
	,@BOND_PAY_AMOUNT		NUMERIC(18,2)
	,@BOND_PAY_COMMENTS		VARCHAR(250)
	,@BOND_PAYMENT_DATE		DATETIME
	,@PAY_TRAN_ID NUMERIC(18,0) = 0
	,@TEMP_BOND_TRAN_ID NUMERIC(18,2) = 0
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	DECLARE @EMP_CODE NUMERIC 
	DECLARE @EMP_ID NUMERIC 
	DECLARE @STR_EMP_CODE VARCHAR(20)
	DECLARE @FIX_CODE VARCHAR(4)


	
	IF @BOND_PAY_AMOUNT IS NULL
		SET @BOND_PAY_AMOUNT = 0
		
	
		
	IF @BOND_PAY_ID = 0 
		BEGIN
				
			IF @SAL_TRAN_ID > 0
				BEGIN
					IF NOT EXISTS (	SELECT BOND_PAY_ID  FROM T0210_MONTHLY_BOND_PAYMENT WITH (NOLOCK)
									WHERE BOND_PAYMENT_DATE = @BOND_PAYMENT_DATE AND CMP_ID = @CMP_ID 
									AND BOND_APR_ID=@BOND_APR_ID AND SAL_TRAN_ID = @SAL_TRAN_ID)
							BEGIN
							
										--SET @BOND_PAY_CODE = CAST(@BOND_PAY_ID AS VARCHAR(20))
										
										--IF ISNULL(@SAL_TRAN_ID,0) > 0 SET @BOND_PAYMENT_TYPE = ''
										
										SELECT @BOND_PAY_ID = ISNULL(MAX(BOND_PAY_ID),0) +1  
										FROM T0210_MONTHLY_BOND_PAYMENT WITH (NOLOCK)
										
										INSERT INTO T0210_MONTHLY_BOND_PAYMENT
										(
											BOND_PAY_ID,
											BOND_APR_ID,
											CMP_ID,
											SAL_TRAN_ID,
											BOND_PAY_AMOUNT,
											BOND_PAY_COMMENTS,
											BOND_PAYMENT_DATE
										)
										VALUES	
										(
											@BOND_PAY_ID,
											@BOND_APR_ID,
											@CMP_ID,
											@SAL_TRAN_ID,
											@BOND_PAY_AMOUNT,
											@BOND_PAY_COMMENTS,
											@BOND_PAYMENT_DATE
										)
							END
					ELSE
   						BEGIN					
   									UPDATE T0210_MONTHLY_BOND_PAYMENT 
   									
									SET BOND_PAY_AMOUNT = BOND_PAY_AMOUNT + @BOND_PAY_AMOUNT,
									BOND_PAY_COMMENTS = @BOND_PAY_COMMENTS,
									BOND_PAYMENT_DATE = @BOND_PAYMENT_DATE,
									SAL_TRAN_ID = @SAL_TRAN_ID
									WHERE BOND_APR_ID = @BOND_APR_ID AND CMP_ID = CMP_ID 
										AND SAL_TRAN_ID = @SAL_TRAN_ID
   						END		 
				END	
	       ELSE 
		       BEGIN
					IF NOT EXISTS (SELECT BOND_PAY_ID  FROM T0210_MONTHLY_BOND_PAYMENT WITH (NOLOCK) WHERE BOND_PAYMENT_DATE = @BOND_PAYMENT_DATE AND CMP_ID = @CMP_ID AND BOND_APR_ID=@BOND_APR_ID AND SAL_TRAN_ID = @SAL_TRAN_ID)
						BEGIN	
							--SET @BOND_PAY_CODE = CAST(@BOND_PAY_ID AS VARCHAR(20))
							
							--IF ISNULL(@SAL_TRAN_ID,0) > 0 SET @BOND_PAYMENT_TYPE = ''
							
							SELECT @BOND_PAY_ID = ISNULL(MAX(BOND_PAY_ID),0) +1  FROM T0210_MONTHLY_BOND_PAYMENT WITH (NOLOCK)
							
							INSERT INTO T0210_MONTHLY_BOND_PAYMENT
							(
								BOND_PAY_ID,
								BOND_APR_ID,
								CMP_ID,
								SAL_TRAN_ID,
								BOND_PAY_AMOUNT,
								BOND_PAY_COMMENTS,
								BOND_PAYMENT_DATE
							)
							VALUES	
							(
								@BOND_PAY_ID,
								@BOND_APR_ID,
								@CMP_ID,
								@SAL_TRAN_ID,
								@BOND_PAY_AMOUNT,
								@BOND_PAY_COMMENTS,
								@BOND_PAYMENT_DATE
							)
					
						END
					ELSE
						BEGIN
							UPDATE T0210_MONTHLY_BOND_PAYMENT 
							SET BOND_PAY_AMOUNT = BOND_PAY_AMOUNT + @BOND_PAY_AMOUNT,
							BOND_PAY_COMMENTS = @BOND_PAY_COMMENTS,
							BOND_PAYMENT_DATE = @BOND_PAYMENT_DATE,
							SAL_TRAN_ID = @SAL_TRAN_ID
							WHERE BOND_APR_ID = @BOND_APR_ID AND CMP_ID = CMP_ID 
							AND SAL_TRAN_ID = @SAL_TRAN_ID
						END
		        END
		END
	 ELSE
		BEGIN
							UPDATE T0210_MONTHLY_BOND_PAYMENT 
							SET BOND_PAY_AMOUNT = BOND_PAY_AMOUNT + @BOND_PAY_AMOUNT,
							BOND_PAY_COMMENTS = @BOND_PAY_COMMENTS,
							BOND_PAYMENT_DATE = @BOND_PAYMENT_DATE,
							SAL_TRAN_ID = @SAL_TRAN_ID
							WHERE BOND_PAY_ID = @BOND_PAY_ID AND CMP_ID = CMP_ID
		END
	RETURN



