
---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0210_MONTHLY_AD_DETAIL_TRIGGER_GPF]	
AS	
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	DECLARE @Cmp_ID AS NUMERIC
	DECLARE @Emp_Id AS NUMERIC
	DECLARE @For_Date AS DATETIME
	DECLARE @Sal_tran_id AS NUMERIC


	/*****************************
	******FOR GPF*******
	*****************************/	
	IF EXISTS(	SELECT 1 FROM #INSERTED INS INNER JOIN T0050_AD_MASTER AM WITH (NOLOCK) ON INS.AD_ID = AM.AD_ID AND INS.Cmp_ID=AM.CMP_ID
				WHERE	AM.AD_DEF_ID=14 AND INS.M_AD_Amount <> 0 )			
		BEGIN
			DECLARE @GPF_TRAN_ID NUMERIC(18,0);
			DECLARE @GPF_CREDIT NUMERIC(18,0);
			
			
			SELECT	@Cmp_ID=INS.Cmp_ID,@Emp_Id=INS.Emp_Id,@For_Date=INS.To_date,
					@Sal_tran_id=INS.Temp_Sal_Tran_ID,@GPF_CREDIT = isnull(ins.m_ad_amount,0)
			FROM	#INSERTED INS INNER JOIN T0050_AD_MASTER AM WITH (NOLOCK) ON INS.AD_ID = AM.AD_ID 
			WHERE	AM.AD_DEF_ID=14 
			
			SELECT	@GPF_TRAN_ID = TRAN_ID 
			FROM	T0140_EMP_GPF_TRANSACTION GPF WITH (NOLOCK)
			WHERE	GPF.CMP_ID=@Cmp_ID AND GPF.EMP_ID=@Emp_Id AND MONTH(GPF.FOR_DATE) = MONTH(@For_Date) 
					AND YEAR(GPF.FOR_DATE) = YEAR(@For_Date) AND GPF.GPF_CREDIT > 0 
			
			IF @GPF_TRAN_ID  IS NOT NULL
				BEGIN
					UPDATE	T0140_EMP_GPF_TRANSACTION 
					SET		GPF_CREDIT = ISNULL(GPF_CREDIT,0) + @GPF_CREDIT
					WHERE	TRAN_ID=@GPF_TRAN_ID
				END
			ELSE
				BEGIN
					SET @GPF_TRAN_ID = ISNULL((SELECT MAX(TRAN_ID) FROM T0140_EMP_GPF_TRANSACTION WITH (NOLOCK)), 0) +1
					INSERT	INTO T0140_EMP_GPF_TRANSACTION 
						(CMP_ID,TRAN_ID,EMP_ID,SAL_TRAN_ID,FOR_DATE,GPF_OPENING,GPF_CREDIT,GPF_DEBIT,GPF_CLOSING,SYSTEM_DATE)
					VALUES
						(@Cmp_ID,@GPF_TRAN_ID,@Emp_Id,@Sal_tran_id,@For_Date, 0,@GPF_CREDIT,0,0, GETDATE())
				END
			
			EXEC dbo.P0140_UPDATE_GPF_CLOSING @CMP_ID, @Emp_Id, @For_Date		
			
		END	

