
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0211_GET_SALARY_PROCESSING_STATUS]
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	DECLARE @SP_ID INT;
	SELECT @SP_ID=SPID FROM t0211_Salary_processing_status WITH (NOLOCK)
	
	IF @SP_ID IS NOT NULL AND EXISTS(SELECT 1 FROM master.dbo.sysprocesses WHERE spid=@SP_ID)
		BEGIN
			CREATE TABLE #PROC_INFO(EventType Varchar(32), [Parameters] Varchar(1024), EventInfo Varchar(Max)); 

			DECLARE @SQL VARCHAR(MAX);

			SET @SQL = 'DBCC INPUTBUFFER(' + CAST(@SP_ID AS VARCHAR(16)) +')'

			INSERT INTO #PROC_INFO
			EXEC (@SQL)

			
			IF EXISTS(SELECT 1 FROM #PROC_INFO WHERE EventInfo LIKE '%P0200_Pre_Salary%')
				BEGIN
					DECLARE @PROCESSED NUMERIC(9,2)
					SELECT @PROCESSED = (PROCESSED * 100) / TOTALCOUNT FROM t0211_Salary_processing_status WITH (NOLOCK) WHERE SPID=@SP_ID
					SELECT @PROCESSED
					RETURN;
				END
		END
	
	SELECT -1
	RETURN;
