


---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0220_INCENTIVE_PROCESS]
	  
	  @Emp_ID NUMERIC(18,0),
	  @Cmp_Id AS NUMERIC(18,0),
	  @Scheme_ID NUMERIC(18,0),
	  @Branch_ID NUMERIC(18,0),
	  @Desig_ID NUMERIC(18,0),
	  @Incentive_Amt NUMERIC(18,2),
	  @Additional_Amt NUMERIC(18,2),
	  @Deduction_Amt NUMERIC(18,2), -- ADDED ON 03022018
	  @Paid_Amt NUMERIC(18,2),
	  @Status CHAR(1),
	  @For_Date DATETIME,
	  @Login_ID AS NUMERIC(18,0),
	  @Tran_Type AS CHAR(1),
	  @where as VARCHAR(MAX) = null
	  
	 
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	--SET @EMP_ID=ISNULL(@EMP_ID,0)
	
	--IF @EMP_ID = 0
	--BEGIN
	--	--SET @EMP_ID = 0
	--	RAISERROR('@@ Emp_ID is Required @@',16,2)  
	--	Return  
	--END
	
	
		IF(@TRAN_TYPE='I')
			BEGIN
			
			IF NOT EXISTS(SELECT 1 FROM DBO.T0220_INCENTIVE_PROCESS WITH (NOLOCK) WHERE EMP_ID=@EMP_ID AND CMP_ID=@CMP_ID AND SCHEME_ID=@SCHEME_ID AND 
				BRANCH_ID=@BRANCH_ID AND DESIG_ID=@DESIG_ID AND FOR_DATE=@FOR_DATE)
				BEGIN
					INSERT INTO DBO.T0220_INCENTIVE_PROCESS
								(
									EMP_ID,
									CMP_ID,
									SCHEME_ID,
									BRANCH_ID,
									DESIG_ID,
									INCENTIVE_AMT,
									ADDITIONAL_AMT,
									DEDUCTION_AMT,
									PAID_AMT,
									STATUS,
									For_Date,
									LOGIN_ID,
									SYSTEM_DATE
								 )
								VALUES
								(	
									@EMP_ID,
									@CMP_ID,
									@SCHEME_ID,
									@BRANCH_ID,
									@DESIG_ID,
									@INCENTIVE_AMT,
									@ADDITIONAL_AMT,
									@DEDUCTION_AMT,
									@PAID_AMT,
									@STATUS,
									@For_Date,
									@LOGIN_ID,
									GETDATE()
								)
				END
			ELSE
				BEGIN
					DELETE FROM DBO.T0220_INCENTIVE_PROCESS WHERE EMP_ID=@EMP_ID AND CMP_ID=@CMP_ID AND SCHEME_ID=@SCHEME_ID AND 
								BRANCH_ID=@BRANCH_ID AND DESIG_ID=@DESIG_ID AND FOR_DATE=@FOR_DATE
								
					INSERT INTO DBO.T0220_INCENTIVE_PROCESS
							(
								EMP_ID,
								CMP_ID,
								SCHEME_ID,
								BRANCH_ID,
								DESIG_ID,
								INCENTIVE_AMT,
								ADDITIONAL_AMT,
								DEDUCTION_AMT,
								PAID_AMT,
								STATUS,
								For_Date,
								LOGIN_ID,
								SYSTEM_DATE
							 )
							VALUES
							(	
								@EMP_ID,
								@CMP_ID,
								@SCHEME_ID,
								@BRANCH_ID,
								@DESIG_ID,
								@INCENTIVE_AMT,
								@ADDITIONAL_AMT,
								@DEDUCTION_AMT,
								@PAID_AMT,
								@STATUS,
								@For_Date,
								@LOGIN_ID,
								GETDATE()
							)		
				END			
			END
	ELSE IF (@TRAN_TYPE='E')
		BEGIN
			DECLARE @STRQRY1 AS VARCHAR(MAX)
			
			IF (ISNULL(@WHERE,'')<>'' )
				BEGIN
				
					
					
					SELECT INCP.INC_TRAN_ID,CAST(E.ALPHA_EMP_CODE AS VARCHAR) AS ALPHA_EMP_CODE,EMP_FULL_NAME,B.BRANCH_NAME,B.BRANCH_ID
					,CONVERT(VARCHAR(3), INCP.FOR_DATE, 100) AS INC_MONTH,YEAR(INCP.FOR_DATE) AS INC_YEAR,INCP.FOR_DATE,
					ISNULL(INCP.INCENTIVE_AMT,0) AS INCENTIVE_AMT,ISNULL(INCP.ADDITIONAL_AMT,0) AS ADDITIONAL_AMT,ISNULL(INCP.DEDUCTION_AMT,0) AS DEDUCTION_AMT,(ISNULL(INCP.INCENTIVE_AMT,0) + ISNULL(INCP.ADDITIONAL_AMT,0) - ISNULL(INCP.DEDUCTION_AMT,0)) AS TOTAL_INCENTIVE_AMOUNT ,ISNULL(INCP.PAID_AMT,0) AS PAID_AMT,INCP.STATUS,
					E.EMP_LEFT,E.Dept_ID,E.SEGMENT_ID,E.VERTICAL_ID,E.SUBVERTICAL_ID,E.SUBBRANCH_ID,E.CAT_ID
					INTO #INCENTIVE_TBL
					FROM DBO.T0220_INCENTIVE_PROCESS INCP WITH (NOLOCK)
					INNER JOIN DBO.T0080_EMP_MASTER E WITH (NOLOCK) ON E.EMP_ID=INCP.EMP_ID
					INNER JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON INCP.BRANCH_ID=B.BRANCH_ID
					WHERE E.CMP_ID=@CMP_ID ORDER BY INCP.SYSTEM_DATE DESC
					
					
					SET @STRQRY1 = 'SELECT INC_TRAN_ID,ALPHA_EMP_CODE,EMP_FULL_NAME,BRANCH_NAME
					,INC_MONTH,INC_YEAR,FOR_DATE,
					INCENTIVE_AMT,ADDITIONAL_AMT,DEDUCTION_AMT,TOTAL_INCENTIVE_AMOUNT,PAID_AMT,STATUS,EMP_LEFT,BRANCH_ID,Dept_ID,SEGMENT_ID,VERTICAL_ID,SUBVERTICAL_ID,SUBBRANCH_ID,CAT_ID
					FROM '+ '#Incentive_tbl' +' 
					WHERE ' +@WHERE + ''
					
					EXEC (@STRQRY1)
					DROP TABLE #INCENTIVE_TBL
					
				END
				
				
	
			--ORDER BY E.ALPHA_EMP_CODE
			
		END
				
		
		
END

