


CREATE PROCEDURE [dbo].[P0250_SALARY_PUBLISH_IMPORT]
	   
	  @Emp_Code  as varchar(255)
	 ,@CMP_Id as numeric
	 ,@Month as numeric(5,0)
	 ,@Year as numeric(5,0)
	 ,@Emp_Full_Name  as varchar(250)
	 ,@Sal_Type varchar(12)
	 ,@Comments varchar(max)
	 ,@Log_Status Int = 0 Output
	 ,@Row_No as Int 
	 ,@Process_Type varchar(100)
	 ,@Allowance_Name varchar(100)
	 
	 
AS

        SET NOCOUNT ON 
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		SET ARITHABORT ON

BEGIN

	Declare @Emp_ID  as numeric(18,0)
	set @Emp_ID = 0
	
	IF @MONTH = 0
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'MONTH IS NOT PROPERLY INSERTED',0,'ENTER PROPER MONTH',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @YEAR = 0
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'YEAR IS NOT PROPERLY INSERTED',0,'ENTER PROPER YEAR',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @EMP_CODE = ''
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'ALPHA EMPLOYEE CODE IS NOT PROPERLY INSERTED',0,'ENTER PROPER ALPHA EMPLOYEE CODE',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @EMP_FULL_NAME = ''
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'EMPLOYEE FULL NAME IS NOT PROPERLY INSERTED',0,'ENTER PROPER EMPLOYEE FULL NAME',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @SAL_TYPE = ''
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'SALARY TYPE IS NOT PROPERLY INSERTED',0,'ENTER PROPER SALARY TYPE',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @Comments = ''
	BEGIN
		INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'COMMENTS IS NOT PROPERLY INSERTED',0,'ENTER PROPER COMMENTS',GETDATE(),'PUBLISH SALARY IMPORT',0)						
		SET @LOG_STATUS=1			
		RETURN
	END
	
	IF @SAL_TYPE='PAYMENT'
	BEGIN
		
		IF @PROCESS_TYPE=''
		BEGIN
				INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'IF SALARY TYPE IS PAYMENT THEN PROCESS TYPE IS REQUIRED',0,'ENTER PROCESS TYPE',GETDATE(),'PUBLISH SALARY IMPORT',0)						
				SET @LOG_STATUS=1			
				RETURN
		END
		ELSE IF @PROCESS_TYPE <> '' 
	    BEGIN
				IF @Process_Type='ALLOWANCE' AND @Allowance_Name=''
				BEGIN
					INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'ALLOWANCE NAME IS REQUIRED',0,'ENTER ALLOWANCE NAME',GETDATE(),'PUBLISH SALARY IMPORT',0)						
					SET @LOG_STATUS=1			
					RETURN
				END
	    END
	END
	
		
	IF NOT EXISTS (SELECT 1 FROM T0080_EMP_MASTER WITH (NOLOCK) WHERE ALPHA_EMP_CODE = @EMP_CODE AND CMP_ID = @CMP_ID)
	BEGIN	
			INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'EMPLOYEE CODE NOT EXISTS',0,'ENTER PROPER EMPLOYEE CODE',GETDATE(),'PUBLISH SALARY IMPORT',0)						
			SET @LOG_STATUS=1			
			RETURN	
	END
	
	
	IF @MONTH <> 0 AND @YEAR <> 0 AND @EMP_CODE <> '' AND @EMP_FULL_NAME <> '' AND @SAL_TYPE <> '' AND @COMMENTS <> ''
		BEGIN
			SELECT @EMP_ID = EMP_ID FROM T0080_EMP_MASTER WITH (NOLOCK) WHERE ALPHA_EMP_CODE = @EMP_CODE AND CMP_ID = @CMP_ID
			
			IF @EMP_ID <> 0
				BEGIN
					IF @SAL_TYPE='PAYMENT'
						BEGIN
							IF EXISTS(SELECT 1 FROM DBO.T0250_Payment_PUBLISH_ESS WITH (NOLOCK) WHERE EMP_ID= @EMP_ID AND CMP_ID =@CMP_ID AND MONTH = @MONTH AND YEAR=@YEAR)
								BEGIN
									UPDATE T0250_Payment_PUBLISH_ESS SET COMMENTS=@COMMENTS
									WHERE EMP_ID= @EMP_ID AND CMP_ID =@CMP_ID AND MONTH = @MONTH AND YEAR=@YEAR
								END
							ELSE
								BEGIN
									INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,@EMP_CODE,'RECORDS IS NOT PUBLISH',0,'RECORDS IS NOT PUBLISH',GETDATE(),'PUBLISH SALARY IMPORT',0)
									SET @LOG_STATUS=1			
									RETURN
								END
						END
					ELSE
						BEGIN
							IF EXISTS(SELECT 1 FROM DBO.T0250_SALARY_PUBLISH_ESS WITH (NOLOCK) WHERE EMP_ID= @EMP_ID AND CMP_ID =@CMP_ID AND MONTH = @MONTH AND YEAR=@YEAR)
								BEGIN
									UPDATE T0250_SALARY_PUBLISH_ESS SET COMMENTS=@COMMENTS
									WHERE EMP_ID= @EMP_ID AND CMP_ID =@CMP_ID AND MONTH = @MONTH AND YEAR=@YEAR
								END
							ELSE
								BEGIN
								
									INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,@EMP_CODE,'RECORDS IS NOT PUBLISH',0,'RECORDS IS NOT PUBLISH',GETDATE(),'PUBLISH SALARY IMPORT',0)
									SET @LOG_STATUS=1			
									RETURN
								END
						END
				END
		END
	ELSE
		BEGIN
		
			INSERT INTO DBO.T0080_IMPORT_LOG VALUES (@ROW_NO,@CMP_ID,0,'ENTER PUBLISH SALARY INFORMATION',0,'ENTER PROPER INFORMATION',GETDATE(),'PUBLISH SALARY IMPORT',0)
			SET @LOG_STATUS=1			
			RETURN	
			--RAISERROR('ENTER TOTAL MANDATORY INFORMATION',16,2)
		END
		
END

