
---22/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P9999_BULK_INSERT_DEVICE_INOUT_DETAIL]

AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


DECLARE @MAX_TRAN_ID as Decimal(12,0)
SELECT @MAX_TRAN_ID  = ISNULL(MAX(IO_Tran_ID),0)  FROM T9999_DEVICE_INOUT_DETAIL

if Exists(SELECT 1 FROM sys.identity_columns WHERE OBJECT_NAME(object_id) = 'T9999_DEVICE_INOUT_DETAIL')

	BEGIN
		INSERT INTO T9999_DEVICE_INOUT_DETAIL (Cmp_ID,Enroll_No,IO_DateTime,IP_Address,In_Out_flag)

		SELECT  ISNULL((SELECT Cmp_ID FROM T0080_EMP_MASTER AS E WITH (NOLOCK) WHERE E.Enroll_No= A.User_ID),1) as Cmp_ID ,A.[User_ID],A.[Punch_DateTime],A.[IP_Address],A.[IO_Flag]
		FROM TMP_DEVICE_IMPORT_DATA as A LEFT OUTER JOIN T9999_DEVICE_INOUT_DETAIL as B WITH (NOLOCK)
		ON A.User_ID = B.Enroll_No
		AND A.Punch_DateTime = B.IO_DateTime
		AND A.IP_ADDRESS= B.IP_ADDRESS
		WHERE ISNULL(B.Enroll_No,0)=0
		      And isnull(A.IP_ADDRESS,'') <> ''
	END

ELSE

	BEGIN

	INSERT INTO T9999_DEVICE_INOUT_DETAIL (IO_Tran_ID,Cmp_ID,Enroll_No,IO_DateTime,IP_Address,In_Out_flag)

	SELECT @MAX_TRAN_ID+ A.iSrNo AS TRAN_ID,
	ISNULL((SELECT Cmp_ID FROM T0080_EMP_MASTER AS E WITH (NOLOCK) WHERE E.Enroll_No= A.User_ID),1) as Cmp_ID
	,A.[User_ID],A.[Punch_DateTime],A.[IP_Address],A.[IO_Flag]
	FROM TMP_DEVICE_IMPORT_DATA as A LEFT OUTER JOIN T9999_DEVICE_INOUT_DETAIL as B WITH (NOLOCK)
	ON A.User_ID = B.Enroll_No
	AND A.Punch_DateTime = B.IO_DateTime
	AND A.IP_ADDRESS= B.IP_ADDRESS
	WHERE ISNULL(B.Enroll_No,0)=0
		  And isnull(A.IP_ADDRESS,'') <> ''
	END
	
	
	

