
---13/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[RPT_Production_Bonus_Register]
	 @Cmp_ID		numeric
	,@From_Date		datetime
	,@To_Date		datetime 
	,@Branch_ID		numeric   = 0
	,@Cat_ID		numeric  = 0
	,@Grd_ID		numeric = 0
	,@Type_ID		numeric  = 0
	,@Dept_ID		numeric  = 0
	,@Desig_ID		numeric = 0
	,@Emp_ID		numeric  = 0
	,@Constraint	varchar(max) = ''	 
	,@Payment_Mode	varchar(20) = ''
	,@PBranch_ID	varchar(max) = '0'
	,@Group_Name	integer = 4 
	,@Report_Type   integer = 0
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	if @Branch_ID = 0
		set @Branch_ID = null
	if @Cat_ID = 0
		set @Cat_ID = null
	if @Type_ID = 0
		set @Type_ID = null
	if @Dept_ID = 0
		set @Dept_ID = null
	if @Grd_ID = 0
		set @Grd_ID = null
	if @Emp_ID = 0
		set @Emp_ID = null
		
	If @Desig_ID = 0
		set @Desig_ID = null
	
	 CREATE TABLE #Emp_Cons 
	 (      
	   Emp_ID numeric ,     
	   Branch_ID numeric,
	   Increment_ID numeric    
	 )   
	 
	 EXEC SP_RPT_FILL_EMP_CONS  @Cmp_ID,@From_Date,@To_Date,@Branch_ID,@Cat_ID,@Grd_ID,@Type_ID,@Dept_ID,@Desig_ID ,@Emp_ID ,@constraint ,0 ,0 ,0,0,0,0,0,0,2,@PBranch_ID 
	
	DECLARE  @MONTH AS NUMERIC
	DECLARE  @YEAR AS NUMERIC
		     
	SET @MONTH = MONTH(@TO_DATE)
	SET @YEAR = YEAR(@TO_DATE)
	
	CREATE table #Temp_Production_Bonus
	(
		Emp_ID numeric(18, 0) Not Null,
		Cmp_ID numeric(18, 0) Not Null,
		W_Day  numeric(18,2),
		Basic_Pay NUMERIC(18,2),
		Present  NUMERIC(18,2),
		Holiday  numeric(18,2),
		Others	 numeric(18,0),
		Leave	 Numeric(18,2),
		Bonus	numeric(18,2),
		Prod_Bonus	numeric(18,2),
		Label_Name  VARCHAR(20)
		
	)	
	Create CLUSTERED INDEX ind_temp2 ON #Temp_Production_Bonus(Emp_ID)
	Create NONCLUSTERED INDEX ind_temp3 ON #Temp_Production_Bonus(Cmp_ID)
		
		
		INSERT INTO #TEMP_PRODUCTION_BONUS
		SELECT  E.EMP_ID,E.CMP_ID,MS.WORKING_DAYS,MS.BASIC_SALARY,MS.PRESENT_DAYS,(Ms.Weekoff_Days + MS.HOLIDAY_DAYS),0,
				(ISNULL(MS.TOTAL_LEAVE_DAYS,0) + ISNULL(MS.ABSENT_DAYS,0)),0,0,'PROD.BONUS'
		FROM 	#EMP_CONS EC INNER JOIN
				T0080_EMP_MASTER E WITH (NOLOCK) ON E.EMP_ID = EC.EMP_ID INNER JOIN
				T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON MS.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = MS.INCREMENT_ID
		WHERE	MONTH(MS.MONTH_END_DATE) = MONTH(@TO_DATE) AND YEAR(MS.MONTH_END_DATE) = YEAR(@TO_DATE)
				AND E.CMP_ID = @CMP_ID
	
		
		DECLARE @PRODUCTIONBONUS_AD_DEF_ID AS NUMERIC 	
		
		SET @PRODUCTIONBONUS_AD_DEF_ID=20
							
		UPDATE   T 						
		SET		BONUS = Q.AMOUNT				
		FROM	DBO.#TEMP_PRODUCTION_BONUS T 
				INNER JOIN (
							SELECT	DISTINCT AD_SORT_NAME ,PB.Amount_Perc AS AMOUNT,EC.Emp_ID
							FROM	T0050_AD_MASTER AD WITH (NOLOCK) INNER JOIN
									T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID AND MAD.CMP_ID = AD.CMP_ID LEFT JOIN
									T0190_PRODUCTION_BONUS_VARIABLE_IMPORT PB WITH (NOLOCK) ON PB.AD_ID = AD.AD_ID AND PB.CMP_ID = AD.CMP_ID INNER JOIN
									#Emp_Cons EC On Ec.Emp_ID = MAD.Emp_ID
							WHERE	PB.CMP_ID= @CMP_ID 
										AND PB.MONTH = @MONTH AND PB.YEAR = @YEAR
										AND AD_ACTIVE = 1 AND AD_FLAG = 'I' AND AD_NOT_EFFECT_SALARY = 0 
										AND AD_DEF_ID = @PRODUCTIONBONUS_AD_DEF_ID --AND MAD.EMP_ID = @EMP_ID	
							--GROUP BY  AD_SORT_NAME,EC.Emp_ID
						  )Q ON T.Emp_ID = Q.Emp_ID AND T.LABEL_NAME = 'PROD.BONUS' 
		
		UPDATE   T 						
		SET		PROD_BONUS = Q.AMOUNT
		FROM	DBO.#TEMP_PRODUCTION_BONUS T 
				INNER JOIN (
							SELECT	DISTINCT AD_SORT_NAME ,ISNULL(SUM(M_AD_AMOUNT),0) AS AMOUNT,EC.Emp_ID
							FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK) 
									INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID AND 
												MAD.CMP_ID = AD.CMP_ID
									INNER JOIN #Emp_Cons EC On Ec.Emp_ID = Mad.Emp_ID
							WHERE	MAD.CMP_ID= @CMP_ID 
										AND MONTH(MAD.TO_DATE) = @MONTH AND YEAR(MAD.TO_DATE) = @YEAR
										AND AD_ACTIVE = 1 AND AD_FLAG = 'I' AND AD_NOT_EFFECT_SALARY = 0 
										AND AD_DEF_ID = @PRODUCTIONBONUS_AD_DEF_ID --AND MAD.EMP_ID = @EMP_ID	
							GROUP BY EC.EMP_ID,AD_SORT_NAME,MAD.M_AD_CALCULATED_AMOUNT							
						  )Q ON T.Emp_ID = Q.Emp_ID AND T.LABEL_NAME = 'PROD.BONUS' 							
		
		
		SELECT  T.*,E.Alpha_Emp_Code,E.Emp_Full_Name
				,ISNULL(GM.GRD_ID,0) AS GRD_ID,ISNULL(ETM.[TYPE_ID],0) AS [TYPE_ID],
				 ETM.[Type_Name] as [Type_Name],DGM.Desig_Name,BM.Branch_Name,GM.Grd_Name,DM.Dept_Name
				,ISNULL(BM.BRANCH_ID,0) AS BRANCH_ID		
				,VERTICAL_NAME,SV.SUBVERTICAL_NAME			
				,ISNULL(VS.VERTICAL_ID,0) AS VERTICAL_ID
				,ISNULL(SV.SUBVERTICAL_ID,0) AS SUBVERTICAL_ID   
				,ISNULL(DGM.DESIG_ID,0) AS DESIG_ID		
				,DM.DEPT_CODE , CCM.CENTER_NAME , ISNULL(CCM.CENTER_ID,0) AS CENTER_ID , CCM.CENTER_CODE
				,CMP_NAME,CMP_ADDRESS,
				@FROM_DATE AS P_FROM_DATE,
				DM.DEPT_ID
		INTO	#TEMP_PRODUCTION_BONUS1
		FROM 	#TEMP_PRODUCTION_BONUS T Inner JOIN
				#EMP_CONS EC ON Ec.Emp_ID = T.Emp_ID INNER JOIN
				T0080_EMP_MASTER E WITH (NOLOCK) ON E.EMP_ID = EC.EMP_ID INNER JOIN
				T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON MS.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = MS.INCREMENT_ID INNER JOIN
				T0095_INCREMENT I WITH (NOLOCK) ON I.INCREMENT_ID = EC.INCREMENT_ID AND I.EMP_ID = EC.EMP_ID LEFT OUTER JOIN 
				T0040_DEPARTMENT_MASTER WITH (NOLOCK) ON I.DEPT_ID = T0040_DEPARTMENT_MASTER.DEPT_ID LEFT OUTER JOIN
				T0040_GRADE_MASTER GM WITH (NOLOCK) ON I.GRD_ID = GM.GRD_ID				LEFT OUTER JOIN
				T0040_TYPE_MASTER ETM WITH (NOLOCK) ON I.TYPE_ID = ETM.TYPE_ID			LEFT OUTER JOIN
				T0040_DESIGNATION_MASTER DGM WITH (NOLOCK) ON I.DESIG_ID = DGM.DESIG_ID LEFT OUTER JOIN
				T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON I.DEPT_ID = DM.DEPT_ID		INNER JOIN 
				T0030_BRANCH_MASTER BM WITH (NOLOCK) ON I.BRANCH_ID = BM.BRANCH_ID      LEFT OUTER JOIN 
				T0040_VERTICAL_SEGMENT VS WITH (NOLOCK) ON VS.VERTICAL_ID = I.VERTICAL_ID  LEFT OUTER JOIN 
				T0050_SUBVERTICAL SV WITH (NOLOCK) ON SV.SUBVERTICAL_ID = I.SUBVERTICAL_ID LEFT OUTER JOIN 
				T0040_COST_CENTER_MASTER CCM WITH (NOLOCK) ON CCM.CENTER_ID = I.CENTER_ID LEFT Outer JOIN
				T0010_COMPANY_MASTER CM WITH (NOLOCK) ON CM.CMP_ID = E.CMP_ID
		WHERE	MONTH(MS.MONTH_END_DATE) = MONTH(@TO_DATE) AND YEAR(MS.MONTH_END_DATE) = YEAR(@TO_DATE)
				AND E.CMP_ID = @CMP_ID
		ORDER BY EMP_CODE			
	
						
		
		SELECT * FROM #TEMP_PRODUCTION_BONUS1
		
		
		SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
				ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
				ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS,
				(ISNULL(SUM(TMP.PRESENT),0) + ISNULL(SUM(HOLIDAY),0)) AS TOTAL_DAYS
		FROM	DBO.#TEMP_PRODUCTION_BONUS1  AS TMP
		
			IF @GROUP_NAME = 0 
				BEGIN
				SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
						ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
						ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS,
						TMP.GRD_NAME AS GROUP_NAME,ISNULL(TMP.GRD_ID,0) AS GROUP_ID
				FROM	DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
				GROUP BY GRD_ID,GRD_NAME
				--ORDER BY ROW_ID,LABEL_NAME					
			END
			ELSE IF @GROUP_NAME = 1 
				BEGIN
					SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS,
							TMP.[TYPE_NAME] AS GROUP_NAME,TMP.[TYPE_ID] AS GROUP_ID
					FROM	DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY [TYPE_ID],[TYPE_NAME]
					--ORDER BY ROW_ID,LABEL_NAME	
				END	
			ELSE IF @GROUP_NAME = 2 
				BEGIN
					IF EXISTS(SELECT 1 FROM  #TEMP_PRODUCTION_BONUS1 WHERE ISNUMERIC(DEPT_CODE) >0)
						BEGIN						
							SELECT ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS,
							TMP.DEPT_CODE AS GROUP_NAME,CAST( CASE WHEN ISNUMERIC(TMP.DEPT_CODE) =1 THEN TMP.DEPT_CODE ELSE 0 END AS NUMERIC) AS GROUP_ID
							FROM DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
							GROUP BY DEPT_CODE
							--ORDER BY ROW_ID,LABEL_NAME			
						END
					ELSE
						BEGIN
							SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
									ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
									ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
									,TMP.DEPT_NAME AS GROUP_NAME,ISNULL(TMP.DEPT_ID,0) AS GROUP_ID
							FROM DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
							GROUP BY DEPT_ID,DEPT_NAME
							--ORDER BY ROW_ID,LABEL_NAME			
						END

				END
			ELSE IF @GROUP_NAME = 3 
				BEGIN
					SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
							,TMP.DESIG_NAME AS GROUP_NAME,ISNULL(TMP.DESIG_ID,0) AS GROUP_ID
					FROM	DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY DESIG_ID,DESIG_NAME
					--ORDER BY ROW_ID,LABEL_NAME	
				END
			ELSE IF @GROUP_NAME = 4 
				BEGIN
					SELECT  ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
							,TMP.BRANCH_NAME AS GROUP_NAME,ISNULL(TMP.BRANCH_ID,0) AS GROUP_ID
					FROM DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY BRANCH_ID,BRANCH_NAME
					--ORDER BY ROW_ID,LABEL_NAME	
				END
			ELSE IF @GROUP_NAME = 5 
				BEGIN
					SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
							,TMP.VERTICAL_NAME AS GROUP_NAME,ISNULL(TMP.VERTICAL_ID,0) AS GROUP_ID
					FROM	DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY VERTICAL_ID,VERTICAL_NAME
					--ORDER BY ROW_ID,LABEL_NAME	
				END
			ELSE IF @GROUP_NAME = 6 
				BEGIN
					SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
							,TMP.SUBVERTICAL_NAME AS GROUP_NAME,ISNULL(TMP.SUBVERTICAL_ID,0) AS GROUP_ID
					FROM DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY SUBVERTICAL_ID,SUBVERTICAL_NAME
					--ORDER BY ROW_ID,LABEL_NAME	
				END
			ELSE IF @GROUP_NAME = 9 
				BEGIN
					SELECT	ISNULL(SUM(TMP.BASIC_PAY),0) AS BASIC_PAY,ISNULL(SUM(TMP.PRESENT),0) AS PRESENT,
							ISNULL(SUM(HOLIDAY),0) AS HOLIDAY,ISNULL(SUM(LEAVE),0) AS LEAVE,
							ISNULL(SUM(BONUS),0) AS BONUS,ISNULL(SUM(PROD_BONUS),0) AS PROD_BONUS
							,TMP.CENTER_CODE AS GROUP_NAME,ISNULL(TMP.CENTER_ID,0) AS GROUP_ID
					FROM DBO.#TEMP_PRODUCTION_BONUS1  AS TMP 
					GROUP BY CENTER_ID,CENTER_CODE
					--ORDER BY ROW_ID,LABEL_NAME	
				END
				
		drop TABLE #TEMP_PRODUCTION_BONUS
		drop TABLE #TEMP_PRODUCTION_BONUS1
		
RETURN	
