
CREATE PROCEDURE [dbo].[RPT_TDS_CHALLAN]

@CMP_ID NUMERIC(18,0),
@MONTH NUMERIC(18,0),
@YEAR NUMERIC(18,0),
@CHALLAN_ID NUMERIC(18,0)

AS

	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET ARITHABORT ON
	
	DECLARE @FIN_FROM_DATE AS DATETIME
	DECLARE @FIN_TO_DATE AS DATETIME
	SELECT @FIN_FROM_DATE =  DBO.GET_YEAR_START_DATE(@YEAR,@MONTH,2)
	SELECT @FIN_TO_DATE =  DBO.GET_YEAR_END_DATE(@YEAR,@MONTH,2)
				
	SELECT     CHALLAN_ID, TDSC.CMP_ID, MONTH, YEAR, PAYMENT_DATE, TDSC.BANK_ID, BM.BANK_NAME, BM.BANK_BSR_CODE, PAID_BY, CHEQUE_NO, CIN_NO, CHEQUE_DATE, TAX_AMOUNT, ED_CESS, 
						  INTEREST_AMOUNT, PENALTY_AMOUNT, OTHER_AMOUNT, TOTAL_AMOUNT
						  ,CM.CMP_TAN_NO, CM.CMP_NAME , CM.CMP_ADDRESS, CM.CMP_PHONE , CM.CMP_PINCODE, BM.BANK_BRANCH_NAME,@FIN_FROM_DATE AS FIN_START_DATE,@FIN_TO_DATE AS FIN_END_DATE
						  ,dbo.F_Number_TO_Word(Total_Amount)TotAmt_Word
	FROM     T0220_TDS_CHALLAN TDSC WITH (NOLOCK)
			INNER JOIN T0010_COMPANY_MASTER CM WITH (NOLOCK) ON CM.CMP_ID = TDSC.CMP_ID
			LEFT OUTER JOIN T0040_BANK_MASTER BM WITH (NOLOCK) ON BM.BANK_ID = TDSC.BANK_ID
	WHERE YEAR = @YEAR AND MONTH = @MONTH AND TDSC.CMP_ID = @CMP_ID AND CHALLAN_ID = @CHALLAN_ID
	
	--WHERE Challan_Id = @Challan_Id
	
	--SELECT     Tran_Id, Challan_Id, Emp_Id, TDS_Amount, Ed_Cess
	--FROM         T0230_TDS_CHALLAN_DETAIL
	--WHERE Challan_Id = @Challan_Id
			
	
	
RETURN




