
-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,06/12/2016>
-- DESCRIPTION:	<DESCRIPTION,, SALARY REGISTER WITH NEW FORMAT.>
---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[RPT_SALARY_REGISTER]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	 @CMP_ID NUMERIC(18,0),
	 @FROM_DATE DATETIME,
	 @TO_DATE DATETIME,
	 @BRANCH_ID NUMERIC(18,0),
	 @CAT_ID NUMERIC(18,0) = 0,
	 @GRD_ID NUMERIC(18,0) = 0,
	 @TYPE_ID NUMERIC(18,0) = 0,
	 @DEPT_ID NUMERIC(18,0) = 0,
	 @DESIG_ID NUMERIC(18,0) = 0,
	 @EMP_ID NUMERIC(18,0) = 0,
	 @CONSTRAINT NVARCHAR(MAX)='',
	 @SAL_TYPE NUMERIC(18,0) = 0,
	 @SALARY_CYCLE_ID NUMERIC(18,0)=0,
	 @SEGMENT_ID NUMERIC(18,0)=0,
	 @VERTICAL_ID NUMERIC(18,0)=0,
	 @SUBVERTICAL_ID NUMERIC(18,0)=0,
	 @SUBBRANCH_ID NUMERIC(18,0)=0,
	 @PBRANCH_ID VARCHAR(MAX)= '0',   --changed by jimit 27012017
	 @Show_Hidden_Allowance  bit = 0   --Added by Jaina 16-05-2017
	,@Group_Name	integer = 0		----- Add jignesh Patel 25 10 2021 for Chiripal
	,@Summary_Option  Int = -1  --- Add by Jignesh Patel 30-Sep-2021---- For Chiripal (1  For Summary)
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON 
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET ARITHABORT ON

	------ Add by Jignesh Patel 04-10-2021---- For Chiripal (1  For Summary)
	--If Isnull(@Show_Hidden_Allowance,0) = 0
	--	Begin
	--		SET @Summary_Option =1
	--	ENd
	If Isnull(@Summary_Option,0)=8
	Begin
		SET @Summary_Option =0
	End
	Else
	Begin
		SET @Summary_Option =@Summary_Option+1
	ENd
	----------------- END --------------------

	set @Show_Hidden_Allowance = 0
	
	IF @SALARY_CYCLE_ID = 0
		SET @SALARY_CYCLE_ID = NULL		
	IF @SEGMENT_ID = 0 
		SET @SEGMENT_ID = NULL
	IF @VERTICAL_ID = 0 
		SET @VERTICAL_ID = NULL
	IF @SUBVERTICAL_ID = 0 
		SET @SUBVERTICAL_ID  = NULL
	IF @SUBBRANCH_ID = 0
		SET @SUBBRANCH_ID = NULL

	DROP INDEX IF EXISTS IX_EMP_CONS_EMPID ON tempdb.#EMP_CONS
	
	CREATE TABLE #EMP_CONS 
	 (      
		EMP_ID		 NUMERIC ,     
		BRANCH_ID	 NUMERIC,
		INCREMENT_ID NUMERIC
	 )      
	
	EXEC SP_RPT_FILL_EMP_CONS  @CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRD_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID ,@EMP_ID ,@CONSTRAINT ,0 ,0 ,0,0,0,0,0,0,0,0,0,0	
	
	IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_EMP_CONS_EMPID')
	begin
		CREATE INDEX IX_EMP_CONS_EMPID ON #EMP_CONS (EMP_ID);	
	end
	
	DECLARE @MONTH NUMERIC(18,0)
	DECLARE @YEAR NUMERIC(18,0)
	DECLARE @CUR_EMP_ID NUMERIC(18,0)
	DECLARE @CUR_SAL_TRAN_ID NUMERIC(18,0)
	DECLARE @CUR_ALPHA_EMP_CODE NVARCHAR(50)
	DECLARE @CUR_UANNO NVARCHAR(50)
	DECLARE @CUR_EMP_FULL_NAME NVARCHAR(250)
	DECLARE @CUR_DESIGNATION NVARCHAR(50)
	DECLARE @CUR_ESIC_NO NVARCHAR(20)
	
	SET @MONTH = MONTH(@TO_DATE)
	SET @YEAR = YEAR(@TO_DATE)
	
	CREATE TABLE #EMP_DETAILS
	(
		EMP_ID NUMERIC(18,0),
		SAL_TRAN_ID NUMERIC(18,0),
		UANNO	NVARCHAR(100),
		GROSS_SALARY NUMERIC(18,2),
		GROSS_DEDUCTION NUMERIC(18,2),
		PF_WAGES	NUMERIC(18,2),
		ESI_WAGES	NUMERIC(18,2),
		CTC NUMERIC(18,2),
		Sal_Cal_Day NUMERIC(18,2), --Mukti(06032017)		
		ESIC_NO     NVARCHAR(20)  --Added By Jimit 28122017
		
	)
	CREATE TABLE #WORKING_DETAILS
	(
		EMP_ID		NUMERIC(18,0),
		SAL_TRAN_ID NUMERIC(18,0),
		PARA_NAME	NVARCHAR(25),
		DAYS		NUMERIC(18,2),
		PARA_TYPE	TINYINT
		
	)
	CREATE TABLE #RATEOFWAGES
	(
		EMP_ID           NUMERIC(18,0),
		SAL_TRAN_ID      NUMERIC(18,0),
		ALLOWANCE_NAME   NVARCHAR(100),
		RATE_TYPE		 NVARCHAR(10),
		ALLOWANCE_AMOUNT NUMERIC(18,2),
		ALLOWANCE_TYPE	 CHAR(1)
		
	)


			
	DECLARE CUR_EMP CURSOR FOR
	SELECT	SG.EMP_ID ,SG.SAL_TRAN_ID,E.UAN_No,E.SIN_No 
	FROM	DBO.T0200_MONTHLY_SALARY SG WITH (NOLOCK)
			INNER JOIN T0080_EMP_MASTER E WITH (NOLOCK) ON SG.EMP_ID =E.EMP_ID 
			INNER JOIN #EMP_CONS EC ON E.EMP_ID = EC.EMP_ID 
	WHERE	SG.CMP_ID = @CMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH 
			AND YEAR(SG.MONTH_END_DATE) = @YEAR AND ISNULL(SG.IS_FNF,0)=0

	OPEN  CUR_EMP
	FETCH NEXT FROM CUR_EMP INTO @EMP_ID ,@CUR_SAL_TRAN_ID,@CUR_UANNO,@CUR_ESIC_NO
	WHILE @@FETCH_STATUS = 0
		BEGIN		
			INSERT	INTO #EMP_DETAILS(EMP_ID,SAL_TRAN_ID,UANNO,GROSS_SALARY,GROSS_DEDUCTION,CTC,Sal_Cal_Day,ESIC_NO)
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,@CUR_UANNO,GROSS_SALARY,TOTAL_DEDU_AMOUNT,NET_AMOUNT,Sal_Cal_Days,@CUR_ESIC_NO
			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK) 
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR 
							
							
			UPDATE	#EMP_DETAILS 
			SET		PF_WAGES = ISNULL(QRY.M_AD_Calculated_Amount,0) 
			FROM	(
					SELECT  MAD.M_AD_Calculated_Amount
					FROM	T0210_MONTHLY_AD_DETAIL  MAD WITH (NOLOCK)
							INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID
					WHERE	MAD.SAL_TRAN_ID = @CUR_SAL_TRAN_ID AND AD.AD_DEF_ID = 2 and MAD.M_AD_Amount > 0								
					)QRY
			WHERE 	#EMP_DETAILS.SAL_TRAN_ID = @CUR_SAL_TRAN_ID					
						
			UPDATE	#EMP_DETAILS 
			SET		ESI_WAGES = ISNULL(QRY.M_AD_Calculated_Amount,0) 
			FROM	(
					SELECT  MAD.M_AD_Calculated_Amount 
					FROM	T0210_MONTHLY_AD_DETAIL  MAD WITH (NOLOCK)
							INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID
					WHERE	MAD.SAL_TRAN_ID = @CUR_SAL_TRAN_ID AND AD.AD_DEF_ID = 3 and MAD.M_AD_Amount > 0
					)QRY					
			WHERE 	#EMP_DETAILS.SAL_TRAN_ID = @CUR_SAL_TRAN_ID
							
							
			INSERT	INTO #WORKING_DETAILS(EMP_ID,SAL_TRAN_ID,PARA_NAME,DAYS,PARA_TYPE)
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,'P',PRESENT_DAYS,1
			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK)
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR  
			
			UNION ALL
			
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,'WO',WEEKOFF_DAYS,1
			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK)
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR 
			
			UNION ALL 
			
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,'HO',Holiday_Days,1
			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK)
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR  
			
			UNION ALL
			
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,'AB',Absent_Days,1
			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK)
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR  
		
			UNION ALL
			
			SELECT	@EMP_ID ,@CUR_SAL_TRAN_ID,
			---'OT Hrs.', Isnull(M_OT_Hours,0) + Isnull(M_HO_OT_Hours,0) + Isnull(M_WO_OT_Hours,0) ,1
			'OT Hrs.', 
			case when is_Monthly_Salary = 1 then Isnull(OT_Hours,0)  else 0  end +    ---- Add by Jignesh Patel 09-08-2021
			Isnull(M_OT_Hours,0)+ Isnull(M_HO_OT_Hours,0) + Isnull(M_WO_OT_Hours,0) ,1

			FROM	DBO.T0200_MONTHLY_SALARY WITH (NOLOCK)
			WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR  
			
			
			--commented by Krushna for daily wages employee basic comes wrong 27-12-2018 
			----SALARY STRUCTURE 0712016
			--INSERT	INTO #RATEOFWAGES(EMP_ID,SAL_TRAN_ID,ALLOWANCE_NAME,RATE_TYPE,ALLOWANCE_AMOUNT,ALLOWANCE_TYPE)
			--SELECT	MS.Emp_ID,MS.Sal_Tran_ID,'Basic','AMT',MS.Basic_Salary,'I' from T0200_MONTHLY_SALARY MS 
			--WHERE	EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR
			
			INSERT	INTO #RATEOFWAGES(EMP_ID,SAL_TRAN_ID,ALLOWANCE_NAME,RATE_TYPE,ALLOWANCE_AMOUNT,ALLOWANCE_TYPE)
			SELECT	MS.Emp_ID,MS.Sal_Tran_ID,'Basic','AMT',I.Basic_Salary,'I'  
			from	T0200_MONTHLY_SALARY MS WITH (NOLOCK)
					INNER JOIN T0095_INCREMENT I WITH (NOLOCK) on MS.Increment_ID = I.Increment_ID
					INNER JOIN (
									SELECT	MAX(I1.INCREMENT_ID) AS INCREMENT_ID,I1.EMP_ID 
									FROM	T0095_INCREMENT I1  WITH (NOLOCK) 					
											INNER JOIN (
															SELECT	max(Increment_Effective_Date) as For_Date,Emp_ID
															from	T0095_INCREMENT WITH (NOLOCK)
															where	CMP_ID = @CMP_ID AND EMP_ID = @EMP_ID AND Increment_Effective_Date <= @TO_dATE
															and Increment_Type <> 'Transfer'
															GROUP BY EMP_ID		
														)INN_QRY ON INN_QRY.For_Date = I1.Increment_Effective_Date AND INN_QRY.Emp_ID = I1.Emp_ID
									GROUP BY I1.EMP_ID 
								)INN_QRY1 ON I.Emp_ID = INN_QRY1.Emp_ID AND I.Increment_ID = INN_QRY1.INCREMENT_ID
			WHERE	MS.EMP_ID = @EMP_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR  
				
			UNION
			
			SELECT	EE.EMP_ID,@CUR_SAL_TRAN_ID,AM.AD_SORT_NAME,E_AD_MODE, E_AD_AMOUNT ,E_AD_FLAG 
			FROM	T0100_EMP_EARN_DEDUCTION EE WITH (NOLOCK)
					INNER JOIN (
								SELECT	MAX(INCREMENT_ID) AS INCREMENT_ID,EED.EMP_ID 
								FROM	T0100_EMP_EARN_DEDUCTION EED WITH (NOLOCK)  
										INNER JOIN(
													SELECT	MAX(FOR_DATE)AS FOR_DATE,EED.EMP_ID 
													FROM	T0100_EMP_EARN_DEDUCTION EED WITH (NOLOCK)
													WHERE	CMP_ID = @CMP_ID AND EED.EMP_ID = @EMP_ID AND FOR_DATE <= @TO_dATE		
													GROUP BY EED.EMP_ID,EED.FOR_DATE
												  ) INN_QRY ON INN_QRY.FOR_DATE = EED.FOR_DATE AND  INN_QRY.EMP_ID = EED.EMP_ID
								WHERE	CMP_ID = @CMP_ID AND EED.EMP_ID = @EMP_ID AND EED.FOR_DATE <= @TO_dATE	
								GROUP BY EED.EMP_ID
								)QRY ON QRY.EMP_ID = EE.EMP_ID AND QRY.INCREMENT_ID =EE.INCREMENT_ID
					INNER JOIN T0050_AD_MASTER AM WITH (NOLOCK) ON AM.AD_ID = EE.AD_ID
			WHERE 	EE.E_AD_AMOUNT > 0	
					AND (CASE WHEN @SHOW_HIDDEN_ALLOWANCE = 0 AND am.Hide_In_Reports = 1  THEN 0 ELSE 1 END) = 1 --Added by Jaina 24-12-2016
					AND AM.AD_NOT_EFFECT_SALARY = 0 --added by Krushna 28-12-2018
				
			INSERT	INTO #WORKING_DETAILS(EMP_ID,SAL_TRAN_ID,PARA_NAME,DAYS,PARA_TYPE)
			SELECT	@EMP_ID,@CUR_SAL_TRAN_ID,LM.LEAVE_CODE,QRY.LEAVE_USED,2 
			FROM	T0040_LEAVE_MASTER LM WITH (NOLOCK)
					INNER JOIN (SELECT	EMP_ID,LEAVE_ID, SUM((ISNULL(LEAVE_USED,0) + ISNULL(COMPOFF_USED,0))) AS LEAVE_USED
								FROM	T0140_LEAVE_TRANSACTION LT	WITH (NOLOCK)
								WHERE	(FOR_DATE BETWEEN @FROM_DATE AND @TO_DATE) AND EMP_ID = @EMP_ID AND (ISNULL(LEAVE_USED,0) + ISNULL(COMPOFF_USED,0)) > 0
								GROUP BY LT.EMP_ID,LT.LEAVE_ID
								)QRY ON QRY.EMP_ID = @EMP_ID AND QRY.LEAVE_ID = LM.LEAVE_ID
			
			
			FETCH NEXT FROM CUR_EMP INTO @EMP_ID ,@CUR_SAL_TRAN_ID,@CUR_UANNO,@CUR_ESIC_NO
		END
	CLOSE CUR_EMP
	DEALLOCATE CUR_EMP

	----------- @Dept_Summary Add By Jignesh Patel 30-Sep-2021----------- For Chiripal
	If @Summary_Option = 0
	Begin
		SELECT * FROM #RATEOFWAGES
		SELECT * FROM #WORKING_DETAILS
		SELECT * FROM #EMP_DETAILS	
	END
		If @Summary_Option > 0
	Begin
		
	SET @Summary_Option =@Summary_Option-1
		
	Declare @sSql as Varchar(max)
	Declare @sSqlSummaryOn as Varchar(5000)

	Select @sSqlSummaryOn = Case When @Summary_Option= 0 then 'Grd_ID' 
							Else Case When @Summary_Option= 1 then 'Type_ID' 
							Else Case When @Summary_Option= 2 then 'Dept_ID' 
							Else Case When @Summary_Option= 3 then 'Desig_Id' 
							Else Case When @Summary_Option= 4 then 'Branch_ID' 
							Else Case When @Summary_Option= 5 then 'Vertical_ID' 
							Else Case When @Summary_Option= 6 then 'SubVertical_ID' 
							Else Case When @Summary_Option= 7 then 'subBranch_ID' 
							end end End end end End end end
   SET @sSql = 'SELECT 
	--RW.*,
	isnull(' + @sSqlSummaryOn +',0)  as EMP_ID, isnull( '+ @sSqlSummaryOn +',0) as SAL_TRAN_ID ,ALLOWANCE_NAME,RATE_TYPE,Sum(ALLOWANCE_AMOUNT) as ALLOWANCE_AMOUNT,ALLOWANCE_TYPE
	FROM #RATEOFWAGES AS RW
	 Inner Join (
	 SELECT EC.EMP_ID , I.' + @sSqlSummaryOn +'  from #EMP_CONS as EC INNER JOIN T0095_INCREMENT as I
     On I.Increment_ID = EC.INCREMENT_ID
	) as IC On RW.EMP_ID = IC.EMP_ID 
	GROUP BY '+ @sSqlSummaryOn +' ,ALLOWANCE_NAME,RATE_TYPE,ALLOWANCE_TYPE'

	exec(@sSql)
	
	SET @sSql= ''
	
	SET @sSql= 'SELECT  
	---WD.*,IC.Dept_ID 
	isnull(' + @sSqlSummaryOn +',0) as EMP_ID, isnull(' + @sSqlSummaryOn +',0) as SAL_TRAN_ID,PARA_NAME,Sum(DAYS) as Days,PARA_TYPE	
	FROM #WORKING_DETAILS as WD
	Inner Join (
	 SELECT EC.EMP_ID , I.' + @sSqlSummaryOn +'  from #EMP_CONS as EC INNER JOIN T0095_INCREMENT as I
     On I.Increment_ID = EC.INCREMENT_ID
	) as IC On WD.EMP_ID = IC.EMP_ID 
	Group By  ' + @sSqlSummaryOn +',PARA_NAME,PARA_TYPE'

	exec(@sSql)
	
	SET @sSql= ''
	
	SET @sSql= 'SELECT 
	---ED.*,IC.Dept_ID 
	isnull(' + @sSqlSummaryOn +',0) AS EMP_ID,isnull(' + @sSqlSummaryOn +',0) AS SAL_TRAN_ID,'''' AS UANNO,SUM(GROSS_SALARY) AS GROSS_SALARY,SUM(GROSS_DEDUCTION) AS GROSS_DEDUCTION
	,SUM(PF_WAGES) as PF_WAGES,	SUM(ESI_WAGES) as ESI_WAGES,SUM(CTC) AS CTC,SUM(Sal_Cal_Day) as Sal_Cal_Day,''''as ESIC_NO	
	FROM #EMP_DETAILS as ED
	Inner Join (
	 SELECT EC.EMP_ID , I.' + @sSqlSummaryOn +'  from #EMP_CONS as EC INNER JOIN T0095_INCREMENT as I
     On I.Increment_ID = EC.INCREMENT_ID
	) as IC On ED.EMP_ID = IC.EMP_ID 
	Group By ' + @sSqlSummaryOn +' '
		
	exec(@sSql)
	SET @sSql= ''

	END

	

END


