



---29/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_Claim_CLOSING_AS_ON_DATE]
	@CMP_ID		NUMERIC ,
	@EMP_ID		NUMERIC ,
    @Claim_Name varchar(20),
	@FOR_DATE	DATETIME = null
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
		if Isnull(@For_Date,'') = '' 
			begin
				select @For_Date = max(For_Date) From T0140_Claim_TRANSACTION  WITH (NOLOCK) where Emp_ID = @Emp_ID
			end
	

		SELECT Claim_Name,Claim_Issue,Claim_Return,Claim_CLOSING FROM T0140_Claim_TRANSACTION LT WITH (NOLOCK) INNER JOIN  
		( SELECT MAX(FOR_dATE) FOR_DATE , Claim_ID,EMP_ID FROM T0140_Claim_TRANSACTION WITH (NOLOCK)
			WHERE EMP_ID = @EMP_ID AND FOR_DATE <=FOR_DATE
		GROUP BY EMP_ID,Claim_ID) Q ON LT.EMP_ID = Q.EMP_ID AND LT.Claim_ID = Q.Claim_ID AND 
		LT.FOR_DATE = Q.FOR_DATE INNER JOIN T0040_Claim_MASTER LM WITH (NOLOCK) ON LT.Claim_ID = LM.Claim_ID
	RETURN




