

-- =============================================
-- AUTHOR:		NILESH PATEL
-- CREATE DATE: 16-06-2017
-- DESCRIPTION:	CALCULATE LATE MARK SLAB WISE  
---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---

-- =============================================
CREATE PROCEDURE [dbo].[SP_CALCULATE_LATE_DEDUCTION_PERCENTAGE]
	 @EMP_ID			 NUMERIC
	,@CMP_ID	     	 NUMERIC
	,@MONTH_ST_DATE		 DATETIME
	,@MONTH_END_DATE	 DATETIME
	,@INCREMENT_ID		 NUMERIC 
	,@STRWEEKOFF_DATE VARCHAR(MAX)=''
	,@STRHOLIDAY_DATE VARCHAR(MAX)=''
	,@RETURN_RECORD_SET	 NUMERIC =0
	,@RETURN_LATE_DATE_TABLE TINYINT = 0
	,@ABSENT_DATE_STRING	VARCHAR(MAX) =''
	,@SAL_TRAN_ID NUMERIC = 0
	,@tmp_Month_St_Date DATETIME
	,@tmp_Month_End_Date DATETIME
	
AS
BEGIN

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	DECLARE @IN_DATE			DATETIME
	DECLARE @SHIFT_ST_TIME		VARCHAR(10)
	DECLARE @SHIFT_ST_DATETIME	DATETIME
	DECLARE @VAR_SHIFT_ST_DATE	VARCHAR(20)
	DECLARE @EMP_LATE_LIMIT		VARCHAR(10)
	DECLARE @LATE_LIMIT_SEC		NUMERIC
	DECLARE @BRANCH_ID		    NUMERIC 
	DECLARE @EMP_LATE_MARK		INT
	DECLARE @LATE_DEDU_TYPE		VARCHAR(10)
	DECLARE @MONTH				NUMERIC
	DECLARE @VARMONTH			VARCHAR(10)
	DECLARE @LATE_WITH_LEAVE    NUMERIC(1,0)
	DECLARE @YEAR				NUMERIC
	DECLARE @SHIFT_ST_TIME_HALF_DAY 	VARCHAR(10)
	DECLARE @IS_HALF_DAY 	TINYINT
	DECLARE @ROUNDINGVALUE 	NUMERIC(18,2) 
	DECLARE @IS_LATE_CALC_ON_HO_WO TINYINT
	DECLARE @IS_LATEMARK AS TINYINT
	DECLARE @SHIFT_MAX_LATE_TIME DATETIME
	DECLARE @OUT_DATE DATETIME	
	DECLARE @SHIFT_END_TIME VARCHAR(10)
	DECLARE @VAR_SHIFT_END_DATE	VARCHAR(20)
	DECLARE @SHIFT_END_TIME_HALF_DAY VARCHAR(10)
	DECLARE @SHIFT_NAME VARCHAR(200)
	
	
	SET @MONTH	= MONTH(@MONTH_ST_DATE)
	SET @VARMONTH = @MONTH
	SET @VARMONTH = '#' + @VARMONTH + '#'
	SET @ROUNDINGVALUE = 0
	SET @YEAR	= YEAR(@MONTH_ST_DATE)
	SET @IS_LATEMARK = 0
	SET @SHIFT_NAME = ''
	
	DECLARE @LATE_MARK_SCENARIO NUMERIC(5,0)
	DECLARE @GEN_ID NUMERIC(5,0)
	DECLARE @ACTUAL_SHIFT_ST_TIME DATETIME
	DECLARE @ACTUAL_MIN_DIFF NUMERIC(18,0)
	DECLARE @LATE_ADJ_AGAIN_OT NUMERIC(18,0)
	DECLARE @IS_LATE_PERCENTAGE NUMERIC(1,0)
	DECLARE @IS_LATE_CALCULATE_ON NUMERIC(1,0)
	DECLARE @GROSS_SALARY NUMERIC(18,2)
	DECLARE @BASIC_SALARY NUMERIC(18,2)
	DECLARE @SAL_FIX_DAYS NUMERIC(18,2)
	DECLARE @Late_Limit NUMERIC(18,2)
	
	SET @LATE_MARK_SCENARIO = 0
	SET @ACTUAL_MIN_DIFF = 0
	SET @GEN_ID = 0
	SET @LATE_ADJ_AGAIN_OT = 0
	SET @IS_LATE_PERCENTAGE = 0
	SET @IS_LATE_CALCULATE_ON = 0
	SET @GROSS_SALARY = 0
	SET @BASIC_SALARY = 0
	SET @SAL_FIX_DAYS = 0
	SET @Late_Limit = 0
	
	SELECT	@EMP_LATE_MARK = ISNULL(EMP_LATE_MARK,0) ,
			@EMP_LATE_LIMIT = ISNULL(EMP_LATE_LIMIT,'00:00'),
			@BRANCH_ID =BRANCH_ID,
			@LATE_DEDU_TYPE = LATE_DEDU_TYPE,
			--@GROSS_SALARY = I.Gross_Salary,
			@BASIC_SALARY = I.Basic_Salary
	FROM	T0095_INCREMENT I WITH (NOLOCK)
	WHERE	I.EMP_ID = @EMP_ID AND INCREMENT_ID =@INCREMENT_ID	
	
	SELECT	@LATE_MARK_SCENARIO = ISNULL(LATE_MARK_SCENARIO,0),
			@GEN_ID = ISNULL(GEN_ID,0),
			@LATE_WITH_LEAVE = LATE_WITH_LEAVE,
			@IS_LATE_CALC_ON_HO_WO = IS_LATE_CALC_ON_HO_WO,
			@IS_LATEMARK = IS_LATE_MARK, 
			@ROUNDINGVALUE = ISNULL(EARLY_HOUR_UPPER_ROUNDING,0),
			@LATE_ADJ_AGAIN_OT = ISNULL(LATE_ADJ_AGAIN_OT,0),
			@IS_LATE_PERCENTAGE = ISNULL(IS_LATEMARK_PERCENTAGE,0),
			@SAL_FIX_DAYS = ISNULL(SAL_FIX_DAYS,0),
			@Late_Limit = dbo.F_Return_Sec(Late_Limit),
			@IS_LATE_CALCULATE_ON = ISNULL(IS_LATEMARK_CAL_ON,0)  
			-- 1 Calculate Basic 
			-- 2 Calculate on Gross
	FROM	T0040_GENERAL_SETTING G WITH (NOLOCK)
			INNER JOIN (
							SELECT	MAX(FOR_DATE) AS FOR_DATE 
							FROM	T0040_GENERAL_SETTING WITH (NOLOCK)    
							WHERE	CMP_ID = @CMP_ID AND FOR_DATE <=@MONTH_END_DATE AND BRANCH_ID=@BRANCH_ID
						)  G1 ON G.FOR_DATE=G1.FOR_DATE
	WHERE	CMP_ID = @CMP_ID AND BRANCH_ID =@BRANCH_ID 

	IF OBJECT_ID('tempdb..#Temp_AD') is not null
		drop TABLE #Temp_AD
	
	  SELECT E_AD_AMOUNT,AD_NOT_EFFECT_SALARY,PARTOFCTC
			INTO #Temp_AD
		FROM (
		SELECT EED.AD_ID,
			 CASE WHEN QRY1.INCREMENT_ID >= EED.INCREMENT_ID /*QRY1.FOR_DATE > EED.FOR_DATE*/ THEN
				CASE WHEN QRY1.E_AD_PERCENTAGE IS NULL THEN EED.E_AD_PERCENTAGE ELSE QRY1.E_AD_PERCENTAGE END 
			 ELSE
				EED.E_AD_PERCENTAGE END AS E_AD_PERCENTAGE,
			 CASE WHEN QRY1.INCREMENT_ID >= EED.INCREMENT_ID /*QRY1.FOR_DATE > EED.FOR_DATE*/ THEN
				CASE WHEN QRY1.E_AD_AMOUNT IS NULL THEN EED.E_AD_AMOUNT ELSE QRY1.E_AD_AMOUNT END 
			 ELSE
				EED.E_AD_AMOUNT END AS E_AD_AMOUNT,
			E_AD_FLAG,E_AD_MAX_LIMIT ,AD_CALCULATE_ON ,AD_DEF_ID ,                    
			ISNULL(AD_NOT_EFFECT_ON_PT,0) AS AD_NOT_EFFECT_ON_PT,
			ISNULL(AD_NOT_EFFECT_SALARY,0) AS AD_NOT_EFFECT_SALARY,ISNULL(AD_EFFECT_ON_OT,0) AS AD_EFFECT_ON_OT,
			ISNULL(AD_EFFECT_ON_EXTRA_DAY,0) AS AD_EFFECT_ON_EXTRA_DAY,
			AD_NAME,ISNULL(AD_EFFECT_ON_LATE,0) AS AD_EFFECT_ON_LATE,
			ISNULL(AD_EFFECT_MONTH,'') AS AD_EFFECT_MONTH,
			ISNULL(AD_CAL_TYPE,'') AS AD_CAL_TYPE,ISNULL(AD_EFFECT_FROM,'') AS AD_EFFECT_FROM,
			ISNULL(ADM.AD_NOT_EFFECT_ON_LWP,0) AS AD_NOT_EFFECT_ON_LWP,
			ISNULL(ADM.ALLOWANCE_TYPE,'A') AS ALLOWANCE_TYPE, 
			ISNULL(ADM.AUTO_PAID,0) AS AUTOPAID,
			ADM.AD_LEVEL,ADM.IS_ROUNDING,
			ISNULL(ADM.AD_PART_OF_CTC,0) AS PARTOFCTC
		FROM DBO.T0100_EMP_EARN_DEDUCTION EED WITH (NOLOCK) INNER JOIN                    
			   DBO.T0050_AD_MASTER ADM WITH (NOLOCK) ON EED.AD_ID = ADM.AD_ID   LEFT OUTER JOIN
				( SELECT EEDR.EMP_ID, EEDR.AD_ID, EEDR.FOR_DATE, EEDR.E_AD_AMOUNT,EEDR.E_AD_PERCENTAGE,EEDR.ENTRY_TYPE ,EEDR.INCREMENT_ID
					FROM T0110_EMP_EARN_DEDUCTION_REVISED EEDR WITH (NOLOCK) INNER JOIN
					( SELECT MAX(FOR_DATE) FOR_DATE, AD_ID FROM T0110_EMP_EARN_DEDUCTION_REVISED WITH (NOLOCK)
						WHERE EMP_ID = @EMP_ID AND FOR_DATE <= @MONTH_END_DATE
					 GROUP BY AD_ID )QRY ON EEDR.FOR_DATE = QRY.FOR_DATE AND EEDR.AD_ID = QRY.AD_ID 
				) QRY1 ON EED.AD_ID = QRY1.AD_ID AND EED.EMP_ID = QRY1.EMP_ID  AND QRY1.FOR_DATE>=EED.FOR_DATE                
		WHERE EED.EMP_ID = @EMP_ID AND EED.INCREMENT_ID = @INCREMENT_ID AND ADM.AD_ACTIVE = 1
				AND CASE WHEN QRY1.ENTRY_TYPE IS NULL THEN '' ELSE QRY1.ENTRY_TYPE END <> 'D' 
				AND EED.E_AD_FLAG = 'I' AND Isnull(ADM.AD_NOT_EFFECT_SALARY,0) = 0 
		UNION 
		
		SELECT EED.AD_ID,E_AD_PERCENTAGE,E_AD_AMOUNT,E_AD_FLAG,E_AD_MAX_LIMIT ,AD_CALCULATE_ON ,AD_DEF_ID ,                    
			ISNULL(AD_NOT_EFFECT_ON_PT,0) AS AD_NOT_EFFECT_ON_PT,
			ISNULL(AD_NOT_EFFECT_SALARY,0) AS AD_NOT_EFFECT_SALARY,
			ISNULL(AD_EFFECT_ON_OT,0) AS AD_EFFECT_ON_OT,
			ISNULL(AD_EFFECT_ON_EXTRA_DAY,0) AS AD_EFFECT_ON_EXTRA_DAY
			,AD_NAME,ISNULL(AD_EFFECT_ON_LATE,0) AS AD_EFFECT_ON_LATE ,ISNULL(AD_EFFECT_MONTH,'') AS AD_EFFECT_MONTH,
			ISNULL(AD_CAL_TYPE,'') AS AD_CAL_TYPE,ISNULL(AD_EFFECT_FROM,'') AS AD_EFFECT_FROM,
			ISNULL(ADM.AD_NOT_EFFECT_ON_LWP,0) AS AD_NOT_EFFECT_ON_LWP,
			ISNULL(ADM.ALLOWANCE_TYPE,'A') AS ALLOWANCE_TYPE, 
			ISNULL(ADM.AUTO_PAID,0) AS AUTOPAID,
			ADM.AD_LEVEL,ADM.IS_ROUNDING,
			ISNULL(ADM.AD_PART_OF_CTC,0) AS PARTOFCTC
		FROM DBO.T0110_EMP_EARN_DEDUCTION_REVISED EED WITH (NOLOCK) INNER JOIN  
			( SELECT MAX(FOR_DATE) FOR_DATE, AD_ID FROM T0110_EMP_EARN_DEDUCTION_REVISED WITH (NOLOCK)
				WHERE EMP_ID  = @EMP_ID AND FOR_DATE <= @MONTH_END_DATE 
				GROUP BY AD_ID )QRY ON EED.FOR_DATE = QRY.FOR_DATE AND EED.AD_ID = QRY.AD_ID                   
		   INNER JOIN DBO.T0050_AD_MASTER ADM WITH (NOLOCK) ON EED.AD_ID = ADM.AD_ID                     
		WHERE EMP_ID = @EMP_ID 
				AND ADM.AD_ACTIVE = 1
				AND EED.ENTRY_TYPE = 'A'
				AND EED.INCREMENT_ID = @INCREMENT_ID
				and EED.E_AD_FLAG = 'I' AND Isnull(ADM.AD_NOT_EFFECT_SALARY,0) = 0
		) QRY
	
	

	IF @IS_LATE_CALCULATE_ON = 2 
		BEGIN
			Select @GROSS_SALARY = SUM(E_AD_AMOUNT) + @BASIC_SALARY From #Temp_AD Where Isnull(AD_NOT_EFFECT_SALARY,0) = 0
			if isnull(@GROSS_SALARY,0) = 0
				set @GROSS_SALARY = @BASIC_SALARY -- Add by Deepal base on issue resolved in the Genus (#19474) 11112021
		END
	
	IF @IS_LATE_CALCULATE_ON = 3 
		BEGIN
			Select @GROSS_SALARY = SUM(E_AD_AMOUNT) + @BASIC_SALARY From #Temp_AD Where Isnull(PARTOFCTC,0) = 1
		END
	
		
	
	IF OBJECT_ID('TEMPDB.DBO.#ABSENT_DATES') IS NOT NULL
		DROP TABLE #ABSENT_DATES
	
	CREATE TABLE #ABSENT_DATES  
	(
		ABSENT_DATE DATETIME
	)
	
	IF @ABSENT_DATE_STRING <> ''
		BEGIN
			INSERT INTO #ABSENT_DATES(ABSENT_DATE)
			SELECT DATA FROM DBO.SPLIT(@ABSENT_DATE_STRING,'#')
		END
	
	
	SELECT @LATE_LIMIT_SEC	= DBO.F_RETURN_SEC(@EMP_LATE_LIMIT)
   
    IF OBJECT_ID('TEMPDB.DBO.#LATE_MARK_SLAB') IS NOT NULL
		DROP TABLE #LATE_MARK_SLAB
    
    CREATE TABLE #LATE_MARK_SLAB
    (
		CMP_ID NUMERIC(18,0),
		EMP_ID NUMERIC(18,0),
		TRANS_ID NUMERIC(18,0),
		BRANCH_ID NUMERIC(18,0),
		FROM_MIN NUMERIC(18,0),
		TO_MIN NUMERIC(18,0),
		EXMPT_COUNT NUMERIC(18,0),
		DEDUCTION NUMERIC(18,2),
		DEDUCTION_TYPE VARCHAR(100),
		GEN_ID NUMERIC(18,0),
		CURR_COUNT NUMERIC(18,0),
		ONE_TIME_EXEMPTION NUMERIC(2,0),
		Total_Deduct_Days Numeric(18,2),
		GROUP_FLAG BIT
    )
    
    IF OBJECT_ID ('TEMPDB.DBO.#LATE_MARK_TRANSACTION') IS NOT NULL
		DROP TABLE 	#LATE_MARK_TRANSACTION
		
	CREATE TABLE #LATE_MARK_TRANSACTION
	(
		CMP_ID NUMERIC(18,0),
		EMP_ID NUMERIC(18,0),
		FOR_DATE DATETIME,
		LATE_MIN VARCHAR(50),
		LATE_CALC_ON_PERCENT NUMERIC(5,2),
		LATE_CALC_ON_AMT NUMERIC(18,2),
		LATE_AMOUNT NUMERIC(18,2),
		LATE_SEC NUMERIC(18,0),
		LATE_LIMIT VARCHAR(50),
		SHIFT_ID NUMERIC(18,0),
		SHIFT_NAME VARCHAR(200),
		IN_TIME DATETIME
	)
	
	DECLARE @LATE_CALC_ON_PERCENT NUMERIC(5,2)
	SET @LATE_CALC_ON_PERCENT = 0
	
    IF @LATE_MARK_SCENARIO = 2
		BEGIN
			 INSERT INTO #LATE_MARK_SLAB(CMP_ID,EMP_ID,TRANS_ID,BRANCH_ID,FROM_MIN,TO_MIN,EXMPT_COUNT,DEDUCTION,DEDUCTION_TYPE,GEN_ID,CURR_COUNT,ONE_TIME_EXEMPTION,Total_Deduct_Days,GROUP_FLAG)
			 SELECT @CMP_ID,@EMP_ID,TRANS_ID,@BRANCH_ID,FROM_MIN,TO_MIN,EXEMPTION_COUNT,DEDUCTION,DEDUCTION_TYPE,GEN_ID,0,ONE_TIME_EXEMPTION,0,0
			 FROM T0050_GENERAL_LATEMARK_SLAB WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND GEN_ID = @GEN_ID 
		END

	IF  @EMP_LATE_MARK = 1
		BEGIN
		
			DECLARE @HALFDAYDATE VARCHAR(500)								
			EXEC GET_HALFDAY_DATE @CMP_ID,@EMP_ID,@MONTH_ST_DATE,@MONTH_END_DATE,0,@HALFDAYDATE OUTPUT
			
			DECLARE @FOR_DATECURR	DATETIME	
			SET @FOR_DATECURR = NULL
			
			DECLARE @IS_CANCEL_LATE_IN TINYINT
			DECLARE @DIFFERNCE_ROUNDING_LATE_SEC NUMERIC
			DECLARE @SHIFT_ID NUMERIC(18,0);	
			
			DECLARE CURLMARK CURSOR FOR
			SELECT	MIN(CAST(CAST(IN_TIME AS VARCHAR(11)) + ' ' + DBO.F_RETURN_HHMM(IN_TIME) AS DATETIME)),
					MAX(CAST(CAST(OUT_TIME AS VARCHAR(11)) + ' ' + DBO.F_RETURN_HHMM(OUT_TIME) AS DATETIME)),
					EI.FOR_DATE 
			FROM	DBO.T0150_EMP_INOUT_RECORD EI WITH (NOLOCK)	
					LEFT OUTER JOIN #ABSENT_DATES AD ON EI.FOR_DATE = AD.ABSENT_DATE
			WHERE	EMP_ID =@EMP_ID AND FOR_DATE>=@MONTH_ST_DATE AND FOR_DATE<=@MONTH_END_DATE  
					AND (ISNULL(IS_CANCEL_LATE_IN,0) =0 OR ISNULL(IS_CANCEL_LATE_IN,0) = 1)			
					AND Chk_By_Superior = 0
					AND ABSENT_DATE IS NULL 
			GROUP BY FOR_DATE	
			OPEN  CURLMARK
			FETCH NEXT FROM CURLMARK INTO @IN_DATE,@OUT_DATE,@FOR_DATECURR
			WHILE @@FETCH_STATUS = 0
				BEGIN
					
					SET @SHIFT_ID = NULL;
					SET @SHIFT_ID = DBO.FN_GET_SHIFT_FROM_MONTHLY_ROTATION(@CMP_ID, @EMP_ID, @IN_DATE);
					
					
					SELECT	@SHIFT_ST_TIME=SM.SHIFT_ST_TIME,
							@SHIFT_END_TIME=SM.SHIFT_END_TIME,
							@IS_HALF_DAY=ISNULL(SM.IS_HALF_DAY,0),
							@SHIFT_ST_TIME_HALF_DAY = ISNULL(SM.HALF_ST_TIME,'00:00'),
							@SHIFT_END_TIME_HALF_DAY = ISNULL(SM.HALF_END_TIME,'00:00'),
							@SHIFT_NAME = SM.Shift_Name
					FROM	T0040_SHIFT_MASTER SM WITH (NOLOCK)
					WHERE	SM.CMP_ID=@CMP_ID AND SM.SHIFT_ID=@SHIFT_ID
					
					SET @VAR_SHIFT_ST_DATE = CAST(@IN_DATE AS VARCHAR(11)) + ' '  + @SHIFT_ST_TIME  
					SET @VAR_SHIFT_END_DATE = CAST(@OUT_DATE AS VARCHAR(11)) + ' '  + @SHIFT_END_TIME
					
					SET @SHIFT_ST_DATETIME = CAST(@VAR_SHIFT_ST_DATE AS DATETIME)
					SET @SHIFT_ST_DATETIME = DATEADD(S,@LATE_LIMIT_SEC,@SHIFT_ST_DATETIME)
					
					
					IF @IS_LATEMARK = 1
						BEGIN
							
							IF @IS_LATE_CALC_ON_HO_WO = 0									
								BEGIN
									IF CHARINDEX(CAST(@IN_DATE AS VARCHAR(11)),@STRWEEKOFF_DATE,0) <> 0 OR CHARINDEX(CAST(@IN_DATE AS VARCHAR(11)),@STRHOLIDAY_DATE,0) <> 0 
										SET @IN_DATE = @SHIFT_ST_DATETIME
								END
								
										SET		@IS_CANCEL_LATE_IN = 0
										SELECT	TOP 1 @IS_CANCEL_LATE_IN=ISNULL(IS_CANCEL_LATE_IN,0)
										FROM	DBO.T0150_EMP_INOUT_RECORD WITH (NOLOCK)
										WHERE	EMP_ID =@EMP_ID AND FOR_DATE = CONVERT(VARCHAR(11),@IN_DATE,106)
												--AND ISNULL(LATE_CALC_NOT_APP,0)=0 AND CHK_BY_SUPERIOR <> 0 -- CHANGED BY RAMIZ ON 04/03/2016 FROM CHK_BY_SUPERIOR = 1 TO CHK_BY_SUPERIOR <> 0 AS NOW CHK_BY_SUPERIOR = 2 IS ALSO COMING
												AND ((CHK_BY_SUPERIOR = 2 AND REASON = '' ) OR (CHK_BY_SUPERIOR <> 2 AND REASON <> '' ))
												AND CHK_BY_SUPERIOR > 0
										ORDER BY IS_CANCEL_LATE_IN DESC

																				
										IF(CHARINDEX(CONVERT(NVARCHAR(11),@IN_DATE,109),@HALFDAYDATE) > 0) 
											BEGIN
												IF @IS_HALF_DAY = 1
													BEGIN
														SET @VAR_SHIFT_ST_DATE = CAST(@IN_DATE AS VARCHAR(11)) + ' '  + @SHIFT_ST_TIME_HALF_DAY
														SET @VAR_SHIFT_END_DATE = CAST(@OUT_DATE AS VARCHAR(11)) + ' '  + @SHIFT_END_TIME_HALF_DAY	
													END
												ELSE
													BEGIN
														SET @VAR_SHIFT_ST_DATE = CAST(@IN_DATE AS VARCHAR(11)) + ' '  + @SHIFT_ST_TIME
														SET @VAR_SHIFT_END_DATE = CAST(@OUT_DATE AS VARCHAR(11)) + ' '  + @SHIFT_END_TIME	
													END
											END
										ELSE
											BEGIN
												SET @VAR_SHIFT_ST_DATE = CAST(@IN_DATE AS VARCHAR(11)) + ' '  + @SHIFT_ST_TIME
												SET @VAR_SHIFT_END_DATE = CAST(@OUT_DATE AS VARCHAR(11)) + ' '  + @SHIFT_END_TIME	
											END	
											
										SET @SHIFT_ST_DATETIME = CAST(@VAR_SHIFT_ST_DATE AS DATETIME)
										SET @ACTUAL_SHIFT_ST_TIME = @SHIFT_ST_DATETIME
										SET @SHIFT_ST_DATETIME = DATEADD(S,@LATE_LIMIT_SEC,@SHIFT_ST_DATETIME)
										
										
										DECLARE @IS_HALF_DAY_LEAVE TINYINT
										DECLARE @IS_FULL_DAY_LEAVE TINYINT
										
										SET @IS_HALF_DAY_LEAVE = 0
										SET @IS_FULL_DAY_LEAVE = 0
										
										DECLARE @FR_DT AS DATETIME
										SET @FR_DT = CAST(CONVERT(NVARCHAR(11),@IN_DATE,106) + ' 00:00:00' AS DATETIME)
										
										IF EXISTS(
													SELECT	LA.LEAVE_APPROVAL_ID 
													FROM	T0120_LEAVE_APPROVAL LA WITH (NOLOCK) INNER JOIN T0130_LEAVE_APPROVAL_DETAIL LAD WITH (NOLOCK) ON LA.LEAVE_APPROVAL_ID = LAD.LEAVE_APPROVAL_ID
													WHERE	EMP_ID = @EMP_ID AND LEAVE_ASSIGN_AS = 'FIRST HALF' 
															AND (
																	ISNULL(HALF_LEAVE_DATE,TO_DATE) = @FR_DT OR 
																	CASE WHEN HALF_LEAVE_DATE = '01-JAN-1900' 
																		THEN TO_DATE 
																	ELSE 
																		HALF_LEAVE_DATE 
																	END = @FR_DT 
												 )AND APPROVAL_STATUS = 'A')
										BEGIN	
											SET @IS_HALF_DAY_LEAVE = 1		
										END
										
										IF EXISTS(
													SELECT	LA.LEAVE_APPROVAL_ID 
													FROM	T0120_LEAVE_APPROVAL LA WITH (NOLOCK) INNER JOIN T0130_LEAVE_APPROVAL_DETAIL LAD WITH (NOLOCK) ON LA.LEAVE_APPROVAL_ID = LAD.LEAVE_APPROVAL_ID
													WHERE	EMP_ID = @EMP_ID AND UPPER(LEAVE_ASSIGN_AS) = 'PART DAY' 
													AND (FROM_DATE= @FR_DT) AND LEAVE_OUT_TIME = @SHIFT_MAX_LATE_TIME AND APPROVAL_STATUS = 'A'
												 )
										BEGIN	
											SET @IS_HALF_DAY_LEAVE = 1		
										END
										
										IF EXISTS(SELECT EMP_ID FROM T0140_LEAVE_TRANSACTION WITH (NOLOCK) WHERE EMP_ID = @EMP_ID AND FOR_DATE = @FR_DT AND ( LEAVE_USED >= 1 OR COMPOFF_USED >= 1 ))	--COMPOFF_USED	--ANKIT 04122015
										BEGIN	
											SET @IS_FULL_DAY_LEAVE = 1		
										END
										
										SET @DIFFERNCE_ROUNDING_LATE_SEC = 0

										

										IF @IN_DATE > @SHIFT_ST_DATETIME AND @IS_CANCEL_LATE_IN = 0  AND @IS_HALF_DAY_LEAVE = 0 AND @IS_FULL_DAY_LEAVE = 0-- MODIFIED BY MITESH ON 08/08/2011										
											BEGIN
												/* FOR SHIFT START TIME 12:00 AM & EMPLOYEE IN PUNCH EARLY THEN NOT COUNT LATE MARK (NIRMA CLIENT)  --ANKIT 07112015 */
												
												IF @ROUNDINGVALUE > 0 
													BEGIN
														IF DATEPART(HH,@SHIFT_ST_DATETIME) = 0 AND @IN_DATE < DATEADD(D,1,@FOR_DATECURR)
															SET @DIFFERNCE_ROUNDING_LATE_SEC = DATEDIFF(S,DATEADD(D,1,@FOR_DATECURR) ,@IN_DATE)
														ELSE
															SET @DIFFERNCE_ROUNDING_LATE_SEC = DATEDIFF(S,CAST(@VAR_SHIFT_ST_DATE AS DATETIME) ,@IN_DATE)
															
														SELECT @DIFFERNCE_ROUNDING_LATE_SEC = DBO.PRO_ROUNDING_SEC_HH_MM(@DIFFERNCE_ROUNDING_LATE_SEC,@ROUNDINGVALUE)
													END	
												ELSE
													BEGIN
														IF DATEPART(HH,@SHIFT_ST_DATETIME) = 0 AND @IN_DATE < DATEADD(D,1,@FOR_DATECURR)
															SET @DIFFERNCE_ROUNDING_LATE_SEC = DATEDIFF(S,DATEADD(D,1,@FOR_DATECURR) ,@IN_DATE)
														ELSE
															SET @DIFFERNCE_ROUNDING_LATE_SEC = DATEDIFF(S,@SHIFT_ST_DATETIME ,@IN_DATE)
													END
													
												IF @DIFFERNCE_ROUNDING_LATE_SEC > 0	
													BEGIN 
														IF (@IN_DATE > @SHIFT_ST_DATETIME)
														BEGIN
															
															SELECT @ACTUAL_MIN_DIFF = DATEDIFF(MINUTE, @ACTUAL_SHIFT_ST_TIME , @IN_DATE)
															
															UPDATE #LATE_MARK_SLAB SET CURR_COUNT = CURR_COUNT + 1 
															WHERE @ACTUAL_MIN_DIFF BETWEEN FROM_MIN AND TO_MIN 
															
															IF(@ACTUAL_MIN_DIFF * 60) > @Late_Limit 
																BEGIN
																	SELECT @LATE_CALC_ON_PERCENT = ISNULL(DEDUCTION,0) FROM #LATE_MARK_SLAB WHERE @ACTUAL_MIN_DIFF BETWEEN FROM_MIN AND TO_MIN 
															
																	INSERT INTO #LATE_MARK_TRANSACTION(CMP_ID,EMP_ID,FOR_DATE,LATE_MIN,LATE_CALC_ON_PERCENT,LATE_CALC_ON_AMT,LATE_AMOUNT,LATE_SEC,LATE_LIMIT,SHIFT_ID,SHIFT_NAME,IN_TIME)
																	VALUES(@CMP_ID,@EMP_ID,@FR_DT,DBO.F_RETURN_HOURS((@ACTUAL_MIN_DIFF * 60)- @LATE_LIMIT),@LATE_CALC_ON_PERCENT,(CASE WHEN @IS_LATE_CALCULATE_ON = 1 THEN @BASIC_SALARY WHEN @IS_LATE_CALCULATE_ON = 2 THEN @GROSS_SALARY WHEN @IS_LATE_CALCULATE_ON = 3 THEN @GROSS_SALARY END),0,((@ACTUAL_MIN_DIFF * 60)- @LATE_LIMIT),DBO.F_RETURN_HOURS(@LATE_LIMIT),@SHIFT_ID,@SHIFT_ST_TIME + '- ' + @SHIFT_END_TIME,@IN_DATE)


																	
																END
														END
													END
								END
						END
					FETCH NEXT FROM CURLMARK INTO @IN_DATE,@OUT_DATE,@FOR_DATECURR
				END
			CLOSE curLMark;
			DEALLOCATE curLMark;
		END
		
		DECLARE @MONTH_DAYS NUMERIC(18,2)
		SET @MONTH_DAYS = 0
		
		

		IF @SAL_FIX_DAYS <> 0
			BEGIN
				Update #LATE_MARK_TRANSACTION SET LATE_AMOUNT = ((LATE_CALC_ON_AMT/@SAL_FIX_DAYS) * LATE_CALC_ON_PERCENT) / 100
			END
		ELSE
			BEGIN				
				SET @MONTH_DAYS = DATEDIFF(D,@tmp_Month_St_Date,@tmp_Month_End_Date) + 1				
				IF @MONTH_DAYS > 0
					Begin						
						UPDATE #LATE_MARK_TRANSACTION SET LATE_AMOUNT = ((LATE_CALC_ON_AMT/@MONTH_DAYS) * LATE_CALC_ON_PERCENT) / 100
					End
			END
		
		DECLARE @TRAN_ID NUMERIC
		SET @TRAN_ID = 0
		
		SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0)  FROM T0140_MONTHLY_LATEMARK_TRANSACTION WITH (NOLOCK) 
		
		INSERT INTO T0140_MONTHLY_LATEMARK_TRANSACTION(TRAN_ID,SAL_TRAN_ID,CMP_ID,EMP_ID,LATE_MIN,LATE_SEC,FOR_DATE,LATE_CAL_ON_PERCENT,LATE_CALC_ON_AMT,LATE_AMOUNT,LATE_LIMIT,SHIFT_ID,SHIFT_NAME,IN_TIME)
		SELECT (@TRAN_ID + ROW_NUMBER() OVER ( ORDER BY EMP_ID )) as row_id,@SAL_TRAN_ID,
				CMP_ID,EMP_ID,LATE_MIN,LATE_SEC,FOR_DATE,LATE_CALC_ON_PERCENT,LATE_CALC_ON_AMT,LATE_AMOUNT,LATE_LIMIT,SHIFT_ID,SHIFT_NAME,IN_TIME
		FROM #LATE_MARK_TRANSACTION
		
END

