



---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_EMP_INCENTIVE_PROCESS_GET]
	 @Cmp_ID		NUMERIC
	,@From_Date		DATETIME
	,@To_Date		DATETIME 
	,@Branch_ID		NUMERIC   = 0
	,@Cat_ID		VARCHAR(MAX) = ''
	,@Grd_ID		VARCHAR(MAX) = ''
	,@Type_ID		NUMERIC  = 0
	,@Dept_ID		VARCHAR(MAX) = ''
	,@Desig_ID		VARCHAR(MAX) = ''
	,@Emp_ID		NUMERIC  = 0
	,@Constraint	VARCHAR(MAX) = ''
	,@Incentive_Status	VARCHAR(10)='All'
	,@Incentive_Cycle  NUMERIC  = 0
	,@Branch_Constraint VARCHAR(MAX) = ''
	,@Segment_ID VARCHAR(MAX) = ''
	,@Vertical VARCHAR(MAX) = ''
	,@SubVertical VARCHAR(MAX) = ''
	,@subBranch VARCHAR(MAX) = ''
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


	CREATE TABLE #Emp_Cons 
	(
		Emp_ID numeric ,  
		Branch_ID numeric,
		Increment_ID numeric    
	)
	
	IF (DATEDIFF(D,@FROM_DATE, @To_Date) > 31)
		SET @To_Date = DATEADD(D,-1,DATEADD(M, 1,@FROM_DATE));
	
	
	
	EXEC SP_RPT_FILL_EMP_CONS_MULTIDROPDOWN @Cmp_ID,@To_Date,@To_Date,@Branch_ID,@Cat_ID,@Grd_ID,@Type_ID,@Dept_ID,@Desig_ID,@Emp_ID,@constraint,0,0,@Segment_ID,@Vertical,@SubVertical,@subBranch,0,0,0,@Branch_Constraint,0,0
	CREATE UNIQUE NONCLUSTERED INDEX IX_EMP_CONS ON #Emp_Cons (EMP_ID)

	
	DECLARE @Date_Diff NUMERIC 
	
						
	CREATE TABLE #INCENTIVE_MST
	(	
		Emp_ID NUMERIC(18,0),
		Branch_ID  NUMERIC(18,0),
		Desig_ID NUMERIC(18,0),
		Scheme_ID NUMERIC(18,0),
		Effective_Date DATETIME,
		Status Varchar(100),
		Color_flag NUMERIC(1,0)		
	)
	
	CREATE TABLE #INCENTIVE_TABLE_PARAMETER
	(	
		EMP_ID NUMERIC(18,0),
		SCHEME_ID  NUMERIC(18,0),
		PARA_NAME VARCHAR(MAX),
		FROM_SLAB NUMERIC(18,2),
		TO_SLAB NUMERIC(18,2),
		SLAB_VALUE NUMERIC(18,2),
		IMPORT_VALUE NUMERIC(18,2)		
	)
	
	CREATE TABLE #INCENTIVE_TOTAL_SLAB
	(	
		EMP_ID NUMERIC(18,0),
		TRAN_ID NUMERIC(18,0),
		SCHEME_ID  NUMERIC(18,0),
		INCENTIVE_NAME VARCHAR(MAX),
		INCENTIVE_VALUE NUMERIC(18,2),
		OTHER_INCENTIVE_AMOUNT NUMERIC(18,2),
		SLAB_TYPE TINYINT,
		CALC_TYPE VARCHAR(100),
		CALC_ON VARCHAR(100),
		CONSIDER_PARA VARCHAR(max) -- ADDED ON 13102017
	)
	CREATE TABLE #INCENTIVE_TOTAL_AMOUNT
	(	
		EMP_ID NUMERIC(18,0),
		TRAN_ID NUMERIC(18,0),
		SCHEME_ID  NUMERIC(18,0),
		INCENTIVE_NAME VARCHAR(MAX),
		INCENTIVE_VALUE NUMERIC(18,2),
		INCENTIVE_AMOUNT NUMERIC(18,2),
		DEDUCTION_AMOUNT NUMERIC(18,2), -- ADDED ON 03022018
		IS_ADDITIONAL BIT
	)
	DECLARE @inc_status varchar(15)
	set	@inc_status='Hold'
	
	
	
	--IF @Incentive_Status = 'Done'  COMMENTED ON 07022018 TAKE COMMON CODE FOR BOTH PENDING || DONE INCENTIVE 
	--	BEGIN
	--		--INSERT INTO #INCENTIVE_MST(Emp_ID, Branch_ID, Desig_ID, Scheme_ID, Effective_Date, Status, Color_flag)
	--		--SELECT	E.EMP_ID, BM.BRANCH_ID,DGM.DESIG_ID,NULL, NULL, @INCENTIVE_STATUS AS STATUS,
	--		--		(CASE WHEN @INC_STATUS = 'HOLD' THEN 1 WHEN @INC_STATUS = 'PENDING' THEN 2 END) AS COLOR_FLAG	
	--		--FROM	T0080_EMP_MASTER E 
	--		--		INNER JOIN T0030_BRANCH_MASTER BM ON E.BRANCH_ID = BM.BRANCH_ID
	--		--		LEFT OUTER JOIN T0040_DESIGNATION_MASTER DGM ON E.DESIG_ID = DGM.DESIG_ID
	--		--WHERE	E.Cmp_ID = @Cmp_Id 
	--		--		AND ((@From_Date < E.Emp_LEft_Date AND @To_Date < E.Emp_LEft_Date) OR E.Emp_LEft_Date IS NULL)	
	--		--ORDER BY  Emp_Code ASC
				
	--	END	
	IF @Incentive_Status = 'Pending' OR @Incentive_Status = 'Done' OR @Incentive_Status='All'
		BEGIN	
				
			 --- CHANGED BY RAJPUT REPLACE INSTEAD 'FROM_DATE'  - TO - 'TO_DATE' WITH <=TO_DATE SET DUE TO EFFECTTIVE DATE DOES NOT GETING PROPER ON 24012018
			INSERT	INTO #INCENTIVE_MST(Emp_ID, Branch_ID, Desig_ID, Scheme_ID, Effective_Date, Status, Color_flag)
			SELECT	E.EMP_ID,I.BRANCH_ID,I.DESIG_ID,INS.SCHEME_ID,INS.EFFECTIVE_DATE,@INCENTIVE_STATUS AS STATUS,
					(CASE WHEN @INC_STATUS = 'HOLD' THEN 1 WHEN @INC_STATUS = 'PENDING' THEN 2 END) AS COLOR_FLAG
			FROM	#EMP_CONS E
					INNER JOIN T0095_INCREMENT I WITH (NOLOCK) ON E.INCREMENT_ID=I.INCREMENT_ID
					CROSS APPLY (SELECT	DISTINCT SCHEME_ID,INS.EFFECTIVE_DATE 
								FROM	V0055_INCENTIVE_SCHEME_DETAIL INS 										
										INNER JOIN  (SELECT MAX(EFFECTIVE_DATE) AS EFFECTIVE_DATE, Desig_Id, Branch_ID
													 FROM	V0055_INCENTIVE_SCHEME_DETAIL SD										
													 WHERE	SD.DESIG_ID=I.DESIG_ID AND SD.BRANCH_ID=I.BRANCH_ID																									
															AND SD.EFFECTIVE_DATE <= @TO_DATE
													 GROUP BY DESIG_ID, BRANCH_ID) SD ON INS.EFFECTIVE_DATE=SD.EFFECTIVE_DATE AND INS.BRANCH_ID=SD.BRANCH_ID AND INS.DESIG_ID=SD.DESIG_ID								
								) INS
			WHERE	I.CMP_ID = @CMP_ID AND INS.EFFECTIVE_DATE<=@TO_DATE				
		END
	
	DELETE INC FROM #INCENTIVE_MST INC --ADDED ON 06022018 DUE TO EMPLOYEE SHEET HAS NOT IMPORT EVENT SHOWING IN INCENITVE PROCESS PAGE.
	WHERE	NOT EXISTS(SELECT 1 FROM T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) WHERE IMP.Desig_ID=INC.Desig_ID AND IMP.Branch_ID=INC.Branch_ID AND IMP.For_Date=@From_Date)
	
	
	IF(@Incentive_Status='Pending') -- ADDED ON 07022018 TAKE RECORDS AS PER INCENTIVE STATUS
		BEGIN
			DELETE INC FROM #INCENTIVE_MST INC 
			WHERE	EXISTS(SELECT 1 FROM DBO.T0220_INCENTIVE_PROCESS IMP WITH (NOLOCK) WHERE IMP.DESIG_ID=INC.DESIG_ID 
										AND IMP.BRANCH_ID=INC.BRANCH_ID AND IMP.EMP_ID=INC.EMP_ID AND IMP.SCHEME_ID=INC.SCHEME_ID
										AND IMP.FOR_DATE=@FROM_DATE)
		END
	ELSE IF(@Incentive_Status='Done')
		BEGIN
			DELETE INC FROM #INCENTIVE_MST INC 
			WHERE	NOT EXISTS(SELECT 1 FROM DBO.T0220_INCENTIVE_PROCESS IMP WITH (NOLOCK) WHERE IMP.DESIG_ID=INC.DESIG_ID 
										AND IMP.BRANCH_ID=INC.BRANCH_ID AND IMP.EMP_ID=INC.EMP_ID AND IMP.SCHEME_ID=INC.SCHEME_ID
										AND IMP.FOR_DATE=@FROM_DATE)
		END	
	ELSE 
		BEGIN 
			
			UPDATE	INC	
			SET		INC.Status='Done'
			FROM	#INCENTIVE_MST INC 	
			WHERE	EXISTS(SELECT 1 FROM DBO.T0220_INCENTIVE_PROCESS IMP WITH (NOLOCK) WHERE IMP.DESIG_ID=INC.DESIG_ID 
										AND IMP.BRANCH_ID=INC.BRANCH_ID AND IMP.EMP_ID=INC.EMP_ID AND IMP.SCHEME_ID=INC.SCHEME_ID
										AND IMP.FOR_DATE=@FROM_DATE)
			
			UPDATE	INC	
			SET		INC.Status='Pending'
			FROM	#INCENTIVE_MST INC 	
			WHERE	NOT EXISTS(SELECT 1 FROM DBO.T0220_INCENTIVE_PROCESS IMP WITH (NOLOCK) WHERE IMP.DESIG_ID=INC.DESIG_ID 
										AND IMP.BRANCH_ID=INC.BRANCH_ID AND IMP.EMP_ID=INC.EMP_ID AND IMP.SCHEME_ID=INC.SCHEME_ID
										AND IMP.FOR_DATE=@FROM_DATE)
		
		END
					
	
	SELECT INC.*, E.Alpha_Emp_Code, E.Emp_Full_Name,B.Branch_Name,D.Desig_Name,E.Emp_Left,E.DEPT_ID
	INTO #INCENTIVE_DETAILS
	FROM	#INCENTIVE_MST INC
			INNER JOIN T0080_EMP_MASTER E WITH (NOLOCK) ON INC.Emp_ID=E.Emp_ID
			INNER JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON INC.Branch_ID=B.Branch_ID
			INNER JOIN T0040_DESIGNATION_MASTER D WITH (NOLOCK) ON INC.Desig_ID=D.Desig_ID
	ORDER	BY E.Alpha_Emp_Code
	
	
	
	DECLARE @SCHEME_ID AS NUMERIC(18,0)
	DECLARE CURINCENTIVE_AMOUNT CURSOR FAST_FORWARD FOR      
	SELECT DISTINCT SCHEME_ID FROM #INCENTIVE_DETAILS ORDER BY SCHEME_ID
	OPEN CURINCENTIVE_AMOUNT
	FETCH NEXT FROM CURINCENTIVE_AMOUNT INTO @SCHEME_ID
	WHILE @@FETCH_STATUS = 0                    
		BEGIN        
		    
			INSERT INTO  #INCENTIVE_TABLE_PARAMETER(EMP_ID,SCHEME_ID,PARA_NAME,FROM_SLAB,TO_SLAB,SLAB_VALUE,IMPORT_VALUE)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.PARA_NAME,ISP.FROM_SLAB,ISP.TO_SLAB,ISP.SLAB_VALUE,IMP.PARA_VALUE
			--INTO #INCENTIVE_TABLE_PARAMETER
			FROM	DBO.T0055_INCENTIVE_SCHEME_PARA ISP WITH (NOLOCK)
					INNER JOIN #INCENTIVE_DETAILS IM ON ISP.SCHEME_ID=IM.Scheme_ID
					INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK)
								ON IMP.Para_Name=ISP.Para_Name AND IMP.PARA_VALUE BETWEEN ISP.FROM_SLAB AND ISP.TO_SLAB AND IMP.EMP_ID=IM.EMP_ID
								AND IMP.Para_Type='PM' AND ISP.PARA_FOR='INCENTIVE' AND IMP.For_Date BETWEEN @From_Date AND @To_Date -- ADDED ON 23022018 IMP.For_Date<=@To_Date IMP.For_Date BETWEEN @From_Date AND @To_Date IMPORT TABLE WHICH DUPLICATE SLAB VALUE TAKE
			WHERE	IM.SCHEME_ID=@SCHEME_ID  
			ORDER BY IM.EMP_ID,ISP.PARA_NAME
			
	
			FETCH NEXT FROM CURINCENTIVE_AMOUNT INTO @SCHEME_ID
			
	    END                    
	CLOSE CURINCENTIVE_AMOUNT                    
	DEALLOCATE CURINCENTIVE_AMOUNT
	
	
		
		BEGIN -- MARKS --	
						
			
			---- PARAMETER-INCENTIVE (SLAB TYPE - MARKS , CALC. TYPE - FIXED) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,SLAB_TYPE,CALC_TYPE,CALC_ON,CONSIDER_PARA)
			SELECT	 T.EMP_ID, INC.SCHEME_ID, INC.INC_TRAN_ID,INC.INCENTIVE_NAME, SUM(T.SLAB_VALUE),SLAB_TYPE,CALC_TYPE,CALC_ON,'--All--'
			FROM	#INCENTIVE_TABLE_PARAMETER T
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,CONSIDER_PARA,SLAB_TYPE,CALC_TYPE,CALC_ON FROM DBO.T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) INC	ON T.SCHEME_ID=INC.SCHEME_ID AND INC.SLAB_TYPE=0 AND INC.CALC_TYPE='Fixed' AND ISNULL(INC.CONSIDER_PARA,'--ALL--') = '--ALL--'
			GROUP BY T.EMP_ID, INC.SCHEME_ID, INC.INC_TRAN_ID,INC.INCENTIVE_NAME,INC.SLAB_TYPE,INC.CALC_TYPE,INC.CALC_ON
			---- END ----
			
			---- DIRECT INCENTIVE (SLAB TYPE - MARKS , CALC. TYPE - FIXED ) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=0 AND ISP.CALC_TYPE='Fixed'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END -----
			
			---- SLAB-TYPE:FIXED,CALC-TYPE:FIXED, CALCULATION BASED ON PARAMETER ADDITIONAL INCENTIVE ADDED ON 13102017 
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,SLAB_TYPE,CALC_TYPE,CALC_ON,CONSIDER_PARA)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,IMP.PARA_VALUE,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON,ISP.CONSIDER_PARA
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,CONSIDER_PARA,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=0 AND ISP.CALC_TYPE='Fixed' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.CONSIDER_PARA AND IMP.EMP_ID=IM.EMP_ID AND  ISNULL(ISP.CONSIDER_PARA,'--All--') <> '--All--' AND IMP.For_Date BETWEEN @From_Date AND @To_Date -- Added on 23022018
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END
		
		
		END
		
		BEGIN -- PERCENTAGE --
			
			---- (SLAB TYPE - PERCENTAGE , CALC. TYPE - FIXED) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	 T.EMP_ID, INC.SCHEME_ID, INC.INC_TRAN_ID,INC.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),SLAB_TYPE,CALC_TYPE,CALC_ON
			FROM	#INCENTIVE_DETAILS T
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON,CONSIDER_PARA FROM DBO.T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) INC	ON T.SCHEME_ID=INC.SCHEME_ID AND INC.SLAB_TYPE=1 AND INC.CALC_TYPE='Fixed'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=INC.INCENTIVE_NAME AND IMP.EMP_ID=T.EMP_ID AND IMP.PARA_TYPE='IM' AND ISNULL(INC.CONSIDER_PARA,'--ALL--') = '--ALL--'
			GROUP BY T.EMP_ID, INC.SCHEME_ID, INC.INC_TRAN_ID,INC.INCENTIVE_NAME,INC.SLAB_TYPE,INC.CALC_TYPE,INC.CALC_ON
			---- END ----
			
			
			---- (SLAB TYPE - PERCENTAGE , CALC. TYPE - PERCENT , CALC ON - NET LABOR) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,OTHER_INCENTIVE_AMOUNT,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),SUM(IMP1.PARA_VALUE),ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM DBO.T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP	ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=1 AND ISP.CALC_TYPE='Percent' AND ISP.CALC_ON='Net Labor'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP1 WITH (NOLOCK) ON IMP1.PARA_NAME=ISP.CALC_ON AND IMP1.EMP_ID=IM.EMP_ID  --AND IMP.PARA_TYPE='I' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			---- END ----
			
		
			---- INCENTIVE (SLAB TYPE - PERCENTAGE , CALC. TYPE - PERCENT , CALC ON - ACHIEVEMENT) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,OTHER_INCENTIVE_AMOUNT,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),SUM(IMP1.PARA_VALUE),ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=1 AND ISP.CALC_TYPE='Percent' AND ISP.CALC_ON='Achievement'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP1 WITH (NOLOCK) ON IMP1.PARA_NAME=ISP.CALC_ON AND IMP1.EMP_ID=IM.EMP_ID  --AND IMP.PARA_TYPE='I' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END -----
			
		
		
			---- INCENTIVE (SLAB TYPE - PERCENTAGE , CALC. TYPE - PERCENT , CALC ON - ELIGIBLE INCENTIVE) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,OTHER_INCENTIVE_AMOUNT,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),0,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=1 AND ISP.CALC_TYPE='Percent' AND ISP.CALC_ON='Eligible Incentive' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' AND IMP.For_Date BETWEEN @From_Date AND @To_Date -- ADDED ON 23022018 AND IMP.For_Date BETWEEN @From_Date AND @To_Date
				--INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP1 ON IMP1.PARA_NAME=ISP.Incentive_Name AND IMP1.EMP_ID=IM.EMP_ID  --AND IMP.PARA_TYPE='I' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END ----
			
			
			
			---- SLAB-TYPE:PERCENTAGE,CALC-TYPE:FIXED, CALCULATION BASED ON PARAMETER ADDITIONAL INCENTIVE ADDED ON 20022018
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,SLAB_TYPE,CALC_TYPE,CALC_ON,CONSIDER_PARA)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,IMP.PARA_VALUE,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON,ISP.CONSIDER_PARA
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,CONSIDER_PARA,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=1 AND ISP.CALC_TYPE='Fixed' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.CONSIDER_PARA AND IMP.EMP_ID=IM.EMP_ID AND  ISNULL(ISP.CONSIDER_PARA,'--All--') <> '--All--' 
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END
			
		END
		
		BEGIN -- NOs --
		
			---- INCENTIVE (SLAB TYPE - NOs , CALC. TYPE - RATE , CALC ON - PAID SERVICE) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,OTHER_INCENTIVE_AMOUNT,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),SUM(IMP1.PARA_VALUE),ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=2 AND ISP.CALC_TYPE='Rate' AND ISP.CALC_ON='Paid Service'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP1 WITH (NOLOCK) ON IMP1.PARA_NAME=ISP.CALC_ON AND IMP1.EMP_ID=IM.EMP_ID  --AND IMP.PARA_TYPE='I' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			
			---- END ----
			
			---- INCENTIVE (SLAB TYPE - NOs , CALC. TYPE - RATE , CALC ON - VEHICLE) ----
			INSERT INTO #INCENTIVE_TOTAL_SLAB(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,OTHER_INCENTIVE_AMOUNT,SLAB_TYPE,CALC_TYPE,CALC_ON)
			SELECT	IM.EMP_ID,ISP.SCHEME_ID,ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,SUM(IMP.PARA_VALUE),SUM(IMP1.PARA_VALUE),ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			FROM	#INCENTIVE_DETAILS IM 
				INNER JOIN 
				(
					SELECT DISTINCT SCHEME_ID,INC_TRAN_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON FROM T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK)
				) ISP ON IM.SCHEME_ID=ISP.SCHEME_ID AND ISP.SLAB_TYPE=2 AND ISP.CALC_TYPE='Rate' AND ISP.CALC_ON='Vehicle'
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP WITH (NOLOCK) ON IMP.PARA_NAME=ISP.INCENTIVE_NAME AND IMP.EMP_ID=IM.EMP_ID AND IMP.PARA_TYPE='IM' 
				INNER JOIN DBO.T0190_EMP_INCENTIVE_IMPORT IMP1 WITH (NOLOCK) ON IMP1.PARA_NAME=ISP.CALC_ON AND IMP1.EMP_ID=IM.EMP_ID  --AND IMP.PARA_TYPE='I' 
			GROUP BY IM.EMP_ID, ISP.SCHEME_ID, ISP.INC_TRAN_ID,ISP.INCENTIVE_NAME,ISP.SLAB_TYPE,ISP.CALC_TYPE,ISP.CALC_ON
			ORDER BY IM.EMP_ID,ISP.INCENTIVE_NAME
			---- END ----
			
		
		END 
		
		
		-- CALCULATION START
		
		---- SLAB TYPE: MARKS, CALCULATION TYPE: FIXED
		
		
		
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,INC.SLAB_VALUE
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=0 
							AND INC_TSLAB.CALC_TYPE='FIXED' AND INC_TSLAB.CALC_ON=INC.CALC_ON AND ISNULL(INC_TSLAB.CONSIDER_PARA,'--All--') = '--All--' 
							AND INC.INCENTIVE_FOR <> 'DEDUCTION' --ADDED ON 05022018 FOR DEDUCTION PART CONDITION
							AND INC_TSLAB.INCENTIVE_NAME=INC.INCENTIVE_NAME --ADDED ON 23022018 DUPLICATE INCENTIVE AMOUNT COME DURING ADDITION AMOUNT CALCULATE TIME
		
		
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,INC.SLAB_VALUE
				--(INC_TSLAB.OTHER_INCENTIVE_AMOUNT * INC.SLAB_VALUE / 100) as INCENTIVE_AMOUNT
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=1 
							AND INC_TSLAB.CALC_TYPE='PERCENT' AND INC_TSLAB.CALC_ON=INC.CALC_ON AND INC_TSLAB.CALC_ON NOT IN ('NET LABOR','ACHIEVEMENT')
							AND INC_TSLAB.INCENTIVE_NAME=INC.INCENTIVE_NAME
		
		
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,INC.SLAB_VALUE
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=0 
							AND INC_TSLAB.CALC_TYPE='FIXED' AND INC_TSLAB.CALC_ON=INC.CALC_ON AND INC.CONSIDER_PARA=INC_TSLAB.CONSIDER_PARA AND  ISNULL(INC_TSLAB.CONSIDER_PARA,'--All--') <> '--All--'  -- CALCULATION BASED ON PARAMETER ADDITIONAL 13102017
		
		
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,INC.SLAB_VALUE
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=1 
							AND INC_TSLAB.CALC_TYPE='FIXED' AND INC_TSLAB.CALC_ON=INC.CALC_ON AND INC.CONSIDER_PARA=INC_TSLAB.CONSIDER_PARA AND  ISNULL(INC_TSLAB.CONSIDER_PARA,'--All--') <> '--All--'  -- CALCULATION BASED ON PARAMETER ADDITIONAL 20022018
		
		
		
		UPDATE	T	
		SET		T.INCENTIVE_AMOUNT = (INC.SLAB_VALUE * T1.INCENTIVE_AMOUNT / 100 ),
				IS_ADDITIONAL=1
		--SELECT T.EMP_ID,T.SCHEME_ID,T.TRAN_ID,T.INCENTIVE_NAME,
		--		T1.INCENTIVE_AMOUNT,INC.SLAB_VALUE,
		--	--(T.INCENTIVE_AMOUNT * T1.INCENTIVE_AMOUNT / 100 ) + T.INCENTIVE_AMOUNT AS INCENTIVE_AMOUNT ,				
		--		(INC.SLAB_VALUE * T1.INCENTIVE_AMOUNT / 100 ) AS INCENTIVE_AMOUNT 
		FROM	#INCENTIVE_TOTAL_AMOUNT T 				
				INNER JOIN T0055_INCENTIVE_SCHEME_INC INC ON T.TRAN_ID=INC.INC_TRAN_ID  AND T.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB
				INNER JOIN (SELECT	T1.INCENTIVE_NAME,T1.INCENTIVE_VALUE,T1.EMP_ID ,T1.INCENTIVE_AMOUNT
							FROM	#INCENTIVE_TOTAL_AMOUNT T1 
									INNER JOIN T0055_INCENTIVE_SCHEME_INC INC1 WITH (NOLOCK) ON T1.TRAN_ID=INC1.INC_TRAN_ID  AND T1.INCENTIVE_VALUE BETWEEN INC1.FROM_SLAB AND INC1.TO_SLAB
							WHERE	INC1.CALC_TYPE='FIXED') T1 ON T.EMP_ID=T1.EMP_ID
		WHERE	INC.CALC_TYPE='PERCENT' AND INC.CALC_ON='ELIGIBLE INCENTIVE' AND ISNULL(INC.CONSIDER_PARA,'--ALL--') = '--ALL--'
		---- END ----
		
		
		
		---- CALCULATION BASED ON PARAMETER ADDITIONAL INCENTIVE ADDED ON 13102017	----
		UPDATE	T	
		SET		T.INCENTIVE_AMOUNT = (INC.SLAB_VALUE),
				IS_ADDITIONAL=1
		FROM	#INCENTIVE_TOTAL_AMOUNT T 				
				INNER JOIN T0055_INCENTIVE_SCHEME_INC INC ON T.TRAN_ID=INC.INC_TRAN_ID  AND T.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB
				INNER JOIN (SELECT	T1.INCENTIVE_NAME,T1.INCENTIVE_VALUE,T1.EMP_ID ,T1.INCENTIVE_AMOUNT
							FROM	#INCENTIVE_TOTAL_AMOUNT T1 
									INNER JOIN T0055_INCENTIVE_SCHEME_INC INC1 WITH (NOLOCK) ON T1.TRAN_ID=INC1.INC_TRAN_ID  AND T1.INCENTIVE_VALUE BETWEEN INC1.FROM_SLAB AND INC1.TO_SLAB
							WHERE	INC1.CALC_TYPE='FIXED') T1 ON T.EMP_ID=T1.EMP_ID
		WHERE	INC.CALC_TYPE='FIXED' AND ISNULL(INC.CONSIDER_PARA,'--ALL--') <> '--ALL--' and t.SCHEME_ID=INC.Scheme_ID
		---- END -----
		
		
		---- SLAB TYPE: PERCENTAGE, CALCULATION TYPE: PERCENT, CALCULATION ON:(NET LABOR,ACHIEVEMENT)
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,
				(INC_TSLAB.OTHER_INCENTIVE_AMOUNT * INC.SLAB_VALUE / 100) as INCENTIVE_AMOUNT
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=1 
							AND INC_TSLAB.CALC_TYPE='PERCENT' AND INC.Calc_ON IN ('Net Labor','Achievement')
		---- END ----
			
		
		---- SLAB TYPE: PERCENTAGE, CALCULATION TYPE: FIXED
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,INC.SLAB_VALUE
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=1 
							AND INC_TSLAB.CALC_TYPE='FIXED' AND INC_TSLAB.CALC_ON=INC.CALC_ON AND ISNULL(INC_TSLAB.CONSIDER_PARA,'--All--') = '--All--' 
							AND INC.INCENTIVE_FOR<>'DEDUCTION' --ADDED ON 05022018 FOR DEDUCTION PART CONDITION
							
							-- AND INC_TSLAB.CALC_ON=INC.CALC_ON AND ISNULL(INC_TSLAB.CONSIDER_PARA,'--All--') = '--All--'  AND INC.INCENTIVE_FOR<>'DEDUCTION' ADDED ON 20022018
							
		---- END ---- 
		
		
		---- SLAB TYPE: PERCENTAGE, CALCULATION TYPE: RATE, CALCULATION ON:(PAID SERVICE,VEHICLE)
		INSERT INTO #INCENTIVE_TOTAL_AMOUNT(EMP_ID,SCHEME_ID,TRAN_ID,INCENTIVE_NAME,INCENTIVE_VALUE,INCENTIVE_AMOUNT)
		SELECT	INC_TSLAB.EMP_ID,INC_TSLAB.SCHEME_ID,INC_TSLAB.TRAN_ID,INC_TSLAB.INCENTIVE_NAME,
				INC_TSLAB.INCENTIVE_VALUE,
				(INC_TSLAB.OTHER_INCENTIVE_AMOUNT * INC.SLAB_VALUE) as INCENTIVE_AMOUNT
		FROM	#INCENTIVE_TOTAL_SLAB INC_TSLAB
				INNER JOIN  T0055_INCENTIVE_SCHEME_INC INC WITH (NOLOCK) ON  INC_TSLAB.INCENTIVE_VALUE BETWEEN INC.FROM_SLAB AND INC.TO_SLAB 
							AND INC.Scheme_ID=INC_TSLAB.SCHEME_ID AND  INC_TSLAB.SLAB_TYPE=2 
							AND INC_TSLAB.CALC_TYPE='RATE' 
		---- End ---
		
		-- CODE FOR DEDUCTION
		
		
		
		EXEC SP_CALC_INCENTIVE_DEDUCTION --ADDED ON 03022018 
		
		-- END 
		
	-- IF EXISTS(SELECT 1 FROM #INCENTIVE_TOTAL_AMOUNT INC WHERE IS_ADDITIONAL=1 AND SCHEME_ID=@SCHEME_ID AND INC.IS_ADDITIONAL=1 AND INC.IS_ADDITIONAL IS NOT NULL)


			SELECT	ID.EMP_ID,ID.Dept_ID,ID.BRANCH_ID,ID.DESIG_ID,ID.SCHEME_ID,ID.EFFECTIVE_DATE,ID.STATUS,
					ID.COLOR_FLAG,ID.ALPHA_EMP_CODE,(ID.ALPHA_EMP_CODE + ' - ' + ID.EMP_FULL_NAME) AS EMP_FULL_NAME,ID.BRANCH_NAME,ID.DESIG_NAME,ID.EMP_LEFT,
					INC.INCENTIVE_AMOUNT,ISNULL(INC.DEDUCTION_AMOUNT,0) AS DEDUCTION_AMOUNT,SUM(ISNULL(INC_ADD.INCENTIVE_AMOUNT ,0) )AS ADDITIONAL_INCENTIVE,
					SUM(INC.INCENTIVE_AMOUNT + ISNULL(INC_ADD.INCENTIVE_AMOUNT ,0) - ISNULL(INC.DEDUCTION_AMOUNT,0)  ) AS TOTAL_INCENTIVE_AMOUNT
			FROM	#INCENTIVE_DETAILS ID
					INNER JOIN (SELECT * FROM #INCENTIVE_TOTAL_AMOUNT WHERE ISNULL(IS_ADDITIONAL,0) = 0) INC ON ID.Emp_ID=INC.EMP_ID
					LEFT OUTER JOIN (SELECT * FROM #INCENTIVE_TOTAL_AMOUNT WHERE ISNULL(IS_ADDITIONAL,0) = 1) INC_ADD ON ID.Emp_ID=INC_ADD.EMP_ID
					
					GROUP BY ID.EMP_ID,ID.Dept_ID,ID.BRANCH_ID,ID.DESIG_ID,ID.SCHEME_ID,ID.EFFECTIVE_DATE,ID.STATUS,
					ID.COLOR_FLAG,ID.ALPHA_EMP_CODE,ID.ALPHA_EMP_CODE, ID.EMP_FULL_NAME,ID.BRANCH_NAME,ID.DESIG_NAME,ID.EMP_LEFT,
					INC.INCENTIVE_AMOUNT,INC.DEDUCTION_AMOUNT
					
					
					
			--END
	
		--SELECT  E.Emp_ID,E.ALPHA_EMP_CODE, E.EMP_FULL_NAME,E.BRANCH_NAME,E.DESIG_NAME,E.EMP_LEFT,E.EFFECTIVE_DATE AS FOR_DATE
		--		,MONTH(E.EFFECTIVE_DATE) AS INC_MONTH,YEAR(E.EFFECTIVE_DATE) AS INC_YEAR,E.STATUS,E.COLOR_FLAG,E.BRANCH_ID,E.DESIG_ID,INC_AMOUNT.* 
		--FROM #INCENTIVE_TOTAL_AMOUNT INC_AMOUNT 
		--		INNER JOIN  #INCENTIVE_DETAILS E ON INC_AMOUNT.EMP_ID=E.EMP_ID
				
				
		
		RETURN

END

	

