


-- =============================================
-- Author: Nilesh Patel
-- Create date: 06-03-2018
-- Description:	Self Assessment Report Sp 
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[SP_Emp_Self_Assessment_Report]
	@Cmp_ID Numeric,
	@Emp_ID Numeric,
	@Initiation_Id Numeric
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	Declare @Show_KPA_Measure Numeric
	Set @Show_KPA_Measure = 0

   SELECT @Show_KPA_Measure = Isnull(Show_KPA_Measure,0) 
   FROM T0050_APPRAISALLIMIT_SETTING TAS WITH (NOLOCK)
   INNER JOIN(
				SELECT MAX(EFFECTIVE_DATE) AS EFFDATE,CMP_ID 
					FROM T0050_APPRAISALLIMIT_SETTING  WITH (NOLOCK)
				WHERE CMP_ID = @Cmp_ID
				GROUP BY CMP_ID
			) AS QRY
	ON TAS.EFFECTIVE_DATE = QRY.EFFDATE AND TAS.CMP_ID = QRY.CMP_ID
	WHERE TAS.CMP_ID = @Cmp_ID

	SELECT INITIATEID,THI.CMP_ID,THI.EMP_ID,SA_EMPCOMMENTS,EM.ALPHA_EMP_CODE,EM.ALPHA_EMP_CODE + ' - ' + EM.EMP_FULL_NAME as EMP_FULL_NAME,CM.CMP_NAME,CM.CMP_ADDRESS
		FROM T0050_HRMS_INITIATEAPPRAISAL THI WITH (NOLOCK)
		INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON THI.EMP_ID = EM.EMP_ID
		INNER JOIN T0010_COMPANY_MASTER CM WITH (NOLOCK) ON CM.CMP_ID = THI.Cmp_ID
	WHERE THI.EMP_ID = @Emp_ID AND INITIATEID = @Initiation_Id and THI.Cmp_ID = @Cmp_ID

	SELECT HKM.KPA_TYPE,HK.KPA_CONTENT,HK.KPA_TARGET,ACTUAL_ACHIEVEMENT,KPA_WEIGHTAGE,
		 KPA_ACHIEVEMENT,KPA_ACHIEVEMENTEMP,KPA_CRITICAL,INITIATEID,HK.KPA_Performace_Measure,@Show_KPA_Measure As KPA_Measure,
		 ISNULL(HK.Achievement_Percentage_Emp,0)Achievement_Percentage_Emp
	FROM T0052_HRMS_KPA HK WITH (NOLOCK)
		 INNER JOIN T0040_HRMS_KPATYPE_MASTER HKM WITH (NOLOCK) ON HK.KPA_TYPE_ID = HKM.KPA_TYPE_ID 
	WHERE EMP_ID = @Emp_ID AND INITIATEID = @Initiation_Id and HK.Cmp_ID = @Cmp_ID

	SELECT 
		SM.SAPPARISAL_CONTENT,EMP_WEIGHTAGE,EMP_RATING,FINAL_EMP_SCORE,INITIATEID
	FROM T0052_HRMS_EMPSELFAPPRAISAL HES WITH (NOLOCK)
		INNER JOIN T0040_SELFAPPRAISAL_MASTER SM WITH (NOLOCK) ON HES.SAPPARISAL_ID = SM.SAPPARISAL_ID 
	WHERE EMP_ID = @Emp_ID AND INITIATEID = @Initiation_Id and HES.Cmp_ID = @Cmp_ID

	SELECT 
		HOM.OA_TITLE,EOA_COLUMN1,EOA_COLUMN2,INITIATION_ID
	FROM T0050_HRMS_EMPOA_FEEDBACK HEF WITH (NOLOCK)
		INNER JOIN T0040_HRMS_OTHERASSESSMENT_MASTER HOM WITH (NOLOCK) ON HEF.OA_ID = HOM.OA_ID 
	WHERE EMP_ID = @Emp_ID AND INITIATION_ID = @Initiation_Id and HEF.Cmp_ID = @Cmp_ID
	
	SELECT ap.Emp_ID,ap.InitiateId,ap.[Plan],ap.Area,hm.Method,tm.TimeFrame,ap.Comments					
	from T0110_HRMS_Appraisal_PlanDetails ap WITH (NOLOCK)
	inner join T0050_HRMS_InitiateAppraisal i WITH (NOLOCK) on i.InitiateId=ap.InitiateId and i.Emp_Id=ap.Emp_ID
	LEFT join T0040_HRMS_TimeFrame_Master tm WITH (NOLOCK) on tm.TimeFrame_Id=ap.TimeFrame_Id
	LEFT join T0040_HRMS_Method_Master hm WITH (NOLOCK) on hm.Method_Id=ap.Method_Id
	where ap.Cmp_ID =@cmp_id and ap.Emp_ID=@Emp_ID and ap.InitiateId=@Initiation_Id and ap.Approval_Level='Emp'
		
END

