

-- =============================================
-- Author:		<Author,,Jimit>
-- Create date: <Create Date,,20112018>
-- Description:	<Description,,For Getting Attendance Lock Records>
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[SP_EMP_Attendance_Lock]
	 @CMP_ID				NUMERIC
	,@FROM_DATE				DATETIME
	,@TO_DATE				DATETIME 
	,@BRANCH_ID				NUMERIC = 0
	,@CAT_ID				NUMERIC	= 0	
	,@DEPT_ID				NUMERIC = 0			
	,@ATTENDANCELOCK_STATUS	VARCHAR(15) = 'ALL'
	,@Emp_ID NUMERIC = 0
		
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

		
		IF @BRANCH_ID = 0
			SET @BRANCH_ID = NULL
		IF @CAT_ID = 0
			SET @CAT_ID = NULL
		IF @DEPT_ID = 0
			SET @DEPT_ID = NULL
		
	
		CREATE TABLE #EMP_CONS 
		 (      
			EMP_ID			NUMERIC ,     
			BRANCH_ID		NUMERIC,
			INCREMENT_ID	NUMERIC    
		 )      
 	
	EXEC SP_RPT_FILL_EMP_CONS	@CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,0,0,@DEPT_ID,0,@Emp_ID,
								'',0 ,0 ,0,0,0,0,0,0,0,'0',0	

	CREATE CLUSTERED INDEX IX_EMP_CONS_EMP_ID_BRANCH_ID_INCREMENT_ID ON #EMP_CONS (EMP_ID,BRANCH_ID,INCREMENT_ID) 
		
		IF @ATTENDANCELOCK_STATUS = 'All' 
		   BEGIN		
					SELECT * FROM
					(
						SELECT		DISTINCT	E.EMP_ID,E.ALPHA_EMP_CODE AS EMP_CODE,E.EMP_FULL_NAME AS EMPLOYEE_NAME,DM.DEPT_NAME AS DEPARTMENT, 
									'Lock'  AS IS_LOCK,I.BRANCH_ID,I.DEPT_ID,I.Vertical_ID,I.SubVertical_ID
						FROM		T0080_EMP_MASTER E WITH (NOLOCK) INNER JOIN 
									#EMP_CONS EC ON E.EMP_ID = EC.EMP_ID  INNER JOIN
									T0095_INCREMENT I WITH (NOLOCK) ON I.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = I.INCREMENT_ID LEFT OUTER JOIN							  
									T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON I.DEPT_ID = DM.DEPT_ID INNER JOIN							
									T0180_LOCKED_ATTENDANCE SPE WITH (NOLOCK) ON E.EMP_ID = SPE.EMP_ID AND [YEAR] = YEAR(@TO_DATE) AND [MONTH] = MONTH(@TO_DATE)
						WHERE		E.CMP_ID = @CMP_ID
					
					
						UNION ALL

						SELECT DISTINCT	E.EMP_ID,E.ALPHA_EMP_CODE AS EMP_CODE,E.EMP_FULL_NAME AS EMPLOYEE_NAME,DM.DEPT_NAME AS DEPARTMENT, 
									'UnLock' AS IS_LOCK,I.BRANCH_ID,I.DEPT_ID,I.Vertical_ID,I.SubVertical_ID
						FROM		T0080_EMP_MASTER E WITH (NOLOCK) INNER JOIN 
									#EMP_CONS EC ON E.EMP_ID = EC.EMP_ID  INNER JOIN
									T0095_INCREMENT I WITH (NOLOCK) ON I.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = I.INCREMENT_ID LEFT OUTER JOIN							  
									T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON I.DEPT_ID = DM.DEPT_ID LEFT OUTER JOIN							
									T0180_LOCKED_ATTENDANCE SPE WITH (NOLOCK) ON E.EMP_ID = SPE.EMP_ID AND [YEAR] = YEAR(@TO_DATE) AND [MONTH] = MONTH(@TO_DATE)
						WHERE		E.CMP_ID = @CMP_ID AND 
									NOT EXISTS(
													SELECT	1 
													FROM	T0180_LOCKED_ATTENDANCE SP WITH (NOLOCK)
													WHERE	E.EMP_ID = SP.EMP_ID AND SP.[YEAR] = YEAR(@TO_DATE) AND	SP.[MONTH] = MONTH(@TO_DATE)
											   )
					)Q	
					ORDER BY		Q.EMP_CODE,Q.EMPLOYEE_NAME
		   END	 
		ELSE IF @ATTENDANCELOCK_STATUS = 'Lock' 
				BEGIN		
						SELECT DISTINCT	E.EMP_ID,E.ALPHA_EMP_CODE AS EMP_CODE,E.EMP_FULL_NAME AS EMPLOYEE_NAME,DM.DEPT_NAME AS DEPARTMENT, 
										'Lock'  AS IS_LOCK,I.BRANCH_ID,I.DEPT_ID,I.Vertical_ID,I.SubVertical_ID
						FROM			T0080_EMP_MASTER E WITH (NOLOCK) INNER JOIN 
										#EMP_CONS EC ON E.EMP_ID = EC.EMP_ID  INNER JOIN
										T0095_INCREMENT I WITH (NOLOCK) ON I.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = I.INCREMENT_ID LEFT OUTER JOIN							  
										T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON I.DEPT_ID = DM.DEPT_ID INNER JOIN							
										T0180_LOCKED_ATTENDANCE SPE WITH (NOLOCK) ON E.EMP_ID = SPE.EMP_ID AND [YEAR] = YEAR(@TO_DATE) AND [MONTH] = MONTH(@TO_DATE)
						WHERE			E.CMP_ID = @CMP_ID
						ORDER BY		E.ALPHA_EMP_CODE,E.EMP_FULL_NAME
				END	   
	   ELSE IF @ATTENDANCELOCK_STATUS = 'UnLock'
				BEGIN
						SELECT DISTINCT	E.EMP_ID,E.ALPHA_EMP_CODE AS EMP_CODE,E.EMP_FULL_NAME AS EMPLOYEE_NAME,DM.DEPT_NAME AS DEPARTMENT, 
										'UnLock' AS IS_LOCK,I.BRANCH_ID,I.DEPT_ID,I.Vertical_ID,I.SubVertical_ID
						FROM			T0080_EMP_MASTER E WITH (NOLOCK) INNER JOIN 
										#EMP_CONS EC ON E.EMP_ID = EC.EMP_ID  INNER JOIN
										T0095_INCREMENT I WITH (NOLOCK) ON I.EMP_ID = EC.EMP_ID AND EC.INCREMENT_ID = I.INCREMENT_ID LEFT OUTER JOIN							  
										T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON I.DEPT_ID = DM.DEPT_ID LEFT OUTER JOIN							
										T0180_LOCKED_ATTENDANCE SPE WITH (NOLOCK) ON E.EMP_ID = SPE.EMP_ID AND [YEAR] = YEAR(@TO_DATE) AND [MONTH] = MONTH(@TO_DATE)
						WHERE			E.CMP_ID = @CMP_ID AND
										NOT EXISTS(
														SELECT	1 
														FROM	T0180_LOCKED_ATTENDANCE SP WITH (NOLOCK)
														WHERE	E.EMP_ID = SP.EMP_ID AND SP.[YEAR] = YEAR(@TO_DATE) AND	SP.[MONTH] = MONTH(@TO_DATE)
													)
						ORDER BY		E.ALPHA_EMP_CODE,E.EMP_FULL_NAME		
				END
RETURN
	
	
	

