



---13/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_GET_LABLE_FOR_CHECKLIST] 
@CMP_ID AS NUMERIC
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	DECLARE @TRAN_ID AS NUMERIC
	DECLARE @FIELD_NAME AS VARCHAR(50)	
	DECLARE @FIELD_VALUE AS  VARCHAR(100)
	DECLARE @FLAG  AS CHAR(1)
	
    SET @FLAG='N'		
    SET @TRAN_ID=0
		
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'EMP CODE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'EMP FULL NAME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'ENROLL NO','',@FLAG)

	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'INITIAL','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'FIRST NAME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SECOND NAME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'LAST NAME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PHOTO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'BRANCH','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'GRADE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DESIGNATION','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DEPARTMENT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'STATUS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DATE OF JOIN','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SHIFT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SALARY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CTC','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MANAGER','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'OVERTIME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'LATE MARK','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'FULL PF','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'FIX SALARY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PART TIME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PROBATION','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'GENDER','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MARITIAL STATUS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DATE OF BIRTH','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PF NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PAN NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'ESIC NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DRIVING LICENSE','',@FLAG)
	
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'EXPIRY DATE OF LICENSE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'RELIGION','',@FLAG)

	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'HEIGHT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MARK IDENTIFICATION','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DISPENSARY','',@FLAG)
	
  SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DOCTOR NAME','',@FLAG)    
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DISPENSARY ADDRESS','',@FLAG)    
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'INSURANCE NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CONFIRMATION DATE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'BLOOD GROUP','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PERSONAL EMAIL ID','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PERMANENT ADDRESS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CITY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'STATE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'POST BOX','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'COUNTRY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'TEL NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'NATIONALITY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'OFFICE NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MOBILE NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'WORKING ADDRESS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CITY(WORKING)','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'STATE(WORKING)','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'POST BOX(WORKING)','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'OFFICIAL EMAIL','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'EMERGENCY CONTACT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'DEPENDANTS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CHILDREN','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'IMMIGRATION','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'ASSET','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'CONTRACT DETAIL','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SUPERWISER(REPORTING)','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'EXPERIENCE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'QUALIFICATION','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SKILL','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'ATTACHMENT','',@FLAG)
	
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'BANK','',@FLAG)
	
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'WAGES TYPE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'SALARY ON','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'PAYMENT MODE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'ACCOUNT NO','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'LATE LIMIT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'LATE DEDUCTION TYPE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MIN OVER TIME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'MAX OVER TIME','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'YEAR LEAVE DAYS','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'YEAR LEAVE AMOUNT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'YEAR BONUS PER','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'YEAR BONUS AMOUNT','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'GRATUITY APPLICABLE','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'BONUS YEARLY','',@FLAG)
	
	SET @TRAN_ID = @TRAN_ID + 1	
	INSERT INTO #CHECKLIST_LABLE_GET 
	VALUES(@TRAN_ID,'WEEK OFF','',@FLAG)
	
	INSERT INTO #CHECKLIST_LABLE_GET 
	SELECT  @TRAN_ID + 1,UPPER(AD_NAME),'','N' FROM T0050_AD_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID
	
	
	
RETURN




