


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[SP_GET_Induction_Training_List] 
	@Cmp_ID Numeric,
	@Emp_ID Numeric,
	@Training_Id Numeric = 0,
	@Flag Numeric = 0
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	IF @Flag = 0 -- For HR Induction Process
		BEGIN
			SELECT DISTINCT HTM.Training_ID,HTM.Training_name
				FROM T0040_HRMS_TRAINING_MASTER HTM WITH (NOLOCK)
					INNER JOIN T0030_HRMS_TRAINING_TYPE HTT WITH (NOLOCK) ON HTT.TRAINING_TYPE_ID = HTM.TRAINING_TYPE
					--INNER JOIN T0050_EMP_WISE_CHECKLIST EWC ON EWC.TRAINING_ID = HTM.TRAINING_ID
					INNER JOIN T0150_HRMS_TRAINING_QUESTIONNAIRE HTQ WITH (NOLOCK) ON CAST(HTQ.TRAINING_ID AS VARCHAR) = CAST(HTM.TRAINING_ID AS VARCHAR)
			WHERE HTM.CMP_ID = @CMP_ID AND ISNULL(HTT.TYPE_INDUCTION,0) = 1 --AND HTT.Induction_Traning_Dept = 1				  
				  AND EXISTS(Select 1 From T0150_HRMS_TRAINING_QUESTIONNAIRE HTQ WITH (NOLOCK) Where CHARINDEX(Cast(HTM.Training_id as Varchar(10)),HTQ.Training_Id) > 0)
		END
	--ELSE IF @Flag = 1 -- For HR Induction Process
	--	BEGIN
	--		SELECT DISTINCT F.TRAINING_QUE_ID,QUESTION,F.TRAINING_ID,F.CMP_ID,QUESTIONNIARE_TYPE,QUESTION_TYPE,
	--		CASE WHEN QUESTION_TYPE = 1 THEN 'Title' WHEN QUESTION_TYPE = 2 THEN 'Text' WHEN QUESTION_TYPE=3 THEN 'Paragraph Text' WHEN QUESTION_TYPE = 4 THEN 'Multiple Choice' WHEN QUESTION_TYPE=5 THEN 'CheckBoxList' WHEN QUESTION_TYPE = 6 THEN 'DropdownList' WHEN QUESTION_TYPE = 7 THEN 'Multiple Choice Grid' ELSE 'Paragraph Text' END  QUESTIONTYPE,
	--			SORTING_NO,QUESTION_OPTION,ANSWER AS ACTUALANSWER,F.MARKS AS ACTUALMARKS,ISNULL(QUESTION_ROW_TYPE,0)QUESTION_ROW_TYPE,EWC.Checklist_ID , 0 as Checklist_Fun_ID ,Isnull(HTM.Training_MCP,0) as Passing_Criteria,
	--			EWC.Passing_Flag,Isnull(EWC.Training_attempt_count,0) as Training_attempt_count 
	--			FROM T0150_HRMS_TRAINING_QUESTIONNAIRE F 
	--		CROSS apply [dbo].[Split](F.TRAINING_ID, '#') as S
	--		INNER JOIN T0050_EMP_WISE_CHECKLIST EWC ON CAST(EWC.TRAINING_ID AS VARCHAR) = S.Data
	--		INNER JOIN T0040_HRMS_TRAINING_MASTER HTM ON CAST(HTM.TRAINING_ID AS VARCHAR) = CAST(EWC.TRAINING_ID AS VARCHAR)
	--		WHERE F.CMP_ID = @CMP_ID AND S.Data = @TRAINING_ID AND EWC.EMP_ID = @EMP_ID
	--				AND QUESTIONNIARE_TYPE = 1
	--		ORDER BY SORTING_NO ASC
	--	END
	--ELSE IF @Flag = 2 -- For Functional Induction Process
	--	BEGIN
	--		SELECT DISTINCT EWC.Training_ID,HTM.Training_name,EWC.Emp_ID
	--			FROM T0040_HRMS_TRAINING_MASTER HTM 
	--				INNER JOIN T0030_HRMS_TRAINING_TYPE HTT ON HTT.TRAINING_TYPE_ID = HTM.TRAINING_TYPE
	--				INNER JOIN T0050_EMP_WISE_FUN_CHECKLIST EWC ON EWC.TRAINING_ID = HTM.TRAINING_ID
	--				--INNER JOIN T0150_HRMS_TRAINING_QUESTIONNAIRE HTQ ON CAST(HTQ.TRAINING_ID AS VARCHAR) = CAST(HTM.TRAINING_ID AS VARCHAR)
	--		WHERE HTM.CMP_ID = @CMP_ID AND ISNULL(HTT.TYPE_INDUCTION,0) = 1 AND EWC.EMP_ID = @EMP_ID AND HTT.Induction_Traning_Dept = 2
	--			  AND EWC.FILL_DATE <= GETDATE()
	--			  AND EXISTS(Select 1 From T0150_HRMS_TRAINING_QUESTIONNAIRE HTQ Where CHARINDEX(Cast(HTM.Training_id as Varchar(10)),HTQ.Training_Id) > 0)
	--	END
	ELSE IF @Flag = 4 -- For Functional Induction Process
		BEGIN
			SELECT DISTINCT F.TRAINING_QUE_ID,QUESTION,F.TRAINING_ID,F.CMP_ID,QUESTIONNIARE_TYPE,QUESTION_TYPE,
			CASE WHEN QUESTION_TYPE = 1 THEN 'Title' WHEN QUESTION_TYPE = 2 THEN 'Text' WHEN QUESTION_TYPE=3 THEN 'Paragraph Text' WHEN QUESTION_TYPE = 4 THEN 'Multiple Choice' WHEN QUESTION_TYPE=5 THEN 'CheckBoxList' WHEN QUESTION_TYPE = 6 THEN 'DropdownList' WHEN QUESTION_TYPE = 7 THEN 'Multiple Choice Grid' ELSE 'Paragraph Text' END  QUESTIONTYPE,
				SORTING_NO,QUESTION_OPTION,ANSWER AS ACTUALANSWER,F.MARKS AS ACTUALMARKS,
				ISNULL(QUESTION_ROW_TYPE,0) AS QUESTION_ROW_TYPE, Isnull(HTM.Training_MCP,0) as Passing_Criteria				
				FROM T0150_HRMS_TRAINING_QUESTIONNAIRE F WITH (NOLOCK)
			CROSS apply [dbo].[Split](F.TRAINING_ID, '#') as S
		--	INNER JOIN T0050_EMP_WISE_FUN_CHECKLIST EWC ON CAST(EWC.TRAINING_ID AS VARCHAR) = S.Data
			INNER JOIN T0040_HRMS_TRAINING_MASTER HTM WITH (NOLOCK) ON CAST(HTM.TRAINING_ID AS VARCHAR) = S.Data
			WHERE F.CMP_ID = @CMP_ID AND S.Data = @TRAINING_ID 	AND QUESTIONNIARE_TYPE = 1
			ORDER BY SORTING_NO ASC
		END
END

