




--************************************--
--*DEVELOPED BY GIRISH ON 30-APR-2010*--
---19/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
--************************************--
CREATE PROCEDURE [dbo].[SP_GET_RECORD_FOR_CHECKLIST]  
@Cmp_ID		numeric
,@From_Date datetime
,@To_Date datetime
,@Branch_ID		numeric   = 0
,@Cat_ID		numeric  = 0
,@Grd_ID		numeric = 0
,@Type_ID		numeric  = 0
,@Dept_ID		numeric  = 0
,@Desig_ID		numeric = 0
,@Emp_ID		numeric  = 0
,@Constraint	varchar(5000) = ''
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

 	if @Branch_ID = 0
		set @Branch_ID = null
	if @Cat_ID = 0
		set @Cat_ID = null
		 
	if @Type_ID = 0
		set @Type_ID = null
	if @Dept_ID = 0
		set @Dept_ID = null
	if @Grd_ID = 0
		set @Grd_ID = null
	if @Emp_ID = 0
		set @Emp_ID = null
		
	If @Desig_ID = 0
		set @Desig_ID = null
 	
   Declare @Emp_Cons Table
		(
			Emp_ID	numeric
		)
	
	if @Constraint <> ''
		begin
			Insert Into @Emp_Cons
			select  cast(data  as numeric) from dbo.Split (@Constraint,'#') 
		end
	else 
		begin
			Insert Into @Emp_Cons

			select I.Emp_Id from T0095_Increment I WITH (NOLOCK) inner join T0080_Emp_Master e WITH (NOLOCK) on i.Emp_ID = E.Emp_ID inner join 
					( select max(Increment_effective_Date) as For_Date , Emp_ID from T0095_Increment WITH (NOLOCK)
					--where Increment_Effective_date <= @To_Date
					Where Cmp_ID = @Cmp_ID
					group by emp_ID  ) Qry on
					I.Emp_ID = Qry.Emp_ID	and I.Increment_effective_Date = Qry.For_Date
			Where I.Cmp_ID = @Cmp_ID 
			and Isnull(I.Cat_ID,0) = Isnull(@Cat_ID ,Isnull(I.Cat_ID,0))
			and I.Branch_ID = isnull(@Branch_ID ,I.Branch_ID)
			and I.Grd_ID = isnull(@Grd_ID ,I.Grd_ID)
			and isnull(I.Dept_ID,0) = isnull(@Dept_ID ,isnull(I.Dept_ID,0))
			and Isnull(I.Type_ID,0) = isnull(@Type_ID ,Isnull(I.Type_ID,0))
			and Isnull(I.Desig_ID,0) = isnull(@Desig_ID ,Isnull(I.Desig_ID,0))
			and I.Emp_ID = isnull(@Emp_ID ,I.Emp_ID) 
			--and Date_of_Join >=@From_Date and Date_OF_Join <=@to_Date
		end	
		
		
	CREATE table #CHECKLIST_LABLE_GET 
	(
		TRAN_ID  NUMERIC(18, 0) NOT NULL,
		FIELD_NAME  VARCHAR(50) NOT NULL,
		FIELD_VALUE  VARCHAR(100),
		FLAG  CHAR(1)
	)
	DECLARE @CHECKLIST_LABLE_GET TABLE
	(
		CMP_ID NUMERIC(18,0),  --- ADDED BY FALAK ON 25-MAR-2011
		EMP_ID NUMERIC(18,0),
		EMP_FULL_NAME VARCHAR(50) NOT NULL, 
		TRAN_ID  NUMERIC(18, 0) NOT NULL,
		FIELD_NAME  VARCHAR(50) NOT NULL,
		FIELD_VALUE  VARCHAR(100),
		FLAG  CHAR(1),
		FINAL_NAME VARCHAR(150) ,
		COUNT NUMERIC(18,0),
		Row_Count numeric(18,0)
	)
	EXEC SP_GET_LABLE_FOR_CHECKLIST @Cmp_ID -- Changed by Falak on 25-MAR-2011
	
DECLARE @EMP_CODE VARCHAR(15)
DECLARE @EMP_FULL_NAME VARCHAR(150)
DECLARE @ENROLL_NO VARCHAR(15)
DECLARE @INITIAL VARCHAR(15)
DECLARE @FIRST_NAME VARCHAR(15)
DECLARE @SECOND_NAME VARCHAR(15)
DECLARE @LAST_NAME VARCHAR(15)
DECLARE @PHOTO VARCHAR(15) 
DECLARE @BRANCH VARCHAR(15)
DECLARE @GRADE VARCHAR(15)
DECLARE @DESIGNATION VARCHAR(15)
DECLARE @DEPARTMENT VARCHAR(15)
DECLARE @STATUS VARCHAR(15)
DECLARE @DATE_OF_JOIN VARCHAR(15)
DECLARE @SHIFT VARCHAR(15)
DECLARE @SALARY VARCHAR(15)
DECLARE @CTC VARCHAR(15)
DECLARE @MANAGER VARCHAR(15)
DECLARE @OVERTIME VARCHAR(15)
DECLARE @LATE_MARK VARCHAR(15)
DECLARE @FULL_PF VARCHAR(15)
DECLARE @PT VARCHAR(15)
DECLARE @FIX_SALARY VARCHAR(15)
DECLARE @PART_TIME VARCHAR(15)
DECLARE @PROBATION VARCHAR(15)
DECLARE @GENDER VARCHAR(15)
DECLARE @MARITIAL_STATUS VARCHAR(15)
DECLARE @DATE_OF_BIRTH VARCHAR(15)
DECLARE @PF_NO VARCHAR(15)
DECLARE @PT_NO VARCHAR(15)
DECLARE @ESIC_NO VARCHAR(15)
DECLARE @DRIVING_LICENSE VARCHAR(15)
DECLARE @EXPIRY_DATE_OF_LICENSE VARCHAR(15)
DECLARE @RELIGION VARCHAR(15)
DECLARE @HEIGHT VARCHAR(15)
DECLARE @MARK_IDENTIFICATION VARCHAR(15)
DECLARE @DISPENSARY VARCHAR(15)
DECLARE @DOCTOR_NAME VARCHAR(15)
DECLARE @DISPENSARY_ADDRESS VARCHAR(15)
DECLARE @INSURANCE_NO VARCHAR(15)
DECLARE @CONFIRMATION_DATE VARCHAR(15)
DECLARE @BLOOD_GROUP VARCHAR(15)
DECLARE @PERSONAL_EMAIL_ID VARCHAR(15)
DECLARE @PERMANENT_ADDRESS VARCHAR(15)
DECLARE @CITY VARCHAR(15)
DECLARE @STATE VARCHAR(15)
DECLARE @POST_BOX VARCHAR(15)
DECLARE @COUNTRY VARCHAR(15)
DECLARE @TEL_NO VARCHAR(15)
DECLARE @NATIONALITY VARCHAR(15)
DECLARE @OFFICE_NO VARCHAR(15)
DECLARE @MOBILE_NO VARCHAR(15)
DECLARE @WORKING_ADDRESS VARCHAR(15)
DECLARE @CITY_WORKING VARCHAR(15)
DECLARE @STATE_WORKING VARCHAR(15)
DECLARE @POST_BOX_WORKING VARCHAR(15)
DECLARE @OFFICIAL_EMAIL VARCHAR(15)

DECLARE @EMERGENCY_CONTACT NUMERIC(18,0)
DECLARE @DEPENDANTS NUMERIC(18,0)
DECLARE @CHILDREN NUMERIC(18,0)
DECLARE @IMMIGRATION NUMERIC(18,0)
DECLARE @ASSET NUMERIC(18,0)
DECLARE @CONTRACT_DETAIL NUMERIC(18,0)
DECLARE @SUPERWISER_REPORTING NUMERIC(18,0)
DECLARE @EXPERIENCE NUMERIC(18,0)
DECLARE @QUALIFICATION NUMERIC(18,0)
DECLARE @SKILL NUMERIC(18,0)
DECLARE @ATTACHMENT NUMERIC(18,0)

DECLARE @BANK VARCHAR(15)
DECLARE @CURRENCY VARCHAR(15)
DECLARE @WAGES_TYPE VARCHAR(15)
DECLARE @SALARY_ON VARCHAR(15)
DECLARE @PAYMENT_MODE VARCHAR(15)
DECLARE @ACCOUNT_NO VARCHAR(15)
DECLARE @LATE_LIMIT VARCHAR(15)
DECLARE @LATE_DEDUCTION_TYPE VARCHAR(15)
DECLARE @MIN_OVER_TIME VARCHAR(15)
DECLARE @MAX_OVER_TIME VARCHAR(15)
DECLARE @YEAR_LEAVE_DAYS VARCHAR(15)
DECLARE @YEAR_LEAVE_AMOUNT VARCHAR(15)
DECLARE @YEAR_BONUS_PER VARCHAR(15)
DECLARE @YEAR_BONUS_AMOUNT VARCHAR(15)
DECLARE @GRATUITY_APPLICABLE VARCHAR(15)
DECLARE @BONUS_YEARLY VARCHAR(15)
DECLARE @INCREMENT_ID NUMERIC(18,0)


DECLARE CUR_EMP CURSOR FOR
SELECT EMP_ID  FROM  @Emp_Cons
OPEN  CUR_EMP
FETCH NEXT FROM CUR_EMP INTO @EMP_ID
WHILE @@FETCH_STATUS = 0
	BEGIN
			SET @INCREMENT_ID=0
			
			Select  @EMP_FULL_NAME =Emp_full_Name from T0080_emp_Master WITH (NOLOCK) where cmp_id=@Cmp_ID and Emp_ID=@Emp_ID
			
			INSERT INTO @CHECKLIST_LABLE_GET
			SELECT @Cmp_Id,@EMP_ID,ISNULL(@EMP_FULL_NAME,''),TRAN_ID,FIELD_NAME,FIELD_VALUE,FLAG,'',0,0 FROM #CHECKLIST_LABLE_GET
			
			SELECT  @EMP_CODE=ISNULL(CAST(EMP_CODE AS VARCHAR(15)),''),
				    @ENROLL_NO=ISNULL(CAST(ENROLL_NO AS VARCHAR(15)),''), 	
				    @INITIAL=ISNULL(Initial,''),
				    @FIRST_NAME=ISNULL(Emp_First_Name,''),
		            @SECOND_NAME=ISNULL(Emp_Second_Name,''),
                    @LAST_NAME=ISNULL(Emp_Last_Name,''),
                    @PHOTO=ISNULL(Image_Name,''),
				    @BRANCH=ISNULL(CAST(BRANCH_ID AS VARCHAR(15)),''),	                  
                    @GRADE=ISNULL(CAST(GRD_ID AS VARCHAR(15)),''),
                    @DESIGNATION=ISNULL(CAST(DESIG_ID AS VARCHAR(15)),''),
				    @DEPARTMENT=ISNULL(CAST(DEPT_ID AS VARCHAR(15)),''),
				    @STATUS=ISNULL(CAST(TYPE_ID AS VARCHAR(15)),''),
				    @DATE_OF_JOIN=ISNULL(CAST(Date_Of_Join AS VARCHAR(15)),''),
					@SHIFT=ISNULL(CAST(SHIFT_ID AS VARCHAR(15)),''),
                    @SALARY=ISNULL(CAST(Basic_Salary AS VARCHAR(15)),''),
                    @CTC=ISNULL(CAST(GROSS_SALARY AS VARCHAR(15)),''),
					@OVERTIME=ISNULL(CAST(EMP_OT AS VARCHAR(15)),''),
					@LATE_MARK=ISNULL(CAST(EMP_LATE_MARK AS VARCHAR(15)),''),
					@FULL_PF=ISNULL(CAST(EMP_FULL_PF AS VARCHAR(15)),''),
					@PT=ISNULL(CAST(EMP_PT AS VARCHAR(15)),''),
					@FIX_SALARY=ISNULL(CAST(EMP_FIX_SALARY AS VARCHAR(15)),''),
					@PART_TIME=ISNULL(CAST(EMP_PART_TIME AS VARCHAR(15)),''),
					@PROBATION=ISNULL(CAST(IS_ON_PROBATION AS VARCHAR(15)),''),
					@GENDER=ISNULL(CAST(GENDER AS VARCHAR(15)),''),
					@MARITIAL_STATUS =ISNULL(CAST(MARITAL_STATUS AS VARCHAR(15)),''),
					@DATE_OF_BIRTH=ISNULL(CAST(DATE_OF_BIRTH AS VARCHAR(15)),''),
					@PF_NO=ISNULL(CAST(SIN_NO AS VARCHAR(15)),''),
					@PT_NO=ISNULL(CAST(PAN_NO AS VARCHAR(15)),''),
					@ESIC_NO=ISNULL(CAST(SSN_NO AS VARCHAR(15)),''),
					@DRIVING_LICENSE=ISNULL(CAST(DR_LIC_NO AS VARCHAR(15)),''),
					@EXPIRY_DATE_OF_LICENSE=ISNULL(CAST(DR_LIC_EX_DATE AS VARCHAR(15)),''),
					@RELIGION=ISNULL(CAST(RELIGION AS VARCHAR(15)),''),
					@HEIGHT=ISNULL(CAST(HEIGHT AS VARCHAR(15)),''),
					@MARK_IDENTIFICATION=ISNULL(CAST(Emp_Mark_Of_Identification AS VARCHAR(15)),''),
					@DISPENSARY=ISNULL(CAST(Despencery AS VARCHAR(15)),''),
					@DOCTOR_NAME=ISNULL(CAST(Doctor_Name AS VARCHAR(15)),''),
					@DISPENSARY_ADDRESS=ISNULL(CAST(DespenceryAddress AS VARCHAR(15)),''),
					@INSURANCE_NO=ISNULL(CAST(INSURANCE_NO AS VARCHAR(15)),''),
					@CONFIRMATION_DATE=ISNULL(CAST(Emp_Confirm_Date AS VARCHAR(15)),''),
					@BLOOD_GROUP=ISNULL(CAST(Blood_Group AS VARCHAR(15)),''),
					@PERSONAL_EMAIL_ID=ISNULL(CAST(Other_Email AS VARCHAR(15)),''),
					@PERMANENT_ADDRESS=ISNULL(CAST(STREET_1 AS VARCHAR(15)),''),
					@CITY=ISNULL(CAST(CITY AS VARCHAR(15)),''),
					@STATE=ISNULL(CAST(CITY AS VARCHAR(15)),''),
					@POST_BOX=ISNULL(CAST(ZIP_CODE AS VARCHAR(15)),''),
					@COUNTRY=ISNULL(CAST(LOC_ID AS VARCHAR(15)),''),
					@TEL_NO=ISNULL(CAST(HOME_TEL_NO AS VARCHAR(15)),''),
					@NATIONALITY=ISNULL(CAST(NATIONALITY AS VARCHAR(15)),''),
					@OFFICE_NO=ISNULL(CAST(WORK_TEL_NO AS VARCHAR(15)),''),
					@MOBILE_NO=ISNULL(CAST(MOBILE_NO AS VARCHAR(15)),''),
					@WORKING_ADDRESS=ISNULL(CAST(PRESENT_STREET AS VARCHAR(15)),''),
					@CITY_WORKING=ISNULL(CAST(PRESENT_CITY AS VARCHAR(15)),''),
					@STATE_WORKING=ISNULL(CAST(PRESENT_STATE AS VARCHAR(15)),''),
					@POST_BOX_WORKING=ISNULL(CAST(PRESENT_POST_BOX AS VARCHAR(15)),''),
					@OFFICIAL_EMAIL=ISNULL(CAST(WORK_EMAIL AS VARCHAR(15)),''),
					@MANAGER =ISNULL(CAST(EMP_SUPERIOR AS VARCHAR(15)),''),
					--DECLARE @EMERGENCY_CONTACT CHAR(1)
					--DECLARE @DEPENDANTS CHAR(1)
					--DECLARE @CHILDREN CHAR(1)
					--DECLARE @IMMIGRATION CHAR(1)
					--DECLARE @ASSET CHAR(1)
					--DECLARE @CONTRACT_DETAIL CHAR(1)
					--DECLARE @SUPERWISER_REPORTING CHAR(1)
					--DECLARE @EXPERIENCE CHAR(1)
					--DECLARE @QUALIFICATION CHAR(1)
					--DECLARE @SKILL CHAR(1)
					--DECLARE @ATTACHMENT CHAR(1)
					@BANK=ISNULL(CAST(BANK_ID AS VARCHAR(15)),''),
					@WAGES_TYPE=ISNULL(CAST(WAGES_TYPE AS VARCHAR(15)),''),
					@SALARY_ON=ISNULL(CAST(SALARY_BASIS_ON AS VARCHAR(15)),''),
					@PAYMENT_MODE=ISNULL(CAST(PAYMENT_MODE AS VARCHAR(15)),''),
					@ACCOUNT_NO=ISNULL(CAST(INC_BANK_AC_NO AS VARCHAR(15)),''),
					@LATE_LIMIT=ISNULL(CAST(EMP_LATE_LIMIT AS VARCHAR(15)),''),
					@LATE_DEDUCTION_TYPE=ISNULL(CAST(LATE_DEDU_TYPE AS VARCHAR(15)),''),
					@MIN_OVER_TIME=ISNULL(CAST(EMP_OT_MIN_LIMIT AS VARCHAR(15)),''),
					@MAX_OVER_TIME=ISNULL(CAST(EMP_OT_MAX_LIMIT AS VARCHAR(15)),''),
					@YEAR_LEAVE_DAYS=ISNULL(CAST(YEARLY_LEAVE_DAYS AS VARCHAR(15)),''),
					@YEAR_LEAVE_AMOUNT=ISNULL(CAST(YEARLY_LEAVE_AMOUNT AS VARCHAR(15)),''),
					@YEAR_BONUS_PER=ISNULL(CAST(YEARLY_BONUS_PER AS VARCHAR(15)),''),
					@YEAR_BONUS_AMOUNT=ISNULL(CAST(YEARLY_BONUS_AMOUNT AS VARCHAR(15)),''),
					@GRATUITY_APPLICABLE=ISNULL(CAST(IS_GR_APP AS VARCHAR(15)),''),
					@BONUS_YEARLY=ISNULL(CAST(IS_YEARLY_BONUS AS VARCHAR(15)),''),
					@INCREMENT_ID=INCREMENT_ID,@EMP_FULL_NAME=EMP_FULL_NAME
					FROM V0080_EMPLOYEE_MASTER WHERE EMP_ID=@EMP_ID
					
					
					IF @EMP_CODE = '0'
						SET @EMP_CODE=''
					IF 	@ENROLL_NO='0'
						SET @ENROLL_NO=''
					IF @PHOTO='1.jpg'
						SET  @PHOTO=''
					IF @SALARY='0.00'	
						SET @SALARY=''
					IF @CTC='0.00'	
						SET @CTC=''
					IF @OVERTIME='0'
						SET @OVERTIME=''
					IF @LATE_MARK='0'		
						SET @LATE_MARK=''
					IF @FULL_PF='0'
						SET @FULL_PF=''
					IF @PT='0'		
						SET @PT=''
					IF @FIX_SALARY='0'	
						SET @FIX_SALARY=''
					IF @PART_TIME='0'	
						SET @PART_TIME=''
					IF @PROBATION='0'
						SET @PROBATION=''
					IF @COUNTRY='0'
						SET @COUNTRY=''
					IF @MANAGER='0'
						SET @MANAGER=''
					IF @BANK='0'				
						SET @BANK=''
					IF @LATE_LIMIT='00:00'	
						SET @LATE_LIMIT=''
					IF @MIN_OVER_TIME='00:00'	
						SET @MIN_OVER_TIME=''
					IF @MAX_OVER_TIME='00:00'	
						SET @MAX_OVER_TIME=''
					IF @GRATUITY_APPLICABLE='0'
						SET @GRATUITY_APPLICABLE=''
					IF @BONUS_YEARLY='0'		
						SET @BONUS_YEARLY=''
					IF @INSURANCE_NO='0'
						SET @INSURANCE_NO=''
					IF @YEAR_LEAVE_DAYS='0.00'
						SET @YEAR_LEAVE_DAYS=''
					IF @YEAR_LEAVE_AMOUNT='0'
						SET @YEAR_LEAVE_AMOUNT=''
					IF @YEAR_BONUS_PER='0.00'
						SET @YEAR_BONUS_PER=''
					IF @YEAR_BONUS_AMOUNT='0.00'
						SET @YEAR_BONUS_AMOUNT=''
	
					DECLARE @TRAN_ID AS NUMERIC(18,0)
					SET @TRAN_ID=0
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@EMP_CODE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@EMP_FULL_NAME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@ENROLL_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@INITIAL WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@FIRST_NAME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@SECOND_NAME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@LAST_NAME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PHOTO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@BRANCH WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@GRADE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DESIGNATION WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DEPARTMENT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@STATUS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DATE_OF_JOIN WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@SHIFT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE= @SALARY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @CTC WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @MANAGER WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @OVERTIME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @LATE_MARK WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @FULL_PF WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=  @PT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@FIX_SALARY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PART_TIME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PROBATION WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@GENDER WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@MARITIAL_STATUS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DATE_OF_BIRTH WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PF_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PT_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@ESIC_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DRIVING_LICENSE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@EXPIRY_DATE_OF_LICENSE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@RELIGION WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@HEIGHT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@MARK_IDENTIFICATION WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DISPENSARY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DOCTOR_NAME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@DISPENSARY_ADDRESS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@INSURANCE_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@CONFIRMATION_DATE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@BLOOD_GROUP WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PERSONAL_EMAIL_ID WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PERMANENT_ADDRESS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@CITY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@STATE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@POST_BOX WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@COUNTRY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@TEL_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@NATIONALITY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@OFFICE_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@MOBILE_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@WORKING_ADDRESS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@CITY_WORKING WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@STATE_WORKING WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@POST_BOX_WORKING WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@OFFICIAL_EMAIL WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @EMERGENCY_CONTACT=0
					SELECT @EMERGENCY_CONTACT=COUNT(ROW_ID) FROM T0090_EMP_EMERGENCY_CONTACT_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @EMERGENCY_CONTACT > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@EMERGENCY_CONTACT AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @DEPENDANTS=0
					SELECT @DEPENDANTS=COUNT(ROW_ID) FROM T0090_EMP_DEPENDANT_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @DEPENDANTS > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@DEPENDANTS AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
						
					SET @TRAN_ID=@TRAN_ID+1
					SET @CHILDREN=0
					SELECT @CHILDREN=COUNT(ROW_ID) FROM T0090_EMP_CHILDRAN_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @CHILDREN > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@CHILDREN AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @IMMIGRATION=0
					SELECT @IMMIGRATION=COUNT(ROW_ID) FROM T0090_EMP_IMMIGRATION_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @IMMIGRATION > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@IMMIGRATION AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @ASSET=0
					SELECT @ASSET=COUNT(ASSET_ID) FROM T0090_EMP_ASSET_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @ASSET > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@ASSET AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @CONTRACT_DETAIL=0
					SELECT @CONTRACT_DETAIL=COUNT(TRAN_ID) FROM T0090_EMP_CONTRACT_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @CONTRACT_DETAIL > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@CONTRACT_DETAIL AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @SUPERWISER_REPORTING=0
					SELECT @SUPERWISER_REPORTING=COUNT(ROW_ID) FROM T0090_EMP_REPORTING_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @SUPERWISER_REPORTING > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@SUPERWISER_REPORTING AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
					
					SET @TRAN_ID=@TRAN_ID+1
					SET @EXPERIENCE=0
					SELECT @EXPERIENCE=COUNT(ROW_ID) FROM T0090_EMP_EXPERIENCE_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @EXPERIENCE > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@EXPERIENCE AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
				
					SET @TRAN_ID=@TRAN_ID+1
					SET @QUALIFICATION=0
					SELECT @QUALIFICATION=COUNT(ROW_ID) FROM T0090_EMP_QUALIFICATION_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @QUALIFICATION > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@QUALIFICATION AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
				
					SET @TRAN_ID=@TRAN_ID+1
					SET @SKILL=0
					SELECT @SKILL=COUNT(ROW_ID) FROM T0090_EMP_SKILL_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @SKILL > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@SKILL AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
				
					SET @TRAN_ID=@TRAN_ID+1
					SET @ATTACHMENT=0
					SELECT @ATTACHMENT=COUNT(ROW_ID) FROM T0090_EMP_DOC_DETAIL WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @ATTACHMENT > 0
						UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=CAST(@ATTACHMENT AS VARCHAR(15)) WHERE  EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID 
				
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@BANK WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@WAGES_TYPE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@SALARY_ON WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@PAYMENT_MODE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@ACCOUNT_NO WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@LATE_LIMIT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@LATE_DEDUCTION_TYPE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@MIN_OVER_TIME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@MAX_OVER_TIME WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@YEAR_LEAVE_DAYS WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@YEAR_LEAVE_AMOUNT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@YEAR_BONUS_PER WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@YEAR_BONUS_AMOUNT WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@GRATUITY_APPLICABLE WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					UPDATE @CHECKLIST_LABLE_GET
					SET FIELD_VALUE=@BONUS_YEARLY WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
					
					SET @TRAN_ID=@TRAN_ID+1
					DECLARE @WEEK_OFF AS VARCHAR(50)
					SELECT @WEEK_OFF = ISNULL(WEEKOFF_DAY,'') FROM T0100_WEEKOFF_ADJ WITH (NOLOCK) WHERE EMP_ID=@EMP_ID
					IF @WEEK_OFF<>''
							UPDATE @CHECKLIST_LABLE_GET SET FIELD_VALUE=@WEEK_OFF WHERE EMP_ID=@EMP_ID AND TRAN_ID=@TRAN_ID
							
					
						DECLARE @AD_ID NUMERIC(18,0)
						DECLARE @AD_NAME VARCHAR(100)
						DECLARE CUR_ALLO CURSOR FOR
						SELECT AD_ID,AD_NAME  FROM  V0100_EMP_EARN_DEDUCTION WHERE INCREMENT_ID=@INCREMENT_ID
						OPEN  CUR_ALLO
						FETCH NEXT FROM CUR_ALLO INTO @AD_ID,@AD_NAME
						WHILE @@FETCH_STATUS = 0
						BEGIN
							IF EXISTS(SELECT AD_NAME FROM V0100_EMP_EARN_DEDUCTION WHERE EMP_ID=@EMP_ID AND INCREMENT_ID=@INCREMENT_ID AND AD_NAME=@AD_NAME)
								BEGIN
									UPDATE @CHECKLIST_LABLE_GET SET FLAG='Y' WHERE FIELD_NAME=@AD_NAME AND EMP_ID=@EMP_ID
								END
								
					
						FETCH NEXT FROM CUR_ALLO INTO @AD_ID,@AD_NAME
						END
					CLOSE CUR_ALLO
					DEALLOCATE CUR_ALLO	
					
					

FETCH NEXT FROM CUR_EMP INTO @EMP_ID
	END
CLOSE CUR_EMP
DEALLOCATE CUR_EMP	
UPDATE @CHECKLIST_LABLE_GET SET FLAG='Y' WHERE FIELD_VALUE<>''


UPDATE @CHECKLIST_LABLE_GET SET FINAL_NAME=FIELD_VALUE WHERE (FIELD_NAME = 'EMP CODE' OR FIELD_NAME ='EMP FULL NAME')
UPDATE @CHECKLIST_LABLE_GET SET FINAL_NAME=FLAG WHERE  FINAL_NAME = ''

DECLARE @COUNT_EMPLOYEE NUMERIC(18,0)
select @COUNT_EMPLOYEE=ISNULL(count(distinct(emp_id)),0) from @CHECKLIST_LABLE_GET
UPDATE @CHECKLIST_LABLE_GET SET COUNT=@COUNT_EMPLOYEE 


Declare @Row_Count numeric(18,0)
select @Row_Count=Count(Tran_ID) from @CHECKLIST_LABLE_GET Group By Emp_ID 


Update @CHECKLIST_LABLE_GET set Row_Count=isnull(@Row_Count,0)



--Changed By Falak on 25-MAR-2011
if @Branch_id is null 
begin
	SELECT CHK.*,CM.Cmp_Name,CM.Cmp_Address,(null)as comp_name,(null)as Branch_Address

	FROM @CHECKLIST_LABLE_GET as CHK inner join T0010_Company_MAster CM WITH (NOLOCK)
	on CHK.cmp_id = CM.Cmp_id	--inner Join T0030_Branch_MAster BM
	--on CM.cmp_id = BM.cmp_id --where BM.Branch_ID = isnull(@Branch_ID,0)
	ORDER BY EMP_ID
end
else
begin

	SELECT CHK.*,CM.Cmp_Name,CM.Cmp_Address,BM.comp_name,BM.Branch_Address

	FROM @CHECKLIST_LABLE_GET as CHK inner join T0010_Company_MAster CM WITH (NOLOCK)
	on CHK.cmp_id = CM.Cmp_id	inner Join T0030_Branch_MAster BM WITH (NOLOCK)
	on CM.cmp_id = BM.cmp_id where BM.Branch_ID = isnull(@Branch_ID,0)
	ORDER BY EMP_ID
end
	
RETURN




