

-- =============================================
-- Author:		<Jaina>
-- Create date: <03-06-2016>
-- Description:	<Get Exit Scheme level>
---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[SP_Get_Exit_Scheme_Level]
@Cmp_id numeric(18,0),
	@Emp_id numeric(18,0)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

		SELECT ISNULL(MAX(RPT_LEVEL),0) AS MAX_LEVEL,SD.SCHEME_ID FROM T0050_SCHEME_DETAIL SD WITH (NOLOCK) INNER JOIN
		(

		   SELECT DISTINCT T.SCHEME_ID,T.EMP_ID,T.Cmp_ID  FROM T0095_EMP_SCHEME T WITH (NOLOCK) INNER JOIN 
			T0050_SCHEME_DETAIL T1 WITH (NOLOCK) ON T.SCHEME_ID = T1.SCHEME_ID  INNER JOIN
			(
				SELECT MAX(EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID FROM T0095_EMP_SCHEME WITH (NOLOCK)
							WHERE EMP_ID = @Emp_id AND TYPE = 'EXIT' AND EFFECTIVE_DATE <= GETDATE()
							GROUP BY EMP_ID 
			)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE= T.EFFECTIVE_DATE AND INNER_QRY.EMP_ID= T.EMP_ID 
			WHERE T.EMP_ID = @Emp_id AND T.Cmp_ID = @Cmp_id 
			AND TYPE = 'EXIT' 
		 
		)QRY ON QRY.SCHEME_ID = SD.SCHEME_ID
		GROUP BY SD.SCHEME_ID


END


