




--ALTER by Nilay
--ALTER IT FORM DESIGN FROM THE SP

--Insert form design -----
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_IT_INSERT_FORM_DESIGN]
	@Cmp_ID numeric(18,0),
	@Form_ID numeric(18,0)
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 1,  @Field_Name = 'Basic Salary',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 1, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 1, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 25, @Field_Name = '1. Gross Salary',										 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 26, @Field_Name = 'a Salary u/s 174(1)',									 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 1, @To_Row_ID = 25,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 27, @Field_Name = 'b Value of Perquisites u/s 17(2) (as per From 12 B',	 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 28, @Field_Name = 'c Profit in lieu of salary u/s 17(3) (as per Form 1',	 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 29, @Field_Name = 'd Total (a + b + c)',									 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 26,@To_Row_ID = 28,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 30, @Field_Name = '2 Less : Allowance to the extent exempt u/s. 10',		 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 31, @Field_Name = 'HRA',													 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 7, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 32, @Field_Name = 'Medical ',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 11,@Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 33, @Field_Name = 'Education',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 8, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 34, @Field_Name = 'Conveyance',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 9, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 39, @Field_Name = 'Total Allowance Exemption',								 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 31,@To_Row_ID = 34,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 40, @Field_Name = '3 Balance (1 - 2)',										 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 2, @From_Row_ID = 29,@To_Row_ID = 39,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 41, @Field_Name = '4. Deduction',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 42, @Field_Name = 'a. Tax on Employment',									 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 10,@Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 43, @Field_Name = '5. Aggregate of 4',										 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 42,@To_Row_ID = 42,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 44, @Field_Name = '6. Income Chargable under the Head ''Salaries(3-5)',	 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 2, @From_Row_ID = 40,@To_Row_ID = 43,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 45, @Field_Name = '7. Add: Income from other income reported the Employee', @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 46, @Field_Name = 'Capital Gain',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 47, @Field_Name = 'Income from oher source Total',							 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 48, @Field_Name = 'Total of 7',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 46,@To_Row_ID = 47,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 49, @Field_Name = '8. Gross Total Income (6 + 7)',							 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 1, @From_Row_ID = 44,@To_Row_ID = 48,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 50, @Field_Name = '9. Deduction under chapter VIA',						 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 51, @Field_Name = 'a. 80CCC',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 52, @Field_Name = 'b. 80CCD',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 53, @Field_Name = 'c. 80C',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 54, @Field_Name = '1. Equity Linked Saving Scheme',						 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 55, @Field_Name = '2. NSC',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 409,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 56, @Field_Name = '3. PPF',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 411,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 57, @Field_Name = '4.(a) EPF',												 @Field_Type = 0, @AD_ID = 46,@Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 58, @Field_Name = '5. Housing Loan Principal Repayment',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 416,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 59, @Field_Name = '6. L.I.C',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 414,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 60, @Field_Name = '7. Bank FD',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 410,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 61, @Field_Name = '8. Education',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 405,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 62, @Field_Name = '9.Other',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 63, @Field_Name = 'ULIP',													 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 413,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 64, @Field_Name = 'Pension Plan',											 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 415,	@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 65, @Field_Name = 'ELSS',													 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 66, @Field_Name = '10. Deduction under pension scheme',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 72, @Field_Name = 'Total (80CCC, 80CCD, 80C (1 To 10))',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 3, @From_Row_ID = 51,@To_Row_ID = 65,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '1', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 73, @Field_Name = '11. Infra Bond',										 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 20000,	@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 74, @Field_Name = 'Total (80C, 80CCC, 80CCD)',								 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 3, @From_Row_ID = 72,@To_Row_ID = 73,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '1', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 75, @Field_Name = 'd. Sec 80D - Mediclaim (Self/Family)',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 76, @Field_Name = 'e. 80DD',												 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 82, @Field_Name = 'g. 80GGC (Cont. To Political Party)',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 0, @From_Row_ID = 0, @To_Row_ID = 0, @Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '0', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 6, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 83, @Field_Name = '10. Aggregate of Chapter VIA (a to e)',					 @Field_Type = 0, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 3, @From_Row_ID = 72,@To_Row_ID = 82,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '1', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 8, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'
Exec P0100_IT_FORM_DESIGN @Tran_ID = 0 , @Cmp_ID = @Cmp_ID, @Format_Name = '', @Row_ID = 84, @Field_Name = '11. Total Taxable Income (8 - 10)',						 @Field_Type = 2, @AD_ID = 0, @Rimb_ID = 0, @Default_Def_Id = 0, @Is_Total = 2, @From_Row_ID = 49,@To_Row_ID = 83,@Multiple_Row_ID = '', @Is_Exempted = 0, @Max_Limit = 0,		@Max_Limit_Compare_Row_ID = 0, @Max_Limit_Compare_Type = '1', @Is_Proof_Req = 0, @Login_ID = 0, @IT_ID = 0,		@Form_ID = @Form_ID, @Col_No = 1, @Is_Show = 1, @Concate_Space = 0, @Is_Salary_Comp = 0, @Exem_Againt_Row_ID = 0, @tran_type = 'Inse'

RETURN




