



---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_LEAVE_CLOSING_AS_ON_DATE_KELEVEN]
	@CMP_ID		NUMERIC ,
	@EMP_ID		NUMERIC ,
	@FOR_DATE	DATETIME = null,
	@Leave_ID	numeric
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

		if Isnull(@For_Date,'') = '' 
			begin
				select @For_Date = max(For_Date) From T0140_LEAVE_TRANSACTION WITH (NOLOCK) where Emp_ID = @Emp_ID
			end
						
		declare @GRD_ID		NUMERIC
		select @GRD_ID = grd_id from t0080_emp_master WITH (NOLOCK) where emp_id = @EMP_ID and cmp_id = @CMP_ID 
				
		SELECT Leave_Opening,Leave_Used,LEAVE_CLOSING,LEAVE_CODE,LEAVE_NAME,LT.LEAVE_ID FROM T0140_LEAVE_TRANSACTION LT WITH (NOLOCK) INNER JOIN  
		(SELECT MAX(FOR_dATE) FOR_DATE , LEAVE_ID,EMP_ID FROM T0140_LEAVE_TRANSACTION WITH (NOLOCK)
		WHERE EMP_ID = @EMP_ID AND FOR_DATE <=@FOR_DATE AND LEAVE_ID in (Select Leave_ID from V0040_LEAVE_DETAILS Where Grd_ID=@GRD_ID) --and Leave_ID=@LEAVE_id
		GROUP BY EMP_ID,LEAVE_ID) Q ON LT.EMP_ID = Q.EMP_ID AND LT.LEAVE_ID = Q.LEAVE_ID AND 
		LT.FOR_DATE = Q.FOR_DATE INNER JOIN T0040_LEAVE_MASTER LM WITH (NOLOCK) ON LT.LEAVE_ID = LM.LEAVE_ID
		where LM.Display_leave_balance=1 --Add By Paras  15-03-2013 
	RETURN




