CREATE TABLE [dbo].[CHEQUE_PRINTING_SETUP] (
    [Company_ID]     NUMERIC (18)    NOT NULL,
    [Bank_ID]        NUMERIC (18)    NOT NULL,
    [Date_Top]       NUMERIC (20, 2) NOT NULL,
    [Date_Left]      NUMERIC (20, 2) NOT NULL,
    [Name_Top]       NUMERIC (20, 2) NOT NULL,
    [Name_Left]      NUMERIC (20, 2) NOT NULL,
    [Amount_Top]     NUMERIC (20, 2) NOT NULL,
    [Amount_Left]    NUMERIC (20, 2) NOT NULL,
    [AmtWords_Top]   NUMERIC (20, 2) NOT NULL,
    [AmtWords_Left]  NUMERIC (20, 2) NOT NULL,
    [AmtWords_Top2]  NUMERIC (20, 2) NOT NULL,
    [AmtWords_Left2] NUMERIC (20, 2) NOT NULL,
    [Cmp_Flag]       CHAR (1)        NOT NULL,
    [Sing_Flag]      CHAR (1)        NOT NULL,
    [Cmp_Top]        NUMERIC (18, 2) NOT NULL,
    [Cmp_Left]       NUMERIC (18, 2) NOT NULL,
    [Sing_Top]       NUMERIC (18, 2) NOT NULL,
    [Sing_left]      NUMERIC (18, 2) NOT NULL,
    [Cmp_Name]       VARCHAR (120)   NOT NULL,
    [Payee_Flag]     CHAR (1)        NOT NULL,
    [Payee_Top]      NUMERIC (18, 2) NOT NULL,
    [Payee_Left]     NUMERIC (18, 2) NOT NULL,
    [AcNO_Flag]      CHAR (1)        NOT NULL,
    [AcNo_Top]       NUMERIC (18, 2) NOT NULL,
    [AcNo_Left]      NUMERIC (18, 2) NOT NULL,
    [OverThan_Flag]  CHAR (1)        NOT NULL,
    [OverThan_Top]   NUMERIC (18, 2) NOT NULL,
    [OverThan_Left]  NUMERIC (18, 2) NOT NULL,
    [Director_Flag]  CHAR (1)        NOT NULL,
    [Director_Top]   NUMERIC (18, 2) NOT NULL,
    [Director_Left]  NUMERIC (18, 2) NOT NULL,
    [Director_Name]  VARCHAR (100)   NULL,
    [Bearer_Flag]    CHAR (1)        NOT NULL,
    [Bearer_Top]     NUMERIC (18, 2) NOT NULL,
    [Bearer_Left]    NUMERIC (18, 2) NOT NULL,
    [User_ID]        NUMERIC (18)    NULL,
    [System_Date]    DATETIME        NULL,
    [FormName]       VARCHAR (50)    NULL,
    [Exec_Trigger]   CHAR (1)        CONSTRAINT [DF_CHEQUE_PRINTING_SETUP_Exec_Trigger] DEFAULT ('Y') NOT NULL,
    CONSTRAINT [PK_CHEQUE_PRINTING_SETUP] PRIMARY KEY CLUSTERED ([Company_ID] ASC, [Bank_ID] ASC) WITH (FILLFACTOR = 80)
);

