CREATE TABLE [dbo].[EMP_FOR_FNF_ALLOWANCE] (
    [Tran_Id]  NUMERIC (18)    NOT NULL,
    [Cmp_id]   NUMERIC (18)    NOT NULL,
    [Emp_id]   NUMERIC (18)    NOT NULL,
    [AD_Id]    NUMERIC (18)    NOT NULL,
    [For_Date] DATETIME        NOT NULL,
    [Amount]   NUMERIC (12, 2) CONSTRAINT [DF_EMP_FOR_FNF_ALLOWANCE_Amount] DEFAULT ((0)) NOT NULL,
    [AD_Flag]  NVARCHAR (2)    NULL,
    [Comments] VARCHAR (500)   NULL,
    CONSTRAINT [PK_EMP_FOR_FNF_ALLOWANCE] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_EMP_FOR_FNF_ALLOWANCE_EMP_FOR_FNF_ALLOWANCE] FOREIGN KEY ([Cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_EMP_FOR_FNF_ALLOWANCE_T0050_AD_MASTER] FOREIGN KEY ([AD_Id]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID]),
    CONSTRAINT [FK_EMP_FOR_FNF_ALLOWANCE_T0080_EMP_MASTER] FOREIGN KEY ([Emp_id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

