CREATE TABLE [dbo].[Emp_Inout_Temp] (
    [Tran_Id]                       NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [emp_id]                        NUMERIC (18)   NOT NULL,
    [for_Date]                      DATETIME       NOT NULL,
    [Dept_id]                       NUMERIC (18)   NULL,
    [Grd_ID]                        NUMERIC (18)   NULL,
    [Type_ID]                       NUMERIC (18)   NULL,
    [Desig_ID]                      NUMERIC (18)   NULL,
    [Shift_ID]                      NUMERIC (18)   NULL,
    [In_Time]                       DATETIME       NULL,
    [Out_Time]                      DATETIME       NULL,
    [Duration]                      VARCHAR (100)  NULL,
    [Duration_sec]                  NUMERIC (18)   NULL,
    [Late_In]                       VARCHAR (100)  NULL,
    [Late_Out]                      VARCHAR (100)  NULL,
    [Early_In]                      VARCHAR (100)  NULL,
    [Early_Out]                     VARCHAR (100)  NULL,
    [Leave]                         VARCHAR (100)  NULL,
    [Shift_Sec]                     NUMERIC (18)   NULL,
    [Shift_Dur]                     VARCHAR (100)  NULL,
    [Total_work]                    VARCHAR (100)  NULL,
    [Less_Work]                     VARCHAR (100)  NULL,
    [More_Work]                     VARCHAR (100)  NULL,
    [Reason]                        VARCHAR (1000) NULL,
    [AB_LEAVE]                      VARCHAR (100)  NULL,
    [Late_In_Sec]                   NUMERIC (18)   NULL,
    [Late_In_count]                 NUMERIC (18)   NULL,
    [Early_Out_sec]                 NUMERIC (18)   NULL,
    [Early_Out_Count]               NUMERIC (18)   NULL,
    [Total_Less_work_Sec]           NUMERIC (18)   NULL,
    [Shift_St_Datetime]             DATETIME       NULL,
    [Shift_en_Datetime]             DATETIME       NULL,
    [Working_Sec_AfterShift]        NUMERIC (18)   NULL,
    [Working_AfterShift_Count]      NUMERIC (18)   NULL,
    [Leave_Reason]                  VARCHAR (1000) NULL,
    [Inout_Reason]                  VARCHAR (1000) NULL,
    [SysDate]                       DATETIME       NULL,
    [Total_Work_Sec]                NUMERIC (18)   NULL,
    [Late_Out_Sec]                  NUMERIC (18)   NULL,
    [Early_In_sec]                  NUMERIC (18)   NULL,
    [Total_More_work_Sec]           NUMERIC (18)   NULL,
    [Is_OT_Applicable]              TINYINT        NULL,
    [Monthly_Deficit_Adjust_OT_Hrs] TINYINT        NULL,
    [Late_Comm_sec]                 NUMERIC (18)   NULL,
    [Branch_Id]                     NUMERIC (18)   NULL,
    CONSTRAINT [PK_Emp_Inout_Temp] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80)
);

