CREATE TABLE [dbo].[EMP_FNF_ALLOWANCE_DETAILS] (
    [Tran_ID]   NUMERIC (18) NOT NULL,
    [Emp_ID]    NUMERIC (18) NOT NULL,
    [Ad_ID]     NUMERIC (18) NOT NULL,
    [From_Date] DATETIME     NOT NULL,
    [To_Date]   DATETIME     NOT NULL,
    [FNF_ID]    NUMERIC (18) NULL,
    [Cmp_Id]    NUMERIC (18) NOT NULL,
    CONSTRAINT [FK_EMP_FNF_ALLOWANCE_DETAILS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

