CREATE TABLE [dbo].[ExmptTable] (
    [Alpha_Emp_Code]   VARCHAR (500) NULL,
    [Emp_Full_Name]    VARCHAR (500) NULL,
    [Branch_Name]      VARCHAR (500) NULL,
    [Grd_Name]         VARCHAR (500) NULL,
    [Desig_Name]       VARCHAR (500) NULL,
    [Dept_Name]        VARCHAR (500) NULL,
    [Emp_ID]           NUMERIC (18)  NULL,
    [Cmp_ID]           NUMERIC (18)  NULL,
    [Cmp_Name]         VARCHAR (500) NULL,
    [Cmp_Address]      VARCHAR (500) NULL,
    [In_Time]          DATETIME      NULL,
    [Out_Time]         DATETIME      NULL,
    [Shift_St_Time]    DATETIME      NULL,
    [Shift_End_Time]   DATETIME      NULL,
    [Late_Hours]       VARCHAR (500) NULL,
    [Early_Hours]      VARCHAR (500) NULL,
    [Late_Limit]       VARCHAR (500) NULL,
    [Early_Limit]      VARCHAR (500) NULL,
    [Late_Deduction]   VARCHAR (500) NULL,
    [Early_Deduction]  VARCHAR (500) NULL,
    [For_Date]         DATETIME      NULL,
    [Type_Name]        VARCHAR (500) NULL,
    [Vertical_Name]    VARCHAR (500) NULL,
    [SubVertical_Name] VARCHAR (500) NULL,
    [Branch_Address]   VARCHAR (500) NULL,
    [Comp_Name]        VARCHAR (500) NULL,
    [Dept_Dis_no]      VARCHAR (400) NULL,
    [From_Date]        DATETIME      NULL,
    [To_Date]          DATETIME      NULL,
    [ExemptFlag]       VARCHAR (10)  NULL
);

