CREATE TABLE [dbo].[SalTemp] (
    [Emp_Name]               VARCHAR (50)    NULL,
    [Grd_Name]               VARCHAR (50)    NULL,
    [Comp_Name]              VARCHAR (50)    NULL,
    [Branch_Address]         VARCHAR (MAX)   NULL,
    [Emp_Code]               VARCHAR (50)    NULL,
    [Type_Name]              VARCHAR (50)    NULL,
    [Dept_Name]              VARCHAR (50)    NULL,
    [Design_Name]            VARCHAR (50)    NULL,
    [Emp_First_Name]         VARCHAR (50)    NULL,
    [AD_Name]                VARCHAR (50)    NULL,
    [AD_Level]               VARCHAR (50)    NULL,
    [Emp_ID]                 NUMERIC (18)    NULL,
    [Cmp_ID]                 NUMERIC (18)    NULL,
    [AD_ID]                  NUMERIC (18)    NULL,
    [SalTran_ID]             NUMERIC (18)    NULL,
    [AD_Description]         VARCHAR (MAX)   NULL,
    [AD_Amount]              NUMERIC (18, 2) NULL,
    [AD_Actual_Amount]       NUMERIC (18, 2) NULL,
    [AD_Calc_Amount]         NUMERIC (18, 2) NULL,
    [For_Date]               DATETIME        NULL,
    [M_AD_Flag]              VARCHAR (10)    NULL,
    [Loan_ID]                NUMERIC (18)    NULL,
    [Def_ID]                 NUMERIC (18)    NULL,
    [M_Arrear_Days]          NUMERIC (18, 2) NULL,
    [YTD]                    NUMERIC (18, 2) NULL,
    [AD_Amt_OnBasic_For_Per] NUMERIC (18, 2) NULL,
    [Branch_ID]              NUMERIC (18, 2) NULL,
    [Alpha_Emp_Code]         VARCHAR (50)    NULL
);

