CREATE TABLE [dbo].[SAP_GDAPIdata_Import] (
    [id]                       INT            IDENTITY (1, 1) NOT NULL,
    [Personnel_number_PERNR]   VARCHAR (8)    NOT NULL,
    [End_Date_ENDDA]           VARCHAR (10)   NULL,
    [StartDate_BEGDA]          VARCHAR (10)   NULL,
    [Action_Type_MASSN]        VARCHAR (2)    NULL,
    [ReasonforAction_MASSG]    VARCHAR (2)    NULL,
    [Employment_STAT2]         VARCHAR (1)    NULL,
    [CompanyCode_BUKRS]        VARCHAR (2)    NULL,
    [Contract_ANSVH]           VARCHAR (2)    NULL,
    [CostCenter_KOSTL]         VARCHAR (10)   NULL,
    [Form_Addr_ANRED]          VARCHAR (1)    NULL,
    [LastName_NACHN]           VARCHAR (40)   NULL,
    [FirstName_VORNA]          VARCHAR (40)   NULL,
    [Title_Designation_TITEL]  VARCHAR (15)   NULL,
    [MiddleName_MIDNM]         VARCHAR (40)   NULL,
    [Gender_GESCH]             VARCHAR (1)    NULL,
    [Birthdate_GBDAT]          VARCHAR (10)   NULL,
    [Nationality_NATIO]        VARCHAR (3)    NULL,
    [Other_nat_NATI2]          VARCHAR (3)    NULL,
    [MaritalStatus_FAMST]      VARCHAR (1)    NULL,
    [Since_FAMDT]              VARCHAR (10)   NULL,
    [No_child_ANZKD]           VARCHAR (3)    NULL,
    [BankKey_BANKL]            VARCHAR (15)   NULL,
    [BankAccount_BANKN]        VARCHAR (18)   NULL,
    [ProbPeriod_PRBZT]         VARCHAR (3)    NULL,
    [ProbationaryPeriod_PRBEH] VARCHAR (10)   NULL,
    [IDnumber_USRID_0010]      VARCHAR (241)  NULL,
    [IDNumber_USRID_0035]      VARCHAR (241)  NULL,
    [CDTM]                     DATETIME       CONSTRAINT [df_cdtmI] DEFAULT (getdate()) NULL,
    [UDTM]                     DATETIME       CONSTRAINT [df_udtmI] DEFAULT (getdate()) NULL,
    [Logdt]                    NVARCHAR (250) NULL,
    [Flag_Done]                INT            CONSTRAINT [df_FlagDoneI] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__SAP_GDAPI__3213E83FD46542CA] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 95)
);

