CREATE TABLE [dbo].[SAP_TITLE] (
    [TITLE_ID] INT            IDENTITY (1, 1) NOT NULL,
    [TITLE]    VARCHAR (50)   NULL,
    [Alias]    NVARCHAR (100) NULL,
    CONSTRAINT [PK_SAP_TITLE] PRIMARY KEY CLUSTERED ([TITLE_ID] ASC) WITH (FILLFACTOR = 95)
);

