CREATE TABLE [dbo].[sumcheck_sum] (
    [Sr_No]                               BIGINT           NULL,
    [EMP_CODE]                            VARCHAR (53)     NULL,
    [Emp_Full_Name]                       VARCHAR (8000)   NULL,
    [Branch]                              VARCHAR (100)    NULL,
    [Branch_State]                        VARCHAR (100)    NULL,
    [vertical_name]                       VARCHAR (100)    NULL,
    [subvertical_name]                    VARCHAR (100)    NULL,
    [Department]                          VARCHAR (100)    NULL,
    [Designation]                         VARCHAR (100)    NULL,
    [Grade]                               VARCHAR (100)    NULL,
    [BandName]                            VARCHAR (100)    NULL,
    [TypeName]                            VARCHAR (100)    NULL,
    [Cost_Center]                         VARCHAR (100)    NULL,
    [Center_Code]                         VARCHAR (25)     NULL,
    [Cost_Element]                        VARCHAR (25)     NULL,
    [Category]                            VARCHAR (100)    NULL,
    [Subbranch_name]                      NVARCHAR (100)   NULL,
    [Segment_Name]                        VARCHAR (100)    NULL,
    [Enroll_NO]                           NUMERIC (18)     NULL,
    [Joining_Date]                        VARCHAR (30)     NULL,
    [Left_Date]                           VARCHAR (30)     NOT NULL,
    [Pan_No]                              VARCHAR (30)     NULL,
    [Aadhar_Card_No]                      VARCHAR (50)     NULL,
    [Date_Of_Birth]                       VARCHAR (30)     NULL,
    [Mobile_No]                           VARCHAR (30)     NULL,
    [Official_Email]                      VARCHAR (50)     NULL,
    [Month_Days]                          NUMERIC (18, 2)  NOT NULL,
    [Present_Day]                         NUMERIC (18, 2)  NOT NULL,
    [Absent_Day]                          NUMERIC (38, 8)  NULL,
    [holiday_day]                         NUMERIC (18, 2)  NOT NULL,
    [Weekoff_Day]                         NUMERIC (18, 2)  NOT NULL,
    [Total_Paid_Leave_Days]               NUMERIC (19, 2)  NULL,
    [Unpaid]                              INT              NOT NULL,
    [Total_Leave_Days]                    NUMERIC (18, 2)  NULL,
    [Late_Days]                           NUMERIC (5, 2)   NULL,
    [Early_Days]                          NUMERIC (5, 2)   NULL,
    [Sal_Cal_Day]                         NUMERIC (18, 2)  NOT NULL,
    [Arear_Day]                           NUMERIC (20, 3)  NULL,
    [Arear_Day_Month]                     NUMERIC (18)     NULL,
    [Present_on_holiday]                  NUMERIC (18, 2)  NOT NULL,
    [Basic_Actual]                        NUMERIC (18, 4)  NULL,
    [Children_Education_Allowance_Actual] NUMERIC (38, 2)  NOT NULL,
    [Company_ESIC_Actual]                 NUMERIC (38, 2)  NOT NULL,
    [Company_PF_Actual]                   NUMERIC (38, 2)  NOT NULL,
    [Gross_Salary_Actual]                 NUMERIC (38, 4)  NULL,
    [Non_Gross_Salary_Actual]             NUMERIC (38, 2)  NULL,
    [Total_Auto_Paid_Salary_Actual]       INT              NOT NULL,
    [CTC_Actual]                          NUMERIC (38, 2)  NULL,
    [PT_Amount_Actual]                    NUMERIC (5)      NULL,
    [Employee_PF_Actual]                  NUMERIC (38, 2)  NOT NULL,
    [ESIC_Actual]                         NUMERIC (38, 2)  NOT NULL,
    [Total_Deduction_Actual]              NUMERIC (38, 2)  NULL,
    [Net_Amount_Actual]                   NUMERIC (38, 2)  NULL,
    [Basic_Salary]                        NUMERIC (18, 2)  NULL,
    [Settl_Salary]                        NUMERIC (18)     NOT NULL,
    [Other_Allow]                         NUMERIC (18, 2)  NULL,
    [Children_Education_Allowance]        NUMERIC (38, 2)  NOT NULL,
    [Total_Earning]                       NUMERIC (38, 2)  NULL,
    [Basic_Salary_Arrear]                 NUMERIC (38, 2)  NULL,
    [Arears]                              INT              NOT NULL,
    [Total_Arrear_Earning]                NUMERIC (38, 2)  NULL,
    [Holiday_OT_Hours]                    NUMERIC (18, 2)  NOT NULL,
    [Holiday_OT_Amount]                   NUMERIC (18, 2)  NOT NULL,
    [Weekoff_OT_Hours]                    NUMERIC (18, 2)  NOT NULL,
    [Weekoff_OT_Amount]                   NUMERIC (18, 2)  NOT NULL,
    [Ot_Rate]                             NUMERIC (38, 20) NULL,
    [OT_Hours]                            NUMERIC (18, 2)  NOT NULL,
    [OT_Amount]                           NUMERIC (18, 2)  NOT NULL,
    [WeekDay_Fix_OT_Rate]                 NUMERIC (18, 3)  NOT NULL,
    [WO_HO_Fix_OT_Rate]                   NUMERIC (18, 3)  NOT NULL,
    [Grade_OT_Hours]                      NUMERIC (22, 6)  NOT NULL,
    [leave_Encash_Amount]                 NUMERIC (18)     NOT NULL,
    [Travel_Amount]                       NUMERIC (18, 2)  NOT NULL,
    [Total_Claim_Amount]                  NUMERIC (18, 3)  NOT NULL,
    [Uniform_Refund_Amount]               NUMERIC (18, 2)  NOT NULL,
    [Gross_Salary]                        NUMERIC (38, 2)  NULL,
    [PT_Amount]                           NUMERIC (18, 2)  NULL,
    [Home_Loan]                           NUMERIC (38, 2)  NULL,
    [Bond_Amount]                         NUMERIC (18, 2)  NOT NULL,
    [Advance_Amount]                      NUMERIC (18, 2)  NOT NULL,
    [Employee_PF]                         NUMERIC (38, 2)  NOT NULL,
    [ESIC]                                NUMERIC (38, 2)  NOT NULL,
    [Revenue_Amount]                      NUMERIC (18)     NULL,
    [LWF_Amount]                          NUMERIC (18)     NOT NULL,
    [Other_Dedu]                          NUMERIC (18, 2)  NOT NULL,
    [Gate_Pass_Amount]                    NUMERIC (18, 2)  NOT NULL,
    [Asset_Installment_Amount]            NUMERIC (18, 2)  NOT NULL,
    [Uniform_Installment_Amount]          NUMERIC (18, 2)  NOT NULL,
    [Late_Dedu_Amount]                    NUMERIC (18)     NOT NULL,
    [Total_Deduction]                     NUMERIC (38, 2)  NULL,
    [Arear_Deduction]                     INT              NOT NULL,
    [Total_Arrear_Deduction]              INT              NOT NULL,
    [Net_Total_Deduction]                 NUMERIC (38, 2)  NULL,
    [Net_Salary]                          NUMERIC (19, 2)  NULL,
    [Net_Round]                           NUMERIC (18, 2)  NOT NULL,
    [Travel_Advance_Amount]               NUMERIC (18, 2)  NOT NULL,
    [Total_Net]                           NUMERIC (18, 2)  NULL,
    [Company_ESIC]                        NUMERIC (38, 2)  NOT NULL,
    [Company_PF]                          NUMERIC (38, 2)  NOT NULL,
    [Employer_PF_Contribution_Arear]      INT              NOT NULL,
    [Total_Emp_Contribution]              NUMERIC (38, 2)  NOT NULL,
    [Total_CTC_Salary]                    NUMERIC (38, 2)  NULL,
    [Other_Allowance_C]                   INT              NOT NULL,
    [salary_Status]                       VARCHAR (20)     NULL,
    [Payment_Mode]                        VARCHAR (20)     NULL,
    [Bank_Name]                           VARCHAR (100)    NULL,
    [Inc_Bank_AC_No]                      VARCHAR (23)     NULL,
    [Bank_Branch_Name]                    VARCHAR (2000)   NULL,
    [Bank_IFSC_Code]                      VARCHAR (50)     NULL,
    [UAN_No]                              VARCHAR (103)    NULL,
    [ESIC_No]                             VARCHAR (33)     NULL,
    [PF_No]                               VARCHAR (33)     NULL,
    [Desig_dis_No]                        NUMERIC (18)     NULL,
    [Gender]                              CHAR (1)         NULL,
    [PF_WAGES]                            NUMERIC (18, 5)  NULL,
    [ESI_WAGES]                           NUMERIC (18, 5)  NULL,
    [Qualification]                       NVARCHAR (MAX)   NULL,
    [Marital_Status]                      VARCHAR (9)      NULL,
    [Month_Year]                          NVARCHAR (8)     NULL
);

