CREATE TABLE [dbo].[T0001_SCHEME_MASTER] (
    [Scm_Id]      NUMERIC (18)  NOT NULL,
    [Scheme]      VARCHAR (100) NOT NULL,
    [Module_Name] VARCHAR (100) NULL,
    [Modify_Date] DATETIME      NOT NULL,
    CONSTRAINT [PK_T0001_SCHEME_MASTER] PRIMARY KEY CLUSTERED ([Scm_Id] ASC) WITH (FILLFACTOR = 80)
);

