CREATE TABLE [dbo].[T0000_SYNC_METHOD] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [METHOD_NAME] VARCHAR (512) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0000_SYNC_METHOD]
    ON [dbo].[T0000_SYNC_METHOD]([METHOD_NAME] ASC);

