CREATE TABLE [dbo].[T0001_LEAVECF_NightProcess_History] (
    [LEAVE_CF_ID]                   NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [Cmp_ID]                        NUMERIC (18)    NOT NULL,
    [Branch_ID]                     NUMERIC (18)    NOT NULL,
    [Grd_ID]                        NUMERIC (18)    NULL,
    [Dept_ID]                       NUMERIC (18)    NULL,
    [Desig_ID]                      NUMERIC (18)    NULL,
    [Cat_ID]                        NUMERIC (18)    NULL,
    [Type_ID]                       NUMERIC (18)    NULL,
    [Segment_ID]                    NUMERIC (18)    NULL,
    [subBranch_ID]                  NUMERIC (18)    NULL,
    [Vertical_ID]                   NUMERIC (18)    NULL,
    [SubVertical_ID]                NUMERIC (18)    NULL,
    [Emp_ID]                        NUMERIC (18)    NOT NULL,
    [Leave_ID]                      NUMERIC (18)    NOT NULL,
    [CF_For_Date]                   DATETIME        NOT NULL,
    [CF_From_Date]                  DATETIME        NOT NULL,
    [CF_To_Date]                    DATETIME        NOT NULL,
    [CF_P_Days]                     NUMERIC (18, 2) NOT NULL,
    [CF_Leave_Days]                 NUMERIC (22, 8) NOT NULL,
    [CF_Type]                       VARCHAR (200)   NOT NULL,
    [Exceed_CF_Days]                NUMERIC (22, 8) NULL,
    [Leave_CompOff_Dates]           NVARCHAR (10)   NULL,
    [Is_Fnf]                        VARCHAR (5)     NOT NULL,
    [Alpha_Emp_Code]                NVARCHAR (100)  NULL,
    [Emp_Full_Name]                 NVARCHAR (100)  NULL,
    [Leave_Name]                    NVARCHAR (100)  NULL,
    [new_join_flag]                 VARCHAR (5)     NULL,
    [date_of_join]                  VARCHAR (100)   NULL,
    [diff]                          VARCHAR (10)    NULL,
    [Advance_Leave_Balance]         NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Advance_Leave_Recover_balance] NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Is_Advance_Leave_Balance]      TINYINT         DEFAULT ((0)) NOT NULL,
    [Month]                         TINYINT         NULL,
    [Year]                          INT             NULL,
    [SystemDate]                    DATETIME        NULL
);

