CREATE TABLE [dbo].[T0000_PATCH_LOG] (
    [ID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [LOG_DATE]  DATETIME       NULL,
    [FILE_DATE] DATETIME       NULL,
    [FILE_PATH] VARCHAR (1024) NULL,
    [APP_VER]   VARCHAR (32)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

