CREATE TABLE [dbo].[T0015_LOGIN_FORM_RIGHTS] (
    [Tran_ID]   NUMERIC (18) NOT NULL,
    [Login_Id]  NUMERIC (18) NOT NULL,
    [Cmp_ID]    NUMERIC (18) NOT NULL,
    [Form_ID]   NUMERIC (18) NOT NULL,
    [Is_Save]   TINYINT      NOT NULL,
    [Is_Delete] TINYINT      NOT NULL,
    [Is_Edit]   TINYINT      NOT NULL,
    [Is_View]   TINYINT      NOT NULL,
    [Is_Print]  TINYINT      NOT NULL,
    CONSTRAINT [PK_T0015_LOGIN_FORM_RIGHTS] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0015_LOGIN_FORM_RIGHTS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0015_LOGIN_FORM_RIGHTS_T0011_LOGIN] FOREIGN KEY ([Login_Id]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID])
);

