CREATE TABLE [dbo].[T0015_LOGIN_RIGHTS] (
    [Login_Rights_ID] NUMERIC (18) NOT NULL,
    [Login_Type_ID]   NUMERIC (18) NOT NULL,
    [Branch_ID]       NUMERIC (18) NULL,
    [Cmp_ID]          NUMERIC (18) NOT NULL,
    [Login_ID]        NUMERIC (18) NOT NULL,
    [Is_Save]         NUMERIC (1)  NOT NULL,
    [Is_Edit]         NUMERIC (1)  NOT NULL,
    [Is_Delete]       NUMERIC (1)  NOT NULL,
    [Is_Report]       NUMERIC (1)  NOT NULL,
    CONSTRAINT [PK_T0015_LOGIN_RIGHTS] PRIMARY KEY CLUSTERED ([Login_Rights_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0015_LOGIN_RIGHTS_T0001_LOGIN_TYPE] FOREIGN KEY ([Login_Type_ID]) REFERENCES [dbo].[T0001_LOGIN_TYPE] ([Login_Type_ID]),
    CONSTRAINT [FK_T0015_LOGIN_RIGHTS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0015_LOGIN_RIGHTS_T0011_LOGIN] FOREIGN KEY ([Login_ID]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID])
);

