CREATE TABLE [dbo].[T0011_OTP_TRANSACTIONS] (
    [Otp_ID]      NUMERIC (18)  NOT NULL,
    [Otp_TypeID]  NUMERIC (18)  NOT NULL,
    [Emp_ID]      NUMERIC (18)  NOT NULL,
    [Cmp_ID]      NUMERIC (18)  NOT NULL,
    [Otp_Code]    INT           NOT NULL,
    [CreatedDate] DATETIME      NULL,
    [ExpiredDate] DATETIME      NULL,
    [IsVerified]  BIT           NULL,
    [Email]       VARCHAR (150) NULL,
    [MobileNo]    VARCHAR (20)  NULL,
    CONSTRAINT [PK_T0011_OTP_TRANSACTIONS] PRIMARY KEY CLUSTERED ([Otp_ID] ASC),
    CONSTRAINT [FK_T0011_OTP_TRANSACTIONS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0011_OTP_TRANSACTIONS_T0011_OTPMASTER] FOREIGN KEY ([Otp_TypeID]) REFERENCES [dbo].[T0011_OTPMASTER] ([Otp_TypeID])
);

