CREATE TABLE [dbo].[T0011_OTPMASTER] (
    [Otp_TypeID]    NUMERIC (18) NOT NULL,
    [Otp_Type]      VARCHAR (50) NOT NULL,
    [Otp_Type_Code] VARCHAR (20) NOT NULL,
    CONSTRAINT [PK_T0011_OTPMASTER] PRIMARY KEY CLUSTERED ([Otp_TypeID] ASC)
);

