CREATE TABLE [dbo].[T0015_LOGIN_BRANCH_RIGHTS] (
    [Tran_Id]   NUMERIC (18) NOT NULL,
    [Login_ID]  NUMERIC (18) NOT NULL,
    [Cmp_ID]    NUMERIC (18) NOT NULL,
    [Branch_Id] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0015_LOGIN_BRANCH_RIGHTS] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0015_LOGIN_BRANCH_RIGHTS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0015_LOGIN_BRANCH_RIGHTS_T0011_LOGIN] FOREIGN KEY ([Login_ID]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID]),
    CONSTRAINT [FK_T0015_LOGIN_BRANCH_RIGHTS_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_Id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID])
);

