CREATE TABLE [dbo].[T0012_COMPANY_CRT_LOGIN_MASTER] (
    [Row_ID]          NUMERIC (18) NOT NULL,
    [Cmp_ID]          NUMERIC (18) NULL,
    [Create_date]     DATETIME     NULL,
    [Last_login_date] DATETIME     NULL,
    CONSTRAINT [PK_T0012_COMPANY_CRT_LOGIN_MASTER] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0012_COMPANY_CRT_LOGIN_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

