CREATE TABLE [dbo].[T0020_COMPANY_TRANSACTION] (
    [Tran_ID]        NUMERIC (18) NOT NULL,
    [Cmp_ID]         NUMERIC (18) NOT NULL,
    [Tran_Year]      VARCHAR (10) NOT NULL,
    [Tran_From_Date] DATETIME     NOT NULL,
    [Tran_To_Date]   DATETIME     NOT NULL,
    [Tran_Lock]      CHAR (1)     NOT NULL,
    [Tran_Year_End]  CHAR (1)     NOT NULL,
    CONSTRAINT [PK_T0020_COMPANY_TRANSACTION] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0020_COMPANY_TRANSACTION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

