CREATE TABLE [dbo].[T0030_TEHSIL_MASTER] (
    [T_ID]     NUMERIC (18) NOT NULL,
    [T_Name]   VARCHAR (50) NULL,
    [State_ID] NUMERIC (18) NULL,
    [Dist_ID]  NUMERIC (18) NULL,
    [Cmp_ID]   NUMERIC (18) NULL,
    [Loc_ID]   NUMERIC (18) NULL,
    CONSTRAINT [PK_T0030_TEHSIL_MASTER] PRIMARY KEY NONCLUSTERED ([T_ID] ASC) WITH (FILLFACTOR = 80)
);

