CREATE TABLE [dbo].[T0030_DISTRICT_MASTER] (
    [Dist_ID]   NUMERIC (18) NOT NULL,
    [Dist_Name] VARCHAR (50) NULL,
    [State_ID]  NUMERIC (18) NULL,
    [Cmp_ID]    NUMERIC (18) NULL,
    [Loc_ID]    NUMERIC (18) NULL,
    CONSTRAINT [PK_T0030_DISTRICT_MASTER] PRIMARY KEY NONCLUSTERED ([Dist_ID] ASC) WITH (FILLFACTOR = 80)
);

