CREATE TABLE [dbo].[T0030_DOCUMENT_TYPE_MASTER] (
    [Doc_Type_ID]   NUMERIC (18)  NOT NULL,
    [Doc_Type_Name] VARCHAR (100) NOT NULL,
    [Doc_Comments]  VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T0030_DOCUMENT_TYPE_MASTER] PRIMARY KEY CLUSTERED ([Doc_Type_ID] ASC) WITH (FILLFACTOR = 80)
);

