CREATE TABLE [dbo].[T0030_CITY_MASTER] (
    [City_ID]     NUMERIC (18)  NOT NULL,
    [City_Name]   VARCHAR (50)  NULL,
    [State_ID]    NUMERIC (18)  NULL,
    [Cmp_ID]      NUMERIC (18)  NULL,
    [Loc_ID]      NUMERIC (18)  NULL,
    [City_Cat_ID] NUMERIC (18)  NULL,
    [Remarks]     VARCHAR (200) NULL,
    CONSTRAINT [PK_T0030_CITY_MASTER] PRIMARY KEY NONCLUSTERED ([City_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0030_CITY_MASTER]
    ON [dbo].[T0030_CITY_MASTER]([Cmp_ID] ASC, [City_Name] ASC, [City_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0030_CITY_MASTER_MISSING_11222]
    ON [dbo].[T0030_CITY_MASTER]([Cmp_ID] ASC, [City_Cat_ID] ASC)
    INCLUDE([City_Name]);

