CREATE TABLE [dbo].[T0030_TRAVEL_MODE_MASTER] (
    [Travel_Mode_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]           NUMERIC (18)  NOT NULL,
    [Travel_Mode_Name] VARCHAR (100) NOT NULL,
    [Login_ID]         NUMERIC (18)  NOT NULL,
    [Create_Date]      DATETIME      NOT NULL,
    [Modify_Date]      DATETIME      NULL,
    [GST_Applicable]   TINYINT       CONSTRAINT [DF_T0030_TRAVEL_MODE_MASTER_Gst_Applicable] DEFAULT ((0)) NOT NULL,
    [Mode_Type]        NUMERIC (18)  NULL,
    CONSTRAINT [PK_T0030_TRAVEL_MODE_MASTER] PRIMARY KEY CLUSTERED ([Travel_Mode_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0030_TRAVEL_MODE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

