CREATE TABLE [dbo].[T0030_HRMS_RATING_MASTER] (
    [Rate_ID]           NUMERIC (18)    NOT NULL,
    [Rate_Value]        NUMERIC (18, 2) NULL,
    [Rate_Text]         NVARCHAR (50)   NULL,
    [Cmp_ID]            NUMERIC (18)    NULL,
    [description_value] NVARCHAR (100)  NULL,
    CONSTRAINT [PK_T0030_HRMS_RATING_MASTER] PRIMARY KEY CLUSTERED ([Rate_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0030_HRMS_RATING_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

