CREATE TABLE [dbo].[T0040_DEDUCTION_EVENING_BREAK] (
    [TRAN_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [CMP_ID]           NUMERIC (18) NULL,
    [BRANCH_ID]        NUMERIC (18) NULL,
    [FROM_SLAB]        NUMERIC (18) NULL,
    [TO_SLAB]          NUMERIC (18) NULL,
    [DEDUCTION_AMOUNT] NUMERIC (18) NULL,
    [SINGLE_PUNCH]     CHAR (1)     NULL,
    PRIMARY KEY CLUSTERED ([TRAN_ID] ASC) WITH (FILLFACTOR = 95)
);

