CREATE TABLE [dbo].[T0040_COST_CENTER_MASTER] (
    [Center_ID]    NUMERIC (18)  NOT NULL,
    [Cmp_ID]       NUMERIC (18)  NOT NULL,
    [Center_Name]  VARCHAR (100) NULL,
    [Center_Code]  VARCHAR (25)  NULL,
    [Cost_Element] VARCHAR (25)  NULL,
    CONSTRAINT [PK_T0040_COST_CENTER_MASTER] PRIMARY KEY CLUSTERED ([Center_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_COST_CENTER_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_COST_CENTER_MASTER_T0040_COST_CENTER_MASTER] FOREIGN KEY ([Center_ID]) REFERENCES [dbo].[T0040_COST_CENTER_MASTER] ([Center_ID])
);

