CREATE TABLE [dbo].[T0040_EMAIL_NOTIFICATION_CONFIG] (
    [EMAIL_NTF_ID]     NUMERIC (18)  NOT NULL,
    [CMP_ID]           NUMERIC (18)  NOT NULL,
    [EMAIL_TYPE_NAME]  VARCHAR (100) NOT NULL,
    [EMAIL_NTF_SENT]   NUMERIC (1)   NOT NULL,
    [EMAIL_NTF_DEF_ID] NUMERIC (3)   NOT NULL,
    [To_Manager]       TINYINT       CONSTRAINT [DF_T0040_EMAIL_NOTIFICATION_CONFIG_To_Manager] DEFAULT ((0)) NOT NULL,
    [To_Hr]            TINYINT       CONSTRAINT [DF_T0040_EMAIL_NOTIFICATION_CONFIG_To_Hr] DEFAULT ((0)) NOT NULL,
    [To_Account]       TINYINT       CONSTRAINT [DF_T0040_EMAIL_NOTIFICATION_CONFIG_To_Account] DEFAULT ((0)) NOT NULL,
    [Other_Email]      VARCHAR (200) NULL,
    [Is_Manager_CC]    TINYINT       CONSTRAINT [DF__T0040_EMA__Is_Ma__5166AF2D] DEFAULT ((0)) NOT NULL,
    [Is_HR_CC]         TINYINT       CONSTRAINT [DF__T0040_EMA__Is_HR__525AD366] DEFAULT ((0)) NOT NULL,
    [Is_Account_CC]    TINYINT       CONSTRAINT [DF__T0040_EMA__Is_Ac__534EF79F] DEFAULT ((0)) NOT NULL,
    [Module_Name]      VARCHAR (100) NULL,
    [Other_Email_Bcc]  VARCHAR (200) NULL,
    [IS_Medical]       TINYINT       DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0040_EMAIL_NOTIFICATION_CONFIG] PRIMARY KEY CLUSTERED ([EMAIL_NTF_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_EMAIL_NOTIFICATION_CONFIG_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0040_EMAIL_NOTIFICATION_CONFIG_11_1413684184__K2_1_3_4_5_6_7_8_9_10_11_12]
    ON [dbo].[T0040_EMAIL_NOTIFICATION_CONFIG]([CMP_ID] ASC)
    INCLUDE([EMAIL_NTF_ID], [EMAIL_TYPE_NAME], [EMAIL_NTF_SENT], [EMAIL_NTF_DEF_ID], [To_Manager], [To_Hr], [To_Account], [Other_Email], [Is_Manager_CC], [Is_HR_CC], [Is_Account_CC]) WITH (FILLFACTOR = 80);

