CREATE TABLE [dbo].[T0040_BRAND_MASTER] (
    [BRAND_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]     NUMERIC (18)  NOT NULL,
    [BRAND_Name] VARCHAR (50)  NOT NULL,
    [BRAND_Desc] VARCHAR (150) NULL,
    CONSTRAINT [PK_T0040_BRAND_MASTER] PRIMARY KEY CLUSTERED ([BRAND_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_BRAND_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

