CREATE TABLE [dbo].[T0040_HR_DOC_MASTER] (
    [HR_DOC_ID]         NUMERIC (18)   NOT NULL,
    [Doc_Title]         VARCHAR (100)  NULL,
    [Cmp_id]            NUMERIC (18)   NULL,
    [Branch_id]         NUMERIC (18)   NULL,
    [Grd_id]            NUMERIC (18)   NULL,
    [Dept_id]           NUMERIC (18)   NULL,
    [Desig_id]          NUMERIC (18)   NULL,
    [Doc_content]       NVARCHAR (MAX) NULL,
    [Display_Joinining] INT            NULL,
    [gender]            CHAR (1)       NULL,
    [Join_Days]         VARCHAR (100)  NULL,
    [Display_Ess]       INT            NULL,
    CONSTRAINT [PK_T0040_HR_DOC_MASTER] PRIMARY KEY CLUSTERED ([HR_DOC_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_HR_DOC_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_HR_DOC_MASTER_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0040_HR_DOC_MASTER_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_id]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0040_HR_DOC_MASTER_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desig_id]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0040_HR_DOC_MASTER_T0040_GRADE_MASTER] FOREIGN KEY ([Grd_id]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID])
);

