CREATE TABLE [dbo].[T0040_LANGUAGE_MASTER] (
    [Lang_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]    NUMERIC (18)  NOT NULL,
    [Lang_Name] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_T0040_LANGUAGE_MASTER] PRIMARY KEY CLUSTERED ([Lang_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_LANGUAGE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

