CREATE TABLE [dbo].[T0045_BONUS_DAYS_SLAB] (
    [Row_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [Cmp_ID]     NUMERIC (18)    NOT NULL,
    [Tran_ID]    NUMERIC (18)    NOT NULL,
    [From_Days]  NUMERIC (18, 2) NOT NULL,
    [To_Days]    NUMERIC (18, 2) NOT NULL,
    [Percentage] NUMERIC (18, 2) NOT NULL,
    CONSTRAINT [PK_T0045_BONUS_DAYS_SLAB] PRIMARY KEY CLUSTERED ([Row_ID] ASC),
    CONSTRAINT [FK_T0045_BONUS_DAYS_SLAB_T0040_BONUS_CALC] FOREIGN KEY ([Tran_ID]) REFERENCES [dbo].[T0040_BONUS_CALC] ([Tran_ID])
);

