CREATE TABLE [dbo].[T0040_PROFESSIONAL_SETTING] (
    [Cmp_ID]                    NUMERIC (18)    NOT NULL,
    [Branch_ID]                 NUMERIC (18)    NULL,
    [For_Date]                  DATETIME        NOT NULL,
    [Row_ID]                    NUMERIC (18)    NOT NULL,
    [From_Limit]                NUMERIC (18)    NOT NULL,
    [To_Limit]                  NUMERIC (18)    NOT NULL,
    [Amount]                    NUMERIC (16, 2) NOT NULL,
    [Applicable_PT_Male_Female] VARCHAR (10)    CONSTRAINT [DF_T0040_PROFESSIONAL_SETTING_Applicable_PT_Male_Female] DEFAULT ('ALL') NOT NULL,
    CONSTRAINT [PK_T0040_PROFESSIONAL_SETTING] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_PROFESSIONAL_SETTING_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_PROFESSIONAL_SETTING_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_ID]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0040_PROFESSIONAL_SETTING_10_1205579333__K3]
    ON [dbo].[T0040_PROFESSIONAL_SETTING]([For_Date] ASC) WITH (FILLFACTOR = 80);

