CREATE TABLE [dbo].[T0040_IP_MASTER] (
    [IP_ID]        NUMERIC (18) NOT NULL,
    [IP_ADDRESS]   VARCHAR (30) NOT NULL,
    [Cmp_ID]       NUMERIC (18) NOT NULL,
    [Branch_Id]    NUMERIC (18) NULL,
    [Device_No]    NUMERIC (3)  NOT NULL,
    [Device_Model] VARCHAR (10) NOT NULL,
    [Is_Active]    NUMERIC (1)  NOT NULL,
    [Baud_Rate]    NUMERIC (18) NOT NULL,
    [Comm_Key]     NUMERIC (3)  NOT NULL,
    [Comm_Port]    NUMERIC (3)  NOT NULL,
    [Device_Type]  VARCHAR (20) CONSTRAINT [DF_T0040_IP_MASTER_Device_Type] DEFAULT ('FingerTec') NULL,
    [Device_Name]  VARCHAR (50) NULL,
    [Is_Gate_Pass] TINYINT      CONSTRAINT [DF_T0040_IP_MASTER_Is_Gate_Pass] DEFAULT ((0)) NOT NULL,
    [Is_Training]  TINYINT      CONSTRAINT [DF_T0040_IP_MASTER_Is_Training] DEFAULT ((0)) NOT NULL,
    [Is_Canteen]   TINYINT      CONSTRAINT [DF_T0040_IP_MASTER_Is_Canteen] DEFAULT ((0)) NOT NULL,
    [Flag]         VARCHAR (10) NULL,
    CONSTRAINT [PK_T0040_IP_MASTER] PRIMARY KEY CLUSTERED ([IP_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_IP_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_IP_MASTER_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_Id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID])
);

