CREATE TABLE [dbo].[T0040_SKILL_MASTER] (
    [Skill_ID]    NUMERIC (18)  NOT NULL,
    [Cmp_ID]      NUMERIC (18)  NOT NULL,
    [Skill_Name]  VARCHAR (300) NULL,
    [Description] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0040_SKILL_MASTER] PRIMARY KEY CLUSTERED ([Skill_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_SKILL_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

