CREATE TABLE [dbo].[T0040_LICENSE_MASTER] (
    [Lic_ID]       NUMERIC (18)  NOT NULL,
    [Cmp_Id]       NUMERIC (18)  NOT NULL,
    [Lic_Name]     VARCHAR (50)  NOT NULL,
    [Lic_Comments] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T0040_LICENSE_MASTER] PRIMARY KEY CLUSTERED ([Lic_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_LICENSE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

