CREATE TABLE [dbo].[T0040_WORK_MASTER] (
    [Work_ID]   NUMERIC (18)  NOT NULL,
    [Work_name] NVARCHAR (50) NOT NULL,
    [Cmp_ID]    NUMERIC (18)  NOT NULL,
    CONSTRAINT [PK_T0040_WORK_MASTER] PRIMARY KEY CLUSTERED ([Work_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_WORK_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

