CREATE TABLE [dbo].[T0040_Functional_Master] (
    [Type_ID]     NUMERIC (18) NOT NULL,
    [Cmp_ID]      NUMERIC (18) NOT NULL,
    [Type_Name]   VARCHAR (50) NOT NULL,
    [Description] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_T0040_FUNCTIONAL_MASTER] PRIMARY KEY CLUSTERED ([Type_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_FUNCTIONAL_MASTER_T0040_FUNCTIONAL_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

