CREATE TABLE [dbo].[T0040_PROFESSIONAL_SETTING_StateWise] (
    [Cmp_ID]     NUMERIC (18) NOT NULL,
    [State_ID]   NUMERIC (18) NULL,
    [For_Date]   DATETIME     NOT NULL,
    [Row_ID]     NUMERIC (18) IDENTITY (1, 1) NOT NULL,
    [From_Limit] NUMERIC (18) NOT NULL,
    [To_Limit]   NUMERIC (18) NOT NULL,
    [Amount]     NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0040_PROFESSIONAL_SETTING_StateWise] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80)
);

