CREATE TABLE [dbo].[T0040_LANGUAGE_DETAIL] (
    [LANG_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [CMP_ID]    NUMERIC (18)   NOT NULL,
    [ENGLISH]   VARCHAR (500)  NULL,
    [LANGUAGES] NVARCHAR (MAX) NULL,
    [REMARK]    NVARCHAR (100) NULL,
    [ACTIVE]    BIT            CONSTRAINT [DF_T0040_LANGUAGE_DETAIL_ACTIVE] DEFAULT ((1)) NOT NULL,
    [SORTID]    INT            NULL
);

