CREATE TABLE [dbo].[T0040_QUALIFICATION_MASTER] (
    [Qual_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]    NUMERIC (18)  NOT NULL,
    [Qual_Name] VARCHAR (100) NOT NULL,
    [Qual_Type] VARCHAR (100) NULL,
    CONSTRAINT [PK_T0040_QUALIFICATION_MASTER] PRIMARY KEY CLUSTERED ([Qual_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_QUALIFICATION_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

