CREATE TABLE [dbo].[T0040_WEEKOFF_MASTER] (
    [W_ID]         NUMERIC (18)   NOT NULL,
    [Cmp_ID]       NUMERIC (18)   NOT NULL,
    [Branch_ID]    NUMERIC (18)   NULL,
    [Weekoff_Name] VARCHAR (20)   NOT NULL,
    [Weekoff_Day]  NUMERIC (3, 1) NULL,
    [Login_ID]     NUMERIC (18)   NULL,
    [System_Date]  DATETIME       NULL,
    CONSTRAINT [PK_T0040_WEEKOFF_MASTER] PRIMARY KEY CLUSTERED ([W_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_WEEKOFF_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_WEEKOFF_MASTER_T0011_LOGIN] FOREIGN KEY ([Login_ID]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID]),
    CONSTRAINT [FK_T0040_WEEKOFF_MASTER_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_ID]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID])
);

