CREATE TABLE [dbo].[T0040_CLAIM_MASTER] (
    [Claim_ID]                          NUMERIC (18)  NOT NULL,
    [Cmp_ID]                            NUMERIC (18)  NOT NULL,
    [Claim_Name]                        VARCHAR (100) NOT NULL,
    [Claim_Max_Limit]                   NUMERIC (18)  NOT NULL,
    [Desig_Wise_Limit]                  NUMERIC (18)  CONSTRAINT [DF_T0040_CLAIM_MASTER_Desig_Wise_Limit] DEFAULT ((0)) NOT NULL,
    [Claim_Apr_Deduct_From_Sal]         NUMERIC (18)  CONSTRAINT [DF__T0040_CLA__Claim__19F1211B] DEFAULT (NULL) NULL,
    [Grade_Wise_Limit]                  NUMERIC (18)  NULL,
    [Branch_Wise_Limit]                 NUMERIC (18)  NULL,
    [Claim_Limit_Type]                  TINYINT       NULL,
    [Claim_Type]                        TINYINT       NULL,
    [Attach_Mandatory]                  BIT           NULL,
    [CLAIM_ALLOW_BEYOND_LIMIT]          TINYINT       CONSTRAINT [DF__T0040_CLA__CLAIM__04374DBA] DEFAULT ((0)) NOT NULL,
    [Beyond_Max_Limit_Deduct_In_Salary] TINYINT       CONSTRAINT [DF__T0040_CLA__Beyon__37A77288] DEFAULT ((0)) NOT NULL,
    [No_Of_Year_Limit]                  NUMERIC (18)  CONSTRAINT [DF__T0040_CLA__No_Of__389B96C1] DEFAULT ((0)) NOT NULL,
    [Claim_For_FNF]                     TINYINT       CONSTRAINT [DF__T0040_CLA__Claim__3B78036C] DEFAULT ((0)) NOT NULL,
    [Gender_Wise]                       TINYINT       CONSTRAINT [DF__T0040_CLA__Gende__72C83856] DEFAULT ((0)) NOT NULL,
    [For_Gender]                        VARCHAR (10)  NULL,
    [Basic_Salary_wise]                 TINYINT       CONSTRAINT [DF__T0040_CLA__Basic__5088FA42] DEFAULT ((0)) NOT NULL,
    [Gross_Salary_wise]                 TINYINT       CONSTRAINT [DF__T0040_CLA__Gross__517D1E7B] DEFAULT ((0)) NOT NULL,
    [Applicable_Once]                   TINYINT       CONSTRAINT [DF__T0040_CLA__Appli__15F24459] DEFAULT ((0)) NOT NULL,
    [Claim_Def_Id]                      INT           CONSTRAINT [DF__T0040_CLA__Claim__5677A919] DEFAULT ((0)) NULL,
    [Claim_Terms_Condition]             VARCHAR (MAX) NULL,
    [YearBy]                            INT           NULL,
    [Claim_Main_Type]                   INT           NULL,
    [Claim_For]                         INT           NULL,
    [Claim_ForMonth]                    INT           NULL,
    [Claim_FromDate]                    SMALLDATETIME NULL,
    [Claim_ToDate]                      SMALLDATETIME NULL,
    [Age_Wise_Limit]                    INT           NULL,
    [Unit_Id]                           INT           NULL,
    [Bill_Id]                           INT           NULL,
    [Claim_ApplicableOnceBasedOnLimit]  INT           NULL,
    [Grade_Age_Limit]                   INT           NULL,
    [After_Joining_Days]                INT           NULL,
    [Claim_Report_Def_Id]               INT           NULL,
    [Chklimitlbl]                       TINYINT       NULL,
    [Relation_Id]                       VARCHAR (MAX) NULL,
    [Application_Limitwise]             INT           NULL,
    [Sorting_no]                        VARCHAR (50)  NULL,
    [ChkAutoFill]                       TINYINT       NULL,
    [ChkNec]                            TINYINT       NULL,
    [Grade_City_Wise_Limit]             TINYINT       NULL,
    [Desig_City_Wise_Limit]             TINYINT       NULL,
    [HQ_City_Wise_Limit]                TINYINT       NULL,
    [Claim_Group]                       TINYINT       DEFAULT (NULL) NULL,
    CONSTRAINT [PK_T0040_CLAIM_MASTER] PRIMARY KEY CLUSTERED ([Claim_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_CLAIM_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

