CREATE TABLE [dbo].[T0040_CURRENCY_MASTER] (
    [Curr_ID]       NUMERIC (18)    NOT NULL,
    [Cmp_ID]        NUMERIC (18)    NOT NULL,
    [Curr_Name]     VARCHAR (50)    NOT NULL,
    [Curr_Rate]     NUMERIC (18, 2) NOT NULL,
    [Curr_Major]    CHAR (1)        NOT NULL,
    [Curr_Symbol]   VARCHAR (10)    NOT NULL,
    [Curr_Sub_Name] VARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_T0040_CURRENCY_MASTER] PRIMARY KEY CLUSTERED ([Curr_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_CURRENCY_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_CURRENCY_MASTER_T0080_EMP_MASTER] FOREIGN KEY ([Curr_ID]) REFERENCES [dbo].[T0040_CURRENCY_MASTER] ([Curr_ID])
);

