CREATE TABLE [dbo].[T0040_EmpKPI_Master] (
    [KpiAtt_Id] NUMERIC (18)    NOT NULL,
    [Cmp_Id]    NUMERIC (18)    NULL,
    [EmpKPI_Id] NUMERIC (18)    NOT NULL,
    [Emp_Id]    NUMERIC (18)    NULL,
    [KPI]       VARCHAR (250)   NULL,
    [Weightage] NUMERIC (18, 2) NULL,
    [SubKPIId]  NUMERIC (18)    NOT NULL,
    CONSTRAINT [PK_T0040_EmpKPI_Master] PRIMARY KEY CLUSTERED ([KpiAtt_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_EmpKPI_Master_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_EmpKPI_Master_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0040_EmpKPI_Master_T0080_EmpKPI] FOREIGN KEY ([EmpKPI_Id]) REFERENCES [dbo].[T0080_EmpKPI] ([EmpKPI_Id]),
    CONSTRAINT [FK_T0040_EmpKPI_Master_T0080_SubKPI_Master] FOREIGN KEY ([SubKPIId]) REFERENCES [dbo].[T0080_SubKPI_Master] ([SubKPIId])
);

