CREATE TABLE [dbo].[T0040_PERFORMANCE_INCENTIVE_MASTER] (
    [PER_INC_TRAN_ID] NUMERIC (18)  NOT NULL,
    [CMP_ID]          NUMERIC (18)  NOT NULL,
    [PER_NAME]        VARCHAR (50)  NOT NULL,
    [PER_DESC]        VARCHAR (150) NULL,
    [TOTAL_POINTS]    NUMERIC (18)  NOT NULL,
    [APPROVE_FROM]    VARCHAR (15)  NOT NULL,
    [SYS_DATE]        DATETIME      NOT NULL,
    CONSTRAINT [PK_T0040_PERFORMANCE_INCENTIVE_MASTER] PRIMARY KEY CLUSTERED ([PER_INC_TRAN_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_PERFORMANCE_INCENTIVE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

