CREATE TABLE [dbo].[T0040_BONUS_LUNCH_AMOUNT] (
    [TRAN_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [CMP_ID]      NUMERIC (18)  NULL,
    [EMP_ID]      NUMERIC (18)  NULL,
    [DESIGNATION] VARCHAR (200) NULL,
    [GENDER]      CHAR (1)      NULL,
    [FOR_DATE]    DATETIME      NULL,
    [ENROLL_NO]   NUMERIC (18)  NULL,
    [IN_TIME]     DATETIME      NULL,
    [OUT_TIME]    DATETIME      NULL,
    [DURATION]    NUMERIC (18)  NULL,
    [AMOUNT]      NUMERIC (18)  NULL,
    PRIMARY KEY CLUSTERED ([TRAN_ID] ASC) WITH (FILLFACTOR = 95)
);

