CREATE TABLE [dbo].[T0040_TS_Project_Master] (
    [Project_ID]              NUMERIC (18)    NOT NULL,
    [Project_Name]            VARCHAR (100)   NULL,
    [Project_Code]            VARCHAR (50)    NULL,
    [Project_Description]     VARCHAR (MAX)   NULL,
    [Start_Date]              DATETIME        NULL,
    [Due_Date]                DATETIME        NULL,
    [Duration]                NVARCHAR (50)   NULL,
    [Project_Status_ID]       NUMERIC (18)    NULL,
    [TimeSheet_Approval_Type] VARCHAR (50)    NULL,
    [Project_Cost]            NUMERIC (18, 2) NULL,
    [Client_ID]               NUMERIC (18)    NULL,
    [Completed]               INT             NULL,
    [Disabled]                INT             NULL,
    [Attachment]              VARCHAR (MAX)   NULL,
    [Address1]                VARCHAR (MAX)   NULL,
    [Address2]                VARCHAR (MAX)   NULL,
    [Loc_ID]                  NUMERIC (18)    NULL,
    [State_ID]                NUMERIC (18)    NULL,
    [Zipcode]                 VARCHAR (50)    NULL,
    [PhoneNo]                 VARCHAR (50)    NULL,
    [FaxNo]                   VARCHAR (50)    NULL,
    [Contact_Person]          VARCHAR (50)    NULL,
    [Contact_Email]           VARCHAR (50)    NULL,
    [Speciality_ID]           NUMERIC (18)    NULL,
    [Contract_Type]           VARCHAR (50)    NULL,
    [Fedora_Charges]          NUMERIC (18, 2) NULL,
    [Overhead_Calculation]    INT             NULL,
    [Cmp_ID]                  NUMERIC (18)    NULL,
    [Created_By]              NUMERIC (18)    NULL,
    [Created_Date]            DATETIME        NULL,
    [Modify_By]               NUMERIC (18)    NULL,
    [Modify_Date]             DATETIME        NULL,
    [City]                    VARCHAR (50)    NULL,
    [Branch_ID]               NUMERIC (18)    NULL,
    [Savedby]                 VARCHAR (500)   NULL,
    CONSTRAINT [PK_T0040_TS_Project_Master] PRIMARY KEY CLUSTERED ([Project_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_TS_Project_Master_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_TS_Project_Master_T0011_LOGIN] FOREIGN KEY ([Created_By]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID]),
    CONSTRAINT [FK_T0040_TS_Project_Master_T0040_Client_Master] FOREIGN KEY ([Client_ID]) REFERENCES [dbo].[T0040_Client_Master] ([Client_ID]),
    CONSTRAINT [FK_T0040_TS_Project_Master_T0040_Project_Status] FOREIGN KEY ([Project_Status_ID]) REFERENCES [dbo].[T0040_Project_Status] ([Project_Status_ID]),
    CONSTRAINT [FK_T0040_TS_Project_Master_T0040_Speciality_Master] FOREIGN KEY ([Speciality_ID]) REFERENCES [dbo].[T0040_Speciality_Master] ([Speciality_ID])
);

