CREATE TABLE [dbo].[T0040_SIGNATURE_MASTER] (
    [Sign_Type_ID]     NUMERIC (18)  NOT NULL,
    [Cmp_ID]           NUMERIC (18)  NOT NULL,
    [Sign_Type]        VARCHAR (50)  NOT NULL,
    [Sign_Name]        VARCHAR (50)  NOT NULL,
    [Sign_Designation] VARCHAR (50)  NOT NULL,
    [Sign_Image_Name]  VARCHAR (250) NOT NULL,
    [Sign_Def_ID]      NUMERIC (18)  NOT NULL,
    CONSTRAINT [PK_T0040_SIGNATURE_MASTER] PRIMARY KEY CLUSTERED ([Sign_Type_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_SIGNATURE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

