CREATE TABLE [dbo].[T0045_LEAVE_APP_NOTICE_SLAB] (
    [Tran_ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [Cmp_ID]       NUMERIC (18)   NOT NULL,
    [Leave_ID]     NUMERIC (18)   NOT NULL,
    [For_Date]     DATETIME       NOT NULL,
    [Leave_Period] NUMERIC (7, 2) NOT NULL,
    [Notice_Days]  NUMERIC (5)    NOT NULL,
    CONSTRAINT [FK_T0045_LEAVE_APP_NOTICE_SLAB_T0040_LEAVE_MASTER] FOREIGN KEY ([Leave_ID]) REFERENCES [dbo].[T0040_LEAVE_MASTER] ([Leave_ID])
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0045_LEAVE_APP_NOTICE_SLAB]
    ON [dbo].[T0045_LEAVE_APP_NOTICE_SLAB]([Cmp_ID] ASC, [Leave_ID] ASC, [For_Date] DESC, [Leave_Period] ASC);

