CREATE TABLE [dbo].[T0040_INCENTIVE_FORMULA_FIELDS] (
    [FIELD_ID]     INT            IDENTITY (1, 1) NOT NULL,
    [CMP_ID]       NUMERIC (18)   NULL,
    [FIELD_NAME]   NVARCHAR (250) NULL,
    [CREATED_DATE] DATETIME       NULL,
    CONSTRAINT [PK_T0040_INCENTIVE_FORMULA_FIELDS] PRIMARY KEY CLUSTERED ([FIELD_ID] ASC)
);

