CREATE TABLE [dbo].[T0040_CALCULATION_WEEKOFF_SLABWISE] (
    [ROW_ID]   NUMERIC (18) NULL,
    [EMP_ID]   NUMERIC (18) NULL,
    [FOR_DATE] DATETIME     NULL,
    [DURATION] NUMERIC (18) NULL,
    [SHIFT_ID] NUMERIC (18) NULL
);

