CREATE TABLE [dbo].[T0040_ATTRIBUTE_MASTER] (
    [Attribute_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]         NUMERIC (18)  NOT NULL,
    [Attribute_Name] VARCHAR (300) NULL,
    [Description]    VARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0040_ATTRIBUTE_MASTER] PRIMARY KEY CLUSTERED ([Attribute_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_ATTRIBUTE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

