CREATE TABLE [dbo].[T0040_HRMS_AwardMaster] (
    [Awards_Id]  NUMERIC (18)  NOT NULL,
    [Cmp_Id]     NUMERIC (18)  NOT NULL,
    [Award_Name] VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_T0040_HRMS_AwardMaster] PRIMARY KEY CLUSTERED ([Awards_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_HRMS_AwardMaster_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

