CREATE TABLE [dbo].[T0040_Asset_Details] (
    [AssetM_ID]       NUMERIC (18)   NOT NULL,
    [Cmp_ID]          NUMERIC (18)   NOT NULL,
    [Asset_ID]        NUMERIC (18)   NOT NULL,
    [Description]     VARCHAR (MAX)  NOT NULL,
    [Type_of_Asset]   VARCHAR (50)   NOT NULL,
    [SerialNo]        VARCHAR (50)   NOT NULL,
    [BRAND_ID]        NUMERIC (18)   NOT NULL,
    [Model]           VARCHAR (50)   NOT NULL,
    [Vendor]          VARCHAR (50)   NOT NULL,
    [Status]          VARCHAR (20)   NULL,
    [Purchase_date]   DATETIME       NOT NULL,
    [Warranty_Starts] DATETIME       NOT NULL,
    [Warranty_Ends]   DATETIME       NOT NULL,
    [Image]           VARCHAR (50)   NOT NULL,
    [Asset_Code]      VARCHAR (50)   NOT NULL,
    [allocation]      BIT            NULL,
    [Asset_Status]    VARCHAR (25)   NULL,
    [Invoice_No]      VARCHAR (50)   NULL,
    [Invoice_Amount]  FLOAT (53)     NULL,
    [Attach_Doc]      NVARCHAR (MAX) NULL,
    [Part_No]         VARCHAR (100)  NULL,
    [IMEI_No]         VARCHAR (100)  NULL,
    [Mac_Address]     VARCHAR (100)  NULL,
    [Vendor_Address]  VARCHAR (MAX)  NULL,
    [Invoice_Date]    DATETIME       NULL,
    [PONO]            VARCHAR (100)  NULL,
    [pono_Date]       DATETIME       NULL,
    [City]            VARCHAR (100)  NULL,
    [contact_person]  VARCHAR (250)  NULL,
    [contact_no]      VARCHAR (20)   NULL,
    [Dispose_date]    DATETIME       NULL,
    [Vendor_Id]       NUMERIC (18)   NULL,
    [Branch_ID]       INT            NULL,
    CONSTRAINT [PK_T0040_Asset_Details] PRIMARY KEY CLUSTERED ([AssetM_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_Asset_Details_T0010_COMPANY_MASTER] FOREIGN KEY ([Asset_ID]) REFERENCES [dbo].[T0040_ASSET_MASTER] ([Asset_ID]),
    CONSTRAINT [FK_T0040_Asset_Details_T0040_ASSET_MASTER] FOREIGN KEY ([Asset_ID]) REFERENCES [dbo].[T0040_ASSET_MASTER] ([Asset_ID]),
    CONSTRAINT [FK_T0040_Asset_Details_T0040_BRAND_MASTER] FOREIGN KEY ([BRAND_ID]) REFERENCES [dbo].[T0040_BRAND_MASTER] ([BRAND_ID]),
    CONSTRAINT [FK_T0040_Asset_Details_T0040_Vendor_Master] FOREIGN KEY ([Vendor_Id]) REFERENCES [dbo].[T0040_Vendor_Master] ([Vendor_Id])
);

