CREATE TABLE [dbo].[T0040_GRADE_MASTER] (
    [Grd_ID]                      NUMERIC (18)    NOT NULL,
    [Cmp_ID]                      NUMERIC (18)    NOT NULL,
    [Cat_ID]                      NUMERIC (18)    NULL,
    [Grd_Name]                    VARCHAR (100)   NOT NULL,
    [Grd_Description]             VARCHAR (100)   NOT NULL,
    [Grd_Dis_No]                  NUMERIC (18)    NOT NULL,
    [Short_Fall_Days]             NUMERIC (18)    CONSTRAINT [DF_T0040_GRADE_MASTER_Short_Fall_Days] DEFAULT ((0)) NOT NULL,
    [Short_Fall_W_Days]           NUMERIC (18)    CONSTRAINT [DF_T0040_GRADE_MASTER_Short_Fall_W_Days] DEFAULT ((0)) NOT NULL,
    [Basic_Percentage]            NUMERIC (18, 3) CONSTRAINT [DF_T0040_GRADE_MASTER_Basic_percentage] DEFAULT ((0)) NULL,
    [Basic_Calc_On]               VARCHAR (20)    NULL,
    [min_basic]                   NUMERIC (18, 2) CONSTRAINT [DF_T0040_GRADE_MASTER_min_basic] DEFAULT ((0)) NOT NULL,
    [Grd_BasicFrom]               NUMERIC (18, 2) NULL,
    [Grd_BasicTo]                 NUMERIC (18, 2) NULL,
    [Eligibility_Amount]          NUMERIC (18, 2) CONSTRAINT [DF__T0040_GRA__Eligi__68B68ADE] DEFAULT ((0)) NULL,
    [Signature]                   NVARCHAR (MAX)  NULL,
    [Eligibility_designationwise] TINYINT         CONSTRAINT [DF__T0040_GRA__Eligi__152BA0A7] DEFAULT ((0)) NOT NULL,
    [OT_Applicable]               TINYINT         CONSTRAINT [DF_T0040_GRADE_MASTER_OT_Applicable] DEFAULT ((1)) NOT NULL,
    [IsActive]                    TINYINT         CONSTRAINT [DF__T0040_GRA__IsAct__4CF1A234] DEFAULT ((1)) NULL,
    [InActive_EffeDate]           DATETIME        CONSTRAINT [DF__T0040_GRA__InEff__4DE5C66D] DEFAULT (NULL) NULL,
    [Fix_Basic_Salary]            NUMERIC (18, 2) CONSTRAINT [DF_T0040_GRADE_MASTER_Fix_Basic_Salary] DEFAULT ((0)) NOT NULL,
    [Fix_Basic_Salary_Night]      NUMERIC (18, 2) CONSTRAINT [DF_T0040_GRADE_MASTER_Fix_Basic_Salary_Night] DEFAULT ((0)) NOT NULL,
    [Desig_ID]                    VARCHAR (MAX)   NULL,
    [Is_Gradewise_Salary]         TINYINT         DEFAULT ((0)) NOT NULL,
    [Grd_WAGES_TYPE]              VARCHAR (20)    NULL,
    CONSTRAINT [PK_T0040_GRADE_MASTER] PRIMARY KEY CLUSTERED ([Grd_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_GRADE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_GRADE_MASTER_T0030_CATEGORY_MASTER] FOREIGN KEY ([Cat_ID]) REFERENCES [dbo].[T0030_CATEGORY_MASTER] ([Cat_ID])
);

