CREATE TABLE [dbo].[T0040_DESIGNATION_MASTER_TRANSPORT] (
    [Designation_ID]   NUMERIC (18) NOT NULL,
    [Designation_Name] VARCHAR (50) NULL,
    [Designation_Code] VARCHAR (50) NULL,
    CONSTRAINT [PK_T0040_DESIGNATION_MASTER_TRANSPORT] PRIMARY KEY CLUSTERED ([Designation_ID] ASC)
);

