CREATE TABLE [dbo].[T0040_ASSET_MASTER] (
    [Asset_ID]   NUMERIC (18)  NOT NULL,
    [Cmp_ID]     NUMERIC (18)  NOT NULL,
    [Asset_Name] VARCHAR (50)  NOT NULL,
    [Asset_Desc] VARCHAR (150) NULL,
    [Code]       VARCHAR (10)  NULL,
    CONSTRAINT [PK_T0040_ASSET_MASTER] PRIMARY KEY CLUSTERED ([Asset_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_ASSET_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

