CREATE TABLE [dbo].[T0040_WARNING_MASTER] (
    [War_ID]       NUMERIC (18)    NOT NULL,
    [Cmp_ID]       NUMERIC (18)    NOT NULL,
    [War_Name]     VARCHAR (MAX)   NULL,
    [War_Comments] VARCHAR (250)   NULL,
    [Deduct_Rate]  NUMERIC (18, 2) NULL,
    [Deduct_Type]  VARCHAR (10)    DEFAULT ('DAY') NOT NULL,
    [Level_Id]     NUMERIC (18)    CONSTRAINT [DF_T0040_WARNING_MASTER_Level_Id] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0040_WARNING_MASTER] PRIMARY KEY CLUSTERED ([War_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_WARNING_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);


GO
CREATE STATISTICS [War_Name]
    ON [dbo].[T0040_WARNING_MASTER]([War_Name]);

