CREATE TABLE [dbo].[T0040_IT_Deduction] (
    [IT_Tran_ID] NUMERIC (18)  NOT NULL,
    [Cmp_ID]     NUMERIC (18)  NOT NULL,
    [IT_Name]    VARCHAR (100) NOT NULL,
    [Max_Limit]  NUMERIC (18)  NULL,
    CONSTRAINT [PK_T0040_IT_Deduction] PRIMARY KEY CLUSTERED ([IT_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_IT_Deduction_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

