CREATE TABLE [dbo].[T0040_DOCUMENT_MASTER] (
    [Doc_ID]           NUMERIC (18)  NOT NULL,
    [Cmp_ID]           NUMERIC (18)  NOT NULL,
    [Doc_Name]         VARCHAR (100) NOT NULL,
    [Doc_Comments]     VARCHAR (250) NOT NULL,
    [Doc_Required]     TINYINT       CONSTRAINT [DF_T0040_DOCUMENT_MASTER_Doc_Required] DEFAULT ((0)) NOT NULL,
    [Document_Type_Id] NUMERIC (18)  CONSTRAINT [DF_T0040_DOCUMENT_MASTER_Document_Type_Id] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0040_DOCUMENT_MASTER] PRIMARY KEY CLUSTERED ([Doc_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_DOCUMENT_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

