CREATE TABLE [dbo].[T0040_INSURANCE_MASTER] (
    [Ins_Tran_ID]    NUMERIC (18)   NOT NULL,
    [Cmp_ID]         NUMERIC (18)   NOT NULL,
    [Ins_Name]       VARCHAR (50)   NOT NULL,
    [Ins_Desc]       VARCHAR (150)  NULL,
    [Type]           VARCHAR (10)   CONSTRAINT [DF_T0040_INSURANCE_MASTER_Type] DEFAULT ('Insurance') NOT NULL,
    [Default_Value]  NVARCHAR (MAX) NULL,
    [Insurance_Type] INT            NULL,
    CONSTRAINT [PK_T0040_INSURANCE_MASTER] PRIMARY KEY CLUSTERED ([Ins_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_INSURANCE_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

