CREATE TABLE [dbo].[T0040_RATING_MASTER] (
    [Rating_ID]   NUMERIC (18)    NOT NULL,
    [Cmp_ID]      NUMERIC (18)    NOT NULL,
    [Title]       VARCHAR (200)   NOT NULL,
    [Description] VARCHAR (MAX)   NOT NULL,
    [From_Rate]   NUMERIC (18, 2) NOT NULL,
    [To_Rate]     NUMERIC (18, 2) NOT NULL,
    CONSTRAINT [PK_T0040_RATING_MASTER] PRIMARY KEY CLUSTERED ([Rating_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_RATING_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

