CREATE TABLE [dbo].[T0040_Task_Master] (
    [Task_ID]           NUMERIC (18)    NOT NULL,
    [Task_Name]         VARCHAR (50)    NULL,
    [Task_Code]         VARCHAR (50)    NULL,
    [Task_Description]  VARCHAR (MAX)   NULL,
    [Task_Priority]     VARCHAR (50)    NULL,
    [Task_Type_ID]      NUMERIC (18)    NULL,
    [Project_ID]        NUMERIC (18)    NULL,
    [Due_Date]          DATETIME        NULL,
    [Duration]          VARCHAR (50)    NULL,
    [Completed]         INT             NULL,
    [IsReOpen]          INT             NULL,
    [Project_Status_ID] NUMERIC (18)    NULL,
    [Milestone_ID]      NUMERIC (18)    NULL,
    [Deadline_Date]     DATETIME        NULL,
    [All_Employee_Task] INT             NULL,
    [All_Project_Task]  INT             NULL,
    [Estimate_Cost]     NUMERIC (18, 2) NULL,
    [Estimate_Duration] VARCHAR (50)    NULL,
    [Task_Attachment]   VARCHAR (MAX)   NULL,
    [Cmp_ID]            NUMERIC (18)    NULL,
    [Created_By]        NUMERIC (18)    NULL,
    [Created_Date]      DATETIME        NULL,
    [Modify_By]         NUMERIC (18)    NULL,
    [Modify_Date]       DATETIME        NULL,
    CONSTRAINT [PK_T0040_Task_Master] PRIMARY KEY CLUSTERED ([Task_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_Task_Master_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0040_Task_Master_T0011_LOGIN] FOREIGN KEY ([Created_By]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID]),
    CONSTRAINT [FK_T0040_Task_Master_T0040_Milestone_Master] FOREIGN KEY ([Milestone_ID]) REFERENCES [dbo].[T0040_Milestone_Master] ([Milestone_ID]),
    CONSTRAINT [FK_T0040_Task_Master_T0040_Project_Status] FOREIGN KEY ([Project_Status_ID]) REFERENCES [dbo].[T0040_Project_Status] ([Project_Status_ID]),
    CONSTRAINT [FK_T0040_Task_Master_T0040_Task_Type_Master] FOREIGN KEY ([Task_Type_ID]) REFERENCES [dbo].[T0040_Task_Type_Master] ([Task_Type_ID]),
    CONSTRAINT [FK_T0040_Task_Master_T0040_TS_Project_Master] FOREIGN KEY ([Project_ID]) REFERENCES [dbo].[T0040_TS_Project_Master] ([Project_ID])
);

