CREATE TABLE [dbo].[T0040_SHIFT_MASTER] (
    [Shift_ID]              NUMERIC (18)    NOT NULL,
    [Cmp_ID]                NUMERIC (18)    NOT NULL,
    [Shift_Name]            VARCHAR (100)   NOT NULL,
    [Shift_St_Time]         VARCHAR (10)    NOT NULL,
    [Shift_End_Time]        VARCHAR (10)    NOT NULL,
    [Shift_Dur]             VARCHAR (10)    NOT NULL,
    [F_St_Time]             VARCHAR (10)    NULL,
    [F_End_Time]            VARCHAR (10)    NULL,
    [F_Duration]            VARCHAR (10)    NULL,
    [S_St_Time]             VARCHAR (10)    NULL,
    [S_End_Time]            VARCHAR (10)    NULL,
    [S_Duration]            VARCHAR (10)    NULL,
    [T_St_Time]             VARCHAR (10)    NULL,
    [T_End_Time]            VARCHAR (10)    NULL,
    [T_Duration]            VARCHAR (10)    NULL,
    [Inc_Auto_Shift]        TINYINT         NULL,
    [Is_Half_Day]           TINYINT         DEFAULT ((0)) NOT NULL,
    [Week_Day]              VARCHAR (10)    NULL,
    [Half_St_Time]          VARCHAR (10)    NULL,
    [Half_End_Time]         VARCHAR (10)    NULL,
    [Half_Dur]              VARCHAR (10)    NULL,
    [Half_min_duration]     VARCHAR (10)    NULL,
    [Is_Split_Shift]        TINYINT         CONSTRAINT [DF_T0040_SHIFT_MASTER_Is_Split_Shift] DEFAULT ((0)) NOT NULL,
    [Is_Training_Shift]     TINYINT         CONSTRAINT [DF_T0040_SHIFT_MASTER_Is_Training_Shift] DEFAULT ((0)) NOT NULL,
    [Split_Shift_Rate]      NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Split_Shift_Ratio]     NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [DeduHour_SecondBreak]  TINYINT         CONSTRAINT [DF_T0040_SHIFT_MASTER_DeduHour_SecondBreak] DEFAULT ((0)) NOT NULL,
    [DeduHour_ThirdBreak]   TINYINT         CONSTRAINT [DF_T0040_SHIFT_MASTER_DeduHour_ThirdBreak] DEFAULT ((0)) NOT NULL,
    [Auto_Shift_Group]      TINYINT         DEFAULT ((0)) NOT NULL,
    [Shift_WeekDay_OT_Rate] NUMERIC (5, 4)  DEFAULT ((0)) NOT NULL,
    [Shift_WeekOff_OT_Rate] NUMERIC (5, 4)  DEFAULT ((0)) NOT NULL,
    [Shift_Holiday_OT_Rate] NUMERIC (5, 4)  DEFAULT ((0)) NOT NULL,
    [Is_InActive]           TINYINT         DEFAULT ((0)) NOT NULL,
    [InActive_Date]         DATETIME        NULL,
    [IsNightShift]          TINYINT         NULL,
    CONSTRAINT [PK_T0040_SHIFT_MASTER] PRIMARY KEY CLUSTERED ([Shift_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0040_SHIFT_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

