CREATE TABLE [dbo].[T0050_HRMS_InitiateAppraisal] (
    [InitiateId]                           NUMERIC (18)    NOT NULL,
    [Cmp_ID]                               NUMERIC (18)    NOT NULL,
    [Emp_Id]                               NUMERIC (18)    NULL,
    [AppraiserId]                          NUMERIC (18)    NULL,
    [SA_Startdate]                         DATETIME        NULL,
    [SA_Enddate]                           DATETIME        NULL,
    [SA_EmpComments]                       NVARCHAR (500)  NULL,
    [SA_AppComments]                       NVARCHAR (500)  NULL,
    [SA_Status]                            INT             CONSTRAINT [DF_T0050_HRMS_InitiateAppraisal_SA_Status] DEFAULT ((0)) NULL,
    [KPA_Score]                            NUMERIC (18, 2) NULL,
    [KPA_Final]                            NUMERIC (18, 2) NULL,
    [SA_SubmissionDate]                    DATETIME        NULL,
    [SA_ApprovedDate]                      DATETIME        NULL,
    [PF_Score]                             NUMERIC (18, 2) NULL,
    [PF_Final]                             NUMERIC (18, 2) NULL,
    [PO_Score]                             NUMERIC (18, 2) NULL,
    [PO_Final]                             NUMERIC (18, 2) NULL,
    [Overall_Score]                        NUMERIC (18, 2) NULL,
    [Achivement_Id]                        NUMERIC (18)    NULL,
    [AppraiserComment]                     NVARCHAR (500)  NULL,
    [Promo_YesNo]                          INT             NULL,
    [Promo_Desig]                          NUMERIC (18)    NULL,
    [Promo_Wef]                            DATETIME        NULL,
    [JR_YesNo]                             INT             NULL,
    [JR_From]                              DATETIME        NULL,
    [JR_To]                                DATETIME        NULL,
    [Inc_YesNo]                            INT             NULL,
    [Inc_Reason]                           NVARCHAR (500)  NULL,
    [ReviewerComment]                      NVARCHAR (500)  NULL,
    [Appraiser_Date]                       DATETIME        NULL,
    [SA_ApprovedBy]                        NUMERIC (18)    NULL,
    [Per_ApprovedBy]                       NUMERIC (18)    NULL,
    [Overall_Status]                       INT             NULL,
    [GH_Comment]                           NVARCHAR (500)  NULL,
    [SA_SendToRM]                          INT             NULL,
    [SendToHOD]                            INT             NULL,
    [HOD_Comment]                          NVARCHAR (500)  NULL,
    [HOD_ApprovedOn]                       DATETIME        NULL,
    [HOD_ApprovedBy]                       NUMERIC (18)    NULL,
    [HOD_Id]                               NUMERIC (18)    NULL,
    [DirectScore]                          INT             CONSTRAINT [DF_T0050_HRMS_InitiateAppraisal_DirectScore] DEFAULT ((0)) NULL,
    [RM_Score]                             NUMERIC (18, 2) NULL,
    [HOD_Score]                            NUMERIC (18, 2) NULL,
    [Group_Head_Score]                     NUMERIC (18, 2) NULL,
    [Final_Evaluation]                     INT             NULL,
    [Financial_Year]                       INT             NULL,
    [Duration_FromMonth]                   INT             NULL,
    [Duration_ToMonth]                     INT             NULL,
    [Promo_Grade]                          NUMERIC (18)    NULL,
    [GH_Id]                                NUMERIC (18)    NULL,
    [Rm_Required]                          TINYINT         CONSTRAINT [DF_T0050_HRMS_InitiateAppraisal_Rm_Required] DEFAULT ((1)) NULL,
    [Emp_Engagement]                       INT             NULL,
    [Emp_Engagement_Comment]               NVARCHAR (100)  NULL,
    [HAO_Id]                               NUMERIC (18)    NULL,
    [Overall_Score_RM]                     NUMERIC (18, 2) NULL,
    [Overall_Score_HOD]                    NUMERIC (18, 2) NULL,
    [Overall_Score_GH]                     NUMERIC (18, 2) NULL,
    [Overall_Score_MD]                     NUMERIC (18, 2) NULL,
    [MD_Comments]                          NVARCHAR (MAX)  NULL,
    [Send_directly_Performance_Assessment] INT             NULL,
    [Achivement_Id_RM]                     INT             NULL,
    [Achivement_Id_HOD]                    INT             NULL,
    [Achivement_Id_GH]                     INT             NULL,
    CONSTRAINT [PK_T0050_HRMS_InitiateAppraisal] PRIMARY KEY CLUSTERED ([InitiateId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_HRMS_InitiateAppraisal_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0050_HRMS_InitiateAppraisal_T0050_HRMS_InitiateAppraisal] FOREIGN KEY ([InitiateId]) REFERENCES [dbo].[T0050_HRMS_InitiateAppraisal] ([InitiateId])
);

