CREATE TABLE [dbo].[T0055_REIMBURSEMENT] (
    [RIMB_ID]    NUMERIC (18) NOT NULL,
    [CMP_ID]     NUMERIC (18) NOT NULL,
    [RIMB_NAME]  VARCHAR (50) NOT NULL,
    [RIMB_FLAG]  CHAR (1)     NOT NULL,
    [RIMB_LEVEL] NUMERIC (18) NOT NULL,
    [AD_ID]      NUMERIC (18) NULL,
    CONSTRAINT [PK_T0055_REIMBURSEMENT] PRIMARY KEY CLUSTERED ([RIMB_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0055_REIMBURSEMENT_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0055_REIMBURSEMENT_T0050_AD_MASTER] FOREIGN KEY ([AD_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID])
);

