CREATE TABLE [dbo].[T0055_Hrms_Initiate_KPASetting] (
    [KPA_InitiateId]     NUMERIC (18)   NOT NULL,
    [Cmp_Id]             NUMERIC (18)   NOT NULL,
    [Emp_Id]             NUMERIC (18)   NOT NULL,
    [KPA_StartDate]      DATETIME       NOT NULL,
    [KPA_EndDate]        DATETIME       NOT NULL,
    [Initiate_Status]    INT            NOT NULL,
    [Year]               INT            NOT NULL,
    [RM_Required]        INT            NOT NULL,
    [Hod_Id]             NUMERIC (18)   NULL,
    [GH_Id]              NUMERIC (18)   NULL,
    [Emp_ApprovedDate]   DATETIME       NULL,
    [Rm_ApprovedDate]    DATETIME       NULL,
    [HOD_ApprovedDate]   DATETIME       NULL,
    [GH_ApprovedDate]    DATETIME       NULL,
    [Emp_Comment]        NVARCHAR (500) NULL,
    [RM_Comment]         NVARCHAR (500) NULL,
    [HOD_Comment]        NVARCHAR (500) NULL,
    [GH_Comment]         NVARCHAR (500) NULL,
    [Duration_FromMonth] VARCHAR (25)   DEFAULT ('') NOT NULL,
    [Duration_ToMonth]   VARCHAR (25)   DEFAULT ('') NOT NULL,
    [Review_Type]        VARCHAR (10)   NULL,
    [Send_to_RM]         INT            NULL,
    [Period]             VARCHAR (10)   NULL,
    CONSTRAINT [PK_T0055_Hrms_Initiate_KPASetting] PRIMARY KEY CLUSTERED ([KPA_InitiateId] ASC),
    CONSTRAINT [FK_T0055_Hrms_Initiate_KPASetting_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0055_Hrms_Initiate_KPASetting_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0055_Hrms_Initiate_KPASetting_T0080_EMP_MASTER1] FOREIGN KEY ([Hod_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0055_Hrms_Initiate_KPASetting_T0080_EMP_MASTER2] FOREIGN KEY ([GH_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

