CREATE TABLE [dbo].[T0050_GENERAL_DETAIL] (
    [GEN_TRAN_ID]        NUMERIC (18)    NOT NULL,
    [CMP_ID]             NUMERIC (18)    NOT NULL,
    [GEN_ID]             NUMERIC (18)    NOT NULL,
    [ACC_1_1]            NUMERIC (18, 3) NOT NULL,
    [ACC_1_2]            NUMERIC (18, 3) NOT NULL,
    [ACC_2_3]            NUMERIC (18, 3) NOT NULL,
    [ACC_10_1]           NUMERIC (18, 3) NOT NULL,
    [ACC_21_1]           NUMERIC (18, 3) NOT NULL,
    [ACC_22_3]           NUMERIC (18, 3) NOT NULL,
    [ACC_10_1_MAX_LIMIT] NUMERIC (18, 2) NOT NULL,
    [PF_LIMIT]           NUMERIC (18)    NOT NULL,
    [PF_PENSION_AGE]     NUMERIC (18, 2) NULL,
    [ACC_22_4]           NUMERIC (18, 3) CONSTRAINT [DF_T0050_GENERAL_DETAIL_ACC_22_4] DEFAULT ((0)) NULL,
    [IS_NCP_PRORATA]     INT             CONSTRAINT [DF_T0050_GENERAL_DETAIL_IS_NCP_PRORATA] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0050_GENERAL_DETAIL] PRIMARY KEY CLUSTERED ([GEN_TRAN_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_GENERAL_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0050_GENERAL_DETAIL_10_1493580359__K3_5_11]
    ON [dbo].[T0050_GENERAL_DETAIL]([GEN_ID] ASC)
    INCLUDE([ACC_1_2], [PF_LIMIT]) WITH (FILLFACTOR = 80);

