CREATE TABLE [dbo].[T0050_SHIFT_ROTATION_MASTER] (
    [Cmp_ID]        NUMERIC (18)  NOT NULL,
    [Tran_ID]       NUMERIC (18)  NOT NULL,
    [Rotation_Name] VARCHAR (100) NOT NULL,
    [Day1]          NUMERIC (18)  NULL,
    [Day2]          NUMERIC (18)  NULL,
    [Day3]          NUMERIC (18)  NULL,
    [Day4]          NUMERIC (18)  NULL,
    [Day5]          NUMERIC (18)  NULL,
    [Day6]          NUMERIC (18)  NULL,
    [Day7]          NUMERIC (18)  NULL,
    [Day8]          NUMERIC (18)  NULL,
    [Day9]          NUMERIC (18)  NULL,
    [Day10]         NUMERIC (18)  NULL,
    [Day11]         NUMERIC (18)  NULL,
    [Day12]         NUMERIC (18)  NULL,
    [Day13]         NUMERIC (18)  NULL,
    [Day14]         NUMERIC (18)  NULL,
    [Day15]         NUMERIC (18)  NULL,
    [Day16]         NUMERIC (18)  NULL,
    [Day17]         NUMERIC (18)  NULL,
    [Day18]         NUMERIC (18)  NULL,
    [Day19]         NUMERIC (18)  NULL,
    [Day20]         NUMERIC (18)  NULL,
    [Day21]         NUMERIC (18)  NULL,
    [Day22]         NUMERIC (18)  NULL,
    [Day23]         NUMERIC (18)  NULL,
    [Day24]         NUMERIC (18)  NULL,
    [Day25]         NUMERIC (18)  NULL,
    [Day26]         NUMERIC (18)  NULL,
    [Day27]         NUMERIC (18)  NULL,
    [Day28]         NUMERIC (18)  NULL,
    [Day29]         NUMERIC (18)  NULL,
    [Day30]         NUMERIC (18)  NULL,
    [Day31]         NUMERIC (18)  NULL,
    [SysDate]       DATETIME      NOT NULL,
    [Sorting_No]    INT           NOT NULL,
    [Rotation_Type] TINYINT       DEFAULT ((0)) NOT NULL,
    [Change_Mode]   TINYINT       DEFAULT ((0)) NOT NULL,
    [Change_On]     SMALLINT      NULL,
    [Change_After]  SMALLINT      NULL,
    [Skip_WeekOff]  BIT           DEFAULT ((0)) NOT NULL,
    [ChangeOn_Day]  TINYINT       NULL,
    CONSTRAINT [PK_T0050_Shift_Rotation_Master] PRIMARY KEY NONCLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80)
);

