CREATE TABLE [dbo].[T0055_SKILL_GENERAL_SETTING] (
    [Skill_ID]         NUMERIC (18)    NOT NULL,
    [Cmp_ID]           NUMERIC (18)    NOT NULL,
    [Branch_ID]        NUMERIC (18)    NULL,
    [Dept_ID]          NUMERIC (18)    NULL,
    [Grade_ID]         NUMERIC (18)    NULL,
    [Desig_ID]         NUMERIC (18)    NULL,
    [For_Date]         DATETIME        NOT NULL,
    [Skill_Min_Rate]   NUMERIC (18, 2) NOT NULL,
    [Skill_Max_Rate]   NUMERIC (18, 2) NOT NULL,
    [Skill_Total_Rate] NUMERIC (18, 2) NOT NULL,
    [Skill_Duration]   NUMERIC (18, 2) NOT NULL,
    CONSTRAINT [PK_T0055_SKILL_GENERAL_SETTING] PRIMARY KEY CLUSTERED ([Skill_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0055_SKILL_GENERAL_SETTING_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0055_SKILL_GENERAL_SETTING_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_ID]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0055_SKILL_GENERAL_SETTING_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_ID]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0055_SKILL_GENERAL_SETTING_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desig_ID]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0055_SKILL_GENERAL_SETTING_T0040_GRADE_MASTER] FOREIGN KEY ([Grade_ID]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID])
);

