CREATE TABLE [dbo].[T0050_HRMS_APPRAISAL_SETTING] (
    [Appr_id]            NUMERIC (18)    NOT NULL,
    [Cmp_id]             NUMERIC (18)    NULL,
    [Branch_id]          NUMERIC (18)    NULL,
    [Dept_id]            NUMERIC (18)    NULL,
    [Desig_id]           NUMERIC (18)    NULL,
    [Grade_id]           NUMERIC (18)    NULL,
    [Actual_Ctc]         NUMERIC (18, 2) NULL,
    [Experience]         NUMERIC (18, 2) NULL,
    [Min_Appraisal]      NUMERIC (18, 2) NULL,
    [Max_Appraisal]      NUMERIC (18, 2) NULL,
    [Appraisal_Duration] NUMERIC (18, 2) NULL,
    [For_Date]           DATETIME        NULL,
    CONSTRAINT [PK_T0050_HRMS_APPRAISAL_SETTING] PRIMARY KEY CLUSTERED ([Appr_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_HRMS_APPRAISAL_SETTING_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0050_HRMS_APPRAISAL_SETTING_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0050_HRMS_APPRAISAL_SETTING_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_id]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0050_HRMS_APPRAISAL_SETTING_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desig_id]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0050_HRMS_APPRAISAL_SETTING_T0040_GRADE_MASTER] FOREIGN KEY ([Grade_id]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID])
);

