CREATE TABLE [dbo].[T0050_LEAVE_CF_SETTING] (
    [Leave_ID]     NUMERIC (18) NOT NULL,
    [Row_ID]       NUMERIC (18) NOT NULL,
    [Cmp_ID]       NUMERIC (18) NOT NULL,
    [From_Pdays]   NUMERIC (18) NOT NULL,
    [To_Pdays]     NUMERIC (18) NOT NULL,
    [CF_Days]      NUMERIC (18) NOT NULL,
    [CF_Full_Days] NUMERIC (1)  CONSTRAINT [DF_T0050_LEAVE_CF_SETTING_CF_Full_Days] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_T0050_LEAVE_CF_SETTING] PRIMARY KEY CLUSTERED ([Leave_ID] ASC, [Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_LEAVE_CF_SETTING_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0050_LEAVE_CF_SETTING_T0040_LEAVE_MASTER] FOREIGN KEY ([Leave_ID]) REFERENCES [dbo].[T0040_LEAVE_MASTER] ([Leave_ID])
);

