CREATE TABLE [dbo].[T0055_HRMS_EMP_SKILL_DETAILS] (
    [Skill_R_ID]        NUMERIC (18)    NOT NULL,
    [Cmp_ID]            NUMERIC (18)    NOT NULL,
    [For_Date]          DATETIME        NOT NULL,
    [Emp_ID]            NUMERIC (18)    NOT NULL,
    [S_Emp_ID]          NUMERIC (18)    NULL,
    [Login_ID]          NUMERIC (18)    NOT NULL,
    [Status]            CHAR (1)        NOT NULL,
    [Skill_Actual_Rate] NUMERIC (18, 2) NULL,
    [Skill_Rate_Given]  NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_T0055_HRMS_EMP_SKILL_DETAILS] PRIMARY KEY CLUSTERED ([Skill_R_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0055_HRMS_EMP_SKILL_DETAILS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0055_HRMS_EMP_SKILL_DETAILS_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0055_HRMS_EMP_SKILL_DETAILS_T0080_EMP_MASTER1] FOREIGN KEY ([S_Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

