CREATE TABLE [dbo].[T0055_EMP_DEFINED_SHIFT] (
    [Cmp_ID]         NUMERIC (18) NOT NULL,
    [Emp_ID]         NUMERIC (18) NOT NULL,
    [Last_Execution] DATETIME     NOT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0055_EMP_DEFINED_SHIFT]
    ON [dbo].[T0055_EMP_DEFINED_SHIFT]([Cmp_ID] ASC, [Emp_ID] ASC, [Last_Execution] DESC) WITH (FILLFACTOR = 80);

