CREATE TABLE [dbo].[T0050_AppraisalLimit_Setting] (
    [Limit_Id]                    NUMERIC (18)    NOT NULL,
    [Cmp_ID]                      NUMERIC (18)    NOT NULL,
    [ScoreLimit_KPA]              NUMERIC (18, 2) NULL,
    [ScoreLimit_PA]               NUMERIC (18, 2) NULL,
    [ScoreLimit_PoA]              NUMERIC (18, 2) NULL,
    [RecommendLimit_Skill]        NUMERIC (18)    NULL,
    [RecommendLimit_GM]           NUMERIC (18)    NULL,
    [JoiningDate_Limit]           NUMERIC (18)    NULL,
    [KPA_Limit]                   NUMERIC (18)    NULL,
    [KpaMaster_Yes]               INT             NULL,
    [KPA_Default]                 BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_KPA_Default] DEFAULT ((1)) NULL,
    [KPA_Score]                   BIT             NULL,
    [KPA_AllowEmp]                BIT             NULL,
    [SA_SubCriteria]              BIT             NULL,
    [OA_ViewByManager]            BIT             NULL,
    [KPA_AllowEmpScore_Display]   BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_KPA_AllowEmpScore_Display] DEFAULT ((0)) NULL,
    [KPA_AllowRMScore_Display]    BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_KPA_AllowRMScore_Display] DEFAULT ((0)) NULL,
    [KPA_Percentage]              BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_KPA_Percentage] DEFAULT ((0)) NULL,
    [KPA_PerScore]                NUMERIC (5)     NULL,
    [KPA_AllowAddKPA]             BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_KPA_AllowAddKPA] DEFAULT ((0)) NULL,
    [Emp_AssessApprove_days]      INT             NULL,
    [Emp_PA_Approve_RM_days]      INT             NULL,
    [PA_HOD_Days]                 INT             NULL,
    [PA_GH_Days]                  INT             NULL,
    [Effective_Date]              DATETIME        NULL,
    [Multiple_Evaluation]         INT             NULL,
    [Interim_EvaluationBy]        VARCHAR (50)    NULL,
    [Interim_DisplayTab]          VARCHAR (100)   NULL,
    [Display_PreviousKPA]         BIT             NULL,
    [Display_PreviousKPAYear]     BIT             CONSTRAINT [DF_T0050_AppraisalLimit_Setting_Display_PreviousKPAYear] DEFAULT ((0)) NULL,
    [Final_DisplayTab]            VARCHAR (100)   NULL,
    [Send_Dept_Wise]              NUMERIC (18)    DEFAULT ((1)) NOT NULL,
    [Self_Assessment_With_Answer] NUMERIC (18)    DEFAULT ((1)) NOT NULL,
    [Score_Using_Formula]         NUMERIC (18)    DEFAULT ((0)) NOT NULL,
    [Show_KPA_Measure]            NUMERIC (18)    DEFAULT ((0)) NOT NULL,
    [Total_KPA_Weightage]         NUMERIC (18, 2) NULL,
    [MinKPA]                      INT             DEFAULT ((0)) NOT NULL,
    [MaxKPA]                      INT             DEFAULT ((0)) NOT NULL,
    [show_Completion_Date]        INT             DEFAULT ((0)) NOT NULL,
    [show_Attach_Document]        INT             DEFAULT ((0)) NOT NULL,
    [show_Justification]          INT             DEFAULT ((1)) NOT NULL,
    [MinKPAWeightage]             FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [MaxKPAWeightage]             FLOAT (53)      DEFAULT ((0)) NOT NULL,
    [Score_Using_STDFormula]      INT             DEFAULT ((0)) NULL,
    [Score_Using_PerFormula]      INT             DEFAULT ((0)) NULL,
    [Validity_Period_Type]        INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_T0050_AppraisalLimit_Setting] PRIMARY KEY CLUSTERED ([Limit_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_AppraisalLimit_Setting_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

