CREATE TABLE [dbo].[T0050_SHIFT_ROTATION_DETAIL] (
    [Cmp_ID]        NUMERIC (18) NOT NULL,
    [Shift_Tran_ID] NUMERIC (18) NOT NULL,
    [Rotation_ID]   NUMERIC (18) NOT NULL,
    [Shift_ID]      NUMERIC (18) NOT NULL,
    [Sort_ID]       INT          NOT NULL,
    CONSTRAINT [PK_T0050_SHIFT_ROTATION_DETAIL] PRIMARY KEY NONCLUSTERED ([Shift_Tran_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0050_SHIFT_ROTATION_DETAIL]
    ON [dbo].[T0050_SHIFT_ROTATION_DETAIL]([Rotation_ID] ASC, [Sort_ID] ASC, [Shift_ID] ASC) WITH (FILLFACTOR = 80);

