CREATE TABLE [dbo].[T0055_INCENTIVE_SCHEME_DETAIL] (
    [Scheme_ID] NUMERIC (18) NOT NULL,
    [Row_ID]    NUMERIC (18) NOT NULL,
    [Desig_ID]  NUMERIC (18) NULL,
    [Branch_ID] NUMERIC (18) NULL,
    CONSTRAINT [FK_T0055_SCHEME_DETAIL_T0050_SCHEME] FOREIGN KEY ([Scheme_ID]) REFERENCES [dbo].[T0050_INCENTIVE_SCHEME] ([Scheme_ID])
);

