CREATE TABLE [dbo].[T0052_ResumeFinal_Approval] (
    [CanApp_Id]           NUMERIC (18)    NOT NULL,
    [Cmp_Id]              NUMERIC (18)    NOT NULL,
    [ResumeFinal_ID]      NUMERIC (18)    NULL,
    [Approver_EmpId]      NUMERIC (18)    NULL,
    [Is_Final]            INT             NULL,
    [Approved_Date]       DATETIME        NULL,
    [CanApp_Status]       INT             NULL,
    [Resume_ID]           NUMERIC (18)    NULL,
    [Resume_Status]       INT             NULL,
    [Rec_post_Id]         NUMERIC (18)    NULL,
    [Comments]            VARCHAR (500)   NULL,
    [Branch_id]           NUMERIC (18)    NULL,
    [Grd_id]              NUMERIC (18)    NULL,
    [Desig_id]            NUMERIC (18)    NULL,
    [Dept_id]             NUMERIC (18)    NULL,
    [Joining_date]        DATETIME        NULL,
    [Basic_Salay]         NUMERIC (18, 2) NULL,
    [Login_id]            NUMERIC (18)    NULL,
    [Total_CTC]           NUMERIC (18, 2) NULL,
    [ReportingManager_Id] NUMERIC (18)    NULL,
    [Remarks]             VARCHAR (100)   NULL,
    [ShiftId]             NUMERIC (18)    NULL,
    [EmploymentTypeId]    NUMERIC (18)    NULL,
    [Rpt_Level]           INT             NULL,
    [R_Cmp_Id]            NUMERIC (18)    NULL,
    [Vertical_id]         NUMERIC (18)    NULL,
    [SubVertical_id]      NUMERIC (18)    NULL,
    [Gross_Salary]        NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_T0052_ResumeFinal_Approval] PRIMARY KEY CLUSTERED ([CanApp_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_id]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desig_id]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0040_GRADE_MASTER] FOREIGN KEY ([Grd_id]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0040_SHIFT_MASTER] FOREIGN KEY ([ShiftId]) REFERENCES [dbo].[T0040_SHIFT_MASTER] ([Shift_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0040_Vertical_Segment] FOREIGN KEY ([Vertical_id]) REFERENCES [dbo].[T0040_Vertical_Segment] ([Vertical_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0050_SubVertical] FOREIGN KEY ([SubVertical_id]) REFERENCES [dbo].[T0050_SubVertical] ([SubVertical_ID]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0052_HRMS_Posted_Recruitment] FOREIGN KEY ([Rec_post_Id]) REFERENCES [dbo].[T0052_HRMS_Posted_Recruitment] ([Rec_Post_Id]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0055_Resume_Master] FOREIGN KEY ([Resume_ID]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id]),
    CONSTRAINT [FK_T0052_ResumeFinal_Approval_T0060_RESUME_FINAL] FOREIGN KEY ([ResumeFinal_ID]) REFERENCES [dbo].[T0060_RESUME_FINAL] ([Tran_ID])
);

