CREATE TABLE [dbo].[T0050_HRMS_Recruitment_Request] (
    [Rec_Req_ID]           NUMERIC (18)    NOT NULL,
    [Job_Title]            VARCHAR (50)    NOT NULL,
    [Cmp_id]               NUMERIC (18)    NOT NULL,
    [S_Emp_ID]             NUMERIC (18)    NULL,
    [Login_ID]             NUMERIC (18)    NULL,
    [Posted_date]          DATETIME        NOT NULL,
    [Grade_Id]             NUMERIC (18)    NULL,
    [Desi_Id]              NUMERIC (18)    NULL,
    [Branch_id]            NUMERIC (18)    NULL,
    [Type_ID]              NUMERIC (18)    NULL,
    [Dept_Id]              NUMERIC (18)    NULL,
    [Skill_detail]         NVARCHAR (1000) NULL,
    [Job_Description]      VARCHAR (2500)  NULL,
    [No_of_vacancies]      NUMERIC (3)     NOT NULL,
    [App_status]           TINYINT         NOT NULL,
    [Qualification_detail] VARCHAR (500)   NULL,
    [Experience_Detail]    VARCHAR (500)   NULL,
    [System_Date]          DATETIME        NULL,
    [BusinessSegment_Id]   NUMERIC (18)    NULL,
    [Vertical_Id]          NUMERIC (18)    NULL,
    [SubVertical_Id]       NUMERIC (18)    NULL,
    [Type_Of_Opening]      NUMERIC (18)    NULL,
    [JD_CodeId]            NUMERIC (18)    NULL,
    [Budgeted]             BIT             CONSTRAINT [DF_T0050_HRMS_Recruitment_Request_Budgeted] DEFAULT ((0)) NULL,
    [Exp_Min]              FLOAT (53)      CONSTRAINT [DF_T0050_HRMS_Recruitment_Request_Exp_Min] DEFAULT ((0)) NULL,
    [Exp_Max]              FLOAT (53)      CONSTRAINT [DF_T0050_HRMS_Recruitment_Request_Exp_Max] DEFAULT ((0)) NULL,
    [Rep_EmployeeId]       VARCHAR (MAX)   NULL,
    [Justification]        VARCHAR (1000)  DEFAULT ('') NOT NULL,
    [CTC_Budget]           NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [Is_Left_ReplaceEmpId] BIT             DEFAULT ((0)) NOT NULL,
    [Comments]             VARCHAR (1000)  DEFAULT ('') NOT NULL,
    [Attach_Doc]           VARCHAR (2000)  NULL,
    [Document_ID]          VARCHAR (250)   DEFAULT ('') NOT NULL,
    [Experience_Type]      INT             NULL,
    [MIN_CTC_Budget]       NUMERIC (18, 2) NULL,
    [MRF_Code]             VARCHAR (200)   NULL,
    [Category_ID]          INT             NULL,
    [Manager_Attach_Docs]  VARCHAR (5000)  NULL,
    [Gender_Specific]      VARCHAR (15)    DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_T0050_HRMS_Recruitment_Request_1] PRIMARY KEY CLUSTERED ([Rec_Req_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0011_LOGIN] FOREIGN KEY ([Login_ID]) REFERENCES [dbo].[T0011_LOGIN] ([Login_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_Business_Segment] FOREIGN KEY ([BusinessSegment_Id]) REFERENCES [dbo].[T0040_Business_Segment] ([Segment_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_Id]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desi_Id]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_GRADE_MASTER] FOREIGN KEY ([Grade_Id]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_TYPE_MASTER] FOREIGN KEY ([Type_ID]) REFERENCES [dbo].[T0040_TYPE_MASTER] ([Type_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0040_Vertical_Segment] FOREIGN KEY ([Vertical_Id]) REFERENCES [dbo].[T0040_Vertical_Segment] ([Vertical_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0050_JobDescription_Master] FOREIGN KEY ([JD_CodeId]) REFERENCES [dbo].[T0050_JobDescription_Master] ([Job_Id]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0050_SubVertical] FOREIGN KEY ([SubVertical_Id]) REFERENCES [dbo].[T0050_SubVertical] ([SubVertical_ID]),
    CONSTRAINT [FK_T0050_HRMS_Recruitment_Request_T0080_EMP_MASTER] FOREIGN KEY ([S_Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

