CREATE TABLE [dbo].[T0050_EMP_PAY_SCALE_DETAIL] (
    [Cmp_ID]         NUMERIC (18) NOT NULL,
    [Tran_ID]        NUMERIC (18) NOT NULL,
    [Emp_ID]         NUMERIC (18) NOT NULL,
    [Effective_Date] DATETIME     NOT NULL,
    [Pay_Scale_ID]   NUMERIC (18) NOT NULL,
    [System_date]    DATETIME     NULL,
    CONSTRAINT [PK_T0050_EMP_PAY_SCALE_DETAIL] PRIMARY KEY NONCLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0050_EMP_PAY_SCALE_DETAIL_Emp_ID_Eff_Date_Tran_ID]
    ON [dbo].[T0050_EMP_PAY_SCALE_DETAIL]([Emp_ID] ASC, [Effective_Date] DESC, [Tran_ID] DESC) WITH (FILLFACTOR = 80);

