CREATE TABLE [dbo].[T0060_EMP_MASTER_APP] (
    [Emp_Tran_ID]                    BIGINT          NOT NULL,
    [Emp_Application_ID]             INT             NOT NULL,
    [Emp_ID]                         INT             NOT NULL,
    [Cmp_ID]                         INT             NOT NULL,
    [Branch_ID]                      INT             NOT NULL,
    [Cat_ID]                         INT             NULL,
    [Grd_ID]                         INT             NOT NULL,
    [Dept_ID]                        INT             NULL,
    [Desig_ID]                       INT             NULL,
    [Type_ID]                        INT             NULL,
    [Shift_ID]                       INT             NOT NULL,
    [Bank_ID]                        INT             NULL,
    [Emp_code]                       NUMERIC (18)    NOT NULL,
    [Initial]                        VARCHAR (50)    NULL,
    [Emp_First_Name]                 VARCHAR (100)   NOT NULL,
    [Emp_Second_Name]                VARCHAR (100)   NOT NULL,
    [Emp_Last_Name]                  VARCHAR (100)   NOT NULL,
    [Curr_ID]                        INT             NULL,
    [Date_Of_Join]                   DATETIME        NOT NULL,
    [SSN_No]                         VARCHAR (30)    NULL,
    [SIN_No]                         VARCHAR (30)    NULL,
    [Dr_Lic_No]                      VARCHAR (30)    NULL,
    [Pan_No]                         VARCHAR (30)    NULL,
    [Date_Of_Birth]                  DATETIME        NULL,
    [Marital_Status]                 VARCHAR (20)    NULL,
    [Gender]                         CHAR (1)        NULL,
    [Dr_Lic_Ex_Date]                 DATETIME        NULL,
    [Nationality]                    VARCHAR (20)    NULL,
    [Loc_ID]                         INT             NULL,
    [Street_1]                       VARCHAR (250)   NULL,
    [City]                           VARCHAR (30)    NULL,
    [State]                          VARCHAR (20)    NULL,
    [Zip_code]                       VARCHAR (20)    NULL,
    [Home_Tel_no]                    VARCHAR (30)    NULL,
    [Mobile_No]                      VARCHAR (30)    NULL,
    [Work_Tel_No]                    VARCHAR (30)    NULL,
    [Work_Email]                     VARCHAR (50)    NULL,
    [Other_Email]                    VARCHAR (50)    NULL,
    [Basic_Salary]                   NUMERIC (18, 4) NULL,
    [Image_Name]                     VARCHAR (200)   NULL,
    [Emp_Full_Name]                  VARCHAR (250)   NULL,
    [Emp_Left]                       CHAR (1)        NULL,
    [Emp_Left_Date]                  DATETIME        NULL,
    [Increment_ID]                   INT             NULL,
    [Present_Street]                 VARCHAR (250)   NULL,
    [Present_City]                   VARCHAR (30)    NULL,
    [Present_State]                  VARCHAR (20)    NULL,
    [Present_Post_Box]               VARCHAR (20)    NULL,
    [Emp_Superior]                   NUMERIC (18)    NULL,
    [Enroll_No]                      NUMERIC (18)    NULL,
    [Blood_Group]                    VARCHAR (10)    NULL,
    [Tally_Led_Name]                 VARCHAR (100)   NULL,
    [Religion]                       VARCHAR (50)    NULL,
    [Height]                         VARCHAR (50)    NULL,
    [Emp_Mark_Of_Identification]     VARCHAR (250)   NULL,
    [Despencery]                     VARCHAR (250)   NULL,
    [Doctor_Name]                    VARCHAR (100)   NULL,
    [DespenceryAddress]              VARCHAR (250)   NULL,
    [Insurance_No]                   VARCHAR (50)    NULL,
    [Is_Gr_App]                      TINYINT         NULL,
    [Is_Yearly_Bonus]                TINYINT         NULL,
    [Yearly_Leave_Days]              NUMERIC (5, 2)  NULL,
    [Yearly_Leave_Amount]            NUMERIC (7)     NULL,
    [Yearly_Bonus_Per]               NUMERIC (5, 2)  NULL,
    [Yearly_Bonus_Amount]            NUMERIC (7)     NULL,
    [Emp_Confirm_Date]               DATETIME        NULL,
    [IS_Emp_FNF]                     TINYINT         NULL,
    [Is_On_Probation]                TINYINT         NULL,
    [Tally_Led_ID]                   INT             NULL,
    [Login_ID]                       INT             NULL,
    [System_Date]                    DATETIME        NULL,
    [Probation]                      NUMERIC (18, 2) NULL,
    [Worker_Adult_No]                NUMERIC (18)    NULL,
    [Father_name]                    VARCHAR (100)   NULL,
    [Bank_BSR]                       VARCHAR (100)   NULL,
    [Product_name]                   VARCHAR (50)    NULL,
    [Old_Ref_No]                     VARCHAR (50)    NULL,
    [Chg_Pwd]                        INT             NULL,
    [Alpha_Code]                     VARCHAR (20)    NULL,
    [Alpha_Emp_Code]                 VARCHAR (50)    NULL,
    [Ifsc_Code]                      VARCHAR (50)    NULL,
    [Leave_In_Probation]             TINYINT         NULL,
    [Is_LWF]                         TINYINT         NOT NULL,
    [DBRD_Code]                      VARCHAR (50)    NULL,
    [Dealer_Code]                    VARCHAR (50)    NULL,
    [CCenter_Remark]                 VARCHAR (500)   NULL,
    [Emp_PF_Opening]                 NUMERIC (18, 2) NOT NULL,
    [Emp_Category]                   VARCHAR (50)    NULL,
    [Emp_UIDNo]                      VARCHAR (25)    NULL,
    [Emp_Cast]                       VARCHAR (50)    NULL,
    [Emp_Annivarsary_Date]           VARCHAR (50)    NULL,
    [Extra_AB_Deduction]             NUMERIC (18, 2) NULL,
    [CompOff_Min_hrs]                VARCHAR (10)    NOT NULL,
    [mother_name]                    VARCHAR (100)   NULL,
    [Min_Wages]                      NUMERIC (18, 2) NOT NULL,
    [Emp_Offer_Date]                 DATETIME        NULL,
    [Segment_ID]                     INT             NULL,
    [Vertical_ID]                    INT             NULL,
    [SubVertical_ID]                 INT             NULL,
    [GroupJoiningDate]               DATETIME        NULL,
    [subBranch_ID]                   INT             NULL,
    [Bank_ID_Two]                    NUMERIC (18)    NULL,
    [Ifsc_Code_Two]                  VARCHAR (50)    NULL,
    [Code_Date_Format]               VARCHAR (10)    NULL,
    [Code_Date]                      VARCHAR (10)    NULL,
    [EmpName_Alias_PrimaryBank]      VARCHAR (100)   NULL,
    [EmpName_Alias_SecondaryBank]    VARCHAR (100)   NULL,
    [EmpName_Alias_PF]               VARCHAR (100)   NULL,
    [EmpName_Alias_PT]               VARCHAR (100)   NULL,
    [EmpName_Alias_Tax]              VARCHAR (100)   NULL,
    [EmpName_Alias_ESIC]             VARCHAR (100)   NULL,
    [EmpName_Alias_Salary]           VARCHAR (100)   NULL,
    [Emp_Notice_Period]              NUMERIC (18)    NOT NULL,
    [System_Date_Join_left]          DATETIME        NULL,
    [Emp_Canteen_Code]               VARCHAR (50)    NULL,
    [Emp_Dress_Code]                 VARCHAR (50)    NULL,
    [Emp_Shirt_Size]                 VARCHAR (20)    NULL,
    [Emp_Pent_Size]                  VARCHAR (20)    NULL,
    [Emp_Shoe_Size]                  VARCHAR (20)    NULL,
    [Thana_ID]                       INT             NOT NULL,
    [Tehsil]                         VARCHAR (50)    NULL,
    [District]                       VARCHAR (50)    NULL,
    [Thana_Id_Wok]                   NUMERIC (18)    NOT NULL,
    [Tehsil_Wok]                     VARCHAR (50)    NULL,
    [District_Wok]                   VARCHAR (50)    NULL,
    [SkillType_ID]                   INT             NULL,
    [About_Me]                       NVARCHAR (MAX)  NULL,
    [UAN_No]                         VARCHAR (100)   NULL,
    [CompOff_WO_App_Days]            NUMERIC (18, 2) NOT NULL,
    [CompOff_WO_Avail_Days]          NUMERIC (18, 2) NOT NULL,
    [CompOff_WD_App_Days]            NUMERIC (18, 2) NOT NULL,
    [CompOff_WD_Avail_Days]          NUMERIC (18, 2) NOT NULL,
    [CompOff_HO_App_Days]            NUMERIC (18, 2) NOT NULL,
    [CompOff_HO_Avail_Days]          NUMERIC (18, 2) NOT NULL,
    [Date_of_Retirement]             DATETIME        NULL,
    [Salary_Depends_on_Production]   NUMERIC (1)     NOT NULL,
    [Ration_Card_Type]               VARCHAR (10)    NULL,
    [Ration_Card_No]                 VARCHAR (50)    NULL,
    [Vehicle_NO]                     VARCHAR (50)    NULL,
    [Is_On_Training]                 NUMERIC (2)     NOT NULL,
    [Training_Month]                 NUMERIC (18, 2) NULL,
    [Aadhar_Card_No]                 VARCHAR (50)    NULL,
    [is_for_mobile_Access]           TINYINT         NOT NULL,
    [Actual_Date_Of_Birth]           DATETIME        NULL,
    [is_PF_Trust]                    TINYINT         NOT NULL,
    [PF_Trust_No]                    VARCHAR (500)   NULL,
    [Extension_No]                   VARCHAR (10)    NULL,
    [LinkedIn_ID]                    VARCHAR (100)   NULL,
    [Twitter_ID]                     VARCHAR (100)   NULL,
    [Manager_Probation]              NUMERIC (18)    NOT NULL,
    [PF_Start_Date]                  DATETIME        NULL,
    [Signature_Image_Name]           VARCHAR (200)   NULL,
    [Leave_Encash_Working_Days]      NUMERIC (18, 2) NOT NULL,
    [Rejoin_Emp_ID]                  INT             NOT NULL,
    [Is_Camera_enable]               TINYINT         NOT NULL,
    [Is_Geofence_enable]             TINYINT         NOT NULL,
    [Is_Probation_Month_Days]        TINYINT         NOT NULL,
    [Is_Trainee_Month_Days]          TINYINT         NOT NULL,
    [Induction_Training]             VARCHAR (200)   NULL,
    [Approve_Status]                 CHAR (1)        NULL,
    [Approved_Emp_ID]                INT             NULL,
    [Approved_Date]                  DATETIME        NULL,
    [Rpt_Level]                      INT             NULL,
    [Is_Final_Approval]              BIT             NULL,
    [Ref_Emp_Tran_ID]                BIGINT          NULL,
    [HolidayCompOffAvail_After_Days] NUMERIC (18)    DEFAULT ((0)) NULL,
    [WeekOffCompOffAvail_After_Days] NUMERIC (18)    DEFAULT ((0)) NULL,
    [WeekdayCompOffAvail_After_Days] NUMERIC (18)    DEFAULT ((0)) NULL,
    [Band_Id]                        NUMERIC (18)    NULL,
    [Is_Pradhan_Mantri]              BIT             NULL,
    [Is_1time_PF_Member]             BIT             NULL,
    [Emp_Cast_Join]                  VARCHAR (50)    NULL,
    [Comment]                        VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_T0060_EMP_MASTER_APP] PRIMARY KEY NONCLUSTERED ([Emp_Tran_ID] ASC)
);

