CREATE TABLE [dbo].[T0060_GPF_INTEREST_RATE] (
    [Cmp_ID]         NUMERIC (18)    NOT NULL,
    [Tran_ID]        NUMERIC (18)    NOT NULL,
    [AD_ID]          NUMERIC (18)    NOT NULL,
    [Effective_Date] DATETIME        NOT NULL,
    [Interest_Rate]  NUMERIC (18, 4) NOT NULL,
    [System_date]    DATETIME        NULL,
    CONSTRAINT [PK_T0060_GPF_INTEREST_RATE] PRIMARY KEY NONCLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0060_GPF_INTEREST_RATE]
    ON [dbo].[T0060_GPF_INTEREST_RATE]([AD_ID] ASC, [Effective_Date] DESC) WITH (FILLFACTOR = 80);

