CREATE TABLE [dbo].[T0060_Appraisal_EmployeeKPA] (
    [Emp_KPA_Id]             NUMERIC (18)    NOT NULL,
    [Cmp_Id]                 NUMERIC (18)    NOT NULL,
    [Emp_Id]                 NUMERIC (18)    NOT NULL,
    [KPA_Content]            NVARCHAR (1500) NULL,
    [KPA_Target]             NVARCHAR (1000) NULL,
    [KPA_Weightage]          NUMERIC (18, 2) NULL,
    [Effective_Date]         DATETIME        NULL,
    [status]                 INT             CONSTRAINT [DF_T0060_Appraisal_EmployeeKPA_status] DEFAULT ((1)) NULL,
    [KPA_Type_ID]            NUMERIC (18)    NULL,
    [KPA_Performace_Measure] NVARCHAR (500)  NULL,
    [Completion_Date]        DATETIME        NULL,
    [Attach_Docs]            VARCHAR (1000)  NULL,
    [KPA_InitiateId]         INT             NULL,
    [Remarks]                NVARCHAR (2000) NULL,
    [Is_Active]              BIT             DEFAULT ((1)) NOT NULL,
    [SrNo]                   INT             NULL,
    [Approval_Level]         VARCHAR (10)    NULL,
    [SystemDate]             DATETIME        NULL,
    [UserId]                 INT             NULL,
    [Emp_Comment]            NVARCHAR (500)  NULL,
    [RM_Comment]             NVARCHAR (500)  NULL,
    [HOD_Comment]            NVARCHAR (500)  NULL,
    [GH_Comment]             NVARCHAR (500)  NULL,
    CONSTRAINT [PK_T0060_Appraisal_EmployeeKPA] PRIMARY KEY CLUSTERED ([Emp_KPA_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0060_Appraisal_EmployeeKPA_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0060_Appraisal_EmployeeKPA_T0040_HRMS_KPAType_Master] FOREIGN KEY ([KPA_Type_ID]) REFERENCES [dbo].[T0040_HRMS_KPAType_Master] ([KPA_Type_Id]),
    CONSTRAINT [FK_T0060_Appraisal_EmployeeKPA_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

