CREATE TABLE [dbo].[T0060_EFFECT_AD_MASTER] (
    [AD_TRAN_ID]   NUMERIC (18) NOT NULL,
    [AD_ID]        NUMERIC (18) NOT NULL,
    [CMP_ID]       NUMERIC (18) NOT NULL,
    [EFFECT_AD_ID] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0060_EFFECT_AD_MASTER] PRIMARY KEY CLUSTERED ([AD_TRAN_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0060_EFFECT_AD_MASTER_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0060_EFFECT_AD_MASTER_T0050_AD_MASTER] FOREIGN KEY ([AD_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID]),
    CONSTRAINT [FK_T0060_EFFECT_AD_MASTER_T0050_AD_MASTER1] FOREIGN KEY ([EFFECT_AD_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID])
);

