CREATE TABLE [dbo].[T0070_EMP_INCREMENT_APP] (
    [Emp_Tran_ID]                   BIGINT          NOT NULL,
    [Emp_Application_ID]            INT             NOT NULL,
    [Increment_ID]                  INT             NOT NULL,
    [Cmp_ID]                        INT             NOT NULL,
    [Branch_ID]                     INT             NOT NULL,
    [Cat_ID]                        INT             NULL,
    [Grd_ID]                        INT             NOT NULL,
    [Dept_ID]                       INT             NULL,
    [Desig_ID]                      INT             NULL,
    [Type_ID]                       INT             NULL,
    [Bank_ID]                       INT             NULL,
    [Curr_ID]                       INT             NULL,
    [Wages_Type]                    VARCHAR (10)    NULL,
    [Salary_Basis_On]               VARCHAR (20)    NULL,
    [Basic_Salary]                  NUMERIC (18, 4) NULL,
    [Gross_Salary]                  NUMERIC (18, 4) NULL,
    [Increment_Type]                VARCHAR (30)    NULL,
    [Increment_Date]                DATETIME        NOT NULL,
    [Increment_Effective_Date]      DATETIME        NOT NULL,
    [Payment_Mode]                  VARCHAR (20)    NULL,
    [Inc_Bank_AC_No]                VARCHAR (20)    NULL,
    [Emp_OT]                        NUMERIC (18)    NULL,
    [Emp_OT_Min_Limit]              VARCHAR (10)    NULL,
    [Emp_OT_Max_Limit]              VARCHAR (10)    NULL,
    [Increment_Per]                 NUMERIC (18, 2) NULL,
    [Increment_Amount]              NUMERIC (18, 4) NULL,
    [Pre_Basic_Salary]              NUMERIC (18, 4) NULL,
    [Pre_Gross_Salary]              NUMERIC (18, 4) NULL,
    [Increment_Comments]            VARCHAR (250)   NULL,
    [Emp_Late_mark]                 NUMERIC (1)     NULL,
    [Emp_Full_PF]                   NUMERIC (1)     NULL,
    [Emp_PT]                        NUMERIC (1)     NULL,
    [Emp_Fix_Salary]                NUMERIC (1)     NULL,
    [Emp_Part_Time]                 TINYINT         NULL,
    [Late_Dedu_Type]                VARCHAR (10)    NULL,
    [Emp_Late_Limit]                VARCHAR (10)    NULL,
    [Emp_PT_Amount]                 NUMERIC (5)     NULL,
    [Emp_Childran]                  TINYINT         NULL,
    [Is_Master_Rec]                 TINYINT         NULL,
    [Login_ID]                      INT             NULL,
    [System_Date]                   DATETIME        NULL,
    [Yearly_Bonus_Amount]           NUMERIC (22, 2) NULL,
    [Deputation_End_Date]           DATETIME        NULL,
    [Is_Deputation_Reminder]        TINYINT         NULL,
    [Appr_Int_ID]                   INT             NULL,
    [CTC]                           NUMERIC (18, 4) NULL,
    [Emp_Early_mark]                NUMERIC (1)     NULL,
    [Early_Dedu_Type]               VARCHAR (10)    NULL,
    [Emp_Early_Limit]               VARCHAR (10)    NULL,
    [Emp_Deficit_mark]              NUMERIC (1)     NULL,
    [Deficit_Dedu_Type]             VARCHAR (10)    NULL,
    [Emp_Deficit_Limit]             VARCHAR (10)    NULL,
    [Center_ID]                     INT             NULL,
    [Emp_WeekDay_OT_Rate]           NUMERIC (10, 3) NULL,
    [Emp_WeekOff_OT_Rate]           NUMERIC (10, 3) NULL,
    [Emp_Holiday_OT_Rate]           NUMERIC (10, 3) NULL,
    [Is_Metro_City]                 TINYINT         NOT NULL,
    [Pre_CTC_Salary]                NUMERIC (18, 4) NOT NULL,
    [Incerment_Amount_gross]        NUMERIC (18, 4) NOT NULL,
    [Incerment_Amount_CTC]          NUMERIC (18, 4) NOT NULL,
    [Increment_Mode]                TINYINT         NOT NULL,
    [is_physical]                   TINYINT         NULL,
    [SalDate_ID]                    INT             NULL,
    [Emp_Auto_Vpf]                  TINYINT         NOT NULL,
    [Segment_ID]                    INT             NULL,
    [Vertical_ID]                   INT             NULL,
    [SubVertical_ID]                INT             NULL,
    [subBranch_ID]                  INT             NULL,
    [Monthly_Deficit_Adjust_OT_Hrs] TINYINT         NOT NULL,
    [Fix_OT_Hour_Rate_WD]           NUMERIC (18, 3) NOT NULL,
    [Fix_OT_Hour_Rate_WO_HO]        NUMERIC (18, 3) NOT NULL,
    [Bank_ID_Two]                   NUMERIC (18)    NULL,
    [Payment_Mode_Two]              VARCHAR (20)    NULL,
    [Inc_Bank_AC_No_Two]            VARCHAR (20)    NULL,
    [Bank_Branch_Name]              VARCHAR (50)    NULL,
    [Bank_Branch_Name_Two]          VARCHAR (50)    NULL,
    [Reason_ID]                     NUMERIC (5)     NOT NULL,
    [Reason_Name]                   VARCHAR (200)   NULL,
    [Increment_App_ID]              INT             NULL,
    [Customer_Audit]                TINYINT         NOT NULL,
    [Sales_Code]                    VARCHAR (20)    NULL,
    [Physical_Percent]              NUMERIC (18, 2) NOT NULL,
    [Approved_Emp_ID]               INT             NULL,
    [Approved_Date]                 DATETIME        NULL,
    [Rpt_Level]                     INT             NULL,
    [Pay_Scale_ID]                  INT             NULL,
    [Pay_Scale_Effective_Date]      DATETIME        NULL,
    CONSTRAINT [FK_T0070_EMP_INCREMENT_APP_T0060_EMP_MASTER_APP] FOREIGN KEY ([Emp_Tran_ID]) REFERENCES [dbo].[T0060_EMP_MASTER_APP] ([Emp_Tran_ID])
);

