CREATE TABLE [dbo].[T0080_File_Approval] (
    [File_Apr_Id]        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [File_App_Id]        INT            CONSTRAINT [DF_T0080_File_Approval_File_App_Id] DEFAULT ((0)) NULL,
    [Approve_Date]       DATETIME       NULL,
    [Branch_Id]          NUMERIC (18)   NULL,
    [Dept_Id]            NUMERIC (18)   NULL,
    [Desig_Id]           NUMERIC (18)   NULL,
    [Emp_Id]             NUMERIC (18)   NULL,
    [S_Emp_Id]           NUMERIC (18)   NULL,
    [File_Number]        VARCHAR (50)   NOT NULL,
    [F_StatusId]         INT            CONSTRAINT [DF_T0080_File_Approval_F_StatusId] DEFAULT ((0)) NULL,
    [F_TypeId]           NUMERIC (18)   NULL,
    [Subject]            VARCHAR (500)  NULL,
    [Description]        VARCHAR (MAX)  NULL,
    [Process_Date]       DATETIME       NULL,
    [File_App_Doc]       NVARCHAR (MAX) NULL,
    [Cmp_ID]             NUMERIC (18)   NULL,
    [CreatedDate]        DATETIME       NULL,
    [CreatedBy]          VARCHAR (MAX)  NULL,
    [UpdatedDate]        DATETIME       NULL,
    [UpdatedBy]          VARCHAR (MAX)  NULL,
    [User ID]            VARCHAR (MAX)  NULL,
    [Forward_Emp_Id]     NUMERIC (18)   NULL,
    [Submit_Emp_Id]      NUMERIC (18)   NULL,
    [Approval_Comments]  VARCHAR (500)  NULL,
    [Review_Emp_Id]      NUMERIC (18)   NULL,
    [Reviewed_by_Emp_Id] NUMERIC (18)   NULL,
    [File_Type_Number]   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0080_File_Approval] PRIMARY KEY CLUSTERED ([File_Apr_Id] ASC) WITH (FILLFACTOR = 95)
);

