CREATE TABLE [dbo].[T0080_EMP_MASTER_shadow] (
    [AuditId]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [Emp_ID]                     NUMERIC (18)    NOT NULL,
    [Cmp_ID]                     NUMERIC (18)    NOT NULL,
    [Branch_ID]                  NUMERIC (18)    NOT NULL,
    [Cat_ID]                     NUMERIC (18)    NULL,
    [Grd_ID]                     NUMERIC (18)    NOT NULL,
    [Dept_ID]                    NUMERIC (18)    NULL,
    [Desig_Id]                   NUMERIC (18)    NULL,
    [Type_ID]                    NUMERIC (18)    NULL,
    [Shift_ID]                   NUMERIC (18)    NOT NULL,
    [Bank_ID]                    NUMERIC (18)    NULL,
    [Emp_code]                   NUMERIC (18)    NOT NULL,
    [Initial]                    VARCHAR (50)    NULL,
    [Emp_First_Name]             VARCHAR (100)   NOT NULL,
    [Emp_Second_Name]            VARCHAR (100)   NOT NULL,
    [Emp_Last_Name]              VARCHAR (100)   NOT NULL,
    [Curr_ID]                    NUMERIC (18)    NULL,
    [Date_Of_Join]               DATETIME        NOT NULL,
    [SSN_No]                     VARCHAR (30)    NULL,
    [SIN_No]                     VARCHAR (30)    NULL,
    [Dr_Lic_No]                  VARCHAR (30)    NULL,
    [Pan_No]                     VARCHAR (30)    NULL,
    [Date_Of_Birth]              DATETIME        NULL,
    [Marital_Status]             VARCHAR (20)    NULL,
    [Gender]                     CHAR (1)        NULL,
    [Dr_Lic_Ex_Date]             DATETIME        NULL,
    [Nationality]                VARCHAR (20)    NULL,
    [Loc_ID]                     NUMERIC (18)    NULL,
    [Street_1]                   VARCHAR (250)   NULL,
    [City]                       VARCHAR (30)    NULL,
    [State]                      VARCHAR (100)   NULL,
    [Zip_code]                   VARCHAR (20)    NULL,
    [Home_Tel_no]                VARCHAR (30)    NULL,
    [Mobile_No]                  VARCHAR (30)    NULL,
    [Work_Tel_No]                VARCHAR (30)    NULL,
    [Work_Email]                 VARCHAR (50)    NULL,
    [Other_Email]                VARCHAR (50)    NULL,
    [Basic_Salary]               NUMERIC (18, 2) NULL,
    [Image_Name]                 VARCHAR (100)   NULL,
    [Emp_Full_Name]              VARCHAR (250)   NULL,
    [Emp_Left]                   CHAR (1)        NULL,
    [Emp_Left_Date]              DATETIME        NULL,
    [Increment_ID]               NUMERIC (18)    NULL,
    [Present_Street]             VARCHAR (250)   NULL,
    [Present_City]               VARCHAR (30)    NULL,
    [Present_State]              VARCHAR (100)   NULL,
    [Present_Post_Box]           VARCHAR (20)    NULL,
    [Emp_Superior]               NUMERIC (18)    NULL,
    [Enroll_No]                  NUMERIC (18)    NULL,
    [Blood_Group]                VARCHAR (10)    NULL,
    [Tally_Led_Name]             VARCHAR (100)   NULL,
    [Religion]                   VARCHAR (50)    NULL,
    [Height]                     VARCHAR (50)    NULL,
    [Emp_Mark_Of_Identification] VARCHAR (250)   NULL,
    [Despencery]                 VARCHAR (250)   NULL,
    [Doctor_Name]                VARCHAR (100)   NULL,
    [DespenceryAddress]          VARCHAR (250)   NULL,
    [Insurance_No]               VARCHAR (50)    NULL,
    [Is_Gr_App]                  TINYINT         NULL,
    [Is_Yearly_Bonus]            TINYINT         NULL,
    [Yearly_Leave_Days]          NUMERIC (5, 2)  NULL,
    [Yearly_Leave_Amount]        NUMERIC (7)     NULL,
    [Yearly_Bonus_Per]           NUMERIC (5, 2)  NULL,
    [Yearly_Bonus_Amount]        NUMERIC (7)     NULL,
    [Emp_Confirm_Date]           DATETIME        NULL,
    [IS_Emp_FNF]                 TINYINT         NULL,
    [Is_On_Probation]            TINYINT         NULL,
    [Tally_Led_ID]               NUMERIC (18)    NULL,
    [Login_ID]                   NUMERIC (18)    NULL,
    [System_Date]                DATETIME        NULL,
    [Probation]                  NUMERIC (18, 2) NULL,
    [Worker_Adult_No]            NUMERIC (18)    NULL,
    [Father_name]                VARCHAR (100)   NULL,
    [Bank_BSR]                   VARCHAR (100)   NULL,
    [Product_name]               VARCHAR (50)    NULL,
    [Old_Ref_No]                 VARCHAR (50)    NULL,
    [AuditAction]                CHAR (1)        NOT NULL,
    [AuditDate]                  DATETIME        CONSTRAINT [DF_T0080_EMP_MASTER_shadow_AuditDate] DEFAULT (getdate()) NOT NULL,
    [login_id1]                  NUMERIC (18)    NULL,
    [AuditUser]                  VARCHAR (50)    CONSTRAINT [DF_T0080_EMP_MASTER_shadow_AuditUser] DEFAULT (suser_sname()) NOT NULL,
    [AuditApp]                   VARCHAR (128)   CONSTRAINT [DF_T0080_EMP_MASTER_shadow_AuditApp] DEFAULT (('App=('+rtrim(isnull(app_name(),'')))+') ') NULL,
    [Chg_Pwd]                    INT             NULL,
    [Alpha_Code]                 VARCHAR (20)    NULL,
    [Alpha_Emp_Code]             VARCHAR (50)    NULL,
    [Ifsc_Code]                  VARCHAR (50)    NULL,
    [Leave_In_Probation]         TINYINT         NULL,
    CONSTRAINT [PK_T0080_EMP_MASTER_shadow] PRIMARY KEY CLUSTERED ([AuditId] ASC) WITH (FILLFACTOR = 80)
);

