CREATE TABLE [dbo].[T0090_EMP_PRIVILEGE_DETAILS] (
    [Trans_Id]     NUMERIC (18) NOT NULL,
    [Cmp_id]       NUMERIC (18) NOT NULL,
    [Login_Id]     NUMERIC (18) NOT NULL,
    [Privilege_Id] NUMERIC (18) NOT NULL,
    [From_Date]    DATETIME     NULL,
    CONSTRAINT [PK_T0080_EMP_PRIVILEGE_DETAILS] PRIMARY KEY CLUSTERED ([Trans_Id] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_PRIVILEGE_DETAILS_26_1575012692__K5D_K3_4]
    ON [dbo].[T0090_EMP_PRIVILEGE_DETAILS]([From_Date] DESC, [Login_Id] ASC)
    INCLUDE([Privilege_Id]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0090_EMP_PRIVILEGE_DETAILS_Login_Id_From_Date_Privilege_Id]
    ON [dbo].[T0090_EMP_PRIVILEGE_DETAILS]([Login_Id] ASC, [From_Date] ASC)
    INCLUDE([Privilege_Id]);


GO
CREATE STATISTICS [_dta_stat_1575012692_3_4_5]
    ON [dbo].[T0090_EMP_PRIVILEGE_DETAILS]([Login_Id], [Privilege_Id], [From_Date]);

