CREATE TABLE [dbo].[T0090_EMP_DOC_DETAIL] (
    [Row_ID]             NUMERIC (18)  NOT NULL,
    [Emp_ID]             NUMERIC (18)  NOT NULL,
    [Cmp_ID]             NUMERIC (18)  NOT NULL,
    [Doc_ID]             NUMERIC (18)  NOT NULL,
    [Doc_Path]           VARCHAR (500) NOT NULL,
    [Doc_Comments]       VARCHAR (250) NOT NULL,
    [Date_of_Expiry]     DATETIME      NULL,
    [DocUpload_DateTime] DATE          NULL,
    [Verify]             BIT           NULL,
    CONSTRAINT [PK_T0090_EMP_DOC_DETAIL_1] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_DOC_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_DOC_DETAIL_T0040_DOCUMENT_MASTER] FOREIGN KEY ([Doc_ID]) REFERENCES [dbo].[T0040_DOCUMENT_MASTER] ([Doc_ID]),
    CONSTRAINT [FK_T0090_EMP_DOC_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

