CREATE TABLE [dbo].[T0095_EMP_COMPANY_TRANSFER] (
    [Tran_Id]               NUMERIC (18)  NOT NULL,
    [Old_Cmp_Id]            NUMERIC (18)  NOT NULL,
    [Old_Emp_Id]            NUMERIC (18)  NOT NULL,
    [Old_Branch_Id]         NUMERIC (18)  NOT NULL,
    [Old_Grd_Id]            NUMERIC (18)  NOT NULL,
    [Old_Desig_Id]          NUMERIC (18)  NOT NULL,
    [Old_Dept_Id]           NUMERIC (18)  NOT NULL,
    [Old_Shift_Id]          NUMERIC (18)  NOT NULL,
    [Old_Type_Id]           NUMERIC (18)  NOT NULL,
    [Old_Cat_Id]            NUMERIC (18)  NOT NULL,
    [Old_Client_Id]         NUMERIC (18)  NOT NULL,
    [Old_Emp_Manager_Id]    NUMERIC (18)  NOT NULL,
    [Old_Emp_WeekOff_Day]   VARCHAR (100) NULL,
    [Effective_Date]        DATETIME      NOT NULL,
    [New_Cmp_Id]            NUMERIC (18)  NOT NULL,
    [New_Emp_Id]            NUMERIC (18)  NOT NULL,
    [New_Branch_Id]         NUMERIC (18)  NOT NULL,
    [New_Grd_Id]            NUMERIC (18)  NOT NULL,
    [New_Desig_Id]          NUMERIC (18)  NOT NULL,
    [New_Dept_Id]           NUMERIC (18)  NULL,
    [New_Shift_Id]          NUMERIC (18)  NOT NULL,
    [New_Cat_Id]            NUMERIC (18)  NULL,
    [New_Type_Id]           NUMERIC (18)  NULL,
    [New_Client_Id]         NUMERIC (18)  NOT NULL,
    [New_Emp_mngr_Id]       NUMERIC (18)  NULL,
    [New_Emp_WeekOff_Day]   VARCHAR (100) NULL,
    [Old_Privilege_ID]      NUMERIC (18)  NULL,
    [New_Privilege_ID]      NUMERIC (18)  NULL,
    [New_SubVertical_ID]    NUMERIC (18)  NULL,
    [New_Segment_ID]        NUMERIC (18)  NULL,
    [New_SubBranch_ID]      NUMERIC (18)  NULL,
    [New_Login_Alias]       VARCHAR (50)  NULL,
    [Old_Login_Alias]       VARCHAR (50)  NULL,
    [Old_SubVertical_ID]    NUMERIC (18)  NULL,
    [Old_Segment_ID]        NUMERIC (18)  NULL,
    [Old_SubBranch_ID]      NUMERIC (18)  NULL,
    [New_SalCycle_ID]       NUMERIC (18)  NULL,
    [Old_SalCycle_Id]       NUMERIC (18)  NULL,
    [Is_MultiPage_Flag]     TINYINT       CONSTRAINT [DF_T0095_EMP_COMPANY_TRANSFER_Is_MultiPage_Flag] DEFAULT ((0)) NOT NULL,
    [ReplaceManager_Cmp_ID] NUMERIC (18)  NULL,
    [ReplaceManager_ID]     NUMERIC (18)  NULL,
    CONSTRAINT [PK_T0095_EMP_COMPANY_TRANSFER] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80)
);

