CREATE TABLE [dbo].[T0090_EMP_REPORTING_DETAIL] (
    [Row_ID]           NUMERIC (18) NOT NULL,
    [Emp_ID]           NUMERIC (18) NOT NULL,
    [R_Emp_ID]         NUMERIC (18) NULL,
    [Cmp_ID]           NUMERIC (18) NOT NULL,
    [Reporting_To]     VARCHAR (30) NOT NULL,
    [Reporting_Method] VARCHAR (20) NOT NULL,
    [Effect_Date]      DATETIME     NULL,
    CONSTRAINT [PK_T0090_EMP_REPORTING_DETAIL_1] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_REPORTING_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_REPORTING_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0090_EMP_REPORTING_DETAIL_T0080_EMP_MASTER1] FOREIGN KEY ([R_Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_11_66099276__K3_K2_7]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([R_Emp_ID] ASC, [Emp_ID] ASC)
    INCLUDE([Effect_Date]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_12_222623836__K3_K2_K4_K6_7]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([R_Emp_ID] ASC, [Emp_ID] ASC, [Cmp_ID] ASC, [Reporting_Method] ASC)
    INCLUDE([Effect_Date]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_8_66099276__K2_7]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Emp_ID] ASC)
    INCLUDE([Effect_Date]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_10_66099276__K2_K7]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Emp_ID] ASC, [Effect_Date] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_9_66099276__K2_K7_K3_K1]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Emp_ID] ASC, [Effect_Date] ASC, [R_Emp_ID] ASC, [Row_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0090_EMP_REPORTING_DETAIL_9_66099276__K7_K3_K2]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Effect_Date] ASC, [R_Emp_ID] ASC, [Emp_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE STATISTICS [_dta_stat_222623836_3_4]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([R_Emp_ID], [Cmp_ID]);


GO
CREATE STATISTICS [_dta_stat_222623836_6_3_4]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Reporting_Method], [R_Emp_ID], [Cmp_ID]);


GO
CREATE STATISTICS [_dta_stat_222623836_2_6_3]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Emp_ID], [Reporting_Method], [R_Emp_ID]);


GO
CREATE STATISTICS [_dta_stat_222623836_2_4_6]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Emp_ID], [Cmp_ID], [Reporting_Method]);


GO
CREATE STATISTICS [_dta_stat_66099276_1_7_3]
    ON [dbo].[T0090_EMP_REPORTING_DETAIL]([Row_ID], [Effect_Date], [R_Emp_ID]);

