CREATE TABLE [dbo].[T0090_EMP_LANGUAGE_DETAIL] (
    [Row_ID]       NUMERIC (18)  NOT NULL,
    [Emp_Id]       NUMERIC (18)  NOT NULL,
    [Cmp_ID]       NUMERIC (18)  NOT NULL,
    [Lang_ID]      NUMERIC (18)  NOT NULL,
    [Lang_Fluency] VARCHAR (20)  NOT NULL,
    [Lang_Ability] VARCHAR (200) NULL,
    CONSTRAINT [PK_T0090_EMP_LANGUAGE_DETAIL] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_LANGUAGE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_LANGUAGE_DETAIL_T0040_LANGUAGE_MASTER] FOREIGN KEY ([Lang_ID]) REFERENCES [dbo].[T0040_LANGUAGE_MASTER] ([Lang_ID]),
    CONSTRAINT [FK_T0090_EMP_LANGUAGE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

