CREATE TABLE [dbo].[T0090_Change_Request_Approval] (
    [Request_Apr_ID]               NUMERIC (18)    NOT NULL,
    [Request_id]                   NUMERIC (18)    NOT NULL,
    [Cmp_id]                       NUMERIC (18)    NULL,
    [Emp_ID]                       NUMERIC (18)    NULL,
    [Request_Type_id]              NUMERIC (18)    NULL,
    [Change_Reason]                VARCHAR (500)   NULL,
    [Request_Date]                 DATETIME        NULL,
    [Effective_Date]               DATETIME        NULL,
    [Shift_From_Date]              DATETIME        NULL,
    [Shift_To_Date]                DATETIME        NULL,
    [Curr_Details]                 VARCHAR (500)   NULL,
    [New_Details]                  VARCHAR (MAX)   NULL,
    [Curr_Tehsil]                  VARCHAR (MAX)   NULL,
    [Curr_District]                VARCHAR (200)   NULL,
    [Curr_Thana]                   VARCHAR (200)   NULL,
    [Curr_City_Village]            VARCHAR (200)   NULL,
    [Curr_State]                   VARCHAR (200)   NULL,
    [Curr_Pincode]                 NUMERIC (18)    NULL,
    [New_Tehsil]                   VARCHAR (200)   NULL,
    [New_District]                 VARCHAR (200)   NULL,
    [New_Thana]                    VARCHAR (200)   NULL,
    [New_City_Village]             VARCHAR (200)   NULL,
    [New_State]                    VARCHAR (200)   NULL,
    [New_Pincode]                  NUMERIC (18)    NULL,
    [Request_status]               CHAR (1)        NULL,
    [Increment_ID]                 NUMERIC (18)    NULL,
    [Increment_ID_old]             NUMERIC (18)    NULL,
    [Quaulification_ID]            NUMERIC (6)     NULL,
    [Specialization]               VARCHAR (500)   NULL,
    [Passing_Year]                 NUMERIC (6)     NULL,
    [Score]                        VARCHAR (100)   NULL,
    [Quaulification_Star_Date]     DATETIME        NULL,
    [Quaulification_End_Date]      DATETIME        NULL,
    [Dependant_Name]               VARCHAR (500)   NULL,
    [Dependant_Gender]             CHAR (1)        NULL,
    [Dependant_DOB]                DATETIME        NULL,
    [Dependant_Age]                NUMERIC (18, 1) NULL,
    [Dependant_Relationship]       VARCHAR (500)   NULL,
    [Dependant_Is_Resident]        NUMERIC (1)     NULL,
    [Dependant_Is_Dependant]       NUMERIC (1)     NULL,
    [Pass_Visa_Citizenship]        NUMERIC (18)    NULL,
    [Pass_Visa_No]                 VARCHAR (100)   NULL,
    [Pass_Visa_Issue_Date]         DATETIME        NULL,
    [Pass_Visa_Exp_Date]           DATETIME        NULL,
    [Pass_Visa_Review_Date]        DATETIME        NULL,
    [Pass_Visa_Status]             VARCHAR (20)    NULL,
    [License_ID]                   NUMERIC (18)    NULL,
    [License_Type]                 VARCHAR (100)   NULL,
    [License_IssueDate]            DATETIME        NULL,
    [License_No]                   VARCHAR (100)   NULL,
    [License_ExpDate]              DATETIME        NULL,
    [License_Is_Expired]           NUMERIC (1)     NULL,
    [Image_path]                   VARCHAR (1000)  NULL,
    [Curr_IFSC_Code]               VARCHAR (200)   NULL,
    [Curr_Account_No]              VARCHAR (200)   NULL,
    [Curr_Branch_Name]             VARCHAR (200)   NULL,
    [New_IFSC_Code]                VARCHAR (200)   NULL,
    [New_Account_No]               VARCHAR (200)   NULL,
    [New_Branch_Name]              VARCHAR (200)   NULL,
    [Nominess_Address]             VARCHAR (500)   NULL,
    [Nominess_Share]               NUMERIC (5)     NULL,
    [Nominess_For]                 NUMERIC (5)     NULL,
    [Nominees_Row_ID]              VARCHAR (500)   NULL,
    [Hospital_Name]                VARCHAR (500)   NULL,
    [Hospital_Address]             VARCHAR (500)   NULL,
    [Admit_Date]                   DATETIME        NULL,
    [MediCalim_Approval_Amount]    NUMERIC (18, 2) NULL,
    [Old_Pan_No]                   VARCHAR (200)   NULL,
    [New_Pan_No]                   VARCHAR (200)   NULL,
    [Old_Adhar_No]                 VARCHAR (200)   NULL,
    [New_Adhar_No]                 VARCHAR (200)   NULL,
    [Loan_Skip_Details]            VARCHAR (MAX)   NULL,
    [Loan_Month]                   NUMERIC (5)     NULL,
    [Loan_Year]                    NUMERIC (5)     NULL,
    [Child_Birth_Date]             DATETIME        NULL,
    [Dep_OccupationID]             INT             NULL,
    [Dep_HobbyID]                  NVARCHAR (500)  NULL,
    [Dep_HobbyName]                NVARCHAR (1000) NULL,
    [Dep_DepCompanyName]           NVARCHAR (200)  NULL,
    [Dep_CmpCity]                  NVARCHAR (200)  NULL,
    [Dep_Standard_ID]              INT             NULL,
    [Dep_Shcool_College]           NVARCHAR (200)  NULL,
    [Dep_SchCity]                  NVARCHAR (200)  NULL,
    [Dep_ExtraActivity]            NVARCHAR (500)  NULL,
    [Emp_Fav_Sport_id]             NVARCHAR (500)  NULL,
    [Emp_Fav_Sport_Name]           NVARCHAR (1000) NULL,
    [Emp_Hobby_id]                 NVARCHAR (500)  NULL,
    [Emp_Hobby_Name]               NVARCHAR (1000) NULL,
    [Emp_Fav_Food]                 NVARCHAR (100)  NULL,
    [Emp_Fav_Restro]               NVARCHAR (100)  NULL,
    [Emp_Fav_Trv_Destination]      NVARCHAR (100)  NULL,
    [Emp_Fav_Festival]             NVARCHAR (100)  NULL,
    [Emp_Fav_SportPerson]          NVARCHAR (100)  NULL,
    [Emp_Fav_Singer]               NVARCHAR (100)  NULL,
    [Dep_PancardNo]                NVARCHAR (100)  NULL,
    [Dep_AdharcardNo]              NVARCHAR (100)  NULL,
    [Dep_Height]                   NVARCHAR (10)   NULL,
    [Dep_Weight]                   NVARCHAR (10)   NULL,
    [OtherHobby]                   NVARCHAR (100)  NULL,
    [OtherSports]                  NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_Sport_id]        NVARCHAR (500)  NULL,
    [Curr_Emp_Fav_Sport_Name]      NVARCHAR (1000) NULL,
    [Curr_Emp_Hobby_id]            NVARCHAR (500)  NULL,
    [Curr_Emp_Hobby_Name]          NVARCHAR (1000) NULL,
    [Curr_Emp_Fav_Food]            NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_Restro]          NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_Trv_Destination] NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_Festival]        NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_SportPerson]     NVARCHAR (100)  NULL,
    [Curr_Emp_Fav_Singer]          NVARCHAR (100)  NULL,
    [Curr_Dep_ID]                  INT             NULL,
    [Curr_Dep_Name]                NVARCHAR (100)  NULL,
    [Curr_Dep_Gender]              NVARCHAR (1)    NULL,
    [Curr_Dep_DOB]                 DATETIME        NULL,
    [Curr_Dep_CAGE]                NUMERIC (18, 2) NULL,
    [Curr_Dep_Relationship]        NVARCHAR (100)  NULL,
    [Curr_Dep_ISResi]              INT             NULL,
    [Curr_Dep_ISDep]               INT             NULL,
    [Curr_Dep_ImagePath]           NVARCHAR (1000) NULL,
    [Curr_Dep_PanCard]             NVARCHAR (100)  NULL,
    [Curr_Dep_AdharCard]           NVARCHAR (100)  NULL,
    [Curr_Dep_Height]              NVARCHAR (10)   NULL,
    [Curr_Dep_Weight]              NVARCHAR (10)   NULL,
    [Curr_Dep_OccupationID]        INT             NULL,
    [Curr_Dep_OccupationName]      NVARCHAR (1000) NULL,
    [Curr_Dep_HobbyID]             NVARCHAR (500)  NULL,
    [Curr_Dep_HobbyName]           NVARCHAR (1000) NULL,
    [Curr_Dep_CompanyName]         NVARCHAR (100)  NULL,
    [Curr_Dep_CompanyCity]         NVARCHAR (100)  NULL,
    [Curr_Dep_StandardID]          INT             NULL,
    [Curr_Dep_StandardName]        NVARCHAR (100)  NULL,
    [Curr_Dep_SchCol]              NVARCHAR (100)  NULL,
    [Curr_Dep_SchColCity]          NVARCHAR (100)  NULL,
    [Curr_Dep_ExtraActivity]       NVARCHAR (100)  NULL,
    [Dep_Std_Specialization]       NVARCHAR (300)  NULL,
    [Curr_Dep_Std_Specialization]  NVARCHAR (300)  NULL,
    PRIMARY KEY CLUSTERED ([Request_Apr_ID] ASC) WITH (FILLFACTOR = 80)
);

