CREATE TABLE [dbo].[T0090_EMP_GOAL_DETAILS] (
    [Emp_Goal_ID] NUMERIC (18) NOT NULL,
    [Cmp_ID]      NUMERIC (18) NOT NULL,
    [Goal_ID]     NUMERIC (18) NULL,
    [For_Date]    DATETIME     NOT NULL,
    [Start_Date]  DATETIME     NULL,
    [End_Date]    DATETIME     NULL,
    [Emp_ID]      NUMERIC (18) NULL,
    [Login_ID]    NUMERIC (18) NULL,
    [Goal_Status] CHAR (1)     NOT NULL,
    CONSTRAINT [PK_T0090_EMP_GOAL_DETAILS] PRIMARY KEY CLUSTERED ([Emp_Goal_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_GOAL_DETAILS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_GOAL_DETAILS_T0040_HRMS_Goal_Master] FOREIGN KEY ([Goal_ID]) REFERENCES [dbo].[T0040_HRMS_Goal_Master] ([Goal_id]),
    CONSTRAINT [FK_T0090_EMP_GOAL_DETAILS_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

