CREATE TABLE [dbo].[T0090_EMP_CONTRACT_DETAIL] (
    [Tran_ID]     NUMERIC (18)  NOT NULL,
    [Cmp_ID]      NUMERIC (18)  NOT NULL,
    [Emp_ID]      NUMERIC (18)  NOT NULL,
    [Prj_ID]      NUMERIC (18)  NOT NULL,
    [Start_Date]  DATETIME      NOT NULL,
    [End_Date]    DATETIME      NOT NULL,
    [Is_Renew]    TINYINT       NOT NULL,
    [Is_Reminder] TINYINT       NOT NULL,
    [Comments]    VARCHAR (200) NULL,
    CONSTRAINT [PK_T0090_EMP_CONTRACT_DETAIL] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_CONTRACT_DETAIL_T0010_COMPANY_MASTER1] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_CONTRACT_DETAIL_T0040_PROJECT_MASTER] FOREIGN KEY ([Prj_ID]) REFERENCES [dbo].[T0040_PROJECT_MASTER] ([Prj_ID]),
    CONSTRAINT [FK_T0090_EMP_CONTRACT_DETAIL_T0080_EMP_MASTER1] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

