CREATE TABLE [dbo].[T0090_App_Master] (
    [App_Id]             NUMERIC (18)    NOT NULL,
    [Resume_Id]          NUMERIC (18)    NOT NULL,
    [Cmp_Id]             NUMERIC (18)    NOT NULL,
    [Branch_Id]          NUMERIC (18)    NOT NULL,
    [Grade_Id]           NUMERIC (18)    NULL,
    [Dept_Id]            NUMERIC (18)    NULL,
    [Desig_Id]           NUMERIC (18)    NULL,
    [Type_Id]            NUMERIC (18)    NULL,
    [Shift_Id]           NUMERIC (18)    NULL,
    [Initial]            VARCHAR (50)    NULL,
    [App_First_Name]     VARCHAR (50)    NOT NULL,
    [App_Middle_Name]    VARCHAR (50)    NULL,
    [App_Last_Name]      VARCHAR (50)    NOT NULL,
    [Date_Of_Join]       DATETIME        NULL,
    [Basic_Salary]       NUMERIC (18, 2) NULL,
    [Gender]             CHAR (1)        NULL,
    [Marital_Status]     VARCHAR (20)    NULL,
    [Date_Of_Birth]      DATETIME        NULL,
    [Primary_Email]      VARCHAR (50)    NULL,
    [Other_Email]        VARCHAR (50)    NULL,
    [Present_Street]     VARCHAR (250)   NULL,
    [Present_City]       VARCHAR (50)    NULL,
    [Present_State]      VARCHAR (50)    NULL,
    [Present_Post_Box]   VARCHAR (50)    NULL,
    [Present_Loc]        NUMERIC (18)    NULL,
    [Home_Tel_No]        VARCHAR (50)    NULL,
    [Mobile_No]          VARCHAR (50)    NULL,
    [Permanent_Street]   VARCHAR (250)   NULL,
    [Permanent_City]     VARCHAR (50)    NULL,
    [Permanent_State]    VARCHAR (50)    NULL,
    [Permanent_Post_Box] VARCHAR (50)    NULL,
    [App_Full_Name]      VARCHAR (250)   NULL,
    [Status]             NUMERIC (1)     NULL,
    CONSTRAINT [PK_T0090_App_Master] PRIMARY KEY CLUSTERED ([App_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_App_Master_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_App_Master_T0030_BRANCH_MASTER] FOREIGN KEY ([Branch_Id]) REFERENCES [dbo].[T0030_BRANCH_MASTER] ([Branch_ID]),
    CONSTRAINT [FK_T0090_App_Master_T0030_CATEGORY_MASTER] FOREIGN KEY ([Grade_Id]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID]),
    CONSTRAINT [FK_T0090_App_Master_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_Id]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0090_App_Master_T0040_DESIGNATION_MASTER] FOREIGN KEY ([Desig_Id]) REFERENCES [dbo].[T0040_DESIGNATION_MASTER] ([Desig_ID]),
    CONSTRAINT [FK_T0090_App_Master_T0040_TYPE_MASTER] FOREIGN KEY ([Type_Id]) REFERENCES [dbo].[T0040_TYPE_MASTER] ([Type_ID]),
    CONSTRAINT [FK_T0090_App_Master_T0055_Resume_Master] FOREIGN KEY ([Resume_Id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

