CREATE TABLE [dbo].[T0090_EMP_QUALIFICATION_DETAIL] (
    [Emp_ID]         NUMERIC (18)   NOT NULL,
    [Row_ID]         NUMERIC (18)   NOT NULL,
    [Cmp_ID]         NUMERIC (18)   NOT NULL,
    [Qual_ID]        NUMERIC (18)   NOT NULL,
    [Specialization] VARCHAR (100)  NULL,
    [Year]           NUMERIC (18)   NULL,
    [Score]          VARCHAR (20)   NULL,
    [St_Date]        DATETIME       NULL,
    [End_Date]       DATETIME       NULL,
    [Comments]       VARCHAR (250)  NULL,
    [attach_doc]     NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0090_EMP_QUALIFICATION_DETAIL] PRIMARY KEY CLUSTERED ([Emp_ID] ASC, [Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_QUALIFICATION_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_QUALIFICATION_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0090_EMP_QUALIFICATION_DETAIL_T0090_EMP_QUALIFICATION_DETAIL] FOREIGN KEY ([Qual_ID]) REFERENCES [dbo].[T0040_QUALIFICATION_MASTER] ([Qual_ID])
);

