CREATE TABLE [dbo].[T0091_HRMS_RESUME_HEALTH_DETAIL] (
    [Row_D_ID]   NUMERIC (18)   NOT NULL,
    [cmp_id]     NUMERIC (18)   NULL,
    [Row_ID]     NUMERIC (18)   NULL,
    [Que_Id]     NUMERIC (18)   NULL,
    [Que_Tag]    VARCHAR (1000) NULL,
    [answer_tag] VARCHAR (1000) NULL,
    CONSTRAINT [PK_T0091_HRMS_RESUME_HEALTH_DETAIL] PRIMARY KEY CLUSTERED ([Row_D_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0091_HRMS_RESUME_HEALTH_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0091_HRMS_RESUME_HEALTH_DETAIL_T0090_HRMS_RESUME_HEALTH] FOREIGN KEY ([Row_ID]) REFERENCES [dbo].[T0090_HRMS_RESUME_HEALTH] ([Row_ID])
);

