CREATE TABLE [dbo].[T0090_HRMS_EMP_SKILL_SETTING] (
    [Emp_Skill_ID]        NUMERIC (18)    NOT NULL,
    [Skill_R_ID]          NUMERIC (18)    NOT NULL,
    [Emp_ID]              NUMERIC (18)    NOT NULL,
    [Skill_ID]            NUMERIC (18)    NOT NULL,
    [Skilll_Rate_Given]   NUMERIC (18, 2) NOT NULL,
    [Skill_Actual_Rate]   NUMERIC (18, 2) NULL,
    [Skill_Rate_Employee] NUMERIC (18, 2) NULL,
    [Skill_Rate_Superior] NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_T0090_HRMS_EMP_SKILL_SETTING] PRIMARY KEY CLUSTERED ([Emp_Skill_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_HRMS_EMP_SKILL_SETTING_T0040_SKILL_MASTER] FOREIGN KEY ([Skill_ID]) REFERENCES [dbo].[T0040_SKILL_MASTER] ([Skill_ID]),
    CONSTRAINT [FK_T0090_HRMS_EMP_SKILL_SETTING_T0055_HRMS_EMP_SKILL_DETAILS] FOREIGN KEY ([Skill_R_ID]) REFERENCES [dbo].[T0055_HRMS_EMP_SKILL_DETAILS] ([Skill_R_ID]),
    CONSTRAINT [FK_T0090_HRMS_EMP_SKILL_SETTING_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

