CREATE TABLE [dbo].[T0090_HRMS_RESUME_SKILL] (
    [Row_Id]           NUMERIC (18)  NOT NULL,
    [Resume_Id]        NUMERIC (18)  NOT NULL,
    [Cmp_Id]           NUMERIC (18)  NOT NULL,
    [Skill_Id]         NUMERIC (18)  NOT NULL,
    [Skill_Comments]   VARCHAR (250) NOT NULL,
    [Skill_Experience] VARCHAR (50)  NULL,
    [attach_Documents] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0090_HRMS_RESUME_SKILL] PRIMARY KEY CLUSTERED ([Row_Id] ASC, [Resume_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_HRMS_RESUME_SKILL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_SKILL_T0040_SKILL_MASTER] FOREIGN KEY ([Skill_Id]) REFERENCES [dbo].[T0040_SKILL_MASTER] ([Skill_ID]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_SKILL_T0055_Resume_Master] FOREIGN KEY ([Resume_Id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

