CREATE TABLE [dbo].[T0090_HRMS_RESUME_BANK] (
    [Resume_Bank_Id] NUMERIC (18) NOT NULL,
    [Cmp_Id]         NUMERIC (18) NOT NULL,
    [Resume_Id]      NUMERIC (18) NOT NULL,
    [Bank_Id]        NUMERIC (18) NOT NULL,
    [IFSC_Code]      VARCHAR (50) NULL,
    [Account_No]     VARCHAR (50) NULL,
    [Branch_Name]    VARCHAR (50) NULL,
    CONSTRAINT [PK_T0090_HRMS_RESUME_BANK] PRIMARY KEY CLUSTERED ([Resume_Bank_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_HRMS_RESUME_BANK_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_BANK_T0040_BANK_MASTER] FOREIGN KEY ([Bank_Id]) REFERENCES [dbo].[T0040_BANK_MASTER] ([Bank_ID]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_BANK_T0055_Resume_Master] FOREIGN KEY ([Resume_Id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

