CREATE TABLE [dbo].[T0090_EMP_CHILDRAN_DETAIL] (
    [Emp_ID]             NUMERIC (18)    NOT NULL,
    [Row_ID]             NUMERIC (18)    NOT NULL,
    [Cmp_ID]             NUMERIC (18)    NOT NULL,
    [Name]               VARCHAR (100)   NOT NULL,
    [Gender]             CHAR (1)        NOT NULL,
    [Date_Of_Birth]      DATETIME        NULL,
    [C_Age]              NUMERIC (18, 1) NULL,
    [Relationship]       VARCHAR (50)    NULL,
    [Is_Resi]            NUMERIC (1)     NULL,
    [Is_Dependant]       TINYINT         CONSTRAINT [DF_T0090_EMP_CHILDRAN_DETAIL_Is_Dependant] DEFAULT ((0)) NULL,
    [Image_Path]         VARCHAR (100)   NULL,
    [Pan_Card_No]        VARCHAR (20)    NULL,
    [Adhar_Card_No]      VARCHAR (20)    NULL,
    [Height]             VARCHAR (10)    NULL,
    [Weight]             VARCHAR (10)    NULL,
    [OccupationID]       INT             NULL,
    [HobbyID]            NVARCHAR (500)  NULL,
    [HobbyName]          NVARCHAR (1000) NULL,
    [DepCompanyName]     NVARCHAR (200)  NULL,
    [Standard_ID]        INT             NULL,
    [Shcool_College]     NVARCHAR (200)  NULL,
    [ExtraActivity]      NVARCHAR (500)  NULL,
    [City]               NVARCHAR (200)  NULL,
    [CDTM]               DATETIME        DEFAULT (getdate()) NULL,
    [CmpCity]            NVARCHAR (200)  NULL,
    [Std_Specialization] NVARCHAR (300)  NULL,
    [DepWorkTime]        NVARCHAR (200)  NULL,
    CONSTRAINT [PK_T0090_EMP_CHILDRAN_DETAIL] PRIMARY KEY CLUSTERED ([Emp_ID] ASC, [Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_CHILDRAN_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_CHILDRAN_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

