CREATE TABLE [dbo].[T0090_EMP_LICENSE_DETAIL] (
    [Row_ID]       NUMERIC (18)  NOT NULL,
    [Emp_ID]       NUMERIC (18)  NOT NULL,
    [Cmp_ID]       NUMERIC (18)  NOT NULL,
    [LIC_ID]       NUMERIC (18)  NOT NULL,
    [Lic_St_Date]  DATETIME      NOT NULL,
    [Lic_End_Date] DATETIME      NOT NULL,
    [Lic_Comments] VARCHAR (250) NOT NULL,
    [Lic_For]      VARCHAR (50)  NULL,
    [Lic_Number]   VARCHAR (20)  NULL,
    [Is_Expired]   TINYINT       CONSTRAINT [DF_T0090_EMP_LICENSE_DETAIL_Is_Expired] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0090_EMP_LICENSE_DETAIL_1] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_LICENSE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_LICENSE_DETAIL_T0040_LICENSE_MASTER] FOREIGN KEY ([LIC_ID]) REFERENCES [dbo].[T0040_LICENSE_MASTER] ([Lic_ID]),
    CONSTRAINT [FK_T0090_EMP_LICENSE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

