CREATE TABLE [dbo].[T0090_HRMS_RESUME_EARN_DEDUCTION] (
    [AD_Row_ID]       NUMERIC (18)    NOT NULL,
    [CMP_ID]          NUMERIC (18)    NOT NULL,
    [Resume_id]       NUMERIC (18)    NOT NULL,
    [AD_ID]           NUMERIC (18)    NOT NULL,
    [FOR_DATE]        DATETIME        NULL,
    [E_AD_FLAG]       CHAR (1)        NULL,
    [E_AD_MODE]       VARCHAR (10)    NULL,
    [E_AD_PERCENTAGE] NUMERIC (12, 2) NULL,
    [E_AD_AMOUNT]     NUMERIC (18, 2) NULL,
    [E_AD_MAX_LIMIT]  NUMERIC (18)    NULL,
    [TRAN_ID]         NUMERIC (18)    NULL,
    CONSTRAINT [PK_T0090_HRMS_RESUME_EARN_DEDUCTION] PRIMARY KEY CLUSTERED ([AD_Row_ID] ASC, [Resume_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EARN_DEDUCTION_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EARN_DEDUCTION_T0055_Resume_Master] FOREIGN KEY ([Resume_id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EARN_DEDUCTION_T0060_RESUME_FINAL] FOREIGN KEY ([TRAN_ID]) REFERENCES [dbo].[T0060_RESUME_FINAL] ([Tran_ID]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EARN_DEDUCTION_T0090_HRMS_RESUME_EARN_DEDUCTION] FOREIGN KEY ([AD_Row_ID], [Resume_id]) REFERENCES [dbo].[T0090_HRMS_RESUME_EARN_DEDUCTION] ([AD_Row_ID], [Resume_id])
);


GO
CREATE NONCLUSTERED INDEX [IX_T0090_HRMS_RESUME_EARN_DEDUCTION]
    ON [dbo].[T0090_HRMS_RESUME_EARN_DEDUCTION]([AD_Row_ID] ASC, [Resume_id] ASC) WITH (FILLFACTOR = 80);

