CREATE TABLE [dbo].[t0090_HRMS_RESUME_DOCUMENT] (
    [Doc_Id]          NUMERIC (18)  NOT NULL,
    [Cmp_Id]          NUMERIC (18)  NOT NULL,
    [DocType_Id]      NUMERIC (18)  NOT NULL,
    [Resume_Id]       NUMERIC (18)  NOT NULL,
    [Resume_Final_Id] NUMERIC (18)  NULL,
    [File_Name]       VARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_t0090_HRMS_RESUME_DOCUMENT] PRIMARY KEY CLUSTERED ([Doc_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_t0090_HRMS_RESUME_DOCUMENT_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_t0090_HRMS_RESUME_DOCUMENT_T0040_DOCUMENT_MASTER] FOREIGN KEY ([DocType_Id]) REFERENCES [dbo].[T0040_DOCUMENT_MASTER] ([Doc_ID]),
    CONSTRAINT [FK_t0090_HRMS_RESUME_DOCUMENT_T0055_Resume_Master] FOREIGN KEY ([Resume_Id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id]),
    CONSTRAINT [FK_t0090_HRMS_RESUME_DOCUMENT_T0060_RESUME_FINAL] FOREIGN KEY ([Resume_Final_Id]) REFERENCES [dbo].[T0060_RESUME_FINAL] ([Tran_ID])
);

