CREATE TABLE [dbo].[T0095_HRMS_CANDIDATE_SCHEME] (
    [Candidate_Scheme_Id] NUMERIC (18) NOT NULL,
    [Cmp_Id]              NUMERIC (18) NOT NULL,
    [Resume_ID]           NUMERIC (18) NOT NULL,
    [Scheme_ID]           NUMERIC (18) NOT NULL,
    [Type]                VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_T0095_HRMS_EMP_SCHEME] PRIMARY KEY CLUSTERED ([Candidate_Scheme_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0095_HRMS_EMP_SCHEME_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0095_HRMS_EMP_SCHEME_T0040_Scheme_Master] FOREIGN KEY ([Scheme_ID]) REFERENCES [dbo].[T0040_Scheme_Master] ([Scheme_Id]),
    CONSTRAINT [FK_T0095_HRMS_EMP_SCHEME_T0060_RESUME_FINAL] FOREIGN KEY ([Resume_ID]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id]),
    CONSTRAINT [FK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL_T0040_Scheme_Master] FOREIGN KEY ([Scheme_ID]) REFERENCES [dbo].[T0040_Scheme_Master] ([Scheme_Id]),
    CONSTRAINT [FK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL_T0060_RESUME_FINAL] FOREIGN KEY ([Resume_ID]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

