CREATE TABLE [dbo].[T0090_EMP_IMMIGRATION_DETAIL] (
    [Emp_ID]             NUMERIC (18)   NOT NULL,
    [Row_ID]             NUMERIC (18)   NOT NULL,
    [Cmp_ID]             NUMERIC (18)   NOT NULL,
    [Loc_ID]             NUMERIC (18)   NULL,
    [Imm_Type]           VARCHAR (20)   NOT NULL,
    [Imm_No]             VARCHAR (20)   NOT NULL,
    [Imm_Issue_Date]     DATETIME       NULL,
    [Imm_Issue_Status]   VARCHAR (20)   NOT NULL,
    [Imm_Date_of_Expiry] DATETIME       NULL,
    [Imm_Review_Date]    DATETIME       NULL,
    [Imm_Comments]       VARCHAR (250)  NOT NULL,
    [attach_doc]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0090_EMP_IMMIGRATION_DETAIL] PRIMARY KEY CLUSTERED ([Emp_ID] ASC, [Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_EMP_IMMIGRATION_DETAIL_T0001_LOCATION_MASTER] FOREIGN KEY ([Loc_ID]) REFERENCES [dbo].[T0001_LOCATION_MASTER] ([Loc_ID]),
    CONSTRAINT [FK_T0090_EMP_IMMIGRATION_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_EMP_IMMIGRATION_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

