CREATE TABLE [dbo].[T0090_HRMS_RESUME_EXPERIENCE] (
    [Row_ID]             NUMERIC (18)    NOT NULL,
    [Cmp_ID]             NUMERIC (18)    NOT NULL,
    [Resume_ID]          NUMERIC (18)    NOT NULL,
    [Employer_Name]      VARCHAR (100)   NULL,
    [Desig_Name]         VARCHAR (100)   NULL,
    [St_Date]            DATETIME        NULL,
    [End_Date]           DATETIME        NULL,
    [ExpProof]           VARCHAR (MAX)   NULL,
    [DocumentType]       VARCHAR (100)   NULL,
    [Fromdate]           DATETIME        NULL,
    [Todate]             DATETIME        NULL,
    [GrossSalary]        NUMERIC (18)    NULL,
    [ProfessionalTax]    NUMERIC (18)    NULL,
    [Surcharge]          NUMERIC (18)    NULL,
    [EducationCess]      NUMERIC (18)    NULL,
    [TDS]                NUMERIC (18)    NULL,
    [ITax]               NUMERIC (18)    NULL,
    [FYear]              VARCHAR (50)    NULL,
    [StillContinue]      TINYINT         CONSTRAINT [DF_T0090_HRMS_RESUME_EXPERIENCE_StillContinue] DEFAULT ((0)) NULL,
    [Fresher]            TINYINT         CONSTRAINT [DF_T0090_HRMS_RESUME_EXPERIENCE_Fresher] DEFAULT ((0)) NULL,
    [CTC]                NUMERIC (18, 2) NULL,
    [Manager_Name]       VARCHAR (150)   NULL,
    [Manager_Contact_No] VARCHAR (15)    NULL,
    [Reason_For_Leaving] VARCHAR (500)   NULL,
    CONSTRAINT [PK_T0090_HRMS_RESUME_EXPERIENCE_1] PRIMARY KEY CLUSTERED ([Row_ID] ASC, [Resume_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EXPERIENCE_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0090_HRMS_RESUME_EXPERIENCE_T0055_Resume_Master] FOREIGN KEY ([Resume_ID]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

