CREATE TABLE [dbo].[T0095_EMP_SCHEMA] (
    [Tran_ID]      NUMERIC (18)  NOT NULL,
    [Cmp_ID]       NUMERIC (18)  NOT NULL,
    [Emp_ID]       NUMERIC (18)  NOT NULL,
    [Increment_ID] NUMERIC (18)  NOT NULL,
    [Scheme_ID]    NUMERIC (18)  NOT NULL,
    [Type]         VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_T0095_EMP_SCHEMA] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0095_EMP_SCHEMA_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0095_EMP_SCHEMA_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0095_EMP_SCHEMA_T0095_EMP_SCHEMA] FOREIGN KEY ([Scheme_ID]) REFERENCES [dbo].[T0095_EMP_SCHEMA] ([Tran_ID]),
    CONSTRAINT [FK_T0095_EMP_SCHEMA_T0095_INCREMENT] FOREIGN KEY ([Increment_ID]) REFERENCES [dbo].[T0095_INCREMENT] ([Increment_ID])
);

