CREATE TABLE [dbo].[T0100_INCREMENT_APP_EARN_DEDUCTION] (
    [AD_TRAN_ID]          NUMERIC (18)    NOT NULL,
    [CMP_ID]              NUMERIC (18)    NOT NULL,
    [EMP_ID]              NUMERIC (18)    NOT NULL,
    [AD_ID]               NUMERIC (18)    NOT NULL,
    [App_ID]              NUMERIC (18)    NOT NULL,
    [FOR_DATE]            DATETIME        NOT NULL,
    [E_AD_FLAG]           CHAR (1)        NOT NULL,
    [E_AD_MODE]           VARCHAR (10)    NOT NULL,
    [E_AD_PERCENTAGE]     NUMERIC (18, 5) NOT NULL,
    [E_AD_AMOUNT]         NUMERIC (18, 4) NOT NULL,
    [E_AD_MAX_LIMIT]      NUMERIC (18)    NOT NULL,
    [E_AD_YEARLY_AMOUNT]  NUMERIC (18, 2) CONSTRAINT [DF_T0100_INCREMENT_APP_EARN_DEDUCTION_E_AD_YEARLY_AMOUNT] DEFAULT ((0)) NOT NULL,
    [It_Estimated_Amount] NUMERIC (18, 2) CONSTRAINT [DF_T0100_INCREMENT_APP_EARN_DEDUCTION_It_Estimated_Amount] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0100_INCREMENT_APP_EARN_DEDUCTION] PRIMARY KEY CLUSTERED ([AD_TRAN_ID] ASC)
);

