CREATE TABLE [dbo].[T0100_HRMS_CANDIDATE_SCHEME_LEVEL] (
    [Candidate_Scheme_Id] NUMERIC (18) NOT NULL,
    [Cmp_Id]              NUMERIC (18) NOT NULL,
    [Resume_ID]           NUMERIC (18) NOT NULL,
    [Scheme_ID]           NUMERIC (18) NOT NULL,
    [Type]                VARCHAR (50) NOT NULL,
    [Tran_Id]             NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL] PRIMARY KEY CLUSTERED ([Candidate_Scheme_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL_T0040_Scheme_Master1] FOREIGN KEY ([Scheme_ID]) REFERENCES [dbo].[T0040_Scheme_Master] ([Scheme_Id]),
    CONSTRAINT [FK_T0100_HRMS_CANDIDATE_SCHEME_LEVEL_T0052_ResumeFinal_Approval] FOREIGN KEY ([Tran_Id]) REFERENCES [dbo].[T0052_ResumeFinal_Approval] ([CanApp_Id])
);

