CREATE TABLE [dbo].[T0100_ANUAL_BONUS] (
    [Bonus_Tran_ID]   NUMERIC (18) NOT NULL,
    [Cmp_ID]          NUMERIC (18) NOT NULL,
    [Emp_ID]          NUMERIC (18) NOT NULL,
    [Ad_ID]           NUMERIC (18) NOT NULL,
    [Amount]          NUMERIC (22) NOT NULL,
    [Effective_Month] NUMERIC (18) NOT NULL,
    [Effective_Year]  NUMERIC (18) NOT NULL,
    [Sal_Tran_ID]     NUMERIC (18) NOT NULL,
    [Sys_Date]        DATETIME     NOT NULL,
    CONSTRAINT [PK_T0100_ANUAL_BONUS] PRIMARY KEY CLUSTERED ([Bonus_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_ANUAL_BONUS_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_ANUAL_BONUS_T0050_AD_MASTER] FOREIGN KEY ([Ad_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID]),
    CONSTRAINT [FK_T0100_ANUAL_BONUS_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

