CREATE TABLE [dbo].[T0100_NIGHT_HALT_APPLICATION] (
    [Application_ID] NUMERIC (18)    NOT NULL,
    [Cmp_ID]         NUMERIC (18)    NOT NULL,
    [Emp_ID]         NUMERIC (18)    NOT NULL,
    [S_Emp_ID]       NUMERIC (18)    NULL,
    [From_Date]      DATETIME        NOT NULL,
    [To_Date]        DATETIME        NOT NULL,
    [No_Of_Days]     NUMERIC (18, 2) NOT NULL,
    [Visit_Place]    VARCHAR (MAX)   NULL,
    [Remarks]        VARCHAR (MAX)   NULL,
    [App_Status]     VARCHAR (1)     NULL,
    [Login_ID]       NUMERIC (18)    NOT NULL,
    [System_Date]    DATETIME        NULL,
    CONSTRAINT [PK_T0100_NIGHT_HALT_APPLICATION] PRIMARY KEY CLUSTERED ([Application_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_NIGHT_HALT_APPLICATION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_NIGHT_HALT_APPLICATION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

