CREATE TABLE [dbo].[T0100_IT_DECLARATION] (
    [IT_TRAN_ID]        NUMERIC (18)    NOT NULL,
    [CMP_ID]            NUMERIC (18)    NOT NULL,
    [IT_ID]             NUMERIC (18)    NOT NULL,
    [EMP_ID]            NUMERIC (18)    NOT NULL,
    [FOR_DATE]          DATETIME        NOT NULL,
    [AMOUNT]            NUMERIC (18, 2) NOT NULL,
    [DOC_NAME]          VARCHAR (200)   NOT NULL,
    [LOGIN_ID]          NUMERIC (18)    NULL,
    [SYSTEM_DATE]       DATETIME        NULL,
    [REPEAT_YEARLY]     TINYINT         NULL,
    [AMOUNT_ESS]        NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [IT_Flag]           TINYINT         DEFAULT ((0)) NOT NULL,
    [FINANCIAL_YEAR]    VARCHAR (20)    NULL,
    [Is_Lock]           BIT             CONSTRAINT [DF_T0100_IT_DECLARATION_Is_Lock] DEFAULT ((0)) NOT NULL,
    [Is_Metro_NonMetro] VARCHAR (30)    NULL,
    [IsCompare_Flag]    VARCHAR (50)    NULL,
    CONSTRAINT [PK_T0100_IT_DECLARATION] PRIMARY KEY CLUSTERED ([IT_TRAN_ID] ASC),
    CONSTRAINT [FK_T0100_IT_DECLARATION_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_IT_DECLARATION_T0070_IT_MASTER] FOREIGN KEY ([IT_ID]) REFERENCES [dbo].[T0070_IT_MASTER] ([IT_ID]),
    CONSTRAINT [FK_T0100_IT_DECLARATION_T0080_EMP_MASTER] FOREIGN KEY ([EMP_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_T0100_IT_DECLARATION]
    ON [dbo].[T0100_IT_DECLARATION]([EMP_ID] ASC, [FINANCIAL_YEAR] ASC, [FOR_DATE] ASC);


GO
CREATE STATISTICS [AMOUNT]
    ON [dbo].[T0100_IT_DECLARATION]([AMOUNT]);


GO
CREATE STATISTICS [AMOUNT_ESS]
    ON [dbo].[T0100_IT_DECLARATION]([AMOUNT_ESS]);


GO
CREATE STATISTICS [CMP_ID]
    ON [dbo].[T0100_IT_DECLARATION]([CMP_ID]);


GO
CREATE STATISTICS [DOC_NAME]
    ON [dbo].[T0100_IT_DECLARATION]([DOC_NAME]);


GO
CREATE STATISTICS [FINANCIAL_YEAR]
    ON [dbo].[T0100_IT_DECLARATION]([FINANCIAL_YEAR]);


GO
CREATE STATISTICS [FOR_DATE]
    ON [dbo].[T0100_IT_DECLARATION]([FOR_DATE]);


GO
CREATE STATISTICS [Is_Lock]
    ON [dbo].[T0100_IT_DECLARATION]([Is_Lock]);


GO
CREATE STATISTICS [Is_Metro_NonMetro]
    ON [dbo].[T0100_IT_DECLARATION]([Is_Metro_NonMetro]);


GO
CREATE STATISTICS [IT_Flag]
    ON [dbo].[T0100_IT_DECLARATION]([IT_Flag]);


GO
CREATE STATISTICS [IT_ID]
    ON [dbo].[T0100_IT_DECLARATION]([IT_ID]);


GO
CREATE STATISTICS [LOGIN_ID]
    ON [dbo].[T0100_IT_DECLARATION]([LOGIN_ID]);


GO
CREATE STATISTICS [REPEAT_YEARLY]
    ON [dbo].[T0100_IT_DECLARATION]([REPEAT_YEARLY]);


GO
CREATE STATISTICS [SYSTEM_DATE]
    ON [dbo].[T0100_IT_DECLARATION]([SYSTEM_DATE]);

