CREATE TABLE [dbo].[T0100_WEEKOFF_ROSTER] (
    [Tran_Id]      NUMERIC (18) NOT NULL,
    [Cmp_id]       NUMERIC (18) NOT NULL,
    [Emp_id]       NUMERIC (18) NOT NULL,
    [For_date]     DATETIME     NOT NULL,
    [is_Cancel_WO] TINYINT      CONSTRAINT [DF_T0100_WEEKOFF_ROSTER_is_Cancel_WO] DEFAULT ((0)) NOT NULL,
    [User_ID]      NUMERIC (18) NULL,
    [System_Date]  DATETIME     NULL,
    CONSTRAINT [PK_T0100_WEEKOFF_ROSTER] PRIMARY KEY NONCLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0100_WEEKOFF_ROSTER]
    ON [dbo].[T0100_WEEKOFF_ROSTER]([Emp_id] ASC, [For_date] DESC);


GO
CREATE NONCLUSTERED INDEX [ix_T0100_WEEKOFF_ROSTER_is_Cancel_WO]
    ON [dbo].[T0100_WEEKOFF_ROSTER]([is_Cancel_WO] ASC);

