CREATE TABLE [dbo].[T0100_PROJECT_ALLOCATION] (
    [Row_ID]     NUMERIC (18) NOT NULL,
    [Cmp_ID]     NUMERIC (18) NOT NULL,
    [Prj_ID]     NUMERIC (18) NOT NULL,
    [Emp_ID]     NUMERIC (18) NOT NULL,
    [Eff_date]   DATETIME     NOT NULL,
    [Emp_Active] CHAR (1)     NULL,
    CONSTRAINT [PK_T0100_PROJECT_ALLOCATION] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_PROJECT_ALLOCATION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_PROJECT_ALLOCATION_T0040_PROJECT_MASTER] FOREIGN KEY ([Prj_ID]) REFERENCES [dbo].[T0040_PROJECT_MASTER] ([Prj_ID]),
    CONSTRAINT [FK_T0100_PROJECT_ALLOCATION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

