CREATE TABLE [dbo].[T0100_TRAINING_APPLICATION] (
    [Training_App_ID] NUMERIC (18)  NOT NULL,
    [Training_Title]  VARCHAR (50)  NOT NULL,
    [Training_Desc]   VARCHAR (100) NULL,
    [For_Date]        DATETIME      NOT NULL,
    [Posted_Emp_ID]   NUMERIC (18)  NULL,
    [Skill_ID]        NUMERIC (18)  NOT NULL,
    [App_Status]      VARCHAR (1)   NOT NULL,
    [Cmp_ID]          NUMERIC (18)  NOT NULL,
    [Login_ID]        NUMERIC (18)  NOT NULL,
    [System_Date]     DATETIME      NOT NULL,
    CONSTRAINT [PK_T0100_TRAINING_APPLICATION] PRIMARY KEY CLUSTERED ([Training_App_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_TRAINING_APPLICATION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_TRAINING_APPLICATION_T0040_SKILL_MASTER] FOREIGN KEY ([Skill_ID]) REFERENCES [dbo].[T0040_SKILL_MASTER] ([Skill_ID])
);

