CREATE TABLE [dbo].[T0100_WEEKOFF_ADJ] (
    [W_Tran_ID]           NUMERIC (18)  NOT NULL,
    [Emp_ID]              NUMERIC (18)  NOT NULL,
    [Cmp_ID]              NUMERIC (18)  NOT NULL,
    [For_Date]            DATETIME      NOT NULL,
    [Weekoff_Day]         VARCHAR (100) NOT NULL,
    [Weekoff_Day_Value]   VARCHAR (100) NULL,
    [Alt_W_Name]          VARCHAR (100) NULL,
    [Alt_W_Full_Day_Cont] VARCHAR (250) NULL,
    [Alt_W_Half_Day_Cont] VARCHAR (50)  NULL,
    [Is_P_Comp]           TINYINT       CONSTRAINT [DF_T0100_WEEKOFF_ADJ_Is_P_Comp] DEFAULT ((0)) NULL,
    [IsMakerChecker]      BIT           DEFAULT ((0)) NULL,
    [weekOffOddEven]      VARCHAR (10)  NULL,
    CONSTRAINT [PK_T0100_WEEKOFF_ADJ] PRIMARY KEY CLUSTERED ([W_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_WEEKOFF_ADJ_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_WEEKOFF_ADJ_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [T0100_Weekoff_Adj_New]
    ON [dbo].[T0100_WEEKOFF_ADJ]([Cmp_ID] ASC, [Emp_ID] ASC, [For_Date] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0100_WEEKOFF_ADJ_For_SP_RPT_EMP_IN_OUT_MUSTER_HOME_GET]
    ON [dbo].[T0100_WEEKOFF_ADJ]([For_Date] ASC)
    INCLUDE([Emp_ID]);


GO
CREATE NONCLUSTERED INDEX [IX_T0100_WEEKOFF_ADJ_For_SP_RPT_EMP_IN_OUT_MUSTER_HOME_GET_include]
    ON [dbo].[T0100_WEEKOFF_ADJ]([Emp_ID] ASC, [For_Date] ASC);


GO
CREATE STATISTICS [_dta_stat_2082106458_5_4_2]
    ON [dbo].[T0100_WEEKOFF_ADJ]([Weekoff_Day], [For_Date], [Emp_ID]);


GO
CREATE STATISTICS [_dta_stat_2082106458_4_2]
    ON [dbo].[T0100_WEEKOFF_ADJ]([For_Date], [Emp_ID]);

