CREATE TABLE [dbo].[T0100_EMP_PROBATION_ATTRIBUTE_DETAIL] (
    [Prob_Attr_ID] NUMERIC (18)    NOT NULL,
    [Cmp_ID]       NUMERIC (18)    NOT NULL,
    [Emp_ID]       NUMERIC (18)    NOT NULL,
    [Attr_Rating]  NUMERIC (18, 2) NULL,
    [Attribute_ID] NUMERIC (18)    NOT NULL,
    [Emp_Prob_ID]  NUMERIC (18)    NOT NULL,
    [Final_Review] NUMERIC (18)    NULL,
    [Review_Type]  VARCHAR (15)    NULL,
    CONSTRAINT [PK_T0100_EMP_PROBATION_ATTRIBUTE_DETAIL] PRIMARY KEY CLUSTERED ([Prob_Attr_ID] ASC),
    CONSTRAINT [FK_T0100_EMP_PROBATION_ATTRIBUTE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_EMP_PROBATION_ATTRIBUTE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0100_EMP_PROBATION_ATTRIBUTE_DETAIL_T0095_EMP_PROBATION_MASTER] FOREIGN KEY ([Emp_Prob_ID]) REFERENCES [dbo].[T0095_EMP_PROBATION_MASTER] ([Probation_Evaluation_ID])
);

