CREATE TABLE [dbo].[T0100_EMP_SHIFT_DETAIL] (
    [Shift_Tran_ID] NUMERIC (18) NOT NULL,
    [Emp_ID]        NUMERIC (18) NOT NULL,
    [Cmp_ID]        NUMERIC (18) NOT NULL,
    [Shift_ID]      NUMERIC (18) NOT NULL,
    [For_Date]      DATETIME     NOT NULL,
    [Shift_Type]    NUMERIC (5)  CONSTRAINT [DF_T0100_EMP_SHIFT_DETAIL_Shift_Type] DEFAULT ((0)) NULL,
    [Rotation_ID]   NUMERIC (18) NULL,
    CONSTRAINT [PK_T0100_EMP_SHIFT_DETAIL] PRIMARY KEY CLUSTERED ([Shift_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_EMP_SHIFT_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_EMP_SHIFT_DETAIL_T0040_SHIFT_MASTER] FOREIGN KEY ([Shift_ID]) REFERENCES [dbo].[T0040_SHIFT_MASTER] ([Shift_ID]),
    CONSTRAINT [FK_T0100_EMP_SHIFT_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [T0100_Emp_shift_detail_new]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Cmp_ID] ASC, [Emp_ID] ASC, [Shift_ID] ASC, [For_Date] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0100_EMP_SHIFT_DETAIL_24_1534628510__K2_K5_6]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Emp_ID] ASC, [For_Date] ASC)
    INCLUDE([Shift_Type]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0100_EMP_SHIFT_DETAIL_24_1534628510__K3_K2_K5_4_6]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Cmp_ID] ASC, [Emp_ID] ASC, [For_Date] ASC)
    INCLUDE([Shift_ID], [Shift_Type]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0100_EMP_SHIFT_DETAIL_E_F_C_S]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Emp_ID] ASC, [For_Date] ASC, [Cmp_ID] ASC, [Shift_ID] ASC)
    INCLUDE([Shift_Tran_ID], [Shift_Type]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0100_EMP_SHIFT_DETAIL_For_SP_GET_ATTENDANCEREGU_APPLICATION_RECORDS]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([For_Date] ASC)
    INCLUDE([Emp_ID], [Shift_ID]);


GO
CREATE NONCLUSTERED INDEX [ix_T0100_EMP_SHIFT_DETAIL_Shift_Type]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Shift_Type] ASC)
    INCLUDE([Emp_ID], [Shift_ID], [For_Date]) WITH (FILLFACTOR = 90);


GO
CREATE STATISTICS [IS_T0100_EMP_SHIFT_DETAIL_S_F_C_E]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Shift_ID], [For_Date], [Cmp_ID], [Emp_ID]);


GO
CREATE STATISTICS [IS_T0100_EMP_SHIFT_DETAIL_F_C]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([For_Date], [Cmp_ID]);


GO
CREATE STATISTICS [IS_T0100_EMP_SHIFT_DETAIL_S_E_F]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Shift_ID], [Emp_ID], [For_Date]);


GO
CREATE STATISTICS [_dta_stat_530100929_1_2_3]
    ON [dbo].[T0100_EMP_SHIFT_DETAIL]([Shift_Tran_ID], [Emp_ID], [Cmp_ID]);

