CREATE TABLE [dbo].[T0100_RIMBURSEMENT_DETAIL] (
    [RIMB_TRAN_ID] NUMERIC (18)    NOT NULL,
    [RIMB_ID]      NUMERIC (18)    NOT NULL,
    [CMP_ID]       NUMERIC (18)    NOT NULL,
    [EMP_ID]       NUMERIC (18)    NOT NULL,
    [FOR_DATE]     DATETIME        NOT NULL,
    [RIMB_AMOUNT]  NUMERIC (18, 2) NOT NULL,
    CONSTRAINT [PK_T0100_RIMBURSEMENT_DETAIL] PRIMARY KEY CLUSTERED ([RIMB_TRAN_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_RIMBURSEMENT_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_RIMBURSEMENT_DETAIL_T0055_REIMBURSEMENT] FOREIGN KEY ([RIMB_ID]) REFERENCES [dbo].[T0055_REIMBURSEMENT] ([RIMB_ID]),
    CONSTRAINT [FK_T0100_RIMBURSEMENT_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([EMP_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

