CREATE TABLE [dbo].[T0100_FTP_DETAILS] (
    [FTP_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [CMP_ID]       INT           NULL,
    [FTP_URL]      VARCHAR (100) NULL,
    [FTP_UserName] VARCHAR (100) NULL,
    [FTP_Password] VARCHAR (100) NULL,
    [DOMAIN_NAME]  VARCHAR (50)  NULL,
    [CLIENTCODE]   VARCHAR (50)  NULL,
    [REMARKS]      VARCHAR (250) NULL,
    CONSTRAINT [PK_T0100_FTP_DETAILS] PRIMARY KEY CLUSTERED ([FTP_ID] ASC)
);

