CREATE TABLE [dbo].[T0100_EMpKPI_Master_Level] (
    [Row_Id]    NUMERIC (18)    NOT NULL,
    [Cmp_Id]    NUMERIC (18)    NULL,
    [Tran_Id]   NUMERIC (18)    NULL,
    [SubKPIId]  NUMERIC (18)    NULL,
    [Emp_Id]    NUMERIC (18)    NULL,
    [KPI]       VARCHAR (250)   NULL,
    [Weightage] NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_T0100_EMpKPI_Master_Level] PRIMARY KEY CLUSTERED ([Row_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_EMpKPI_Master_Level_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_EMpKPI_Master_Level_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0100_EMpKPI_Master_Level_T0090_EmpKPI_Approval] FOREIGN KEY ([Tran_Id]) REFERENCES [dbo].[T0090_EmpKPI_Approval] ([Tran_Id]),
    CONSTRAINT [FK_T0100_EMpKPI_Master_Level_T0090_SubKPI_Master_Level] FOREIGN KEY ([SubKPIId]) REFERENCES [dbo].[T0080_SubKPI_Master] ([SubKPIId])
);

