CREATE TABLE [dbo].[T0100_HRMS_RESUME_EARN_DEDUCTION_LEVEL] (
    [AD_Row_ID]       NUMERIC (18)    NOT NULL,
    [CMP_ID]          NUMERIC (18)    NOT NULL,
    [Resume_id]       NUMERIC (18)    NOT NULL,
    [AD_ID]           NUMERIC (18)    NOT NULL,
    [FOR_DATE]        DATETIME        NULL,
    [E_AD_FLAG]       CHAR (1)        NULL,
    [E_AD_MODE]       VARCHAR (10)    NULL,
    [E_AD_PERCENTAGE] NUMERIC (12, 2) NULL,
    [E_AD_AMOUNT]     NUMERIC (18, 2) NULL,
    [E_AD_MAX_LIMIT]  NUMERIC (18)    NULL,
    [TRAN_ID]         NUMERIC (18)    NULL,
    CONSTRAINT [PK_T0100_HRMS_RESUME_EARN_DEDUCTION_LEVEL_1] PRIMARY KEY CLUSTERED ([AD_Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_HRMS_RESUME_EARN_DEDUCTION_LEVEL_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_HRMS_RESUME_EARN_DEDUCTION_LEVEL_T0052_ResumeFinal_Approval] FOREIGN KEY ([TRAN_ID]) REFERENCES [dbo].[T0052_ResumeFinal_Approval] ([CanApp_Id]),
    CONSTRAINT [FK_T0100_HRMS_RESUME_EARN_DEDUCTION_LEVEL_T0060_RESUME_FINAL] FOREIGN KEY ([Resume_id]) REFERENCES [dbo].[T0055_Resume_Master] ([Resume_Id])
);

