CREATE TABLE [dbo].[T0100_EMP_SKILL_ATTR_ASSIGN] (
    [Tran_ID]         NUMERIC (18)    NOT NULL,
    [Cmp_ID]          NUMERIC (18)    NOT NULL,
    [Effect_Date]     DATETIME        NOT NULL,
    [Desig_Id]        NUMERIC (18)    NULL,
    [Skill_Weightage] NUMERIC (18, 2) CONSTRAINT [DF_T0100_EMP_SKILL_ATTR_ASSIGN_Skill_Weightage] DEFAULT ((0)) NOT NULL,
    [Attr_Weightage]  NUMERIC (18, 2) CONSTRAINT [DF_T0100_EMP_SKILL_ATTR_ASSIGN_Attr_Weightage] DEFAULT ((0)) NOT NULL,
    [Type]            NUMERIC (18)    DEFAULT ((2)) NOT NULL,
    [Dept_Id]         NUMERIC (18)    NULL,
    CONSTRAINT [PK_T0100_EMP_SKILL_ATTR_ASSIGN] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_EMP_SKILL_ATTR_ASSIGN_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

