CREATE TABLE [dbo].[T0100_HRMS_TRAINING_APPLICATION] (
    [Training_App_ID] NUMERIC (18)  NOT NULL,
    [Training_id]     NUMERIC (18)  NULL,
    [Training_Desc]   VARCHAR (150) NULL,
    [For_Date]        DATETIME      NULL,
    [Posted_Emp_ID]   NUMERIC (18)  NULL,
    [Skill_ID]        NUMERIC (18)  NULL,
    [App_Status]      INT           NULL,
    [Cmp_ID]          NUMERIC (18)  NOT NULL,
    [Login_ID]        NUMERIC (18)  NULL,
    [System_Date]     DATETIME      NULL,
    [Training_Plan]   TINYINT       CONSTRAINT [DF_T0100_HRMS_TRAINING_APPLICATION_Training_Plan] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0100_HRMS_TRAINING_APPLICATION] PRIMARY KEY CLUSTERED ([Training_App_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_HRMS_TRAINING_APPLICATION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_HRMS_TRAINING_APPLICATION_T0040_Hrms_Training_master] FOREIGN KEY ([Training_id]) REFERENCES [dbo].[T0040_Hrms_Training_master] ([Training_id]),
    CONSTRAINT [FK_T0100_HRMS_TRAINING_APPLICATION_T0040_SKILL_MASTER] FOREIGN KEY ([Skill_ID]) REFERENCES [dbo].[T0040_SKILL_MASTER] ([Skill_ID]),
    CONSTRAINT [FK_T0100_HRMS_TRAINING_APPLICATION_T0080_EMP_MASTER] FOREIGN KEY ([Posted_Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

