CREATE TABLE [dbo].[T0100_EMP_PERFORMANCE_DETAIL] (
    [PER_DETAIL_ID]   NUMERIC (18)    NOT NULL,
    [PER_INC_TRAN_ID] NUMERIC (18)    NOT NULL,
    [CMP_ID]          NUMERIC (18)    NOT NULL,
    [EMP_ID]          NUMERIC (18)    NOT NULL,
    [FOR_DATE]        DATETIME        NOT NULL,
    [PERCENTAGE]      NUMERIC (18, 2) NOT NULL,
    [OUT_OF_PER]      NUMERIC (18, 2) NOT NULL,
    [LOGIN_ID]        NUMERIC (18)    NOT NULL,
    [SYS_DATE]        DATETIME        NOT NULL,
    CONSTRAINT [PK_T0100_EMP_PERFORMANCE_DETAIL] PRIMARY KEY CLUSTERED ([PER_DETAIL_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0100_EMP_PERFORMANCE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([CMP_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0100_EMP_PERFORMANCE_DETAIL_T0040_PERFORMANCE_INCENTIVE_MASTER] FOREIGN KEY ([PER_INC_TRAN_ID]) REFERENCES [dbo].[T0040_PERFORMANCE_INCENTIVE_MASTER] ([PER_INC_TRAN_ID]),
    CONSTRAINT [FK_T0100_EMP_PERFORMANCE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([EMP_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

