CREATE TABLE [dbo].[T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL] (
    [Travel_Apr_Other_Detail_ID] NUMERIC (18)    NOT NULL,
    [Tran_ID]                    NUMERIC (18)    NOT NULL,
    [Cmp_ID]                     NUMERIC (18)    NOT NULL,
    [Travel_Mode_ID]             NUMERIC (18)    NOT NULL,
    [For_date]                   DATETIME        NOT NULL,
    [Description]                VARCHAR (MAX)   NULL,
    [Amount]                     NUMERIC (18, 2) NULL,
    [Self_Pay]                   TINYINT         CONSTRAINT [DF_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_Self_Pay] DEFAULT ((0)) NOT NULL,
    [modify_Date]                DATETIME        NULL,
    [To_Date]                    DATETIME        NULL,
    [Curr_ID]                    NUMERIC (18)    DEFAULT (NULL) NULL,
    [SGST]                       NUMERIC (18, 2) CONSTRAINT [DF_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_SGST] DEFAULT ((0)) NOT NULL,
    [CGST]                       NUMERIC (18, 2) CONSTRAINT [DF_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_CGST] DEFAULT ((0)) NOT NULL,
    [IGST]                       NUMERIC (18, 2) CONSTRAINT [DF_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_IGST] DEFAULT ((0)) NOT NULL,
    [GST_No]                     NVARCHAR (50)   NULL,
    [GST_Company_Name]           NVARCHAR (250)  NULL,
    CONSTRAINT [PK_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL] PRIMARY KEY CLUSTERED ([Travel_Apr_Other_Detail_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_TRAVEL_APPROVAL_OTHER_DETAIL_LEVEL_T0115_TRAVEL_LEVEL_APPROVAL] FOREIGN KEY ([Tran_ID]) REFERENCES [dbo].[T0115_TRAVEL_LEVEL_APPROVAL] ([Tran_Id])
);

