CREATE TABLE [dbo].[T0115_AttendanceRegu_Level_Approval] (
    [Tran_Id]             NUMERIC (18)  NOT NULL,
    [Emp_ID]              NUMERIC (18)  NOT NULL,
    [Cmp_ID]              NUMERIC (18)  NOT NULL,
    [IO_Tran_ID]          NUMERIC (18)  NOT NULL,
    [For_Date]            DATETIME      NOT NULL,
    [In_Time]             DATETIME      NULL,
    [Out_Time]            DATETIME      NULL,
    [Duration]            VARCHAR (10)  NULL,
    [Reason]              VARCHAR (100) NULL,
    [Skip_Count]          NUMERIC (18)  NULL,
    [Late_Calc_Not_App]   NUMERIC (1)   CONSTRAINT [DF_T0115_AttendanceRegu_Level_Approval_Late_Calc_Not_App] DEFAULT ((0)) NULL,
    [Chk_By_Superior]     TINYINT       CONSTRAINT [DF_T0115_AttendanceRegu_Level_Approval_Chk_By_Superior] DEFAULT ((0)) NULL,
    [Half_Full_day]       VARCHAR (50)  NULL,
    [Is_Cancel_Late_In]   TINYINT       CONSTRAINT [DF_T0115_AttendanceRegu_Level_Approval_Is_Cancel_Late_In] DEFAULT ((0)) NULL,
    [Is_Cancel_Early_Out] TINYINT       CONSTRAINT [DF_T0115_AttendanceRegu_Level_Approval_Is_Cancel_Early_Out] DEFAULT ((0)) NULL,
    [S_Emp_Id]            NUMERIC (18)  NULL,
    [S_Comment]           VARCHAR (50)  NULL,
    [Rpt_Level]           TINYINT       NOT NULL,
    [System_Date]         DATETIME      NOT NULL,
    CONSTRAINT [PK_T0115_AttendanceRegu_Level_Approval] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_AttendanceRegu_Level_Approval_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_AttendanceRegu_Level_Approval_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

