CREATE TABLE [dbo].[T0115_Loan_Level_Approval] (
    [Tran_Id]                     NUMERIC (18)    NOT NULL,
    [Loan_Apr_Id]                 NUMERIC (18)    NOT NULL,
    [Cmp_Id]                      NUMERIC (18)    NOT NULL,
    [Loan_App_Id]                 NUMERIC (18)    NULL,
    [Emp_Id]                      NUMERIC (18)    NOT NULL,
    [Loan_Id]                     NUMERIC (18)    NOT NULL,
    [Loan_Apr_date]               DATETIME        NOT NULL,
    [Loan_Apr_Code]               VARCHAR (20)    NOT NULL,
    [Loan_Apr_Amount]             NUMERIC (18)    NOT NULL,
    [Loan_Apr_No_of_Installment]  NUMERIC (18)    NOT NULL,
    [Loan_Apr_Installment_Amount] NUMERIC (22, 2) NOT NULL,
    [Loan_Apr_Intrest_Type]       VARCHAR (20)    NOT NULL,
    [Loan_Apr_Intrest_Per]        NUMERIC (18, 4) NOT NULL,
    [Loan_Apr_Intrest_Amount]     NUMERIC (22, 2) NOT NULL,
    [Loan_Apr_Deduct_From_Sal]    NUMERIC (18)    NOT NULL,
    [Loan_Apr_Pending_Amount]     NUMERIC (22, 2) NOT NULL,
    [Loan_Apr_By]                 VARCHAR (100)   NOT NULL,
    [Loan_Apr_Payment_Date]       DATETIME        NULL,
    [Loan_Apr_Payment_Type]       VARCHAR (20)    NOT NULL,
    [Bank_ID]                     NUMERIC (18)    NULL,
    [Loan_Apr_Cheque_No]          VARCHAR (10)    NOT NULL,
    [Loan_Apr_Status]             CHAR (1)        NULL,
    [Loan_Number]                 VARCHAR (50)    NULL,
    [Deduction_Type]              VARCHAR (20)    NULL,
    [S_Emp_Id]                    NUMERIC (18)    NOT NULL,
    [Rpt_Level]                   TINYINT         NOT NULL,
    [System_Date]                 DATETIME        NOT NULL,
    [Loan_Approval_Remarks]       VARCHAR (250)   NULL,
    [No_of_Inst_Loan_Amt]         NUMERIC (18)    DEFAULT ((0)) NOT NULL,
    [Total_Loan_Int_Amount]       NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Loan_Int_Installment_Amount] NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0115_Loan_Level_Approval] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_Loan_Level_Approval_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_Loan_Level_Approval_T0040_LOAN_MASTER] FOREIGN KEY ([Loan_Id]) REFERENCES [dbo].[T0040_LOAN_MASTER] ([Loan_ID]),
    CONSTRAINT [FK_T0115_Loan_Level_Approval_T0080_EMP_MASTER] FOREIGN KEY ([Emp_Id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0115_Loan_Level_Approval_T0100_LOAN_APPLICATION] FOREIGN KEY ([Loan_App_Id]) REFERENCES [dbo].[T0100_LOAN_APPLICATION] ([Loan_App_ID])
);

