CREATE TABLE [dbo].[T0110_GRATUITY_DETAIL] (
    [Gr_D_ID]          NUMERIC (18) NOT NULL,
    [GR_ID]            NUMERIC (18) NOT NULL,
    [Cmp_ID]           NUMERIC (18) NOT NULL,
    [For_Date]         DATETIME     NOT NULL,
    [Gr_D_Calc_Amount] NUMERIC (18) NOT NULL,
    [Gr_D_Amount]      NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0110_GRATUITY_DETAIL] PRIMARY KEY CLUSTERED ([Gr_D_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0110_GRATUITY_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0110_GRATUITY_DETAIL_T0100_GRATUITY] FOREIGN KEY ([GR_ID]) REFERENCES [dbo].[T0100_GRATUITY] ([Gr_ID])
);

