CREATE TABLE [dbo].[T0115_TRAVEL_APPROVAL_ADVDETAIL_LEVEL] (
    [Row_Adv_ID]      NUMERIC (18)    NOT NULL,
    [Tran_Id]         NUMERIC (18)    NOT NULL,
    [Cmp_ID]          NUMERIC (18)    NOT NULL,
    [Expence_Type]    VARCHAR (100)   NOT NULL,
    [Amount]          NUMERIC (18, 2) NOT NULL,
    [Adv_Detail_Desc] NVARCHAR (250)  NULL,
    [Travel_App_ID]   NUMERIC (18)    NOT NULL,
    [Curr_ID]         NUMERIC (18)    DEFAULT (NULL) NULL,
    [Amount_dollar]   NUMERIC (18, 2) DEFAULT (NULL) NULL,
    CONSTRAINT [PK_T0115_TRAVEL_APPROVAL_ADVDETAIL_LEVEL] PRIMARY KEY CLUSTERED ([Row_Adv_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_TRAVEL_APPROVAL_ADVDETAIL_LEVEL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_TRAVEL_APPROVAL_ADVDETAIL_LEVEL_T0115_TRAVEL_LEVEL_APPROVAL] FOREIGN KEY ([Tran_Id]) REFERENCES [dbo].[T0115_TRAVEL_LEVEL_APPROVAL] ([Tran_Id])
);

