CREATE TABLE [dbo].[T0115_Travel_Settlement_Level_Expense] (
    [int_Exp_Id]           NUMERIC (18)    NOT NULL,
    [int_Id]               NUMERIC (18)    NOT NULL,
    [Travel_Settlement_Id] NUMERIC (18)    NOT NULL,
    [Travel_Approval_Id]   NUMERIC (18)    NOT NULL,
    [Emp_ID]               NUMERIC (18)    NOT NULL,
    [Cmp_ID]               NUMERIC (18)    NOT NULL,
    [for_Date]             DATETIME        NOT NULL,
    [Amount]               NUMERIC (18, 2) NULL,
    [Approved_Amount]      NUMERIC (18, 2) NULL,
    [Expense_Type_ID]      NUMERIC (18)    NULL,
    [Comments]             VARCHAR (MAX)   NULL,
    [Missing]              TINYINT         NULL,
    [from_time]            VARCHAR (30)    NULL,
    [To_time]              VARCHAR (30)    NULL,
    [Duration]             NUMERIC (18, 2) NOT NULL,
    [Appr_From_Time]       VARCHAR (25)    NULL,
    [Appr_To_Time]         VARCHAR (25)    NULL,
    [Appr_Duration]        NUMERIC (18, 2) NOT NULL,
    [Rpt_Level]            NUMERIC (18)    NULL,
    [Status]               NVARCHAR (10)   NOT NULL,
    [manager_emp_id]       NUMERIC (18)    DEFAULT (NULL) NULL,
    [Limit_Amount]         NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [Curr_ID]              NUMERIC (18)    DEFAULT (NULL) NULL,
    [Curr_Amount]          NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [Exchange_Rate]        NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [ExpKm]                NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [SelfPay]              TINYINT         DEFAULT ((0)) NOT NULL,
    [No_of_Days]           NUMERIC (18)    DEFAULT ((0)) NOT NULL,
    [GuestName]            VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_T0015_Travel_Settlement_Level_Expense] PRIMARY KEY CLUSTERED ([int_Exp_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0015_Travel_Settlement_Level_Expense_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0015_Travel_Settlement_Level_Expense_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

