CREATE TABLE [dbo].[T0110_TRAINING_APPLICATION_DETAIL] (
    [Tran_App_Detail_ID] NUMERIC (18) NOT NULL,
    [Training_App_ID]    NUMERIC (18) NULL,
    [Emp_ID]             NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0110_TRAINING_APPLICATION_DETAIL] PRIMARY KEY CLUSTERED ([Tran_App_Detail_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0110_TRAINING_APPLICATION_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0110_TRAINING_APPLICATION_DETAIL_T0100_TRAINING_APPLICATION] FOREIGN KEY ([Training_App_ID]) REFERENCES [dbo].[T0100_TRAINING_APPLICATION] ([Training_App_ID])
);

