CREATE TABLE [dbo].[T0110_SKILL_WEIGHTAGE] (
    [Row_ID]    NUMERIC (18)    NOT NULL,
    [Cmp_ID]    NUMERIC (18)    NOT NULL,
    [Skill_ID]  NUMERIC (18)    NOT NULL,
    [Tran_Id]   NUMERIC (18)    NOT NULL,
    [Weightage] NUMERIC (18, 2) CONSTRAINT [DF_T0110_SKILL_WEIGHTAGE_Weightage] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0110_SKILL_WEIGHTAGE] PRIMARY KEY CLUSTERED ([Row_ID] ASC),
    CONSTRAINT [FK_T0110_SKILL_WEIGHTAGE_T0110_SKILL_WEIGHTAGE] FOREIGN KEY ([Tran_Id]) REFERENCES [dbo].[T0100_EMP_SKILL_ATTR_ASSIGN] ([Tran_ID])
);

