CREATE TABLE [dbo].[T0110_EMP_LEFT_JOIN_TRAN] (
    [LJ_Tran_ID] NUMERIC (18) NOT NULL,
    [Emp_ID]     NUMERIC (18) NOT NULL,
    [Cmp_ID]     NUMERIC (18) NOT NULL,
    [Join_Date]  DATETIME     NOT NULL,
    [Left_Date]  DATETIME     NULL,
    [Left_ID]    NUMERIC (18) NULL,
    CONSTRAINT [PK_T0110_EMP_LEFT_JOIN_TRAN] PRIMARY KEY CLUSTERED ([LJ_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0110_EMP_LEFT_JOIN_TRAN_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0110_EMP_LEFT_JOIN_TRAN_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0110_EMP_LEFT_JOIN_TRAN_T0100_LEFT_EMP] FOREIGN KEY ([Left_ID]) REFERENCES [dbo].[T0100_LEFT_EMP] ([Left_ID])
);


GO
CREATE NONCLUSTERED INDEX [T0110_Emp_Left_Join_Tran_Index]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Cmp_ID] ASC, [Emp_ID] ASC, [Join_Date] ASC, [Left_Date] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0110_EMP_LEFT_JOIN_TRAN_For_SP_RPT_EMP_IN_OUT_MUSTER_HOME_GET]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Emp_ID] ASC)
    INCLUDE([Cmp_ID], [Join_Date], [Left_Date]);


GO
CREATE STATISTICS [_dta_stat_770101784_5_3_2]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Left_Date], [Cmp_ID], [Emp_ID]);


GO
CREATE STATISTICS [_dta_stat_770101784_2_4]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Emp_ID], [Join_Date]);


GO
CREATE STATISTICS [IS_T0110_EMP_LEFT_JOIN_TRAN_Left_Date_Cmp]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Left_Date], [Cmp_ID]);


GO
CREATE STATISTICS [IS_T0110_EMP_LEFT_JOIN_TRAN_Join_Cmp]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Join_Date], [Cmp_ID]);


GO
CREATE STATISTICS [IS_T0110_EMP_LEFT_JOIN_TRAN_Emp_ID_Left_Date_Cmp_ID]
    ON [dbo].[T0110_EMP_LEFT_JOIN_TRAN]([Emp_ID], [Left_Date], [Cmp_ID]);

