CREATE TABLE [dbo].[T0115_RC_LTA_Travel_Detail_Level] (
    [Tran_ID]          NUMERIC (18)    NOT NULL,
    [RC_LevelTran_ID]  NUMERIC (18)    NOT NULL,
    [RC_Travel_ID]     NUMERIC (18)    NOT NULL,
    [Cmp_ID]           NUMERIC (18)    NOT NULL,
    [Travel_Date]      DATETIME        NOT NULL,
    [From_Place]       VARCHAR (255)   NULL,
    [To_Place]         VARCHAR (255)   NULL,
    [Mode_Of_Travel]   VARCHAR (255)   NULL,
    [Fare]             NUMERIC (18, 2) NULL,
    [File_Name]        VARCHAR (255)   NULL,
    [Tax_Exception]    TINYINT         NULL,
    [Block_Period]     VARCHAR (255)   NULL,
    [Abroad_Travel]    TINYINT         NULL,
    [Remarks]          VARCHAR (MAX)   NULL,
    [Current_Year]     INT             NULL,
    [From_Date]        DATETIME        NULL,
    [To_Date]          DATETIME        NULL,
    [Amount]           NUMERIC (18, 2) NULL,
    [Bill_No]          VARCHAR (50)    NULL,
    [Bill_Date]        DATETIME        NULL,
    [Apr_Amount]       NUMERIC (18, 2) NOT NULL,
    [CreatedBy]        NUMERIC (18)    NOT NULL,
    [CreatedDate]      DATETIME        NOT NULL,
    [AD_Exp_Master_ID] NUMERIC (18)    NULL,
    CONSTRAINT [PK_T0115_RC_LTA_Travel_Detail_Level] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_RC_LTA_Travel_Detail_Level_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_RC_LTA_Travel_Detail_Level_T0050_AD_Expense_Limit_Master] FOREIGN KEY ([AD_Exp_Master_ID]) REFERENCES [dbo].[T0050_AD_Expense_Limit_Master] ([AD_Exp_Master_ID]),
    CONSTRAINT [FK_T0115_RC_LTA_Travel_Detail_Level_T0115_RC_Level_Approval] FOREIGN KEY ([RC_LevelTran_ID]) REFERENCES [dbo].[T0115_RC_Level_Approval] ([Tran_ID])
);

