CREATE TABLE [dbo].[T0115_EMP_PROBATION_SKILL_DETAIL_LEVEL] (
    [Row_ID]        NUMERIC (18)    NOT NULL,
    [Tran_ID]       NUMERIC (18)    NOT NULL,
    [Emp_Id]        NUMERIC (18)    NOT NULL,
    [Cmp_Id]        NUMERIC (18)    NOT NULL,
    [Skill_ID]      NUMERIC (18)    NOT NULL,
    [Skill_Rating]  NUMERIC (18, 2) NOT NULL,
    [Final_Review]  NUMERIC (18)    NULL,
    [Review_Type]   VARCHAR (15)    NULL,
    [Strengths]     VARCHAR (5000)  DEFAULT ('') NOT NULL,
    [Other_Factors] VARCHAR (5000)  DEFAULT ('') NOT NULL,
    [Remarks]       VARCHAR (5000)  DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_T0115_EMP_PROBATION_SKILL_DETAIL_LEVEL] PRIMARY KEY CLUSTERED ([Row_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_EMP_PROBATION_SKILL_DETAIL_LEVEL_T0115_EMP_PROBATION_MASTER_LEVEL] FOREIGN KEY ([Tran_ID]) REFERENCES [dbo].[T0115_EMP_PROBATION_MASTER_LEVEL] ([Tran_Id])
);

