CREATE TABLE [dbo].[T0115_CLAIM_LEVEL_APPROVAL] (
    [Tran_ID]                  NUMERIC (18)    NOT NULL,
    [Claim_App_ID]             NUMERIC (18)    NULL,
    [Cmp_Id]                   NUMERIC (18)    NOT NULL,
    [Emp_ID]                   NUMERIC (18)    NOT NULL,
    [S_Emp_ID]                 NUMERIC (18)    NULL,
    [Approval_Date]            DATETIME        NOT NULL,
    [Claim_Apr_Status]         VARCHAR (50)    NULL,
    [Claim_Apr_Comments]       NVARCHAR (MAX)  NULL,
    [Login_ID]                 NUMERIC (18)    NOT NULL,
    [System_Date]              DATETIME        NOT NULL,
    [Rpt_Level]                NUMERIC (18)    NOT NULL,
    [Claim_Apr_Amount]         NUMERIC (18, 2) NULL,
    [Claim_Apr_Pending_Amnt]   NUMERIC (18, 2) NULL,
    [Claim_App_Amount]         NUMERIC (18, 2) NOT NULL,
    [Curr_ID]                  NUMERIC (18)    NULL,
    [Curr_Rate]                NUMERIC (18, 2) NULL,
    [Claim_App_Total_Amount]   NUMERIC (18, 2) NOT NULL,
    [Attached_doc_File]        NVARCHAR (MAX)  NULL,
    [Claim_ID]                 NUMERIC (18)    NULL,
    [Deduct_From_salary]       NUMERIC (18)    NULL,
    [for_date]                 DATETIME        NULL,
    [claim_App_purpose]        VARCHAR (500)   DEFAULT (NULL) NULL,
    [Approved_Petrol_Km]       NUMERIC (18, 2) CONSTRAINT [DF_T0115_CLAIM_LEVEL_APPROVAL_Approved_Petrol_Km] DEFAULT ((0)) NOT NULL,
    [Is_Mobile_Entry]          TINYINT         NULL,
    [Claim_Model]              VARCHAR (500)   NULL,
    [Claim_IMEI]               VARCHAR (500)   NULL,
    [Claim_NoofPerson]         VARCHAR (500)   NULL,
    [Claim_DateOfPurchase]     SMALLDATETIME   NULL,
    [Claim_BookName]           VARCHAR (200)   NULL,
    [Claim_Subject]            VARCHAR (200)   NULL,
    [Claim_ActualPrice]        FLOAT (53)      NULL,
    [Claim_PriceAfterDiscount] FLOAT (53)      NULL,
    [Claim_FamilyMember]       VARCHAR (200)   NULL,
    [Claim_Relation]           VARCHAR (100)   NULL,
    [Claim_Age]                FLOAT (53)      NULL,
    [Claim_Limit]              FLOAT (53)      NULL,
    [Claim_FamilyMeberId]      INT             NULL,
    [Claim_UnitName]           VARCHAR (100)   NULL,
    [Claim_UnitFlag]           INT             NULL,
    [Claim_ConversionRate]     FLOAT (53)      NULL,
    [Claim_Comments]           NVARCHAR (500)  NULL,
    [LabelString]              VARCHAR (500)   NULL,
    CONSTRAINT [PK_T0115_CLAIM_LEVEL_APPROVAL] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0115_CLAIM_LEVEL_APPROVAL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0115_CLAIM_LEVEL_APPROVAL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0115_CLAIM_LEVEL_APPROVAL_T0100_CLAIM_APPLICATION] FOREIGN KEY ([Claim_App_ID]) REFERENCES [dbo].[T0100_CLAIM_APPLICATION] ([Claim_App_ID])
);

