CREATE TABLE [dbo].[T0115_EMP_PROBATION_MASTER_LEVEL] (
    [Tran_Id]                    NUMERIC (18)   NOT NULL,
    [Emp_id]                     NUMERIC (18)   NOT NULL,
    [Cmp_id]                     NUMERIC (18)   NOT NULL,
    [Probation_Status]           NUMERIC (18)   NOT NULL,
    [Evaluation_Date]            DATETIME       NOT NULL,
    [Extend_Period]              NUMERIC (18)   NULL,
    [Old_Probation_Period]       NUMERIC (18)   NOT NULL,
    [Old_Probation_EndDate]      DATETIME       NULL,
    [New_Probation_EndDate]      DATETIME       NULL,
    [Major_Strength]             VARCHAR (1500) NULL,
    [Major_Weakness]             VARCHAR (1500) NULL,
    [Appraiser_Remarks]          NVARCHAR (500) NULL,
    [Appraisal_Reviewer_Remarks] NVARCHAR (500) NULL,
    [Flag]                       VARCHAR (15)   NULL,
    [Training_ID]                NVARCHAR (MAX) NULL,
    [S_Emp_ID]                   NUMERIC (18)   NOT NULL,
    [Status]                     CHAR (1)       NOT NULL,
    [Rpt_Level]                  NUMERIC (18)   NOT NULL,
    [System_Datetime]            DATETIME       NOT NULL,
    [Approval_Period_Type]       VARCHAR (50)   NULL,
    [Emp_Type_Id]                NUMERIC (18)   NULL,
    [Probation_Evaluation_ID]    NUMERIC (18)   CONSTRAINT [DF_T0115_EMP_PROBATION_MASTER_LEVEL_Probation_Evaluation_ID_1] DEFAULT ((0)) NOT NULL,
    [Final_Review]               NUMERIC (18)   NULL,
    [Review_Type]                VARCHAR (15)   NULL,
    [Is_Self_Rating]             TINYINT        DEFAULT ((0)) NOT NULL,
    [Attach_Docs]                VARCHAR (MAX)  DEFAULT ('') NOT NULL,
    [Confirmation_date]          DATETIME       NULL,
    CONSTRAINT [PK_T0115_EMP_PROBATION_MASTER_LEVEL] PRIMARY KEY CLUSTERED ([Tran_Id] ASC) WITH (FILLFACTOR = 80)
);

