CREATE TABLE [dbo].[T0120_GRADEWISE_ALLOWANCE] (
    [Tran_ID]          NUMERIC (18)    NOT NULL,
    [cmp_id]           NUMERIC (18)    NOT NULL,
    [Ad_ID]            NUMERIC (18)    NOT NULL,
    [Grd_ID]           NUMERIC (18)    NULL,
    [Sys_Date]         DATETIME        NOT NULL,
    [AD_Level]         NUMERIC (18)    NULL,
    [AD_MODE]          VARCHAR (10)    NULL,
    [AD_PERCENTAGE]    NUMERIC (18, 5) NULL,
    [AD_AMOUNT]        NUMERIC (18, 4) NULL,
    [AD_MAX_LIMIT]     NUMERIC (18, 2) NULL,
    [AD_NON_TAX_LIMIT] NUMERIC (18, 2) NULL,
    CONSTRAINT [PK_T0120_GRADEWISE_ALLOWANCE] PRIMARY KEY CLUSTERED ([Tran_ID] ASC),
    CONSTRAINT [FK_T0120_GRADEWISE_ALLOWANCE_T0010_COMPANY_MASTER] FOREIGN KEY ([cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0120_GRADEWISE_ALLOWANCE_T0040_GRADE_MASTER] FOREIGN KEY ([Grd_ID]) REFERENCES [dbo].[T0040_GRADE_MASTER] ([Grd_ID]),
    CONSTRAINT [FK_T0120_GRADEWISE_ALLOWANCE_T0050_AD_MASTER] FOREIGN KEY ([Ad_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_T0120_GRADEWISE_ALLOWANCE_SP_IT_TAX_PREPARATION]
    ON [dbo].[T0120_GRADEWISE_ALLOWANCE]([Grd_ID] ASC) WITH (FILLFACTOR = 90);

