CREATE TABLE [dbo].[T0120_HRMS_TRAINING_APPROVAL] (
    [Training_Apr_ID]       NUMERIC (18)     NOT NULL,
    [Training_App_ID]       NUMERIC (18)     NOT NULL,
    [Login_ID]              NUMERIC (18)     NULL,
    [Training_id]           NUMERIC (18)     NULL,
    [Training_Date]         DATETIME         NULL,
    [Place]                 VARCHAR (500)    NULL,
    [Faculty]               VARCHAR (200)    NULL,
    [Training_Pro_ID]       NUMERIC (18)     NULL,
    [Description]           VARCHAR (500)    NULL,
    [Training_Cost]         NUMERIC (18, 2)  NULL,
    [Training_Cost_per_Emp] NUMERIC (18, 2)  NULL,
    [Apr_Status]            INT              NULL,
    [Cmp_ID]                NUMERIC (18)     NOT NULL,
    [Training_End_Date]     DATETIME         NULL,
    [Training_Type]         NUMERIC (18)     NULL,
    [Training_Leave_Type]   INT              NULL,
    [no_of_day]             INT              NULL,
    [Impact_Salary]         INT              NULL,
    [emp_feedback]          INT              NULL,
    [Sup_feedback]          INT              NULL,
    [Comments]              TEXT             NULL,
    [branch_id]             VARCHAR (MAX)    NULL,
    [dept_id]               VARCHAR (MAX)    NULL,
    [desig_id]              VARCHAR (MAX)    NULL,
    [grd_id]                VARCHAR (MAX)    NULL,
    [Training_Code]         VARCHAR (50)     NULL,
    [Training_FromTime]     VARCHAR (50)     NULL,
    [Training_ToTime]       VARCHAR (50)     NULL,
    [Lock]                  TINYINT          NULL,
    [Bond_Month]            INT              CONSTRAINT [DF_T0120_HRMS_TRAINING_APPROVAL_Bond_Month] DEFAULT ((0)) NOT NULL,
    [Attachment]            VARCHAR (MAX)    NULL,
    [Manager_FeedbackDays]  INT              NULL,
    [PublishTraining]       TINYINT          CONSTRAINT [DF_T0120_HRMS_TRAINING_APPROVAL_PublishTraining] DEFAULT ((0)) NULL,
    [VideoURL]              NVARCHAR (MAX)   NULL,
    [latitude]              NUMERIC (18, 14) CONSTRAINT [DF_T0120_HRMS_TRAINING_APPROVAL_latitude] DEFAULT ((0)) NOT NULL,
    [longitude]             NUMERIC (18, 14) CONSTRAINT [DF_T0120_HRMS_TRAINING_APPROVAL_longitude] DEFAULT ((0)) NOT NULL,
    [category_id]           VARCHAR (MAX)    DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_T0120_HRMS_TRAINING_APPROVAL] PRIMARY KEY CLUSTERED ([Training_Apr_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0120_HRMS_TRAINING_APPROVAL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0120_HRMS_TRAINING_APPROVAL_T0040_Hrms_Training_master] FOREIGN KEY ([Training_id]) REFERENCES [dbo].[T0040_Hrms_Training_master] ([Training_id]),
    CONSTRAINT [FK_T0120_HRMS_TRAINING_APPROVAL_T0050_HRMS_Training_Provider_master] FOREIGN KEY ([Training_Pro_ID]) REFERENCES [dbo].[T0050_HRMS_Training_Provider_master] ([Training_Pro_ID])
);

