CREATE TABLE [dbo].[T0120_CLAIM_APPROVAL] (
    [Claim_Apr_ID]              NUMERIC (18)    NOT NULL,
    [Cmp_ID]                    NUMERIC (18)    NOT NULL,
    [Claim_App_ID]              NUMERIC (18)    NULL,
    [Emp_ID]                    NUMERIC (18)    NOT NULL,
    [Claim_ID]                  NUMERIC (18)    CONSTRAINT [DF_T0120_CLAIM_APPROVAL_Claim_ID] DEFAULT (NULL) NULL,
    [Claim_Apr_Date]            DATETIME        NOT NULL,
    [Claim_Apr_Code]            VARCHAR (20)    NOT NULL,
    [Claim_Apr_Amount]          NUMERIC (18, 3) NOT NULL,
    [Claim_Apr_Comments]        VARCHAR (250)   NOT NULL,
    [Claim_Apr_By]              VARCHAR (100)   NOT NULL,
    [Claim_Apr_Deduct_From_Sal] NUMERIC (18)    CONSTRAINT [DF_T0120_CLAIM_APPROVAL_Claim_Apr_Deduct_From_Sal] DEFAULT ((0)) NULL,
    [Claim_Apr_Pending_Amount]  NUMERIC (18, 3) CONSTRAINT [DF_T0120_CLAIM_APPROVAL_Claim_Apr_Pending_Amount] DEFAULT ((0)) NULL,
    [Claim_apr_Status]          CHAR (1)        NULL,
    [Claim_App_Date]            DATETIME        NULL,
    [Claim_App_Amount]          NUMERIC (18, 3) NULL,
    [Curr_ID]                   NUMERIC (18)    NULL,
    [Curr_Rate]                 NUMERIC (18, 3) NULL,
    [Purpose]                   NVARCHAR (250)  NULL,
    [Claim_App_Total_Amount]    NUMERIC (18, 3) NULL,
    [S_Emp_ID]                  NUMERIC (18)    CONSTRAINT [DF__T0120_CLA__S_Emp__20C83BDC] DEFAULT (NULL) NULL,
    [Petrol_KM]                 NUMERIC (18, 2) CONSTRAINT [DF_T0120_CLAIM_APPROVAL_Petrol_KM] DEFAULT ((0)) NOT NULL,
    [Is_Mobile_Entry]           TINYINT         NULL,
    CONSTRAINT [PK_T0120_CLAIM_APPROVAL] PRIMARY KEY CLUSTERED ([Claim_Apr_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0120_CLAIM_APPROVAL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0120_CLAIM_APPROVAL_T0040_CLAIM_MASTER] FOREIGN KEY ([Claim_ID]) REFERENCES [dbo].[T0040_CLAIM_MASTER] ([Claim_ID]),
    CONSTRAINT [FK_T0120_CLAIM_APPROVAL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0120_CLAIM_APPROVAL_T0100_CLAIM_APPLICATION] FOREIGN KEY ([Claim_App_ID]) REFERENCES [dbo].[T0100_CLAIM_APPLICATION] ([Claim_App_ID])
);

