CREATE TABLE [dbo].[T0130_HRMS_TRAINING_ALERT] (
    [Tran_alert_ID]     NUMERIC (18)  NOT NULL,
    [Training_Apr_ID]   NUMERIC (18)  NOT NULL,
    [Dept_ID]           NUMERIC (18)  NULL,
    [Emp_id]            NUMERIC (18)  NULL,
    [Comments]          VARCHAR (500) NULL,
    [alerts_Start_Days] NUMERIC (18)  NULL,
    [alerts_Days]       NUMERIC (18)  NULL,
    [cmp_id]            NUMERIC (18)  NOT NULL,
    CONSTRAINT [PK_T0130_HRMS_TRAINING_ALERT] PRIMARY KEY CLUSTERED ([Tran_alert_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_ALERT_T0010_COMPANY_MASTER] FOREIGN KEY ([cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_ALERT_T0040_DEPARTMENT_MASTER] FOREIGN KEY ([Dept_ID]) REFERENCES [dbo].[T0040_DEPARTMENT_MASTER] ([Dept_Id]),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_ALERT_T0080_EMP_MASTER] FOREIGN KEY ([Emp_id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

