CREATE TABLE [dbo].[T0130_HRMS_TRAINING_EMPLOYEE_DETAIL] (
    [Tran_emp_Detail_ID] NUMERIC (18) NOT NULL,
    [Training_App_ID]    NUMERIC (18) NULL,
    [Training_Apr_ID]    NUMERIC (18) NULL,
    [Emp_ID]             NUMERIC (18) NULL,
    [Emp_tran_status]    INT          NULL,
    [cmp_id]             NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0130_HRMS_TRAINING_EMPLOYEE_DETAIL] PRIMARY KEY CLUSTERED ([Tran_emp_Detail_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_EMPLOYEE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_EMPLOYEE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_EMPLOYEE_DETAIL_T0100_HRMS_TRAINING_APPLICATION] FOREIGN KEY ([Training_App_ID]) REFERENCES [dbo].[T0100_HRMS_TRAINING_APPLICATION] ([Training_App_ID]),
    CONSTRAINT [FK_T0130_HRMS_TRAINING_EMPLOYEE_DETAIL_T0120_HRMS_TRAINING_APPROVAL] FOREIGN KEY ([Training_Apr_ID]) REFERENCES [dbo].[T0120_HRMS_TRAINING_APPROVAL] ([Training_Apr_ID])
);

