CREATE TABLE [dbo].[T0130_Asset_Approval_Det] (
    [Asset_ApprDet_ID]         NUMERIC (18)    NOT NULL,
    [Asset_Approval_ID]        NUMERIC (18)    NULL,
    [Cmp_ID]                   NUMERIC (18)    NOT NULL,
    [Asset_ID]                 NUMERIC (18)    NOT NULL,
    [Brand_Id]                 NUMERIC (18)    NOT NULL,
    [Model_Name]               VARCHAR (50)    NULL,
    [Serial_No]                VARCHAR (50)    NOT NULL,
    [Purchase_date]            DATETIME        NOT NULL,
    [LoginId]                  NUMERIC (18)    NOT NULL,
    [System_date]              DATETIME        NOT NULL,
    [AssetM_ID]                NUMERIC (18)    NULL,
    [Asset_Code]               VARCHAR (50)    NULL,
    [Asset_Status]             VARCHAR (2)     NULL,
    [Return_Date]              DATETIME        NULL,
    [Application_Type]         NUMERIC (18)    NULL,
    [Allocation_Date]          DATETIME        NULL,
    [Return_asset_approval_id] NUMERIC (18)    NULL,
    [Approval_status]          CHAR (1)        NULL,
    [Installment_date]         DATETIME        NULL,
    [Installment_Amount]       NUMERIC (18, 2) NULL,
    [Issue_amount]             NUMERIC (18, 2) NULL,
    [Sal_Tran_Id]              NUMERIC (18)    NULL,
    [Deduction_type]           VARCHAR (15)    NULL,
    [Transfer_Id]              NUMERIC (18)    NULL,
    CONSTRAINT [PK_T0130_Asset_Approval_Det] PRIMARY KEY CLUSTERED ([Asset_ApprDet_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0130_Asset_Approval_Det_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0130_Asset_Approval_Det_T0040_Asset_Details] FOREIGN KEY ([AssetM_ID]) REFERENCES [dbo].[T0040_Asset_Details] ([AssetM_ID]),
    CONSTRAINT [FK_T0130_Asset_Approval_Det_T0120_Asset_Approval] FOREIGN KEY ([Asset_Approval_ID]) REFERENCES [dbo].[T0120_Asset_Approval] ([Asset_Approval_ID])
);

