CREATE TABLE [dbo].[T0130_TRAVEL_Help_Desk] (
    [Tran_id]            NUMERIC (18)   NOT NULL,
    [Travel_Approval_ID] NUMERIC (18)   NOT NULL,
    [Cmp_ID]             NUMERIC (18)   NOT NULL,
    [Emp_ID]             NUMERIC (18)   NOT NULL,
    [File_Name]          NVARCHAR (MAX) NULL,
    [Remarks]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0130_TRAVEL_Help_Desk] PRIMARY KEY CLUSTERED ([Tran_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0130_TRAVEL_Help_Desk_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0130_TRAVEL_Help_Desk_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0130_TRAVEL_Help_Desk_T0120_TRAVEL_APPROVAL] FOREIGN KEY ([Travel_Approval_ID]) REFERENCES [dbo].[T0120_TRAVEL_APPROVAL] ([Travel_Approval_ID])
);

