CREATE TABLE [dbo].[T0130_TRAVEL_APPROVAL_DETAIL] (
    [Travel_Approval_Detail_ID] NUMERIC (18)    NOT NULL,
    [Travel_Approval_ID]        NUMERIC (18)    NOT NULL,
    [Cmp_ID]                    NUMERIC (18)    NOT NULL,
    [Place_Of_Visit]            VARCHAR (100)   NOT NULL,
    [Travel_Purpose]            VARCHAR (200)   NOT NULL,
    [Instruct_Emp_ID]           NUMERIC (18)    NULL,
    [Travel_Mode_ID]            NUMERIC (18)    NOT NULL,
    [From_Date]                 DATETIME        NOT NULL,
    [Period]                    NUMERIC (18, 2) NOT NULL,
    [To_Date]                   DATETIME        NOT NULL,
    [Remarks]                   NVARCHAR (500)  NULL,
    [Leave_Approval_ID]         NUMERIC (18)    NOT NULL,
    [Leave_ID]                  NUMERIC (18)    NOT NULL,
    [State_ID]                  NUMERIC (18)    NULL,
    [City_ID]                   NUMERIC (18)    NULL,
    [Loc_ID]                    NUMERIC (18)    DEFAULT (NULL) NULL,
    [Project_ID]                NUMERIC (18)    DEFAULT (NULL) NULL,
    [Half_Leave_Date]           DATETIME        NULL,
    [LeaveType]                 VARCHAR (50)    NULL,
    [Night_Day]                 NUMERIC (18)    CONSTRAINT [DF_T0130_TRAVEL_APPROVAL_DETAIL_Night_Day] DEFAULT ((0)) NOT NULL,
    [Reason_ID]                 NUMERIC (18)    NULL,
    [From_State_id]             INT             NULL,
    [From_City_id]              INT             NULL,
    CONSTRAINT [PK_T0130_TRAVEL_APPROVAL_DETAIL] PRIMARY KEY CLUSTERED ([Travel_Approval_Detail_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0130_TRAVEL_APPROVAL_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0130_TRAVEL_APPROVAL_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Instruct_Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0130_TRAVEL_APPROVAL_DETAIL_T0120_TRAVEL_APPROVAL] FOREIGN KEY ([Travel_Approval_ID]) REFERENCES [dbo].[T0120_TRAVEL_APPROVAL] ([Travel_Approval_ID])
);

