CREATE TABLE [dbo].[T0140_BOND_TRANSACTION] (
    [Bond_Tran_ID] NUMERIC (18)    NOT NULL,
    [Cmp_ID]       NUMERIC (18)    NOT NULL,
    [Bond_ID]      NUMERIC (18)    NOT NULL,
    [Emp_ID]       NUMERIC (18)    NOT NULL,
    [For_Date]     DATETIME        NOT NULL,
    [Bond_Opening] NUMERIC (22, 2) NOT NULL,
    [Bond_Issue]   NUMERIC (22, 2) NOT NULL,
    [Bond_Return]  NUMERIC (22, 2) NOT NULL,
    [Bond_Closing] NUMERIC (22, 2) NOT NULL,
    CONSTRAINT [PK_T0140_BOND_TRANSACTION] PRIMARY KEY CLUSTERED ([Bond_Tran_ID] ASC),
    CONSTRAINT [FK_T0140_BOND_TRANSACTION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0140_BOND_TRANSACTION_T0040_BOND_MASTER] FOREIGN KEY ([Bond_ID]) REFERENCES [dbo].[T0040_BOND_MASTER] ([Bond_ID]),
    CONSTRAINT [FK_T0140_BOND_TRANSACTION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

