CREATE TABLE [dbo].[T0140_CLAIM_TRANSACTION] (
    [Claim_Tran_ID]  NUMERIC (18)    NOT NULL,
    [Cmp_ID]         NUMERIC (18)    NOT NULL,
    [Claim_ID]       NUMERIC (18)    NOT NULL,
    [Emp_ID]         NUMERIC (18)    NOT NULL,
    [For_Date]       DATETIME        NOT NULL,
    [Claim_Opening]  NUMERIC (18, 3) NOT NULL,
    [Claim_Issue]    NUMERIC (18, 3) NOT NULL,
    [Claim_Return]   NUMERIC (18, 3) NOT NULL,
    [Claim_Closing]  NUMERIC (18, 3) NOT NULL,
    [Salary_Tran_ID] INT             NULL,
    CONSTRAINT [PK_T0140_CLAIM_TRANSACTION] PRIMARY KEY CLUSTERED ([Claim_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0140_CLAIM_TRANSACTION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0140_CLAIM_TRANSACTION_T0040_CLAIM_MASTER] FOREIGN KEY ([Claim_ID]) REFERENCES [dbo].[T0040_CLAIM_MASTER] ([Claim_ID]),
    CONSTRAINT [FK_T0140_CLAIM_TRANSACTION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

