CREATE TABLE [dbo].[T0140_ADVANCE_TRANSACTION] (
    [Adv_Tran_ID] NUMERIC (18) NOT NULL,
    [Cmp_ID]      NUMERIC (18) NOT NULL,
    [Emp_ID]      NUMERIC (18) NOT NULL,
    [For_Date]    DATETIME     NOT NULL,
    [Adv_Opening] NUMERIC (18) NOT NULL,
    [Adv_Issue]   NUMERIC (18) NOT NULL,
    [Adv_Return]  NUMERIC (18) NOT NULL,
    [Adv_Closing] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_T0140_ADVANCE_TRANSACTION] PRIMARY KEY CLUSTERED ([Adv_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0140_ADVANCE_TRANSACTION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0140_ADVANCE_TRANSACTION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0140_ADVANCE_TRANSACTION_24_1253579504__K3_K4_K2_1_5_6_7_8]
    ON [dbo].[T0140_ADVANCE_TRANSACTION]([Emp_ID] ASC, [For_Date] ASC, [Cmp_ID] ASC)
    INCLUDE([Adv_Tran_ID], [Adv_Opening], [Adv_Issue], [Adv_Return], [Adv_Closing]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0140_ADVANCE_TRANSACTION_24_1253579504__K2_K3_K4_8]
    ON [dbo].[T0140_ADVANCE_TRANSACTION]([Cmp_ID] ASC, [Emp_ID] ASC, [For_Date] ASC)
    INCLUDE([Adv_Closing]) WITH (FILLFACTOR = 80);


GO
CREATE STATISTICS [_dta_stat_1253579504_4_3_2]
    ON [dbo].[T0140_ADVANCE_TRANSACTION]([For_Date], [Emp_ID], [Cmp_ID]);


GO
CREATE STATISTICS [_dta_stat_1253579504_2_4]
    ON [dbo].[T0140_ADVANCE_TRANSACTION]([Cmp_ID], [For_Date]);

