CREATE TABLE [dbo].[T0140_EMP_GPF_TRANSACTION] (
    [CMP_ID]      NUMERIC (18)    NOT NULL,
    [TRAN_ID]     NUMERIC (18)    NOT NULL,
    [EMP_ID]      NUMERIC (18)    NOT NULL,
    [SAL_TRAN_ID] NUMERIC (18)    NULL,
    [FOR_DATE]    DATETIME        NOT NULL,
    [GPF_OPENING] NUMERIC (18, 4) NULL,
    [GPF_CREDIT]  NUMERIC (18, 4) NULL,
    [GPF_DEBIT]   NUMERIC (18, 4) NULL,
    [GPF_CLOSING] NUMERIC (18, 4) NULL,
    [GPF_POSTING] NUMERIC (18, 4) NULL,
    [SYSTEM_DATE] DATETIME        NULL,
    CONSTRAINT [PK_T0140_EMP_GPF_BALANCE] PRIMARY KEY NONCLUSTERED ([TRAN_ID] ASC) WITH (FILLFACTOR = 80)
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_T0140_EMP_GPF_BALANCE_Emp_ID_For_Date_Tran_ID]
    ON [dbo].[T0140_EMP_GPF_TRANSACTION]([EMP_ID] ASC, [FOR_DATE] ASC, [TRAN_ID] ASC) WITH (FILLFACTOR = 80);

