CREATE PROCEDURE SP_Mobile_HRMS_WebService_Get_State 
	@Cmp_ID numeric (18,0)   
	,@Country_ID numeric (18,0)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	
	IF @Country_ID = 0
		BEGIN
			SELECT State_ID, State_Name FROM T0020_STATE_MASTER WITH (NOLOCK) WHERE Cmp_ID = @Cmp_ID ORDER BY State_Name ASC
		END
	ELSE
		BEGIN
			SELECT State_ID, State_Name FROM T0020_STATE_MASTER WITH (NOLOCK) WHERE Loc_ID = @Country_ID AND Cmp_ID = @Cmp_ID ORDER BY State_Name ASC
		END
END
