
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_Mobile_Leave_Master]
	@Emp_ID numeric(18,0),
	@Cmp_ID	numeric(18,0)
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

DECLARE @SettingValue int
DECLARE @BranchID numeric(18,0)
DECLARE @GradeID numeric(18,0)

SELECT @SettingValue = Setting_Value FROM T0040_Setting WITH (NOLOCK) WHERE Cmp_ID = @Cmp_ID AND setting_Name = 'Branch wise Leave'

SELECT @BranchID = BRANCH_ID,@GradeID =I.GRD_ID 
FROM T0095_INCREMENT I WITH (NOLOCK)
INNER JOIN 
(
	SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID 
	FROM T0095_INCREMENT I WITH (NOLOCK)
	INNER JOIN
	(
		SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID 
		FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @Cmp_ID AND Emp_ID =@Emp_ID
		GROUP BY EMP_ID
	)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = 	I.EMP_ID
	WHERE CMP_ID =  @Cmp_ID AND I.Emp_ID =@Emp_ID
	GROUP BY I.EMP_ID	
)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID

IF @SettingValue = 1
	BEGIN
		EXEC GET_Leave_Details @Cmp_ID = @Cmp_ID,@Grd_ID = @GradeID,@Emp_ID =@Emp_ID,@Branch_ID = @BranchID,@Leave_Type=''
	END
ELSE
	BEGIN
		SELECT Leave_ID,Leave_Name 
		FROM V0040_LEAVE_DETAILS 
		WHERE (1=(CASE ISNULL(leave_Status,0) WHEN 0 THEN (CASE WHEN ISNULL(InActive_Effective_Date,GETDATE())>=GETDATE() THEN 1 ELSE 0 END ) ELSE  1 END )) AND Grd_ID =@GradeID ORDER BY Leave_Name
	END

