
---18/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_RPT_GRADE_MASTER]
	 @Cmp_ID	 numeric
	,@Grd_ID   numeric
as
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

select * from T0040_GRADE_MASTER WITH (NOLOCK)
where Cmp_ID = @Cmp_ID
and (@Grd_ID =0 or Grd_ID = @Grd_ID)

