



---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[Sp_recruitment_process]
	 @START_DATE	DATETIME
	,@END_DATE		DATETIME 
	,@EMP_ID		NUMERIC(18,0)
	,@CMP_ID		NUMERIC(18,0) 
	,@BRANCH_ID	NUMERIC(18,0) = 0
	,@EMP NVARCHAR(MAX)
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
 
 
	IF @START_DATE = ''
	 SET @START_DATE=NULL
	IF @END_DATE = ''
	 SET @END_DATE=NULL
	IF @BRANCH_ID =0
	 SET @BRANCH_ID=NULL
	 
	IF ISNULL(@START_DATE,'') <> '' AND ISNULL(@END_DATE,'') <> ''
	  BEGIN
		 SELECT APPROVAL_STATUS FROM V0130_LEAVE_APPROVAL_DETAILS WHERE CMP_ID=@CMP_ID AND EMP_ID = ISNULL(@EMP_ID,0) 
						AND ((@START_DATE >= FROM_DATE AND @START_DATE <= TO_DATE) OR 
							(@END_DATE >= FROM_DATE AND 	@END_DATE <= TO_DATE) OR 
							(FROM_DATE >= @START_DATE AND FROM_DATE <= @END_DATE) OR
							(TO_DATE >= @START_DATE AND TO_DATE <= @END_DATE))
							
	 END
	ELSE IF ISNULL(@START_DATE,'') <> '' AND ISNULL(@END_DATE,'') = ''
		BEGIN
			SELECT APPROVAL_STATUS 
			FROM V0130_LEAVE_APPROVAL_DETAILS 
			WHERE CMP_ID=@CMP_ID AND EMP_ID = ISNULL(@EMP_ID,0) 
						 AND ((@START_DATE >= FROM_DATE AND @START_DATE <= TO_DATE) OR
						(FROM_DATE >= @START_DATE) OR (FROM_DATE <= @END_DATE)) 
		END
	ELSE IF ISNULL(@START_DATE,'') = '' AND ISNULL(@END_DATE,'') <> ''
		BEGIN
			SELECT '' as APPROVAL_STATUS 
		END
		
	 CREATE TABLE #EMP_CONS
	 (
		EMP_ID NUMERIC(18,0)
	 )
	 IF @EMP<> ''
		INSERT INTO #EMP_CONS(EMP_ID) SELECT CAST(DATA  AS NUMERIC) FROM DBO.SPLIT (@EMP,',')  
	 
	SELECT ALPHA_EMP_CODE + '-' + EMP_FULL_NAME AS EMP_FULL_NAME_NEW ,EM.EMP_ID FROM T0080_EMP_MASTER EM WITH (NOLOCK)
	 LEFT OUTER JOIN #EMP_CONS EC ON  EM.EMP_ID = EC.EMP_ID
	 INNER JOIN
	 (
	 	SELECT MAX(EMP_ID)AS EMP_ID,EMP_SUPERIOR FROM T0080_EMP_MASTER EM WITH (NOLOCK) WHERE CMP_ID =@CMP_ID
										GROUP BY EM.EMP_SUPERIOR
	 )S_QRY ON S_QRY.EMP_SUPERIOR = EM.EMP_ID
	 INNER JOIN
		(
						SELECT I.EMP_ID,I.BRANCH_ID,I.DESIG_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
						(  SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
							(
								SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE,EMP_ID 
								FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID	GROUP BY EMP_ID
							)IN_QRY ON IN_QRY.EMP_ID = I.EMP_ID AND IN_QRY.INCREMENT_EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE
							GROUP BY I.EMP_ID
						) QRY ON QRY.EMP_ID =I.EMP_ID AND QRY.INCREMENT_ID = I.INCREMENT_ID
		)INC ON INC.EMP_ID = EM.EMP_ID and ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
	 WHERE EMP_LEFT='N' AND EM.CMP_ID=@CMP_ID AND ISNULL(EC.EMP_ID,0) = 0
	 UNION
	 SELECT ALPHA_EMP_CODE + '-' + EMP_FULL_NAME AS EMP_FULL_NAME_NEW ,EM.EMP_ID FROM T0080_EMP_MASTER EM WITH (NOLOCK)
	 LEFT OUTER JOIN #EMP_CONS EC ON  EM.EMP_ID = EC.EMP_ID
	 INNER JOIN
		(
						SELECT I.EMP_ID,I.BRANCH_ID,I.DESIG_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
						(  SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
							(
								SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE,EMP_ID 
								FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID	GROUP BY EMP_ID
							)IN_QRY ON IN_QRY.EMP_ID = I.EMP_ID AND IN_QRY.INCREMENT_EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE
							GROUP BY I.EMP_ID
						) QRY ON QRY.EMP_ID =I.EMP_ID AND QRY.INCREMENT_ID = I.INCREMENT_ID
		)INC ON INC.EMP_ID = EM.EMP_ID and ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
	 INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.DESIG_ID = INC.DESIG_ID 
	 WHERE EMP_LEFT='N' AND EM.CMP_ID=@CMP_ID AND ISNULL(EC.EMP_ID,0) = 0
	AND (DM.DEF_ID=1 OR DM.IS_MAIN=1)
	 ORDER BY EMP_FULL_NAME_NEW
		 
--	Commented by gadriwala muslim 07112016 - Not Properly Written & slow process code. -   	
/*	declare @emp_cons table
	(emp_id  numeric(18,0))
	
	if @emp<> ''
		insert into @emp_cons(emp_id) select cast(data  as numeric) from dbo.Split (@emp,',')  

	select emp_full_name_new,emp_id from v0080_employee_master 
	where emp_id 
	not in
	(
	 select emp_id from @emp_cons
	) 
	and emp_left='N' and cmp_id=@cmp_id and 
	 (
		emp_id in ( 
						select emp_superior from v0080_employee_master 
					    where emp_superior in (
												select emp_id from v0080_employee_master 
												where emp_left='N' and branch_id=isnull(@branch_id,branch_id) and cmp_id=@cmp_id
											  )
				   ) 
		or 
		desig_id in 
				  (
					select desig_id from t0040_designation_master where def_id=1 or is_main=1
				  ) 
	 
	 ) order by emp_code asc;*/

	RETURN




