
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_RPT_LAST_ABSENTISM_REPORT]
 @Cmp_ID			numeric
,@From_Date			datetime
,@To_Date			datetime
,@Branch_ID			varchar(Max)=''
,@Cat_ID			varchar(Max)=''
,@Grd_ID			varchar(Max)=''
,@Type_ID			varchar(Max)=''
,@Dept_ID			varchar(Max)=''
,@Desig_ID			varchar(Max)=''
,@Segment_Id		varchar(Max)=''
,@Vertical_Id		varchar(Max)=''	
,@SubVertical_Id	varchar(Max)='' 
,@SubBranch_Id		varchar(Max)=''	
,@DAYS				NUMERIC(5,0) = 1
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	
	
	 IF OBJECT_ID('tempdb..#EMP_CONS') IS NOT NULL 
         BEGIN
               DROP TABLE #EMP_CONS
         END
	
	CREATE TABLE #EMP_CONS 
	(      
		EMP_ID NUMERIC ,     
		BRANCH_ID NUMERIC,
		INCREMENT_ID NUMERIC
	)	
	Exec SP_RPT_FILL_EMP_CONS_MULTIDROPDOWN @Cmp_ID,@From_Date,@To_Date,@Branch_ID,@Cat_ID,@Grd_ID,@Type_ID,@Dept_ID,@Desig_ID,0,'',0,0,'',@Vertical_Id,@SubVertical_Id,'',0,0,0,'0',0,0


		SELECT '="' + EM.ALPHA_EMP_CODE + '"' AS ALPHA_EMP_CODE , EM.EMP_FULL_NAME ,REPLACE(CONVERT(VARCHAR , DATE_OF_JOIN , 106) , ' ' , '-') AS DATE_OF_JOIN , BM.BRANCH_NAME AS BRANCH
		,DM.DESIG_NAME AS DESIGNATION ,GM.GRD_NAME AS GRADE, DP.DEPT_NAME AS DEPARTMENT,CTM.CAT_NAME AS CATEGORY, VS.VERTICAL_NAME AS VERTICAL , SV.SUBVERTICAL_NAME AS SUBVERTICAL 
		,SB.SUBBRANCH_NAME AS SUBBRANCH, TM.TYPE_NAME AS EMPLOYEE_TYPE , BS.SEGMENT_NAME AS BUSINESS_SEGMENT
		,REPLACE(CONVERT(VARCHAR , ISNULL(Q2.LT_FOR_DATE, Q1.EIR_FOR_DATE) , 106) , ' ' , '-') AS LAST_ATTENDEND_DATE , REPLACE(CONVERT(VARCHAR , GETDATE() , 106) , ' ' , '-') AS REPORT_GENERATED_DATE
		,DATEDIFF(DD,ISNULL(Q2.LT_FOR_DATE, Q1.EIR_FOR_DATE) ,  GETDATE()) AS TOTAL_ABSENT_DAYS
		FROM T0080_EMP_MASTER EM WITH (NOLOCK)
		INNER JOIN T0095_INCREMENT INC WITH (NOLOCK) on INC.EMP_ID = EM.EMP_ID AND INC.CMP_ID = EM.CMP_ID
		INNER JOIN (
						SELECT	MAX(I2.Increment_ID) AS Increment_ID,I2.Emp_ID 
						FROM	T0095_Increment I2 WITH (NOLOCK) INNER JOIN T0080_EMP_MASTER E WITH (NOLOCK) ON I2.Emp_ID=E.Emp_ID
								INNER JOIN (
												SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE, I3.EMP_ID
												FROM T0095_INCREMENT I3 WITH (NOLOCK) INNER JOIN T0080_EMP_MASTER E3 WITH (NOLOCK) ON I3.Emp_ID=E3.Emp_ID	
												WHERE I3.Increment_effective_Date <= @To_Date
												GROUP BY I3.EMP_ID  
											) I3 ON I2.Increment_Effective_Date=I3.Increment_Effective_Date AND I2.EMP_ID=I3.Emp_ID																																			
						GROUP BY I2.Emp_ID
					) I ON INC.Emp_ID = I.Emp_ID AND INC.Increment_ID = I.Increment_ID
		INNER JOIN T0150_EMP_INOUT_RECORD EIR WITH (NOLOCK) ON EM.Emp_ID = EIR.Emp_ID
		INNER JOIN (
					SELECT EIR1.EMP_ID , MAX(EIR1.FOR_DATE) AS EIR_FOR_DATE 
					FROM T0150_EMP_INOUT_RECORD EIR1 WITH (NOLOCK)
					GROUP BY EIR1.EMP_ID
					)Q1 ON EM.EMP_ID = Q1.EMP_ID 
		LEFT OUTER JOIN 
					(
					SELECT LT.Emp_ID , MAX(LT.For_Date) AS LT_FOR_DATE
					FROM T0140_LEAVE_TRANSACTION LT WITH (NOLOCK)
					WHERE LT.Leave_Used <> 0
					GROUP BY LT.EMP_ID
					)Q2 ON EM.Emp_ID = Q2.Emp_ID AND Q2.LT_FOR_DATE > Q1.EIR_FOR_DATE
		INNER JOIN #Emp_Cons ec ON EC.Emp_ID = INC.Emp_ID AND EC.Increment_ID = INC.Increment_ID
		INNER JOIN T0030_BRANCH_MASTER BM WITH (NOLOCK) ON Bm.Branch_ID = inc.Branch_ID AND INC.Cmp_ID = bm.Cmp_ID
		INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.DESIG_ID = INC.DESIG_ID AND iNC.Cmp_ID = dm.Cmp_ID
		INNER JOIN T0040_GRADE_MASTER GM WITH (NOLOCK) ON GM.GRD_ID = INC.GRD_ID AND INC.CMP_ID = GM.CMP_ID
		LEFT OUTER JOIN T0040_DEPARTMENT_MASTER DP WITH (NOLOCK) ON DP.DEPT_ID = INC.DEPT_ID AND INC.CMP_ID = DP.CMP_ID
		LEFT OUTER JOIN T0040_VERTICAL_SEGMENT VS WITH (NOLOCK) ON VS.VERTICAL_ID = INC.VERTICAL_ID AND INC.CMP_ID = VS.CMP_ID
		LEFT OUTER JOIN T0050_SUBVERTICAL SV WITH (NOLOCK) ON SV.SUBVERTICAL_ID = INC.SUBVERTICAL_ID AND INC.CMP_ID = SV.CMP_ID
		LEFT OUTER JOIN T0040_BUSINESS_SEGMENT BS WITH (NOLOCK) ON BS.SEGMENT_ID = INC.SEGMENT_ID AND INC.CMP_ID = BS.CMP_ID
		LEFT OUTER JOIN T0050_SUBBRANCH SB WITH (NOLOCK) ON SB.SUBBRANCH_ID = INC.SUBBRANCH_ID AND INC.CMP_ID = SB.CMP_ID
		LEFT OUTER JOIN T0040_TYPE_MASTER TM WITH (NOLOCK) ON TM.TYPE_ID = INC.TYPE_ID AND INC.CMP_ID	= TM.CMP_ID
		LEFT OUTER JOIN T0030_CATEGORY_MASTER CTM WITH (NOLOCK) ON CTM.CAT_ID = INC.CAT_ID AND INC.CMP_ID = CTM.CMP_ID
		WHERE EMP_LEFT <> 'Y' AND DATEDIFF(dd,ISNULL(Q2.LT_FOR_DATE, Q1.EIR_FOR_DATE) ,  @To_Date)  > @DAYS 
		GROUP BY EM.CMP_ID , EM.EMP_ID , EM.ALPHA_EMP_CODE , EM.EMP_FULL_NAME ,EM.DATE_OF_JOIN ,BM.BRANCH_NAME, DM.DESIG_NAME ,gm.Grd_Name, 
		DP.DEPT_NAME ,CTM.CAT_NAME, VS.VERTICAL_NAME , SV.SUBVERTICAL_NAME , SB.SUBBRANCH_NAME , TM.TYPE_NAME, BS.SEGMENT_NAME,  Q2.LT_FOR_DATE,Q1.EIR_FOR_DATE
		ORDER BY ALPHA_EMP_CODE
RETURN

