
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[SP_RPT_BANK_STATEMENT_GET_IDFC]
	 @CMP_ID		 NUMERIC  
	,@FROM_DATE		 DATETIME  
	,@TO_DATE		 DATETIME  
	,@BRANCH_ID		 VARCHAR(MAX)  
	,@CAT_ID		 VARCHAR(MAX)  
	,@GRD_ID		 VARCHAR(MAX)  
	,@TYPE_ID		 VARCHAR(MAX)
	,@DEPT_ID		 VARCHAR(MAX)
	,@DESIG_ID		 VARCHAR(MAX)
	,@EMP_ID		 NUMERIC  
	,@CONSTRAINT	 VARCHAR(MAX)  	
	,@ORDER_BY		 VARCHAR(30) = 'CODE'
	,@PAYMENT_MODE   VARCHAR(15) = ''
	,@SEGMENT_ID	 VARCHAR(MAX) = ''
	,@VERTICAL_ID	 VARCHAR(MAX) = ''
	,@SUBVERTICAL_ID VARCHAR(MAX) =''
	,@SUBBRANCH_ID	 VARCHAR(MAX) = ''
	--,@BANK_ID  NUMERIC = 0  
	,@BANK_ID		 VARCHAR(MAX) = ''	--changed by ramiz on 18/03/2019
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	IF @BANK_ID = ''  
		SET @BANK_ID = NULL 		
			
	CREATE TABLE #EMP_CONS 
	(      
		EMP_ID NUMERIC ,     
		BRANCH_ID NUMERIC,
		INCREMENT_ID NUMERIC
	)	

	EXEC SP_RPT_FILL_EMP_CONS_MULTIDROPDOWN @CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRD_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID,@EMP_ID,
											@CONSTRAINT,0,0,'','','','',0,0,0,'0',0,0  
	
		
	--CODE ADDED BY RAMIZ TO TAKE SELECTED BANKS IN TEMP TABLE--
	SELECT TOP 0 * INTO #BANK_MASTER 
	FROM T0040_BANK_MASTER BM WITH (NOLOCK)
	IF LEN(ISNULL(@Bank_ID, '')) = 0
		INSERT INTO #BANK_MASTER 
		SELECT  * FROM T0040_BANK_MASTER BM WITH (NOLOCK)
		WHERE BM.CMP_ID = @CMP_ID
	ELSE
		INSERT INTO #BANK_MASTER 
		SELECT  BM.* FROM T0040_BANK_MASTER BM WITH (NOLOCK)
				inner join (SELECT CAST(Data As Numeric) As BANK_ID FROM dbo.Split(@Bank_ID,'#') T 
							WHERE T.Data <> '' and IsNumeric(T.Data) = 1
							)  T ON T.BANK_ID = BM.BANK_ID

										
	SELECT		CM.CMP_CODE ,'="' + BM1.Bank_Ac_No + '"'   AS 'Debit Account No.','LBT' AS 'Transaction Type Code', CONVERT(VARCHAR(20) , GETDATE() , 103) AS 'VALUE DATE',
				'="' + CAST(MS.NET_AMOUNT AS VARCHAR) + '"' AS AMOUNT,ISNULL(EM.EMPNAME_ALIAS_PRIMARYBANK,EM.EMP_FULL_NAME) AS 'BENEFICIERY NAME','="' +INC_QRY.INC_BANK_AC_NO + '"' AS 'BENEFICIERY A/C NUMBER',
				EM.IFSC_CODE as 'BENEFICIERY IFSC', '' AS 'Customer Ref No.' , EM.Work_Email as 'Beneficary Email ID', EM.Mobile_No AS 'Beneficiary Mobile No.' ,'' AS REMARKS, 'NEFT' AS 'PAYMENT TYPE' , 
				'OTH' AS 'Purpose Code','11' AS 'BENEFICIERY A/C TYPE', '' as 'Payable Location' , '' as 'Print Branch Name' , '' as 'Mode of Delivery' , '' as 'Transaction Currency' ,
				'' as 'BENE_ADD1' ,'' as 'BENE_ADD2' ,'' as 'BENE_ADD3' ,'' as 'BENE_ADD4' 
				
				--For Header
				,CM.CMP_NAME,CM.CMP_ADDRESS,BM.COMP_NAME,BM.BRANCH_ADDRESS,@FROM_DATE AS FROM_DATE,@TO_DATE AS TO_DATE
				,@PAYMENT_MODE  AS  PAYMENT_MODE,DP.DEPT_NAME,DM.DESIG_NAME,TM.TYPE_NAME,GM.GRD_NAME ,BN.BANK_ID
	INTO		#FINAL_TABLE
	FROM		T0080_EMP_MASTER EM WITH (NOLOCK)
				INNER JOIN	#EMP_CONS EC ON EC.EMP_ID = EM.EMP_ID
				INNER JOIN	T0095_INCREMENT INC_QRY WITH (NOLOCK) ON INC_QRY.INCREMENT_ID = EC.INCREMENT_ID AND INC_QRY.EMP_ID = EC.EMP_ID 
				LEFT OUTER JOIN	
				--Added By Jimit 27092018 in salary we Consider Increment id with out Transfer and deputation (case at Golcha Employee Trnasfer to another branch so here it pick latest Increment Id with Transfer case)
					(
						SELECT	MAX(I2.Increment_ID) AS Increment_ID,I2.Emp_ID 	
						FROM	T0095_Increment I2 WITH (NOLOCK)
							INNER JOIN T0080_EMP_MASTER E WITH (NOLOCK) ON I2.Emp_ID=E.Emp_ID
							INNER JOIN 
								(
									SELECT	MAX(INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE, I3.EMP_ID	
									FROM	T0095_INCREMENT I3 WITH (NOLOCK) INNER JOIN 
											T0080_EMP_MASTER E3 WITH (NOLOCK) ON I3.Emp_ID=E3.Emp_ID 
									WHERE	I3.Increment_effective_Date <= getdate() AND I3.Cmp_ID = @CMP_ID AND	
											I3.Increment_Type NOt IN ('Transfer','Deputation')
									GROUP BY I3.EMP_ID 
								 ) I3 ON I2.Increment_Effective_Date=I3.Increment_Effective_Date AND I2.EMP_ID=I3.Emp_ID	
						WHERE I2.Increment_Type NOT IN ('Transfer','Deputation')
						GROUP BY I2.Emp_ID 
					) I_Q1 ON EC.Emp_ID = I_Q1.Emp_ID
				LEFT OUTER JOIN	#BANK_MASTER BN ON INC_QRY.BANK_ID = BN.BANK_ID 
				LEFT OUTER JOIN	T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON MS.INCREMENT_ID = I_Q1.INCREMENT_ID AND MS.EMP_ID = EM.EMP_ID
				LEFT OUTER JOIN	T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.DESIG_ID = INC_QRY.DESIG_ID
				LEFT OUTER JOIN	T0030_BRANCH_MASTER BM WITH (NOLOCK) ON BM.BRANCH_ID = EC.BRANCH_ID
				INNER JOIN		T0010_COMPANY_MASTER CM WITH (NOLOCK) ON CM.CMP_ID = EM.CMP_ID
				LEFT OUTER JOIN	T0040_DEPARTMENT_MASTER DP WITH (NOLOCK) ON DP.DEPT_ID = INC_QRY.DEPT_ID
				LEFT OUTER JOIN T0040_GRADE_MASTER GM WITH (NOLOCK) ON GM.GRD_ID= INC_QRY.GRD_ID
				LEFT OUTER JOIN	T0040_TYPE_MASTER TM WITH (NOLOCK) ON TM.[TYPE_ID] =INC_QRY.[TYPE_ID]
				LEFT OUTER JOIN
					(
						SELECT Bank_Id,Cmp_Id FROM #BANK_MASTER WHERE Cmp_Id = @Cmp_Id AND Is_Default = 'Y'
					)Q ON Q.Cmp_Id = EM.Cmp_Id
				LEFT OUTER JOIN	#BANK_MASTER BM1 On BM1.BANK_ID = Q.Bank_Id		
	WHERE		MONTH(MS.MONTH_END_DATE) = MONTH(@TO_DATE) AND YEAR(MS.MONTH_END_DATE) = YEAR(@TO_DATE) 
				AND INC_QRY.PAYMENT_MODE =  (CASE WHEN @PAYMENT_MODE <> '' THEN @PAYMENT_MODE ELSE INC_QRY.PAYMENT_MODE END)
				--AND ISNULL(INC_QRY.BANK_ID,0) = ISNULL(@BANK_ID,ISNULL(INC_QRY.BANK_ID,0))
	ORDER BY	CASE WHEN @ORDER_BY='ENROLL_NO' THEN RIGHT(REPLICATE('0',21) + CAST(EM.ENROLL_NO AS VARCHAR), 21)  
					 WHEN @ORDER_BY='NAME' THEN EM.EMP_FULL_NAME 
					 WHEN @ORDER_BY = 'DESIGNATION' THEN (CASE WHEN DM.DESIG_DIS_NO = 0 THEN DM.DESIG_NAME 
															   ELSE RIGHT(REPLICATE('0',21) + CAST(DM.DESIG_DIS_NO AS VARCHAR), 21)   
														   END) 
					 END,
				CASE WHEN ISNUMERIC(REPLACE(REPLACE(EM.ALPHA_EMP_CODE,'="',''),'"','')) = 1 THEN RIGHT(REPLICATE('0',21) + REPLACE(REPLACE(EM.ALPHA_EMP_CODE,'="',''),'"',''), 20)
					 WHEN ISNUMERIC(REPLACE(REPLACE(EM.ALPHA_EMP_CODE,'="',''),'"','')) = 0 THEN LEFT(REPLACE(REPLACE(EM.ALPHA_EMP_CODE,'="',''),'"','') + REPLICATE('',21), 20)
					 ELSE REPLACE(REPLACE(EM.ALPHA_EMP_CODE,'="',''),'"','')
				END

		--Added By Ramiz on 18/03/2019
	--IF Len(isNull(@Bank_ID ,'')) > 0
	--	delete from #FINAL_TABLE Where BANK_ID IS NULL
								
			SELECT * FROM #FINAL_TABLE
RETURN
	
