




CREATE PROCEDURE [dbo].[SP_T0040_GENERAL_SETTING_GET]
	@CMP_ID		NUMERIC ,
	@BRANCH_ID	NUMERIC ,
	@FOR_DATE	DATETIME,
	@COLUMN_OPTION	VARCHAR(20) ='ALL'
AS
	SET NOCOUNT ON 
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET ARITHABORT ON  
	
		
	IF @BRANCH_ID > 0 
		BEGIN
			SELECT GS.* FROM T0040_GENERAL_SETTING GS WITH (NOLOCK) INNER JOIN 
				(SELECT MAX(FOR_DATE)FOR_DATE,BRANCH_ID,CMP_ID FROM T0040_GENERAL_SETTING WITH (NOLOCK) 
					WHERE CMP_ID =@CMP_ID AND BRANCH_ID = @BRANCH_ID and For_date <=@For_Date
					GROUP BY CMP_ID,BRANCH_ID ) Q 
					ON GS.BRANCH_ID	= Q.BRANCH_ID AND GS.FOR_DATE = Q.FOR_DATE
		END
	ELSE
		BEGIN
			SELECT GS.* FROM T0040_GENERAL_SETTING GS WITH (NOLOCK) INNER JOIN 
				(SELECT MAX(FOR_DATE)FOR_DATE,CMP_ID FROM T0040_GENERAL_SETTING WITH (NOLOCK)
					WHERE CMP_ID =@CMP_ID and For_date <=@For_Date
					GROUP BY CMP_ID ) Q 
					ON GS.CMP_ID = Q.CMP_ID AND GS.FOR_DATE = Q.FOR_DATE
		END
	
	RETURN




