




CREATE PROCEDURE [dbo].[SP_T0015_Login_Rights]
	@CMP_ID		NUMERIC ,
	@BRANCH_ID	NUMERIC ,
    @Login_ID Numeric
AS
	SET NOCOUNT ON 
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET ARITHABORT ON  
	
	IF @BRANCH_ID > 0 
		BEGIN
			SELECT GS.* FROM T0015_Login_Rights GS WITH (NOLOCK) INNER JOIN 
				(SELECT BRANCH_ID,CMP_ID FROM T0011_Login WITH (NOLOCK)
					WHERE CMP_ID =@Cmp_ID AND BRANCH_ID = @Branch_ID
					GROUP BY CMP_ID,BRANCH_ID) Q 
					ON GS.BRANCH_ID	= Q.BRANCH_ID AND GS.Cmp_ID = Q.Cmp_ID where Login_ID = @Login_ID
		END
	ELSE
		BEGIN
		SELECT GS.* FROM T0015_Login_Rights GS WITH (NOLOCK) INNER JOIN 
				(SELECT CMP_ID FROM T0011_Login WITH (NOLOCK) 
					WHERE CMP_ID =@Cmp_ID 
					GROUP BY CMP_ID ) Q 
					ON GS.CMP_ID = Q.CMP_ID  Where Login_ID=@Login_ID
		END
	
	RETURN




