

--Created By Mukti(07012016) 
CREATE PROCEDURE [dbo].[Update_Menu_setting]        
@cmp_id numeric(18,0) = 0
AS        
		SET NOCOUNT ON 
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		SET ARITHABORT ON   
begin
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Is_BranchWise_Birthday'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='IS_YEARLY_CTC'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='AX'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Min. basic rules applicable'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Show Left Employee for Salary'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Add initial in employee full name'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Send Email in Bulk Leave Approval'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Employee Retirement Age'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Enable Miss punch SMS'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Send Remainder mail of Increment'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Present Compulsory Extra Days Deduction(Holiday Master)'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Calculate Salary Base on Production Details'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Send Email through SQL Job'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Employee Lock After First Salary'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Salary Cycle Employee Wise'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Salary Records Highlight if no PAN Card Number'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Salary Records Highlight if Previous Salary on Hold'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Leave not Approval Popup in Salary'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Hide Browse file in IT declaration'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable IT Declaration for mid join employee upto days'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='show other Employee leave in leave Approval'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Show Emp Detail at top view(Ess)'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Process salary in background'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Show Pass Responsibility in Leave'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Show list of employees whose PT settings are pending during Salary Process'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Salary Slip with Password Protected'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='State wise minimum wages Calculation'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Salary Slip with Password Protected'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Hide Downline Employee Salary'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Allow Part Day Leave'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Allow Attendance Regularization Editable'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Show Current Month Attendance Regularization Count On Home Page'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Allow Comments in Salary Slip'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='In OT Approval Remark Column Show'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Hide Cancel Weekoff and Holiday in Leave Approval'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Upper Round for Employer ESIC'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Allowance detail show in Allowance/Reimbursement'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Intimate day for Allowance/Reimbursement application'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Age Restriction in Medical for Dependent (Enter Age)'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Hide Age Column'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Reimbusement application after date of join days'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Reimbershment Not Effect in Salary Default'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Insurance Reminder Days'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Add Other Employees In Travel Settlement'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Check out Date Option in Travel Application'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Instruct By Employee Column in Travel Application'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Hide Currency in Claim Application'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Enable document upload in grade master'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='OD and CompOff Leave Consider As Present'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Check Absent History of Previous Month in Leave'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Lower Round in leave Balance'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Asset Installment'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Conveyance Tax Exemption based on prorate'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Hide Monthly OT Approval'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Comp-off Balance show as on date wise'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Bulk Increment Basic Salary Upper Rouning'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Report Preview Options'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Show Reimbursement Amount in Salary Slip'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Maximum gap between two canteen punch (In minutes)'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Import Option for Estimated Amount'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Reimbershment Shows in IT Computation'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Allow Same Date Increment'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Special Allowance Calculate From Employee Allowance/Deduction Revise'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Pre Comp-off Request Mandatory'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Auto comp-Off leave dates adjust'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Auto CompOff Approval'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Branch wise Leave'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Auto LWP Leave'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Monthly base get reimbursement claim amount'
	Update T0040_SETTING set Module_Name='TIMESHEET' where Cmp_ID=@Cmp_ID and Setting_Name='Timesheet Type (Daily or Weekly)'
	Update T0040_SETTING set Module_Name='TIMESHEET' where Cmp_ID=@Cmp_ID and Setting_Name='Required Specility and Type of Services'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Hide Allowance Rate in Salary Slip'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Admin Side Default Salary Slip Format'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Display Leave Detail by Selected Period'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Include Leave Details in Salary Slip'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Show Birthday Reminder Group Company wise'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Round Loan Interest Amount'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Auto credit one medical leave when first time ESIC leave have approved in year'
	Update T0040_SETTING set Module_Name=NULL where Cmp_ID=@Cmp_ID and Setting_Name='Display Actual Birth Date'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Disable Tax Free Checkbox'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Show absent days in salary slip when calaculate salary on fix day'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable International Travel'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Show Gradewise Salary Textbox in Grade Master'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='How Many Decimal In Allowance'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='InActive User After Days'
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable document upload in Grade Master' 
	Update T0040_SETTING set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Setting_Name='Enable Project in Travel'	
end


