

---19/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[Update_Default_Mail_Settings_New]
		@Cmp_ID		numeric
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN 

	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Emp Probation Confirm'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Emp Probation Extend'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal1' where Cmp_ID=@Cmp_ID and Email_Type='Appraisal Initiation'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Claim Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Claim Payment'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='CompOff Application'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='CompOff Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Probation Confirm'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Probation Extend'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Employee forgetpassword'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Exit Application'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Exit Interview'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='ForgetPassword'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Interview Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Interview Call'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Leave Application'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Leave Cancellation'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Loan Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Loan Payment'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='NOC Exit'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Recruitment Post Detail'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Travel Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Travel Settlement Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Travel Settelment Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Welcome Email'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Increment'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Birth Day'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Travel Settlement Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Employee SignoffGoal'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Manager SignoffGoal'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Employee Signoff For Goal Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Manager Signoff For Goal Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Employee Review For Performance Summary'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Manager Review For Performance Summary'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Setting Inserted'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Setting Updated'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Setting Deleted'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Employee Review For Competency'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Manager Review For Competency'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Signoff For Goal Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Signoff For Goal Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Emp Performance Summary Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation Performance Summary Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Competency Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Competency Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Goal Signoff'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Goal Signoff'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Offer Letter'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Candidate Link'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Reimbursement\Claim Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Reimbursement\Claim Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Auto Mail of Probation Over'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Notify SubVertical'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Self Assessment'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='SelfAssessment Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='SelfAssessment Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='SelfAssessment Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='PerformanceAssessment Allocation'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='PerformanceAssessment GHReview'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='PerformanceAssessment Final'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Final Stage Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Direct Assessment Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Extended Self Assessment'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Asset Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Asset Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Recruitment Request'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Recruitment Request Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Resume Screening'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Resume Screened'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Employee Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Reviewed'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Employee Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Manager Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Employee Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Reviewed'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Employee Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Manager Approved'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Manager Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Reject'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPIRating Approve'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Closed'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Objective Manager Review'
	Update T0010_Email_Format_Setting_Default set Module_Name='Appraisal3' where Cmp_ID=@Cmp_ID and Email_Type='KPI Objective Final Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Change Request Application'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Change Request Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='TIMESHEET' where Cmp_ID=@Cmp_ID and Email_Type='Timesheet Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='TIMESHEET' where Cmp_ID=@Cmp_ID and Email_Type='Timesheet Approval'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Recruitment Approval Level'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Candidate Approval Scheme'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Candidate Approval Level'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Candidate Rejection'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Training Reminder'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Survey Form Filled By Employee'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Fill The Survey Form'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='PreCompOff Application'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Offer/Appointment Letter Status'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Leave Application Job'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Send final list of trainees'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Training Answers/Feedback Submitted'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Attendance Regularization'
	Update T0010_Email_Format_Setting_Default set Module_Name='HRMS' where Cmp_ID=@Cmp_ID and Email_Type='Candidate Resume Acknowledgement'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Birth Day Notification(Ess)'
	Update T0010_Email_Format_Setting_Default set Module_Name=NULL where Cmp_ID=@Cmp_ID and Email_Type='Reward Template'
	
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Marriage Anniversary'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Ticket Open'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Ticket Close'
	Update T0010_Email_Format_Setting_Default set Module_Name='PAYROLL' where Cmp_ID=@Cmp_ID and Email_Type='Different Location Login Alert'
	
	
--Added by Mukti(11012018)Set Is_Active=0 as not in use email formats(start)---
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Appraisal Initiation'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Appraisal Approval'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Manager SignoffGoal'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Manager Signoff For Goal Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Manager Review For Performance Summary'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Manager Review For Competency'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Employee SignoffGoal'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Employee Signoff For Goal Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Employee Review For Performance Summary'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Employee Review For Competency'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Signoff For Goal Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Signoff For Goal Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Emp Performance Summary Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation Performance Summary Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Competency Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Competency Review'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Employee Goal Signoff'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Confirmation for Manager Goal Signoff'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Setting Inserted'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Setting Updated'
	update T0010_Email_Format_Setting_Default set Is_Active=0 where  Cmp_ID=@Cmp_ID and Email_Type='Setting Deleted'
--Added by Mukti(11012018)Set Is_Active=0 as not in use email formats(end)---
END
