
---10/3/2021 (EDIT BY MEHUL ) (Scaler-valued function WITH NOLOCK)---
CREATE FUNCTION [dbo].[F_GET_DOWNLINE_EMPLOYEES_XML] 
	(
		@R_EMP_ID NUMERIC(18,0),
		@EFF_DATE DATETIME
	)
RETURNS VARCHAR(MAX)
AS
	BEGIN
			IF @EFF_DATE IS NULL
				SET @EFF_DATE = GETDATE();
				
			DECLARE @EMP_ID VARCHAR(MAX)
		
			SELECT		@EMP_ID = REPLACE(REPLACE(STUFF((SELECT ',' + QUOTENAME(RD.EMP_ID) 
			FROM		T0090_EMP_REPORTING_DETAIL RD WITH (NOLOCK) INNER JOIN 
						(
							SELECT MAX(EFFECT_DATE) AS EFFECT_DATE,EMP_ID FROM T0090_EMP_REPORTING_DETAIL WITH (NOLOCK)
							WHERE EFFECT_DATE <= @EFF_DATE
							GROUP BY EMP_ID
						) AS EMP_SUP
			ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE
			WHERE RD.R_EMP_ID =@R_EMP_ID
			GROUP BY RD.EMP_ID 
			ORDER BY RD.EMP_ID  
			FOR XML PATH(''),TYPE).value('.', 'NVARCHAR(MAX)') ,1,1,''),']',''),'[','')-- AS EMP_ID

					
			RETURN ISNULL(@EMP_ID ,'')
	END




