
---10/3/2021 (EDIT BY MEHUL ) (Scaler-valued function WITH NOLOCK)---
CREATE FUNCTION [dbo].[F_Get_FTP_Filename]
	(
		@cmp_id as INTEGER
	)
RETURNS  varchar(2000)
AS
	BEGIN
		DECLARE @ftpFileName varchar(2000)	
		DECLARE @DAY	AS VARCHAR(2)
		DECLARE @MONTH	AS VARCHAR(2)
		DECLARE @EXTENSION_NO AS NUMERIC
		DECLARE @EXTENSION_VAR AS VARCHAR(3)
	
		SET @DAY = CAST(DAY(GETDATE()) AS CHAR(2))
		SET @MONTH =  RIGHT('0' + RTRIM(MONTH(GETDATE())), 2);
		
		SELECT  @EXTENSION_NO = ISNULL(MAX(FileExtension),0) + 1
		FROM T9999_FTP_UPLOAD_HISTORY WITH (NOLOCK)
		WHERE CAST(Login_Date AS DATE) = CAST(GETDATE() AS DATE)
	
	
		SELECT @EXTENSION_VAR = RIGHT('00' + RTRIM(@EXTENSION_NO), 3);
		
		IF NOT EXISTS (SELECT 1 FROM T0100_FTP_DETAILS WITH (NOLOCK))
			SET @ftpFileName = 'rpt_Bank_Statement_ftp.001'
		ELSE
			SELECT @ftpFileName = DOMAIN_NAME + '_' + CLIENTCODE + '_' + CLIENTCODE + @DAY + @MONTH + '.' + @EXTENSION_VAR 
			FROM T0100_FTP_DETAILS WITH (NOLOCK) WHERE CMP_ID = @cmp_id



	RETURN @ftpFileName 
	END




