


---10/3/2021 (EDIT BY MEHUL ) (Table-valued function WITH NOLOCK)---
CREATE FUNCTION [dbo].[fn_getCompanyDetail] 
(	
	@Cmp_ID NUMERIC,
	@Effect_Date DateTime
)

RETURNS @Rtn_Effective_Table TABLE 
(
  EFFECT_DATE DATETIME,
  CMP_ID NUMERIC,
  CMP_NAME VARCHAR(100),
  CMP_ADDRESS VARCHAR(250),
  CMP_PINCODE VARCHAR(10),
  CMP_PHONE VARCHAR(20),
  CMP_EMAIL VARCHAR(50),
  CMP_WEB VARCHAR(50),
  CMP_CITY VARCHAR(50),
  LOC_ID NUMERIC,
  DATE_FORMAT VARCHAR(5),
  FROM_DATE DATETIME,
  TO_DATE DATETIME,
  PF_NO VARCHAR(20),
  ESIC_NO VARCHAR(20),
  DOMAIN_NAME VARCHAR(50),
  IMAGE_NAME VARCHAR(200),
  DEFAULT_HOLIDAY VARCHAR(120),
  CMP_TYPE VARCHAR(30),
  CMP_STATE_NAME VARCHAR(20),             
  CMP_HR_MANAGER VARCHAR(50),
  CMP_HR_MANAGER_DESIG VARCHAR(30),
  CIT_PIN NUMERIC,
  CIT_CITY NVARCHAR(100)
)
AS
BEGIN	

	
	IF EXISTS(SELECT 1 FROM T0040_SETTING WITH (NOLOCK) WHERE Setting_Name='Enable Effective Date Wise Company Name' AND Setting_Value=1 and CMP_ID=@CMP_ID)
		BEGIN	
		 
			INSERT INTO @Rtn_Effective_Table
				SELECT  QRY1.EFFECT_DATE,CM.CMP_ID, ISNULL(CD.CMP_NAME,CM.CMP_NAME) AS CMP_NAME,ISNULL(CD.CMP_ADDRESS,CM.CMP_ADDRESS) AS CMP_ADDRESS,CM.CMP_PINCODE, CM.CMP_PHONE, CM.CMP_EMAIL, CM.CMP_WEB, CM.CMP_CITY, CM.LOC_ID,  CM.DATE_FORMAT, FROM_DATE, TO_DATE, PF_NO, ESIC_NO, 
					  CM.DOMAIN_NAME, CM.IMAGE_NAME, CM.DEFAULT_HOLIDAY, CM.CMP_TYPE, CM.CMP_STATE_NAME, CM.CMP_HR_MANAGER, CM.CMP_HR_MANAGER_DESIG, CM.CIT_PIN, CM.CIT_CITY
				FROM         T0010_COMPANY_MASTER CM WITH (NOLOCK)
					LEFT JOIN (SELECT	MAX(Effect_Date) AS Effect_Date,I1.Cmp_Id
							FROM	T0011_COMPANY_DETAIL I1 WITH (NOLOCK)
							WHERE Effect_Date <= Case When (YEAR(ISNULL(@Effect_Date,'1900-01-01')) < 1901) 
												then GETDATE() Else @Effect_Date END
							GROUP BY I1.Cmp_Id) QRY1 ON Cm.Cmp_Id=QRY1.Cmp_Id
					LEFT JOIN T0011_COMPANY_DETAIL CD WITH (NOLOCK) ON CD.CMP_ID = CM.CMP_ID and CD.Effect_Date = QRY1.Effect_Date
				WHERE	CM.Cmp_Id=@Cmp_ID
		END
		
	ELSE
		BEGIN
			INSERT INTO @Rtn_Effective_Table
			SELECT  From_Date As EFFECT_DATE,CM.CMP_ID, CMP_NAME,CMP_ADDRESS,CM.CMP_PINCODE, CM.CMP_PHONE, CM.CMP_EMAIL, CM.CMP_WEB, CM.CMP_CITY, CM.LOC_ID,  CM.DATE_FORMAT, FROM_DATE, TO_DATE, PF_NO, ESIC_NO, 
				  CM.DOMAIN_NAME, CM.IMAGE_NAME, CM.DEFAULT_HOLIDAY, CM.CMP_TYPE, CM.CMP_STATE_NAME, CM.CMP_HR_MANAGER, CM.CMP_HR_MANAGER_DESIG, CM.CIT_PIN, CM.CIT_CITY
			FROM     T0010_COMPANY_MASTER CM WITH (NOLOCK)			
			WHERE	CM.Cmp_Id=@Cmp_ID
		END
	RETURN
END 
