CREATE FUNCTION [DBO].[FNC_KPMS_DEPENDENCY_CAL](@GSGGOALID INT,@GSG_GoalSetting_Id INT,@Goal_Allotment_Id  INT)      
RETURNS VARCHAR(MAX)    

AS                              
BEGIN                           
	--@GSGGOALID INT = 2,@GSG_GoalSetting_Id = 1,@Goal_Allotment_Id = 2
	DECLARE @ISDEPENDED INT,@TARGETVALUE INT,@DEPTARGETVALUE INT,@ACTUAL_VALUE INT,@DEPEN_GID INT,@COUNT INT = 1,@IND INT,@TBL_TV INT,@TBL_DTV INT,@D_Type INT,@Freq_Id int,@Depended_Freqid int,@Dpend_Goalid int,@Achievement int,@Month_Num int,@DMonth_Num varchar(max)
	select @Month_Num = MONTH(DATEADD(MM,-1,GETDATE()))
	
	DECLARE @tbl_MONTH_NUM TABLE(Month_Number int)
	DECLARE @DEP_TMP TABLE(RN INT,GID INT,D_GID INT,TARGETVAL INT,DEPEND_TARGETVAL INT,FREQ_ID INT,DEPEND_FREQ_ID INT,D_Type INT)
	
	ISDPENDED:
	SELECT @ISDEPENDED = GSG_ISDEPENDENCY FROM KPMS_T0110_GOAL_SETTING_GOAL WHERE GSG_GOAL_ID = @GSGGOALID	AND GSG_GOALSETTING_ID = @GSG_GoalSetting_Id 
	IF(@ISDEPENDED = 1)
		BEGIN
		SET @DEPEN_GID = @GSGGOALID	

			SELECT @D_Type = GSG_Depend_Type_Id FROM KPMS_T0110_Goal_Setting_Goal WHERE GSG_GOAL_ID = @GSGGOALID and GSG_GoalSetting_Id = @GSG_GoalSetting_Id 
			SELECT @Freq_Id = GSG_FrequecyId FROM KPMS_T0110_Goal_Setting_Goal WHERE GSG_GOAL_ID = @GSGGOALID and GSG_GoalSetting_Id = @GSG_GoalSetting_Id
			SELECT @Dpend_Goalid = GSG_DEPEND_GOAL_ID FROM KPMS_T0110_GOAL_SETTING_GOAL WHERE GSG_GOAL_ID = @GSGGOALID AND GSG_GOALSETTING_ID = @GSG_GoalSetting_Id 
			SELECT @Depended_Freqid = GSG_FrequecyId FROM KPMS_T0110_Goal_Setting_Goal WHERE GSG_GOAL_ID = @Dpend_Goalid and GSG_GoalSetting_Id = @GSG_GoalSetting_Id 
			SELECT @TargetValue = TargetValues FROM KPMS_T0100_Level_Assign WHERE GoalId = @GSGGOALID and Goal_Allotment_Id = @Goal_Allotment_Id
			SELECT @GSGGOALID = GSG_DEPEND_GOAL_ID FROM KPMS_T0110_GOAL_SETTING_GOAL WHERE GSG_GOAL_ID = @GSGGOALID AND GSG_GOALSETTING_ID = @GSG_GoalSetting_Id
			SELECT @DEPTARGETVALUE = TARGETVALUES FROM KPMS_T0100_LEVEL_ASSIGN WHERE GOALID = @GSGGOALID AND GOAL_ALLOTMENT_ID = @Goal_Allotment_Id
			SELECT @ISDEPENDED = GSG_ISDEPENDENCY FROM KPMS_T0110_GOAL_SETTING_GOAL WHERE GSG_GOAL_ID = @GSGGOALID AND GSG_GOALSETTING_ID = @GSG_GoalSetting_Id

			INSERT INTO @DEP_TMP VALUES (@COUNT,@GSGGOALID,@DEPEN_GID,@TARGETVALUE,@DEPTARGETVALUE,@DEPENDED_FREQID,@FREQ_ID,@D_Type)  

			SET @COUNT = @COUNT + 1

			IF @ISDEPENDED = 1 GOTO ISDPENDED
		END  

	DECLARE @COUNT2 INT 
	SELECT @COUNT2 = COUNT(RN) FROM @DEP_TMP 

		WHILE(@COUNT2>0)
		BEGIN
			SELECT @Freq_Id = FREQ_ID FROM @DEP_TMP WHERE RN = @COUNT2
			SELECT @Depended_Freqid = DEPEND_FREQ_ID FROM @DEP_TMP WHERE RN = @COUNT2
			SELECT @D_Type = D_Type FROM @DEP_TMP WHERE RN = @COUNT2
				IF(@D_Type = 1)
					BEGIN
						IF(@Freq_Id = 1 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE =  (DEPEND_TARGETVAL) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END			
						ELSE
						 IF(@Freq_Id = 1 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL*3) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 1 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL*12) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE =  (DEPEND_TARGETVAL) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL/3) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL*4) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE =  (DEPEND_TARGETVAL) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL/12) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE = (DEPEND_TARGETVAL/4) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END

						SET @COUNT2 = @COUNT2 - 1
						UPDATE @DEP_TMP SET DEPEND_TARGETVAL = @ACTUAL_VALUE WHERE RN = @COUNT2
				END
				ELSE
				BEGIN
			
					SELECT @ACHIEVEMENT = ACHIEVEMENT FROM KPMS_T0110_TARGETACHIVEMENT A INNER JOIN @DEP_TMP B ON A.GOALID = B.GID WHERE RN = @COUNT2 AND MONTH_NUM = @MONTH_NUM AND A.GOALID = B.GID

						IF(@Freq_Id = 1 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE =  (@Achievement) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END			
						ELSE
						 IF(@Freq_Id = 1 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement*3) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 1 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement*12) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE =  (@Achievement) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement/3) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 2 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement*4) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 3)
							BEGIN
								SELECT @ACTUAL_VALUE =  (@Achievement) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 1)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement/12) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END
						ELSE 
						 IF(@Freq_Id = 3 and @Depended_Freqid = 2)
							BEGIN
								SELECT @ACTUAL_VALUE = (@Achievement/4) * CAST(TARGETVAL AS NUMERIC(18,2))/100 FROM @DEP_TMP WHERE RN = @COUNT2
							END

						SET @COUNT2 = @COUNT2 - 1
						UPDATE @DEP_TMP SET DEPEND_TARGETVAL = @ACTUAL_VALUE WHERE RN = @COUNT2
				END
		END

	RETURN @ACTUAL_VALUE

END  
  