




Create FUNCTION [dbo].[GET_MONTH_END_DATE_bkp_12Jan2022_Deepali]
	(
		@MONTH AS NUMERIC ,
		@YEAR AS NUMERIC
	)
RETURNS DATETIME
AS
	
	BEGIN
		
		DECLARE @MONTH_ST_DATE AS DATETIME	
		DECLARE @MONTH_END_DATE AS DATETIME	
		
	
		DECLARE @MONTH_DAY AS NUMERIC
		DECLARE @DAY AS NUMERIC 
		DECLARE @FOR_DATE AS DATETIME
		
		SET @FOR_DATE = CAST(CAST(@MONTH AS VARCHAR(2)) + '/' + '01' + '/' + CAST(@YEAR AS VARCHAR(5)) AS SMALLDATETIME)
		
		SET @DAY = DAY(@FOR_DATE) - 1
		
		SET @MONTH_DAY = DAY(DATEADD(d, -DAY(DATEADD(m,1,@FOR_DATE)),DATEADD(m,1,@FOR_DATE))) - 1
		SET @MONTH_ST_DATE = DATEADD(D,-@DAY,@FOR_DATE)
		
		SET @MONTH_END_DATE = DATEADD(D,@MONTH_DAY,@MONTH_ST_DATE)
	
		RETURN @MONTH_END_DATE
	END




