

-- =============================================
-- AUTHOR:		<AUTHOR,,NAME>
-- CREATE DATE: <CREATE DATE,,>
-- DESCRIPTION:	<DESCRIPTION,,>
---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE  [dbo].[CHECK_DUPLICATION_TRAINING_PLAN]
 @CMP_ID AS NUMERIC(18,0)
,@TRAINING_APP_ID NUMERIC(18,0)
,@TRAINING_ID NUMERIC(18,0)	
,@FROM_DATE	 DATETIME
,@TO_DATE DATETIME

AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	
	IF EXISTS( SELECT 1 FROM T0120_HRMS_TRAINING_SCHEDULE HTS WITH (NOLOCK) INNER JOIN
	 T0120_HRMS_TRAINING_APPROVAL HTA WITH (NOLOCK) ON HTS.TRAINING_APP_ID = HTA.TRAINING_APP_ID
	WHERE ((@FROM_DATE BETWEEN HTS.FROM_DATE AND HTS.TO_DATE) OR (@TO_DATE BETWEEN HTS.FROM_DATE AND HTS.TO_DATE))
	AND HTA.TRAINING_ID = @TRAINING_ID AND HTS.TRAINING_APP_ID <> @TRAINING_APP_ID)
		BEGIN	
			SELECT 1 AS DUPLICATION
		END
	ELSE
		BEGIN
			SELECT 0 AS DUPLICATION
		END
	
END

