

-- =============================================
-- Author     :	Gadriwala Muslim 
-- ALTER date: 17-01-2017
-- Description:	Modified SP as per Requirement
---02/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[Event_Logs_Get]
 @CMP_ID		NUMERIC(18, 0)
,@MODULE_NAME	NVARCHAR(100)
,@EVENT_FLAG	TINYINT
,@BATCH_ID		VARCHAR(100) = ''
,@IS_MANUAL		TINYINT = 0
AS
BEGIN
	
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	if @BATCH_ID <> ''
		SET @BATCH_ID = '%'+ @BATCH_ID
	

	DECLARE @TTL_NO_OF_EMPS AS NUMERIC(18,0)
	DECLARE @ERR_NO_OF_EMPS AS NUMERIC(18,0)
	SET @TTL_NO_OF_EMPS = 0
	SET @ERR_NO_OF_EMPS = 0
	
		IF @IS_MANUAL = 1
			BEGIN
							
			if @BATCH_ID <> ''
				BEGIN
				
				SELECT  @TTL_NO_OF_EMPS = ISNULL(COUNT(EMP_ID),0) FROM T0200_PRE_SALARY_DATA PSD WITH (NOLOCK) WHERE
				CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
				AND ISNULL(PSD.BATCH_ID,'') like @BATCH_ID
				AND PSD.CMP_ID = @CMP_ID
				
				SELECT  @ERR_NO_OF_EMPS = ISNULL(COUNT(EL.EMP_ID),0)  FROM EVENT_LOGS EL WITH (NOLOCK)
				INNER JOIN  T0200_PRE_SALARY_DATA PSD WITH (NOLOCK) ON EL.EMP_ID = PSD.EMP_ID 
				WHERE PSD.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
				EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)AND CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
				AND ISNULL(PSD.BATCH_ID,'') like  @BATCH_ID AND EL.SYSTEM_DATE >= PSD.SAL_GENERATE_DATE
				AND EL.ERROR_NAME <> ''
				
				SELECT   LOG_ID,PSD.CMP_ID,PSD.EMP_ID,PSD.LOGIN_ID,MODULE_NAME,ERROR_NAME,DESCRIPTION,EL.System_Date AS SYSTEM_DATE,EVENT_FLAG,REMARKS FROM EVENT_LOGS EL WITH (NOLOCK)
				INNER JOIN  T0200_PRE_SALARY_DATA PSD WITH (NOLOCK) ON EL.EMP_ID = PSD.EMP_ID
				WHERE PSD.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
				EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) AND CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
				AND ISNULL(PSD.BATCH_ID,'') like @BATCH_ID AND EL.SYSTEM_DATE >= PSD.SAL_GENERATE_DATE
				AND EL.ERROR_NAME <> ''
				ORDER BY EL.System_Date desc		
				END	
			ELSE
				BEGIN
					SELECT  @TTL_NO_OF_EMPS = ISNULL(COUNT(EMP_ID),0) FROM T0200_PRE_SALARY_DATA PSD WITH (NOLOCK) WHERE
					CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) AND PSD.CMP_ID = @CMP_ID	
					
					SELECT  @ERR_NO_OF_EMPS = ISNULL(COUNT(EL.EMP_ID),0)  FROM EVENT_LOGS EL WITH (NOLOCK)
					WHERE EL.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
					EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
					
					SELECT   LOG_ID,EL.CMP_ID,EL.EMP_ID,EL.LOGIN_ID,MODULE_NAME,ERROR_NAME,DESCRIPTION,EL.SYSTEM_DATE AS SYSTEM_DATE,EVENT_FLAG,REMARKS FROM EVENT_LOGS EL
					WHERE EL.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) 
					ORDER BY EL.SYSTEM_DATE DESC		
				
				END
				
				
				select 'Total process Record(s) : ' + cast(@TTL_NO_OF_EMPS as varchar(18)) + '<br> Success process Record(s) : ' +  cast((@TTL_NO_OF_EMPS - @ERR_NO_OF_EMPS) AS varchar(18))  + '<br> Error Record(s) : ' + cast((@ERR_NO_OF_EMPS) AS varchar(18)) as Salary_Msg
				
				
			END
		ELSE
			BEGIN
				if @BATCH_ID <> ''
					BEGIN
				
						SELECT  @TTL_NO_OF_EMPS = ISNULL(COUNT(EMP_ID),0) FROM T0200_PRE_SALARY_DATA_MONTHLY PSD WITH (NOLOCK) WHERE
						CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
						AND ISNULL(PSD.BATCH_ID,'') like @BATCH_ID AND PSD.CMP_ID = @CMP_ID 
						
						SELECT  @ERR_NO_OF_EMPS = ISNULL(COUNT(EL.EMP_ID),0)  FROM EVENT_LOGS EL
						INNER JOIN  T0200_PRE_SALARY_DATA_MONTHLY PSD WITH (NOLOCK) ON EL.EMP_ID = PSD.EMP_ID
						WHERE PSD.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
						EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) AND CONVERT(VARCHAR(10),PSD.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
						AND ISNULL(PSD.BATCH_ID,'') like @BATCH_ID AND EL.SYSTEM_DATE >= PSD.SAL_GENERATE_DATE
						AND EL.ERROR_NAME <> ''
						
						SELECT  LOG_ID,PSDM.CMP_ID,PSDM.EMP_ID,PSDM.LOGIN_ID,MODULE_NAME,ERROR_NAME,DESCRIPTION,EL.System_Date,EVENT_FLAG,REMARKS FROM EVENT_LOGS EL
						INNER JOIN  T0200_PRE_SALARY_DATA_MONTHLY PSDM WITH (NOLOCK) ON EL.EMP_ID = PSDM.EMP_ID
						WHERE PSDM.CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
						EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)AND CONVERT(VARCHAR(10),PSDM.SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
						AND ISNULL(PSDM.BATCH_ID,'') like   @BATCH_ID AND EL.SYSTEM_DATE <= PSDM.SAL_GENERATE_DATE
						AND EL.ERROR_NAME <> ''
						ORDER BY  EL.System_Date desc
					END
				ELSE
					BEGIN
							SELECT  @TTL_NO_OF_EMPS = ISNULL(COUNT(EMP_ID),0) FROM T0200_PRE_SALARY_DATA_MONTHLY WITH (NOLOCK) WHERE
							CONVERT(VARCHAR(10),SAL_GENERATE_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) AND CMP_ID = @CMP_ID	
							
							SELECT  @ERR_NO_OF_EMPS = ISNULL(COUNT(EMP_ID),0)  FROM EVENT_LOGS WITH (NOLOCK)
							WHERE   CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND 
							EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120)
							
							SELECT   LOG_ID,CMP_ID,EMP_ID,LOGIN_ID,MODULE_NAME,ERROR_NAME,DESCRIPTION,SYSTEM_DATE AS SYSTEM_DATE,EVENT_FLAG,REMARKS FROM EVENT_LOGS WITH (NOLOCK)
							WHERE CMP_ID=@CMP_ID AND MODULE_NAME=@MODULE_NAME AND EVENT_FLAG=@EVENT_FLAG AND CONVERT(VARCHAR(10),SYSTEM_DATE,120)=CONVERT(VARCHAR(10),GETDATE(),120) 
							ORDER BY SYSTEM_DATE DESC		
					END
					
				select 'Total process Record(s) : ' + cast(@TTL_NO_OF_EMPS as varchar(18)) + '<br> Success process Record(s) : ' +  cast((@TTL_NO_OF_EMPS - @ERR_NO_OF_EMPS) AS varchar(18))  + '<br> Error Record(s) : ' + cast((@ERR_NO_OF_EMPS) AS varchar(18)) as Salary_Msg
			END

END


