


-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,01092016>
-- DESCRIPTION:	<DESCRIPTION,,EXIT ANALYSIS GRAPH>
---19/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE  [dbo].[EXIT_ANALYSIS_GRAPH]
@CMP_ID NUMERIC(18,0),
@FROM_DATE DATETIME,
@TO_DATE DATETIME,
@BRANCH_ID NUMERIC(18,0),
@GRD_ID NUMERIC(18,0),
@DEPT_ID NUMERIC(18,0),
@GRAPH TINYINT
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	
	IF @BRANCH_ID = 0
		SET @BRANCH_ID = NULL
	IF @GRD_ID = 0
		SET @GRD_ID = NULL
	IF @DEPT_ID = 0
		SET @DEPT_ID = NULL
	IF @GRAPH = 1
		BEGIN	
			SELECT QE.QUESTION,SUM(EAR.RATING)/ COUNT(QE.QUEST_ID) AS AVG_RATING FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) INNER JOIN
			T0080_EMP_MASTER EM WITH (NOLOCK) ON EF.EMP_ID= EM.EMP_ID INNER JOIN 
			(
					SELECT ISNULL(IE.GRD_ID,0) AS GRD_ID,
						   ISNULL(IE.DEPT_ID,0) AS DEPT_ID,
						   ISNULL(IE.BRANCH_ID,0) AS BRANCH_ID,IE.EMP_ID   
					FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
					(
						SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.Emp_ID   FROM T0095_INCREMENT IE WITH (NOLOCK)  INNER JOIN
						(	
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
							WHERE  IE.CMP_ID = @CMP_ID GROUP BY IE.EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
						GROUP BY IE.EMP_ID
					)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
			)INC ON INC.EMP_ID = EM.EMP_ID
			INNER JOIN  T0200_QUESTION_EXIT_ANALYSIS_MASTER QE WITH (NOLOCK) ON QE.QUEST_ID = EF.QUESTION_ID
			INNER JOIN  T0040_EXIT_ANALYSIS_RATING EAR WITH (NOLOCK) ON EAR.RATING_ID = EF.ANSWER_RATE
			WHERE  EM.EMP_LEFT = 'Y'  AND 
				(EM.EMP_LEFT_DATE BETWEEN @FROM_DATE AND @TO_DATE) AND EF.CMP_ID = @CMP_ID 
				AND ISNULL(INC.GRD_ID,0) = ISNULL(@GRD_ID,ISNULL(INC.GRD_ID,0))	
				AND ISNULL(INC.DEPT_ID,0) = ISNULL(@DEPT_ID,ISNULL(INC.DEPT_ID,0))	
				AND ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
				AND (QE.QUESTION_TYPE = 4 or QE.Question_Type = 6)	
			GROUP BY QE.QUESTION
			
			SELECT ROW_NUMBER() OVER(PARTITION BY EM.ALPHA_EMP_CODE ORDER BY QE.QUESTION) AS ROW_ID,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME, 
			QE.QUESTION,EF.COMMENTS FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) INNER JOIN
			T0080_EMP_MASTER EM WITH (NOLOCK) ON EF.EMP_ID= EM.EMP_ID INNER JOIN 
			(
					SELECT ISNULL(IE.GRD_ID,0) AS GRD_ID,
						   ISNULL(IE.DEPT_ID,0) AS DEPT_ID,
						   ISNULL(IE.BRANCH_ID,0) AS BRANCH_ID,IE.EMP_ID   
					FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
					(
						SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.Emp_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)  INNER JOIN
						(	
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
							WHERE  IE.CMP_ID = @CMP_ID GROUP BY IE.EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
						GROUP BY IE.EMP_ID
					)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
					
			)INC ON INC.EMP_ID = EM.EMP_ID
			INNER JOIN  T0200_QUESTION_EXIT_ANALYSIS_MASTER QE WITH (NOLOCK) ON QE.QUEST_ID = EF.QUESTION_ID
			WHERE  EM.EMP_LEFT = 'Y'  AND 
				(EM.EMP_LEFT_DATE BETWEEN @FROM_DATE AND @TO_DATE) AND EF.CMP_ID = @CMP_ID 
				AND ISNULL(INC.GRD_ID,0) = ISNULL(@GRD_ID,ISNULL(INC.GRD_ID,0))	
				AND ISNULL(INC.DEPT_ID,0) = ISNULL(@DEPT_ID,ISNULL(INC.DEPT_ID,0))	
				AND ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
				AND (QE.QUESTION_TYPE = 2)	
			ORDER BY EM.Alpha_Emp_Code,ROW_ID
		END
	ELSE
		BEGIN
			SELECT EM.EMP_ID,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME,EM.EMP_LEFT_DATE,GM.GRD_NAME,BM.BRANCH_NAME,DM.DEPT_NAME,
			QE.QUEST_ID,QE.QUESTION,EAR.RATING FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) INNER JOIN
			T0080_EMP_MASTER EM WITH (NOLOCK) ON EF.EMP_ID= EM.EMP_ID INNER JOIN 
			(
					SELECT ISNULL(IE.GRD_ID,0) AS GRD_ID,
						   ISNULL(IE.DEPT_ID,0) AS DEPT_ID,
						   ISNULL(IE.BRANCH_ID,0) AS BRANCH_ID,IE.EMP_ID   
					FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
					(
						SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN
						(	
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
							WHERE  IE.CMP_ID = @CMP_ID GROUP BY IE.EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
						GROUP BY IE.EMP_ID
					)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
			)INC ON INC.EMP_ID = EF.EMP_ID
			INNER JOIN  T0200_QUESTION_EXIT_ANALYSIS_MASTER QE WITH (NOLOCK) ON QE.QUEST_ID = EF.QUESTION_ID
			LEFT OUTER JOIN T0040_EXIT_ANALYSIS_RATING EAR WITH (NOLOCK) ON EAR.RATING_ID = EF.ANSWER_RATE
			INNER JOIN T0040_GRADE_MASTER GM WITH (NOLOCK) ON GM.GRD_ID = INC.GRD_ID
			INNER JOIN T0030_BRANCH_MASTER BM WITH (NOLOCK) ON BM.BRANCH_ID = INC.BRANCH_ID
			LEFT OUTER JOIN T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON DM.DEPT_ID = INC.DEPT_ID
			WHERE  EM.EMP_LEFT = 'Y'  AND 
				(EM.EMP_LEFT_DATE BETWEEN @FROM_DATE AND @TO_DATE) AND EF.CMP_ID = @CMP_ID 
				AND ISNULL(INC.GRD_ID,0) = ISNULL(@GRD_ID,ISNULL(INC.GRD_ID,0))	
				AND ISNULL(INC.DEPT_ID,0) = ISNULL(@DEPT_ID,ISNULL(INC.DEPT_ID,0))	
				AND ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
				AND (QE.QUESTION_TYPE = 4 or QE.Question_Type = 6)	
			
			
			SELECT EM.EMP_ID,EM.EMP_FULL_NAME,EM.EMP_LEFT_DATE,GM.GRD_NAME,BM.BRANCH_NAME,DM.DEPT_NAME,
			QE.QUEST_ID,QE.QUESTION,EF.COMMENTS FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) INNER JOIN
			T0080_EMP_MASTER EM WITH (NOLOCK) ON EF.EMP_ID= EM.EMP_ID INNER JOIN 
			(
					SELECT ISNULL(IE.GRD_ID,0) AS GRD_ID,
						   ISNULL(IE.DEPT_ID,0) AS DEPT_ID,
						   ISNULL(IE.BRANCH_ID,0) AS BRANCH_ID,IE.EMP_ID   
					FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
					(
						SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.Emp_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)  INNER JOIN
						(	
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK) 
							WHERE  IE.CMP_ID = @CMP_ID GROUP BY IE.EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
						GROUP BY IE.EMP_ID
					)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
					
			)INC ON INC.EMP_ID = EM.EMP_ID
			INNER JOIN  T0200_QUESTION_EXIT_ANALYSIS_MASTER QE WITH (NOLOCK) ON QE.QUEST_ID = EF.QUESTION_ID
			LEFT OUTER JOIN  T0040_EXIT_ANALYSIS_RATING EAR  WITH (NOLOCK) ON EAR.RATING_ID = EF.ANSWER_RATE
			INNER JOIN T0040_GRADE_MASTER GM WITH (NOLOCK) ON GM.GRD_ID = INC.GRD_ID
			INNER JOIN T0030_BRANCH_MASTER BM WITH (NOLOCK) ON BM.BRANCH_ID = INC.BRANCH_ID
			LEFT OUTER JOIN T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON DM.DEPT_ID = INC.DEPT_ID
			WHERE  EM.EMP_LEFT = 'Y'  AND 
				(EM.EMP_LEFT_DATE BETWEEN @FROM_DATE AND @TO_DATE) AND EF.CMP_ID = @CMP_ID 
				AND ISNULL(INC.GRD_ID,0) = ISNULL(@GRD_ID,ISNULL(INC.GRD_ID,0))	
				AND ISNULL(INC.DEPT_ID,0) = ISNULL(@DEPT_ID,ISNULL(INC.DEPT_ID,0))	
				AND ISNULL(INC.BRANCH_ID,0) = ISNULL(@BRANCH_ID,ISNULL(INC.BRANCH_ID,0))
				AND (QE.QUESTION_TYPE = 2)	
			ORDER BY EM.ALPHA_EMP_CODE
		END
		
				
	
END

