

---23/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[Get_Bond_Grade_Wise]
	@Cmp_ID			numeric,
	@Emp_Id			numeric,
	@Subsidy_Flag   numeric = 0
AS 
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	Begin
		DECLARE @GRD_ID NUMERIC(5,0)
		DECLARE @CUR_BOND_ID NUMERIC(5,0)
		DECLARE @CUR_BOND_NAME VARCHAR(500)
		DECLARE @CUR_GRADE_DETAILS VARCHAR(500)
		
		CREATE TABLE #BOND_DETAILS
		(
			BOND_ID NUMERIC(5,0),
			BOND_NAME VARCHAR(500)
		)
		
		SELECT @GRD_ID = I.GRD_ID 
		FROM T0095_INCREMENT I WITH (NOLOCK) 
			INNER JOIN(	SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFETIVE_DATE,EMP_ID 
						FROM T0095_INCREMENT  WITH (NOLOCK)
						WHERE EMP_ID = @EMP_ID 
						GROUP BY EMP_ID
					   ) AS QRY ON I.EMP_ID = QRY.EMP_ID AND I.INCREMENT_EFFECTIVE_DATE = QRY.EFFETIVE_DATE 
		WHERE I.CMP_ID = @CMP_ID AND I.EMP_ID = @EMP_ID
		
		DECLARE CUR_GRADE_WISE_BOND CURSOR
		FOR SELECT BOND_ID,BOND_NAME,GRADE_DETAILS FROM T0040_BOND_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID --WHERE IS_GRADE_WISE = 1 AND IS_INTEREST_SUBSIDY_LIMIT = (CASE WHEN @SUBSIDY_FLAG = 1 THEN 1 ELSE 0 END)
		OPEN CUR_GRADE_WISE_BOND
		FETCH NEXT FROM CUR_GRADE_WISE_BOND INTO @CUR_BOND_ID,@CUR_BOND_NAME,@CUR_GRADE_DETAILS
		
		WHILE @@FETCH_STATUS = 0
			BEGIN
				IF CHARINDEX(CAST(@GRD_ID AS VARCHAR),@CUR_GRADE_DETAILS) > 0
					BEGIN
						INSERT INTO #BOND_DETAILS(BOND_ID,BOND_NAME)VALUES(@CUR_BOND_ID,@CUR_BOND_NAME)
					END
				FETCH NEXT FROM CUR_GRADE_WISE_BOND INTO @CUR_BOND_ID,@CUR_BOND_NAME,@CUR_GRADE_DETAILS
			END 
		CLOSE CUR_GRADE_WISE_BOND
		DEALLOCATE CUR_GRADE_WISE_BOND
		
		
		SELECT * FROM #BOND_DETAILS
	End
	

Return




