

---29/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[GET_INTERVIEW_QUESTION_ASSIGNED]
@CMP_ID NUMERIC(18,0),	
@EXIT_ID NUMERIC(18,0),
@EMP_ID NUMERIC(18,0),
@AUTO_ASSIGNED TINYINT = 0,
@INSERT_QUESTIONS TINYINT = 0,
@Group_Id numeric(18,0) = 0 --Added by Jaina 07-06-2018
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	
	 IF @EMP_ID	 = 0 
		SELECT @EMP_ID = ISNULL(EMP_ID,0) FROM T0200_EMP_EXITAPPLICATION WITH (NOLOCK) WHERE EXIT_ID = @EXIT_ID 
	
	 
	 DECLARE @DESIGN_ID NUMERIC(18,0)
	
	 SELECT @DESIGN_ID = ISNULL(IE.DESIG_ID,0) FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
	 (
		SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID  FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN
		(	
			SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
			WHERE IE.EMP_ID = @EMP_ID AND IE.CMP_ID = @CMP_ID GROUP BY IE.EMP_ID
		)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
	)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
	WHERE IE.EMP_ID = @EMP_ID		
	
	
	CREATE TABLE #QUEST_DESIG_WISE
	(
		QUEST_ID NUMERIC(18,0),
		QUESTION_TYPE  NUMERIC(18,0),
		DESIGN_ID NUMERIC(18,0),
		AUTO_ASSIGN TINYINT
	)
	
	DECLARE @CUR_QUEST_ID NUMERIC(18,0)
	DECLARE @CUR_QUEST_TYPE NUMERIC(18,0)
	DECLARE @CUR_STRDESIG_ID NVARCHAR(MAX)
	DECLARE @CUR_AUTO_ASSIGN TINYINT
	DECLARE @SPLITTER VARCHAR(10)
	
	SET @CUR_QUEST_ID = 0
	SET @CUR_QUEST_TYPE = 0
	SET @CUR_STRDESIG_ID = ''
	SET @CUR_AUTO_ASSIGN = 0	
	--select @DESIGN_ID
	
	

	DECLARE CURQUESTDESIGN CURSOR FOR 
		SELECT DISTINCT	QUEST_ID,QUESTION_TYPE,STRDESIG_ID,AUTOASSIGN 
		FROM	T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK)
		WHERE	CMP_ID  = @CMP_ID AND ISNULL(STRDESIG_ID,'') <>  ''
	OPEN CURQUESTDESIGN
		 FETCH NEXT FROM CURQUESTDESIGN INTO  @CUR_QUEST_ID,@CUR_QUEST_TYPE,@CUR_STRDESIG_ID,@CUR_AUTO_ASSIGN
		 WHILE @@FETCH_STATUS = 0
			BEGIN
						
				SET @SPLITTER = '#'
				IF CHARINDEX(',', @CUR_STRDESIG_ID) > 0
					SET @SPLITTER = ','
					
				
				INSERT	INTO #QUEST_DESIG_WISE(QUEST_ID,QUESTION_TYPE,DESIGN_ID,AUTO_ASSIGN)
				SELECT	@CUR_QUEST_ID,@CUR_QUEST_TYPE,DATA,@CUR_AUTO_ASSIGN 
				FROM	DBO.SPLIT(@CUR_STRDESIG_ID,@SPLITTER) 
				WHERE	Data <> '' AND  DATA = @DESIGN_ID    --Change by Jaina 08-12-2016
												
				FETCH NEXT FROM CURQUESTDESIGN INTO  @CUR_QUEST_ID,@CUR_QUEST_TYPE,@CUR_STRDESIG_ID,@CUR_AUTO_ASSIGN
			END
	CLOSE CURQUESTDESIGN
    DEALLOCATE CURQUESTDESIGN

	--Select * From #QUEST_DESIG_WISE
	--Select @INSERT_QUESTIONS,@AUTO_ASSIGNED
	--return
    
    IF @INSERT_QUESTIONS = 1
		BEGIN
			DECLARE @MAX_EXIT_INTV_ID AS NUMERIC(18,0)	
			SELECT @MAX_EXIT_INTV_ID = ISNULL(MAX(INTERVIEW_ID),0) + 1  FROM T0200_EXIT_INTERVIEW WITH (NOLOCK)
			IF @EXIT_ID = 0
				SET @EXIT_ID = NULL
			IF NOT EXISTS(SELECT 1 FROM T0200_EXIT_INTERVIEW WITH (NOLOCK) WHERE EMP_ID= @EMP_ID)
				BEGIN	
					INSERT INTO T0200_EXIT_INTERVIEW(INTERVIEW_ID,EMP_ID,EXIT_ID,QUESTION_ID,CMP_ID,POSTED_DATE,INT_STATUS,IS_VIEW,IS_Active)
					SELECT  (ROW_NUMBER() OVER (ORDER BY QEA.QUEST_ID) + @MAX_EXIT_INTV_ID) AS ROW_ID,@EMP_ID,@EXIT_ID,QEA.QUEST_ID,@CMP_ID,GETDATE(),'P',0,1 FROM #QUEST_DESIG_WISE QDW 
						 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON QDW.QUEST_ID = QEA.QUEST_ID
						 WHERE  QDW.AUTO_ASSIGN  = @AUTO_ASSIGNED	
				END
		END
	ELSE
		BEGIN
				IF @AUTO_ASSIGNED = 1
					BEGIN	
							
						SELECT ROW_NUMBER() OVER( ORDER BY QRY.QUEST_ID) AS ROW_ID,* 
						FROM (
								SELECT QEA.QUEST_ID,QEA.QUESTION,QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS 
								FROM #QUEST_DESIG_WISE QDW 
									 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON QDW.QUEST_ID = QEA.QUEST_ID
									 LEFT OUTER JOIN T0200_EXIT_INTERVIEW EI WITH (NOLOCK) ON EI.QUESTION_ID =QDW.QUEST_ID AND EI.EMP_ID = @EMP_ID	
									 LEFT OUTER JOIN T0040_Exit_Group_Master G WITH (NOLOCK) ON G.Group_Id = QEA.Group_Id
								WHERE  QDW.AUTO_ASSIGN  = @AUTO_ASSIGNED AND ISNULL(EI.QUESTION_ID,0) = 0 
									   and QEA.Group_Id = @Group_Id
								UNION
								SELECT QEA.QUEST_ID,QEA.QUESTION,QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS 
								FROM T0200_EXIT_INTERVIEW EV WITH (NOLOCK)
								 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON EV.QUESTION_ID = QEA.QUEST_ID 
								WHERE EV.EMP_ID = @EMP_ID AND IS_ACTIVE = 0 
									and QEA.Group_Id = @Group_Id
							)QRY
					END
				ELSE
					BEGIN
							
						--Added by Jaina 21-08-2018
						If Exists(Select 1 From T0200_Exit_Feedback WITH (NOLOCK) Where cmp_id = @Cmp_id and emp_id =@Emp_id and exit_id =@EXIT_ID and is_draft = 1)
							BEGIN
								
								SELECT DISTINCT ROW_NUMBER() OVER( ORDER BY QEA.QUEST_ID) AS ROW_ID,QEA.QUEST_ID,QEA.QUESTION,
									  QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS,F.Answer_rate,F.Comments
								FROM T0200_EXIT_INTERVIEW EV WITH (NOLOCK)
									 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON EV.QUESTION_ID = QEA.QUEST_ID 
									 LEFT OUTER JOIN T0040_Exit_Group_Master G WITH (NOLOCK) ON G.Group_Id = QEA.Group_Id
									 inner JOIN T0200_Exit_Feedback F WITH (NOLOCK) ON F.exit_id = EV.exit_id and F.emp_id = EV.emp_id and F.question_id =QEA.Quest_ID
								WHERE EV.EMP_ID = @EMP_ID  AND EV.IS_ACTIVE = 1 
									 and QEA.Group_Id = @Group_Id
							END
						else if Exists(Select 1 From T0200_Exit_Feedback WITH (NOLOCK) Where cmp_id = @Cmp_id and emp_id =@Emp_id and exit_id =@EXIT_ID and is_draft = 0)
							begin
								SELECT DISTINCT ROW_NUMBER() OVER( ORDER BY QEA.QUEST_ID) AS ROW_ID,QEA.QUEST_ID,QEA.QUESTION,
									  QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS,F.Answer_rate,F.Comments
								FROM T0200_EXIT_INTERVIEW EV WITH (NOLOCK)
									 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON EV.QUESTION_ID = QEA.QUEST_ID 
									 LEFT OUTER JOIN T0040_Exit_Group_Master G WITH (NOLOCK) ON G.Group_Id = QEA.Group_Id
									 inner JOIN T0200_Exit_Feedback F WITH (NOLOCK) ON F.exit_id = EV.exit_id and F.emp_id = EV.emp_id and F.question_id =QEA.Quest_ID
								WHERE EV.EMP_ID = @EMP_ID  AND EV.IS_ACTIVE = 1 
									 and QEA.Group_Id = @Group_Id
							end
						else
							begin								
								SELECT  ROW_NUMBER() OVER( ORDER BY QEA.QUEST_ID) AS ROW_ID,QEA.QUEST_ID,QEA.QUESTION,
									  QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS, 0 As Answer_rate, '' as Comments 
								FROM T0200_EXIT_INTERVIEW EV WITH (NOLOCK)
									 INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA WITH (NOLOCK) ON EV.QUESTION_ID = QEA.QUEST_ID 
									 LEFT OUTER JOIN T0040_Exit_Group_Master G WITH (NOLOCK) ON G.Group_Id = QEA.Group_Id
								WHERE EV.EMP_ID = @EMP_ID  AND EV.IS_ACTIVE = 1 
									 and QEA.Group_Id = @Group_Id and EV.cmp_id = @cmp_ID
							end
						--UNION
						--SELECT QEA.QUEST_ID,QEA.QUESTION,QEA.QUESTION_TYPE,QEA.QUESTION_OPTIONS FROM #QUEST_DESIG_WISE QDW 
						-- INNER JOIN T0200_QUESTION_EXIT_ANALYSIS_MASTER QEA ON QDW.QUEST_ID = QEA.QUEST_ID
						--WHERE  QDW.AUTO_ASSIGN  = @AUTO_ASSIGNED 
					END
		END
	
END


