-- =============================================
-- Author:		<Author,,GADRIWALA MUSLIM>
-- Create date: <Create Date,,15112016>
-- Description:	<Description,,GET HRMS TRAINING DETAILS FOR ESS HOME PAGE>
-- =============================================
CREATE PROCEDURE [dbo].[GET_HRMS_TRAINING_DETAILS_HOME_PAGE]
   @CMP_ID NUMERIC(18,0),  
   @BRANCH_ID NUMERIC(18,0)  ,
   @EMP_ID NUMERIC(18,0)  
AS
BEGIN
	
	
	DECLARE @FOR_DATE VARCHAR(50) 
	SET @FOR_DATE= CAST(GETDATE() AS VARCHAR(11))
/*****************************************************************************************************
									POSTED TRAINING STATUS
******************************************************************************************************/		    
	
				
	SELECT DISTINCT HTA.TRAINING_APR_ID,HTM.TRAINING_NAME,QRY.FROM_DATE AS TRAINING_DATE,CAST(DESCRIPTION AS VARCHAR(50)) AS DESCRIPTION1 
	FROM  T0120_HRMS_TRAINING_APPROVAL HTA WITH (NOLOCK)
	INNER JOIN T0130_HRMS_TRAINING_EMPLOYEE_DETAIL HTD WITH (NOLOCK) ON HTA.TRAINING_APR_ID = HTD.TRAINING_APR_ID
	INNER JOIN T0040_HRMS_TRAINING_MASTER HTM WITH (NOLOCK) ON HTA.TRAINING_ID = HTM.TRAINING_ID
	INNER JOIN (SELECT TRAINING_APP_ID,MIN(FROM_DATE)AS FROM_DATE,MAX(TO_DATE) AS TO_DATE  FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) 
	GROUP BY TRAINING_APP_ID
	) 
	QRY ON QRY.TRAINING_APP_ID = HTA.TRAINING_APP_ID
	WHERE HTD.EMP_ID = @EMP_ID AND HTA.APR_STATUS = 1 AND ISNULL(HTA.TRAINING_APR_ID,0) > 0
		AND EMP_TRAN_STATUS=1  and  QRY.FROM_DATE >=@FOR_DATE 
	ORDER BY QRY.FROM_DATE ASC
	
	/* OLD CODE..
		SELECT TRAINING_APR_ID,TRAINING_NAME,TRAINING_DATE,CAST(DESCRIPTION AS VARCHAR(50)) AS DESCRIPTION1 
						FROM DBO.V0130_HRMS_TRAINING_EMPLOYEE_DETAIL WHERE 
						EMP_ID=@EMP_ID AND APR_STATUS=1 AND ISNULL(TRAINING_APR_ID,0) > 0 
						AND TRAINING_DATE>= @FOR_DATE AND EMP_TRAN_STATUS=1   
						ORDER BY TRAINING_DATE ASC*/
/*****************************************************************************************************
									ALERTS TRAINING STATUS
******************************************************************************************************/			  
			
				
			SELECT DISTINCT TA.TRAINING_APR_ID,TRAINING_NAME,CAST(DESCRIPTION AS VARCHAR(50)) AS DESCRIPTION1,
					TA.COMMENTS,DEPT_NAME,QRY.FROM_DATE AS TRAINING_DATE, QRY.TO_DATE AS LAST_DATE 
			 FROM T0130_HRMS_TRAINING_ALERT TA WITH (NOLOCK)
			INNER JOIN T0080_EMP_MASTER  EM WITH (NOLOCK) ON TA.EMP_ID = EM.EMP_ID
			INNER JOIN T0120_HRMS_TRAINING_APPROVAL HTA WITH (NOLOCK) ON TA.TRAINING_APR_ID = HTA.TRAINING_APR_ID
			INNER JOIN T0040_HRMS_TRAINING_MASTER HTM WITH (NOLOCK) ON HTA.TRAINING_ID = HTM.TRAINING_ID
			INNER JOIN 
			(
				SELECT TRAINING_APP_ID,MIN(FROM_DATE) AS FROM_DATE,MAX(TO_DATE) AS TO_DATE FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) 
				GROUP BY TRAINING_APP_ID
			) QRY ON QRY.TRAINING_APP_ID = HTA.TRAINING_APP_ID
			INNER JOIN 
			(			
				SELECT I.EMP_ID,I.GRD_ID,I.DESIG_ID,I.DEPT_ID,I.BRANCH_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN 
				(	
					SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID , IE.EMP_ID FROM T0095_INCREMENT IE WITH (NOLOCK)  INNER JOIN
					(
						SELECT MAX(IE.INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE,IE.EMP_ID 
						FROM T0095_INCREMENT IE WITH (NOLOCK) 
						WHERE IE.EMP_ID = @EMP_ID
						GROUP BY IE.EMP_ID
					)INN_QRY ON INN_QRY.EMP_ID= IE.EMP_ID
					GROUP BY IE.EMP_ID
				)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID
			) INC ON INC.EMP_ID = TA.EMP_ID
			LEFT OUTER JOIN T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON DM.DEPT_ID = INC.DEPT_ID
			WHERE TA.EMP_ID = @EMP_ID AND HTA.APR_STATUS = 1
			AND ISNULL(TA.TRAINING_APR_ID,0) > 0 AND (@FOR_DATE BETWEEN DATEADD(DAY,-TA.ALERTS_START_DAYS,QRY.FROM_DATE) AND QRY.FROM_DATE)
			ORDER BY QRY.FROM_DATE ASC
	/* OLD CODE..
		SELECT DISTINCT TRAINING_APR_ID,TRAINING_NAME,CAST(DESCRIPTION AS VARCHAR(50)) AS DESCRIPTION1,
			COMMENTS,DEPT_NAME,TRAINING_DATE,TRAINING_END_DATE AS LAST_DATE 
			FROM DBO.V0130_HRMS_TRAINING_ALERT 
			WHERE EMP_ID=@EMP_ID AND APR_STATUS=1  
					AND ISNULL(TRAINING_APR_ID,0) <> 0 AND TRAINING_DATE>= @FOR_DATE AND 
					TRAINING_DATE<=DATEADD(DAY,ALERTS_START_DAYS,@FOR_DATE) ORDER BY TRAINING_DATE ASC*/
/*****************************************************************************************************
									POSTED TRAINING STATUS
******************************************************************************************************/		

		SELECT TOP 1 HTM.TRAINING_NAME, 
		CASE 
			WHEN APR_STATUS = 0 THEN 'Pending' 
			WHEN APR_STATUS = 1 THEN 'Approve' 
			ELSE 'Reject' END AS APR_STATUS_NAME
		FROM T0120_HRMS_TRAINING_APPROVAL HTA WITH (NOLOCK) 
		INNER JOIN T0130_HRMS_TRAINING_EMPLOYEE_DETAIL HTD WITH (NOLOCK) ON HTA.TRAINING_APR_ID = HTD.TRAINING_APR_ID
		INNER JOIN
		(
			SELECT TRAINING_APP_ID,MIN(FROM_DATE) as FROM_DATE,MAX(TO_DATE) as TO_DATE FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) 
			GROUP BY TRAINING_APP_ID
		) QRY ON QRY.TRAINING_APP_ID = HTA.TRAINING_APP_ID
		INNER JOIN T0040_HRMS_TRAINING_MASTER HTM ON HTA.TRAINING_ID = HTM.TRAINING_ID
		WHERE HTD.EMP_ID=@EMP_ID  AND APR_STATUS=1 AND QRY.FROM_DATE > @FOR_DATE  ORDER BY QRY.FROM_DATE DESC 
	
    
	/* OLD CODE..
	SELECT TOP 1 TRAINING_NAME,APR_STATUS_NAME FROM DBO.V0120_HRMS_TRAINING_APPROVAL 
	WHERE EMP_ID=@EMP_ID  AND APR_STATUS=1  ORDER BY TRAINING_DATE DESC */
		    
/*****************************************************************************************************
									POSTED TRAINING DETAILS
******************************************************************************************************/		    		
		SELECT A.TRAINING_ID,E.EMP_ID,T.TRAINING_NAME,ISNULL(A.TRAINING_CODE,A.TRAINING_APR_ID) TRAINING_CODE,
		(ISNULL(A.TRAINING_CODE,A.TRAINING_APR_ID) +' - '+T.TRAINING_NAME)TRAINING,QRY.FROM_DATE AS TRAINING_DATE,
		A.FACULTY AS 'Provider_Name',QRY.TO_DATE AS TRAINING_END_DATE,A.TRAINING_APR_ID 
		FROM DBO.T0130_HRMS_TRAINING_EMPLOYEE_DETAIL E WITH (NOLOCK)
			INNER JOIN DBO.T0120_HRMS_TRAINING_APPROVAL A WITH (NOLOCK) ON A.TRAINING_APR_ID= E.TRAINING_APR_ID
			INNER JOIN
				(
					SELECT  TRAINING_APP_ID,MIN(FROM_DATE)as FROM_DATE ,MAX(TO_DATE) as TO_DATE FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) 
					GROUP BY TRAINING_APP_ID
				) QRY ON QRY.TRAINING_APP_ID = A.TRAINING_APP_ID
			INNER JOIN DBO.T0150_EMP_TRAINING_INOUT_RECORD I WITH (NOLOCK) ON I.EMP_ID = E.EMP_ID  AND I.FOR_DATE BETWEEN QRY.FROM_DATE AND QRY.TO_DATE
			LEFT JOIN DBO.T0150_HRMS_TRAINING_ANSWERS ANS WITH (NOLOCK) ON ANS.EMP_ID=E.EMP_ID AND ANS.TRAINING_APR_ID = A.TRAINING_APR_ID
			INNER JOIN DBO.T0040_HRMS_TRAINING_MASTER T WITH (NOLOCK) ON T.TRAINING_ID = A.TRAINING_ID			
			CROSS JOIN DBO.T0150_HRMS_TRAINING_QUESTIONNAIRE Q WITH (NOLOCK) 		
		WHERE E.EMP_ID = @EMP_ID  AND (E.EMP_TRAN_STATUS = 1 OR E.EMP_TRAN_STATUS=4)  AND QRY.TO_DATE <= GETDATE()
				AND I.TRAINING_APR_ID IS NOT NULL AND ANS.TRAN_ANSWER_ID IS NULL 
			AND EXISTS (SELECT DATA FROM DBO.SPLIT(Q.TRAINING_ID, '#') PB WHERE PB.DATA=A.TRAINING_ID) AND Q.QUESTIONNIARE_TYPE =0
		GROUP BY A.TRAINING_ID,E.EMP_ID,T.TRAINING_NAME,ISNULL(A.TRAINING_CODE,A.TRAINING_APR_ID),
		(ISNULL(A.TRAINING_CODE,A.TRAINING_APR_ID) +' - '+T.TRAINING_NAME),QRY.From_date,A.FACULTY,QRY.To_date,A.TRAINING_APR_ID
		UNION
			select DISTINCT TM.TRAINING_ID,TI.EMP_ID,Training_name,'Induction' AS Training_Code,'' AS Training,
					Training_Date,TM.Emp_Name as 'Provider_Name',Training_Date AS TRAINING_END_DATE,TI.Training_Induction_ID as TRAINING_APR_ID 
					from T0110_Training_Induction_Details TI WITH (NOLOCK)
						inner join V0040_Training_Induction_Master TM on TI.Training_Induction_ID=TM.Training_Induction_ID
						inner join T0150_HRMS_TRAINING_Questionnaire TQ WITH (NOLOCK) on TQ.CMP_ID=TI.CMP_ID
						LEFT JOIN DBO.T0150_HRMS_TRAINING_ANSWERS ANS WITH (NOLOCK) ON ANS.EMP_ID=TI.EMP_ID and TM.Training_ID=ans.Training_id 
						--AND ANS.TRAINING_APR_ID = TI.Training_Induction_ID
			WHERE TI.EMP_ID=@EMP_ID AND EXISTS(SELECT DATA FROM DBO.SPLIT(TQ.Training_Id,'#')PB Where pb.Data=TM.Training_id) 
			and TQ.Questionniare_Type =3 AND ANS.TRAN_ANSWER_ID IS NULL
			ORDER BY TRAINING_ID		
		
END

