---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[GET_EMP_PRIVILEGE_ADMINRIGHTS]
	@CMP_ID AS numeric,
	@Privilege_ID AS numeric	
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	SELECT 1 FROM T0020_PRIVILEGE_MASTER PM WITH (NOLOCK) INNER JOIN T0050_PRIVILEGE_DETAILS PD WITH (NOLOCK) ON PM.PRIVILEGE_ID = PD.PRIVILAGE_ID
	INNER JOIN T0000_DEFAULT_FORM D WITH (NOLOCK) ON PD.FORM_ID = D.FORM_ID WHERE PAGE_FLAG NOT IN('EP','DE','ER') 
	AND PM.CMP_ID = @CMP_ID AND PM.PRIVILEGE_ID =@Privilege_ID AND (PD.Is_View + PD.is_delete+ PD.is_edit + PD.is_save ) >0
END
	




