


-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,18102016>
-- Description:	<Description,,GET LIST OF HOD , HOD & REPORTING MANAGER FOR HRMS >
---22/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[GET_HRMS_LIST_HOD_REPORTING]
	@CMP_ID AS NUMERIC(18,0),
	@TRAINING_APR_ID AS NUMERIC(18,0),
	@BRANCH_ID AS VARCHAR(MAX),
	@DEPT_ID AS VARCHAR(MAX),
	@GRADE_ID AS VARCHAR(MAX),
	@DESIGN_ID AS VARCHAR(MAX),
	@TYPE	TINYINT = 0
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	IF @BRANCH_ID = '' OR  @BRANCH_ID = '0'
		BEGIN
			SET @BRANCH_ID = NULL
		END
	IF @DEPT_ID = '' OR @DEPT_ID = '0'
		BEGIN
			SET @DEPT_ID = NULL
		END	
	IF @GRADE_ID = '' OR @GRADE_ID = '0'
		BEGIN
			SET @GRADE_ID = NULL
		END
	IF @DESIGN_ID = '' OR @DESIGN_ID  = '0'
		BEGIN
			SET @DESIGN_ID  = NULL
		END
	CREATE TABLE #HOD_LIST
	(
		EMP_ID NUMERIC(18,0),
		DEPT_ID NUMERIC(18,0),
		DEPT_NAME NVARCHAR(100),
		BRANCH_ID NUMERIC(18,0),
		BRANCH_NAME NVARCHAR(100),
		EMP_FULL_NAME_NEW NVARCHAR(200)
	)	
	
	IF @TYPE = 1
		BEGIN
		 		 
		SELECT  ALPHA_EMP_CODE+'-'+EMP_FULL_NAME AS EMP_FULL_NAME_NEW,I.DEPT_ID,DEPT_NAME,BRANCH_NAME,E.EMP_ID,E.ALPHA_EMP_CODE
			 FROM T0080_EMP_MASTER E WITH (NOLOCK)
				INNER JOIN 
				(
					SELECT I.EMP_ID,I.INCREMENT_ID,BRANCH_ID,DEPT_ID,DESIG_ID,I.GRD_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
						(
							SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
							(
								SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID 
								FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID
								GROUP BY EMP_ID
							)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = 	I.EMP_ID
							WHERE CMP_ID =  @CMP_ID
							GROUP BY I.EMP_ID	
						)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID
						
				) I ON I.EMP_ID  = E.EMP_ID 
				
			 LEFT JOIN T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = I.DEPT_ID 
		 	 LEFT JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON B.BRANCH_ID = I.BRANCH_ID 
			 INNER JOIN DBO.SPLIT(@BRANCH_ID,',') SB ON ISNULL(SB.DATA,ISNULL(I.BRANCH_ID,0)) = ISNULL(I.BRANCH_ID,0)
			 INNER JOIN DBO.SPLIT(@DEPT_ID,',') SD ON ISNULL(SD.DATA,ISNULL(I.DEPT_ID,0)) = ISNULL(I.DEPT_ID,0)
			 INNER JOIN DBO.SPLIT(@DESIGN_ID,',') SDS ON ISNULL(SDS.DATA,ISNULL(I.DESIG_ID,0)) = ISNULL(I.DESIG_ID,0)
			 INNER JOIN DBO.SPLIT(@GRADE_ID,',') SGS ON ISNULL(SGS.DATA,ISNULL(I.GRD_ID,0)) = ISNULL(I.GRD_ID,0)
			 INNER JOIN  (	 SELECT MAX(EMP_ID)AS EMP_ID,EMP_SUPERIOR FROM T0080_EMP_MASTER EM WITH (NOLOCK) WHERE CMP_ID =@CMP_ID
							 GROUP BY EM.EMP_SUPERIOR) QRY ON QRY.EMP_SUPERIOR = E.EMP_ID
			 WHERE E.EMP_LEFT='N' AND E.CMP_ID= @CMP_ID 							 
			 UNION
			 SELECT ALPHA_EMP_CODE+'-'+EMP_FULL_NAME AS EMP_FULL_NAME_NEW,I.DEPT_ID,DEPT_NAME,BRANCH_NAME,E.EMP_ID,E.ALPHA_EMP_CODE
			 FROM T0080_EMP_MASTER E WITH (NOLOCK)
				INNER JOIN 
				(
					SELECT I.EMP_ID,I.INCREMENT_ID,BRANCH_ID,DEPT_ID,DESIG_ID,I.GRD_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
						(
							SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
							(
								SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID 
								FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID
								GROUP BY EMP_ID
							)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = 	I.EMP_ID
							WHERE CMP_ID = @CMP_ID
							GROUP BY I.EMP_ID	
						)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID
						
				) I ON I.EMP_ID  = E.EMP_ID 
				
			 LEFT JOIN T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = I.DEPT_ID 
			 LEFT JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON B.BRANCH_ID = I.BRANCH_ID 
			 INNER JOIN DBO.SPLIT(@BRANCH_ID,',') SB ON ISNULL(SB.DATA,ISNULL(I.BRANCH_ID,0)) = ISNULL(I.BRANCH_ID,0)
			 INNER JOIN DBO.SPLIT(@DEPT_ID,',') SD ON ISNULL(SD.DATA,ISNULL(I.DEPT_ID,0)) = ISNULL(I.DEPT_ID,0)
			 INNER JOIN DBO.SPLIT(@DESIGN_ID,',') SDS ON ISNULL(SDS.DATA,ISNULL(I.DESIG_ID,0)) = ISNULL(I.DESIG_ID,0)
			 INNER JOIN DBO.SPLIT(@GRADE_ID,',') SGS ON ISNULL(SGS.DATA,ISNULL(I.GRD_ID,0)) = ISNULL(I.GRD_ID,0)
			 INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.DESIG_ID = I.DESIG_ID 
			 WHERE E.EMP_LEFT='N' AND E.CMP_ID=@CMP_ID AND (DEF_ID=1 OR IS_MAIN=1)
			 ORDER BY ALPHA_EMP_CODE ASC	 
		END
	ELSE
		BEGIN
			INSERT INTO #HOD_LIST(EMP_ID,EMP_FULL_NAME_NEW,DEPT_ID,DEPT_NAME,BRANCH_ID,BRANCH_NAME)
			SELECT DM.EMP_ID,(E.ALPHA_EMP_CODE + '-' + E.EMP_FULL_NAME),DM.DEPT_ID,D.DEPT_NAME,I.BRANCH_ID,B.BRANCH_NAME
			FROM T0095_DEPARTMENT_MANAGER DM WITH (NOLOCK) INNER JOIN
			(
					SELECT MAX(EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID FROM T0095_DEPARTMENT_MANAGER WITH (NOLOCK)
					WHERE CMP_ID = @CMP_ID 
					GROUP BY EMP_ID
			)QRY ON QRY.EFFECTIVE_DATE = DM.EFFECTIVE_DATE AND QRY.EMP_ID = DM.EMP_ID
			INNER JOIN  T0080_EMP_MASTER E WITH (NOLOCK) ON E.EMP_ID=DM.EMP_ID and E.Emp_Left='N'
			INNER JOIN 
			(
				SELECT I.EMP_ID,I.INCREMENT_ID,BRANCH_ID,DEPT_ID,DESIG_ID,I.Grd_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
					(
						SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
						(
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID 
							FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID
							GROUP BY EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = 	I.EMP_ID
						WHERE CMP_ID = @CMP_ID
						GROUP BY I.EMP_ID	
					)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID
					
			) I ON I.EMP_ID  = E.EMP_ID
			LEFT JOIN T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = DM.DEPT_ID  
			LEFT JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON B.BRANCH_ID = I.BRANCH_ID 
			INNER JOIN DBO.SPLIT(@BRANCH_ID,',') SB ON ISNULL(SB.DATA,ISNULL(I.BRANCH_ID,0)) = ISNULL(I.BRANCH_ID,0)
			INNER JOIN DBO.SPLIT(@DEPT_ID,',') SD ON ISNULL(SD.DATA,ISNULL(I.DEPT_ID,0)) = ISNULL(I.DEPT_ID,0)
			INNER JOIN DBO.SPLIT(@DESIGN_ID,',') SDS ON ISNULL(SDS.DATA,ISNULL(I.DESIG_ID,0)) = ISNULL(I.DESIG_ID,0)
			INNER JOIN DBO.SPLIT(@GRADE_ID,',') SGS ON ISNULL(SGS.DATA,ISNULL(I.GRD_ID,0)) = ISNULL(I.GRD_ID,0)
			WHERE DM.CMP_ID = @CMP_ID ORDER BY ALPHA_EMP_CODE ASC
			
		IF EXISTS(SELECT 1 FROM #HOD_LIST)
			BEGIN
					SELECT * FROM #HOD_LIST
			END
		ELSE
			BEGIN
			print 'k'
					SELECT E.EMP_ID,(ALPHA_EMP_CODE+'-'+EMP_FULL_NAME) AS EMP_FULL_NAME_NEW,I.DEPT_ID,D.DEPT_NAME,I.BRANCH_ID,B.BRANCH_NAME
					FROM T0080_EMP_MASTER E WITH (NOLOCK)
					INNER JOIN 
					(
						SELECT I.EMP_ID,I.INCREMENT_ID,BRANCH_ID,DEPT_ID,DESIG_ID,I.GRD_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
							(
								SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,I.EMP_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
								(
									SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,EMP_ID 
									FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @CMP_ID
									GROUP BY EMP_ID
								)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = I.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = 	I.EMP_ID
								WHERE CMP_ID = @CMP_ID
								GROUP BY I.EMP_ID	
							)QRY ON QRY.INCREMENT_ID = I.INCREMENT_ID
							
					) I ON I.EMP_ID  = E.EMP_ID
					LEFT JOIN T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = I.DEPT_ID 
					LEFT JOIN T0030_BRANCH_MASTER B WITH (NOLOCK)ON B.BRANCH_ID = I.BRANCH_ID 
					INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.DESIG_ID = I.DESIG_ID AND (DM.DEF_ID=1 OR IS_MAIN=1)
					INNER JOIN DBO.SPLIT(@BRANCH_ID,',') SB ON ISNULL(SB.DATA,ISNULL(I.BRANCH_ID,0)) = ISNULL(I.BRANCH_ID,0)
				    INNER JOIN DBO.SPLIT(@DEPT_ID,',') SD ON ISNULL(SD.DATA,ISNULL(I.DEPT_ID,0)) = ISNULL(I.DEPT_ID,0)
					INNER JOIN DBO.SPLIT(@DESIGN_ID,',') SDS ON ISNULL(SDS.DATA,ISNULL(I.DESIG_ID,0)) = ISNULL(I.DESIG_ID,0)
					INNER JOIN DBO.SPLIT(@GRADE_ID,',') SGS ON ISNULL(SGS.DATA,ISNULL(I.GRD_ID,0)) = ISNULL(I.GRD_ID,0)
					WHERE EMP_LEFT='N' AND E.CMP_ID=@CMP_ID 
					ORDER BY ALPHA_EMP_CODE ASC
			END
		END
		SELECT * FROM T0130_HRMS_TRAINING_ALERT WITH (NOLOCK) WHERE TRAINING_APR_ID=@TRAINING_APR_ID
END

