
CREATE PROCEDURE [dbo].[GET_MONTHLY_SHIFTCOUNT_RPT]
	 @CMP_ID		NUMERIC  
	,@FROM_DATE		DATETIME
	,@TO_DATE 		DATETIME
	,@BRANCH_ID		NUMERIC	
	,@GRD_ID 		NUMERIC
	,@TYPE_ID 		NUMERIC
	,@DEPT_ID 		NUMERIC
	,@DESIG_ID 		NUMERIC
	,@EMP_ID 		NUMERIC
	,@CONSTRAINT	VARCHAR(MAX)
	,@CAT_ID        NUMERIC = 0	
	,@SEGMENT_ID	NUMERIC = 0 
	,@VERTICAL		NUMERIC = 0 
	,@SUBVERTICAL	NUMERIC = 0 
	,@SUBBRANCH		NUMERIC = 0 

AS
Begin

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	
		CREATE TABLE #EMP_CONS 
		(
			EMP_ID	NUMERIC ,     
			BRANCH_ID NUMERIC,
			INCREMENT_ID NUMERIC 
		)
	
		EXEC SP_RPT_FILL_EMP_CONS	@CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRD_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID,@EMP_ID,
								@CONSTRAINT,0,0,0,0,0,0,0,0,0,0,0,0   

		DECLARE @TOTALDAYS AS NUMERIC,@COUNT AS NUMERIC = 1,@FRDATE AS DATETIME,@COUNTFOR NUMERIC = 1,
		@EMPCOUNT AS NUMERIC = 0,@Emid as numeric,@Stremp as Varchar(200)   

		SELECT @EMPCOUNT = COUNT(EMP_ID) FROM #EMP_CONS

		
		EXEC SP_ATTENDANCE_DASHBOARD_CLONE_04022023 @Cmp_ID=@CMP_ID,@FROM_DATE=@FROM_DATE,@TO_DATE=@TO_DATE,@Emp_Id=@Emid,@CONSTRAINT=@CONSTRAINT,@REPORT_FOR='' 


	drop table #EMP_CONS

	End

