

-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM >
-- CREATE DATE: <CREATE DATE,,30082016>
-- DESCRIPTION:	<DESCRIPTION,, EXIT INTERVIEW >
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[GET_EXIT_INTERVIEW]
@BRANCH_ID NUMERIC(18,0),
@CMP_ID NUMERIC(18,0),
@STRWHERE NVARCHAR(MAX),
@P_BRANCH AS VARCHAR(MAX)= '',
@ORDER_BY AS VARCHAR(250) = '' , 
@FLAG AS TINYINT = 0
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	
	-- QUESTION COUNT
	IF (@P_BRANCH = '' OR @P_BRANCH = '0') 
	SET @P_BRANCH = NULL;    
	
	--Select COUNT(distinct(Question_Id)) as quest from T0200_Exit_Interview where is_active = 1 and cmp_id =" & oclsuser.pCmp_Id & "and exit_id =" & exitid &
	
	DECLARE @STRSQL as NVARCHAR(MAX) = ''
	IF @FLAG = 1 
		BEGIN
			SET @STRSQL = 'SELECT DISTINCT E.EMP_ID,E.CMP_ID,E.BRANCH_ID,E.DEPT_ID,E.ALPHA_EMP_CODE,E.EMP_FULL_NAME,EA.RESIGNATION_DATE,
							EA.LAST_DATE,EA.EXIT_ID,D.DEPT_NAME,EA.SUP_ACK,E.EMP_LEFT
			FROM T0200_EMP_EXITAPPLICATION EA WITH (NOLOCK)  INNER JOIN
				  T0080_EMP_MASTER E WITH (NOLOCK) ON EA.EMP_ID = E.EMP_ID LEFT OUTER JOIN
				  T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = E.DEPT_ID INNER JOIN
				  T0300_EXIT_CLEARANCE_APPROVAL EC WITH (NOLOCK) ON EC.EMP_ID=EA.EMP_ID AND EC.EXIT_ID=EA.EXIT_ID
			WHERE EA.STATUS <> ''R'' AND ' + @STRWHERE +' AND E.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(15)) + ' ORDER BY ' + @ORDER_BY +''
			EXEC(@STRSQL)
		END
	ELSE
		BEGIN
				IF ISNULL(@P_BRANCH,'') <> ''
				BEGIN
					IF @STRWHERE <> ''
						BEGIN
							SET @STRSQL = 'SELECT EEA.*,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME,ISNULL(QUES_QRY.QUESTION_COUNTER,0) AS QUESTION_COUNTER,CASE WHEN ISNULL(FEED.EXIT_FEEDBACK_ID,0) > 0 THEN ''FEEDBACK GIVEN''ELSE ''PENDING'' END AS FEEDBACK_STATUS  FROM T0200_EMP_EXITAPPLICATION EEA WITH (NOLOCK)
							INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EEA.EMP_ID = EM.EMP_ID 
							INNER JOIN ( 
									SELECT IE.BRANCH_ID,IE.EMP_ID FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
									(
										SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.Emp_ID  FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN
										(	
											SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
											WHERE IE.CMP_ID = ' +  CAST(@CMP_ID AS VARCHAR(25))  + ' GROUP BY IE.EMP_ID
										)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID
										GROUP By IE.Emp_ID
									)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID And QRY.Emp_ID  =  IE.Emp_ID	
							)INC ON INC.EMP_ID = EEA.EMP_ID
							INNER JOIN DBO.SPLIT('''+ @P_BRANCH + ''',''#'') BR  ON BR.DATA = INC.BRANCH_ID
							LEFT OUTER JOIN 
							(
								SELECT COUNT(QUESTION_ID) AS QUESTION_COUNTER,EXIT_ID FROM T0200_EXIT_INTERVIEW EI WITH (NOLOCK) WHERE IS_ACTIVE = 1 
								AND EI.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + ' GROUP BY EXIT_ID
							) QUES_QRY ON QUES_QRY.EXIT_ID = EEA.EXIT_ID
							LEFT OUTER JOIN (
							 SELECT MAX(EXIT_FEEDBACK_ID) as EXIT_FEEDBACK_ID ,EXIT_ID FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) WHERE IS_DRAFT=0 GROUP BY EXIT_ID 
							) FEED ON  FEED.EXIT_ID = EEA.EXIT_ID
							WHERE EEA.STATUS = ''P'' AND EEA.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + @STRWHERE + ' ORDER BY ' + @ORDER_BY + ''
							EXEC(@STRSQL)
						END
					ELSE
						BEGIN
							
							SET @STRSQL = 'SELECT EEA.*,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME,ISNULL(QUES_QRY.QUESTION_COUNTER,0) AS QUESTION_COUNTER,CASE WHEN ISNULL(FEED.EXIT_FEEDBACK_ID,0) > 0 THEN ''FEEDBACK GIVEN'' ELSE ''PENDING'' END AS FEEDBACK_STATUS FROM T0200_EMP_EXITAPPLICATION EEA WITH (NOLOCK)
							INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EEA.EMP_ID = EM.EMP_ID
							INNER JOIN ( 
									SELECT IE.BRANCH_ID,IE.EMP_ID FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
									(
										SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.Emp_ID  FROM T0095_INCREMENT IE  WITH (NOLOCK) INNER JOIN
										(	
											SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK) 
											WHERE IE.CMP_ID = '+ CAST(@CMP_ID AS VARCHAR(25))  +' GROUP BY IE.EMP_ID
										)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID
										GROUP BY IE.Emp_ID
									)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID AND QRY.Emp_ID  =  IE.Emp_ID	
							)INC ON INC.EMP_ID = EEA.EMP_ID
							INNER JOIN DBO.SPLIT('''+ @P_BRANCH + ''' ,''#'') BR  ON BR.DATA = INC.BRANCH_ID
							LEFT OUTER JOIN 
							(
								SELECT COUNT(QUESTION_ID) AS QUESTION_COUNTER,EXIT_ID FROM T0200_EXIT_INTERVIEW EI WITH (NOLOCK) WHERE IS_ACTIVE = 1 
								AND EI.CMP_ID = '+ CAST(@CMP_ID AS VARCHAR(25)) +'  GROUP BY EXIT_ID
							) QUES_QRY ON QUES_QRY.EXIT_ID = EEA.EXIT_ID
							LEFT OUTER JOIN (
							 SELECT MAX(EXIT_FEEDBACK_ID) as EXIT_FEEDBACK_ID ,EXIT_ID FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) WHERE IS_DRAFT=0 GROUP BY EXIT_ID 
							) FEED ON  FEED.EXIT_ID = EEA.EXIT_ID
							WHERE EEA.STATUS = ''P'' AND EEA.CMP_ID = '+ CAST(@CMP_ID AS VARCHAR(25)) +' ORDER BY ' + @ORDER_BY + ''	
							print @STRSQL
							EXEC(@STRSQL)
						END
				END
			ELSE
				BEGIN
					IF @STRWHERE <> ''
						BEGIN
							SET @STRSQL = 'SELECT EEA.*,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME,ISNULL(QUES_QRY.QUESTION_COUNTER,0) AS QUESTION_COUNTER,CASE WHEN ISNULL(FEED.EXIT_FEEDBACK_ID,0) > 0 THEN ''FEEDBACK GIVEN''ELSE ''PENDING'' END AS FEEDBACK_STATUS FROM T0200_EMP_EXITAPPLICATION EEA WITH (NOLOCK)
							INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK)  ON EEA.EMP_ID = EM.EMP_ID
							LEFT OUTER JOIN 
							(
								SELECT COUNT(QUESTION_ID) AS QUESTION_COUNTER,EXIT_ID FROM T0200_EXIT_INTERVIEW EI WITH (NOLOCK) WHERE IS_ACTIVE = 1 
								AND EI.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + ' GROUP BY EXIT_ID
							) QUES_QRY ON QUES_QRY.EXIT_ID = EEA.EXIT_ID
							LEFT OUTER JOIN (
							 SELECT MAX(EXIT_FEEDBACK_ID) as EXIT_FEEDBACK_ID ,EXIT_ID FROM T0200_EXIT_FEEDBACK EF WITH (NOLOCK) WHERE IS_DRAFT=0 GROUP BY EXIT_ID 
							) FEED ON  FEED.EXIT_ID = EEA.EXIT_ID
							WHERE EEA.STATUS = ''P'' AND EEA.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + @STRWHERE + ' ORDER BY ' + @ORDER_BY + ''
							EXEC(@STRSQL)
							--ORDER BY EEA.EXIT_ID DESC
						END
					ELSE
						BEGIN
							SET @STRSQL = 'SELECT EEA.*,EM.ALPHA_EMP_CODE,EM.EMP_FULL_NAME,ISNULL(QUES_QRY.QUESTION_COUNTER,0) AS QUESTION_COUNTER,CASE WHEN ISNULL(FEED.EXIT_FEEDBACK_ID,0) > 0 THEN ''FEEBACK GIVEN'' ELSE ''PENDING'' END AS FEEDBACK_STATUS FROM T0200_EMP_EXITAPPLICATION EEA WITH (NOLOCK)
							INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EEA.EMP_ID = EM.EMP_ID
							LEFT OUTER JOIN 
							(
								SELECT COUNT(QUESTION_ID) AS QUESTION_COUNTER,EXIT_ID FROM T0200_EXIT_INTERVIEW EI WITH (NOLOCK) WHERE IS_ACTIVE = 1 
								AND EI.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + '  GROUP BY EXIT_ID
							) QUES_QRY ON QUES_QRY.EXIT_ID = EEA.EXIT_ID
							LEFT OUTER JOIN (
							 SELECT MAX(EXIT_FEEDBACK_ID) as EXIT_FEEDBACK_ID ,EXIT_ID FROM	 T0200_EXIT_FEEDBACK EF  WITH (NOLOCK) WHERE IS_DRAFT=0 GROUP BY EXIT_ID 
							) FEED ON  FEED.EXIT_ID = EEA.EXIT_ID
							WHERE EEA.STATUS = ''P'' AND EEA.CMP_ID = ' + CAST(@CMP_ID AS VARCHAR(25)) + ' ORDER BY ' + @ORDER_BY + '' --ORDER BY EEA.EXIT_ID DESC'
							EXEC(@STRSQL)
						END
				END	
				
		END
			
	
	
    -- INSERT STATEMENTS FOR PROCEDURE HERE
	
END

