

-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,15092016>
-- DESCRIPTION:	<DESCRIPTION,,GET LATEST VALUE FROM INCREMENT_TABLE>
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[GET_INCREMENT_DATA]
@CMP_ID NUMERIC(18,0),
@EMP_ID NUMERIC(18,0)
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

    -- INSERT STATEMENTS FOR PROCEDURE HERE
	SELECT ISNULL(IE.GRD_ID,0) AS GRD_ID,ISNULL(IE.DEPT_ID,0) AS DEPT_ID,
		   ISNULL(IE.BRANCH_ID,0) AS BRANCH_ID,IE.EMP_ID   
					FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN 
					(
						SELECT MAX(IE.INCREMENT_ID) AS INCREMENT_ID,IE.EMP_ID   FROM T0095_INCREMENT IE WITH (NOLOCK) INNER JOIN
						(	
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS EFFECTIVE_DATE,IE.EMP_ID  FROM T0095_INCREMENT IE WITH (NOLOCK)
							WHERE  IE.CMP_ID = @CMP_ID AND IE.EMP_ID = @EMP_ID GROUP BY IE.EMP_ID
						)INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = IE.INCREMENT_EFFECTIVE_DATE AND INNER_QRY.EMP_ID = IE.EMP_ID 
						GROUP BY IE.EMP_ID
					)QRY ON QRY.INCREMENT_ID  =  IE.INCREMENT_ID
END

