
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[GETDATAFORORGCHART]
@cmpid as numeric(18,0) =1,
@Dept_ID numeric(18,0)='3'
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

 --   ;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME) AS
	--(
	--	SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name
	--		FROM
	--			T0080_EMP_MASTER EM --ON EM.Emp_ID = RD.Emp_ID
	--			LEFT JOIN T0090_EMP_REPORTING_DETAIL RPT ON EM.Emp_ID = RPT.Emp_ID 
	--		LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE R_Emp_ID is null AND  EM.Cmp_ID =1 and EM.Emp_Left<> 'Y'
	--	UNION ALL
	--	SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name
	--		FROM	T0090_EMP_REPORTING_DETAIL RD 
	--			INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
	--			INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
	--			INNER JOIN T0080_EMP_MASTER EM ON EM.Emp_ID = RD.Emp_ID 
	--		WHERE (EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
	--)
	
	
	--SELECT q.*,EMP.Emp_Full_Name AS REPORTING_NAME FROM Q LEFT JOIN T0080_EMP_MASTER EMP ON EMP.Emp_ID = R_Emp_ID
	--;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME,Desig_Name,Desig_ID) AS
	--(
	--	SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
	--		FROM
	--			T0080_EMP_MASTER EM --ON EM.Emp_ID = RD.Emp_ID
	--			LEFT JOIN T0090_EMP_REPORTING_DETAIL RPT ON EM.Emp_ID = RPT.Emp_ID 
	--		LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE R_Emp_ID is null AND  EM.Cmp_ID =1 and EM.Emp_Left<> 'Y'
	--	UNION ALL
	--	SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
	--		FROM	T0090_EMP_REPORTING_DETAIL RD 
	--			INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
	--			INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
	--			INNER JOIN T0080_EMP_MASTER EM ON EM.Emp_ID = RD.Emp_ID 
	--			INNER JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE (EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
	--)
	
	
	--SELECT q.Emp_Full_NAME+'#'+q.Desig_Name,EMP.Emp_Full_Name+'#'+DESIG.Desig_Name AS REPORTING_NAME FROM Q
	--LEFT JOIN T0080_EMP_MASTER EMP ON EMP.Emp_ID = R_Emp_ID
	--LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EMP.Desig_Id 
	--INNER JOIN	T0040_DEPARTMENT_MASTER DMER on DMER.Dept_Id = EMP.Dept_ID  WHERE DMER.Dept_Id = 3	
	
	
	--;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME,Desig_Name,Desig_ID) AS
	--(
	--	SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
	--		FROM
	--			T0080_EMP_MASTER EM --ON EM.Emp_ID = RD.Emp_ID
	--			LEFT JOIN T0090_EMP_REPORTING_DETAIL RPT ON EM.Emp_ID = RPT.Emp_ID 
	--		LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE R_Emp_ID is null AND  EM.Cmp_ID =1 and EM.Emp_Left<> 'Y'
	--	UNION ALL
	--	SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
	--		FROM	T0090_EMP_REPORTING_DETAIL RD 
	--			INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
	--			INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
	--			INNER JOIN T0080_EMP_MASTER EM ON EM.Emp_ID = RD.Emp_ID 
	--			INNER JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE (EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
	--)
	
	
	--SELECT q.EMP_ID,q.R_EMP_ID, q.Emp_Full_NAME+'#'+q.Desig_Name,EMP.Emp_Full_Name+'#'+DESIG.Desig_Name AS REPORTING_NAME,DMER.Dept_Name FROM Q
	--LEFT JOIN T0080_EMP_MASTER EMP ON EMP.Emp_ID = R_Emp_ID
	--LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EMP.Desig_Id 
	--INNER JOIN	T0040_DEPARTMENT_MASTER DMER on DMER.Dept_Id = EMP.Dept_ID  WHERE DMER.Dept_Id = 3
	

	--;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME,Desig_Name,Desig_Id) AS
	--(
	--	SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,IE.Desig_Id
	--		FROM
	--			T0080_EMP_MASTER EM --ON EM.Emp_ID = RD.Emp_ID
	--			LEFT JOIN T0090_EMP_REPORTING_DETAIL RPT ON EM.Emp_ID = RPT.Emp_ID 
	--		LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		left join (SELECT I.EMP_ID,I.DESIG_ID,I.BRANCH_ID,I.Grd_ID,I.[Type_ID],I.Dept_ID
	--					FROM T0095_INCREMENT I INNER JOIN
	--							(SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,T0095_INCREMENT.EMP_ID
	--							 FROM T0095_INCREMENT Inner JOIN
	--									(
	--											SELECT MAX(Increment_Effective_Date) AS Increment_Effective_Date , EMP_ID 
	--											FROM T0095_INCREMENT WHERE CMP_ID = @cmpid GROUP BY EMP_ID
	--									) inqry on inqry.Emp_ID = T0095_INCREMENT.Emp_ID
	--							 WHERE CMP_ID =@cmpid
	--							 GROUP BY T0095_INCREMENT.EMP_ID) QRY ON I.EMP_ID = QRY.EMP_ID AND I.INCREMENT_ID = QRY.INCREMENT_ID
	--					where I.Cmp_ID=1
	--			)IE on ie.Emp_ID = EM.Emp_ID
	--		WHERE R_Emp_ID is null AND  EM.Cmp_ID =1 and EM.Emp_Left<> 'Y'
	--	UNION ALL
	--	SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
	--		FROM	T0090_EMP_REPORTING_DETAIL RD 
	--			INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
	--			INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
	--			INNER JOIN T0080_EMP_MASTER EM ON EM.Emp_ID = RD.Emp_ID 
	--			INNER JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = EM.Desig_Id
	--		WHERE (EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
	--)
	
	
	--SELECT q.Emp_Full_NAME+'#'+q.Desig_Name as ename,EMP.Emp_Full_Name+'#'+DESIG.Desig_Name AS Emp_Full_Name,q.Desig_Name,q.Desig_Id FROM Q
	--LEFT JOIN T0080_EMP_MASTER EMP ON EMP.Emp_ID = R_Emp_ID
	--LEFT JOIN T0040_DESIGNATION_MASTER DESIG ON DESIG.Desig_ID = q.Desig_Id 
	--INNER JOIN	T0040_DEPARTMENT_MASTER DMER on DMER.Dept_Id = EMP.Dept_ID--  WHERE DMER.Dept_Id in(@Dept_ID) and q.CMP_ID = @cmpid	
	
	
	;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME,Desig_Name,Desig_Id) AS
	(
		SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,IE.Desig_Id
			FROM
				T0080_EMP_MASTER EM WITH (NOLOCK) --ON EM.Emp_ID = RD.Emp_ID
				LEFT JOIN T0090_EMP_REPORTING_DETAIL RPT WITH (NOLOCK) ON EM.Emp_ID = RPT.Emp_ID 
			LEFT JOIN T0040_DESIGNATION_MASTER DESIG WITH (NOLOCK) ON DESIG.Desig_ID = EM.Desig_Id
			left join (SELECT I.EMP_ID,I.DESIG_ID,I.BRANCH_ID,I.Grd_ID,I.[Type_ID],I.Dept_ID
						FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
								(SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,T0095_INCREMENT.EMP_ID
								 FROM T0095_INCREMENT WITH (NOLOCK) Inner JOIN
										(
												SELECT MAX(Increment_Effective_Date) AS Increment_Effective_Date , EMP_ID 
												FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @cmpid GROUP BY EMP_ID
										) inqry on inqry.Emp_ID = T0095_INCREMENT.Emp_ID
								 WHERE CMP_ID =@cmpid
								 GROUP BY T0095_INCREMENT.EMP_ID) QRY ON I.EMP_ID = QRY.EMP_ID AND I.INCREMENT_ID = QRY.INCREMENT_ID
						where I.Cmp_ID=@cmpid
				)IE on ie.Emp_ID = EM.Emp_ID
			WHERE R_Emp_ID is null AND  EM.Cmp_ID =@cmpid and EM.Emp_Left<> 'Y'
		UNION ALL
		SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name,DESIG.Desig_Name,DESIG.Desig_ID
			FROM	T0090_EMP_REPORTING_DETAIL RD WITH (NOLOCK)
				INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
				INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
				INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EM.Emp_ID = RD.Emp_ID 
				INNER JOIN T0040_DESIGNATION_MASTER DESIG WITH (NOLOCK) ON DESIG.Desig_ID = EM.Desig_Id
			WHERE (EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
	)
	
	
	SELECT  q.Emp_Full_NAME+'#'+q.Desig_Name as ename,EMP.Emp_Full_Name+'#'+DESIG.Desig_Name AS Emp_Full_Name FROM Q
	LEFT JOIN T0080_EMP_MASTER EMP WITH (NOLOCK) ON EMP.Emp_ID = R_Emp_ID
	left join (SELECT I.EMP_ID,I.DESIG_ID,I.BRANCH_ID,I.Grd_ID,I.[Type_ID],I.Dept_ID
						FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN
								(SELECT MAX(INCREMENT_ID) AS INCREMENT_ID,T0095_INCREMENT.EMP_ID
								 FROM T0095_INCREMENT WITH (NOLOCK) Inner JOIN
										(
												SELECT MAX(Increment_Effective_Date) AS Increment_Effective_Date , EMP_ID 
												FROM T0095_INCREMENT WITH (NOLOCK) WHERE CMP_ID = @cmpid GROUP BY EMP_ID
										) inqry on inqry.Emp_ID = T0095_INCREMENT.Emp_ID
								 WHERE CMP_ID =@cmpid
								 GROUP BY T0095_INCREMENT.EMP_ID) QRY ON I.EMP_ID = QRY.EMP_ID AND I.INCREMENT_ID = QRY.INCREMENT_ID
						where I.Cmp_ID=@cmpid
				)IE on ie.Emp_ID = EMP.EMP_ID
	LEFT JOIN T0040_DESIGNATION_MASTER DESIG WITH (NOLOCK) ON DESIG.Desig_ID = IE.Desig_Id 
	INNER JOIN	T0040_DEPARTMENT_MASTER DMER WITH (NOLOCK) on DMER.Dept_Id = EMP.Dept_ID  WHERE  q.CMP_ID = @cmpid and DMER.Dept_Id in(@Dept_ID) 	
		--where R_EMP_ID = 81
END

