

-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,, 23122016>
-- DESCRIPTION:	<DESCRIPTION,, REPORTING MANAGER,DOWNLINE EMPLOYEE LIST>
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[HRMS_TRAINING_DOWNLINE_REPORTING_EMP]
	@CMP_ID NUMERIC(18,0),
	@EMP_ID NUMERIC(18,0)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


		CREATE TABLE #REPORTING_EMP_DOWN_LINE
		(
			EMP_ID NUMERIC(18,0),
			R_EMP_ID NUMERIC(18,0),
			REPORTING_TO NVARCHAR(250),
			ALPHA_EMP_CODE NVARCHAR(100),
			EMP_FULL_NAME NVARCHAR(250),
			EMP_FULL_NAME_NEW NVARCHAR(250),
			REPORTINGMANAGER NVARCHAR(250),
			DEPT_NAME NVARCHAR(150),
			DEPT_ID NUMERIC(18,0),
			DESIG_NAME NVARCHAR(150),
			DESIG_ID NUMERIC(18,0),
			BRANCH_ID NUMERIC(18,0),
			BRANCH_NAME NVARCHAR(150),
			EMP_LEFT CHAR(1),
			CMP_ID	NUMERIC(18,0)
		)
				INSERT INTO #REPORTING_EMP_DOWN_LINE(EMP_ID,R_EMP_ID,REPORTING_TO,ALPHA_EMP_CODE,EMP_FULL_NAME,EMP_FULL_NAME_NEW,REPORTINGMANAGER,DEPT_NAME,DEPT_ID,DESIG_ID,DESIG_NAME,BRANCH_ID,BRANCH_NAME,EMP_LEFT,CMP_ID)
				SELECT  E.EMP_ID, R_EMP_ID,REPORTING_TO,E.ALPHA_EMP_CODE,E.EMP_FULL_NAME,(E.ALPHA_EMP_CODE+'-'+E.EMP_FULL_NAME) AS EMP_FULL_NAME_NEW,
					(RM.ALPHA_EMP_CODE+'-'+RM.EMP_FULL_NAME) AS REPORTINGMANAGER,D.DEPT_NAME,INC.DEPT_ID,INC.DESIG_ID,DG.DESIG_NAME,
					INC.BRANCH_ID,B.BRANCH_NAME ,E.EMP_LEFT ,@CMP_ID
					FROM T0080_EMP_MASTER E WITH (NOLOCK)
					INNER JOIN T0095_INCREMENT INC WITH (NOLOCK) ON INC.EMP_ID = E.EMP_ID INNER JOIN
					(
						SELECT MAX(INC.INCREMENT_ID)AS INCREMENT_ID,INC.EMP_ID FROM T0095_INCREMENT INC  WITH (NOLOCK) INNER JOIN
						(
							SELECT MAX(INCREMENT_EFFECTIVE_DATE) AS  EFFECTIVE_DATE,IE.EMP_ID
							FROM T0095_INCREMENT IE WITH (NOLOCK) WHERE EMP_ID =@EMP_ID
							GROUP BY IE.EMP_ID 
						) INN_QRY ON INN_QRY.EFFECTIVE_DATE = INC.INCREMENT_EFFECTIVE_DATE AND INN_QRY.EMP_ID = INC.EMP_ID
						WHERE INC.EMP_ID = @EMP_ID	
						GROUP BY INC.EMP_ID
					)QRY ON QRY.EMP_ID = INC.EMP_ID AND QRY.INCREMENT_ID = INC.INCREMENT_ID
					LEFT JOIN T0030_BRANCH_MASTER B WITH (NOLOCK) ON B.BRANCH_ID = INC.BRANCH_ID 
					LEFT JOIN T0040_DEPARTMENT_MASTER D WITH (NOLOCK) ON D.DEPT_ID = INC.DEPT_ID 
					LEFT JOIN T0040_DESIGNATION_MASTER DG WITH (NOLOCK) ON DG.DESIG_ID = INC.DESIG_ID   
					LEFT JOIN (
						SELECT R_EMP_ID,ERD.EMP_ID,ERD.Reporting_To FROM T0090_EMP_REPORTING_DETAIL ERD WITH (NOLOCK) INNER JOIN
						  (	
							SELECT MAX(EFFECT_DATE) AS EFFECTIVE_DATE,EMP_ID FROM T0090_EMP_REPORTING_DETAIL WITH (NOLOCK)
							GROUP BY EMP_ID
						  )INNER_QRY ON INNER_QRY.EFFECTIVE_DATE = ERD.EFFECT_DATE AND INNER_QRY.EMP_ID = ERD.EMP_ID
					) R_QRY ON R_QRY.EMP_ID = E.EMP_ID
					LEFT JOIN T0080_EMP_MASTER RM WITH (NOLOCK) ON RM.EMP_ID = R_QRY.R_EMP_ID WHERE  E.EMP_ID = @EMP_ID AND E.CMP_ID= @CMP_ID
                     
				 INSERT INTO #REPORTING_EMP_DOWN_LINE(EMP_ID,R_EMP_ID,REPORTING_TO,ALPHA_EMP_CODE,EMP_FULL_NAME,EMP_FULL_NAME_NEW,REPORTINGMANAGER,DEPT_NAME,DEPT_ID,DESIG_ID,DESIG_NAME,BRANCH_ID,BRANCH_NAME,EMP_LEFT,CMP_ID)                     
                   EXEC GET_DOWNLINE_EMPLOYEES  @R_EMP_ID = @EMP_ID,@CMP_ID = @CMP_ID 
                   
                 SELECT  * FROM #REPORTING_EMP_DOWN_LINE 
END

