


---25/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[INSERT_DEVICE_EMP_INFORMATION]   
 @IP_ADDRESS_ID AS NUMERIC ,  
 @IP_ADDRESS AS VARCHAR(20),  
 @CARD_ID AS NUMERIC ,  
 @FINGER_ID AS NUMERIC ,  
 @FINGER_TEMPLATE AS VARCHAR(max),  
 @PWD AS NUMERIC ,  
 @PRIVILEDGE AS NUMERIC ,  
 @NAME AS VARCHAR(10),  
 @IS_FINGER INT --Added by Falak on 09-APR-2011  
   
AS  
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

 IF ISNULL(@PWD,0) = 0   
  SET @PWD = NULL  
   
 IF EXISTS(SELECT CARD_ID FROM DEVICE_EMP_INFORMATION WITH (NOLOCK) WHERE IP_ADDRESS_ID = @IP_ADDRESS_ID  
     AND CARD_ID = @CARD_ID AND FINGER_ID = @FINGER_ID and IS_FINGER = @IS_FINGER  )  
       
  BEGIN  
   UPDATE  DEVICE_EMP_INFORMATION  
   SET     IP_ADDRESS = @IP_ADDRESS,   
     FINGER_TEMPLATE = @FINGER_TEMPLATE,  
     PWD = @PWD,  
     PRIVILEDGE = @PRIVILEDGE,  
     NAME = @NAME--,  
     --IS_FINGER = @IS_FINGER   
   WHERE CARD_ID = @CARD_ID AND FINGER_ID = @FINGER_ID AND IP_ADDRESS_ID = @IP_ADDRESS_ID and IS_FINGER = @IS_FINGER  
  END  
 ELSE  
  BEGIN  
   INSERT INTO DEVICE_EMP_INFORMATION  
                         (IP_ADDRESS_ID, IP_ADDRESS, CARD_ID, FINGER_ID, FINGER_TEMPLATE,PWD,PRIVILEDGE,NAME,IS_FINGER)  
   VALUES     (@IP_ADDRESS_ID, @IP_ADDRESS, @CARD_ID, @FINGER_ID, @FINGER_TEMPLATE,@PWD,@PRIVILEDGE,@NAME,@IS_FINGER )  
  END  
   
   
   
 RETURN  
  
  
  

