  
  
-- =============================================  
-- Author:  <Author,,Zishanali Tailor>  
-- Create date: <Create Date,,04122013>  
-- Description: <Description,,Insert country in T0001_Location_Master>  
---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---  
-- =============================================  
CREATE PROCEDURE [dbo].[InsertDefaultLocations]   
AS  
  
SET NOCOUNT ON   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
SET ARITHABORT ON  
  
  
BEGIN  
  
  Declare @Location_Master Table(Loc_Id  numeric,Loc_Name varchar(MAX))  
  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (1, N'INDIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (2, N'PAKISTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (4, N'AFGHANISTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (5, N'ALAND ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (6, N'ALBANIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (7, N'ALGERIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (8, N'AMERICAN SAMOA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (9, N'ANDORRA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (10, N'ANGOLA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (11, N'ANGUILLA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (12, N'ANTARCTICA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (13, N'ANTIGUA AND BARBUDA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (14, N'ARGENTINA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (15, N'ARMENIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (16, N'ARUBA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (17, N'AUSTRALIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (18, N'AUSTRIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (19, N'AZERBAIJAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (20, N'BAHAMAS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (21, N'BAHRAIN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (22, N'BARBADOS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (23, N'BELARUS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (24, N'BELGIUM')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (25, N'BELIZE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (26, N'BENIN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (27, N'BERMUDA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (28, N'BHUTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (29, N'BOLIVIA, PLURINATIONAL STATE OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (30, N'BONAIRE, SINT EUSTATIUS AND SABA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (31, N'BOSNIA AND HERZEGOVINA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (32, N'BOTSWANA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (33, N'BOUVET ISLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (34, N'BRAZIL')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (35, N'BRITISH INDIAN OCEAN TERRITORY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (36, N'BRUNEI DARUSSALAM')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (37, N'BULGARIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (38, N'BURKINA FASO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (39, N'BURUNDI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (40, N'CAMBODIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (41, N'CAMEROON')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (42, N'CANADA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (43, N'CAPE VERDE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (44, N'CAYMAN ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (45, N'CENTRAL AFRICAN REPUBLIC')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (46, N'CHAD')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (47, N'CHILE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (48, N'CHINA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (49, N'CHRISTMAS ISLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (50, N'COCOS (KEELING) ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (51, N'COLOMBIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (52, N'COMOROS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (53, N'CONGO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (54, N'CONGO, THE DEMOCRATIC REPUBLIC OF THE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (55, N'COOK ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (56, N'COSTA RICA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (57, N'CÔTE D''IVOIRE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (58, N'CROATIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (59, N'CUBA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (60, N'CURAÇAO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (61, N'CYPRUS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (62, N'CZECH REPUBLIC')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (63, N'DENMARK')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (64, N'DJIBOUTI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (65, N'DOMINICA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (66, N'DOMINICAN REPUBLIC')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (67, N'ECUADOR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (68, N'EGYPT')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (69, N'EL SALVADOR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (70, N'EQUATORIAL GUINEA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (71, N'ERITREA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (72, N'ESTONIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (73, N'ETHIOPIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (74, N'FALKLAND ISLANDS (MALVINAS)')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (75, N'FAROE ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (76, N'FIJI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (77, N'FINLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (78, N'FRANCE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (79, N'FRENCH GUIANA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (80, N'FRENCH POLYNESIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (81, N'FRENCH SOUTHERN TERRITORIES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (82, N'GABON')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (83, N'GAMBIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (84, N'GEORGIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (85, N'GERMANY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (86, N'GHANA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (87, N'GIBRALTAR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (88, N'GREECE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (89, N'GREENLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (90, N'GRENADA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (91, N'GUADELOUPE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (92, N'GUAM')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (93, N'GUATEMALA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (94, N'GUERNSEY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (95, N'GUINEA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (96, N'GUINEA-BISSAU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (97, N'GUYANA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (98, N'HAITI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (99, N'HEARD ISLAND AND MCDONALD ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (100, N'HOLY SEE (VATICAN CITY STATE)')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (101, N'HONDURAS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (102, N'HONG KONG')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (103, N'HUNGARY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (104, N'ICELAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (105, N'INDONESIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (106, N'IRAN, ISLAMIC REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (107, N'IRAQ')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (108, N'IRELAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (109, N'ISLE OF MAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (110, N'ISRAEL')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (111, N'ITALY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (112, N'JAMAICA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (113, N'JAPAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (114, N'JERSEY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (115, N'JORDAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (116, N'KAZAKHSTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (117, N'KENYA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (118, N'KIRIBATI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (119, N'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (120, N'KOREA, REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (121, N'KUWAIT')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (122, N'KYRGYZSTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (123, N'LAO PEOPLE''S DEMOCRATIC REPUBLIC')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (124, N'LATVIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (125, N'LEBANON')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (126, N'LESOTHO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (127, N'LIBERIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (128, N'LIBYA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (129, N'LIECHTENSTEIN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (130, N'LITHUANIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (131, N'LUXEMBOURG')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (132, N'MACAO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (133, N'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (134, N'MADAGASCAR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (135, N'MALAWI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (136, N'MALAYSIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (137, N'MALDIVES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (138, N'MALI')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (139, N'MALTA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (140, N'MARSHALL ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (141, N'MARTINIQUE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (142, N'MAURITANIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (143, N'MAURITIUS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (144, N'MAYOTTE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (145, N'MEXICO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (146, N'MICRONESIA, FEDERATED STATES OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (147, N'MOLDOVA, REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (148, N'MONACO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (149, N'MONGOLIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (150, N'MONTENEGRO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (151, N'MONTSERRAT')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (152, N'MOROCCO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (153, N'MOZAMBIQUE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (154, N'MYANMAR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (155, N'NAMIBIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (156, N'NAURU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (157, N'NEPAL')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (158, N'NETHERLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (159, N'NEW CALEDONIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (160, N'NEW ZEALAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (161, N'NICARAGUA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (162, N'NIGER')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (163, N'NIGERIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (164, N'NIUE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (165, N'NORFOLK ISLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (166, N'NORTHERN MARIANA ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (167, N'NORWAY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (168, N'OMAN')    
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (170, N'PALAU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (171, N'PALESTINE, STATE OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (172, N'PANAMA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (173, N'PAPUA NEW GUINEA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (174, N'PARAGUAY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (175, N'PERU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (176, N'PHILIPPINES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (177, N'PITCAIRN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (178, N'POLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (179, N'PORTUGAL')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (180, N'PUERTO RICO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (181, N'QATAR')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (182, N'RÉUNION')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (183, N'ROMANIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (184, N'RUSSIAN FEDERATION')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (185, N'RWANDA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (186, N'SAINT BARTHÉLEMY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (187, N'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (188, N'SAINT KITTS AND NEVIS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (189, N'SAINT LUCIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (190, N'SAINT MARTIN (FRENCH PART)')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (191, N'SAINT PIERRE AND MIQUELON')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (192, N'SAINT VINCENT AND THE GRENADINES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (193, N'SAMOA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (194, N'SAN MARINO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (195, N'SAO TOME AND PRINCIPE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (196, N'SAUDI ARABIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (197, N'SENEGAL')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (198, N'SERBIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (199, N'SEYCHELLES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (200, N'SIERRA LEONE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (201, N'SINGAPORE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (202, N'SINT MAARTEN (DUTCH PART)')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (203, N'SLOVAKIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (204, N'SLOVENIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (205, N'SOLOMON ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (206, N'SOMALIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (207, N'SOUTH AFRICA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (208, N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (209, N'SOUTH SUDAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (210, N'SPAIN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (211, N'SRI LANKA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (212, N'SUDAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (213, N'SURINAME')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (214, N'SVALBARD AND JAN MAYEN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (215, N'SWAZILAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (216, N'SWEDEN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (217, N'SWITZERLAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (218, N'SYRIAN ARAB REPUBLIC')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (219, N'TAIWAN, PROVINCE OF CHINA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (220, N'TAJIKISTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (221, N'TANZANIA, UNITED REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (222, N'THAILAND')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (223, N'TIMOR-LESTE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (224, N'TOGO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (225, N'TOKELAU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (226, N'TONGA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (227, N'TRINIDAD AND TOBAGO')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (228, N'TUNISIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (229, N'TURKEY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (230, N'TURKMENISTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (231, N'TURKS AND CAICOS ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (232, N'TUVALU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (233, N'UGANDA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (234, N'UKRAINE')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (235, N'UNITED ARAB EMIRATES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (236, N'UNITED STATES')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (237, N'UNITED STATES MINOR OUTLYING ISLANDS')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (238, N'URUGUAY')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (239, N'UZBEKISTAN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (240, N'VANUATU')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (241, N'VENEZUELA, BOLIVARIAN REPUBLIC OF')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (242, N'VIET NAM')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (243, N'VIRGIN ISLANDS, BRITISH')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (244, N'VIRGIN ISLANDS, U.S.')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (245, N'WALLIS AND FUTUNA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (246, N'WESTERN SAHARA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (247, N'YEMEN')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (248, N'ZAMBIA')  
  INSERT INTO @Location_Master([Loc_ID], [Loc_name]) VALUES (249, N'ZIMBABWE')  
  
  
  --Select * from @Location_Master  
  
  DECLARE @Loc_Id numeric,   
    @Loc_Name varchar(100),  
    @message varchar(80)  
  
  DECLARE L_Master CURSOR FOR SELECT Loc_Id,Loc_Name FROM @Location_Master  
  OPEN L_Master  
  FETCH NEXT FROM L_Master INTO @Loc_Id, @Loc_Name  
  WHILE @@FETCH_STATUS = 0  
  BEGIN  
  
   DECLARE @CNT as int  
   DECLARE @Loc_id_max as int  
   SET @CNT = 0   
   SET @Loc_id_max = 0  
   SET @CNT = (Select COUNT(*) from T0001_LOCATION_MASTER WITH (NOLOCK) WHERE UPPER(Loc_name) = UPPER(@Loc_Name))  
   IF @CNT = 0  
   BEGIN  
		if not exists(select 1 from T0001_LOCATION_MASTER where Loc_name = @Loc_Name) 	
		BEGIN
			select @Loc_id_max = isnull(max(Loc_ID),0) + 1 from T0001_LOCATION_MASTER WITH (NOLOCK)  
			INSERT INTO T0001_LOCATION_MASTER (Loc_ID,Loc_name) VALUES (@Loc_id_max,@Loc_Name)  
		END
     END  
     FETCH NEXT FROM L_Master INTO @Loc_Id, @Loc_Name  
  END  
  
  CLOSE L_Master  
  DEALLOCATE L_Master  

  --Added by Sumit 25112015  
  Exec P0040_Country_Category_Master 0,0,'Developed','','I'  
  Exec P0040_Country_Category_Master 0,0,'Developing','','I'  
  Exec P0040_Country_Category_Master 0,0,'Other','','I'  
END  
  