



---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE     PROCEDURE [dbo].[INSERT_DEVICE_INOUT_DETAIL]
 @COMPANY_ID			NUMERIC  
,@CARD_ID				NUMERIC 
,@DATETIME				DATETIME
,@IP_ADDRESS			VARCHAR(20)
,@Reader_No				numeric = 0
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

Declare @IO_Tran_ID numeric
	IF NOT EXISTS  ( SELECT * FROM t9999_DEVICE_INOUT_DETAIL WITH (NOLOCK) WHERE Enroll_NO = @CARD_ID AND [IO_Datetime] = @DATETIME )
		BEGIN
			select @IO_Tran_ID = isnull(Max(IO_Tran_ID),0) + 1  from T9999_DEVICE_INOUT_DETAIL WITH (NOLOCK)

				INSERT INTO t9999_DEVICE_INOUT_DETAIL
				                      (IO_Tran_ID,Cmp_ID, Enroll_No, IO_Datetime, IP_ADDRESS)
				VALUES     (@IO_Tran_ID,@COMPANY_ID, @CARD_ID, @DATETIME, @IP_ADDRESS)
		END	
	RETURN 




