
---18/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0000_Home_Page_New]  
  @ver_update as tinyint = 0
AS  
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
BEGIN

DELETE FROM T0000_DEFAULT_FORM WHERE FORM_ID >= 9000 and Form_ID < 10000
--Module Name field Added By Mukti(16012015)for TMS project to hide salary related fields
  
insert into [dbo].[T0000_DEFAULT_FORM](Form_ID,Form_Name,Under_Form_ID,Sort_ID,Form_Type,Form_url,Form_Image_url,Is_Active_For_menu,Alias,[Module_name])values(9000,'Home Page Rights',-1,1000,1,'','',1,'Home Page Rights',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9001, N'TD_Home_Admin_1', -1, 1001, 1, '', '', 1, N'Admin Home Page',Null)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9002, N'TD_Home_Admin_2', 9001, 1002, 1, '', '', 1, N'Application Status',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9003, N'TD_Home_Admin_3', 9002, 1003, 1, '', '', 1, N'Leave Application',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9004, N'TD_Home_Admin_4', 9002, 1004, 1, '', '', 1, N'Leave Cancellation',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9005, N'TD_Home_Admin_5', 9002, 1005, 1, '', '', 1, N'Comp Off Application',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9013, N'TD_Home_Admin_13', 9002, 1006, 1, '', '', 1, N'Pre Comp Off Application',NULL)  --Added By Jaina 30-11-2015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9006, N'TD_Home_Admin_6', 9002, 1007, 1, '', '', 1, N'Loan Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9007, N'TD_Home_Admin_7', 9002, 1008, 1, '', '', 1, N'Claim Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9008, N'TD_Home_Admin_8', 9002, 1009, 1, '', '', 1, N'Attendance Regularization',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9009, N'TD_Home_Admin_9', 9002, 1010, 1, '', '', 1, N'Reimbursement Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9010, N'TD_Home_Admin_12', 9002, 1011, 1, '', '', 1, N'Asset Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9011, N'TD_Home_Admin_10', 9002, 1012, 1, '', '', 1, N'Travel Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9012, N'TD_Home_Admin_11', 9002, 1013, 1, '', '', 1, N'Travel Settlement Application','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9014, N'TD_Home_Admin_14', 9002, 1014, 1, '', '', 1, N'GatePass Application',NULL) --Admin  Gate Pass Application Count --  Ankit 06062016


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9021, N'TD_Home_Admin_21', 9001, 1021, 1, '', '', 1, N'Quick Data',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9022, N'TD_Home_Admin_22', 9021, 1022, 1, '', '', 1, N'Yearly Holiday','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9023, N'TD_Home_Admin_23', 9021, 1023, 1, '', '', 1, N'Active/InActive Users',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9024, N'TD_Home_Admin_24', 9021, 1024, 1, '', '', 1, N'Exit Application',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9025, N'TD_Home_Admin_25', 9021, 1025, 1, '', '', 0, N'Training Application','HRMS')  --Change bt Jaina 01-09-2016 (Set Inactive =0 )
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9026, N'TD_Home_Admin_26', 9021, 1026, 1, '', '', 1, N'Allowance/Reimbursement Application','PAYROLL') 
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9027, N'TD_Home_Admin_27', 9021, 1027, 1, '', '', 1, N'Company Consolidate Info',NULL) 
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9028, N'TD_Home_Admin_160', 9021, 1028, 1, '', '', 1, N'Scheme Not Assigned',NULL)   --Added by Jaina 28-11-2016

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9041, N'TD_Home_Admin_41', 9001, 1041, 1, '', '', 1, N'Graphics Report',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9042, N'TD_Home_Admin_42', 9041, 1042, 1, '', '', 1, N'Leave Reports',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9043, N'TD_Home_Admin_43', 9041, 1043, 1, '', '', 1, N'View Message',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9044, N'TD_Home_Admin_44', 9041, 1044, 1, '', '', 1, N'Yearly Salary','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9045, N'TD_Home_Admin_45', 9041, 1045, 1, '', '', 1, N'Whosoff',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9046, N'TD_Home_Admin_46', 9041, 1046, 1, '', '', 1, N'View Graphical Report',NULL) -- Added By Ali 21032014
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9047, N'TD_Home_Admin_47', 9041, 1046, 1, '', '', 1, N'Continues Absent',NULL) -- Added By Nilesh patel on 27112015


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9061, N'TD_Home_Admin_61', 9001, 1061, 1, '', '', 1, N'Other Details',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9067, N'TD_Home_Admin_87', 9061, 1062, 1, '', '', 1, N'Insurance Reminder','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9062, N'TD_Home_Admin_62', 9061, 1063, 1, '', '', 1, N'Appraisal Initiation','Appraisal1')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9063, N'TD_Home_Admin_63', 9061, 1064, 1, '', '', 1, N'Skill Evaluation Pending','Appraisal1')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9064, N'TD_Home_Admin_64', 9061, 1065, 1, '', '', 0, N'Training Feedback','HRMS')  --Change bY Jaina 01-09-2016 Set Inactive = 0 
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9066, N'TD_Home_Admin_70', 9061, 1066, 1, '', '', 1, N'Timesheet Approval','TIMESHEET') -- added by Prakash Patel on 28012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9068, N'TD_Home_Admin_67', 9061, 1067, 1, '', '', 1, N'IT Declaration','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9065, N'TD_Home_Admin_65', 9061, 1068, 1, '', '', 1, N'Survey',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9069, N'lnk_Today_Attendance', 9061, 1069, 1, '', '', 1, N'Todays Attendance',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9070, N'lnk_GPF_Interest', 9061, 1070, 1, '', '', 1, N'GPF Interest Credit Process','GPF')   --added jimit 14122015  --Change By Jaina 1-09-2016 (Module Name)


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9081, N'TD_Home_Admin_81', 9001, 1081, 1, '', '', 1, N'Deputation/Contract',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9082, N'TD_Home_Admin_82', 9081, 1082, 1, '', '', 1, N'Deputation Over',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9083, N'TD_Home_Admin_83', 9081, 1083, 1, '', '', 1, N'Contract Over',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9084, N'TD_Home_Admin_84', 9081, 1084, 1, '', '', 1, N'Probation Over',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9085, N'TD_Home_Admin_85', 9081, 1085, 1, '', '', 1, N'Optional Holiday',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9086, N'TD_Home_Admin_86', 9081, 1086, 1, '', '', 1, N'Asset Return','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9160, N'TD_Home_Admin_161', 9081, 1087, 1, '', '', 1, N'Retirement Over','PAYROLL')  --Added by Jaina 12-08-2017

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9101, N'TD_Home_Admin_101', 9001, 1101, 1, '', '', 1, N'Leave Data',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9102, N'TD_Home_Admin_102', 9101, 1102, 1, '', '', 1, N'Leave/OD Status',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9103, N'TD_Home_Admin_103', 9101, 1103, 1, '', '', 1, N'Leave Carry Forward',NULL)

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9121, N'TD_Home_Admin_121', 9001, 1121, 1, '', '', 1, N'Employees Detail',NULL)

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9131, N'TD_Home_Admin_131', 9001, 1131, 1, '', '', 1, N'Right Panel',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9132, N'TD_Home_Admin_132', 9131, 1132, 1, '', '', 1, N'Todays attendance',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9133, N'TD_Home_Admin_133', 9131, 1133, 1, '', '', 1, N'Birthday Reminder',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9134, N'TD_Home_Admin_134', 9131, 1134, 1, '', '', 1, N'Add & View Events',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9135, N'TD_Home_Admin_135', 9131, 1135, 1, '', '', 1, N'Message Board',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9136, N'TD_Home_Admin_136', 9131, 1136, 1, '', '', 1, N'New Joining Details',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9138, N'TD_Home_Admin_138', 9131, 1137, 1, '', '', 1, N'Wall Of Fame',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9137, N'TD_Home_Admin_137', 9131, 1138, 1, '', '', 1, N'Post Request',NULL)


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9151, N'TD_Home_Admin_151', 9001, 1151, 1, '', '', 1, N'Left Panel',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9152, N'TD_Home_Admin_152', 9151, 1152, 1, '', '', 1, N'Last Account Activity',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9153, N'TD_Home_Admin_153', 9151, 1153, 1, '', '', 1, N'Change password',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9154, N'TD_Home_Admin_154', 9151, 1154, 1, '', '', 1, N'Employee Search Preference',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9158, N'TD_Home_Admin_158', 9151, 1155, 1, '', '', 1, N'Change Company',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9155, N'TD_Home_Admin_155', 9151, 1156, 1, '', '', 1, N'Quick Links',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9156, N'TD_Home_Admin_156', 9151, 1157, 1, '', '', 1, N'Todays Thought',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9157, N'TD_Home_Admin_157', 9151, 1158, 1, '', '', 1, N'Info',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9159, N'TD_Home_Admin_159', 9021, 1159, 1, '', '', 1, N'Active/InActive Mobile Users','MOBILE')


---------------------------------------------------------------------------------------------------------------------- ESS SIDE -----------------------------------------------------------------------------------------------------------------------------

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9201, N'TD_Home_ESS_201', -1, 1201, 1, '', '', 1, N'ESS Home Page',NULL)

-- Commented by rohit for this code is Hide in Form as per guidance by sneha on 30102013
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9202, N'TD_Home_ESS_202', 9201, 1202, 1, '', '', 1, N'Central Panel')
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9203, N'TD_Home_ESS_203', 9202, 1203, 1, '', '', 1, N'Training Feedback')
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9204, N'TD_Home_ESS_204', 9202, 1204, 1, '', '', 1, N'Posted Training')   
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9205, N'TD_Home_ESS_205', 9202, 1205, 1, '', '', 1, N'HR Released Doc')   
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9206, N'TD_Home_ESS_206', 9202, 1206, 1, '', '', 1, N'Recruitment Pending List')
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9207, N'TD_Home_ESS_207', 9202, 1207, 1, '', '', 1, N'Training Team List to Approve')
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias]) VALUES (9208, N'TD_Home_ESS_208', 9202, 1208, 1, '', '', 1, N'Training Your List to Approve')
--Ended by rohit for this code is Hide in Form as per guidance by sneha on 30102013

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9220, N'TD_Home_ESS_220', 9201, 1220, 1, '', '', 1, N'Center panel',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9221, N'TD_Home_ESS_221', 9220, 1221, 1, '', '', 1, N'Policy Document',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9222, N'TD_Home_ESS_222', 9220, 1222, 1, '', '', 1, N'New Joining Details',NULL)


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9261, N'TD_Home_ESS_261', 9201, 1240, 1, '', '', 1, N'My Links',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9262, N'TD_Home_ESS_262', 9261, 1241, 1, '', '', 1, N'Attendance Regularization',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9263, N'TD_Home_ESS_263', 9261, 1242, 1, '', '', 1, N'My Team Member Details',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9341, N'TD_Home_ESS_290', 9261, 1243, 1, '', '', 1, N'Timesheet Approval','TIMESHEET') -- added by Prakash Patel on 28012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9265, N'TD_Home_ESS_265', 9261, 1244, 1, '', '', 1, N'Leave Approval',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9266, N'TD_Home_ESS_266', 9261, 1245, 1, '', '', 1, N'Leave Cancellation Approval',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9267, N'TD_Home_ESS_267', 9261, 1246, 1, '', '', 1, N'In Time :',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9268, N'TD_Home_ESS_268', 9261, 1247, 1, '', '', 1, N'Attendance Summary',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9269, N'TD_Home_ESS_269', 9261, 1248, 1, '', '', 1, N'Employee History',NULL)
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9270, N'TD_Home_ESS_270', 9261, 1249, 1, '', '', 1, N'Current Year Salary Detail','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9271, N'TD_Home_ESS_271', 9261, 1250, 1, '', '', 1, N'Holiday Calendar',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9272, N'TD_Home_ESS_272', 9261, 1251, 1, '', '', 1, N'Leave Balance',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9273, N'TD_Home_ESS_273', 9261, 1252, 1, '', '', 1, N'Probation Over',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9274, N'TD_Home_ESS_274', 9261, 1253, 1, '', '', 1, N'Comp Off Application',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9343, N'TD_Home_Ess_343', 9261, 1254, 1, '', '', 1, N'Pre Comp Off Application',NULL)  --Added By Jaina 30-11-2015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9275, N'TD_Home_ESS_275', 9261, 1255, 1, '', '', 1, N'exit interview scheduled',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9276, N'TD_Home_ESS_276', 9261, 1256, 1, '', '', 1, N'Exit Approval',NULL)  --Change By Jaina 18-07-2016      
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9277, N'TD_Home_ESS_277', 9261, 1257, 1, '', '', 1, N'Reimbursement Approval','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9278, N'TD_Home_ESS_278', 9261, 1258, 1, '', '', 1, N'Pending Document''s List',NULL) -- Added By Ali 21032014
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9279, N'TD_Home_ESS_279', 9261, 1259, 1, '', '', 1, N'View Graphical Report',NULL) -- Added By Ali 21032014
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9280, N'TD_Home_ESS_300', 9261, 1252, 1, '', '', 1, N'Trainee Over',NULL)	--Ankit 10022016


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9334, N'TD_Home_ESS_280', 9261, 1260, 1, '', '', 1, N'Loan Approval','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9333, N'TD_Home_ESS_285', 9261, 1261, 1, '', '', 1, N'About Me',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9335, N'TD_Home_ESS_286', 9261, 1262, 1, '', '', 1, N'Travel Approval','PAYROLL')  -- Added By Ramiz on 14112014
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9336, N'TD_Home_ESS_287', 9261, 1263, 1, '', '', 1, N'Travel Settlement Approval','PAYROLL') -- Added By Ramiz on 14112014
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9285, N'TD_Home_ESS_315', 9261, 1264, 1, '', '', 1, N'Claim Approvals','PAYROLL')--Added by sumit 02032015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9264, N'TD_Home_ESS_264', 9261, 1265, 1, '', '', 1, N'Warning Details',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9286, N'TD_Home_Ess_289', 9261, 1266, 1, '', '', 1, N'Whosoff',NULL)--Added by jimit 30072015

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9338, N'TD_Home_ESS_288', 9261, 1267, 1, '', '', 1, N'Training Feedback','HRMS')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9339, N'TD_Home_ESS_345', 9261, 1268, 1, '', '', 1, N'Fill Up The Survey Form',NULL)--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9340, N'TD_Home_ESS_341', 9261, 1269, 1, '', '', 1, N'Employee Rewards Initiated','HRMS')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9342, N'TD_Home_ESS_342', 9261, 1270, 1, '', '', 1, N'Change Request Approval',NULL)--added by Jaina 31-10-2015


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9281, N'TD_Home_ESS_281', 9261, 1281, 1, '', '', 1, N'Graph',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9282, N'TD_Home_ESS_282', 9281, 1282, 1, '', '', 1, N'Attendance Graph',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9283, N'TD_Home_ESS_283', 9281, 1283, 1, '', '', 1, N'Attendance Summary',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9284, N'TD_Home_ESS_284', 9281, 1284, 1, '', '', 1, N'Attendance Hourly Summary',NULL)


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9291, N'TD_Home_ESS_291', 9201, 1291, 1, '', '', 1, N'Appraisal','HRMS')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9292, N'TD_Home_ESS_292', 9291, 1292, 1, '', '', 1, N'Appraisal is invoked.','Appraisal1')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9293, N'TD_Home_ESS_293', 9291, 1293, 1, '', '', 1, N'Team Members Appraisal invoked.','Appraisal1')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9294, N'TD_Home_ESS_294', 9291, 1294, 1, '', '', 1, N'Self Assessment Form.','Appraisal2')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9295, N'TD_Home_ESS_295', 9291, 1295, 1, '', '', 1, N'Employee Assessment Pending','Appraisal2')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9296, N'TD_Home_ESS_296', 9291, 1296, 1, '', '', 1, N'Employee For Group Head Approval','Appraisal2')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9297, N'TD_Home_ESS_333', 9291, 1297, 1, '', '', 1, N'Appraisal Alert','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9298, N'TD_Home_ESS_334', 9291, 1298,1,'','',1,N'Approve KPI Rating','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9299, N'TD_Home_ESS_335', 9291, 1299,1,'','',1,N'Employee Reviewed Alert','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES  (9300, N'TD_Home_ESS_336', 9291, 1300,1,'','',1,N'Employee Approved Alert','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9301,N'TD_Home_ESS_337',9291,1301,1,'','',1,N'KPI For Review','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9302,N'TD_Home_ESS_338',9291,1302,1,'','',1,N'KPI Objective','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9303,N'TD_Home_ESS_339',9291,1303,1,'','',1,N'KPI Objective NewEmployee','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9304,N'TD_Home_ESS_340',9291,1304,1,'','',1,N'KPI Objective Notify NewEmployee','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9305,N'TD_Home_ESS_344',9291,1305,1,'','',1,N'KPI Appraisal For Review','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9306,N'TD_Home_ESS_346',9291,1306,1,'','',1,N'KPI Objective for Employee Review','Appraisal3')	--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9307,N'TD_Home_ESS_347',9291,1307,1,'','',1,N'KPI Objective Reviewed by Employee ','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9308,N'TD_Home_ESS_348',9291,1308,1,'','',1,N'KPI Objective Approved by Employee ','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9309,N'TD_Home_ESS_349',9291,1309,1,'','',1,N'KPI Objective for Superior Review','Appraisal3')--added by sneha on 24012015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9365,N'TD_Home_ESS_351',9291,1310,1,'','',1,N'Balance Score Card Setting','Appraisal3')--added by sneha on 02082016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9366,N'TD_Home_ESS_352',9291,1310,1,'','',1,N'Balance Score Card Evaluation','Appraisal3')--added by sneha on 02082016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9367,N'TD_Home_ESS_353',9291,1310,1,'','',1,N'Development Planning Template','Appraisal3')--added by sneha on 10082016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9368,N'TD_Home_ESS_354',9291,1310,1,'','',1,N'Performance Improvement Planning Template','Appraisal3')--added by sneha on 10082016

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9311, N'TD_Home_ESS_301', 9201, 1311, 1, '', '', 1, N'Right Panel',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9312, N'TD_Home_ESS_302', 9311, 1312, 1, '', '', 1, N'Post Request',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9313, N'TD_Home_ESS_303', 9311, 1313, 1, '', '', 1, N'Birthday Reminder',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9314, N'TD_Home_ESS_304', 9311, 1314, 1, '', '', 1, N'Add & View Events',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9315, N'TD_Home_ESS_305', 9311, 1315, 1, '', '', 1, N'Message Board',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9316, N'TD_Home_ESS_306', 9311, 1316, 1, '', '', 1, N'Wall Of Fame',NULL)--added by sneha on 24012015

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9321, N'TD_Home_ESS_321', 9201, 1321, 1, '', '', 1, N'Left Panel',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9322, N'TD_Home_ESS_322', 9321, 1322, 1, '', '', 1, N'Last Login Activity',NULL)
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9323, N'TD_Home_ESS_323', 9321, 1323, 1, '', '', 1, N'Edit Profile | Change Password',NULL)
-- Comment by nilesh patel on 13052016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9324, N'TD_Home_ESS_324', 9321, 1326, 1, '', '', 1, N'Employee Search Preference',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9325, N'TD_Home_ESS_325', 9321, 1327, 1, '', '', 1, N'Quick Links',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9326, N'TD_Home_ESS_326', 9325, 1328, 1, '', '', 1, N'Attendance regularization Request',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9327, N'TD_Home_ESS_327', 9325, 1329, 1, '', '', 1, N'Employee History',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9328, N'TD_Home_ESS_328', 9325, 1330, 1, '', '', 1, N'Salary Slip','PAYROLL')
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9329, N'TD_Home_ESS_329', 9325, 1331, 1, '', '', 1, N'leave Application Status',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9337, N'lnk_View_Img_Vid', 9325, 1331, 1, '', '', 1, N'View Images and Video',NULL)  --added jimit 14122015
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9816, N'tr_Attendance_Calendar', 9325, 1331, 1, '', '', 1, N'Attendance Calendar',NULL)--Added by Gadriwala Muslim 12092016

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9330, N'TD_Home_ESS_330', 9321, 1331, 1, '', '', 1, N'Todays Thought',NULL)
-- Comment by nilesh patel on 13052016 Start
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9331, N'TD_Home_ESS_331', 9323, 1324, 1, '', '', 1, N'Edit Profile',NULL)
--INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9332, N'TD_Home_ESS_332', 9323, 1325, 1, '', '', 1, N'Change Password',NULL)
-- Comment by nilesh patel on 13052016 End
--Change by nilesh patel on 13052016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9331, N'TD_Home_ESS_331', 9325, 1324, 1, '', '', 1, N'Edit Profile',NULL)
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9332, N'TD_Home_ESS_332', 9325, 1325, 1, '', '', 1, N'Change Password',NULL)

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9344, N'TD_Home_ESS_308', 9261, 1252, 1, '', '', 1, N'GatePass Approval',NULL)	-- ESS Gate Pass Application Count --  Ankit 06062016

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9345, N'TD_Home_ESS_309', 9261, 1253, 1, '', '', 1, N'Exit Clearance Detail',NULL)	-- Exit Clearance Approval --Added By Jaina 18-07-2016
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9346, N'TD_Home_Admin_162', 9081, 1088, 1, '', '', 1, N'Document Expiry Reminder','PAYROLL')  	--Added By Mukti(17012018)

INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9347, N'TD_Home_ESS_313', 9261, 1254, 1, '', '', 1, N'Overtime Approval',NULL)	--Added By Jimit 07082018


INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9348, N'Card_001', 9220, 1400, 1, '', '', 1, N'Employee & Team',NULL)	--Added By binal 23122019
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9349, N'Card_002', 9220, 1401, 1, '', '', 1, N'Attendance & Leave',NULL)	--Added By binal 23122019
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9350, N'Card_003', 9220, 1402, 1, '', '', 1, N'Salary',NULL)	--Added By binal 23122019
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9351, N'Card_004', 9220, 1403, 1, '', '', 1, N'Reports',NULL)	--Added By binal 23122019



INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9352, N'TD_Home_ESS_Marriage_307', 9932, 1317, 1, '', '', 1, N'Marriage Anniversary',NULL) --Added By binal 02012020
INSERT INTO [dbo].[T0000_DEFAULT_FORM]([Form_ID], [Form_Name], [Under_Form_ID], [Sort_ID], [Form_Type], [Form_url], [Form_Image_url], [Is_Active_For_menu], [Alias],[Module_name]) VALUES (9353, N'TD_Home_ESS_Work_308', 9933, 1318, 1, '', '', 1, N'Work Anniversary',NULL) --Added By binal 02012020



If (exists(Select 1 from [dbo].[T0000_DEFAULT_FORM] where form_name='TD_Home_ESS_270' and alias='Current Year Salary Detail'))
Begin

Delete [dbo].[T0000_DEFAULT_FORM] where form_name='TD_Home_ESS_270' and alias='Current Year Salary Detail'
end


End
