



---19/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0010_COMPANY_PF_ESIC_Display]
	 @CMP_ID		NUMERIC 
	,@CMP_NAME		VARCHAR(100)
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON	 
		 
		 Select Is_PF_APPLICABLE,Is_ESIC_APPLICABLE from T0010_COMPANY_MASTER WITH (NOLOCK) where  Cmp_ID=@Cmp_ID 
		 
		
	RETURN




