

-- =============================================
-- Author:		<Ripal Patel>
-- ALTER date: <27-Dec-2012>
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0040_HRMS_Appraisal_SOL_Master]
	@SOL_ID				NUMERIC(18,0) OUTPUT,
	@SOL_CMPID			NUMERIC(18,0),
	@SOL				VARCHAR(400),
	@SOL_ISACTIVE		TINYINT,
	@TRAN_TYPE			VARCHAR(1),
	@USER_ID			NUMERIC(18,0)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
    
	IF @TRAN_TYPE ='I'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_HRMS_APPRAISAL_SOL_MASTER WITH (NOLOCK)
									WHERE SOL = @SOL AND SOL_CMPID = @SOL_CMPID)
			BEGIN
			    SET	@SOL_ID = 0
				RETURN
			END
			SELECT @SOL_ID = ISNULL(MAX(SOL_ID),0)+1 FROM T0040_HRMS_APPRAISAL_SOL_MASTER WITH (NOLOCK)
			INSERT INTO T0040_HRMS_APPRAISAL_SOL_MASTER
					   (SOL_ID
					   ,SOL_CMPID
					   ,SOL
					   ,SOL_ISACTIVE
					   ,SOL_CREATEDBY
					   ,SOL_CREATEDDATE)
				 VALUES
					   (@SOL_ID
					   ,@SOL_CMPID
					   ,@SOL
					   ,@SOL_ISACTIVE
					   ,@USER_ID
					   ,GETDATE())
		END
	ELSE IF @TRAN_TYPE ='U'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_HRMS_APPRAISAL_SOL_MASTER WITH (NOLOCK)
									WHERE SOL = @SOL AND SOL_CMPID = @SOL_CMPID AND SOL_ID <> @SOL_ID)
			BEGIN
			    SET	@SOL_ID = 0
				RETURN
			END
				UPDATE T0040_HRMS_APPRAISAL_SOL_MASTER
				   SET SOL = @SOL
					  ,SOL_ISACTIVE = @SOL_ISACTIVE
					  ,SOL_MODIFYBY = @USER_ID
					  ,SOL_MODIFYDATE = GETDATE()
				 WHERE SOL_ID = @SOL_ID AND SOL_CMPID = @SOL_CMPID
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
			IF NOT EXISTS(SELECT 1 FROM T0090_HRMS_APPRAISAL_EMP_SOLASSESSMENTDTL WITH (NOLOCK) WHERE FK_SOL = @SOL_ID)
				BEGIN
					DELETE FROM T0040_HRMS_APPRAISAL_SOL_MASTER
						WHERE SOL_ID = @SOL_ID AND SOL_CMPID = @SOL_CMPID
				END
			ELSE
				BEGIN
					SET	@SOL_ID = 0
					RETURN
				END			
		END
END



