---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_HRMS_Goal_Master]
  @GOAL_ID	NUMERIC(18,0) OUTPUT
 ,@GOAL_TITLE	NVARCHAR(100)
 ,@CMP_ID	NUMERIC(18,0)
 ,@LOGIN_ID	NUMERIC(18,0)
 ,@DESCRIPTION	NVARCHAR(500)
 ,@START_DATE	DATETIME
 ,@END_DATE	DATETIME
 ,@TRAN_TYPE AS CHAR(1)           
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	IF @CMP_ID = 0 
	 SET @CMP_ID  = NULL
	IF @LOGIN_ID=0
	 SET @LOGIN_ID =NULL
	 
	IF @START_DATE = ''  
		SET @START_DATE = NULL  
	IF @END_DATE = ''  
		SET @END_DATE	= NULL    
	IF UPPER(@TRAN_TYPE) ='I' 
		BEGIN
			IF EXISTS (SELECT GOAL_ID  FROM DBO.T0040_HRMS_GOAL_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND GOAL_TITLE=@GOAL_TITLE AND START_DATE=@START_DATE AND END_DATE=@END_DATE)
				BEGIN
					SET @GOAL_ID=0
					RETURN 
				END
			SELECT @GOAL_ID = ISNULL(MAX(GOAL_ID),0) + 1 FROM DBO.T0040_HRMS_GOAL_MASTER WITH (NOLOCK)						
				
			INSERT INTO DBO.T0040_HRMS_GOAL_MASTER(GOAL_ID,GOAL_TITLE,CMP_ID,LOGIN_ID,DESCRIPTION,START_DATE,END_DATE,FOR_DATE)
			VALUES( @GOAL_ID,@GOAL_TITLE,@CMP_ID,@LOGIN_ID,@DESCRIPTION,@START_DATE,@END_DATE,GETDATE())
		END 
	ELSE IF UPPER(@TRAN_TYPE) ='U' 
		BEGIN					
				UPDATE DBO.T0040_HRMS_GOAL_MASTER 
				SET 
					     GOAL_TITLE=@GOAL_TITLE
						,DESCRIPTION=@DESCRIPTION
						,START_DATE=@START_DATE
						,END_DATE=@END_DATE								
				WHERE GOAL_ID = @GOAL_ID  
		END	
	ELSE IF UPPER(@TRAN_TYPE) ='D'
		BEGIN
			DELETE  FROM DBO.T0040_HRMS_GOAL_MASTER WHERE GOAL_ID=@GOAL_ID 
		END
	RETURN
