
---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_HRMS_AwardMaster]
	   @AWARDS_ID				NUMERIC(18,0) OUTPUT
      ,@CMP_ID					NUMERIC(18,0)  
      ,@AWARD_NAME				VARCHAR(100)		
      ,@TRAN_TYPE				VARCHAR(1) 
	  ,@USER_ID					NUMERIC(18,0) = 0
	  ,@IP_ADDRESS				VARCHAR(30)= '' 
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	 IF UPPER(@TRAN_TYPE) ='I' OR UPPER(@TRAN_TYPE) ='U'
		 BEGIN
			IF EXISTS(SELECT 1 FROM T0040_HRMS_AWARDMASTER WITH (NOLOCK) WHERE AWARD_NAME=@AWARD_NAME AND AWARDS_ID<>@AWARDS_ID AND CMP_ID=@CMP_ID)
				BEGIN
					-- COMMENTED BY GADRIWALA MUSLIM 01102016 -- NOT REQUIRED CODE.
					--INSERT INTO DBO.T0080_IMPORT_LOG(ROW_NO,CMP_ID,EMP_CODE,ERROR_DESC,ACTUAL_VALUE,SUGGESTION,FOR_DATE,IMPORT_TYPE) 
					--Values (0,@Cmp_Id,0,'Duplicate entry of Awards name',0,'Duplicate name',GetDate(),'EmployeeReward')
					SET @AWARDS_ID=0
					RETURN 
				END
		 End
	 IF UPPER(@TRAN_TYPE) ='I'
		begin
			SELECT @AWARDS_ID = ISNULL(MAX(AWARDS_ID),0) + 1 FROM T0040_HRMS_AWARDMASTER WITH (NOLOCK)
			INSERT INTO T0040_HRMS_AWARDMASTER
			(
				 AWARDS_ID
				,CMP_ID	
				,AWARD_NAME
			)
			VALUES
			(
				 @AWARDS_ID
				,@CMP_ID
				,@AWARD_NAME
			)
		End
	 ELSE IF UPPER(@TRAN_TYPE) ='U'
		BEGIN
			UPDATE  T0040_HRMS_AWARDMASTER
			SET  AWARD_NAME = @AWARD_NAME
			WHERE AWARDS_ID = @AWARDS_ID
		END
	ELSE IF UPPER(@TRAN_TYPE) ='D'
		BEGIN
			DELETE FROM T0040_HRMS_AWARDMASTER WHERE AWARDS_ID = @AWARDS_ID	
		END
END
