


---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_BONUS_CALC_RECORD_GET]
   @CMP_ID NUMERIC
   ,@BRANCH_ID	NUMERIC
   ,@FOR_DATE DATETIME = NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
  
 	    DECLARE @TRAN_ID AS NUMERIC
 	    DECLARE @PARTICULARS VARCHAR(MAX)
 	    
 	    IF(@FOR_DATE='1900-01-01 00:00:00')
 	       SET @FOR_DATE = NULL
 	      
 	    
 	    IF (@FOR_DATE IS NOT NULL)
 			BEGIN
 			
 			   SELECT @TRAN_ID=TRAN_ID FROM dbo.T0040_BONUS_CALC WITH (NOLOCK) WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE 
 			END
 	    ELSE
 			BEGIN
 			
 				SELECT	@TRAN_ID=TRAN_ID 
 				FROM	dbo.T0040_BONUS_CALC C1 WITH (NOLOCK)
 						INNER JOIN (SELECT BRANCH_ID, MAX(FOR_DATE) AS FOR_DATE FROM T0040_BONUS_CALC WITH (NOLOCK) GROUP BY BRANCH_ID) C2 ON C1.BRANCH_ID=C2.BRANCH_ID AND C1.FOR_DATE=C2.FOR_DATE
 				WHERE	C1.BRANCH_ID=@BRANCH_ID  AND CMP_ID=@CMP_ID
 			END
 			
 			
 	--    SELECT @PARTICULARS = PARTICULARS FROM dbo.T0040_BONUS_CALC WHERE TRAN_ID=@TRAN_ID 	    	    
 	    
		--SELECT	ID, CAST(DATA AS INT) AS DATA INTO #TEMP_DAYS 
		--FROM	DBO.SPLIT(@PARTICULARS, '#') T 
		--WHERE CAST(DATA AS INT) >= 9000
		
		--SELECT	ID, CAST(DATA AS INT) AS DATA INTO #TEMP_LEAVES 
		--FROM	DBO.SPLIT(@PARTICULARS, '#') T
		--WHERE CAST(DATA AS INT) < 9000
 	    
 	    --SET CAPTION TEXT FOR PERTICULARS DAYS/LEAVE
         --SELECT * INTO #DAYS_PART FROM dbo.fn_getParticulars(@CMP_ID, @BRANCH_ID,NULL, 'B') WHERE FLAG = 'D'
         --SELECT * INTO #LEAVE_PART FROM dbo.fn_getParticulars(@CMP_ID, @BRANCH_ID,NULL, 'B') WHERE FLAG = 'L'
         
		--MAIN MASTER TABLE
		SELECT * FROM dbo.T0040_BONUS_CALC WITH (NOLOCK) WHERE TRAN_ID=@TRAN_ID
		
		--DAYS SLAB TABLE
		SELECT * FROM dbo.T0045_BONUS_DAYS_SLAB WITH (NOLOCK) WHERE 	TRAN_ID=@TRAN_ID	
		
		
		--Particulars
		SELECT * INTO #PART  FROM dbo.fn_getParticulars(@CMP_ID, @BRANCH_ID,@FOR_DATE, 'B')
		
		--Day Particulars
		SELECT *   FROM #PART WHERE FLAG = 'D'
		
		--Leave Particulars
		SELECT *   FROM #PART WHERE FLAG = 'L'
		
		
		----DAYS SELECTED TABLE
		--SELECT (CASE WHEN TD.Data IS NULL THEN 0 ELSE 1 END) AS SELECTED,DP.ID, DP.CAPTION 
		--FROM #DAYS_PART DP LEFT OUTER JOIN #TEMP_DAYS TD ON DP.ID= TD.DATA

	 --   --LEAVE SELECTED TABLE
	    
	 --   SELECT (CASE WHEN TD.Data IS NULL THEN 0 ELSE 1 END) AS SELECTED,DP.ID, DP.CAPTION 
	 --   FROM #LEAVE_PART DP LEFT OUTER JOIN #TEMP_LEAVES TD ON DP.ID= TD.DATA 
 	    
 	    
  
END




