



---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_BONUS_CALC_DAYS_SLAB]
    @TRAN_ID NUMERIC OUTPUT
   ,@CMP_ID NUMERIC
   ,@BRANCH_ID	NUMERIC
   ,@FOR_DATE DATETIME = NULL
   ,@FROM_DAYS NUMERIC(18,2)
   ,@TO_DAYS NUMERIC(18,2)
   ,@PERCENTAGE NUMERIC(18,2)
   ,@TRAN_TYPE	Char(1)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
  
 	  
 IF @TRAN_TYPE  = 'I'
	BEGIN	 	
	
		          IF EXISTS(SELECT 1 FROM dbo.T0040_BONUS_CALC WITH (NOLOCK) WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID)
						 BEGIN
							SELECT @TRAN_ID= TRAN_ID FROM dbo.T0040_BONUS_CALC WITH (NOLOCK)  WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID
								--IF(@FROM_DAYS <> 0 AND @TO_DAYS <> 0 AND @PERCENTAGE <> 0)
								--BEGIN
									IF @TRAN_ID <> 0
							        BEGIN
									INSERT INTO dbo.T0045_BONUS_DAYS_SLAB
										(CMP_ID,TRAN_ID,FROM_DAYS,TO_DAYS,PERCENTAGE)
									VALUES
										(@CMP_ID,@TRAN_ID,@FROM_DAYS,@TO_DAYS,@PERCENTAGE) 
										
									END
									
						END
					ELSE
						BEGIN
							SELECT @TRAN_ID= TRAN_ID FROM dbo.T0040_BONUS_CALC WITH (NOLOCK) WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID
									--IF(@FROM_DAYS <> 0 AND @TO_DAYS <> 0 AND @PERCENTAGE <> 0)
									--BEGIN
									IF @TRAN_ID <> 0
							        BEGIN
										INSERT INTO dbo.T0045_BONUS_DAYS_SLAB
											(CMP_ID,TRAN_ID,FROM_DAYS,TO_DAYS,PERCENTAGE)
										VALUES
											(@CMP_ID,@TRAN_ID,@FROM_DAYS,@TO_DAYS,@PERCENTAGE) 
									END
						END	
						
			
				
 END  
 
 	
END




