

-- EXEC [P0040_HRMS_GENERAL_SETTING]
--ALTER BY : NILAY 21`-APRIL -2010
-- HRMS GENERAL SETTING 
--DESCRIPTION  : TO DEFINE SETTING FOR THE POST OR COMAPNY 
---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_HRMS_General_Setting]
		 @GEN_ID      NUMERIC(18,0) OUTPUT
		,@REC_POST_ID NUMERIC(18,0)
		,@REC_REQ_ID  NUMERIC(18,0)
		,@FOR_DATE    DATETIME
		,@CMP_ID      NUMERIC(18,0)
		,@LOGIN_ID    NUMERIC(18,0)
		,@ACTUAL_RATE NUMERIC(18,2) 
		,@MIN_RATE    NUMERIC(18,2)
		,@MAX_RATE    NUMERIC(18,2)
		,@TRAN_TYPE   CHAR(1)
		,@PROCESS_ID  NUMERIC(18,0)
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	
	IF @REC_REQ_ID = 0
	  SET @REC_REQ_ID =NULL
	  
	IF  @REC_POST_ID =0
	 SET @REC_POST_ID =NULL
	
	IF @TRAN_TYPE ='I'
	  BEGIN
	  IF EXISTS(SELECT 1 FROM T0040_HRMS_GENERAL_SETTING WITH (NOLOCK) WHERE PROCESS_ID =@PROCESS_ID AND REC_POST_ID=@REC_POST_ID)
		BEGIN
			SET @GEN_ID = 0			
			RETURN 
			--RAISERROR('THIS ENTRY ALREADY EXISTS',16,2)
		END
	  ELSE
		BEGIN				
			SELECT @GEN_ID= ISNULL(MAX(GEN_ID),0) + 1 	FROM T0040_HRMS_GENERAL_SETTING  WITH (NOLOCK)			
			INSERT INTO T0040_HRMS_GENERAL_SETTING
			    (GEN_ID,REC_POST_ID,REC_REQ_ID,FOR_DATE,CMP_ID,LOGIN_ID,ACTUAL_RATE,MIN_RATE,MAX_RATE,SYS_DATE,PROCESS_ID)
			VALUES(@GEN_ID,@REC_POST_ID,@REC_REQ_ID,GETDATE(),@CMP_ID,@LOGIN_ID,@ACTUAL_RATE,@MIN_RATE,@MAX_RATE,GETDATE(),@PROCESS_ID)
		END
	  End
	ELSE IF @TRAN_TYPE='U'  
	   BEGIN 
				UPDATE T0040_HRMS_GENERAL_SETTING
				   SET  GEN_ID = @GEN_ID,
						REC_POST_ID=@REC_POST_ID,
						REC_REQ_ID=@REC_REQ_ID,
						FOR_DATE = GETDATE(),
						CMP_ID =@CMP_ID,
						LOGIN_ID =@LOGIN_ID,
						ACTUAL_RATE =@ACTUAL_RATE,
						MIN_RATE=@MIN_RATE,
						MAX_RATE=@MAX_RATE,
						SYS_DATE = GETDATE(),
						PROCESS_ID =@PROCESS_ID
				WHERE GEN_ID=@GEN_ID	
	   END
	ELSE IF @TRAN_TYPE='D'
		BEGIN
				DELETE FROM T0040_HRMS_GENERAL_SETTING WHERE GEN_ID=@GEN_ID
		END 
	
	RETURN




