  
  
  
-- =============================================  
-- AUTHOR:  <AUTHOR,,GADRIWALA MUSLIM>  
-- CREATE DATE: <CREATE DATE,,24082016>  
-- DESCRIPTION: <DESCRIPTION,,QUESTION EXIT ANALYSIS ADD/UPDATE/DELETE>  
---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---  
-- =============================================  
CREATE PROCEDURE [dbo].[P0040_EXIT_ANALYSIS_RATING]   
 @RATING_ID NUMERIC(18,0) OUTPUT,  
 @CMP_ID NUMERIC(18,0),  
 @TITLE NVARCHAR(250),  
 @DESCRIPTION NVARCHAR(MAX),  
 @RATING NUMERIC(18,0),  
 @TRAN_TYPE CHAR(1)  
AS  
  
SET NOCOUNT ON   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
SET ARITHABORT ON  
  
BEGIN  
 -- SET NOCOUNT ON added to prevent extra result sets from  
 -- interfering with SELECT statements.  
     set @TITLE = dbo.fnc_ReverseHTMLTags(@TITLE)  --added by Ronak 081021
	 set @DESCRIPTION = dbo.fnc_ReverseHTMLTags(@DESCRIPTION)  --added by Ronak 081021
 IF @TRAN_TYPE = 'I'  
  BEGIN  
     IF EXISTS(SELECT 1 FROM T0040_EXIT_ANALYSIS_RATING WITH (NOLOCK) WHERE UPPER(TITLE) = UPPER(@TITLE) AND CMP_ID = @CMP_ID)  
      BEGIN  
        RAISERROR('@@THIS RATING ALREADY EXISTS@@', 16, 1)  
        SET @RATING_ID = 0  
        RETURN  
      END  
     SELECT @RATING_ID = ISNULL(MAX(RATING_ID),0) + 1 FROM T0040_EXIT_ANALYSIS_RATING WITH (NOLOCK)  
     INSERT INTO T0040_EXIT_ANALYSIS_RATING(RATING_ID,CMP_ID,TITLE,DESCRIPTION,RATING)  
     VALUES(@RATING_ID,@CMP_ID,@TITLE,@DESCRIPTION,@RATING)  
  END  
 ELSE IF @TRAN_TYPE = 'U'  
  BEGIN  
       
     SELECT 1 FROM T0040_EXIT_ANALYSIS_RATING WITH (NOLOCK) WHERE RATING_ID = @RATING_ID AND CMP_ID = @CMP_ID  
     IF NOT EXISTS(SELECT 1 FROM T0040_EXIT_ANALYSIS_RATING WITH (NOLOCK) WHERE RATING_ID = @RATING_ID AND CMP_ID = @CMP_ID)  
      BEGIN  
        RAISERROR('@@THIS RATING NOT AVAILABLE FOR UPDATE@@', 16, 1)  
        SET @RATING_ID = 0  
        RETURN  
      END  
        
              
      UPDATE T0040_EXIT_ANALYSIS_RATING  
       SET TITLE = @TITLE,  
       DESCRIPTION = @DESCRIPTION,  
       RATING = @RATING  
      WHERE RATING_ID = @RATING_ID AND CMP_ID = @CMP_ID   
  END  
 ELSE IF @TRAN_TYPE = 'D'  
  BEGIN  
    IF NOT EXISTS(SELECT 1 FROM T0040_EXIT_ANALYSIS_RATING WITH (NOLOCK) WHERE RATING_ID = @RATING_ID AND CMP_ID = @CMP_ID)  
      BEGIN  
       RAISERROR('@@THIS RATING NOT AVAILABLE FOR DELETE@@', 16, 1)  
       SET @RATING_ID = 0  
       RETURN  
      END  
    DECLARE @QUESTION_OPTIONS_STR AS NVARCHAR(MAX)  
    SET @QUESTION_OPTIONS_STR = NULL  
      
      
    IF exists (SELECT * FROM T0200_Question_Exit_Analysis_Master WITH (NOLOCK) where Cmp_ID = @Cmp_id AND QUESTION_OPTIONS <> '')  --Added by Jaina 24-12-2018  
    BEGIN  
     SELECT DISTINCT @QUESTION_OPTIONS_STR = COALESCE(@QUESTION_OPTIONS_STR + '#','') + ISNULL(QUESTION_OPTIONS,'')   
     FROM T0200_QUESTION_EXIT_ANALYSIS_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID   
            
     IF  EXISTS( SELECT 1 FROM T0040_EXIT_ANALYSIS_RATING  EA WITH (NOLOCK) INNER JOIN DBO.SPLIT(@QUESTION_OPTIONS_STR,'#') RAT ON RAT.DATA = EA.RATING_ID WHERE EA.RATING_ID = @RATING_ID)  
      BEGIN  
        RAISERROR('@@CAN''T DELETE THIS RATING,REFERENCE EXISTS@@', 16, 1)  
        SET @RATING_ID = 0  
        RETURN  
      END  
    end  
        
    DELETE FROM T0040_EXIT_ANALYSIS_RATING WHERE RATING_ID = @RATING_ID AND CMP_ID = @CMP_ID  
  END  
    
  
END  
  