



-- =============================================
-- AUTHOR:		<RIPAL PATEL>
-- ALTER DATE: <26-DEC-2012>
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0040_HRMS_Appraisal_GoalType_Master]
	@GOALTYPE_ID		NUMERIC(18,0) OUTPUT,
	@GOALTYPE_CMPID		NUMERIC(18,0),
	@GOALTYPE			VARCHAR(100),
	@GOALTYPE_ISACTIVE	TINYINT,
	@TRAN_TYPE			VARCHAR(1),
	@USER_ID			NUMERIC(18,0)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
    
	IF @TRAN_TYPE ='I'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_HRMS_APPRAISAL_GOALTYPE_MASTER WITH (NOLOCK) WHERE GOALTYPE = @GOALTYPE AND GOALTYPE_CMPID = @GOALTYPE_CMPID)
			BEGIN
			    SET	@GOALTYPE_ID = 0
				RETURN
			END
				SELECT @GOALTYPE_ID = ISNULL(MAX(GOALTYPE_ID),0)+1 FROM T0040_HRMS_APPRAISAL_GOALTYPE_MASTER WITH (NOLOCK)
				INSERT INTO T0040_HRMS_APPRAISAL_GOALTYPE_MASTER
						   (GOALTYPE_ID
						   ,GOALTYPE_CMPID
						   ,GOALTYPE
						   ,GOALTYPE_ISACTIVE
						   ,GOALTYPE_CREATEDBY
						   ,GOALTYPE_CREATEDDATE)
					 VALUES
						   (@GOALTYPE_ID
						   ,@GOALTYPE_CMPID
						   ,@GOALTYPE
						   ,@GOALTYPE_ISACTIVE
						   ,@USER_ID
						   ,GETDATE())
		END
	ELSE IF @TRAN_TYPE ='U'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_HRMS_APPRAISAL_GOALTYPE_MASTER  WITH (NOLOCK)
							   WHERE GOALTYPE = @GOALTYPE AND GOALTYPE_CMPID = @GOALTYPE_CMPID AND GOALTYPE_ID <> @GOALTYPE_ID)
			BEGIN
			    SET	@GOALTYPE_ID = 0
				RETURN
			END
				UPDATE T0040_HRMS_APPRAISAL_GOALTYPE_MASTER
				   SET GOALTYPE = @GOALTYPE
					  ,GOALTYPE_ISACTIVE = @GOALTYPE_ISACTIVE
					  ,GOALTYPE_MODIFYBY = @USER_ID
					  ,GOALTYPE_MODIFYDATE = GETDATE()
				 WHERE GOALTYPE_ID = @GOALTYPE_ID AND GOALTYPE_CMPID = @GOALTYPE_CMPID
			
		END
	ELSE IF @TRAN_TYPE ='D'
		BEGIN
			IF NOT EXISTS (SELECT FK_GOALID FROM T0090_HRMS_APPRAISAL_EMP_GOALDESCRIPTION WITH (NOLOCK) WHERE FK_GOALTYPE = @GOALTYPE_ID)
				BEGIN
					DELETE FROM T0040_HRMS_APPRAISAL_GOALTYPE_MASTER 
							WHERE GOALTYPE_ID = @GOALTYPE_ID AND GOALTYPE_CMPID = @GOALTYPE_CMPID
					--UPDATE T0040_HRMS_Appraisal_GoalType_Master
					--   SET GoalType_IsActive = @GoalType_IsActive
					--	  ,GoalType_ModifyBy = @User_Id
					--	  ,GoalType_ModifyDate = GETDATE()
					-- WHERE GoalType_Id = @GoalType_Id
				END
			ELSE
				BEGIN
					SET	@GOALTYPE_ID = 0
					RETURN
				END
		END
END



