

CREATE PROCEDURE [dbo].[P_GETDATA_REPORT_85]  
 
	@Cmp_ID		numeric
	,@From_Date		datetime
	,@To_Date		datetime 
	,@Branch_ID		numeric   = 0
	,@Cat_ID		numeric  = 0
	,@Grd_ID		numeric = 0
	,@Type_ID		numeric  = 0
	,@Dept_ID		numeric  = 0
	,@Desig_ID		numeric = 0
	,@Emp_ID		numeric  = 0
	,@Constraint	varchar(5000) = ''
	,@New_Join_emp	numeric = 0 
	,@Left_Emp		Numeric = 0
	,@PBranch_ID varchar(200) = '0'
 
AS    

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON




Declare @TOTAL_SUPERVISOR  INTEGER=0
,@TOTAL_NONSUPERVISOR  INTEGER=0
,@TOTAL_SUPERVISOR_LOCAL  INTEGER=0
,@TOTAL_SUPERVISOR_LOCAL_PERCENTAGE  INTEGER=0
,@TOTAL_NONSUPERVISOR_LOCAL INTEGER=0
,@TOTAL_NONSUPERVISOR_LOCAL_PERCENTAGE INTEGER=0
,@TOTAL INTEGER=0
,@TOTAL_LOCAL_PERCENTAGE INTEGER=0
,@TOTAL_LOCAL INTEGER=0
--,@Gujarati_Header varchar(max)='શ્રમ અને રોજગાર વિભાગના તા. ૩૧-૦૩-૯૫ ના ઠરાવ મુજબ રાજ્યમાં આવેલ જાહેર સાહસો અને સંયુક્ત ક્ષેત્રીય તેમજ મોટા ઉદ્યોગોમાં ૮૫ ટકા જગ્યાઓ સ્થાનિક ઉમેદવારોથી ભરવાની જોગવાઈ અન્વયે કુલ રોજગારી અને તે પૈકી સ્થાનિક રોજગારીની માહિતી દર્શાવતું છમાસિક પત્રક:'

-- GET SUPERVISOR


SET @TOTAL_SUPERVISOR=(select dISTINCT COUNT(*) AS SUPERVISOR
from T0080_EMP_MASTER EM WITH (NOLOCK) INNER JOIN
T0095_INCREMENT INC WITH (NOLOCK) ON INC.Emp_ID=EM.Emp_ID 
AND INC.Increment_Effective_Date=(SELECT MAX(Increment_Effective_Date) FROM T0095_INCREMENT WHERE Emp_ID=EM.Emp_ID)
INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.Desig_ID=INC.Desig_Id where EM.Cmp_ID=@Cmp_ID
AND DM.Def_ID=1
AND ISNULL(EM.EMP_LEFT_DATE,'1900-01-01 00:00:00.000') NOT BETWEEN @FROM_DATE AND @FROM_DATE)

-- GET  NON SUPERVISOR
SET @TOTAL_NONSUPERVISOR=(select dISTINCT COUNT(*) AS 'NON SUPERVISOR'
from T0080_EMP_MASTER EM WITH (NOLOCK) INNER JOIN
T0095_INCREMENT INC WITH (NOLOCK) ON INC.Emp_ID=EM.Emp_ID 
AND INC.Increment_Effective_Date=(SELECT MAX(Increment_Effective_Date) FROM T0095_INCREMENT WHERE Emp_ID=EM.Emp_ID)
INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.Desig_ID=INC.Desig_Id where EM.Cmp_ID=@Cmp_ID
AND DM.Def_ID=0
AND ISNULL(EM.EMP_LEFT_DATE,'1900-01-01 00:00:00.000') NOT BETWEEN @FROM_DATE AND @FROM_DATE)

-- GET LOCAL  SUPERVISOR
SET @TOTAL_SUPERVISOR_LOCAL=(select dISTINCT COUNT(*) AS 'SUPERVISOR LOCAL'
from T0080_EMP_MASTER EM WITH (NOLOCK) INNER JOIN
T0095_INCREMENT INC WITH (NOLOCK) ON INC.Emp_ID=EM.Emp_ID 
AND INC.Increment_Effective_Date=(SELECT MAX(Increment_Effective_Date) FROM T0095_INCREMENT WHERE Emp_ID=EM.Emp_ID)
INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.Desig_ID=INC.Desig_Id 
INNER JOIN T0010_COMPANY_MASTER CMP WITH (NOLOCK) ON CMP.CMP_ID=EM.EMP_ID
where EM.Cmp_ID=@Cmp_ID AND CMP.Cmp_State_Name=EM.State
AND DM.Def_ID=1
AND ISNULL(EM.EMP_LEFT_DATE,'1900-01-01 00:00:00.000') NOT BETWEEN @FROM_DATE AND @FROM_DATE)
-- GET LOCAL NON SUPERVISOR
SET @TOTAL_NONSUPERVISOR_LOCAL=(select dISTINCT COUNT(*) AS 'SUPERVISOR LOCAL'
from T0080_EMP_MASTER EM WITH (NOLOCK) INNER JOIN
T0095_INCREMENT INC WITH (NOLOCK) ON INC.Emp_ID=EM.Emp_ID 
AND INC.Increment_Effective_Date=(SELECT MAX(Increment_Effective_Date) FROM T0095_INCREMENT WHERE Emp_ID=EM.Emp_ID)
INNER JOIN T0040_DESIGNATION_MASTER DM WITH (NOLOCK) ON DM.Desig_ID=INC.Desig_Id 
INNER JOIN T0010_COMPANY_MASTER CMP WITH (NOLOCK) ON CMP.CMP_ID=EM.EMP_ID
where EM.Cmp_ID=@Cmp_ID AND CMP.Cmp_State_Name!=EM.State
AND DM.Def_ID=1
AND ISNULL(EM.EMP_LEFT_DATE,'1900-01-01 00:00:00.000') NOT BETWEEN @FROM_DATE AND @FROM_DATE)

-- GET PERCENTAGE 
set @TOTAL=(@TOTAL_SUPERVISOR+@TOTAL_NONSUPERVISOR)
IF @TOTAL_SUPERVISOR>0
BEGIN
SET @TOTAL_SUPERVISOR_LOCAL_PERCENTAGE=(@TOTAL_SUPERVISOR_LOCAL *100/@TOTAL_SUPERVISOR)
END

IF @TOTAL_NONSUPERVISOR>0
BEGIN
SET @TOTAL_NONSUPERVISOR_LOCAL_PERCENTAGE=(@TOTAL_NONSUPERVISOR_LOCAL *100/@TOTAL_NONSUPERVISOR)
END
-- GET PERCENTAGE 
set @TOTAL_LOCAL=(@TOTAL_NONSUPERVISOR_LOCAL+@TOTAL_SUPERVISOR_LOCAL)
if @TOTAL_LOCAL>0
begin
set @TOTAL_LOCAL_PERCENTAGE=(@TOTAL_LOCAL*100 /(@TOTAL_SUPERVISOR+@TOTAL_NONSUPERVISOR))
end
--CODE TO GET HR NAME BASED ON MAX GROSS SALARY IF MULTIPLE
DECLARE @EmpID INT


SELECT Emp_id   
INTO #EMP_ID FROM T0011_LOGIN L WITH (NOLOCK)   
WHERE Is_HR = 1 AND Emp_ID > 0 AND L.Cmp_ID = @Cmp_ID  
CREATE TABLE #EmpSalaries (
    Emp_ID INT,
    Gross_Salary DECIMAL(18,2)
)

DECLARE @EmpTable TABLE (Emp_ID INT)
INSERT INTO @EmpTable SELECT Emp_ID FROM #EMP_ID

SELECT @EmpID = MIN(Emp_ID) FROM @EmpTable
WHILE @EmpID IS NOT NULL
BEGIN
    DECLARE @GrossSalary DECIMAL(18,2)

    SELECT @GrossSalary = Gross_Salary 
    FROM T0095_INCREMENT 
    WHERE Emp_ID = @EmpID 
    AND Increment_Effective_Date = 
        (SELECT MAX(Increment_Effective_Date) FROM T0095_INCREMENT WHERE Emp_ID = @EmpID)
	    INSERT INTO #EmpSalaries (Emp_ID, Gross_Salary)
    VALUES (@EmpID, @GrossSalary)

    -- Remove processed Emp_ID and get the next one
    DELETE FROM @EmpTable WHERE Emp_ID = @EmpID
    SELECT @EmpID = MIN(Emp_ID) FROM @EmpTable
END  








select 
cd.Cmp_Name AS 'COMPANY NAME' 
,CD.Cmp_Address AS 'COMPANY ADDRESS'
,CM.Cmp_Phone AS 'COMPANY CONTACT NO'
,0 as 'NIC CODE'
,CAST( getdate() AS date) as 'PRINT DATE'
,@TOTAL_SUPERVISOR AS TOTAL_SUPERVISOR
,@TOTAL_NONSUPERVISOR AS TOTAL_NONSUPERVISOR
,@TOTAL_SUPERVISOR_LOCAL AS TOTAL_SUPERVISOR_LOCAL
,@TOTAL as TOTAL
,@TOTAL_SUPERVISOR_LOCAL_PERCENTAGE AS TOTAL_SUPERVISOR_LOCAL_PERCENTAGE
,@TOTAL_NONSUPERVISOR_LOCAL AS TOTAL_NONSUPERVISOR_LOCAL
,@TOTAL_NONSUPERVISOR_LOCAL_PERCENTAGE AS TOTAL_NONSUPERVISOR_LOCAL_PERCENTAGE
,@TOTAL_LOCAL as TOTAL_LOCAL
,@TOTAL_LOCAL_PERCENTAGE as TOTAL_LOCAL_PERCENTAGE
,EMP.Emp_Full_Name AS 'HR_NAME'
,EMP.Work_Tel_No AS 'HR_MOBILE' 
,EMP.Work_Email AS 'HR_WORK_EMAIL'

--,@Gujarati_Header as Gujarati_Header
from T0010_COMPANY_MASTER CM WITH (NOLOCK) INNER JOIN
T0011_COMPANY_DETAIL CD WITH (NOLOCK) on CM.Cmp_Id=CD.Cmp_Id 
INNER JOIN T0080_EMP_MASTER EMP WITH (NOLOCK) ON EMP.CMP_ID=CM.CMP_ID
INNER JOIN #EmpSalaries EGS WITH (NOLOCK) ON  EMP.Emp_ID=EGS.Emp_ID
AND EGS.Gross_Salary=(SELECT MAX(Gross_Salary) FROM #EmpSalaries)
where CM.Cmp_Id=@Cmp_ID


DROP TABLE #EMP_ID
DROP TABLE #EmpSalaries







