

-- =============================================
-- AUTHOR:		SHAIKH RAMIZ
-- CREATE DATE: 11/04/2019
-- DESCRIPTION:	THIS SP WILL DISPLAY CURRENT HR BASED ON EMPLOYEES
---30/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P_GET_BRANCHWISE_HR_OLD]
	@CMP_ID		NUMERIC,
	@TO_DATE	DATETIME,
	@CONSTRAINT	VARCHAR(MAX)
	
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

    IF OBJECT_ID('tempdb..#EMP_CONS') IS NULL
		BEGIN
			CREATE TABLE #Emp_Cons 
			(      
				Emp_ID numeric ,     
				Branch_ID numeric,
				Increment_ID numeric    
			);
			CREATE NONCLUSTERED INDEX IX_Emp_Cons_EmpID ON #Emp_Cons (Emp_ID);
		END
	
		EXEC SP_RPT_FILL_EMP_CONS  @Cmp_ID,NULL,@To_Date,0,0,0,0,0,0 ,0 ,@constraint ,0,0,0,0,0,0,0,0,2,0 
		
		SELECT EC.EMP_ID , EC.BRANCH_ID ,EM.ALPHA_EMP_CODE , EM.EMP_FULL_NAME , EM.Work_Email, EM.Other_Email, T.HR_EMAIL_ID AS HR_WORK_EMAIL , LO.LOGIN_ID
		INTO	#RESULT
		FROM	#EMP_CONS EC
			INNER JOIN
				(	SELECT	EMAIL_ID AS HR_EMAIL_ID, B.BRANCH_ID
					FROM	T0030_BRANCH_MASTER B WITH (NOLOCK)
								INNER JOIN T0011_LOGIN L WITH (NOLOCK) ON B.Cmp_ID = L.Cmp_ID AND (CHARINDEX(',' + CAST(B.BRANCH_ID AS VARCHAR(10)) + ',', ',' + L.BRANCH_ID_MULTI + ',') > 0 or L.BRANCH_ID_MULTI = '0')
								INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EM.EMP_ID = L.EMP_ID
					WHERE L.CMP_ID = @CMP_ID AND L.Is_HR = 1 and EMP_LEFT <> 'Y'
					GROUP BY B.BRANCH_ID , EMAIL_ID
				)T ON EC.BRANCH_ID = T.BRANCH_ID
			INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EC.EMP_ID = EM.EMP_ID
			INNER JOIN T0011_LOGIN LO WITH (NOLOCK) ON EM.EMP_ID = LO.EMP_ID
		
		SELECT	EMP_ID , BRANCH_ID,ALPHA_EMP_CODE , EMP_FULL_NAME , WORK_EMAIL,Other_Email,
				STUFF((SELECT ',' + HR_WORK_EMAIL FROM #RESULT R1 
					   WHERE R.Emp_ID=R1.Emp_ID AND R.Branch_ID=R1.Branch_ID 
					   FOR XML PATH('')), 1,1,'') AS HR_WORK_EMAIL , LOGIN_ID
		FROM	#RESULT R
		GROUP BY EMP_ID , Branch_ID,ALPHA_EMP_CODE , EMP_FULL_NAME , WORK_EMAIL , Other_Email , LOGIN_ID
END

