

-- =============================================
-- Author:		<Author,,Jimit Soni>
-- Create date: <Create Date,,25062019>
-- Description:	<Description,,For Getting LWP Deduction Amount Report>
---02/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P_GET_LWP_DEDUCTION_AMOUNT]
	 @CMP_ID		NUMERIC  
	,@FROM_DATE		DATETIME
	,@TO_DATE 		DATETIME
	,@BRANCH_ID		NUMERIC	
	,@GRD_ID 		NUMERIC
	,@TYPE_ID 		NUMERIC
	,@DEPT_ID 		NUMERIC
	,@DESIG_ID 		NUMERIC
	,@EMP_ID 		NUMERIC
	,@CONSTRAINT	VARCHAR(MAX)
	,@CAT_ID        NUMERIC = 0		
	,@ORDER_BY		VARCHAR(30) = 'CODE'
	
AS
BEGIN
	
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

   
	
	CREATE TABLE #EMP_CONS 
	(
		EMP_ID	NUMERIC ,     
		BRANCH_ID NUMERIC,
		INCREMENT_ID NUMERIC 
	)
	
	EXEC SP_RPT_FILL_EMP_CONS @CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRD_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID,@EMP_ID,
								@CONSTRAINT,0,0,0,0,0,0,0,0,0,0,0,0   



	CREATE TABLE #LWPDEDUCTION
	(		
	    CMP_ID				NUMERIC(18,0)
	   ,EMP_ID				NUMERIC(18,0) 
	   ,EMP_CODE			NUMERIC(18,0)	   
	   ,ALPHA_EMP_CODE		VARCHAR(50)
	   ,EMP_FULL_NAME		VARCHAR(250)	   
	   ,BASIC_AMOUNT		NUMERIC(18,2)
	   ,GROSS_AMOUNT		NUMERIC(18,2)
	   ,BASIC_LWP_DEDUCTION	NUMERIC(18,2)
	   ,GROSS_LWP_DEDUCTION	NUMERIC(18,2)
	   --,TOTAL_LWP_DEDUCTION	NUMERIC(18,2)
	)

	INSERT INTO #LWPDEDUCTION 
	SELECT		E.CMP_ID,E.EMP_ID,E.EMP_CODE,E.ALPHA_EMP_CODE,(E.ALPHA_EMP_CODE + ' - ' + E.EMP_FULL_NAME) EMP_FULL_NAME,
				INC.BASIC_SALARY,INC.GROSS_SALARY,0,0--,0
	FROM		T0080_EMP_MASTER E	WITH (NOLOCK)
				INNER JOIN	T0095_INCREMENT INC WITH (NOLOCK) ON E.EMP_ID = INC.EMP_ID AND E.INCREMENT_ID = INC.INCREMENT_ID
				INNER JOIN 	(
								SELECT	MAX(I2.INCREMENT_ID) AS INCREMENT_ID,I2.EMP_ID 	
								FROM	T0095_INCREMENT I2 WITH (NOLOCK) INNER JOIN 
										#EMP_CONS EC ON I2.EMP_ID=EC.EMP_ID INNER JOIN 
										(
											SELECT	MAX(INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE, I3.EMP_ID	
											FROM	T0095_INCREMENT I3 WITH (NOLOCK) INNER JOIN 
													#EMP_CONS E3 ON I3.EMP_ID=E3.EMP_ID 
											WHERE	I3.INCREMENT_EFFECTIVE_DATE <= @TO_DATE AND I3.CMP_ID = @CMP_ID	
											GROUP BY I3.EMP_ID 
										) I3 ON I2.INCREMENT_EFFECTIVE_DATE=I3.INCREMENT_EFFECTIVE_DATE AND I2.EMP_ID=I3.EMP_ID	
								GROUP BY I2.EMP_ID 
							) I ON INC.EMP_ID = I.EMP_ID AND INC.INCREMENT_ID = I.INCREMENT_ID

			 UPDATE L
			 SET	L.BASIC_LWP_DEDUCTION = L.BASIC_AMOUNT - IsNUll(Q.Salary_Amount,0),
					L.GROSS_LWP_DEDUCTION = L.GROSS_AMOUNT - IsNUll(Q.Gross_Salary,0)
					--L.TOTAL_LWP_DEDUCTION = (L.GROSS_AMOUNT - IsNUll(Q.Gross_Salary,0)) + (L.BASIC_AMOUNT - IsNUll(Q.Salary_Amount,0))		
			 FROM   #LWPDEDUCTION L INNER JOIN
					(
						SELECT Ms.Salary_Amount,Ms.GRoss_Salary,Ms.EMP_Id
						FROm   T0200_Monthly_Salary Ms WITH (NOLOCK) Inner Join
							   #LWPDEDUCTION LW ON LW.EMP_Id = MS.EMP_Id
						WHERE  month(Month_End_date)= month(@To_date) and Year(Month_End_date) = Year(@To_date)					   
					)Q ON Q.EMP_ID = L.EMP_Id


			SELECT * FROM #LWPDEDUCTION
		    --Where TOTAL_LWP_DEDUCTION <> 0

			DROP TABLE #LWPDEDUCTION
		
END


