

---01/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P_GET_EMP_INCREMENT_APP]
	@CMP_ID		NUMERIC,
	@EMP_ID		NUMERIC,
	@FOR_DATE	DATETIME,
	@INC_APP_ID	NUMERIC = NULL,
	@GRD_ID		NUMERIC = NULL,
	@Rpt_Level	NUMERIC = NULL,
	@HideReport	INT	= 1
AS
	BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

		IF @INC_APP_ID IS NULL
			SET @INC_APP_ID = 0


		CREATE TABLE #INC_APP_DETAIL
		(
			EMP_ID					NUMERIC,
			INC_APP_ID				NUMERIC,
			FOR_DATE				DATETIME,
			AD_ID					NUMERIC,
			AD_NAME					VARCHAR(128),
			AD_MODE					VARCHAR(64),
			AD_PERCENTAGE			NUMERIC(18,4),
			AD_AMOUNT				NUMERIC(18,4),
			AD_Not_effect_salary	NUMERIC,
			AD_Part_Of_Ctc			NUMERIC,
			AD_CALCULATE_ON			VARCHAR(64),
			AD_EFFECT_ON_CTC		BIT,
			AD_LEVEL				NUMERIC(18,0),
			AD_FLAG					CHAR(1),
			C_AD_PERCENTAGE			NUMERIC(18,4),
			C_AD_AMOUNT				NUMERIC(18,4),
			SELECTED				BIT
		)
		CREATE NONCLUSTERED INDEX IX_INC_APP_DETAIL ON #INC_APP_DETAIL (EMP_ID,AD_ID) INCLUDE(FOR_DATE)

		DECLARE @INCREMENT_ID NUMERIC
		SELECT	TOP 1 @INCREMENT_ID = INCREMENT_ID FROM T0095_INCREMENT I WITH (NOLOCK)
		WHERE	Emp_ID=@EMP_ID AND Increment_Effective_Date <= @FOR_DATE
		ORDER	BY Increment_Effective_Date DESC, INCREMENT_ID DESC


		INSERT INTO #INC_APP_DETAIL(EMP_ID,INC_APP_ID,FOR_DATE,AD_ID,AD_NAME,AD_MODE,AD_PERCENTAGE,AD_AMOUNT,AD_Not_effect_salary,AD_Part_Of_Ctc,
				AD_CALCULATE_ON,AD_EFFECT_ON_CTC,AD_LEVEL,AD_FLAG,C_AD_PERCENTAGE,C_AD_AMOUNT,SELECTED)
		SELECT	@EMP_ID,0,@FOR_DATE,EAD.AD_ID,AD.AD_NAME,EAD.E_AD_MODE,EAD.E_AD_PERCENTAGE,EAD.E_AD_AMOUNT,AD.AD_NOT_EFFECT_SALARY,AD.AD_PART_OF_CTC,
				AD.AD_CALCULATE_ON,AD.AD_EFFECT_ON_CTC,AD.AD_LEVEL,EAD.E_AD_FLAG, EAD.E_AD_PERCENTAGE AS C_AD_PERCENTAGE, EAD.E_AD_AMOUNT AS C_AD_AMOUNT, 0 AS SELECTED
		FROM	T0100_EMP_EARN_DEDUCTION EAD WITH (NOLOCK) INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON EAD.AD_ID=AD.AD_ID
		WHERE	EAD.INCREMENT_ID=@INCREMENT_ID	
		ORDER BY AD.AD_LEVEL	
		
		INSERT INTO #INC_APP_DETAIL(EMP_ID,INC_APP_ID,FOR_DATE,AD_ID,AD_NAME,AD_MODE,AD_PERCENTAGE,AD_AMOUNT,AD_Not_effect_salary,AD_Part_Of_Ctc,
				AD_CALCULATE_ON,AD_EFFECT_ON_CTC,AD_LEVEL,AD_FLAG,C_AD_PERCENTAGE,C_AD_AMOUNT, SELECTED)
		SELECT	@EMP_ID,0,@FOR_DATE,EAD.AD_ID,AD.AD_NAME,EAD.E_AD_MODE,EAD.E_AD_PERCENTAGE,EAD.E_AD_AMOUNT,AD.AD_NOT_EFFECT_SALARY,AD.AD_PART_OF_CTC,
				AD.AD_CALCULATE_ON,AD.AD_EFFECT_ON_CTC,AD.AD_LEVEL,EAD.E_AD_FLAG, EAD.E_AD_PERCENTAGE AS C_AD_PERCENTAGE, EAD.E_AD_AMOUNT AS C_AD_AMOUNT , 1 AS SELECTED
		FROM	T0110_EMP_EARN_DEDUCTION_REVISED EAD WITH (NOLOCK)
				INNER JOIN (SELECT	MAX(FOR_DATE) AS FOR_DATE, AD_ID
							FROM	T0110_EMP_EARN_DEDUCTION_REVISED EAD1 WITH (NOLOCK)
							WHERE	EAD1.Increment_ID=@INCREMENT_ID AND EAD1.EMP_ID=@EMP_ID
									AND EAD1.ENTRY_TYPE='A'
							GROUP	BY AD_ID) EAD1 ON EAD.AD_ID=EAD1.AD_ID AND EAD.FOR_DATE=EAD1.FOR_DATE
				INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON EAD.AD_ID=AD.AD_ID
		WHERE	EAD.INCREMENT_ID=@INCREMENT_ID	AND EAD.ENTRY_TYPE='A'
		ORDER BY AD.AD_LEVEL	

		UPDATE	IAPD 
		SET		AD_PERCENTAGE = EAD.E_AD_PERCENTAGE,
				AD_AMOUNT = EAD.E_AD_AMOUNT,
				SELECTED = CASE WHEN EAD.ENTRY_TYPE='D' THEN 0 ELSE 1 END
		FROM	#INC_APP_DETAIL IAPD
				INNER JOIN  T0110_EMP_EARN_DEDUCTION_REVISED EAD ON IAPD.EMP_ID=EAD.EMP_ID AND IAPD.AD_ID=EAD.AD_ID
				INNER JOIN (SELECT	MAX(FOR_DATE) AS FOR_DATE, AD_ID
							FROM	T0110_EMP_EARN_DEDUCTION_REVISED EAD1 WITH (NOLOCK)
							WHERE	EAD1.Increment_ID=@INCREMENT_ID AND EAD1.EMP_ID=@EMP_ID
									AND EAD1.ENTRY_TYPE <> 'A'
							GROUP	BY AD_ID) EAD1 ON EAD.AD_ID=EAD1.AD_ID AND EAD.FOR_DATE=EAD1.FOR_DATE
				INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON EAD.AD_ID=AD.AD_ID
		WHERE	EAD.INCREMENT_ID=@INCREMENT_ID	AND EAD.ENTRY_TYPE <> 'A'


		IF @INC_APP_ID > 0			
			BEGIN
				INSERT INTO #INC_APP_DETAIL(EMP_ID,INC_APP_ID,FOR_DATE,AD_ID,AD_NAME,AD_MODE,AD_PERCENTAGE,AD_AMOUNT,AD_Not_effect_salary,AD_Part_Of_Ctc,
						AD_CALCULATE_ON,AD_EFFECT_ON_CTC,AD_LEVEL,AD_FLAG,C_AD_PERCENTAGE,C_AD_AMOUNT)
				SELECT	@EMP_ID,0,@FOR_DATE,EAD.AD_ID,AD.AD_NAME,EAD.E_AD_MODE,EAD.E_AD_PERCENTAGE,EAD.E_AD_AMOUNT,AD.AD_NOT_EFFECT_SALARY,AD.AD_PART_OF_CTC,
						AD.AD_CALCULATE_ON,AD.AD_EFFECT_ON_CTC,AD.AD_LEVEL,EAD.E_AD_FLAG, EAD.E_AD_PERCENTAGE AS C_AD_PERCENTAGE, EAD.E_AD_AMOUNT AS C_AD_AMOUNT 
				FROM	T0100_INCREMENT_APP_EARN_DEDUCTION EAD WITH (NOLOCK) INNER JOIN T0050_AD_MASTER AD WITH (NOLOCK) ON EAD.AD_ID=AD.AD_ID
				WHERE	EAD.App_ID=@INC_APP_ID
						AND NOT EXISTS(SELECT 1 FROM #INC_APP_DETAIL T WHERE EAD.EMP_ID=T.EMP_ID AND EAD.AD_ID=T.AD_ID)
				ORDER BY AD.AD_LEVEL	

				UPDATE	IAD
				SET		AD_PERCENTAGE = EAD.E_AD_PERCENTAGE, AD_AMOUNT=EAD.E_AD_AMOUNT,SELECTED=1
				FROM	#INC_APP_DETAIL IAD 
						INNER JOIN  T0100_INCREMENT_APP_EARN_DEDUCTION EAD ON IAD.EMP_ID=EAD.EMP_ID AND IAD.AD_ID=EAD.AD_ID						
				WHERE	EAD.App_ID=@INC_APP_ID
			END
	
		INSERT INTO #INC_APP_DETAIL(EMP_ID,INC_APP_ID,FOR_DATE,AD_ID,AD_NAME,AD_MODE,AD_PERCENTAGE,AD_AMOUNT,AD_Not_effect_salary,AD_Part_Of_Ctc,
						AD_CALCULATE_ON,AD_EFFECT_ON_CTC,AD_LEVEL,AD_FLAG,C_AD_PERCENTAGE,C_AD_AMOUNT)
		SELECT	@EMP_ID,0,@FOR_DATE,AD.AD_ID,AD.AD_NAME,AD.AD_MODE,GA.AD_PERCENTAGE,GA.AD_AMOUNT,AD.AD_NOT_EFFECT_SALARY,AD.AD_PART_OF_CTC,
				AD.AD_CALCULATE_ON,AD.AD_EFFECT_ON_CTC,AD.AD_LEVEL,AD.AD_FLAG, GA.AD_PERCENTAGE AS C_AD_PERCENTAGE, GA.AD_AMOUNT AS C_AD_AMOUNT 
		FROM	T0120_Gradewise_Allowance GA WITH (NOLOCK)
				INNER JOIN T0050_AD_Master AD WITH (NOLOCK) on GA.AD_ID =AD.AD_ID 
		WHERE	Grd_ID= @GRD_ID and AD.Cmp_ID=@CMP_ID 
				AND NOT EXISTS(SELECT 1 FROM #INC_APP_DETAIL T WHERE AD.AD_ID=T.AD_ID AND T.EMP_ID=@EMP_ID)
		ORDER BY AD.AD_LEVEL	

		
		UPDATE	IAD
		SET		SELECTED = 0
		FROM	#INC_APP_DETAIL IAD
		WHERE	SELECTED IS NULL

		UPDATE	IAD
		SET		AD_PERCENTAGE = dbo.F_Show_Decimal(AD_PERCENTAGE,@CMP_ID),
				AD_AMOUNT = dbo.F_Show_Decimal(AD_AMOUNT,@CMP_ID)
		FROM	#INC_APP_DETAIL IAD

		IF @HideReport  = 1
			DELETE	T 
			FROM	#INC_APP_DETAIL T INNER JOIN T0050_AD_MASTER AD ON T.AD_ID=AD.AD_ID
			WHERE	AD.Hide_In_Reports = 1
		
		SELECT * FROM #INC_APP_DETAIL
		ORDER BY AD_LEVEL

	END


