


-- created by rohit For generate Script of Sp,view trigger etc
-- created date:- 03032016
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P_GENERATE_SCRIPT]
	@Name varchar(500)
as
begin
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

CREATE TABLE #TMP (DDL NVARCHAR(MAX));

INSERT INTO #TMP
exec sp_helptextnew @Name

	DECLARE @TEXT NVARCHAR(MAX);
	DECLARE CUR CURSOR FOR SELECT DDL FROM #TMP

	OPEN CUR 
	FETCH NEXT FROM CUR INTO @TEXT

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @TEXT
		FETCH NEXT FROM CUR INTO @TEXT
	END
		
		
	CLOSE CUR
	DEALLOCATE  CUR

end



