
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P_GET_NEXT_EMP_PF_NO_EMP_APP]	
	@Cmp_ID		NUMERIC(18,0),
	@NEXT_PF_NO	VARCHAR(32) = '' OUTPUT
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	DECLARE @LAST_PF_NO VARCHAR(32);

	
	--SELECT	TOP 1 @LAST_PF_NO = SSN_No
	--FROM	T0080_EMP_MASTER 
	--WHERE	ISNUMERIC(SSN_No)=1 AND Cmp_ID=@Cmp_ID
	--ORDER BY CAST(SSN_No AS NUMERIC) DESC
	
	
	SELECT @LAST_PF_NO =MAX(LAST_PF_NO) 
	FROM   ( 
          SELECT	TOP 1 SSN_No AS LAST_PF_NO
				FROM	T0080_EMP_MASTER WITH (NOLOCK)
				WHERE	ISNUMERIC(SSN_No)=1 AND Cmp_ID=@Cmp_ID
				ORDER BY CAST(SSN_No AS NUMERIC) DESC
	 
           UNION ALL
           SELECT	TOP 1  SSN_No AS LAST_PF_NO
				FROM	T0060_EMP_MASTER_APP WITH (NOLOCK)
				WHERE	ISNUMERIC(SSN_No)=1 AND Cmp_ID=@Cmp_ID
				ORDER BY CAST(SSN_No AS NUMERIC) DESC
	
           
       )AS dt
       
       
	IF @LAST_PF_NO IS NULL OR @LAST_PF_NO = '0'
		SET @LAST_PF_NO = '1'

	SET @NEXT_PF_NO = CAST(@LAST_PF_NO AS NUMERIC)  + 1;

	
	SET  @NEXT_PF_NO = RIGHT(REPLICATE('0', LEN(@NEXT_PF_NO)) + @NEXT_PF_NO, LEN(@NEXT_PF_NO))
	


	SELECT @NEXT_PF_NO AS NEXT_PF_NO
	

