

-- =============================================
-- Author:		<Author,,Jimit Soni>
-- Create date: <Create Date,,01052019>
-- Description:	<Description,,For Inserting Employee Master fields in Employee Directory Tables>
-- =============================================
CREATE PROCEDURE [dbo].[P_Insert_Employee_Directory_Columns]
	@Cmp_Id Numeric(18,0)
AS

		SET NOCOUNT ON 
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		SET ARITHABORT ON

BEGIN
	
	
	

	IF NOT EXISTS (SELECT 1 FROM T0040_EMPLOYEE_DIRECTORY_COLUMNS WITH (NOLOCK) WHERE CMP_ID = @CMP_ID)
		BEGIN

				--INSERT DEFAULT COLUMNS IN THE TABLE
				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'ALPHA_EMP_CODE','EMPLOYEE CODE','varchar',1,1)

				
				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'EMP_FULL_NAME','EMPLOYEE NAME','varchar',1,2)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'GENDER','GENDER','varchar',1,3)


				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'BRANCH_NAME','Branch','varchar',1,4)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'DEPT_NAME','Department','varchar',1,5)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'DESIG_NAME','Designation','varchar',1,6)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'DATE_OF_JOIN','Date Of Joining','datetime',1,7)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'WORK_EMAIL','Work Email ID','varchar',1,8)

				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				VALUES(@CMP_ID,'WORK_TEL_NO','Work Phone No','varchar',1,9)
				--ENDED


				DECLARE @MAX_NO AS INT
				SELECT	@MAX_NO = MAX(ISNULL(FIELD_ID,0)) + 1 FROM T0040_EMPLOYEE_DIRECTORY_COLUMNS WITH (NOLOCK)



				INSERT INTO T0040_EMPLOYEE_DIRECTORY_COLUMNS (CMP_ID, FIELD_NAME, FIELD_LABEL, DATA_TYPE, IS_SHOW, SORT_INDEX)
				SELECT  @CMP_ID,COLUMN_NAME, REPLACE(COLUMN_NAME, '_', ' ') AS ALIAS, DATA_TYPE,0,Row_Number() Over (Order By  ORDINAL_POSITION) + @MAX_NO
				FROM	INFORMATION_SCHEMA.COLUMNS C
				WHERE	TABLE_NAME='V0080_EMPLOYEE_MASTER'
						AND NOT EXISTS(SELECT 1 FROM T0040_EMPLOYEE_DIRECTORY_COLUMNS T WITH (NOLOCK) WHERE T.FIELD_NAME=C.COLUMN_NAME AND CMP_ID = @CMP_ID)		
						AND COLUMN_NAME NOT LIKE '%_id' --ANd COLUMN_NAME NOT In ('ALPHA_EMP_CODE','GENDER', 'EMP_FULL_NAME','IMAGE_NAME')

		END

	

END


