


--------------------------------------------------

--ADDED JIMIT 20012016 FOR LEAVE REGISTER WITH WAGES FORMF
---13/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
---------------------------------------------------
CREATE PROCEDURE [dbo].[P_RPT_LEAVE_REGISTER_WITH_WAGES_FORMF]
	 @CMP_ID 		NUMERIC
	,@FROM_DATE 	DATETIME
	,@TO_DATE 		DATETIME
	,@BRANCH_ID		NUMERIC 
	,@CAT_ID		NUMERIC	
	,@GRD_ID		NUMERIC
	,@TYPE_ID		NUMERIC 
	,@DEPT_ID		NUMERIC
	,@DESIG_ID		NUMERIC
	,@EMP_ID		NUMERIC
	,@CONSTRAINT	VARCHAR(MAX) = ''
	,@PBRANCH_ID VARCHAR(200) = '0'


AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON 
	
	DECLARE @LEAVE_ID AS NUMERIC
	
	
	
			CREATE TABLE #EMP_CONS 
			(      
				EMP_ID NUMERIC ,     
				BRANCH_ID NUMERIC,
				INCREMENT_ID NUMERIC
			)	
	
			EXEC SP_RPT_FILL_EMP_CONS @CMP_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRD_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID,@EMP_ID,@CONSTRAINT,0,0,0,0,0,0,0,0,0,0,0,0   
						
			
			CREATE TABLE #EMP_LEAVE
			(
				ROW_ID				NUMERIC		IDENTITY (1,1) NOT NULL,
				LEAVE_ID			NUMERIC,
				EMP_ID				NUMERIC,
				CMP_ID				NUMERIC,
				MONTH_NAME			VARCHAR(100),
				MONTH_DATE			DATETIME,
				LEAVE_CREDITED		NUMERIC(18,2),
				LEAVE_USE			NUMERIC(18,2),
				LEAVE_CLOSE		NUMERIC(18,2)				
			)
			CREATE NONCLUSTERED  INDEX IX_EMP_LEAVE_EMPID ON #EMP_LEAVE(EMP_ID,LEAVE_ID)
			
			
		
			SELECT @LEAVE_ID = LEAVE_ID FROM T0040_LEAVE_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND (ISNULL(LEAVE_CODE,'') LIKE '%SICK%' OR ISNULL(LEAVE_CODE,'') LIKE '%SL%' OR ISNULL(LEAVE_CODE,'') LIKE '%MEDICAL%')
			
			--INSERT INTO #EMP_LEAVE(CMP_ID,EMP_ID,LEAVE_ID)
			--SELECT @CMP_ID,@EMP_ID,LEAVE_ID FROM 
			--T0040_LEAVE_MASTER  WHERE CMP_ID = @CMP_ID AND (ISNULL(LEAVE_NAME,'') LIKE '%SICK%' OR ISNULL(LEAVE_NAME,'') LIKE '%SL%' OR ISNULL(LEAVE_NAME,'') LIKE '%MEDICAL%')
					
							
						INSERT INTO #EMP_LEAVE		
						SELECT  @LEAVE_ID,EC.EMP_ID,@CMP_ID,DBO.F_GET_MONTH_NAME(MONTH(@FROM_DATE)),@FROM_DATE,0,SUM(LEAVE_USED)AS LEAVE_USED,0
						FROM    T0140_LEAVE_TRANSACTION LT WITH (NOLOCK) INNER JOIN
								#EMP_CONS EC ON EC.EMP_ID = LT.EMP_ID														
						WHERE   CMP_ID = @CMP_ID AND For_Date > = @FROM_DATE and For_Date <= @TO_DATE  AND LEAVE_ID = @LEAVE_ID --AND Lt.EMP_ID = @EMP_ID
						GROUP BY  EC.EMP_ID									
											
						UPDATE 	EL
						SET EL.LEAVE_CLOSE = Q_1.LEAVE_CLOSING
						FROM #EMP_LEAVE EL INNER JOIN 
						(
							SELECT LEAVE_CLOSING,L1.Emp_ID,L1.Leave_ID
							FROM T0140_LEAVE_TRANSACTION L1 WITH (NOLOCK) INNER JOIN
								 ( SELECT MAX(FOR_DATE)AS FOR_DATE,Lt.EMP_ID,LEAVE_ID
								   FROM T0140_LEAVE_TRANSACTION LT WITH (NOLOCK) INNER JOIN
										#EMP_CONS EC on EC.EMP_ID = LT.Emp_ID				
								   WHERE	CMP_ID = @CMP_ID AND FOR_DATE < = @TO_DATE AND LEAVE_ID = @LEAVE_ID --AND LT.EMP_ID = @EMP_ID
								   GROUP BY	LT.EMP_ID,LT.LEAVE_ID
								  )Q ON Q.EMP_ID = L1.EMP_ID AND Q.LEAVE_ID = L1.LEAVE_ID
							)Q_1 ON Q_1.EMP_ID = EL.EMP_ID AND Q_1.LEAVE_ID = EL.LEAVE_ID 
						 
						
						UPDATE 	EL
						SET EL.LEAVE_CREDITED = Q.LEAVE_CREDITED
						FROM #EMP_LEAVE EL INNER JOIN 
							(
								 Select SUM(L1.Leave_Credit) AS LEAVE_CREDITED,L1.Emp_ID,L1.Leave_ID 
								FROM T0140_LEAVE_TRANSACTION L1 WITH (NOLOCK) INNER JOIN
									#EMP_CONS Ec on Ec.EMP_ID = L1.Emp_ID					
								WHERE	CMP_ID = @CMP_ID AND FOR_DATE < = @TO_DATE AND LEAVE_ID = @LEAVE_ID --AND L1.EMP_ID = @EMP_ID	
								GROUP BY L1.Emp_ID,L1.Leave_ID
							)Q ON Q.EMP_ID = EL.EMP_ID AND Q.LEAVE_ID = EL.LEAVE_ID 
	
		
				
				SELECT   LEAVE_ID,EMP_ID,CMP_ID,MONTH_NAME,MONTH_DATE,LEAVE_CREDITED,LEAVE_USE,LEAVE_CLOSE FROM #EMP_LEAVE 
				WHERE LEAVE_USE IS NOT NULL	AND LEAVE_CREDITED IS NOT NULL

				DROP TABLE #EMP_LEAVE



RETURN
