

---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P_RPT_INCENTIVE_SCHEME_EXPORT]
	 @Cmp_ID 		numeric
	,@From_Date 	datetime
	,@To_Date 		datetime
	,@Branch_ID 	varchar(max) = ''
	,@Cat_ID 		varchar(max) = ''
	,@Grd_ID 		varchar(max) = ''
	,@Type_ID 		varchar(max) = ''
	,@Dept_ID 		varchar(max) = ''
	,@Desig_ID 		varchar(max) = ''
	,@Constraint 	varchar(MAX) = ''
	,@mode			numeric = 0	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	
	 CREATE table #Emp_Cons 
	 (      
	   Emp_ID numeric ,     
	   Branch_ID numeric,
	   Increment_ID numeric    
	 )    
	 
	IF (DATEDIFF(D,@FROM_DATE, @To_Date) > 31)
		SET @To_Date = DATEADD(D,-1,DATEADD(M, 1,@FROM_DATE));
	
	
	
	-- GET EFFECTIVE DATE LETEST 
	DECLARE @INCS_EFFECTIVE_DATE DATETIME
	SELECT @INCS_EFFECTIVE_DATE=INC.EFFECTIVE_DATE  
	FROM   T0050_INCENTIVE_SCHEME INC WITH (NOLOCK)
		INNER JOIN (SELECT	MAX(EFFECTIVE_DATE) AS EFFECTIVE_DATE
					FROM	T0050_INCENTIVE_SCHEME I1 WITH (NOLOCK)
					WHERE EFFECTIVE_DATE <= Case When (YEAR(ISNULL(@TO_DATE,'1900-01-01')) < 1901) 
												then GETDATE() Else @TO_DATE END
					GROUP BY I1.CMP_ID) QRY1 ON INC.EFFECTIVE_DATE=QRY1.EFFECTIVE_DATE
					WHERE	INC.CMP_ID=@CMP_ID

	
	-- END --
	
	
	
	--EXEC SP_RPT_FILL_EMP_CONS  @Cmp_ID,@From_Date,@To_Date,@Branch_ID,@Cat_ID,@Grd_ID,@Type_ID,@Dept_ID,@Desig_ID ,0 ,@constraint ,0 ,0 ,0 ,0 ,0 ,0 
	exec SP_RPT_FILL_EMP_CONS_MULTIDROPDOWN @Cmp_ID,@From_Date,@To_Date,@Branch_ID,@Cat_ID,@Grd_ID,@Type_ID,@Dept_ID,@Desig_ID,0,@constraint,0,0,0,0,0,0,0,0,0,'0',0,0
  
		CREATE TABLE #INCENTIVE_EXPORT
		(	
			EMP_ID NUMERIC(18,0),
			EMP_CODE VARCHAR(50),
			EMP_FULL_NAME VARCHAR(500),
			BRANCH_ID  NUMERIC(18,0),
			BRANCH_NAME VARCHAR(100),
			DESIG_ID NUMERIC(18,0),
			DESIG_NAME VARCHAR(100),
			
			BRANCH_CODE VARCHAR(50), --ADDED ON 16122017 DUE TO MAX LENGTH OF BRANCH NAME || DESIGNATION NAME NOT ALLOW IN EXCEL SHEET
			DESIG_CODE VARCHAR(50) ----ADDED ON 16122017 DUE TO MAX LENGTH OF BRANCH NAME || DESIGNATION NAME NOT ALLOW IN EXCEL SHEET
			
		)
	
	
		INSERT INTO #INCENTIVE_EXPORT
		SELECT	E.EMP_ID,CAST(E.Alpha_Emp_Code AS VARCHAR),E.EMP_FULL_NAME AS EMP_FULL_NAME,
				BM.BRANCH_ID,BM.BRANCH_NAME,DGM.DESIG_ID,DGM.DESIG_NAME,BM.BRANCH_CODE,DGM.DESIG_CODE
		FROM	T0080_EMP_MASTER E WITH (NOLOCK)
				INNER JOIN #EMP_CONS EC ON E.EMP_ID=EC.EMP_ID
				INNER JOIN T0095_INCREMENT I WITH (NOLOCK) ON EC.Increment_ID=I.Increment_ID
				INNER JOIN T0030_BRANCH_MASTER BM WITH (NOLOCK) ON EC.BRANCH_ID = BM.BRANCH_ID
				LEFT OUTER JOIN T0040_DESIGNATION_MASTER DGM WITH (NOLOCK) ON I.DESIG_ID = DGM.DESIG_ID
		WHERE	E.CMP_ID=@CMP_ID
		--AND (E.EMP_LEFT_DATE BETWEEN @FROM_DATE AND @TO_DATE)
		ORDER BY BM.BRANCH_NAME,DGM.DESIG_NAME
		
		--RETURN
		
		CREATE TABLE #TMP_EXPORT
		(
			EMP_ID NUMERIC(18,0),
			EMP_CODE VARCHAR(50),
			EMP_FULL_NAME VARCHAR(100),
			BRANCH_NAME VARCHAR(100),
			DESIG_NAME VARCHAR(100),
			--TYPE VARCHAR(2),
			MONTH NUMERIC(18,0),
			YEAR NUMERIC(18,0),
			PARA_NAME VARCHAR(MAX),
			VALUE NUMERIC(18,2),
			BRANCH_CODE VARCHAR(50), ----ADDED ON 16122017 DUE TO MAX LENGTH OF BRANCH NAME || DESIGNATION NAME NOT ALLOW IN EXCEL SHEET
			DESIG_CODE VARCHAR(50) ----ADDED ON 16122017 DUE TO MAX LENGTH OF BRANCH NAME || DESIGNATION NAME NOT ALLOW IN EXCEL SHEET
		
		)
		--CREATE TABLE #TMP_EXPORT_FOR_INCENTIVE
		--(
		--	EMP_ID NUMERIC(18,0),
		--	EMP_CODE VARCHAR(50),
		--	EMP_FULL_NAME VARCHAR(100),
		--	BRANCH_NAME VARCHAR(100),
		--	DESIG_NAME VARCHAR(100),
		--	TYPE VARCHAR(2),
		--	MONTH NUMERIC(18,0),
		--	YEAR NUMERIC(18,0),
		--	PARA_NAME VARCHAR(100),
		--	VALUE NUMERIC(18,2),
		--	SLAB_TYPE TINYINT,
		--	CALC_TYPE VARCHAR(100),
		--	CALC_ON VARCHAR(100)
			
		--)
		
		
		DECLARE @BRANCH_NAME AS VARCHAR(128)
		DECLARE @DESIG_NAME AS VARCHAR(128)
		DECLARE @BRNCH_ID AS NUMERIC(18,0)
		DECLARE @DESIGN_ID AS NUMERIC(18,0)
		DECLARE @COLS VARCHAR(MAX)
		DECLARE @QUERY VARCHAR(MAX)
		DECLARE @QUERY_SCHEME VARCHAR(MAX)
		
		
		DECLARE CURINCENTIVE CURSOR FAST_FORWARD FOR                    
		SELECT DISTINCT IE.BRANCH_ID,IE.DESIG_ID -- ,IE.BRANCH_NAME,IE.DESIG_NAME
		FROM	#INCENTIVE_EXPORT IE
				INNER JOIN (SELECT DATA AS BRANCH_ID FROM dbo.Split(@Branch_ID,'#') T Where Data <> '') B ON IE.BRANCH_ID=B.BRANCH_ID
				INNER JOIN (SELECT DATA AS DESIG_ID FROM dbo.Split(@DESIG_ID,'#') T Where Data <> '') D ON IE.DESIG_ID=D.DESIG_ID
				
		ORDER BY IE.BRANCH_ID,IE.DESIG_ID
		
		OPEN CURINCENTIVE
		FETCH NEXT FROM CURINCENTIVE INTO  @BRNCH_ID,@DESIGN_ID --, @BRANCH_NAME, @DESIG_NAME
		WHILE @@FETCH_STATUS = 0                    
		BEGIN           
			         
			--SET @BASIC_SALARY = 0
			IF EXISTS(SELECT 1 
						FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
								CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
								CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
						WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID)
				BEGIN 		
			
					-- PARA_TYPE: PARAMETER(P) (PARAMETER WISE CALCULATION)
					
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'PM ' + ISP.PARA_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
							CROSS JOIN (SELECT DISTINCT SCHEME_ID,PARA_NAME FROM T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK) WHERE ISNULL(P_FORMULA,'') = '') ISP
					WHERE	EXISTS (SELECT 1 
									FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
											CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
											CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
									WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISP.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
							AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID 
							
					
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'FM ' + ISP.FIELD_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
							CROSS JOIN (
							SELECT DISTINCT SCHEME_ID, FIELD_NAME FROM T0055_INCENTIVE_SCHEME_PARA T WITH (NOLOCK)
							CROSS APPLY (SELECT ID, SUBSTRING(DATA, CHARINDEX('{',DATA)+1, LEN(DATA)) AS FIELD_NAME
							FROM DBO.SPLIT(T.P_FORMULA, '}') WHERE CHARINDEX('{', DATA) > 0) T1
							WHERE ISNULL(T.P_Formula,'') <> ''
							) ISP
					WHERE	EXISTS (SELECT 1 
									FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
											CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
											CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
									WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISP.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
							AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID 
							
					-- END --
			
			
					-- PARA_TYPE:INCENTIVE(I), SLAB_TYPE:PERCENTAGE, CALCULATION_TYPE:PERCENT, CALCULATION_ON:('NET LABOR','ACHIEVEMENT') || SLAB_TYPE:FIXED (DIRECT INCENTIVE WISE CALCULATION)
						INSERT INTO #TMP_EXPORT
						SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'IM ' + ISI.INCENTIVE_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
						FROM	#INCENTIVE_EXPORT I 
								CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
											FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
											WHERE	INC.SLAB_TYPE=1 AND INC.CALC_TYPE='Percent' AND INC.CALC_ON IN ('Net Labor', 'Achievement','Eligible Incentive')) ISI
								--CROSS JOIN (SELECT DISTINCT SCHEME_ID,EFFECTIVE_DATE FROM T0050_INCENTIVE_SCHEME) ISM --ADDED BY RAJPUT 19072017
						WHERE	EXISTS (SELECT 1 
										FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
												CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
												CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
										WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
								AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
			
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'OT ' + ISI.CALC_ON,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
							CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
										FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
										WHERE	INC.Slab_Type=1 AND INC.Calc_Type='Percent' AND INC.CALC_ON IN ('Net Labor', 'Achievement')) ISI
					WHERE	EXISTS (SELECT 1 
									FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
											CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
											CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
									WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
							AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
					
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'IM ' + ISI.INCENTIVE_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
								CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
											FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
											WHERE	INC.SLAB_TYPE=1 AND INC.CALC_TYPE='Fixed') ISI
					WHERE	EXISTS (SELECT 1 
										FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
												CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
												CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
										WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
								AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
					
					-- PARA_TYPE:INCENTIVE(I), SLAB_TYPE:MARKS, CALCULATION_TYPE:FIXED ADDED ON 16102017
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'IM ' + ISI.INCENTIVE_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
								CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
											FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
											WHERE	INC.SLAB_TYPE=0 AND INC.CALC_TYPE='Fixed') ISI
					WHERE	EXISTS (SELECT 1 
										FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
												CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
												CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
										WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
								AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
								AND NOT EXISTS(SELECT 1 FROM T0055_INCENTIVE_SCHEME_PARA P WITH (NOLOCK) WHERE  ISI.Scheme_ID=P.Scheme_ID)
					-- END --
					
					-- PARA_TYPE:INCENTIVE(I), SLAB_TYPE:NOs,CALCULATION_TYPE:RATE,CALCULATION_ON:('PAID SERVICE','VEHICLE')
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'IM ' + ISI.INCENTIVE_NAME,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
							CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
										FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
										WHERE	INC.SLAB_TYPE=2 AND INC.CALC_TYPE='Rate' AND INC.CALC_ON IN ('Paid Service', 'Vehicle')
										) ISI
					WHERE	EXISTS (SELECT 1 
									FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
											CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
											CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
									WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
							AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
							AND NOT EXISTS(SELECT 1 FROM T0055_INCENTIVE_SCHEME_PARA P WITH (NOLOCK) WHERE  ISI.Scheme_ID=P.Scheme_ID)
					
					
					INSERT INTO #TMP_EXPORT
					SELECT	I.EMP_ID,CAST(I.EMP_CODE AS VARCHAR),I.EMP_FULL_NAME,I.BRANCH_NAME,I.DESIG_NAME,MONTH(@From_Date) AS MONTH,YEAR(@From_Date) AS YEAR,'OM ' +ISI.CALC_ON,0 AS VALUE,I.BRANCH_CODE,I.DESIG_CODE
					FROM	#INCENTIVE_EXPORT I 
							CROSS JOIN (SELECT DISTINCT SCHEME_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON 
										FROM	T0055_INCENTIVE_SCHEME_INC  INC WITH (NOLOCK)
										WHERE	INC.Slab_Type=2 AND INC.Calc_Type='Rate' AND INC.CALC_ON IN ('Paid Service', 'Vehicle')) ISI
					WHERE	EXISTS (SELECT 1 
									FROM	T0050_INCENTIVE_SCHEME SC WITH (NOLOCK)
											CROSS APPLY (SELECT SCHEME_ID, Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Branch_ID IS NOT NULL) SCB
											CROSS APPLY (SELECT SCHEME_ID, Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SCD WITH (NOLOCK) WHERE SC.Scheme_ID=SCD.Scheme_ID AND Desig_ID IS NOT NULL) SCD
									WHERE	SCB.Branch_ID=@BRNCH_ID AND SCD.Desig_ID=@DESIGN_ID AND SC.Scheme_ID=ISI.Scheme_ID AND SC.EFFECTIVE_DATE=@INCS_EFFECTIVE_DATE)
							AND I.BRANCH_ID=@BRNCH_ID AND I.DESIG_ID=@DESIGN_ID
							AND NOT EXISTS(SELECT 1 FROM T0055_INCENTIVE_SCHEME_PARA P WITH (NOLOCK) WHERE  ISI.Scheme_ID=P.Scheme_ID)
					--- END ---
					
					
					
					-- FOR PARAMETER 
					SET @COLS = NULL
					SELECT	@COLS = COALESCE(@COLS + ',', '') +'['+ PARA_NAME  + ']'
					FROM	(SELECT DISTINCT PARA_NAME FROM #TMP_EXPORT) T
					SET @QUERY = 
									'SELECT	Emp_Code as Emp_Code,Emp_Full_Name as Emp_Name,Branch_Name as Branch,Desig_Name as Designation,Year,Month,Branch_Code,Desig_Code,' + @COLS + '
									FROM	(
												SELECT	Emp_Code,Emp_Full_Name,Branch_Name,Desig_Name,Year,Month,Branch_Code,Desig_Code,Para_Name,Value
												FROM	dbo.#TMP_EXPORT
											) AS ST
											PIVOT
											(
												SUM(Value) FOR Para_Name IN (' + @COLS + ')
											) AS PT'

					
					EXEC(@QUERY)
					
					--SELECT * FROM #TMP_EXPORT ORDER BY EMP_ID,PARA_NAME
					TRUNCATE TABLE #TMP_EXPORT
					--TRUNCATE TABLE #TMP_EXPORT_FOR_INCENTIVE
				
				
				END
			FETCH NEXT FROM CURINCENTIVE INTO  @BRNCH_ID,@DESIGN_ID--, @BRANCH_NAME, @DESIG_NAME
	    END                    
		CLOSE CURINCENTIVE                    
		DEALLOCATE CURINCENTIVE
	
		
		

