

-----------------------------------------------

--ADDED JIMIT 09022015------
---SALARY REGISTER FORM-D FOR PUNJAB---

---------------------------------------------
CREATE PROCEDURE [dbo].[P_RPT_EMP_ATTENDANCE_SALARY_REGISTER_FormD]      
	 @COMPANY_ID		NUMERIC  
	,@FROM_DATE		DATETIME
	,@TO_DATE 		DATETIME
	,@BRANCH_ID		NUMERIC	
	,@GRADE_ID 		NUMERIC
	,@TYPE_ID 		NUMERIC
	,@DEPT_ID 		NUMERIC
	,@DESIG_ID 		NUMERIC
	,@EMP_ID 		NUMERIC
	,@CONSTRAINT	VARCHAR(MAX)
	,@CAT_ID        NUMERIC = 0
	,@IS_COLUMN		TINYINT = 0
	,@SALARY_CYCLE_ID  NUMERIC  = 0
	,@SEGMENT_ID NUMERIC = 0 
	,@VERTICAL NUMERIC = 0 
	,@SUBVERTICAL NUMERIC = 0 
	,@SUBBRANCH NUMERIC = 0 
	,@SUMMARY VARCHAR(MAX)=''
	,@PBRANCH_ID VARCHAR(200) = '0'
	,@ORDER_BY   VARCHAR(30) = 'CODE' 
	,@REPORT_CALL VARCHAR(20) = 'IN-OUT'   
    ,@WEEKOFF_ENTRY VARCHAR(1) = 'Y'
    ,@STATE_ID NUMERIC(18,0) = 0
    
AS      
  		SET NOCOUNT ON 
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		SET ARITHABORT ON 


	CREATE TABLE #EMP_CONS 
	(      
		EMP_ID NUMERIC ,     
		BRANCH_ID NUMERIC,
		INCREMENT_ID NUMERIC
	)	
	EXEC SP_RPT_FILL_EMP_CONS @COMPANY_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRADE_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID,@EMP_ID,@CONSTRAINT,0,0,0,0,0,0,0,0,0,0,0,0   
	
	CREATE TABLE #CROSSTAB       
		(   
			EMP_ID NUMERIC,
			CMP_ID	NUMERIC,
			EMP_CODE VARCHAR(100) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,       
			NAME_OF_THE_EMPLOYEE   VARCHAR(200) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,
			FATHER_NAME				VARCHAR(200) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,
			[MONTH]   VARCHAR(200) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,
			[YEAR]    NUMERIC(18,0),
			WAGES_FIXED	NUMERIC(18,2),
			ARREARS_FROM_LAST_MONTH NUMERIC(18,2),
			WAGES_EARNED_DURING_MONTH NUMERIC(18,2),
			ORDINARY_OVERTIME NUMERIC(18,2),
			WAGES_DUE NUMERIC(18,2),
			TOTAL_DEDUCTIONS NUMERIC(18,2),
			ADVANCE_MADE_ON_DATE	VARCHAR(15) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,
			Payment_Made		numeric(18,0),
			PAYMENT_MODE	VARCHAR(15) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,
			STATE_NAME		VARCHAR(50) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
			,DESIG_DIS_NO    NUMERIC(18,0) DEFAULT 0 
			,ENROLL_NO       VARCHAR(50)	 COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS DEFAULT ''	
			,Designation		varchar(100) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS DEFAULT ''
		
		)    
		
	DECLARE @STATE_NAME VARCHAR(50)
	SELECT @STATE_NAME = ISNULL(STATE_NAME,'') FROM T0020_STATE_MASTER WITH (NOLOCK) WHERE STATE_ID = @STATE_ID AND CMP_ID = @COMPANY_ID
		
	INSERT INTO	#CROSSTAB(EMP_ID,CMP_ID,EMP_CODE,NAME_OF_THE_EMPLOYEE,FATHER_NAME,[MONTH],[YEAR],WAGES_FIXED,ARREARS_FROM_LAST_MONTH,WAGES_EARNED_DURING_MONTH,ORDINARY_OVERTIME,WAGES_DUE
							,TOTAL_DEDUCTIONS,ADVANCE_MADE_ON_DATE,Payment_Made,PAYMENT_MODE,STATE_NAME,DESIG_DIS_NO,ENROLL_NO,Designation)
							 
	SELECT		E.EMP_ID,E.CMP_ID,E.ALPHA_EMP_CODE,(E.Alpha_Emp_Code + ' - ' + E.EMP_FULL_NAME) AS EMP_FULL_NAME ,E.FATHER_NAME,Datename(Month,convert(nvarchar,@FROM_DATE)),
				YEAR(@FROM_DATE),0,0,0,0,0,0,NULL,0,0,@STATE_NAME,DNM.DESIG_DIS_NO,E.ENROLL_NO,dnm.Desig_Name
				
	FROM		T0080_EMP_MASTER E 	WITH (NOLOCK) INNER JOIN
					( SELECT I.EMP_ID,I.BASIC_SALARY,I.CTC,I.INC_BANK_AC_NO,PAYMENT_MODE,I.BRANCH_ID,I.GRD_ID,I.DEPT_ID,I.DESIG_ID,I.TYPE_ID,I.CAT_ID,I.VERTICAL_ID,I.SUBVERTICAL_ID,I.SUBBRANCH_ID,I.SEGMENT_ID,I.CENTER_ID FROM T0095_INCREMENT I WITH (NOLOCK) INNER JOIN 
						( SELECT MAX(INCREMENT_ID) AS INCREMENT_ID , EMP_ID FROM T0095_INCREMENT WITH (NOLOCK)
						WHERE INCREMENT_EFFECTIVE_DATE <= @TO_DATE
						AND CMP_ID = @COMPANY_ID
						GROUP BY EMP_ID  ) QRY ON
						I.EMP_ID = QRY.EMP_ID	AND I.INCREMENT_ID = QRY.INCREMENT_ID )INC_QRY ON 
					E.EMP_ID = INC_QRY.EMP_ID INNER JOIN
					#EMP_CONS EC ON E.EMP_ID = EC.EMP_ID INNER JOIN
					T0010_COMPANY_MASTER C WITH (NOLOCK) ON   C.CMP_ID = E.CMP_ID LEFT OUTER JOIN 
					T0040_DESIGNATION_MASTER dnm WITH (NOLOCK) on Inc_Qry.Desig_Id = dnm.Desig_ID
	
	
	------------------------------SALARY COMPONENTS-------------------------------
	
			UPDATE  C 
			SET     C.WAGES_FIXED = Q.GROSS_SALARY, C.WAGES_EARNED_DURING_MONTH = Q.WAGES_EARNED_DURING_MONTH
					,C.ORDINARY_OVERTIME = Q.OT,C.TOTAL_DEDUCTIONS = Q.TOTAL_DEDU_AMOUNT
					,C.PAYMENT_MADE = Q.NET_AMOUNT,C.ARREARS_FROM_LAST_MONTH = Q.AREAR_GROSS
					,C.WAGES_DUE = 	Q.WAGES_EARNED_DURING_MONTH + Q.OT	
					,C.PAYMENT_MODE = Q.Payment_Mode			
			FROM 	#CROSSTAB C INNER JOIN
					(							
						SELECT  I.GROSS_SALARY,MS.Gross_Salary as WAGES_EARNED_DURING_MONTH
								,SUM(ISNULL(OT_AMOUNT,0)) AS OT,
								TOTAL_DEDU_AMOUNT,NET_AMOUNT,Payment_Mode,MS.EMP_ID,MS.CMP_ID,(AREAR_GROSS + MS.Settelement_Amount) AS AREAR_GROSS
						FROM	T0200_MONTHLY_SALARY MS WITH (NOLOCK) INNER JOIN
								T0095_INCREMENT I WITH (NOLOCK) ON I.INCREMENT_ID = MS.INCREMENT_ID AND I.EMP_ID=MS.EMP_ID						
						WHERE	month(Month_End_Date) = month(@To_date) and YEAR(Month_End_Date) = YEAR(@To_date)--MONTH_ST_DATE BETWEEN @FROM_DATE AND @TO_DATE
						GROUP BY MS.EMP_ID,MS.CMP_ID,I.GROSS_SALARY ,MS.Gross_Salary,TOTAL_DEDU_AMOUNT,NET_AMOUNT,AREAR_GROSS,SETTELEMENT_AMOUNT,Payment_Mode
			)Q ON Q.EMP_ID = C.EMP_ID AND Q.CMP_ID = C.CMP_ID
			
	
			UPDATE  C 
			SET    C.ADVANCE_MADE_ON_DATE = Q.FOR_DATE
			FROM 	#CROSSTAB C INNER JOIN
					(							
						SELECT  CONVERT(VARCHAR,FOR_DATE ,103)AS FOR_DATE,EMP_ID,CMP_ID
						FROM	T0100_ADVANCE_PAYMENT WITH (NOLOCK)
						WHERE	FOR_DATE >= @FROM_DATE AND FOR_DATE <= @TO_DATE
								AND ADV_AMOUNT > 0
						GROUP BY EMP_ID,CMP_ID,FOR_DATE								
			)Q ON Q.EMP_ID = C.EMP_ID AND Q.CMP_ID = C.CMP_ID
	
	---------------------------------ENDED------------------------------------------
	
		
		
		ALTER TABLE  #CROSSTAB ADD SIGNATURE_OF_EMPLOYEE VARCHAR
		ALTER TABLE  #CROSSTAB ADD SIGNATURE_OF_EMPLOYER VARCHAR
		ALTER TABLE  #CROSSTAB ADD TOTAL_BALANCE_CARRIED_OVER VARCHAR
		ALTER TABLE  #CROSSTAB ADD REMARKS VARCHAR
		
		ALTER TABLE  #CROSSTAB DROP COLUMN EMP_ID
		ALTER TABLE  #CROSSTAB DROP COLUMN CMP_ID
		
		
		
		UPDATE #CROSSTAB SET EMP_CODE = '="' + EMP_CODE + '"'
		DECLARE @VAL VARCHAR(300)
		--SET @VAL ='
		SELECT ROW_NUMBER() OVER(ORDER BY  @ORDER_BY  ASC) AS SR_NO,* FROM #CROSSTAB ORDER BY  		
		CASE WHEN @Order_By ='Enroll_No' THEN RIGHT(REPLICATE('0',21) + CAST(#CROSSTAB.Enroll_No AS VARCHAR), 21) 
							WHEN @Order_By='Name' THEN #CROSSTAB.NAME_OF_THE_EMPLOYEE
							When @Order_By = 'Designation' then (CASE WHEN #CROSSTAB.Desig_dis_No  = 0 THEN #CROSSTAB.Designation ELSE RIGHT(REPLICATE('0',21) + CAST(#CROSSTAB.Desig_dis_No AS VARCHAR), 21)   END)   
							---ELSE RIGHT(REPLICATE(N' ', 500) + #CTCMast.Emp_Code, 500) 
						End,Case When IsNumeric(Replace(Replace(#CROSSTAB.EMP_CODE,'="',''),'"','')) = 1 then Right(Replicate('0',21) + Replace(Replace(#CROSSTAB.Emp_Code,'="',''),'"',''), 20)
								 When IsNumeric(Replace(Replace(#CROSSTAB.Emp_Code,'="',''),'"','')) = 0 then Left(Replace(Replace(#CROSSTAB.Emp_Code,'="',''),'"','') + Replicate('',21), 20)
								 Else Replace(Replace(#CROSSTAB.Emp_Code,'="',''),'"','') End 
		
		
		--EXEC(@VAL)
		DROP TABLE #CROSSTAB
	
	
	

