

-- =============================================
-- Author:		<Author,,Jimit Soni>
-- Create date: <Create Date,,26082019>
-- Description:	<Description,,For Getting Salary Register State wise For WCL>
---28/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P_SALARY_REGISTER_STATE_WISE]
	 @COMPANY_ID			NUMERIC
	,@FROM_DATE			DATETIME
	,@TO_DATE			DATETIME 
	,@BRANCH_ID			NUMERIC   = 0
	,@CAT_ID			NUMERIC  = 0
	,@GRADE_ID			NUMERIC = 0
	,@TYPE_ID			NUMERIC  = 0
	,@DEPT_ID			NUMERIC  = 0
	,@DESIG_ID			NUMERIC = 0
	,@EMP_ID			NUMERIC  = 0
	,@CONSTRAINT		VARCHAR(MAX) = ''	
	,@SALARY_CYCLE_ID	NUMERIC = 0
	,@SEGMENT_ID		NUMERIC = 0		 
	,@VERTICAL_ID		NUMERIC = 0		 
	,@SUBVERTICAL_ID	NUMERIC = 0	 
	,@SUBBRANCH_ID		NUMERIC = 0		 
	,@FLAG				NUMERIC = 0		

AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	
	DECLARE @TRANSACTION_ID NUMERIC
	SET		@TRANSACTION_ID = 0
	
	DECLARE @MONTH AS NUMERIC(18,0)
	DECLARE @YEAR AS NUMERIC(18,0)
	
	
	CREATE TABLE #TEMP_REPORT_LABEL
	(
		ROW_ID			NUMERIC(18, 0) NOT NULL,
		LABEL_NAME		VARCHAR(200) NOT NULL,
		INCOME_TAX_ID	NUMERIC(18, 0) NULL,
		IS_ACTIVE		VARCHAR(1) NULL,
		FLAG			VARCHAR(1)
	)
		
	CREATE TABLE #TEMP_SALARY_MUSTER_REPORT		
	(
		EMP_ID			NUMERIC(18, 0) NOT NULL,
		CMP_ID			NUMERIC(18, 0) NOT NULL,
		TRANSACTION_ID	NUMERIC(18, 0) NOT NULL DEFAULT (0),
		MONTH			NUMERIC(18, 0) NOT NULL,
		YEAR			NUMERIC(18, 0) NOT NULL,
		LABEL_NAME		VARCHAR(200)   NOT NULL,
		AMOUNT			NUMERIC(18, 2) NULL,
		VALUE_STRING	VARCHAR(250)   NOT NULL DEFAULT (''),
		INCOME_TAX_ID	NUMERIC(18, 0) NULL,
		ROW_ID			NUMERIC(18, 0) NULL,
		DEPT_ID			NUMERIC(18,0),
		DEPT_NAME 		VARCHAR(200),
		CAT_ID			NUMERIC(18,0),
		STATE_NAME		VARCHAR(200),
		FLAG			CHAR	default ''	
	)
		
	IF @BRANCH_ID = 0
		SET @BRANCH_ID = NULL
	IF @CAT_ID = 0
		SET @CAT_ID = NULL		 
	IF @TYPE_ID = 0
		SET @TYPE_ID = NULL
	IF @DEPT_ID = 0
		SET @DEPT_ID = NULL
	IF @GRADE_ID = 0
		SET @GRADE_ID = NULL
	IF @EMP_ID = 0
		SET @EMP_ID = NULL		
	IF @DESIG_ID = 0
		SET @DESIG_ID = NULL
	IF @SALARY_CYCLE_ID = 0
		SET @SALARY_CYCLE_ID = NULL
	IF @SEGMENT_ID = 0		 
		SET @SEGMENT_ID = NULL
	IF @VERTICAL_ID = 0		 
		SET @VERTICAL_ID = NULL
	IF @SUBVERTICAL_ID = 0	 
		SET @SUBVERTICAL_ID = NULL	
	IF @SUBBRANCH_ID = 0	 
		SET @SUBBRANCH_ID = NULL	
		
	
	SET @MONTH = MONTH(@TO_DATE)
	SET @YEAR = YEAR(@TO_DATE)
	  
	EXEC Salary_register_Lable_State_Wise @COMPANY_ID ,@MONTH , @YEAR
	
	CREATE TABLE #EMP_CONS 
	 (      
	   EMP_ID		NUMERIC ,     
	   BRANCH_ID	NUMERIC,
	   INCREMENT_ID NUMERIC    
	 )   
	 
	 EXEC SP_RPT_FILL_EMP_CONS  @COMPANY_ID,@FROM_DATE,@TO_DATE,@BRANCH_ID,@CAT_ID,@GRADE_ID,@TYPE_ID,@DEPT_ID,@DESIG_ID ,@EMP_ID ,@CONSTRAINT ,0 ,@SALARY_CYCLE_ID ,
								@SEGMENT_ID ,@VERTICAL_ID ,@SUBVERTICAL_ID ,@SUBBRANCH_ID 

	
	
			INSERT INTO #TEMP_SALARY_MUSTER_REPORT(EMP_ID, CMP_ID, TRANSACTION_ID, MONTH, YEAR, LABEL_NAME, AMOUNT, VALUE_STRING,ROW_ID,Flag)					
			SELECT	MS.EMP_ID, MS.CMP_ID, @TRANSACTION_ID, @MONTH, @YEAR, 'STRENGTH', 1,'',1,''
			FROM	T0200_MONTHLY_SALARY MS WITH (NOLOCK)
					INNER JOIN #EMP_CONS EC ON MS.EMP_ID = EC.EMP_ID  					
			WHERE	MS.CMP_ID = @COMPANY_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR 					
			UNION ALL
			SELECT	MS.EMP_ID, MS.CMP_ID, @TRANSACTION_ID, @MONTH, @YEAR, 'SALARY DAYS', ISNULL(SAL_CAL_DAYS,0),'',2,''
			FROM	T0200_MONTHLY_SALARY MS WITH (NOLOCK)
					INNER JOIN #EMP_CONS EC ON MS.EMP_ID = EC.EMP_ID  					
			WHERE	MS.CMP_ID = @COMPANY_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR 					
			UNION ALL
			SELECT	MS.EMP_ID, MS.CMP_ID, @TRANSACTION_ID, @MONTH, @YEAR, 'BASIC', ISNULL(SALARY_AMOUNT,0),'',3,'I'
			FROM	T0200_MONTHLY_SALARY MS WITH (NOLOCK)
					INNER JOIN #EMP_CONS EC ON MS.EMP_ID = EC.EMP_ID  					
			WHERE	MS.CMP_ID = @COMPANY_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR 				
			UNION ALL
			SELECT	EC.EMP_ID, @COMPANY_ID, @TRANSACTION_ID, @MONTH, @YEAR, LABEL_NAME, 0,'',ROW_ID,FLAG
			FROM	#TEMP_REPORT_LABEL TRL 
					CROSS JOIN #EMP_CONS EC 
					INNER JOIN T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON EC.EMP_ID=MS.EMP_ID
			WHERE	ROW_ID > 5 AND CMP_ID = @COMPANY_ID AND MONTH(MONTH_END_DATE) = @MONTH AND YEAR(MONTH_END_DATE) = @YEAR					
				
			UPDATE T 
			SET		AMOUNT = T.AMOUNT + Q.AMOUNT 
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
										SELECT  (ISNULL(SUM(MSS.S_Salary_Amount),0)) AS AMOUNT,TMR.EMP_ID
										FROM	#TEMP_SALARY_MUSTER_REPORT TMR 						
												LEFT OUTER JOIN T0201_MONTHLY_SALARY_SETT MSS WITH (NOLOCK) ON  TMR.EMP_Id = MSS.EMP_ID																							
										WHERE	MONTH(MSS.S_Eff_Date) = @MONTH AND YEAR(MSS.S_Eff_Date) = @YEAR	AND LABEL_NAME = 'BASIC' and MSS.Cmp_ID= @Company_Id		
										GROUP BY 		TMR.EMP_ID							
									)Q ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'BASIC'
				WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'BASIC'
			
	

			UPDATE	T 
			SET		AMOUNT = Q.AMOUNT 
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(ReimAmount,0)  AS AMOUNT,MAD.EMP_ID,AD_SORT_NAME
									FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK)
											INNER JOIN	T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID  
											INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MAD.EMP_ID = TMR.EMP_ID AND LABEL_NAME = 'LTA Claim'		
											INNER JOIN	T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON MAD.SAL_TRAN_ID = MS.SAL_TRAN_ID								
									WHERE	AD_ACTIVE = 1 ANd ISNULL(ReimShow,0) = 1   AND  MONTH(To_date) = @MONTH AND YEAR(To_date) = @YEAR and mad.Cmp_ID= @Company_Id										
								)Q  ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'LTA Claim'		
				WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'LTA Claim' AND FLAG = 'R'	
			
			UPDATE	T 
			SET		AMOUNT = Q.AMOUNT 
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(Leave_Salary_Amount,0)  AS AMOUNT,MS.EMP_ID
									FROM	T0200_MONTHLY_SALARY MS	WITH (NOLOCK)										
											INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MS.EMP_ID = TMR.EMP_ID AND LABEL_NAME = 'Leave Encashment'													
									WHERE	MONTH(Month_End_Date) = @MONTH AND YEAR(Month_End_Date) = @YEAR 	and Ms.Cmp_ID= @Company_Id										
								)Q  ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'Leave Encashment'		
			WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'Leave Encashment' 
			
			UPDATE	T 
			SET		AMOUNT = Q.AMOUNT 
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  (ISNULL(OT_AMOUNT,0) + ISNULL(M_WO_OT_Amount,0) + ISNULL(M_HO_OT_Amount,0))   AS AMOUNT,MS.EMP_ID
									FROM	T0200_MONTHLY_SALARY MS	WITH (NOLOCK)										
											INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MS.EMP_ID = TMR.EMP_ID AND LABEL_NAME = 'OT Amount'													
									WHERE	MONTH(Month_End_Date) = @MONTH AND YEAR(Month_End_Date) = @YEAR and Ms.Cmp_ID= @Company_Id										
								)Q  ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'OT Amount'		
				WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'OT Amount' 

			UPDATE	T 
			SET		AMOUNT = Q.AMOUNT 
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(Advance_Amount,0) AS AMOUNT,MS.EMP_ID
									FROM	T0200_MONTHLY_SALARY MS	WITH (NOLOCK)										
											INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MS.EMP_ID = TMR.EMP_ID AND LABEL_NAME = 'Advance'													
									WHERE	MONTH(Month_End_Date) = @MONTH AND YEAR(Month_End_Date) = @YEAR and Ms.Cmp_ID= @Company_Id									
								)Q  ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'Advance'		
				WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'Advance' 

			UPDATE	T 
			SET		AMOUNT = ISNULL(Q.AMOUNT,0) + ISNULL(Q1.AMOUNT,0)
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  (ISNULL(MAD.M_AD_AMOUNT,0) + ISNULL(M_AREAR_AMOUNT,0) + ISNULL(M_AREAR_AMOUNT_Cutoff,0)) AS AMOUNT,MAD.EMP_ID,AD_SORT_NAME
									FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK)
											INNER JOIN	T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID  
											INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MAD.EMP_ID = TMR.EMP_ID AND LABEL_NAME = AD_SORT_NAME 
											INNER JOIN	T0200_MONTHLY_SALARY MS WITH (NOLOCK) ON MAD.SAL_TRAN_ID = MS.SAL_TRAN_ID								
									WHERE	AD_ACTIVE = 1  AND  MONTH(To_date) = @MONTH AND YEAR(To_date) = @YEAR and Mad.Cmp_ID= @Company_Id					
								)Q  ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = Q.AD_SORT_NAME
					LEFT OUTER JOIN (
										SELECT  (ISNULL(SUM(MAd.M_Ad_Amount),0)) AS AMOUNT,MAD.EMP_ID,AD_SORT_NAME
										FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK)
												INNER JOIN	T0050_AD_MASTER AD WITH (NOLOCK) ON MAD.AD_ID = AD.AD_ID  
												INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON MAD.EMP_ID = TMR.EMP_ID AND LABEL_NAME = AD_SORT_NAME 								
												INNER JOIN T0201_MONTHLY_SALARY_SETT MSS WITH (NOLOCK) ON MAD.S_Sal_Tran_ID = MSS.S_Sal_Tran_ID																								
										WHERE	AD_ACTIVE = 1  AND  MONTH(MSS.S_Eff_Date) = @MONTH AND YEAR(MSS.S_Eff_Date) = @YEAR	and Mad.Cmp_ID= @Company_Id
										GROUP BY 		MAD.EMP_ID,AD_SORT_NAME								
									)Q1 ON Q1.Emp_ID = T.EMP_ID AND LABEL_NAME = Q1.AD_SORT_NAME
				WHERE T.EMP_ID = Q.EMP_Id --AND T.LABEL_NAME = Q.AD_SORT_NAME
			
			
			
			UPDATE  T
			SET		DEPT_ID = DM.DEPT_ID,
					DEPT_NAME = DM.DEPT_NAME,
					CAT_ID = CM.CAT_ID,
					STATE_NAME = CM.CAT_DESCRIPTION					
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN	#EMP_CONS EC ON EC.EMP_ID = T.EMP_ID
					INNER JOIN	T0095_INCREMENT I ON I.INCREMENT_ID = EC.INCREMENT_ID AND I.EMP_ID = EC.EMP_ID
					INNER JOIN	T0040_DEPARTMENT_MASTER DM ON DM.DEPT_ID = I.DEPT_ID
					INNER JOIN	T0030_CATEGORY_MASTER CM ON CM.CAT_ID = I.CAT_ID
			
			

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = OTHER_ALLOW_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
						AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'OTH A' and sg.Cmp_ID= @Company_Id

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = ISNULL(SG.OT_AMOUNT,0) + ISNULL(SG.M_WO_OT_Amount,0) + ISNULL(SG.M_HO_OT_AMOUNT,0)
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID 
					AND MONTH(SG.MONTH_END_DATE) = @MONTH AND YEAR(SG.MONTH_END_DATE) = @YEAR 				
			WHERE   LABEL_NAME = 'OT AMT' and sg.Cmp_ID= @Company_Id	

			--UPDATE	#TEMP_SALARY_MUSTER_REPORT
			--SET		AMOUNT = GROSS_SALARY
			--FROM	T0200_MONTHLY_SALARY SG   
			--		INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID  
			--		AND MONTH(SG.MONTH_END_DATE) = @MONTH AND YEAR(SG.MONTH_END_DATE) = @YEAR
			--WHERE   LABEL_NAME = 'GROSS'
			
			UPDATE  T
			SET		AMOUNT = ISNULL(Q.AMOUNT,0) + ISNULL(Q1.AMOUNT,0) + ISNULL(Q2.AMOUNT,0) + ISNULL(Q3.AMOUNT,0) + ISNULL(Q4.AMOUNT,0) + ISNULL(Q5.AMOUNT,0)
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
									FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK) 
											INNER JOIN T0050_AD_MASTER AM WITH (NOLOCK) ON AM.AD_ID = MAD.AD_Id
											INNER JOIN #TEMP_SALARY_MUSTER_REPORT T1 ON MAD.Emp_ID = T1.EMP_ID 
											AND T1.LABEL_NAME = AM.AD_SORT_NAME
									WHERE	FLAG = 'I'  AND AD_ACTIVE = 1 AND M_AD_NOT_EFFECT_SALARY = 0		
											AND MONTH(MAD.TO_DATE) = @MONTH AND YEAR(MAD.TO_DATE) = @YEAR and t1.Cmp_ID= @Company_Id					
									GROUP BY T1.EMP_ID							
								)Q ON Q.EMP_ID = T.EMP_ID  
					INNER JOIN  (
									SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
									FROM	#TEMP_SALARY_MUSTER_REPORT T1 
									WHERE	FLAG = 'I' AND LABEL_NAME = 'BASIC'
											AND MONTH = @MONTH AND YEAR = @YEAR  and t1.Cmp_ID= @Company_Id					
									GROUP BY T1.EMP_ID	
								)Q1  ON Q1.EMP_ID = T.EMP_ID 
					LEFT OUTER JOIN(
										SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
										FROM	#TEMP_SALARY_MUSTER_REPORT T1 
										WHERE	FLAG = 'R' AND LABEL_NAME = 'LTA_Claim'
												AND MONTH = @MONTH AND YEAR = @YEAR and t1.Cmp_ID= @Company_Id					
										GROUP BY T1.EMP_ID	
									) Q2  ON Q2.EMP_ID = T.EMP_ID 
					LEFT OUTER JOIN(
										SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
										FROM	#TEMP_SALARY_MUSTER_REPORT T1 
										WHERE	LABEL_NAME = 'Leave Encashment'	AND MONTH = @MONTH AND YEAR = @YEAR and t1.Cmp_ID= @Company_Id					
										GROUP BY T1.EMP_ID	
									) Q3  ON Q3.EMP_ID = T.EMP_ID 
					LEFT OUTER JOIN(
										SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
										FROM	#TEMP_SALARY_MUSTER_REPORT T1 
										WHERE	LABEL_NAME = 'Advance'	AND MONTH = @MONTH AND YEAR = @YEAR and t1.Cmp_ID= @Company_Id					
										GROUP BY T1.EMP_ID	
									) Q4  ON Q4.EMP_ID = T.EMP_ID 
					LEFT OUTER JOIN(
										SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
										FROM	#TEMP_SALARY_MUSTER_REPORT T1 
										WHERE	LABEL_NAME = 'OT Amount'	AND MONTH = @MONTH AND YEAR = @YEAR and t1.Cmp_ID= @Company_Id					
										GROUP BY T1.EMP_ID	
									) Q5  ON Q5.EMP_ID = T.EMP_ID 
			WHERE	T.LABEL_NAME = 'GROSS'

			

			--UPDATE T 
			--SET		AMOUNT = T.AMOUNT + Q.AMOUNT 
			--FROM	#TEMP_SALARY_MUSTER_REPORT T 
			--		INNER JOIN (
			--							SELECT  (ISNULL(SUM(MSS.S_Gross_Salary),0)) AS AMOUNT,TMR.EMP_ID
			--							FROM	#TEMP_SALARY_MUSTER_REPORT TMR 						
			--									LEFT OUTER JOIN T0201_MONTHLY_SALARY_SETT MSS ON  TMR.EMP_Id = MSS.EMP_ID																							
			--							WHERE	MONTH(MSS.S_Eff_Date) = @MONTH AND YEAR(MSS.S_Eff_Date) = @YEAR	AND LABEL_NAME = 'GROSS' 
			--							GROUP BY 		TMR.EMP_ID							
			--						)Q ON Q.Emp_ID = T.EMP_ID AND LABEL_NAME = 'GROSS'
			--	WHERE T.EMP_ID = Q.EMP_Id AND T.LABEL_NAME = 'GROSS'

			--UPDATE	#TEMP_SALARY_MUSTER_REPORT
			--SET		AMOUNT = ISNULL(SALARY_AMOUNT,0) + ISNULL(Allow_Amount,0) + ISNULL(settelement_Amount,0)
			--FROM	T0200_MONTHLY_SALARY SG   
			--		INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID  
			--		AND MONTH(SG.MONTH_END_DATE) = @MONTH AND YEAR(SG.MONTH_END_DATE) = @YEAR
			--WHERE   LABEL_NAME = 'Total Earn'

			
										
			UPDATE  T
			SET		AMOUNT = ISNULL(Q.AMOUNT,0) + ISNULL(Q1.AMOUNT,0)
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
									FROM	T0210_MONTHLY_AD_DETAIL MAD WITH (NOLOCK)
											INNER JOIN T0050_AD_MASTER AM WITH (NOLOCK) ON AM.AD_ID = MAD.AD_Id
											INNER JOIN #TEMP_SALARY_MUSTER_REPORT T1 ON MAD.Emp_ID = T1.EMP_ID 
											AND T1.LABEL_NAME = AM.AD_SORT_NAME
									WHERE	FLAG = 'I' AND AD_ACTIVE = 1 AND M_AD_NOT_EFFECT_SALARY = 1		
											AND MONTH(MAD.TO_DATE) = @MONTH AND YEAR(MAD.TO_DATE) = @YEAR and t1.Cmp_ID= @Company_Id					
									GROUP BY T1.EMP_ID							
								)Q ON Q.EMP_ID = T.EMP_ID  
					INNER JOIN  (
									SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
									FROM	#TEMP_SALARY_MUSTER_REPORT T1 
									WHERE	FLAG = 'G' AND LABEL_NAME = 'GROSS'
											AND MONTH = @MONTH AND YEAR = @YEAR and t1.Cmp_ID= @Company_Id					
									GROUP BY T1.EMP_ID	
								)Q1  ON Q1.EMP_ID = T.EMP_ID  
			WHERE	T.LABEL_NAME = 'Total Earn'


			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = PT_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'PT' and Sg.Cmp_ID= @Company_Id					

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = ISNULL(LOAN_AMOUNT,0) + ISNULL(LOAN_INTREST_AMOUNT,0) + ISNULL(ADVANCE_AMOUNT,0)
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'Loan\Advance' and Sg.Cmp_ID= @Company_Id					

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = REVENUE_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'REVENUE' and Sg.Cmp_ID= @Company_Id					

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = LWF_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'LWF' and Sg.Cmp_ID= @Company_Id					
						
						
			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = M_IT_TAX
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'TDS' and Sg.Cmp_ID= @Company_Id											

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = OTHER_DEDU_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'OTH DE'	and Sg.Cmp_ID= @Company_Id					

			--UPDATE	#TEMP_SALARY_MUSTER_REPORT
			--SET		AMOUNT = TOTAL_DEDU_AMOUNT
			--FROM	T0200_MONTHLY_SALARY SG   
			--		INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
			--		AND YEAR(SG.MONTH_END_DATE) = @YEAR
			--WHERE   LABEL_NAME = 'DEDUCTION'
			
		
									
			--UPDATE  T
			--SET		AMOUNT  = ISNULL(Q.AMOUNT,0) 
			--FROM    #TEMP_SALARY_MUSTER_REPORT T 
			--		INNER JOIN (
			--						select	distinct (ISNULL(Loan_Amount,0) + isnull(Loan_Intrest_Amount,0)) AS AMOUNT,MLP.EMP_Id
			--						FROM	T0200_MONTHLY_SALARY MLP
			--								INNER JOIN #TEMP_SALARY_MUSTER_REPORT T ON T.EMP_ID = Mlp.EMP_Id
			--						WHERE	month(month_End_date) =  month(@TO_DATE) and year(month_End_date) = year(@TO_DATE) 
			--									and Mlp.Cmp_Id = @Company_Id
									
			--					)Q ON Q.EMP_ID = T.EMP_ID
					
			--WHERE	LABEL_NAME = 'LOAN'
									

			UPDATE  T
			SET		AMOUNT = ISNULL(Q.AMOUNT,0)
			FROM	#TEMP_SALARY_MUSTER_REPORT T 
					INNER JOIN (
									SELECT  ISNULL(SUM(T1.AMOUNT),0) AS AMOUNT,T1.EMP_ID
									FROM	 #TEMP_SALARY_MUSTER_REPORT T1 											
									WHERE	FLAG = 'D' --AND AD_ACTIVE = 1 
											AND MONTH = @MONTH AND YEAR = @YEAR
									GROUP BY T1.EMP_ID							
								)Q ON Q.EMP_ID = T.EMP_ID  												
			WHERE	T.LABEL_NAME = 'DEDUCTION'

			UPDATE	#TEMP_SALARY_MUSTER_REPORT
			SET		AMOUNT = NET_AMOUNT
			FROM	T0200_MONTHLY_SALARY SG   
					INNER JOIN	#TEMP_SALARY_MUSTER_REPORT TMR ON SG.EMP_ID = TMR.EMP_ID AND MONTH(SG.MONTH_END_DATE) = @MONTH
					AND YEAR(SG.MONTH_END_DATE) = @YEAR
			WHERE   LABEL_NAME = 'NET'						
					
			DECLARE @SQL VARCHAR(MAX)
			DECLARE @COLS VARCHAR(MAX)
			DECLARE @SQL1 VARCHAR(MAX)							
			DECLARE @COUNT_SETTLEMENT_COUNT NUMERIC							
			DECLARE @GRAND_TOTAL_ROW VARCHAR(MAX)						
							
							
			DELETE	T 
			FROM	#TEMP_SALARY_MUSTER_REPORT T
					INNER JOIN (
									SELECT	ROW_ID,[MONTH],[YEAR]
									FROM	#TEMP_SALARY_MUSTER_REPORT T1 
									GROUP BY ROW_ID,[MONTH],[YEAR]
									HAVING	SUM(AMOUNT) = 0
								) T1 ON T.ROW_ID=T1.ROW_ID AND T1.[MONTH] = @MONTH
					AND T1.[YEAR] = @YEAR
							
						
							
			SELECT	 @COLS = COALESCE(@COLS + ',','')  + '[' + DEPT_NAME  + '\' + STATE_NAME  + ']' 
			FROM	(
						SELECT	distinct ROW_NUMBER() OVER(PARTITION BY EMP_ID ORDER BY STATE_NAME,DEPT_NAME,ROW_ID) AS ROW_ID,STATE_NAME,DEPT_NAME										
						FROM	#TEMP_SALARY_MUSTER_REPORT											
					) PL
			GROUP BY STATE_NAME,DEPT_NAME
			ORDER BY MAX(ROW_ID)	
			
			

			DECLARE @ALTER_COLS VARCHAR(MAX)
			DECLARE @SUM_COLS VARCHAR(MAX)
							
							
			SELECT	@ALTER_COLS = ISNULL(@ALTER_COLS + ';', '') + 'ALTER TABLE #SALARY_SETTELEMENT ADD ' + DATA + ' NUMERIC(18,2)',
					@SUM_COLS = ISNULL(@SUM_COLS + ',','') + 'SUM(ISNULL(' + DATA + ',0)) AS ' + DATA
			FROM	DBO.SPLIT(@COLS, ',') T
							
			
			
			CREATE TABLE #SALARY_SETTELEMENT
			(				
				LABEL_NAME		VARCHAR(MAX),
				ROW_Id			NUMERIC(18,0)															
			)
			
			exec(@ALTER_COLS);
							
							
			SET @SQL = 'INSERT INTO #SALARY_SETTELEMENT
						SELECT	* 
						FROM	 
							(								
								SELECT	 LABEL_NAME,(DEPT_NAME + ''\'' + STATE_NAME) AS LABELNAME,
										 ISNULL(Amount,0) Amount,ROW_Id										 									
								FROM	 #Temp_Salary_Muster_Report T Left Outer Join
										 T0080_Emp_Master E WITH (NOLOCK) on T.Emp_Id = E.Emp_ID											 								
							) YS 
							PIVOT 
							(
								Sum(Amount) FOR LABELNAME IN (' + @COLS + ')
							) PVT
						ORDER BY ROW_Id'
							
												
			EXEC(@SQL)			
			
			ALTER TABLE #SALARY_SETTELEMENT
			DROP COLUMN ROW_Id
											
			SELECT * FROM #SALARY_SETTELEMENT  
							
							
							
	RETURN




