


CREATE VIEW [dbo].[_dta_mv_9] WITH SCHEMABINDING
 AS 
SELECT  [dbo].[T0090_EMP_REPORTING_DETAIL].[Emp_ID] as _col_1,  count_big(*) as _col_2 FROM  [dbo].[T0090_EMP_REPORTING_DETAIL] WITH (NOLOCK)  WHERE  [dbo].[T0090_EMP_REPORTING_DETAIL].[R_Emp_ID] = 2718.  GROUP BY  [dbo].[T0090_EMP_REPORTING_DETAIL].[Emp_ID]  


