



CREATE VIEW [dbo].[V0010_MACHINE_EMPLOYEES]
AS 
SELECT DISTINCT EM.Emp_ID , EM.ALPHA_EMP_CODE + ' - ' + EMP_FULL_NAME AS Emp_Full_Name , EM.Cmp_ID
FROM T0080_EMP_MASTER EM WITH (NOLOCK)
INNER JOIN T0095_INCREMENT I WITH (NOLOCK) ON EM.Emp_ID = I.Emp_ID
INNER JOIN 
	( SELECT MAX(I.INCREMENT_ID) AS INCREMENT_ID, I.EMP_ID
		FROM T0095_INCREMENT I WITH (NOLOCK) 
		INNER JOIN 
		(
				SELECT MAX(i3.INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE, I3.EMP_ID
				FROM T0095_INCREMENT I3 WITH (NOLOCK)
				WHERE I3.Increment_effective_Date <= GETDATE()
				GROUP BY I3.EMP_ID  
			) I3 ON I.Increment_Effective_Date=I3.Increment_Effective_Date AND I.EMP_ID=I3.Emp_ID	
	   WHERE I.INCREMENT_EFFECTIVE_DATE <= GETDATE()
	   GROUP BY I.Emp_ID  
	) Qry on	I.Emp_ID = Qry.Emp_ID	and I.Increment_ID = Qry.Increment_ID 
INNER JOIN T0040_Business_Segment BS WITH (NOLOCK) ON BS.Segment_ID = I.Segment_ID AND BS.Is_MachineBased = 1
WHERE EM.Emp_Left <> 'Y'




