
CREATE VIEW [dbo].[V0020_District_Master]
AS
SELECT DM.Dist_ID,DM.Dist_Name,SM.State_ID,SM.State_Name,LM.Loc_name,SM.Loc_ID,DM.Cmp_ID
FROM T0030_DISTRICT_MASTER DM WITH (NOLOCK)
inner join T0020_STATE_MASTER SM WITH (NOLOCK) on SM.State_ID= DM.State_id
INNER JOIN T0001_LOCATION_MASTER LM WITH (NOLOCK) ON SM.Loc_ID = LM.Loc_ID and DM.Loc_ID=LM.Loc_ID
