


CREATE VIEW [dbo].[V0020_PRIVILEGE_DETAIL]
AS
	SELECT	PD.Emp_ID, PM.*
	FROM	T0020_PRIVILEGE_MASTER PM WITH (NOLOCK)
			INNER JOIN (SELECT	MAX(PRIVILEGE_ID) AS PRIVILEGE_ID,PD.LOGIN_ID, EPD.Emp_ID
						FROM	T0090_EMP_PRIVILEGE_DETAILS PD WITH (NOLOCK)
								INNER JOIN (
												SELECT	MAX(FROM_DATE) AS FROM_DATE,L.LOGIN_ID, L.Emp_ID
												FROM	T0090_EMP_PRIVILEGE_DETAILS P WITH (NOLOCK)
														INNER JOIN (SELECT L.EMP_ID, LOGIN_ID, Cmp_id FROM T0011_LOGIN L WITH (NOLOCK)
																		INNER JOIN (SELECT MAX(EFFECTIVE_DATE) AS EFFECTIVE_DATE, EMP_ID
																					FROM T0011_LOGIN L1 WITH (NOLOCK) WHERE Effective_Date <= GetDate() AND ISNULL(Emp_ID,0) > 0
																					GROUP BY Emp_ID) L1 ON L.Emp_ID=L1.Emp_ID AND L1.EFFECTIVE_DATE=L.Effective_Date
																	) L ON P.Login_Id=L.Login_ID AND P.Cmp_id=L.Cmp_ID
												WHERE	From_Date <= GETDATE() 	AND ISNULL(L.Emp_ID,0) > 0
												GROUP BY L.Login_ID	, L.Emp_ID		
											) AS EPD ON EPD.FROM_DATE = PD.From_Date AND EPD.Login_ID=PD.Login_Id
						GROUP BY PD.Login_Id, EPD.Emp_ID) PD ON PM.Privilege_ID=PD.Privilege_ID


