





CREATE VIEW [dbo].[V0030_TRAVEL_MODE_MASTER]
AS

SELECT TRAVEL_MODE_ID,CMP_ID,TRAVEL_MODE_NAME,(CASE WHEN GST_APPLICABLE = 0 THEN 'Not Applicable' ELSE 'Applicable' END) AS GST_APPLICABLE,
(CASE WHEN MODE_TYPE = 1 THEN 'Flight' WHEN MODE_TYPE = 2 THEN 'Train' WHEN MODE_TYPE = 3 THEN 'Car/Cab' WHEN MODE_TYPE = 4 THEN 'Bus' WHEN MODE_TYPE  = 5 THEN 'Auto' WHEN MODE_TYPE = 6 THEN 'Hotel' WHEN MODE_TYPE = 7 THEN 'OTHER' ELSE 'OTHER' END) AS MODE_TYPE
FROM 
T0030_TRAVEL_MODE_MASTER WITH (NOLOCK)




