-- select  * from T0040_MOBILE_STORE_MASTER_New
CREATE VIEW [dbo].[V0040_MOBILESTORE_MASTER]
AS
	SELECT m.Store_ID,CURRENT_OUTLET_MAPPING,STORE_CODE,M.Dealer_Code,KRO_TYPE
	,RDS_NAME,ASM_NAME,ZSM_NAME,m.CMP_ID ,IS_ACTIVE
	FROM T0040_MOBILE_STORE_MASTER_New M WITH(NOLOCK)
