




CREATE VIEW [dbo].[V0040_MACHINE_MASTER]
AS
SELECT MM.MACHINE_ID,ME.CMP_ID,MM.MACHINE_NAME,MM.MACHINE_CODE,MM.MACHINE_TYPE,MM.REMARKS , ME.EFFECTIVE_DATE , ME.EFFICIENCY_ID
FROM T0040_MACHINE_MASTER MM WITH (NOLOCK)
INNER JOIN T0040_Machine_Efficiency_Master ME WITH (NOLOCK) ON MM.Machine_ID = ME.Machine_ID AND MM.Cmp_ID = ME.Cmp_ID




