





CREATE VIEW [dbo].[V0040_DESIGWISE_EMPLOYEE]
AS
SELECT     dbo.T0080_EMP_MASTER.Emp_ID, dbo.T0080_EMP_MASTER.Emp_Left, dbo.T0080_EMP_MASTER.Emp_code, 
                      dbo.T0080_EMP_MASTER.Emp_Full_Name, dbo.T0040_DESIGNATION_MASTER.Desig_ID, dbo.T0040_DESIGNATION_MASTER.Desig_Dis_No, 
                      dbo.T0040_DESIGNATION_MASTER.Desig_Name, dbo.T0080_EMP_MASTER.Cmp_ID, dbo.T0040_DESIGNATION_MASTER.Parent_ID, 
                      dbo.T0040_DESIGNATION_MASTER.Def_ID, dbo.T0040_DESIGNATION_MASTER.Is_Main, dbo.T0095_INCREMENT.Branch_ID
FROM         dbo.T0080_EMP_MASTER WITH (NOLOCK) INNER JOIN
                      dbo.T0095_INCREMENT WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Increment_ID = dbo.T0095_INCREMENT.Increment_ID INNER JOIN
                      dbo.T0040_DESIGNATION_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Desig_Id = dbo.T0040_DESIGNATION_MASTER.Desig_ID




