
  
  
  
  
  
  
CREATE VIEW [dbo].[V0050_GET_SubBranch]  
AS  
      
      
    SELECT DISTINCT TAB1.TRAN_ID,TAB1.CMP_ID,EM.EMP_ID,EM.EMP_FULL_NAME,TAB1.EFFECTIVE_DATE,TAB1.SubBranch_ID,TAB1.SUBBRANCH_NAME AS SUBBRANCH FROM  
    (  
       SELECT    INC.TRAN_ID,INC.EMP_ID,INC.CMP_ID,INC.EFFECTIVE_DATE,INC.SubBranch_ID,  
       CASE WHEN INC.SubBranch_ID IS NOT NULL THEN (SELECT VM1.SubBranch_Name + ', ' FROM T0050_SubBranch VM1 WITH (NOLOCK)  WHERE CAST(SubBranch_ID as nvarchar)  IN (SELECT DATA  FROM DBO.SPLIT(ISNULL(INC.SubBranch_ID,'0'),'#')) FOR XML PATH('')) ELSE 'ALL' END AS SUBBRANCH_NAME  
       FROM T0050_Assign_SubBranch INC WITH (NOLOCK) LEFT OUTER JOIN  
       T0050_SubBranch VS WITH (NOLOCK)  ON    
       INC.CMP_ID = VS.CMP_ID  
         
     ) TAB1 INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK)  ON TAB1.EMP_ID = EM.EMP_ID --ORDER BY VS.VERTICAL_NAME  
       
     
  
  
