




CREATE VIEW [dbo].[V0055_INCENTIVE_SCHEME_DETAIL]
AS
	SELECT	Scheme_ID, Effective_Date, SD.Desig_ID, SB.Branch_ID
	FROM	T0050_INCENTIVE_SCHEME S WITH (NOLOCK)
			CROSS APPLY (SELECT Desig_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SD WITH (NOLOCK) WHERE S.Scheme_ID=SD.Scheme_ID AND SD.Desig_ID IS NOT NULL) SD
			CROSS APPLY (SELECT Branch_ID FROM T0055_INCENTIVE_SCHEME_DETAIL SB WITH (NOLOCK) WHERE S.Scheme_ID=SB.Scheme_ID AND SB.Branch_ID IS NOT NULL) SB
			


