


CREATE VIEW [dbo].[V0050_SHIFT_ROTATION_DETAIL]
AS
	SELECT	SD.Shift_Tran_ID,SD.Rotation_ID,SD.Shift_ID,SD.Sort_ID,SM.Shift_Name, SM.Shift_St_Time, SM.Shift_End_Time
	FROM	T0050_SHIFT_ROTATION_DETAIL SD WITH (NOLOCK) INNER JOIN  T0040_SHIFT_MASTER SM  WITH (NOLOCK) ON SD.Cmp_ID=SM.Cmp_ID AND SD.Shift_ID=SM.Shift_ID

