CREATE VIEW [dbo].[V0050_GET_VERTICAL_SUBVERTICAL]  
AS  
      
      
    SELECT DISTINCT TAB1.TRAN_ID,TAB1.CMP_ID,EM.EMP_ID,EM.EMP_FULL_NAME,TAB1.EFFECTIVE_DATE,TAB1.VERTICAL_ID,TAB1.VERTICAL_NAME AS VERTICAL FROM  
    (  
       SELECT    INC.TRAN_ID,INC.EMP_ID,INC.CMP_ID,INC.EFFECTIVE_DATE,INC.VERTICAL_ID,  
       CASE WHEN INC.VERTICAL_ID IS NOT NULL THEN (SELECT VM1.VERTICAL_NAME + ', ' FROM T0040_VERTICAL_SEGMENT VM1 
       WITH (NOLOCK)  
       WHERE CAST(VERTICAL_ID AS Nvarchar) IN (SELECT CAST(DATA AS NUMERIC(18,0))  FROM DBO.SPLIT(ISNULL(INC.VERTICAL_ID,'0'),'#')) FOR XML PATH('')) ELSE 'ALL' END AS VERTICAL_NAME  
       FROM T0050_ASSIGN_VERTICALSUBVERTICAL INC 
       WITH (NOLOCK) 
       LEFT OUTER JOIN  
       T0040_VERTICAL_SEGMENT VS 
        WITH (NOLOCK)
       ON    
       INC.CMP_ID = VS.CMP_ID  
         
     ) TAB1 INNER JOIN T0080_EMP_MASTER EM 
 WITH (NOLOCK)
     
     ON TAB1.EMP_ID = EM.EMP_ID --ORDER BY VS.VERTICAL_NAME  
       
     
  
  
