



CREATE VIEW [dbo].[V0065_Emp_Launguage_Detail_Get_APP]
AS
SELECT     dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Row_ID, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Emp_Tran_ID, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Cmp_ID, 
                      dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Lang_ID, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Lang_Fluency, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Lang_Ability, 
                      dbo.T0040_LANGUAGE_MASTER.Lang_Name, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Emp_Application_ID, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Approved_Emp_ID, 
                      dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Approved_Date, dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Rpt_Level, dbo.T0040_LANGUAGE_MASTER.Lang_ID AS Expr1
FROM         dbo.T0065_EMP_LANGUAGE_DETAIL_APP  WITH (NOLOCK) INNER JOIN
                      dbo.T0040_LANGUAGE_MASTER  WITH (NOLOCK) ON dbo.T0065_EMP_LANGUAGE_DETAIL_APP.Lang_ID = dbo.T0040_LANGUAGE_MASTER.Lang_ID


