



CREATE VIEW [dbo].[V0065_EMP_CONTRACT_DETAIL_APP]
AS
SELECT     dbo.T0065_EMP_CONTRACT_DETAIL_APP.Tran_ID, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Cmp_ID, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Emp_Tran_ID, 
                      dbo.T0065_EMP_CONTRACT_DETAIL_APP.Emp_Application_ID, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Approved_Emp_ID, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Approved_Date, 
                      dbo.T0065_EMP_CONTRACT_DETAIL_APP.Rpt_Level, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Prj_ID, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Start_Date, 
                      dbo.T0065_EMP_CONTRACT_DETAIL_APP.End_Date, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Is_Renew, dbo.T0065_EMP_CONTRACT_DETAIL_APP.Is_Reminder, 
                      dbo.T0065_EMP_CONTRACT_DETAIL_APP.Comments, dbo.T0040_PROJECT_MASTER.Prj_name
FROM         dbo.T0065_EMP_CONTRACT_DETAIL_APP WITH (NOLOCK) INNER JOIN
                      dbo.T0040_PROJECT_MASTER WITH (NOLOCK)  ON dbo.T0065_EMP_CONTRACT_DETAIL_APP.Prj_ID = dbo.T0040_PROJECT_MASTER.Prj_ID


