



CREATE VIEW [dbo].[V0065_EMP_LICENSE_DETAIL_APP]
AS
SELECT     dbo.T0040_LICENSE_MASTER.Lic_Name, dbo.T0065_EMP_LICENSE_DETAIL_APP.Row_ID, dbo.T0065_EMP_LICENSE_DETAIL_APP.Cmp_ID, dbo.T0065_EMP_LICENSE_DETAIL_APP.LIC_ID, 
                      dbo.T0065_EMP_LICENSE_DETAIL_APP.Lic_St_Date, CASE WHEN T0065_EMP_LICENSE_DETAIL_APP.Lic_End_Date = '01/01/1900' THEN '' ELSE CONVERT(varchar(11), 
                      dbo.T0065_EMP_LICENSE_DETAIL_APP.Lic_End_Date, 103) END AS Lic_End_Date, dbo.T0065_EMP_LICENSE_DETAIL_APP.Lic_Comments, dbo.T0065_EMP_LICENSE_DETAIL_APP.Lic_For, 
                      dbo.T0065_EMP_LICENSE_DETAIL_APP.Lic_Number, dbo.T0065_EMP_LICENSE_DETAIL_APP.Is_Expired, dbo.T0065_EMP_LICENSE_DETAIL_APP.Emp_Tran_ID, 
                      dbo.T0065_EMP_LICENSE_DETAIL_APP.Emp_Application_ID, dbo.T0065_EMP_LICENSE_DETAIL_APP.Approved_Emp_ID, dbo.T0065_EMP_LICENSE_DETAIL_APP.Approved_Date, 
                      dbo.T0065_EMP_LICENSE_DETAIL_APP.Rpt_Level
FROM         dbo.T0040_LICENSE_MASTER WITH (NOLOCK) INNER JOIN
                      dbo.T0065_EMP_LICENSE_DETAIL_APP WITH (NOLOCK)  ON dbo.T0040_LICENSE_MASTER.Lic_ID = dbo.T0065_EMP_LICENSE_DETAIL_APP.LIC_ID


