



CREATE VIEW [dbo].[V0065_EMP_REPORTING_DETAIL_APP_Get]
AS
	SELECT RE.*,E.Emp_Full_Name As R_Emp_Full_Name
	FROM	T0065_EMP_REPORTING_DETAIL_APP RE WITH (NOLOCK)
			INNER JOIN T0080_EMP_MASTER E WITH (NOLOCK) ON RE.R_EMP_ID=E.EMP_ID


--select  * FROM	T0065_EMP_REPORTING_DETAIL_APP


