



CREATE VIEW [dbo].[V0065_EMP_QUALIFICATION_DETAIL_APP_Get]
AS
SELECT     dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Emp_Tran_ID, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Emp_Application_ID, 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Approved_Emp_ID, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Approved_Date, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Rpt_Level, 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Row_ID, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Cmp_ID, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Qual_ID, 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Specialization, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Year, dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Score, CONVERT(Varchar(11), 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.St_Date, 103) AS St_Date, CONVERT(Varchar(11), dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.End_Date, 103) AS End_Date, 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Comments, dbo.T0040_QUALIFICATION_MASTER.Qual_Name, dbo.T0060_EMP_MASTER_APP.Alpha_Emp_Code, 
                      dbo.T0060_EMP_MASTER_APP.Branch_ID, dbo.T0030_BRANCH_MASTER.Branch_Name, dbo.T0060_EMP_MASTER_APP.Emp_Full_Name, 
                      CAST(dbo.T0060_EMP_MASTER_APP.Date_Of_Join AS Varchar(11)) AS Date_Of_Join, dbo.T0040_QUALIFICATION_MASTER.Qual_Type, 
                      dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.attach_doc
FROM         dbo.T0065_EMP_QUALIFICATION_DETAIL_APP WITH (NOLOCK) INNER JOIN
                      dbo.T0040_QUALIFICATION_MASTER WITH (NOLOCK)  ON dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Qual_ID = dbo.T0040_QUALIFICATION_MASTER.Qual_ID INNER JOIN
                      dbo.T0060_EMP_MASTER_APP WITH (NOLOCK)  ON dbo.T0065_EMP_QUALIFICATION_DETAIL_APP.Emp_Tran_ID = dbo.T0060_EMP_MASTER_APP.Emp_Tran_ID INNER JOIN
                      dbo.T0030_BRANCH_MASTER WITH (NOLOCK)  ON dbo.T0060_EMP_MASTER_APP.Branch_ID = dbo.T0030_BRANCH_MASTER.Branch_ID


