



CREATE VIEW [dbo].[V0065_EMP_IMMIGRATION_DETAIL_APP_Get]
AS
SELECT     dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Emp_Tran_ID, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Emp_Application_ID, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Approved_Emp_ID, 
                      dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Approved_Date, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Rpt_Level, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Row_ID, 
                      dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Cmp_ID, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Loc_ID, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Type, 
                      dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_No, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Issue_Date, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Issue_Status, 
                      dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Date_of_Expiry, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Review_Date, dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Imm_Comments, 
                      dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.attach_doc, dbo.T0001_LOCATION_MASTER.Loc_name
FROM         dbo.T0065_EMP_IMMIGRATION_DETAIL_APP WITH (NOLOCK) INNER JOIN
                      dbo.T0001_LOCATION_MASTER WITH (NOLOCK)  ON dbo.T0065_EMP_IMMIGRATION_DETAIL_APP.Loc_ID = dbo.T0001_LOCATION_MASTER.Loc_ID


