



CREATE VIEW [dbo].[V0075_EMP_EARN_DEDUCTION_APP]
AS
SELECT     dbo.T0050_AD_MASTER.AD_NAME, EED.AD_TRAN_ID, EED.CMP_ID, EED.Emp_Tran_ID, EED.Emp_Application_ID, EED.Approved_Emp_ID, EED.Approved_Date, EED.Rpt_Level, EED.AD_ID, 
                      EED.INCREMENT_ID, EED.E_AD_FLAG, EED.E_AD_MODE, EED.E_AD_PERCENTAGE, EED.E_AD_AMOUNT, EED.E_AD_MAX_LIMIT, dbo.T0050_AD_MASTER.AD_LEVEL, 
                      dbo.T0050_AD_MASTER.AD_NOT_EFFECT_SALARY, dbo.T0050_AD_MASTER.AD_PART_OF_CTC, dbo.T0050_AD_MASTER.AD_ACTIVE, dbo.T0050_AD_MASTER.AD_NOT_EFFECT_ON_PT, 
                      dbo.T0050_AD_MASTER.FOR_FNF, dbo.T0050_AD_MASTER.NOT_EFFECT_ON_MONTHLY_CTC, dbo.T0050_AD_MASTER.Is_Yearly, dbo.T0050_AD_MASTER.Not_Effect_on_Basic_Calculation, 
                      dbo.T0050_AD_MASTER.AD_CALCULATE_ON, dbo.T0050_AD_MASTER.Effect_Net_Salary, dbo.T0050_AD_MASTER.AD_EFFECT_MONTH, 
                      CASE WHEN E_AD_Flag = 'D' THEN '-' ELSE '+' END AS E_AD_Flag1, dbo.T0050_AD_MASTER.Add_in_sal_amt, dbo.T0050_AD_MASTER.AD_DEF_ID, 
                      dbo.T0050_AD_MASTER.Hide_In_Reports
FROM         dbo.T0075_EMP_EARN_DEDUCTION_APP AS EED WITH (NOLOCK) INNER JOIN
                      dbo.T0060_EMP_MASTER_APP AS EM WITH (NOLOCK)  ON EED.INCREMENT_ID = EM.Increment_ID INNER JOIN
                      dbo.T0050_AD_MASTER WITH (NOLOCK)  ON EED.AD_ID = dbo.T0050_AD_MASTER.AD_ID


