



CREATE VIEW [dbo].[V0090_EMP_GPF_REQUEST]
AS
	SELECT	ROW_NUMBER() OVER (PARTITION BY GPF.CMP_ID,GPF.EMP_ID ORDER BY GPF.EFFECTIVE_DATE DESC) AS ROW_NO, GPF.Cmp_ID,GPF.Tran_ID,GPF.Emp_ID,E.Branch_ID,GPF.AD_ID,E.Alpha_Emp_Code,E.Emp_Full_Name,GPF.Effective_Date,GPF.Amount
			,B.Vertical_ID,B.SubVertical_ID,B.Dept_ID
	FROM	T0090_EMP_GPF_REQUEST GPF WITH (NOLOCK) INNER JOIN 
			--V0080_Employee_Master E ON GPF.Cmp_ID=E.Cmp_ID AND GPF.Emp_ID=E.Emp_ID
			--Added By Jaina 23-09-2015 Start
			T0080_EMP_MASTER As E WITH (NOLOCK)  ON E.Emp_ID=GPF.Emp_ID INNER JOIN
			(
				SELECT	EMP_ID, Branch_ID, CMP_ID,I.Vertical_ID,I.SubVertical_ID,I.Dept_ID
				FROM	T0095_INCREMENT I WITH (NOLOCK) 
				WHERE	I.INCREMENT_ID = (
											SELECT	TOP 1 INCREMENT_ID
											FROM	T0095_INCREMENT I1 WITH (NOLOCK) 
											WHERE	I1.EMP_ID=I.EMP_ID AND I1.CMP_ID=I.CMP_ID
											ORDER BY	INCREMENT_EFFECTIVE_DATE DESC, INCREMENT_ID DESC
										)
	    	  ) AS B ON B.EMP_ID = E.EMP_ID AND B.CMP_ID=E.CMP_ID 
	    	  --Added By Jaina 23-09-2015 End



