





CREATE VIEW [dbo].[V0090_EMP_CONTRACT_DETAIL]
AS
SELECT     dbo.T0090_EMP_CONTRACT_DETAIL.Tran_ID, dbo.T0090_EMP_CONTRACT_DETAIL.Cmp_ID, dbo.T0090_EMP_CONTRACT_DETAIL.Emp_ID, 
                      dbo.T0090_EMP_CONTRACT_DETAIL.Prj_ID, dbo.T0090_EMP_CONTRACT_DETAIL.Start_Date, dbo.T0090_EMP_CONTRACT_DETAIL.End_Date, 
                      dbo.T0090_EMP_CONTRACT_DETAIL.Is_Renew, dbo.T0090_EMP_CONTRACT_DETAIL.Is_Reminder, dbo.T0090_EMP_CONTRACT_DETAIL.Comments, 
                      dbo.T0040_PROJECT_MASTER.Prj_name
FROM         dbo.T0090_EMP_CONTRACT_DETAIL WITH (NOLOCK) INNER JOIN
                      dbo.T0040_PROJECT_MASTER WITH (NOLOCK)  ON dbo.T0090_EMP_CONTRACT_DETAIL.Prj_ID = dbo.T0040_PROJECT_MASTER.Prj_ID




