




CREATE VIEW [dbo].[V0090_HRMS_RESUME_IMM]
AS
SELECT     dbo.T0090_HRMS_RESUME_IMMIGRATION.Imm_Type, dbo.T0090_HRMS_RESUME_IMMIGRATION.Imm_No, 
                      dbo.T0090_HRMS_RESUME_IMMIGRATION.Imm_Comments, dbo.T0090_HRMS_RESUME_IMMIGRATION.Cmp_ID, 
                      dbo.T0090_HRMS_RESUME_IMMIGRATION.Row_ID, dbo.T0090_HRMS_RESUME_IMMIGRATION.Resume_ID
FROM         dbo.T0055_Resume_Master WITH (NOLOCK) INNER JOIN
                      dbo.T0090_HRMS_RESUME_IMMIGRATION WITH (NOLOCK) ON dbo.T0055_Resume_Master.Resume_Id = dbo.T0090_HRMS_RESUME_IMMIGRATION.Resume_ID




