


CREATE VIEW [dbo].[V0090_Emp_Immigration_Detail_Get]
AS
SELECT     dbo.T0090_EMP_IMMIGRATION_DETAIL.Emp_ID, dbo.T0090_EMP_IMMIGRATION_DETAIL.Row_ID, dbo.T0090_EMP_IMMIGRATION_DETAIL.Cmp_ID, 
                      dbo.T0090_EMP_IMMIGRATION_DETAIL.Loc_ID, dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Type, dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_No, 
                      dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Issue_Date, dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Issue_Status, 
                      dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Date_of_Expiry, dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Review_Date, 
                      dbo.T0090_EMP_IMMIGRATION_DETAIL.Imm_Comments, dbo.T0090_EMP_IMMIGRATION_DETAIL.attach_doc, 
                      dbo.T0001_LOCATION_MASTER.Loc_name AS Loc_Name
FROM         dbo.T0090_EMP_IMMIGRATION_DETAIL WITH (NOLOCK) INNER JOIN
                      dbo.T0001_LOCATION_MASTER WITH (NOLOCK) ON dbo.T0090_EMP_IMMIGRATION_DETAIL.Loc_ID = dbo.T0001_LOCATION_MASTER.Loc_ID

