





CREATE VIEW [dbo].[V0090_Emp_Launguage_Detail_Get]
AS
SELECT     dbo.T0090_EMP_LANGUAGE_DETAIL.*, dbo.T0040_LANGUAGE_MASTER.Lang_Name AS Lang_Name
FROM         dbo.T0090_EMP_LANGUAGE_DETAIL WITH (NOLOCK) INNER JOIN
                      dbo.T0040_LANGUAGE_MASTER WITH (NOLOCK)  ON dbo.T0090_EMP_LANGUAGE_DETAIL.Lang_ID = dbo.T0040_LANGUAGE_MASTER.Lang_ID




