





CREATE VIEW [dbo].[V0100_TRAINING_APPLICATION]
AS
SELECT     dbo.T0100_TRAINING_APPLICATION.Training_App_ID, dbo.T0100_TRAINING_APPLICATION.Training_Title, 
                      dbo.T0100_TRAINING_APPLICATION.Training_Desc, dbo.T0100_TRAINING_APPLICATION.For_Date, 
                      dbo.T0100_TRAINING_APPLICATION.Posted_Emp_ID, dbo.T0100_TRAINING_APPLICATION.App_Status, dbo.T0100_TRAINING_APPLICATION.Skill_ID, 
                      dbo.T0040_SKILL_MASTER.Skill_Name, dbo.T0100_TRAINING_APPLICATION.Cmp_ID, dbo.T0100_TRAINING_APPLICATION.Login_ID, 
                      dbo.T0100_TRAINING_APPLICATION.System_Date
FROM         dbo.T0100_TRAINING_APPLICATION WITH (NOLOCK) INNER JOIN
                      dbo.T0040_SKILL_MASTER WITH (NOLOCK)  ON dbo.T0100_TRAINING_APPLICATION.Skill_ID = dbo.T0040_SKILL_MASTER.Skill_ID




