





CREATE VIEW [dbo].[V0100_EMP_PERFORMANCE_DETAIL_EMPLOYEE]    
AS    
SELECT     dbo.T0100_EMP_PERFORMANCE_DETAIL.OUT_OF_PER, dbo.T0100_EMP_PERFORMANCE_DETAIL.PERCENTAGE,     
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.EMP_ID, dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE,     
                      MONTH(dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE) AS month, YEAR(dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE) AS Year,     
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.CMP_ID, dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_INC_TRAN_ID,     
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_DETAIL_ID, dbo.T0080_EMP_MASTER.Emp_Full_Name, dbo.T0080_EMP_MASTER.Branch_ID,     
                      dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.PER_NAME,dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.Approve_From,dbo.T0080_EMP_MASTER.Emp_Superior,     
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.LOGIN_ID, ISNULL(EM.Emp_Full_Name, dbo.T0011_LOGIN.Login_Name) AS LOGIN_NAME,dbo.T0090_EMP_REPORTING_DETAIL.R_EMP_ID,     
                      dbo.T0080_EMP_MASTER.Emp_code    
FROM         dbo.T0100_EMP_PERFORMANCE_DETAIL WITH (NOLOCK) INNER JOIN    
                      dbo.T0080_EMP_MASTER (NOLOCK)  ON dbo.T0100_EMP_PERFORMANCE_DETAIL.EMP_ID = dbo.T0080_EMP_MASTER.Emp_ID INNER JOIN    
                      dbo.T0040_PERFORMANCE_INCENTIVE_MASTER (NOLOCK)  ON     
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_INC_TRAN_ID = dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.PER_INC_TRAN_ID LEFT OUTER JOIN    
                      dbo.T0011_LOGIN (NOLOCK)  ON dbo.T0100_EMP_PERFORMANCE_DETAIL.LOGIN_ID = dbo.T0011_LOGIN.Login_ID LEFT OUTER JOIN    
                      dbo.T0080_EMP_MASTER AS EM (NOLOCK)  ON dbo.T0011_LOGIN.Emp_ID = EM.Emp_ID  LEFT OUTER JOIN   
        dbo.T0090_EMP_REPORTING_DETAIL (NOLOCK)  ON  DBO.T0100_EMP_PERFORMANCE_DETAIL.EMP_ID=dbo.T0090_EMP_REPORTING_DETAIL.EMP_ID  
  



