


CREATE VIEW [dbo].[V0100_REJOIN_EMP]
AS
SELECT      dbo.T0100_REJOIN_EMP.TRAN_ID, dbo.T0100_REJOIN_EMP.Cmp_ID, dbo.T0100_REJOIN_EMP.Emp_ID,dbo.T0100_REJOIN_EMP.Left_Date, dbo.T0100_REJOIN_EMP.REMARKS, 
                      ISNULL(dbo.T0100_REJOIN_EMP.Rejoin_Date, '') AS Rejoin_Date,dbo.T0080_EMP_MASTER.Emp_code, dbo.T0080_EMP_MASTER.Emp_First_Name, dbo.T0100_REJOIN_EMP.System_Date,
                      dbo.T0080_EMP_MASTER.Date_Of_Join, dbo.T0080_EMP_MASTER.Gender, dbo.T0080_EMP_MASTER.Emp_Full_Name, dbo.T0095_INCREMENT.Branch_ID, 
                      dbo.T0095_INCREMENT.Cat_ID, dbo.T0095_INCREMENT.Grd_ID, dbo.T0095_INCREMENT.Dept_ID, dbo.T0095_INCREMENT.Desig_Id, 
                      dbo.T0040_GRADE_MASTER.Grd_Name, dbo.T0040_DEPARTMENT_MASTER.Dept_Name, dbo.T0030_BRANCH_MASTER.Branch_Name, 
                      dbo.T0040_DESIGNATION_MASTER.Desig_Name, dbo.T0080_EMP_MASTER.Alpha_Emp_Code
FROM         dbo.T0095_INCREMENT WITH (NOLOCK) LEFT OUTER JOIN
                      dbo.T0040_DESIGNATION_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Desig_Id = dbo.T0040_DESIGNATION_MASTER.Desig_ID LEFT OUTER JOIN
                      dbo.T0040_GRADE_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Grd_ID = dbo.T0040_GRADE_MASTER.Grd_ID LEFT OUTER JOIN
                      dbo.T0040_DEPARTMENT_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Dept_ID = dbo.T0040_DEPARTMENT_MASTER.Dept_Id LEFT OUTER JOIN
                      dbo.T0030_BRANCH_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Branch_ID = dbo.T0030_BRANCH_MASTER.Branch_ID RIGHT OUTER JOIN
                      dbo.T0080_EMP_MASTER WITH (NOLOCK)  ON dbo.T0095_INCREMENT.Increment_ID = dbo.T0080_EMP_MASTER.Increment_ID RIGHT OUTER JOIN
                      dbo.T0100_REJOIN_EMP WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Emp_ID = dbo.T0100_REJOIN_EMP.Emp_ID

