





CREATE VIEW [dbo].[V0100_RIMBURSEMENT_DETAIL]
AS
SELECT     dbo.T0080_EMP_MASTER.Emp_First_Name, dbo.T0080_EMP_MASTER.Emp_Full_Name, dbo.T0055_REIMBURSEMENT.RIMB_NAME, 
                      dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_TRAN_ID, dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_ID, dbo.T0100_RIMBURSEMENT_DETAIL.CMP_ID, 
                      dbo.T0100_RIMBURSEMENT_DETAIL.EMP_ID, dbo.T0100_RIMBURSEMENT_DETAIL.FOR_DATE, 
                      dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_AMOUNT, dbo.T0080_EMP_MASTER.Emp_Left, dbo.V0080_Employee_Master.Branch_Name, 
                      dbo.T0080_EMP_MASTER.Branch_ID, dbo.T0080_EMP_MASTER.Emp_code
FROM         dbo.T0080_EMP_MASTER WITH (NOLOCK) LEFT OUTER JOIN
                      dbo.V0080_Employee_Master WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Emp_ID = dbo.V0080_Employee_Master.Emp_ID RIGHT OUTER JOIN
                      dbo.T0100_RIMBURSEMENT_DETAIL WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Emp_ID = dbo.T0100_RIMBURSEMENT_DETAIL.EMP_ID RIGHT OUTER JOIN
                      dbo.T0055_REIMBURSEMENT WITH (NOLOCK)  ON dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_ID = dbo.T0055_REIMBURSEMENT.RIMB_ID




