





CREATE VIEW [dbo].[V0100_EMP_PERFORMANCE_DETAIL]  
AS  
SELECT     dbo.T0100_EMP_PERFORMANCE_DETAIL.OUT_OF_PER, dbo.T0100_EMP_PERFORMANCE_DETAIL.PERCENTAGE,   
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.EMP_ID, dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE,   
                      MONTH(dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE) AS month, YEAR(dbo.T0100_EMP_PERFORMANCE_DETAIL.FOR_DATE) AS Year,   
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.CMP_ID, dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_INC_TRAN_ID,   
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_DETAIL_ID, dbo.T0080_EMP_MASTER.Emp_Full_Name, dbo.T0080_EMP_MASTER.Branch_ID,   
                      dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.PER_NAME, dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.Approve_from, dbo.T0080_EMP_MASTER.Emp_Superior,   
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.LOGIN_ID, ISNULL(EM.Emp_Full_Name, dbo.T0011_LOGIN.Login_Name) AS LOGIN_NAME,   
                      dbo.T0080_EMP_MASTER.Emp_code  AS Emp_Code1,dbo.T0080_EMP_MASTER.Alpha_Emp_Code AS Emp_Code,
                      B.Vertical_ID,B.SubVertical_ID,B.Dept_ID   --Added By Jaina 28-09-2015
FROM         dbo.T0100_EMP_PERFORMANCE_DETAIL WITH (NOLOCK) INNER JOIN  
                      dbo.T0080_EMP_MASTER WITH (NOLOCK)  ON dbo.T0100_EMP_PERFORMANCE_DETAIL.EMP_ID = dbo.T0080_EMP_MASTER.Emp_ID INNER JOIN  
                      dbo.T0040_PERFORMANCE_INCENTIVE_MASTER  WITH (NOLOCK) ON   
                      dbo.T0100_EMP_PERFORMANCE_DETAIL.PER_INC_TRAN_ID = dbo.T0040_PERFORMANCE_INCENTIVE_MASTER.PER_INC_TRAN_ID LEFT OUTER JOIN  
                      dbo.T0011_LOGIN WITH (NOLOCK)  ON dbo.T0100_EMP_PERFORMANCE_DETAIL.LOGIN_ID = dbo.T0011_LOGIN.Login_ID LEFT OUTER JOIN  
                      dbo.T0080_EMP_MASTER AS EM  WITH (NOLOCK) ON dbo.T0011_LOGIN.Emp_ID = EM.Emp_ID  INNER JOIN
                      --Added By Jaina 28-09-2015 Start
                      (
						SELECT	EMP_ID, Branch_ID, CMP_ID,I.Vertical_ID,I.SubVertical_ID,I.Dept_ID
						FROM	T0095_INCREMENT I WITH (NOLOCK) 
						WHERE	I.INCREMENT_ID = (
													SELECT	TOP 1 INCREMENT_ID
													FROM	T0095_INCREMENT I1 WITH (NOLOCK) 
													WHERE	I1.EMP_ID=I.EMP_ID AND I1.CMP_ID=I.CMP_ID
													ORDER BY	INCREMENT_EFFECTIVE_DATE DESC, INCREMENT_ID DESC
												)
					  ) AS B ON B.EMP_ID = dbo.T0080_EMP_MASTER.EMP_ID AND B.CMP_ID=dbo.T0080_EMP_MASTER.CMP_ID 
					  --Added By Jaina 28-09-2015 End




