





CREATE VIEW [dbo].[V0100_Reim_Detail]
AS
SELECT     dbo.T0055_REIMBURSEMENT.RIMB_NAME, dbo.T0055_REIMBURSEMENT.RIMB_ID, dbo.T0100_RIMBURSEMENT_DETAIL.CMP_ID, 
                      dbo.T0100_RIMBURSEMENT_DETAIL.EMP_ID, dbo.T0100_RIMBURSEMENT_DETAIL.FOR_DATE, 
                      dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_AMOUNT, dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_TRAN_ID
FROM         dbo.T0055_REIMBURSEMENT WITH (NOLOCK) INNER JOIN
                      dbo.T0100_RIMBURSEMENT_DETAIL  WITH (NOLOCK) ON dbo.T0055_REIMBURSEMENT.RIMB_ID = dbo.T0100_RIMBURSEMENT_DETAIL.RIMB_ID




