



CREATE VIEW [dbo].[V0100_EMP_GRADE_CHANGE]
AS
SELECT    EGD.Tran_ID,EGD.Emp_ID, EGD.Cmp_ID, EGD.Grd_ID, EGD.For_Date,EM.Emp_code, EM.Emp_First_Name, EM.Emp_Full_Name, 
          GM.Grd_Name, INC.Branch_ID, BM.Branch_Name, EM.Emp_Superior, EM.Alpha_Emp_Code,INC.Vertical_ID,
          INC.SubVertical_ID ,DGM.Desig_Name,DPM.DEPT_ID , DPM.Dept_Name,TYM.Type_Name ,GM2.Grd_Name AS Actual_Grade , BS.SEGMENT_NAME
FROM         dbo.T0100_EMP_GRADE_DETAIL EGD WITH (NOLOCK)
			INNER JOIN dbo.T0080_EMP_MASTER EM WITH (NOLOCK)					ON EGD.Emp_ID = EM.Emp_ID 
            INNER JOIN dbo.T0095_INCREMENT INC WITH (NOLOCK)				ON EM.Increment_ID = INC.Increment_ID 
            INNER JOIN dbo.T0040_GRADE_MASTER GM WITH (NOLOCK)			ON EGD.Grd_ID = GM.Grd_ID
            INNER JOIN dbo.T0030_BRANCH_MASTER BM WITH (NOLOCK)			ON INC.Branch_ID = BM.Branch_ID
            INNER JOIN dbo.T0040_DESIGNATION_MASTER DGM WITH (NOLOCK)		ON INC.DESIG_ID = DGM.DESIG_ID
            LEFT OUTER JOIN dbo.T0040_DEPARTMENT_MASTER DPM WITH (NOLOCK)	ON INC.DEPT_ID = DPM.DEPT_ID
			LEFT OUTER JOIN dbo.T0040_TYPE_MASTER TYM WITH (NOLOCK)			ON INC.Type_ID = TYM.Type_ID
			INNER JOIN dbo.T0040_GRADE_MASTER GM2 WITH (NOLOCK)			ON GM2.Grd_ID = INC.Grd_ID
			LEFT OUTER JOIN dbo.T0040_Business_Segment BS WITH (NOLOCK)	ON BS.SEGMENT_ID = INC.SEGMENT_ID



