


CREATE VIEW [dbo].[V0100_Claim_Application_New_Payment]
AS
			SELECT    CA.CLAIM_APP_ID, CA.CMP_ID, CA.CLAIM_ID, 
                      CA.CLAIM_APP_DATE, CA.CLAIM_APP_CODE, 
                      CA.CLAIM_APP_AMOUNT, CA.CLAIM_APP_DESCRIPTION, 
                      CA.CLAIM_APP_DOC, CA.CLAIM_APP_STATUS, CM.CLAIM_NAME, 
                      ISNULL(CA.EMP_ID, 0) AS EMP_ID, EM.EMP_FULL_NAME, 
                      CM.CLAIM_MAX_LIMIT, EM.EMP_FIRST_NAME, EM.MOBILE_NO, 
                      EM.OTHER_EMAIL, ISNULL(INC.BRANCH_ID, 0) AS BRANCH_ID, EM.EMP_CODE, 
                      SEMP.EMP_FULL_NAME AS S_EMP_NAME,CA.S_EMP_ID AS S_EMP_ID, 
                      EM.ALPHA_EMP_CODE + ' - ' + EM.EMP_FULL_NAME AS EMP_FULL_NAME_NEW, 
                      EM.ALPHA_EMP_CODE,SEMP.EMP_FULL_NAME AS SUPERVISOR, INC.DESIG_ID,
                      INC.VERTICAL_ID,INC.SUBVERTICAL_ID, 
                      CASE WHEN SUBMIT_FLAG=0 THEN 'SUBMITTED' ELSE 'DRAFTED' END AS DRAFT_STATUS,
                      SUBMIT_FLAG,INC.DEPT_ID,
                      ISNULL(INC.GRD_ID, 0) AS GRD_ID,CP.Claim_Apr_ID,CM.Claim_Apr_Deduct_From_Sal
			FROM	  DBO.T0100_CLAIM_APPLICATION CA WITH (NOLOCK) INNER JOIN
                      DBO.T0040_CLAIM_MASTER CM WITH (NOLOCK)  ON CA.CLAIM_ID = CM.CLAIM_ID --AND CM.CLAIM_APR_DEDUCT_FROM_SAL <> 1 
					  LEFT OUTER JOIN
                      DBO.T0080_EMP_MASTER AS SEMP WITH (NOLOCK)  ON CA.S_EMP_ID = SEMP.EMP_ID LEFT JOIN
                      DBO.T0080_EMP_MASTER EM WITH (NOLOCK)  ON CA.EMP_ID = EM.EMP_ID INNER JOIN
                      DBO.T0095_INCREMENT INC WITH (NOLOCK)  ON EM.INCREMENT_ID = INC.INCREMENT_ID
					  INNER JOIN T0120_CLAIM_APPROVAL CP WITH (NOLOCK)  ON CA.CLAIM_APP_ID=CP.CLAIM_APP_ID 
		WHERE EXISTS (SELECT 1
						FROM T0130_CLAIM_APPROVAL_DETAIL CAD WITH (NOLOCK)  
							INNER JOIN T0040_CLAIM_MASTER CM WITH (NOLOCK)  ON CAD.Claim_ID = CM.Claim_ID
						WHERE CM.Claim_Apr_Deduct_From_Sal <> 1 AND CP.Claim_Apr_ID = CAD.Claim_Apr_ID)
