






CREATE VIEW [dbo].[V0115_TRAVEL_APPROVAL_OTHER_DETAIL_MODE_LEVEL]
AS


SELECT	TAOL.TRAN_ID,TAOL.CMP_ID,TAOL.TRAVEL_APPROVAL_OTHER_DETAIL_ID as Travel_App_Other_Detail_ID,TAOL.OTHER_TRAN_ID,
		TAOL.TRAVEL_MODE,TAOL.FROM_PLACE,TAOL.TO_PLACE,TAOL.MODE_NAME,TAOL.MODE_NO,
		TAOL.CITY,TAOL.CHECK_OUT_DATE,ISNULL(TAOL.NO_PASSENGER,0) AS NO_PASSENGER
		, CONVERT(varchar(11),TAOL.BOOKING_DATE,103)as BOOKING_DATE
		
		,TAOL.PICK_UP_ADDRESS,
		--TAOL.PICK_UP_TIME
		RIGHT(CONVERT(VARCHAR,TAOL.PICK_UP_TIME,100),7)as PICK_UP_TIME
		,TAOL.DROP_ADDRESS,TAOL.BILL_NO,TAOL.DESCRIPTION,TA.Travel_Application_ID AS Travel_App_ID
FROM	T0115_TRAVEL_LEVEL_APPROVAL TA WITH (NOLOCK) INNER JOIN T0115_TRAVEL_APPROVAL_OTHER_MODE_DETAIL_LEVEL TAOL WITH (NOLOCK)  ON TA.TRAN_ID = TAOL.OTHER_TRAN_ID AND TA.CMP_ID = TAOL.CMP_ID
--inner join T0030_TRAVEL_MODE_MASTER MM WITH (NOLOCK) ON MM.Travel_Mode_ID=TAOL.Travel_Mode




