





CREATE VIEW [dbo].[V0110_LEAVE_APPLICATION_DETAIL_REPORT]
AS
SELECT     dbo.T0100_LEAVE_APPLICATION.Application_Date, dbo.T0110_LEAVE_APPLICATION_DETAIL.From_Date, 
                      dbo.T0110_LEAVE_APPLICATION_DETAIL.To_Date, dbo.T0110_LEAVE_APPLICATION_DETAIL.Leave_Period, 
                      dbo.T0100_LEAVE_APPLICATION.Application_Status, dbo.T0110_LEAVE_APPLICATION_DETAIL.Leave_Reason, 
                      dbo.T0080_EMP_MASTER.Emp_Full_Name, T0080_EMP_MASTER_1.Emp_Full_Name AS ApprovedBy, dbo.T0100_LEAVE_APPLICATION.Emp_ID, 
                      dbo.T0040_DEPARTMENT_MASTER.Dept_Name, dbo.T0040_GRADE_MASTER.Grd_Name, dbo.T0040_DESIGNATION_MASTER.Desig_Name, 
                      dbo.T0040_TYPE_MASTER.Type_Name, dbo.T0100_LEAVE_APPLICATION.Leave_Application_ID
FROM         dbo.T0100_LEAVE_APPLICATION WITH (NOLOCK) INNER JOIN
                      dbo.T0110_LEAVE_APPLICATION_DETAIL WITH (NOLOCK)  ON 
                      dbo.T0100_LEAVE_APPLICATION.Leave_Application_ID = dbo.T0110_LEAVE_APPLICATION_DETAIL.Leave_Application_ID INNER JOIN
                      dbo.T0080_EMP_MASTER WITH (NOLOCK)  ON dbo.T0100_LEAVE_APPLICATION.Emp_ID = dbo.T0080_EMP_MASTER.Emp_ID INNER JOIN
                      dbo.T0080_EMP_MASTER AS T0080_EMP_MASTER_1 WITH (NOLOCK)  ON dbo.T0100_LEAVE_APPLICATION.S_Emp_ID = T0080_EMP_MASTER_1.Emp_ID INNER JOIN
                      dbo.T0040_DEPARTMENT_MASTER WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Dept_ID = dbo.T0040_DEPARTMENT_MASTER.Dept_Id INNER JOIN
                      dbo.T0040_GRADE_MASTER WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Grd_ID = dbo.T0040_GRADE_MASTER.Grd_ID INNER JOIN
                      dbo.T0040_DESIGNATION_MASTER WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Desig_Id = dbo.T0040_DESIGNATION_MASTER.Desig_ID INNER JOIN
                      dbo.T0040_TYPE_MASTER WITH (NOLOCK)  ON dbo.T0080_EMP_MASTER.Type_ID = dbo.T0040_TYPE_MASTER.Type_ID




