


CREATE VIEW [dbo].[V0120_WEEKOFF_ROSTER]
AS
SELECT		ER.TRAN_ID,EM.EMP_ID,ER.CMP_ID,EM.ALPHA_EMP_CODE,EM.EMP_CODE,EM.EMP_FULL_NAME,ER.FOR_DATE,DM.DEPT_NAME AS DEPARTMENT,
			--DESM.DESIG_NAME,I.VERTICAL_ID,I.SUBVERTICAL_ID,I.DEPT_ID,
			--VS.VERTICAL_NAME,SVS.SUBVERTICAL_NAME,
			BRNM.BRANCH_NAME,(CASE WHEN ER.IS_CANCEL_WO = 1 THEN 'Cancel' ELSE 'Assigned' END) AS IS_CANCEL_WO,
			BRNM.BRANCH_ID,I.DEPT_ID,
			I.Grd_ID,I.Type_Id,I.Vertical_ID,I.SubVertical_ID,I.subBranch_ID,I.Cat_ID
FROM        DBO.T0080_EMP_MASTER EM WITH (NOLOCK) INNER JOIN T0100_WEEKOFF_ROSTER ER WITH (NOLOCK)  ON  EM.EMP_ID = ER.EMP_ID AND EM.CMP_ID = ER.CMP_ID
			LEFT OUTER JOIN  (SELECT	I.*
								 FROM		dbo.T0095_INCREMENT AS i  WITH (NOLOCK) 
											INNER JOIN		(SELECT     MAX(I2.Increment_ID) AS Increment_ID, I2.Emp_ID
																FROM          dbo.T0095_INCREMENT AS I2  WITH (NOLOCK) INNER JOIN
																						   (SELECT     MAX(Increment_Effective_Date) AS INCREMENT_EFFECTIVE_DATE, Emp_ID
																							 FROM          dbo.T0095_INCREMENT AS I3 WITH (NOLOCK) 
																							 WHERE      (Increment_Effective_Date <= GETDATE())
																							 GROUP BY Emp_ID) AS I3 ON I2.Increment_Effective_Date = I3.INCREMENT_EFFECTIVE_DATE AND I2.Emp_ID = I3.Emp_ID
																GROUP BY I2.Emp_ID) AS I2 ON i.Emp_ID = I2.Emp_ID AND i.Increment_ID = I2.Increment_ID 
								) I ON EM.EMP_ID = I.EMP_ID 
			LEFT	JOIN		DBO.T0040_DEPARTMENT_MASTER AS DM WITH (NOLOCK)  ON I.DEPT_ID = DM.DEPT_ID 
			--LEFT	JOIN		DBO.T0040_DESIGNATION_MASTER AS DESM ON I.DESIG_ID = DESM.DESIG_ID 
			LEFT	JOIN		DBO.T0040_VERTICAL_SEGMENT AS VS WITH (NOLOCK)  ON I.VERTICAL_ID = VS.VERTICAL_ID
			LEFT	JOIN		DBO.T0050_SUBVERTICAL AS SVS WITH (NOLOCK)  ON I.SUBVERTICAL_ID = SVS.SUBVERTICAL_ID
			LEFT	JOIN		DBO.T0030_BRANCH_MASTER AS BRNM WITH (NOLOCK)  ON I.BRANCH_ID = BRNM.BRANCH_ID
			



