





CREATE VIEW [dbo].[V0140_LOAN_TRANSACTION]
AS
SELECT     dbo.T0040_LOAN_MASTER.Loan_Name, dbo.T0140_LOAN_TRANSACTION.Loan_Tran_ID, dbo.T0140_LOAN_TRANSACTION.Cmp_ID, 
                      dbo.T0140_LOAN_TRANSACTION.Loan_ID, dbo.T0140_LOAN_TRANSACTION.Emp_ID, dbo.T0140_LOAN_TRANSACTION.For_Date, 
                      dbo.T0140_LOAN_TRANSACTION.Loan_Opening, dbo.T0140_LOAN_TRANSACTION.Loan_Issue, dbo.T0140_LOAN_TRANSACTION.Loan_Return, 
                      dbo.T0140_LOAN_TRANSACTION.Loan_Closing
FROM         dbo.T0040_LOAN_MASTER WITH (NOLOCK) RIGHT OUTER JOIN
                      dbo.T0140_LOAN_TRANSACTION WITH (NOLOCK)  ON dbo.T0040_LOAN_MASTER.Loan_ID = dbo.T0140_LOAN_TRANSACTION.Loan_ID




