





CREATE VIEW [dbo].[V0150_JOBWORK_ALLOCATION_REPORT]
AS
SELECT     dbo.T0030_AGENCY_MASTER.Agency_Name, dbo.T0150_JOBWORK_ALLOCATION.Agency_ID, dbo.T0150_JOBWORK_ALLOCATION.Prj_ID, 
                      dbo.T0040_PROJECT_MASTER.Prj_name, dbo.T0150_JOBWORK_ALLOCATION.Work_ID, dbo.T0040_WORK_MASTER.Work_name, 
                      dbo.T0150_JOBWORK_ALLOCATION.Start_Date, dbo.T0150_JOBWORK_ALLOCATION.End_Date, dbo.T0150_JOBWORK_ALLOCATION.Work_Detail, 
                      dbo.T0150_JOBWORK_ALLOCATION.Submit_Date, dbo.T0150_JOBWORK_ALLOCATION.Remark, dbo.T0010_COMPANY_MASTER.Cmp_Id, 
                      dbo.T0010_COMPANY_MASTER.Cmp_Name, dbo.T0010_COMPANY_MASTER.Cmp_Address, dbo.T0150_JOBWORK_ALLOCATION.Prj_Status, 
                      dbo.T0030_AGENCY_MASTER.Agency_Address, dbo.T0030_AGENCY_MASTER.Agency_City, dbo.T0030_AGENCY_MASTER.Agency_phone
FROM         dbo.T0150_JOBWORK_ALLOCATION WITH (NOLOCK) INNER JOIN
                      dbo.T0030_AGENCY_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Agency_ID = dbo.T0030_AGENCY_MASTER.Agency_ID AND 
                      dbo.T0150_JOBWORK_ALLOCATION.Cmp_ID = dbo.T0030_AGENCY_MASTER.Cmp_ID INNER JOIN
                      dbo.T0040_WORK_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Work_ID = dbo.T0040_WORK_MASTER.Work_ID AND 
                      dbo.T0150_JOBWORK_ALLOCATION.Cmp_ID = dbo.T0040_WORK_MASTER.Cmp_ID INNER JOIN
                      dbo.T0040_PROJECT_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Prj_ID = dbo.T0040_PROJECT_MASTER.Prj_ID AND 
                      dbo.T0150_JOBWORK_ALLOCATION.Cmp_ID = dbo.T0040_PROJECT_MASTER.Cmp_ID INNER JOIN
                      dbo.T0010_COMPANY_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Cmp_ID = dbo.T0010_COMPANY_MASTER.Cmp_Id




