





CREATE VIEW [dbo].[V0150_JOBWORK_ALLOCATION]
AS
SELECT     dbo.T0030_AGENCY_MASTER.Agency_Name, dbo.T0150_JOBWORK_ALLOCATION.Row_ID, dbo.T0150_JOBWORK_ALLOCATION.Cmp_ID, 
                      dbo.T0150_JOBWORK_ALLOCATION.Agency_ID, dbo.T0150_JOBWORK_ALLOCATION.Prj_ID, dbo.T0150_JOBWORK_ALLOCATION.Work_ID, 
                      dbo.T0150_JOBWORK_ALLOCATION.Start_Date, dbo.T0150_JOBWORK_ALLOCATION.End_Date, dbo.T0150_JOBWORK_ALLOCATION.Work_Detail, 
                      dbo.T0150_JOBWORK_ALLOCATION.Submit_Date, dbo.T0150_JOBWORK_ALLOCATION.Prj_Status, dbo.T0150_JOBWORK_ALLOCATION.Remark, 
                      dbo.T0040_PROJECT_MASTER.Prj_name, dbo.T0040_WORK_MASTER.Work_name
FROM         dbo.T0150_JOBWORK_ALLOCATION WITH (NOLOCK) LEFT OUTER JOIN
                      dbo.T0040_WORK_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Work_ID = dbo.T0040_WORK_MASTER.Work_ID LEFT OUTER JOIN
                      dbo.T0040_PROJECT_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Prj_ID = dbo.T0040_PROJECT_MASTER.Prj_ID LEFT OUTER JOIN
                      dbo.T0030_AGENCY_MASTER WITH (NOLOCK)  ON dbo.T0150_JOBWORK_ALLOCATION.Agency_ID = dbo.T0030_AGENCY_MASTER.Agency_ID




