


CREATE VIEW [dbo].[V0180_CURRENCY_CONVERSION]  
AS  
 SELECT     dbo.T0180_CURRENCY_CONVERSION.CURR_CONV_ID, dbo.T0180_CURRENCY_CONVERSION.CMP_ID,   
        dbo.T0180_CURRENCY_CONVERSION.CURR_ID, dbo.T0180_CURRENCY_CONVERSION.FOR_DATE,   
        dbo.T0180_CURRENCY_CONVERSION.CURR_RATE, dbo.T0040_CURRENCY_MASTER.Curr_Name,   
        dbo.T0040_CURRENCY_MASTER.Curr_Symbol  
 FROM         dbo.T0040_CURRENCY_MASTER WITH (NOLOCK) INNER JOIN  
                      dbo.T0180_CURRENCY_CONVERSION WITH (NOLOCK)  ON dbo.T0040_CURRENCY_MASTER.Curr_ID = dbo.T0180_CURRENCY_CONVERSION.CURR_ID  

