CREATE TABLE [dbo].[T0140_MONTHLY_LATEMARK_DESIGNATION] (
    [TRAN_ID]        NUMERIC (18)    NOT NULL,
    [SAL_TRAN_ID]    NUMERIC (18)    NULL,
    [CMP_ID]         NUMERIC (18)    NULL,
    [EMP_ID]         NUMERIC (18)    NULL,
    [LATE_MIN]       VARCHAR (100)   NULL,
    [LATE_LUNCH_MIN] VARCHAR (100)   NULL,
    [LATE_SEC]       NUMERIC (18)    NULL,
    [LATE_LUNCH_SEC] NUMERIC (18)    NULL,
    [FOR_DATE]       DATETIME        NULL,
    [NORMAL_RATE]    NUMERIC (18, 2) NULL,
    [LUNCH_RATE]     NUMERIC (18, 2) NULL,
    [LATE_AMOUNT]    NUMERIC (18, 2) NULL,
    [LUNCH_AMOUNT]   NUMERIC (18, 2) NULL,
    [LATE_LIMIT]     VARCHAR (100)   NULL,
    [SHIFT_ID]       NUMERIC (18)    NULL,
    [SHIFT_NAME]     VARCHAR (200)   NULL,
    [IN_TIME]        DATETIME        NULL,
    [BREAK_OUT]      DATETIME        NULL,
    [BREAK_IN]       DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([TRAN_ID] ASC)
);

