CREATE TABLE [dbo].[T0140_LATE_TRANSACTION] (
    [L_Tran_ID]    NUMERIC (18) NOT NULL,
    [Cmp_ID]       NUMERIC (18) NOT NULL,
    [Emp_ID]       NUMERIC (18) NOT NULL,
    [For_Date]     DATETIME     NOT NULL,
    [Late_Opening] NUMERIC (5)  NOT NULL,
    [Late_Credit]  NUMERIC (5)  NOT NULL,
    [Late_Debit]   NUMERIC (5)  NOT NULL,
    [Late_Closing] NUMERIC (5)  NOT NULL,
    CONSTRAINT [PK_T0140_LATE_TRANSACTION] PRIMARY KEY CLUSTERED ([L_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0140_LATE_TRANSACTION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0140_LATE_TRANSACTION_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

