CREATE TABLE [dbo].[T0150_EMP_LUNCH_INOUT_RECORD] (
    [IO_TRAN_ID] INT          IDENTITY (1, 1) NOT NULL,
    [CMP_ID]     NUMERIC (18) NULL,
    [EMP_ID]     NUMERIC (18) NULL,
    [BRANCH_ID]  NUMERIC (18) NULL,
    [DESIG_ID]   NUMERIC (18) NULL,
    [GENDER]     CHAR (1)     NULL,
    [FOR_DATE]   DATETIME     NULL,
    [IN_TIME]    DATETIME     NULL,
    [OUT_TIME]   DATETIME     NULL,
    [DURATION]   NUMERIC (18) NULL,
    PRIMARY KEY CLUSTERED ([IO_TRAN_ID] ASC) WITH (FILLFACTOR = 95)
);

