CREATE TABLE [dbo].[T0150_EMP_WORK_DETAIL] (
    [Work_Tran_ID] NUMERIC (18)  NOT NULL,
    [Emp_ID]       NUMERIC (18)  NOT NULL,
    [Cmp_Id]       NUMERIC (18)  NOT NULL,
    [Prj_ID]       NUMERIC (18)  NOT NULL,
    [Work_ID]      NUMERIC (18)  NOT NULL,
    [Time_From]    DATETIME      NOT NULL,
    [Time_To]      DATETIME      NOT NULL,
    [Duration]     NUMERIC (18)  NOT NULL,
    [Work_Date]    DATETIME      NOT NULL,
    [Description]  VARCHAR (400) NULL,
    CONSTRAINT [PK_T0150_EMP_WORK_DETAIL] PRIMARY KEY CLUSTERED ([Work_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0150_EMP_WORK_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0150_EMP_WORK_DETAIL_T0040_PROJECT_MASTER] FOREIGN KEY ([Prj_ID]) REFERENCES [dbo].[T0040_PROJECT_MASTER] ([Prj_ID]),
    CONSTRAINT [FK_T0150_EMP_WORK_DETAIL_T0040_WORK_MASTER] FOREIGN KEY ([Work_ID]) REFERENCES [dbo].[T0040_WORK_MASTER] ([Work_ID]),
    CONSTRAINT [FK_T0150_EMP_WORK_DETAIL_T0150_EMP_WORK_DETAIL] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

