CREATE TABLE [dbo].[T0150_JOBWORK_ALLOCATION] (
    [Row_ID]      NUMERIC (18)  NOT NULL,
    [Cmp_ID]      NUMERIC (18)  NOT NULL,
    [Agency_ID]   NUMERIC (18)  NOT NULL,
    [Prj_ID]      NUMERIC (18)  NOT NULL,
    [Work_ID]     NUMERIC (18)  NOT NULL,
    [Start_Date]  DATETIME      NOT NULL,
    [End_Date]    DATETIME      NOT NULL,
    [Work_Detail] VARCHAR (50)  NULL,
    [Submit_Date] DATETIME      NULL,
    [Prj_Status]  CHAR (1)      NOT NULL,
    [Remark]      VARCHAR (250) NULL,
    CONSTRAINT [FK_T0150_JOBWORK_ALLOCATION_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0150_JOBWORK_ALLOCATION_T0030_AGENCY_MASTER] FOREIGN KEY ([Agency_ID]) REFERENCES [dbo].[T0030_AGENCY_MASTER] ([Agency_ID]),
    CONSTRAINT [FK_T0150_JOBWORK_ALLOCATION_T0040_PROJECT_MASTER] FOREIGN KEY ([Prj_ID]) REFERENCES [dbo].[T0040_PROJECT_MASTER] ([Prj_ID]),
    CONSTRAINT [FK_T0150_JOBWORK_ALLOCATION_T0040_WORK_MASTER] FOREIGN KEY ([Work_ID]) REFERENCES [dbo].[T0040_WORK_MASTER] ([Work_ID])
);

