CREATE TABLE [dbo].[T0150_AUDIT_EMP_INOUT_RECORD] (
    [IO_Tran_Id]          NUMERIC (18)  NOT NULL,
    [Emp_ID]              NUMERIC (18)  NOT NULL,
    [Cmp_ID]              NUMERIC (18)  NOT NULL,
    [For_Date]            DATETIME      NOT NULL,
    [In_Time]             DATETIME      NULL,
    [Out_Time]            DATETIME      NULL,
    [Duration]            VARCHAR (10)  NULL,
    [Reason]              VARCHAR (100) NULL,
    [Ip_Address]          VARCHAR (50)  NOT NULL,
    [In_Date_Time]        DATETIME      NULL,
    [Out_Date_Time]       DATETIME      NULL,
    [Skip_Count]          NUMERIC (18)  NULL,
    [Late_Calc_Not_App]   NUMERIC (1)   CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Late_Calc_Not_App] DEFAULT ((0)) NULL,
    [Chk_By_Superior]     TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Chk_By_Superior] DEFAULT ((0)) NULL,
    [Sup_Comment]         VARCHAR (100) NULL,
    [Half_Full_day]       VARCHAR (20)  NULL,
    [Is_Cancel_Late_In]   TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Is_Cancel_Late_In] DEFAULT ((0)) NULL,
    [Is_Cancel_Early_Out] TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Is_Cancel_Early_Out] DEFAULT ((0)) NULL,
    [Is_Default_In]       TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Is_Default_In] DEFAULT ((0)) NULL,
    [Is_Default_Out]      TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Is_Default_Out] DEFAULT ((0)) NULL,
    [Cmp_prp_in_flag]     NUMERIC (5)   CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Cmp_prp_in_flag] DEFAULT ((0)) NOT NULL,
    [Cmp_prp_out_flag]    NUMERIC (5)   CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_Cmp_prp_out_flag] DEFAULT ((0)) NOT NULL,
    [is_Cmp_purpose]      TINYINT       CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_is_Cmp_purpose] DEFAULT ((0)) NOT NULL,
    [App_Date]            DATETIME      NULL,
    [Apr_Date]            DATETIME      NULL,
    [System_date]         DATETIME      NULL,
    [Other_Reason]        VARCHAR (MAX) NULL,
    [ManualEntryFlag]     CHAR (3)      CONSTRAINT [DF_T0150_AUDIT_EMP_INOUT_RECORD_ManualEntryFlag] DEFAULT ('N') NULL,
    CONSTRAINT [PK_T0150_AUDIT_EMP_INOUT_RECORD] PRIMARY KEY CLUSTERED ([IO_Tran_Id] ASC),
    CONSTRAINT [FK_T0150_AUDIT_EMP_INOUT_RECORD_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0150_AUDIT_EMP_INOUT_RECORD_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

