CREATE TABLE [dbo].[T0150_Travel_Settlement_Approval_Expense] (
    [int_Exp_Id]           NUMERIC (18)    NOT NULL,
    [int_Id]               NUMERIC (18)    NOT NULL,
    [Travel_Settlement_Id] NUMERIC (18)    NOT NULL,
    [Travel_Approval_Id]   NUMERIC (18)    NOT NULL,
    [Emp_ID]               NUMERIC (18)    NOT NULL,
    [Cmp_ID]               NUMERIC (18)    NOT NULL,
    [For_Date]             DATETIME        NOT NULL,
    [Amount]               NUMERIC (18, 2) NULL,
    [Approved_Amount]      NUMERIC (18, 2) NULL,
    [Expense_Type_id]      NUMERIC (18)    NULL,
    [Comments]             VARCHAR (MAX)   NULL,
    [Missing]              TINYINT         NULL,
    [From_Time]            VARCHAR (25)    NULL,
    [To_Time]              VARCHAR (25)    NULL,
    [Duration]             NUMERIC (18, 2) CONSTRAINT [DF_T0150_Travel_Settlement_Approval_Expense_Duration] DEFAULT ((0)) NOT NULL,
    [Appr_From_Time]       VARCHAR (25)    NULL,
    [Appr_To_Time]         VARCHAR (25)    NULL,
    [Appr_Duration]        NUMERIC (18, 2) CONSTRAINT [DF_T0150_Travel_Settlement_Approval_Expense_Appr_Duration] DEFAULT ((0)) NOT NULL,
    [Grp_Emp]              VARCHAR (MAX)   DEFAULT (NULL) NULL,
    [Grp_Emp_ID]           VARCHAR (MAX)   DEFAULT (NULL) NULL,
    [Curr_ID]              NUMERIC (18)    DEFAULT (NULL) NULL,
    [Exchange_rate]        NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [Curr_Amount]          NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [ExpKm]                NUMERIC (18, 2) DEFAULT (NULL) NULL,
    [SelfPay]              TINYINT         DEFAULT ((0)) NOT NULL,
    [No_of_days]           NUMERIC (18)    NULL,
    [GuestName]            VARCHAR (50)    NULL,
    CONSTRAINT [PK_T0150_Travel_Settlement_Approval_Expense] PRIMARY KEY CLUSTERED ([int_Exp_Id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0150_Travel_Settlement_Approval_Expense_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0150_Travel_Settlement_Approval_Expense_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

