CREATE TABLE [dbo].[T0150_emp_inout_Record_Before_Delete] (
    [IO_Tran_Id]          NUMERIC (18)  NOT NULL,
    [Emp_ID]              NUMERIC (18)  NOT NULL,
    [Cmp_ID]              NUMERIC (18)  NOT NULL,
    [For_Date]            DATETIME      NOT NULL,
    [In_Time]             DATETIME      NULL,
    [Out_Time]            DATETIME      NULL,
    [Duration]            VARCHAR (10)  NULL,
    [Reason]              VARCHAR (100) NULL,
    [Ip_Address]          VARCHAR (50)  NOT NULL,
    [In_Date_Time]        DATETIME      NULL,
    [Out_Date_Time]       DATETIME      NULL,
    [Skip_Count]          NUMERIC (18)  NULL,
    [Late_Calc_Not_App]   NUMERIC (1)   NULL,
    [Chk_By_Superior]     TINYINT       NULL,
    [Sup_Comment]         VARCHAR (100) NULL,
    [Half_Full_day]       VARCHAR (20)  NULL,
    [Is_Cancel_Late_In]   TINYINT       NULL,
    [Is_Cancel_Early_Out] TINYINT       NULL,
    [Is_Default_In]       TINYINT       NULL,
    [Is_Default_Out]      TINYINT       NULL,
    [Cmp_prp_in_flag]     NUMERIC (5)   NOT NULL,
    [Cmp_prp_out_flag]    NUMERIC (5)   NOT NULL,
    [is_Cmp_purpose]      TINYINT       NOT NULL,
    [App_Date]            DATETIME      NULL,
    [Apr_Date]            DATETIME      NULL,
    [System_date]         DATETIME      NULL,
    [Other_Reason]        VARCHAR (MAX) NULL,
    [ManualEntryFlag]     CHAR (3)      NULL,
    [User_ID]             INT           NULL
);

