CREATE TABLE [dbo].[T0185_LOCKED_IN_OUT] (
    [Tran_ID]              INT             IDENTITY (1, 1) NOT NULL,
    [Lock_Id]              INT             NOT NULL,
    [Emp_Id]               INT             NOT NULL,
    [For_date]             DATETIME        NOT NULL,
    [Duration_in_sec]      INT             NULL,
    [Shift_ID]             INT             NULL,
    [Emp_OT]               INT             NULL,
    [P_Days]               NUMERIC (9, 3)  NULL,
    [OT_Sec]               NUMERIC (18)    NULL,
    [In_Time]              DATETIME        NULL,
    [Shift_Start_Time]     DATETIME        NULL,
    [Shift_Change]         TINYINT         NULL,
    [Weekoff_OT_Sec]       INT             NULL,
    [Holiday_OT_Sec]       INT             NULL,
    [Chk_By_Superior]      TINYINT         NULL,
    [Out_Time]             DATETIME        NULL,
    [Shift_End_Time]       DATETIME        NULL,
    [GatePass_Deduct_Days] NUMERIC (18, 2) NULL,
    [Leave_Days]           NUMERIC (9, 3)  NULL,
    [W_Days]               NUMERIC (9, 3)  NULL,
    [H_Days]               NUMERIC (9, 3)  NULL,
    [Late_Sec]             INT             NULL,
    [Early_Sec]            INT             NULL,
    [Status1]              VARCHAR (24)    NULL,
    [Status2]              VARCHAR (24)    NULL,
    [LateSalDeduDays]      NUMERIC (9, 2)  NULL,
    [EarlySalDeduDays]     NUMERIC (9, 2)  NULL,
    CONSTRAINT [fk_LOCKED_IN_OUT] FOREIGN KEY ([Lock_Id]) REFERENCES [dbo].[T0180_LOCKED_ATTENDANCE] ([Lock_Id])
);

