CREATE TABLE [dbo].[T0180_CURRENCY_CONVERSION] (
    [CURR_CONV_ID] NUMERIC (18)    NOT NULL,
    [CMP_ID]       NUMERIC (18)    NOT NULL,
    [CURR_ID]      NUMERIC (18)    NOT NULL,
    [FOR_DATE]     DATETIME        NOT NULL,
    [CURR_RATE]    NUMERIC (22, 2) NOT NULL,
    CONSTRAINT [PK_T0180_CURRENCY_CONVERSION] PRIMARY KEY CLUSTERED ([CURR_CONV_ID] ASC) WITH (FILLFACTOR = 80)
);

