CREATE TABLE [dbo].[T0180_FUEL_CONVERSION] (
    [FUEL_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [CMP_ID]    INT          NULL,
    [FOR_DATE]  DATETIME     NULL,
    [FUEL_RATE] VARCHAR (50) NULL,
    [FUEL_TYPE] VARCHAR (50) NULL,
    CONSTRAINT [PK_T0180_FUEL_CONVERSION] PRIMARY KEY CLUSTERED ([FUEL_ID] ASC)
);

