CREATE TABLE [dbo].[T0190_MONTHLY_AD_DETAIL_IMPORT] (
    [Tran_ID]       NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [Emp_ID]        NUMERIC (18)    NOT NULL,
    [Cmp_ID]        NUMERIC (18)    NOT NULL,
    [AD_ID]         NUMERIC (18)    NOT NULL,
    [Month]         INT             NOT NULL,
    [Year]          INT             NOT NULL,
    [For_Date]      DATETIME        NOT NULL,
    [Amount]        NUMERIC (18, 2) NULL,
    [Comments]      VARCHAR (200)   NOT NULL,
    [Is_Not_Exists] TINYINT         CONSTRAINT [DF_T0190_MONTHLY_AD_DETAIL_IMPORT_Is_Not_Exists] DEFAULT ((0)) NULL,
    [Increment_ID]  NUMERIC (18)    CONSTRAINT [DF_T0190_MONTHLY_AD_DETAIL_IMPORT_Increment_ID] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0190_MONTHLY_AD_DETAIL_IMPORT] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0190_MONTHLY_AD_DETAIL_IMPORT_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0190_MONTHLY_AD_DETAIL_IMPORT_T0050_AD_MASTER] FOREIGN KEY ([AD_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID]),
    CONSTRAINT [FK_T0190_MONTHLY_AD_DETAIL_IMPORT_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_T0190_Monthly_AD_Detail_import_EMPID_ADID_MONTH_YEAR]
    ON [dbo].[T0190_MONTHLY_AD_DETAIL_IMPORT]([Emp_ID] ASC, [AD_ID] ASC, [Month] ASC, [Year] ASC)
    INCLUDE([Cmp_ID], [For_Date]) WITH (FILLFACTOR = 80);

