CREATE TABLE [dbo].[T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY] (
    [Tran_Id]        NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [Cmp_id]         NUMERIC (18)    NOT NULL,
    [Emp_id]         NUMERIC (18)    NOT NULL,
    [Ad_Id]          NUMERIC (18)    NOT NULL,
    [Month]          NUMERIC (18)    NOT NULL,
    [Year]           NUMERIC (18)    NOT NULL,
    [TDS_Amount]     NUMERIC (18, 2) CONSTRAINT [DF_T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY_TDS_Amount] DEFAULT ((0)) NOT NULL,
    [Is_Repeat]      TINYINT         CONSTRAINT [DF_T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY_Is_Repeat] DEFAULT ((0)) NOT NULL,
    [Login_Id]       NUMERIC (18)    CONSTRAINT [DF_T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY_Login_Id] DEFAULT ((0)) NULL,
    [SystemDatetime] DATETIME        CONSTRAINT [DF_T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY_SystemDatetime] DEFAULT (getdate()) NULL,
    [Comments]       VARCHAR (200)   NULL,
    CONSTRAINT [PK_T0190_TAX_IMPORT_ON_NOT_EFFECT_SALARY] PRIMARY KEY CLUSTERED ([Tran_Id] ASC)
);

