CREATE TABLE [dbo].[T0200_Emp_ExitApplication] (
    [exit_id]             NUMERIC (18)  NOT NULL,
    [emp_id]              NUMERIC (18)  NOT NULL,
    [cmp_id]              NUMERIC (18)  NOT NULL,
    [branch_id]           NUMERIC (18)  NULL,
    [desig_id]            NUMERIC (18)  NULL,
    [resignation_date]    DATETIME      NULL,
    [last_date]           DATETIME      NOT NULL,
    [reason]              NUMERIC (18)  NULL,
    [comments]            VARCHAR (100) NULL,
    [status]              CHAR (5)      NOT NULL,
    [is_rehirable]        NUMERIC (18)  NULL,
    [s_emp_id]            NUMERIC (18)  NULL,
    [feedback]            VARCHAR (100) NULL,
    [sup_ack]             CHAR (1)      CONSTRAINT [DF_T0200_Emp_ExitApplication_sup_ack] DEFAULT ('P') NULL,
    [interview_date]      DATETIME      NULL,
    [interview_time]      VARCHAR (50)  NULL,
    [Is_Process]          CHAR (1)      NOT NULL,
    [Email_ForwardTo]     NVARCHAR (50) NULL,
    [DriveData_ForwardTo] NVARCHAR (50) NULL,
    [Rpt_Mng_ID]          NUMERIC (18)  NULL,
    [Application_date]    DATETIME      NULL,
    [Exit_App_Doc]        VARCHAR (MAX) DEFAULT (NULL) NULL,
    [Clearance_ManagerID] VARCHAR (MAX) NULL,
    [User_Id]             NUMERIC (18)  NULL,
    [IP_Address]          VARCHAR (30)  NULL,
    CONSTRAINT [PK_T0200_Emp_ExitApplication] PRIMARY KEY CLUSTERED ([exit_id] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0200_Emp_ExitApplication_T0010_COMPANY_MASTER] FOREIGN KEY ([cmp_id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0200_Emp_ExitApplication_T0080_EMP_MASTER] FOREIGN KEY ([emp_id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0200_Emp_ExitApplication_T0080_EMP_MASTER1] FOREIGN KEY ([s_emp_id]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

