CREATE TABLE [dbo].[T0200_MONTHLY_SALARY_Daily_Daily] (
    [Sal_Tran_ID]              NUMERIC (18)    NOT NULL,
    [Sal_Receipt_No]           NUMERIC (18)    NOT NULL,
    [Emp_ID]                   NUMERIC (18)    NOT NULL,
    [Cmp_ID]                   NUMERIC (18)    NOT NULL,
    [Increment_ID]             NUMERIC (18)    NOT NULL,
    [Month_St_Date]            DATETIME        NOT NULL,
    [Month_End_Date]           DATETIME        NOT NULL,
    [Sal_Generate_Date]        DATETIME        NOT NULL,
    [Sal_Cal_Days]             NUMERIC (18, 1) NOT NULL,
    [Present_Days]             NUMERIC (18, 1) NULL,
    [Absent_Days]              NUMERIC (18, 1) NULL,
    [Holiday_Days]             NUMERIC (18, 1) NULL,
    [Weekoff_Days]             NUMERIC (18, 1) NULL,
    [Cancel_Holiday]           NUMERIC (18, 1) NULL,
    [Cancel_Weekoff]           NUMERIC (18, 1) NULL,
    [Working_Days]             NUMERIC (18, 1) NULL,
    [Outof_Days]               NUMERIC (18, 1) NULL,
    [Total_Leave_Days]         NUMERIC (18, 1) NULL,
    [Paid_Leave_Days]          NUMERIC (18, 1) NULL,
    [Actual_Working_Hours]     VARCHAR (20)    NULL,
    [Working_Hours]            VARCHAR (20)    NULL,
    [Outof_Hours]              VARCHAR (20)    NULL,
    [OT_Hours]                 NUMERIC (18, 1) NULL,
    [Total_Hours]              VARCHAR (20)    NULL,
    [Shift_Day_Sec]            NUMERIC (18)    NULL,
    [Shift_Day_Hour]           VARCHAR (20)    NULL,
    [Basic_Salary]             NUMERIC (18, 2) NULL,
    [Day_Salary]               NUMERIC (18, 5) NULL,
    [Hour_Salary]              NUMERIC (18, 5) NULL,
    [Salary_Amount]            NUMERIC (18, 2) NULL,
    [Allow_Amount]             NUMERIC (18, 2) NULL,
    [OT_Amount]                NUMERIC (18, 2) NULL,
    [Other_Allow_Amount]       NUMERIC (18, 2) NULL,
    [Gross_Salary]             NUMERIC (18, 2) NULL,
    [Dedu_Amount]              NUMERIC (18, 2) NULL,
    [Loan_Amount]              NUMERIC (18, 2) NULL,
    [Loan_Intrest_Amount]      NUMERIC (18, 2) NULL,
    [Advance_Amount]           NUMERIC (18, 2) NULL,
    [Other_Dedu_Amount]        NUMERIC (18, 2) NULL,
    [Total_Dedu_Amount]        NUMERIC (18, 2) NULL,
    [Due_Loan_Amount]          NUMERIC (18, 2) NULL,
    [Net_Amount]               NUMERIC (18, 2) NULL,
    [Actually_Gross_Salary]    NUMERIC (18, 2) NULL,
    [PT_Amount]                NUMERIC (18)    NULL,
    [PT_Calculated_Amount]     NUMERIC (18)    NULL,
    [Total_Claim_Amount]       NUMERIC (18)    NULL,
    [M_OT_Hours]               NUMERIC (18, 1) NULL,
    [M_Adv_Amount]             NUMERIC (18)    NULL,
    [M_Loan_Amount]            NUMERIC (18)    NULL,
    [M_IT_Tax]                 NUMERIC (18)    NULL,
    [LWF_Amount]               NUMERIC (18)    NULL,
    [Revenue_Amount]           NUMERIC (18)    NULL,
    [PT_F_T_Limit]             VARCHAR (20)    NULL,
    [Settelement_Amount]       NUMERIC (18)    NULL,
    [Settelement_Comments]     VARCHAR (250)   NULL,
    [Leave_Salary_Amount]      NUMERIC (18)    NULL,
    [Leave_Salary_Comments]    VARCHAR (250)   NULL,
    [Late_Sec]                 NUMERIC (18)    NULL,
    [Late_Dedu_Amount]         NUMERIC (18)    NULL,
    [Late_Extra_Dedu_Amount]   NUMERIC (18)    NULL,
    [Late_Days]                NUMERIC (5, 1)  NULL,
    [Short_Fall_Days]          NUMERIC (5, 1)  NULL,
    [Short_Fall_Dedu_Amount]   NUMERIC (10)    NULL,
    [Gratuity_Amount]          NUMERIC (10)    NULL,
    [Is_FNF]                   TINYINT         NULL,
    [Bonus_Amount]             NUMERIC (10)    NULL,
    [Incentive_Amount]         NUMERIC (10)    NULL,
    [Trav_Earn_Amount]         NUMERIC (7)     NULL,
    [Cust_Res_Earn_Amount]     NUMERIC (7)     NULL,
    [Trav_Rec_Amount]          NUMERIC (7)     NULL,
    [Mobile_Rec_Amount]        NUMERIC (7)     NULL,
    [Cust_Res_Rec_Amount]      NUMERIC (7)     NULL,
    [Uniform_Rec_Amount]       NUMERIC (7)     NULL,
    [I_Card_Rec_Amount]        NUMERIC (7)     NULL,
    [Excess_Salary_Rec_Amount] NUMERIC (10)    NULL,
    [Salary_Status]            VARCHAR (20)    NULL,
    [Pre_Month_Net_Salary]     NUMERIC (18)    NULL,
    [IT_M_ED_Cess_Amount]      NUMERIC (18, 2) NULL,
    [IT_M_Surcharge_Amount]    NUMERIC (18, 2) NULL
);

