CREATE TABLE [dbo].[T0201_MONTHLY_SALARY_SETT] (
    [S_Sal_Tran_ID]           NUMERIC (18)    NOT NULL,
    [Sal_Tran_ID]             NUMERIC (18)    NULL,
    [S_Sal_Receipt_No]        NUMERIC (18)    NOT NULL,
    [Emp_ID]                  NUMERIC (18)    NOT NULL,
    [Cmp_ID]                  NUMERIC (18)    NOT NULL,
    [Increment_ID]            NUMERIC (18)    NOT NULL,
    [S_Month_St_Date]         DATETIME        NOT NULL,
    [S_Month_End_Date]        DATETIME        NOT NULL,
    [S_Sal_Generate_Date]     DATETIME        NOT NULL,
    [S_Sal_Cal_Days]          NUMERIC (18, 2) NOT NULL,
    [S_Working_Days]          NUMERIC (18, 1) NULL,
    [S_Outof_Days]            NUMERIC (18, 1) NULL,
    [S_OT_Hours]              NUMERIC (18, 1) NULL,
    [S_Shift_Day_Sec]         NUMERIC (18)    NULL,
    [S_Shift_Day_Hour]        VARCHAR (20)    NULL,
    [S_Basic_Salary]          NUMERIC (18, 2) NULL,
    [S_Day_Salary]            NUMERIC (18, 5) NULL,
    [S_Hour_Salary]           NUMERIC (18, 5) NULL,
    [S_Salary_Amount]         NUMERIC (18, 2) NULL,
    [S_Allow_Amount]          NUMERIC (18, 2) NULL,
    [S_OT_Amount]             NUMERIC (18, 2) NULL,
    [S_Other_Allow_Amount]    NUMERIC (18, 2) NULL,
    [S_Gross_Salary]          NUMERIC (18, 2) NULL,
    [S_Dedu_Amount]           NUMERIC (18, 2) NULL,
    [S_Loan_Amount]           NUMERIC (18, 2) NULL,
    [S_Loan_Intrest_Amount]   NUMERIC (18, 2) NULL,
    [S_Advance_Amount]        NUMERIC (18, 2) NULL,
    [S_Other_Dedu_Amount]     NUMERIC (18, 2) NULL,
    [S_Total_Dedu_Amount]     NUMERIC (18, 2) NULL,
    [S_Due_Loan_Amount]       NUMERIC (18, 2) NULL,
    [S_Net_Amount]            NUMERIC (18, 2) NULL,
    [S_Actually_Gross_Salary] NUMERIC (18, 2) NULL,
    [S_PT_Amount]             NUMERIC (18)    CONSTRAINT [DF_Table1_PT_Amount] DEFAULT ((0)) NULL,
    [S_PT_Calculated_Amount]  NUMERIC (18)    CONSTRAINT [DF_Table1_PT_Calculated_Amount] DEFAULT ((0)) NULL,
    [S_Total_Claim_Amount]    NUMERIC (18)    CONSTRAINT [DF_Table1_Total_Claim_Amount] DEFAULT ((0)) NULL,
    [S_M_OT_Hours]            NUMERIC (18, 1) CONSTRAINT [DF_Table1_M_OT_Hours] DEFAULT ((0)) NULL,
    [S_M_Adv_Amount]          NUMERIC (18)    NULL,
    [S_M_Loan_Amount]         NUMERIC (18)    NULL,
    [S_M_IT_Tax]              NUMERIC (18)    NULL,
    [S_LWF_Amount]            NUMERIC (18)    CONSTRAINT [DF_Table1_LWF_Amount] DEFAULT ((0)) NULL,
    [S_Revenue_Amount]        NUMERIC (18)    CONSTRAINT [DF_Table1_Revenue_Amount] DEFAULT ((0)) NULL,
    [S_PT_F_T_Limit]          VARCHAR (20)    NULL,
    [S_Sal_Type]              VARCHAR (20)    NULL,
    [S_Eff_Date]              DATETIME        NOT NULL,
    [Login_ID]                NUMERIC (18)    NOT NULL,
    [Modify_Date]             DATETIME        NOT NULL,
    [S_M_Present_Days]        NUMERIC (12, 1) CONSTRAINT [DF_T0201_MONTHLY_SALARY_SETT_S_M_Present_Days] DEFAULT ((0)) NULL,
    [S_WO_OT_Hours]           NUMERIC (18, 2) NULL,
    [S_HO_OT_Hours]           NUMERIC (18, 2) NULL,
    [S_WO_OT_Amount]          NUMERIC (18, 2) CONSTRAINT [DF_T0201_MONTHLY_SALARY_SETT_S_WO_OT_Amount] DEFAULT ((0)) NOT NULL,
    [S_HO_OT_Amount]          NUMERIC (18, 2) CONSTRAINT [DF_T0201_MONTHLY_SALARY_SETT_S_HO_OT_Amount] DEFAULT ((0)) NOT NULL,
    [Effect_On_Salary]        TINYINT         DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_T0201_MONTHLY_SALARY_SETT] PRIMARY KEY CLUSTERED ([S_Sal_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0201_MONTHLY_SALARY_SETT_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0201_MONTHLY_SALARY_SETT_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0201_MONTHLY_SALARY_SETT_T0095_INCREMENT] FOREIGN KEY ([Increment_ID]) REFERENCES [dbo].[T0095_INCREMENT] ([Increment_ID]),
    CONSTRAINT [FK_T0201_MONTHLY_SALARY_SETT_T0200_MONTHLY_SALARY] FOREIGN KEY ([Sal_Tran_ID]) REFERENCES [dbo].[T0200_MONTHLY_SALARY] ([Sal_Tran_ID])
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T0201_MONTHLY_SALARY_SETT_10_1298103665__K4_31]
    ON [dbo].[T0201_MONTHLY_SALARY_SETT]([Emp_ID] ASC)
    INCLUDE([S_Net_Amount]) WITH (FILLFACTOR = 80);

