CREATE TABLE [dbo].[T0210_PAYSLIP_DATA_DAILY] (
    [PaySlip_Tran_ID]  NUMERIC (18)   NOT NULL,
    [Sal_Tran_ID]      NUMERIC (18)   NULL,
    [Cmp_ID]           NUMERIC (18)   NOT NULL,
    [Allowance_Data]   VARCHAR (8000) NULL,
    [Deduction_Data]   VARCHAR (8000) NULL,
    [Temp_Sal_Tran_ID] NUMERIC (18)   NULL,
    CONSTRAINT [PK_T0210_PAYSLIP_DATA_DAILY] PRIMARY KEY CLUSTERED ([PaySlip_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0210_PAYSLIP_DATA_DAILY_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0210_PAYSLIP_DATA_DAILY_T0200_MONTHLY_SALARY_DAILY] FOREIGN KEY ([Sal_Tran_ID]) REFERENCES [dbo].[T0200_MONTHLY_SALARY_Daily] ([Sal_Tran_ID])
);

