CREATE TABLE [dbo].[T0210_MONTHLY_AD_DETAIL_IMPORT] (
    [I_Tran_ID]      NUMERIC (18)    NOT NULL,
    [Emp_ID]         NUMERIC (18)    NOT NULL,
    [Cmp_ID]         NUMERIC (18)    NOT NULL,
    [AD_ID]          NUMERIC (18)    NOT NULL,
    [For_Date]       DATETIME        NOT NULL,
    [I_AD_Amount]    NUMERIC (18, 2) NOT NULL,
    [I_AD_Comments]  VARCHAR (50)    NOT NULL,
    [I_AD_Max_Limit] NUMERIC (18)    NOT NULL,
    [Is_Not_Exists]  TINYINT         NOT NULL,
    CONSTRAINT [PK_T0210_MONTHLY_AD_DETAIL_IMPORT] PRIMARY KEY CLUSTERED ([I_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0210_MONTHLY_AD_DETAIL_IMPORT_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0210_MONTHLY_AD_DETAIL_IMPORT_T0050_AD_MASTER] FOREIGN KEY ([AD_ID]) REFERENCES [dbo].[T0050_AD_MASTER] ([AD_ID]),
    CONSTRAINT [FK_T0210_MONTHLY_AD_DETAIL_IMPORT_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);

