CREATE TABLE [dbo].[T0210_MONTHLY_LEAVE_DETAIL] (
    [M_Leave_Tran_ID]   NUMERIC (18)    IDENTITY (1, 1) NOT NULL,
    [Temp_Sal_Tran_ID]  NUMERIC (18)    NULL,
    [Emp_ID]            NUMERIC (18)    NOT NULL,
    [Cmp_Id]            NUMERIC (18)    NOT NULL,
    [Leave_ID]          NUMERIC (18)    NOT NULL,
    [Sal_Tran_ID]       NUMERIC (18)    NULL,
    [For_Date]          DATETIME        NOT NULL,
    [Leave_Days]        NUMERIC (18, 4) NOT NULL,
    [Leave_Type]        VARCHAR (50)    NULL,
    [Leave_Paid_Unpaid] CHAR (1)        NULL,
    CONSTRAINT [PK_T0210_MONTHLY_LEAVE_DETAIL] PRIMARY KEY CLUSTERED ([M_Leave_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0210_MONTHLY_LEAVE_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_Id]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0210_MONTHLY_LEAVE_DETAIL_T0040_LEAVE_MASTER] FOREIGN KEY ([Leave_ID]) REFERENCES [dbo].[T0040_LEAVE_MASTER] ([Leave_ID]),
    CONSTRAINT [FK_T0210_MONTHLY_LEAVE_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_T0210_MONTHLY_LEAVE_DETAIL_Emp_ID_Leave_ID_For_Date]
    ON [dbo].[T0210_MONTHLY_LEAVE_DETAIL]([Emp_ID] ASC, [Leave_ID] ASC, [For_Date] ASC)
    INCLUDE([M_Leave_Tran_ID], [Temp_Sal_Tran_ID], [Cmp_Id], [Sal_Tran_ID], [Leave_Days], [Leave_Type], [Leave_Paid_Unpaid]) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0210_MONTHLY_LEAVE_DETAIL_Emp_ID_Sal_Tran_ID]
    ON [dbo].[T0210_MONTHLY_LEAVE_DETAIL]([Emp_ID] ASC, [Sal_Tran_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [IX_T0210_MONTHLY_LEAVE_DETAIL_For_P0200_Pre_Salary]
    ON [dbo].[T0210_MONTHLY_LEAVE_DETAIL]([Temp_Sal_Tran_ID] ASC, [Cmp_Id] ASC);

