CREATE TABLE [dbo].[T0210_PAYSLIP_DATA] (
    [PaySlip_Tran_ID]  NUMERIC (18)   NOT NULL,
    [Sal_Tran_ID]      NUMERIC (18)   NULL,
    [Cmp_ID]           NUMERIC (18)   NOT NULL,
    [Allowance_Data]   VARCHAR (8000) NULL,
    [Deduction_Data]   VARCHAR (8000) NULL,
    [Temp_Sal_Tran_ID] NUMERIC (18)   NULL,
    CONSTRAINT [PK_T0210_PAYSLIP_DATA] PRIMARY KEY CLUSTERED ([PaySlip_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0210_PAYSLIP_DATA_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0210_PAYSLIP_DATA_T0200_MONTHLY_SALARY] FOREIGN KEY ([Sal_Tran_ID]) REFERENCES [dbo].[T0200_MONTHLY_SALARY] ([Sal_Tran_ID])
);


GO
CREATE NONCLUSTERED INDEX [T0210_Payslip_Data_Index]
    ON [dbo].[T0210_PAYSLIP_DATA]([Cmp_ID] ASC, [Sal_Tran_ID] ASC) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [T0210_PAYSLIP_DATA_IX_Tran_ID_Allow_Ded]
    ON [dbo].[T0210_PAYSLIP_DATA]([Temp_Sal_Tran_ID] ASC)
    INCLUDE([PaySlip_Tran_ID], [Allowance_Data], [Deduction_Data]) WITH (FILLFACTOR = 80);

