CREATE TABLE [dbo].[T0230_PF_CHALLAN_DETAIL] (
    [Pf_Challan_ID] NUMERIC (18)  NOT NULL,
    [Cmp_ID]        NUMERIC (18)  NOT NULL,
    [Sr_No]         NUMERIC (18)  NOT NULL,
    [Payment_Head]  VARCHAR (100) NOT NULL,
    [AC_1]          NUMERIC (18)  NOT NULL,
    [AC_2]          NUMERIC (18)  NOT NULL,
    [AC_10]         NUMERIC (18)  NOT NULL,
    [AC_21]         NUMERIC (18)  NOT NULL,
    [AC_22]         NUMERIC (18)  NOT NULL,
    [AC_Total]      NUMERIC (18)  NOT NULL,
    CONSTRAINT [PK_T0230_PF_CHALLAN_DETAIL] PRIMARY KEY CLUSTERED ([Pf_Challan_ID] ASC, [Sr_No] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0230_PF_CHALLAN_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0230_PF_CHALLAN_DETAIL_T0220_PF_CHALLAN] FOREIGN KEY ([Pf_Challan_ID]) REFERENCES [dbo].[T0220_PF_CHALLAN] ([Pf_Challan_ID])
);

