CREATE TABLE [dbo].[T0251_IT_PAID_DETAIL] (
    [Tran_ID]           NUMERIC (18)  NOT NULL,
    [IT_Paid_ID]        NUMERIC (18)  NOT NULL,
    [Cmp_ID]            NUMERIC (18)  NOT NULL,
    [Emp_ID]            NUMERIC (18)  NOT NULL,
    [E_Taxable_Amount]  NUMERIC (18)  NOT NULL,
    [E_IT_Amount]       NUMERIC (12)  NOT NULL,
    [E_IT_Surcharge]    NUMERIC (7)   NOT NULL,
    [E_IT_ED_Cess]      NUMERIC (7)   NOT NULL,
    [E_Total_IT_Amount] NUMERIC (12)  NOT NULL,
    [E_IT_Paid_Amount]  NUMERIC (12)  NOT NULL,
    [E_IT_Comments]     VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_T0251_IT_PAID_DETAIL] PRIMARY KEY CLUSTERED ([Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_T0251_IT_PAID_DETAIL_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id]),
    CONSTRAINT [FK_T0251_IT_PAID_DETAIL_T0080_EMP_MASTER] FOREIGN KEY ([Emp_ID]) REFERENCES [dbo].[T0080_EMP_MASTER] ([Emp_ID]),
    CONSTRAINT [FK_T0251_IT_PAID_DETAIL_T0250_IT_PAID] FOREIGN KEY ([IT_Paid_ID]) REFERENCES [dbo].[T0250_IT_PAID] ([IT_Paid_ID])
);

