CREATE TABLE [dbo].[T0250_DIGITAL_SIGNATURE_POSITION_SETTINGS] (
    [Tran_id] NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [Cmp_id]  NUMERIC (18)  NOT NULL,
    [Module]  NVARCHAR (50) NOT NULL,
    [Param1]  NUMERIC (18)  CONSTRAINT [DF_Table_1_ParamX] DEFAULT ((0)) NOT NULL,
    [Param2]  NUMERIC (18)  CONSTRAINT [DF_Table_1_ParamY] DEFAULT ((0)) NOT NULL,
    [Param3]  NUMERIC (18)  CONSTRAINT [DF_Table_1_ParamH] DEFAULT ((0)) NOT NULL,
    [Param4]  NUMERIC (18)  CONSTRAINT [DF_T0250_DIGITAL_SIGNATURE_POSITION_SETTINGS_Param4] DEFAULT ((0)) NOT NULL,
    [PageNo]  NUMERIC (18)  CONSTRAINT [DF_T0250_DIGITAL_SIGNATURE_POSITION_SETTINGS_PageNo] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T0250_DIGITAL_SIGNATURE_POSITION_SETTINGS] PRIMARY KEY CLUSTERED ([Tran_id] ASC) WITH (FILLFACTOR = 80)
);

