CREATE TABLE [dbo].[T0250_MONTHLY_LOCK_INFORMATION] (
    [Lock_ID]     NUMERIC (18) NOT NULL,
    [Cmp_ID]      NUMERIC (18) NOT NULL,
    [Branch_ID]   NUMERIC (18) NULL,
    [Month]       NUMERIC (5)  NOT NULL,
    [Year]        NUMERIC (5)  NULL,
    [Is_Lock]     NUMERIC (1)  CONSTRAINT [DF_T0250_MONTHLY_LOCK_INFORMATION_Is_Lock] DEFAULT ((0)) NOT NULL,
    [User_ID]     NUMERIC (18) NOT NULL,
    [System_Date] DATETIME     NOT NULL,
    CONSTRAINT [PK_T0250_MONTHLY_LOCK_INFORMATION] PRIMARY KEY CLUSTERED ([Lock_ID] ASC) WITH (FILLFACTOR = 80)
);

