CREATE TABLE [dbo].[T0300_Emp_Exit_Approval_Level] (
    [Tran_Id]             NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Tran_Id] DEFAULT ((0)) NOT NULL,
    [Exit_id]             NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Exit_id] DEFAULT ((0)) NOT NULL,
    [Emp_id]              NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Emp_id] DEFAULT ((0)) NOT NULL,
    [Cmp_id]              NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Cmp_id] DEFAULT ((0)) NOT NULL,
    [Branch_id]           NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Branch_id] DEFAULT ((0)) NULL,
    [Desig_id]            NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Desig_id] DEFAULT ((0)) NULL,
    [Resignation_date]    DATETIME      NULL,
    [Last_date]           DATETIME      NOT NULL,
    [Reason]              NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Reason] DEFAULT ((0)) NULL,
    [Comments]            VARCHAR (100) NULL,
    [Status]              CHAR (5)      NOT NULL,
    [Is_rehirable]        NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Is_rehirable] DEFAULT ((0)) NULL,
    [S_Emp_Id]            NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_S_Emp_Id] DEFAULT ((0)) NULL,
    [Feedback]            VARCHAR (100) NULL,
    [Sup_ack]             CHAR (1)      NULL,
    [Interview_date]      DATETIME      NULL,
    [Interview_time]      VARCHAR (50)  NULL,
    [Is_Process]          CHAR (1)      NOT NULL,
    [Email_ForwardTo]     NVARCHAR (50) NULL,
    [DriveData_ForwardTo] NVARCHAR (50) NULL,
    [Rpt_Mng_ID]          NUMERIC (18)  CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Rpt_Mng_ID] DEFAULT ((0)) NULL,
    [RPT_Level]           TINYINT       CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_RPT_Level] DEFAULT ((0)) NULL,
    [Final_Approval]      TINYINT       CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Final_Approval] DEFAULT ((0)) NULL,
    [Is_FWD_REJECT]       TINYINT       CONSTRAINT [DF_T0300_Emp_Exit_Approval_Level_Is_FWD_REJECT] DEFAULT ((0)) NULL,
    [Application_date]    DATETIME      NULL,
    [Approval_date]       DATETIME      NULL,
    [Clearance_ManagerID] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_T0300_Emp_Exit_Approval_Level_1] PRIMARY KEY CLUSTERED ([Tran_Id] ASC)
);

