CREATE TABLE [dbo].[T9999_USER_FEEDBACK] (
    [USER_ID]     NUMERIC (18)   NOT NULL,
    [USER_NAME]   VARCHAR (100)  NOT NULL,
    [CMP_NAME]    VARCHAR (100)  NULL,
    [CMP_ADDRESS] VARCHAR (100)  NULL,
    [LOCATION]    VARCHAR (50)   NULL,
    [CMP_TEL_NO]  VARCHAR (50)   NULL,
    [MOB_NO]      VARCHAR (50)   NULL,
    [EMAIL_ID]    VARCHAR (100)  NOT NULL,
    [COMMENTS]    VARCHAR (1000) NOT NULL,
    [POST_DATE]   DATETIME       NOT NULL,
    [IP_ADDRESS]  VARCHAR (50)   NULL,
    CONSTRAINT [PK_T9999_USER_FEEDBACK] PRIMARY KEY CLUSTERED ([USER_ID] ASC) WITH (FILLFACTOR = 80)
);

