CREATE TABLE [dbo].[T9999_IMPORT_Week_SCHEDULE] (
    [Emp_ID]   NUMERIC (18)  NOT NULL,
    [Emp_Name] VARCHAR (100) NOT NULL,
    [Emp_Code] NUMERIC (18)  NOT NULL,
    [Month]    NUMERIC (2)   NOT NULL,
    [Year]     NUMERIC (10)  NOT NULL,
    [Day1]     VARCHAR (10)  NOT NULL,
    [Day2]     VARCHAR (10)  NULL,
    [Day3]     VARCHAR (10)  NULL,
    [Day4]     VARCHAR (10)  NULL,
    [Day5]     VARCHAR (10)  NULL,
    [Day6]     VARCHAR (10)  NULL,
    [Day7]     VARCHAR (10)  NULL,
    [Day8]     VARCHAR (10)  NULL,
    [Day9]     VARCHAR (10)  NULL,
    [Day10]    VARCHAR (10)  NULL,
    [Day11]    VARCHAR (10)  NULL,
    [Day12]    VARCHAR (10)  NULL,
    [Day13]    VARCHAR (10)  NULL,
    [Day14]    VARCHAR (10)  NULL,
    [Day15]    VARCHAR (10)  NULL,
    [Day16]    VARCHAR (10)  NULL,
    [Day17]    VARCHAR (10)  NULL,
    [Day18]    VARCHAR (10)  NULL,
    [Day19]    VARCHAR (10)  NULL,
    [Day20]    VARCHAR (10)  NULL,
    [Day21]    VARCHAR (10)  NULL,
    [Day22]    VARCHAR (10)  NULL,
    [Day23]    VARCHAR (10)  NULL,
    [Day24]    VARCHAR (10)  NULL,
    [Day25]    VARCHAR (10)  NULL,
    [Day26]    VARCHAR (10)  NULL,
    [Day27]    VARCHAR (10)  NULL,
    [Day28]    VARCHAR (10)  NULL,
    [Day29]    VARCHAR (10)  NULL,
    [Day30]    VARCHAR (10)  NULL,
    [Day31]    VARCHAR (10)  NULL,
    CONSTRAINT [PK_T9999_IMPORT_Week_SCHEDULE] PRIMARY KEY CLUSTERED ([Emp_ID] ASC, [Month] ASC, [Year] ASC) WITH (FILLFACTOR = 80)
);

