CREATE TABLE [dbo].[T9999_EMPLOYEE_ENROLLMENT] (
    [IO_Tran_ID] NUMERIC (18) NOT NULL,
    [Branch_ID]  NUMERIC (18) NOT NULL,
    [Enroll_No]  NUMERIC (18) NOT NULL,
    [USER_NAME]  VARCHAR (50) NOT NULL,
    [LFPDATA]    TEXT         NOT NULL,
    [LFPNO]      VARCHAR (20) NOT NULL,
    [RFPDATA]    TEXT         NOT NULL,
    [RFPNO]      VARCHAR (10) NOT NULL,
    [LFISO]      IMAGE        NULL,
    [RFISO]      IMAGE        NULL,
    CONSTRAINT [PK_T9999_EMPLOYEE_ENROLLMENT] PRIMARY KEY CLUSTERED ([IO_Tran_ID] ASC) WITH (FILLFACTOR = 80)
);

