CREATE TABLE [dbo].[T9999_LICENSE_REQUEST] (
    [LIC_REQ_ID]     NUMERIC (18)   NOT NULL,
    [CONTACT_PERSON] VARCHAR (100)  NOT NULL,
    [CMP_NAME]       VARCHAR (100)  NOT NULL,
    [CMP_ADDRESS]    VARCHAR (250)  NOT NULL,
    [LOCATION]       VARCHAR (50)   NOT NULL,
    [TEL_NO]         VARCHAR (100)  NOT NULL,
    [MOB_NO]         VARCHAR (100)  NOT NULL,
    [EMAIL_ID]       VARCHAR (100)  NOT NULL,
    [NO_OF_EMP]      NUMERIC (10)   NOT NULL,
    [REQ_DATE]       DATETIME       NOT NULL,
    [OWN_SERVER]     NUMERIC (1)    NOT NULL,
    [SUP_TYPE]       NUMERIC (2)    NOT NULL,
    [MOD_REQUIRE]    NUMERIC (1)    NOT NULL,
    [MOD_COMMENTS]   VARCHAR (1000) NOT NULL,
    [IP_ADDRESS]     VARCHAR (50)   NULL,
    CONSTRAINT [PK_T9999_LICENSE_REQUEST] PRIMARY KEY CLUSTERED ([LIC_REQ_ID] ASC) WITH (FILLFACTOR = 80)
);

