CREATE TABLE [dbo].[Table2] (
    [IT_Tran_ID] NUMERIC (18)  NOT NULL,
    [Cmp_ID]     NUMERIC (18)  NOT NULL,
    [IT_Name]    VARCHAR (100) NOT NULL,
    [Max_Limit]  NUMERIC (18)  NULL,
    CONSTRAINT [PK_Table2] PRIMARY KEY CLUSTERED ([IT_Tran_ID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Table2_T0010_COMPANY_MASTER] FOREIGN KEY ([Cmp_ID]) REFERENCES [dbo].[T0010_COMPANY_MASTER] ([Cmp_Id])
);

