CREATE TABLE [dbo].[Temp_Pre_Salary_Data_monthly] (
    [Type]                  NVARCHAR (50)   NULL,
    [M_Sal_Tran_ID]         NVARCHAR (50)   NULL,
    [Emp_Id]                NUMERIC (18)    NULL,
    [Cmp_ID]                NUMERIC (18)    NULL,
    [Sal_Generate_Date]     NVARCHAR (50)   NULL,
    [Month_St_Date]         NVARCHAR (50)   NULL,
    [Month_End_Date]        NVARCHAR (50)   NULL,
    [M_OT_Hours]            NUMERIC (18, 2) NULL,
    [Areas_Amount]          NUMERIC (18, 2) NULL,
    [M_IT_Tax]              NUMERIC (18, 2) NULL,
    [Other_Dedu]            NUMERIC (18, 2) NULL,
    [M_LOAN_AMOUNT]         NUMERIC (18)    NULL,
    [M_ADV_AMOUNT]          NUMERIC (18)    NULL,
    [IS_LOAN_DEDU]          NUMERIC (18)    NULL,
    [Login_ID]              NUMERIC (18)    NULL,
    [ErrRaise]              VARCHAR (100)   NULL,
    [Is_Negetive]           VARCHAR (1)     NULL,
    [Status]                VARCHAR (10)    NULL,
    [IT_M_ED_Cess_Amount]   NUMERIC (18, 2) NULL,
    [IT_M_Surcharge_Amount] NUMERIC (18, 2) NULL,
    [Allo_On_Leave]         NUMERIC (18)    NULL,
    [W_OT_Hours]            NUMERIC (18, 2) NULL,
    [H_OT_Hours]            NUMERIC (18, 2) NULL,
    [User_Id]               NUMERIC (18)    NULL,
    [IP_Address]            VARCHAR (30)    NULL,
    [IS_Bond_DEDU]          BIT             NULL
);

