CREATE TABLE [dbo].[Test1129] (
    [Emp_Code]                            VARCHAR (20)    NULL,
    [Emp_Name]                            VARCHAR (100)   NULL,
    [Branch_Name]                         VARCHAR (50)    NULL,
    [Joining_Date]                        DATETIME        NULL,
    [Increment_Type]                      VARCHAR (100)   NULL,
    [Entry_Type]                          VARCHAR (30)    NULL,
    [Grade]                               VARCHAR (50)    NULL,
    [Designation]                         VARCHAR (50)    NULL,
    [Department]                          VARCHAR (50)    NULL,
    [Basic_Salary]                        NUMERIC (18, 2) NULL,
    [Gross_Salary]                        NUMERIC (18, 2) NULL,
    [CTC]                                 NUMERIC (18, 2) NULL,
    [Reason_Name]                         VARCHAR (500)   NULL,
    [FNF Recovery]                        NUMERIC (18, 2) NULL,
    [Other_Bonus]                         NUMERIC (18, 2) NULL,
    [Salary_CTC]                          NUMERIC (18, 2) NULL,
    [FNF Test]                            NUMERIC (18, 2) NULL,
    [Employee Retention]                  NUMERIC (18, 2) NULL,
    [Ecogreen Allowance]                  NUMERIC (18, 2) NULL,
    [Transport_Allowance_BG]              NUMERIC (18, 2) NULL,
    [Conveyance_AIA]                      NUMERIC (18, 2) NULL,
    [Quarterly_Reim]                      NUMERIC (18, 2) NULL,
    [Allowance Test]                      NUMERIC (18, 2) NULL,
    [Deputation Allowance]                NUMERIC (18, 2) NULL,
    [R TEST]                              NUMERIC (18, 2) NULL,
    [MED REIM]                            NUMERIC (18, 2) NULL,
    [vfvfdvfdvd]                          NUMERIC (18, 2) NULL,
    [On Time Arrival Perormance]          NUMERIC (18, 2) NULL,
    [Housing Rent Allowance]              NUMERIC (18, 2) NULL,
    [Dearness Allowance]                  NUMERIC (18, 2) NULL,
    [Overtime Allowance]                  NUMERIC (18, 2) NULL,
    [City Compensatory Allowance]         NUMERIC (18, 2) NULL,
    [Children Education Allowance]        NUMERIC (18, 2) NULL,
    [Transportation Allowance]            NUMERIC (18, 2) NULL,
    [Conveyance Reimbursement]            NUMERIC (18, 2) NULL,
    [Arrears Basic]                       NUMERIC (18, 2) NULL,
    [Leave Travell Allowance]             NUMERIC (18, 2) NULL,
    [Medical Reimbursement]               NUMERIC (18, 2) NULL,
    [Telephone Reimbursement]             NUMERIC (18, 2) NULL,
    [Business Attire Reimbursement]       NUMERIC (18, 2) NULL,
    [Car Expenses Reimbursement]          NUMERIC (18, 2) NULL,
    [AIAAttendanceAllow]                  NUMERIC (18, 2) NULL,
    [Training Expense Reim]               NUMERIC (18, 2) NULL,
    [Gratuity]                            NUMERIC (18, 2) NULL,
    [Ex Gratia Bonus]                     NUMERIC (18, 2) NULL,
    [AUTOPAID BONUS]                      NUMERIC (18, 2) NULL,
    [Conveyance]                          NUMERIC (18, 2) NULL,
    [Bonus]                               NUMERIC (18, 2) NULL,
    [Employee Award]                      NUMERIC (18, 2) NULL,
    [Attendance Allowance]                NUMERIC (18, 2) NULL,
    [Production Bonus]                    NUMERIC (18, 2) NULL,
    [Production Variable]                 NUMERIC (18, 2) NULL,
    [Insurance Payment]                   NUMERIC (18, 2) NULL,
    [Production Bonus2]                   NUMERIC (18, 2) NULL,
    [Telephon_bill]                       NUMERIC (18, 2) NULL,
    [Production Variable2]                NUMERIC (18, 2) NULL,
    [Incentive_Import]                    NUMERIC (18, 2) NULL,
    [Benefit_Fix]                         NUMERIC (18, 2) NULL,
    [Transport Assist]                    NUMERIC (18, 2) NULL,
    [Extra Pay]                           NUMERIC (18, 2) NULL,
    [Leave Allowance]                     NUMERIC (18, 2) NULL,
    [Fix Allowance]                       NUMERIC (18, 2) NULL,
    [Canteen Amount1]                     NUMERIC (18, 2) NULL,
    [Overtime Payment]                    NUMERIC (18, 2) NULL,
    [Special Arrear]                      NUMERIC (18, 2) NULL,
    [Company ESIC Contirbution]           NUMERIC (18, 2) NULL,
    [Company PF Contribution]             NUMERIC (18, 2) NULL,
    [Special Allowance]                   NUMERIC (18, 2) NULL,
    [Special Gross]                       NUMERIC (18, 2) NULL,
    [Employee PF]                         NUMERIC (18, 2) NULL,
    [Employee ESIC Contirbution]          NUMERIC (18, 2) NULL,
    [TDS]                                 NUMERIC (18, 2) NULL,
    [General Providence Fund]             NUMERIC (18, 2) NULL,
    [Advance]                             NUMERIC (18, 2) NULL,
    [Tour Deduction]                      NUMERIC (18, 2) NULL,
    [Other Deduction]                     NUMERIC (18, 2) NULL,
    [Other_TDS_CHECK]                     NUMERIC (18, 2) NULL,
    [Canteen Payment]                     NUMERIC (18, 2) NULL,
    [NPF1]                                NUMERIC (18, 2) NULL,
    [NPF2]                                NUMERIC (18, 2) NULL,
    [NPF3]                                NUMERIC (18, 2) NULL,
    [Transport Allowance_Slab]            NUMERIC (18, 2) NULL,
    [Business_Attire_Reimbursement__]     NUMERIC (18, 2) NULL,
    [Vehicle Maintenance Reimbursement]   NUMERIC (18, 2) NULL,
    [Vehicle_Maintenance_Reimbursement__] NUMERIC (18, 2) NULL,
    [Books And Periodical]                NUMERIC (18, 2) NULL,
    [Books N Periodical]                  NUMERIC (18, 2) NULL,
    [C_Telephone Reimbursement]           NUMERIC (18, 2) NULL,
    [C_Telephone Reimbursement__]         NUMERIC (18, 2) NULL,
    [Special Allowance_Corona]            NUMERIC (18, 2) NULL,
    [Extra OT Payment]                    NUMERIC (18, 2) NULL,
    [Car Retention]                       NUMERIC (18, 2) NULL,
    [Variable Payment]                    NUMERIC (18, 2) NULL,
    [Incentive_Worker]                    NUMERIC (18, 2) NULL,
    [Incentive Staff]                     NUMERIC (18, 2) NULL,
    [Seniority Awards]                    NUMERIC (18, 2) NULL,
    [Bond Return]                         NUMERIC (18, 2) NULL,
    [Night Halt]                          NUMERIC (18, 2) NULL,
    [Interest Subsidy Amount]             NUMERIC (18, 2) NULL,
    [arrear]                              NUMERIC (18, 2) NULL,
    [Reference Allowance]                 NUMERIC (18, 2) NULL,
    [Other Amount]                        NUMERIC (18, 2) NULL,
    [Penalty]                             NUMERIC (18, 2) NULL,
    [Attendance AllowanceArkay]           NUMERIC (18, 2) NULL,
    [Shift Allowance_Arkay]               NUMERIC (18, 2) NULL,
    [Extra TDS]                           NUMERIC (18, 2) NULL,
    [Subsidy interest]                    NUMERIC (18, 2) NULL,
    [Arrears Deduction]                   NUMERIC (18, 2) NULL,
    [Optional Allowance1]                 NUMERIC (18, 2) NULL,
    [Hold Salary import]                  NUMERIC (18, 2) NULL,
    [Performace Incetive]                 NUMERIC (18, 2) NULL,
    [Client Tour Claim]                   NUMERIC (18, 2) NULL,
    [Food Allowance]                      NUMERIC (18, 2) NULL,
    [Travelling Allowance]                NUMERIC (18, 2) NULL,
    [Adhoc Allowance]                     NUMERIC (18, 2) NULL,
    [Night_Shift_Allowance]               NUMERIC (18, 2) NULL,
    [IT_Tax]                              NUMERIC (18, 2) NULL,
    [Employer ESIC Contribution]          NUMERIC (18, 2) NULL,
    [Quarterly_Amount]                    NUMERIC (18, 2) NULL,
    [Quarterly_Percentage]                NUMERIC (18, 2) NULL
);

