


---23/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_INCREMENT_CALC]
    @TRAN_ID NUMERIC OUTPUT
   ,@CMP_ID NUMERIC
   ,@FOR_DATE DATETIME
   ,@BRANCH_ID	NUMERIC
   ,@PERTICULARS VARCHAR(512)
   ,@LOGIN_ID   NUMERIC(18,0)
   ,@TRAN_TYPE	Char(1)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	--IF(@FOR_DATE='1900-01-01')
	--	SET @FOR_DATE=NULL	
		
			
	IF ISNULL(@CMP_ID,0) = 0
		BEGIN 
			RAISERROR('@@ Company ID must be specified @@',16,2) 
			RETURN
		END
		
	IF ISNULL(@BRANCH_ID,0) = 0
		BEGIN 
			RAISERROR('@@ Branch ID must be specified @@',16,2) 
			RETURN
		END
	ELSE IF NOT EXISTS(SELECT 1 FROM T0030_BRANCH_MASTER WITH (NOLOCK) WHERE Cmp_ID=@CMP_ID AND Branch_ID = @BRANCH_ID)
		BEGIN 
			RAISERROR('@@ Branch does not exist in selected company @@',16,2) 
			RETURN
		END
	IF (IsNull(@FOR_DATE,'1900-01-01') ='1900-01-01' )  	
		BEGIN
			RAISERROR('@@ For Date must be specified  @@',16,2)  		
			RETURN
		END
	
	
			
 IF @TRAN_TYPE  = 'I' OR @TRAN_TYPE  = 'U'
	BEGIN		
		
				IF EXISTS(SELECT 1 FROM DBO.T0040_INCREMENT_CALC WITH (NOLOCK) WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID)
					BEGIN
					
						SELECT @TRAN_ID = TRAN_ID
						FROM T0040_INCREMENT_CALC WITH (NOLOCK)
						WHERE BRANCH_ID=@BRANCH_ID AND  FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID
					
						UPDATE dbo.T0040_INCREMENT_CALC SET PARTICULARS=@PERTICULARS,LOGIN_ID=@LOGIN_ID,SYSTEMDATE=GETDATE()
							WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID
							
					END	
				ELSE IF NOT EXISTS (SELECT 1 FROM dbo.T0040_INCREMENT_CALC WITH (NOLOCK) WHERE BRANCH_ID=@BRANCH_ID AND FOR_DATE=@FOR_DATE AND CMP_ID=@CMP_ID)
					BEGIN
					
						SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0) + 1  FROM dbo.T0040_INCREMENT_CALC WITH (NOLOCK)
			    		INSERT INTO dbo.T0040_INCREMENT_CALC(CMP_ID,TRAN_ID,FOR_DATE,BRANCH_ID,PARTICULARS,LOGIN_ID,SYSTEMDATE)
							VALUES(@CMP_ID,@TRAN_ID,@FOR_DATE,@BRANCH_ID,@PERTICULARS,@LOGIN_ID,GETDATE())
							
					END
	
		DELETE FROM T0045_INCREMENT_WAGES_SLAB WHERE  TRAN_ID=@TRAN_ID
		DELETE FROM T0045_INCREMENT_DAYS_SLAB WHERE  TRAN_ID=@TRAN_ID
	
			
			
	END 
 ELSE IF @TRAN_TYPE='D'
 BEGIN
		IF EXISTS(SELECT 1 FROM DBO.T0040_INCREMENT_CALC WITH (NOLOCK) WHERE TRAN_ID=@TRAN_ID)
		BEGIN
		DELETE FROM T0045_INCREMENT_WAGES_SLAB WHERE  TRAN_ID=@TRAN_ID
		DELETE FROM T0045_INCREMENT_DAYS_SLAB WHERE  TRAN_ID=@TRAN_ID
		DELETE FROM T0040_INCREMENT_CALC WHERE  TRAN_ID=@TRAN_ID
		END
		
 END
 ELSE 
	BEGIN
		IF EXISTS(SELECT 1 FROM T0040_INCREMENT_CALC WITH (NOLOCK))
			BEGIN
				SELECT INC.TRAN_ID,CONVERT(VARCHAR(10),INC.FOR_DATE,103) AS FOR_DATE,BRCH.BRANCH_NAME FROM T0040_INCREMENT_CALC AS INC WITH (NOLOCK)
				INNER JOIN T0030_BRANCH_MASTER AS BRCH WITH (NOLOCK) ON BRCH.Branch_ID=INC.BRANCH_ID WHERE INC.CMP_ID=@CMP_ID AND INC.BRANCH_ID=@BRANCH_ID
			END
	END
 
END




