


---29/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_OT_CALC_SLAB]
	--@TRAN_ID NUMERIC  OUTPUT
	@GEN_ID NUMERIC(18,0)
   ,@CMP_ID NUMERIC(18,0)
   ,@FROM_HOURS	NUMERIC(9,2)
   ,@TO_HOURS NUMERIC(9,2)
   ,@WD_RATE NUMERIC(9,4) = 0
   ,@WO_RATE NUMERIC(9,4) = 0 
   ,@HO_RATE NUMERIC(9,4) = 0
   ,@SYSTEM_DATE DATETIME = NULL
   ,@TRAN_TYPE	Char(1)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	DECLARE @COUNT_ROW AS NUMERIC(18,0) = 0
 	DECLARE @TRAN_ID NUMERIC  = 0  
 	
 IF @TRAN_TYPE  = 'I'
	BEGIN	 	
		         
		SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0) + 1  FROM dbo.T0050_GENERAL_OT_RATE_SLABWISE WITH (NOLOCK) WHERE GEN_ID=@GEN_ID AND CMP_ID = @CMP_ID
		IF @TRAN_ID <> 0
			BEGIN
				
				INSERT INTO dbo.T0050_GENERAL_OT_RATE_SLABWISE
					(Tran_ID,GEN_ID,CMP_ID,FROM_HOURS,TO_HOURS,WD_RATE,WO_RATE,HO_RATE,SYSTEMDATE)
				VALUES
					(@TRAN_ID,@GEN_ID,@CMP_ID,@FROM_HOURS,@TO_HOURS,@WD_RATE,@WO_RATE,@HO_RATE,GETDATE()) 
					
			END
				
	END  
 ELSE IF @TRAN_TYPE = 'D'
	BEGIN
	
		DELETE FROM dbo.T0050_GENERAL_OT_RATE_SLABWISE WHERE GEN_ID=@GEN_ID AND CMP_ID = @CMP_ID
		
	END
 	
END




