

---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_TRAINING_RATING_MASTER]
	@RAT_ID AS NUMERIC OUTPUT,
	@CMP_ID AS NUMERIC,
	@EFFECTIVE_DATE AS DATETIME,
	@RAT_DESCRIPTION AS VARCHAR(200),
	@RAT_SCORE AS Numeric(5,2),
	@TRAN_TYPE VARCHAR(1),
	@USER_ID NUMERIC(18,0) = 0,
	@IP_ADDRESS VARCHAR(30)= '' 
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

DECLARE @OLDVALUE VARCHAR(MAX)

DECLARE @OLD_RAT_ID AS NUMERIC
DECLARE @OLD_EFFECTIVE_DATE AS DATETIME
DECLARE @OLD_RAT_DESCRIPTION AS VARCHAR(200)
DECLARE @OLD_RAT_SCORE AS NUMERIC(5,2)


	IF @TRAN_TYPE  = 'I'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_TRAINING_RATING_MASTER WITH (NOLOCK)  WHERE CMP_ID = @CMP_ID AND Effective_Date = @EFFECTIVE_DATE AND Rat_ID = @RAT_ID) 
				BEGIN   
					SET @RAT_ID = 0
					RETURN 
				END 
				  
			SELECT @RAT_ID= ISNULL(MAX(RAT_ID),0) + 1 FROM T0040_TRAINING_RATING_MASTER WITH (NOLOCK)

			INSERT INTO T0040_TRAINING_RATING_MASTER
						(RAT_ID,CMP_ID,EFFECTIVE_DATE,RAT_DESCRIPTION,RAT_SCORE,MODIFY_DATE,MODIFY_BY,IP_ADDRESS)
			VALUES      (@RAT_ID,@CMP_ID,@EFFECTIVE_DATE,@RAT_DESCRIPTION,@RAT_SCORE,GETDATE(),@USER_ID,@IP_ADDRESS)
				   		
			SET @OLDVALUE = 'NEW VALUE' + '#'+ 'RATING NAME :' +ISNULL( @RAT_DESCRIPTION,'') + '#'
										+ '#'+ 'RATING SCORE :' +ISNULL(Cast(@RAT_SCORE as Varchar(10)),'') + '#'
										+ '#'+ 'EFFECTIVE DATE :' +ISNULL(Cast(@EFFECTIVE_DATE as Varchar(11)),'') + '#'
		END
	ELSE IF @TRAN_TYPE = 'U'
		BEGIN
			
				--IF EXISTS(SELECT 1 FROM T0040_TRAINING_RATING_MASTER  WHERE CMP_ID = @CMP_ID AND Effective_Date = @EFFECTIVE_DATE AND Rat_ID = @RAT_ID)
				--	BEGIN
				--		SET @RAT_ID = 0
				--		RETURN 
				--	END
				
                 SELECT
					 @OLD_RAT_DESCRIPTION  = ISNULL(RAT_DESCRIPTION,''),
					 @OLD_EFFECTIVE_DATE = ISNULL(EFFECTIVE_DATE,''),
					 @OLD_RAT_SCORE = ISNULL(Cast(RAT_SCORE as Varchar(15)),'')
				 FROM T0040_TRAINING_RATING_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND RAT_ID = @RAT_ID
          
				UPDATE T0040_TRAINING_RATING_MASTER
					SET RAT_DESCRIPTION = @RAT_DESCRIPTION,
					    EFFECTIVE_DATE = @EFFECTIVE_DATE,
						RAT_SCORE =  @RAT_SCORE 
				WHERE CMP_ID = @CMP_ID AND RAT_ID = @RAT_ID AND Effective_Date = @EFFECTIVE_DATE
				
				SET @OLDVALUE = 'OLD VALUE' + '#'+ 'RATING NAME :' +ISNULL(@OLD_RAT_DESCRIPTION,'') + '#'
											+ '#'+ 'RATING SCORE :' +ISNULL(Cast(@OLD_RAT_SCORE as Varchar(10)),'') + '#'
											+ '#'+ 'EFFECTIVE DATE :' +ISNULL(Cast(@OLD_EFFECTIVE_DATE as Varchar(15)),'') + '#'
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
		
			SELECT
				@OLD_RAT_DESCRIPTION  = ISNULL(RAT_DESCRIPTION,''),
				@OLD_EFFECTIVE_DATE = ISNULL(Cast(EFFECTIVE_DATE as Varchar(15)),''),
				@OLD_RAT_SCORE = ISNULL(Cast(RAT_SCORE as Varchar(15)),'')
			FROM DBO.T0040_TRAINING_RATING_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND RAT_ID = @RAT_ID
			
			DELETE FROM T0040_TRAINING_RATING_MASTER WHERE CMP_ID = @CMP_ID AND Effective_Date = @EFFECTIVE_DATE

			SET @OLDVALUE = 'OLD VALUE' + '#'+ 'RATING NAME :' +ISNULL(@OLD_RAT_DESCRIPTION,'') + '#'
											+ '#'+ 'RATING SCORE :' +ISNULL(Cast(@OLD_RAT_SCORE as Varchar(10)),'') + '#'
											+ '#'+ 'EFFECTIVE DATE :' +ISNULL(Cast(@OLD_EFFECTIVE_DATE as Varchar(15)),'') + '#'
		END
           
	EXEC P9999_AUDIT_TRAIL @CMP_ID,@TRAN_TYPE,'TRAINING RATING MASTER',@OLDVALUE,@RAT_ID,@USER_ID,@IP_ADDRESS
	RETURN




