-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
---22/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0045_Claim_FNF_Deduction_Slab]
	@CMP_ID NUMERIC(18,0),
	@CLAIM_ID NUMERIC(18,0),
	@NO_OF_YEAR NUMERIC(18,2),
	@DEDU_IN_PER NUMERIC(18,2),
	@EFFECTIVE_DATE DATETIME
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


	DECLARE @CLAIM_FNF_ID NUMERIC(18,0)
	SET @CLAIM_FNF_ID = 0

	
	SELECT @CLAIM_FNF_ID = ISNULL(MAX(CLAIM_FNF_ID),0)+1 FROM T0045_CLAIM_FNF_DEDUCTION_SLAB WITH (NOLOCK)

	INSERT INTO T0045_CLAIM_FNF_DEDUCTION_SLAB (CLAIM_FNF_ID,CMP_ID,CLAIM_ID,NO_OF_YEAR,DEDU_IN_PER,EFFECTIVE_DATE)
	VALUES (@CLAIM_FNF_ID,@CMP_ID,@CLAIM_ID,@NO_OF_YEAR,@DEDU_IN_PER,@EFFECTIVE_DATE)
END
