
---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_TRAINING_SKILL_MASTER]
	@SKILL_ID AS NUMERIC OUTPUT,
	@SKILL_NAME AS VARCHAR(50),
	@Skill_Sort_ID NUMERIC,
	@CMP_ID AS NUMERIC,
	@TRAN_TYPE VARCHAR(1),
	@USER_ID NUMERIC(18,0) = 0,
	@IP_ADDRESS VARCHAR(30)= '' 
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


DECLARE @OLDVALUE AS  VARCHAR(MAX)

DECLARE @OLDSKILL_NAME AS VARCHAR(50)
SET @OLDSKILL_NAME =''
DECLARE @OLDSORT_NO AS VARCHAR(50)
SET @OLDSORT_NO =''


	IF @TRAN_TYPE  = 'I'
		BEGIN
				 IF EXISTS(SELECT SKILL_ID FROM T0040_TRAINING_SKILL_MASTER WITH (NOLOCK)  WHERE CMP_ID = @CMP_ID AND UPPER(SKILL_NAME) = UPPER(@SKILL_NAME)) 
					BEGIN   
						SET @SKILL_ID = 0
						RETURN 
					END
		         
				  IF @SKILL_NAME  <> ''
					BEGIN 
						SELECT @SKILL_ID= ISNULL(MAX(SKILL_ID),0) + 1 	FROM T0040_TRAINING_SKILL_MASTER WITH (NOLOCK)
						INSERT INTO T0040_TRAINING_SKILL_MASTER
											  (SKILL_ID, CMP_ID, SKILL_NAME,SKILL_SORT_ID,MODIFY_DATE,MODIFY_BY,IP_ADDRESS)
						VALUES     (@SKILL_ID, @CMP_ID,@SKILL_NAME,@SKILL_SORT_ID,GETDATE(),@USER_ID,@IP_ADDRESS)
				
				   END
				   		
				SET @OLDVALUE = 'NEW VALUE' + '#'+ 'SKILL NAME :' +ISNULL( @SKILL_NAME,'') + '#' + 'SORT NO :' +ISNULL(Cast(@SKILL_SORT_ID as Varchar(10)),'') + '#' 
		END
	ELSE IF @TRAN_TYPE = 'U'
		BEGIN
				IF EXISTS(SELECT SKILL_ID FROM T0040_TRAINING_SKILL_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND SKILL_ID <> @SKILL_ID AND UPPER(SKILL_NAME) = UPPER(@SKILL_NAME))
					BEGIN
						SET @SKILL_ID = 0
						RETURN 
					END
					
                 SELECT @OLDSKILL_NAME  =ISNULL(SKILL_NAME,''),@OLDSORT_NO = Cast(Skill_Sort_ID as Varchar(10)) FROM DBO.T0040_TRAINING_SKILL_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND SKILL_ID = @SKILL_ID
          
				UPDATE T0040_TRAINING_SKILL_MASTER
					SET SKILL_NAME=@SKILL_NAME,
					    SKILL_SORT_ID = @SKILL_SORT_ID		    
				WHERE SKILL_ID = @SKILL_ID
				
				SET @OLDVALUE = 'OLD VALUE' + '#'+ 'SKILL NAME :' + @OLDSKILL_NAME + '#'+ 'SORT NAME :' + @OLDSORT_NO + 'NEW VALUE' + '#'+ 'SKILLNAME :' +ISNULL( @SKILL_NAME,'') + '#'+ 'SORT NO :' +ISNULL(Cast(@SKILL_SORT_ID as Varchar(10)),'') 
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
		
			SELECT @OLDSKILL_NAME  =ISNULL(SKILL_NAME,'') ,@OLDSORT_NO = Cast(Skill_Sort_ID as Varchar(10)) FROM DBO.T0040_TRAINING_SKILL_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND SKILL_ID = @SKILL_ID
			
			DELETE FROM T0040_TRAINING_SKILL_MASTER WHERE SKILL_ID= @SKILL_ID
				
			SET @OLDVALUE = 'OLD VALUE' + '#'+ 'SKILL NAME :' + @OLDSKILL_NAME + '#'+ 'SORT NO :' + @OLDSORT_NO 
		END
           
	EXEC P9999_AUDIT_TRAIL @CMP_ID,@TRAN_TYPE,'TRAINING SKILL MASTER',@OLDVALUE,@SKILL_ID,@USER_ID,@IP_ADDRESS
	RETURN




