


---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0045_INCENTIVE_DETAIL]
    @ROW_ID NUMERIC(18,0)
   ,@CMP_ID NUMERIC(18,0)
   ,@INC_TRAN_ID NUMERIC(18,0)
   ,@FROM_SLAB NUMERIC(18,2)
   ,@TO_SLAB NUMERIC(18,2)
   ,@SLAB_VALUE NUMERIC(18,2)
   ,@SLAB_TYPE TINYINT
   ,@CALC_TYPE VARCHAR(100)
   ,@CALC_ON VARCHAR(100)
   ,@INCENTIVE_NAME VARCHAR(100)
   ,@INCENTIVE_FOR VARCHAR(50)
   ,@TRAN_TYPE	Char(1)
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
 	  
 IF @TRAN_TYPE  = 'I'
	BEGIN	 
		SELECT @INC_TRAN_ID=MAX(INC_TRAN_ID) FROM dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK)
	    SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM DBO.T0045_INCENTIVE_DETAIL WITH (NOLOCK)
		SET @ROW_ID=@ROW_ID;SET @INC_TRAN_ID=@INC_TRAN_ID
		
 		IF EXISTS(SELECT 1 FROM dbo.T0040_INCENTIVE_MASTER  WITH (NOLOCK) WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID)
		BEGIN
			IF(@INC_TRAN_ID <> 0)
				BEGIN
				INSERT INTO DBO.T0045_INCENTIVE_DETAIL(ROW_ID,CMP_ID,INC_TRAN_ID,FROM_SLAB,TO_SLAB,SLAB_VALUE,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON,INCENTIVE_FOR)
					VALUES(@ROW_ID,@CMP_ID,@INC_TRAN_ID,@FROM_SLAB,@TO_SLAB,@SLAB_VALUE,@INCENTIVE_NAME,@SLAB_TYPE,@CALC_TYPE,@CALC_ON,@INCENTIVE_FOR)
				END	
		END		
 END  
 ELSE IF @TRAN_TYPE  = 'U'
	BEGIN
	
		SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM DBO.T0045_INCENTIVE_DETAIL WITH (NOLOCK)
		SET @ROW_ID=@ROW_ID;SET @INC_TRAN_ID=@INC_TRAN_ID
		
 		IF EXISTS(SELECT 1 FROM dbo.T0040_INCENTIVE_MASTER  WITH (NOLOCK) WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID)
		BEGIN
			IF(@INC_TRAN_ID <> 0)
				BEGIN
				INSERT INTO DBO.T0045_INCENTIVE_DETAIL(ROW_ID,CMP_ID,INC_TRAN_ID,FROM_SLAB,TO_SLAB,SLAB_VALUE,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON,INCENTIVE_FOR)
					VALUES(@ROW_ID,@CMP_ID,@INC_TRAN_ID,@FROM_SLAB,@TO_SLAB,@SLAB_VALUE,@INCENTIVE_NAME,@SLAB_TYPE,@CALC_TYPE,@CALC_ON,@INCENTIVE_FOR)
				END	
		END		
		
	END
 
 IF @TRAN_TYPE='E'
	 BEGIN
		SELECT ROW_ID,CMP_ID,INC_TRAN_ID,FROM_SLAB,TO_SLAB,SLAB_VALUE FROM T0045_INCENTIVE_DETAIL WITH (NOLOCK)
		WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID
		
	 END
	 

 
END




