  
  
  
---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---  
CREATE PROCEDURE [dbo].[P0040_INCENTIVE_MASTER]  
 -- Add the parameters for the stored procedure here  
 @INC_TRAN_ID NUMERIC(18,0),  
 @CMP_ID NUMERIC(18,0),  
 @INCENTIVE_NAME NVARCHAR(100),  
 @SLAB_TYPE TINYINT,  
 @CALC_TYPE VARCHAR(100),  
 @CALC_ON VARCHAR(100),  
 @INCENTIVE_FOR VARCHAR(100),  
 @SYSTEM_DATE DATETIME,  
 @LOGIN_ID INT,  
 @TRAN_TYPE Char(1)  
AS  
  
SET NOCOUNT ON   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
SET ARITHABORT ON  
  
BEGIN  
  
 -- SET NOCOUNT ON added to prevent extra result sets from  
 -- interfering with SELECT statements.  
  
      
    IF ISNULL(@CMP_ID,0)=0  
    BEGIN  
  RAISERROR('@@ Company Id must be specified @@',16,2)  
  RETURN  
    END  
      
  --  IF ISNULL(@PARAMETER_NAME,'')=''  
  --  BEGIN  
  --RAISERROR('@@ PARAMETER NAME must be specified @@',16,2)  
  --RETURN  
  --  END  
      
  --  IF ISNULL(@PARAMETER_TYPE,0)=0  
  --  BEGIN  
  --RAISERROR('@@ PARAMETER TYPE must be specified @@',16,2)  
  --RETURN  
  --  END  
  
        set @INCENTIVE_NAME = dbo.fnc_ReverseHTMLTags(@INCENTIVE_NAME)  --added by Ronak 081021  
 IF (@TRAN_TYPE='I')  
 BEGIN  
    
  IF NOT EXISTS(SELECT 1 FROM dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INCENTIVE_NAME=@INCENTIVE_NAME)  
   AND NOT EXISTS(SELECT 1 FROM dbo.T0040_PARAMETER_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_NAME=@INCENTIVE_NAME)   
   BEGIN  
   
    INSERT INTO dbo.T0040_INCENTIVE_MASTER(CMP_ID,INCENTIVE_NAME,SLAB_TYPE,CALC_TYPE,CALC_ON,INCENTIVE_FOR,LOGIN_ID,SYSTEM_DATE)  
    VALUES(@CMP_ID,@INCENTIVE_NAME,@SLAB_TYPE,@CALC_TYPE,@CALC_ON,@INCENTIVE_FOR,@LOGIN_ID,GETDATE())  
     
    SELECT @INC_TRAN_ID=MAX(INC_TRAN_ID) from dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK)  
    IF(@INC_TRAN_ID <> 0)  
    BEGIN  
     IF EXISTS(SELECT 1 FROM T0045_INCENTIVE_DETAIL WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID)  
      BEGIN  
       DELETE FROM T0045_INCENTIVE_DETAIL WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID  
      END  
       
    END  
   END  
  ELSE  
   BEGIN  
     
    RAISERROR('@@ This Incentive Name Already Exist. @@',16,2)  
    RETURN  
   END  
 END       
 ELSE IF (@TRAN_TYPE='U')  
 BEGIN  
     IF EXISTS(SELECT 1 FROM dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID)  
  BEGIN  
     
   UPDATE dbo.T0040_INCENTIVE_MASTER SET INCENTIVE_NAME=@INCENTIVE_NAME,SLAB_TYPE=@SLAB_TYPE,  
   CALC_TYPE=@CALC_TYPE,CALC_ON=@CALC_ON,INCENTIVE_FOR=@INCENTIVE_FOR,SYSTEM_DATE=GETDATE(),LOGIN_ID=@LOGIN_ID  
   WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID  
     
   IF(@INC_TRAN_ID <> 0)  
   BEGIN  
    IF EXISTS(SELECT 1 FROM T0045_INCENTIVE_DETAIL WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID)  
     BEGIN  
      DELETE FROM T0045_INCENTIVE_DETAIL WHERE INC_TRAN_ID=@INC_TRAN_ID AND CMP_ID=@CMP_ID  
    END  
   END  
  END  
 END  
   
 ELSE IF(@TRAN_TYPE='D')  
 BEGIN  
    
  IF EXISTS(SELECT 1 FROM dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID)  
  BEGIN  
   DELETE FROM T0045_INCENTIVE_DETAIL WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID  
   DELETE FROM T0040_INCENTIVE_MASTER WHERE CMP_ID=@CMP_ID AND INC_TRAN_ID=@INC_TRAN_ID  
  END  
   
 END  
 ELSE   
 BEGIN  
  SELECT INC_TRAN_ID,INCENTIVE_NAME,(CASE WHEN SLAB_TYPE = 0 THEN 'Parameter' WHEN Slab_Type = 1 THEN 'Percentage' ELSE 'NOs' END) AS SLAB_TYPE,CALC_TYPE,CALC_ON,INCENTIVE_FOR  
   FROM dbo.T0040_INCENTIVE_MASTER WITH (NOLOCK)  
   WHERE CMP_ID=@CMP_ID AND INCENTIVE_FOR=@INCENTIVE_FOR  
 END  
      
END  
  
  