  
  
  
---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---  
CREATE PROCEDURE [dbo].[P0040_PARAMETER_MASTER]  
 -- Add the parameters for the stored procedure here  
 @Para_Id NUMERIC(18,0) OUTPUT,  
 @Cmp_Id NUMERIC(18,0),  
 @Para_Name VARCHAR(100),  
 @Para_For Varchar(100),  
 @Login_Id NUMERIC(18,0),  
 @SYSTEM_DATE DATETIME,  
 @TRAN_TYPE CHAR(1)  
AS  
  
SET NOCOUNT ON   
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
SET ARITHABORT ON  
  
BEGIN  
 -- SET NOCOUNT ON added to prevent extra result sets from  
 -- interfering with SELECT statements.  
      
    IF ISNULL(@CMP_ID,0)=0  
    BEGIN  
  RAISERROR('@@ Company Id must be specified @@',16,2)  
  RETURN  
    END  
      
  --  IF ISNULL(@PARAMETER_NAME,'')=''  
  --  BEGIN  
  --RAISERROR('@@ PARAMETER NAME must be specified @@',16,2)  
  --RETURN  
  --  END  
      
  --  IF ISNULL(@PARAMETER_TYPE,0)=0  
  --  BEGIN  
  --RAISERROR('@@ PARAMETER TYPE must be specified @@',16,2)  
  --RETURN  
  --  END  
  
       set @PARA_NAME = dbo.fnc_ReverseHTMLTags(@PARA_NAME)  --added by Ronak 081021   
 IF (@TRAN_TYPE='I')  
 BEGIN  
   
  IF NOT EXISTS(SELECT 1 FROM T0040_PARAMETER_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_NAME=@PARA_NAME)  
   AND NOT EXISTS(SELECT 1 FROM T0040_INCENTIVE_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND INCENTIVE_NAME=@PARA_NAME)  
   BEGIN  
     
    INSERT INTO T0040_PARAMETER_MASTER(CMP_ID,PARA_NAME,PARA_FOR,LOGIN_ID,SYSTEM_DATE)  
    VALUES(@CMP_ID,@PARA_NAME,@PARA_FOR,@LOGIN_ID,GETDATE())  
     
    SELECT @PARA_ID=MAX(PARA_ID) from T0040_PARAMETER_MASTER WITH (NOLOCK)  
    IF(@PARA_ID<>0)  
    BEGIN  
     IF EXISTS(SELECT 1 FROM T0045_PARAMETER_DETAIL WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_ID=@PARA_ID)  
     BEGIN  
      DELETE FROM T0045_PARAMETER_DETAIL WHERE PARA_ID=@PARA_ID AND CMP_ID=@CMP_ID  
     END  
    END  
     
   END  
  ELSE   
   BEGIN  
     
    RAISERROR('@@ This Parameter Name Already Exist. @@',16,2)  
    RETURN  
      
   END  
 END  
 ELSE IF (@TRAN_TYPE='U')  
 BEGIN  
      
     IF EXISTS(SELECT 1 FROM T0040_PARAMETER_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_ID=@PARA_ID)  
  BEGIN  
     
   UPDATE T0040_PARAMETER_MASTER SET PARA_NAME=@PARA_NAME,PARA_FOR=@PARA_FOR,LOGIN_ID=@LOGIN_ID  
   ,SYSTEM_DATE=GETDATE() WHERE PARA_ID=@PARA_ID AND CMP_ID=@CMP_ID  
     
     
   IF(@PARA_ID <> 0)  
    BEGIN  
     IF EXISTS(SELECT 1 FROM T0045_PARAMETER_DETAIL WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_ID=@PARA_ID)  
     BEGIN  
      DELETE FROM T0045_PARAMETER_DETAIL WHERE PARA_ID=@PARA_ID AND CMP_ID=@CMP_ID  
     END  
    END  
      
  END  
 END   
 ELSE IF(@TRAN_TYPE='D')  
 BEGIN  
    
  IF EXISTS(SELECT 1 FROM T0040_PARAMETER_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND PARA_ID=@PARA_ID)  
  BEGIN  
   DELETE FROM T0040_PARAMETER_MASTER WHERE CMP_ID=@CMP_ID AND PARA_ID=@PARA_ID  
  END  
 END  
 ELSE IF(@TRAN_TYPE='S')  
 BEGIN  
      
   DECLARE @PARAVAL NVARCHAR(100)  
   SET @PARAVAL=REPLACE(@PARA_NAME,'#',',')  
   select * from dbo.Split(@PARAVAL, ',') t inner join T0040_PARAMETER_MASTER p WITH (NOLOCK) on cast(t.Data as numeric) = p.PARA_ID  
   ---SELECT PARA_ID,PARA_NAME FROM #PARA_TABLE WHERE CMP_ID=149 AND PARA_ID in (@PARAVAL)  
    
    
 END  
 ELSE IF (@TRAN_TYPE='F')  
 BEGIN  
    
  SELECT FIELD_NAME   
  FROM dbo.T0040_INCENTIVE_FORMULA_FIELDS WITH (NOLOCK) WHERE CMP_ID=@CMP_ID   
    
 END  
 ELSE  
 BEGIN  
  SELECT PARA_ID,CMP_ID,PARA_NAME,PARA_FOR  
   FROM T0040_PARAMETER_MASTER WITH (NOLOCK) WHERE CMP_ID=@CMP_ID and PARA_FOR=@PARA_FOR  
 END  
   
      
END  
  
  