

-- =============================================
-- Author:		Nilesh Patel
-- Create date: 20-12-2017
-- Description:	Ticket Priority 
---18/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0040_TICKET_PRIORITY]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@TRAN_ID NUMERIC OUTPUT,
	@CMP_ID NUMERIC,
	@PRIORITY_NAME VARCHAR(500),
	@HOURS_LIMIT VARCHAR(20),
	@USER_ID NUMERIC(18,0),
	@TRAN_TYPE CHAR(1)
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	
	IF @TRAN_TYPE = 'I'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_TICKET_PRIORITY WITH (NOLOCK) WHERE UPPER(PRIORITY_NAME) = UPPER(@PRIORITY_NAME) AND CMP_ID = @CMP_ID)
				BEGIN
					RAISERROR('@@Same Ticket Priority exists.@@.',16,2)
					RETURN
				END
				
			SELECT @TRAN_ID = ISNULL(MAX(TRAN_ID),0) + 1 FROM T0040_TICKET_PRIORITY WITH (NOLOCK) 
			
			INSERT INTO T0040_TICKET_PRIORITY(TRAN_ID,CMP_ID,PRIORITY_NAME,Hours_Limit,UserID,Modify_Date)
				VALUES(@TRAN_ID,@CMP_ID,@PRIORITY_NAME,@HOURS_LIMIT,@USER_ID,GETDATE()) 
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
			--Declare @TICKET_TYPE_ID Numeric
			--Select @TICKET_TYPE_ID = Tran_ID FROM T0040_TICKET_PRIORITY WHERE TRAN_ID = @TRAN_ID AND CMP_ID = @CMP_ID
			
			--IF EXISTS(SELECT 1 FROM T0090_TICKET_APPLICATION WHERE TICKET_TYPE_ID = @TICKET_TYPE_ID AND CMP_ID = @CMP_ID)
			IF EXISTS(SELECT 1 FROM T0090_TICKET_APPLICATION WITH (NOLOCK) WHERE Ticket_Priority = @TRAN_ID AND CMP_ID = @CMP_ID)  --Added by Jaina 01-06-2020
				BEGIN					
					RAISERROR('@@Refrence Is Exists So You Can''t Delete it.@@.',16,2)
					RETURN
				END
			DELETE FROM T0040_TICKET_PRIORITY WHERE TRAN_ID = @TRAN_ID AND CMP_ID = @CMP_ID
		END
	ELSE IF @TRAN_TYPE = 'U'
		BEGIN
			IF EXISTS(SELECT 1 FROM T0040_TICKET_PRIORITY WITH (NOLOCK) WHERE UPPER(PRIORITY_NAME) = UPPER(@PRIORITY_NAME) AND CMP_ID = @CMP_ID AND TRAN_ID <> @TRAN_ID )
				BEGIN
					RAISERROR('@@Same Ticket Priority exists.@@.',16,2)
					RETURN
				END
			UPDATE T0040_TICKET_PRIORITY 
				SET 
					PRIORITY_NAME = @PRIORITY_NAME,
					HOURS_LIMIT = @HOURS_LIMIT,
					Modify_Date = GETDATE(),
					USERID = @USER_ID
				WHERE TRAN_ID = @TRAN_ID AND CMP_ID = @CMP_ID
		END
    
END
