

---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0040_ROLE_MASTER]
	@ROLE_ID AS NUMERIC OUTPUT,
	@ROLE_NAME AS VARCHAR(50),
	@CMP_ID AS NUMERIC,
	@TRAN_TYPE VARCHAR(1),
	@USER_ID NUMERIC(18,0) = 0,
	@IP_ADDRESS VARCHAR(30)= '' 
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON


DECLARE @OLDVALUE AS  VARCHAR(MAX)

DECLARE @OLDROLE_NAME AS VARCHAR(50)
SET @OLDROLE_NAME =''


	IF @TRAN_TYPE  = 'I'
		BEGIN
				 IF EXISTS(SELECT 1 FROM T0040_ROLE_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND UPPER(ROLE_NAME) = UPPER(@ROLE_NAME)) 
					BEGIN   
						SET @ROLE_ID = 0
						RETURN 
					END
		         
				  IF @ROLE_NAME  <> ''
					BEGIN 
						SELECT @ROLE_ID= ISNULL(MAX(ROLE_ID),0) + 1 FROM T0040_ROLE_MASTER WITH (NOLOCK) 

						INSERT INTO T0040_ROLE_MASTER
											  (ROLE_ID, CMP_ID, ROLE_NAME,MODIFY_DATE,MODIFY_BY,IP_ADDRESS)
						VALUES     (@ROLE_ID, @CMP_ID,@ROLE_NAME,GETDATE(),@USER_ID,@IP_ADDRESS)
				
				   END
				   		
				SET @OLDVALUE = 'NEW VALUE' + '#'+ 'ROLE NAME :' +ISNULL( @ROLE_NAME,'') + '#'
		END
	ELSE IF @TRAN_TYPE = 'U'
		BEGIN
				IF EXISTS(SELECT 1 FROM T0040_ROLE_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND ROLE_ID <> @ROLE_ID AND UPPER(ROLE_NAME) = UPPER(@ROLE_NAME))
					BEGIN
						SET @ROLE_ID = 0
						RETURN 
					END
					
                 SELECT @OLDROLE_NAME  =ISNULL(ROLE_NAME,'') FROM DBO.T0040_ROLE_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND ROLE_ID = @ROLE_ID
          
				UPDATE T0040_ROLE_MASTER
					SET ROLE_NAME = @ROLE_NAME	    
				WHERE ROLE_ID = @ROLE_ID
				
				SET @OLDVALUE = 'OLD VALUE' + '#'+ 'ROLE NAME :' + @OLDROLE_NAME + 'NEW VALUE' + '#'+ 'ROLENAME :' +ISNULL( @ROLE_NAME,'') 
		END
	ELSE IF @TRAN_TYPE = 'D'
		BEGIN
		
			SELECT @OLDROLE_NAME  =ISNULL(ROLE_NAME,'') FROM DBO.T0040_ROLE_MASTER WITH (NOLOCK) WHERE CMP_ID = @CMP_ID AND ROLE_ID = @ROLE_ID
			
			DELETE FROM T0040_ROLE_MASTER WHERE ROLE_ID= @ROLE_ID
				
			SET @OLDVALUE = 'OLD VALUE' + '#'+ 'ROLE NAME :' + @OLDROLE_NAME 
		END
           
	EXEC P9999_AUDIT_TRAIL @CMP_ID,@TRAN_TYPE,'ROLE MASTER',@OLDVALUE,@ROLE_ID,@USER_ID,@IP_ADDRESS
	RETURN




