


---30/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0050_PRIVILEGE_CHECK_RIGHTS]
	
	@Privilege_ID AS numeric,
	@CMP_ID AS numeric,
	@Form_Name as nvarchar(50),
	@Is_Ess_Form as tinyint = 0,
	@For_Employee AS tinyint = 0   --Added By Jaina 06-09-2016
AS	

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	
	if @Is_Ess_Form = 0
		begin		
		
			if @For_Employee = 1  --Added By Jaina 06-09-2016
				Begin
					SELECT PD.*,DF.FORM_NAME FROM T0050_PRIVILEGE_DETAILS PD WITH (NOLOCK) 
					INNER JOIN T0000_DEFAULT_FORM DF WITH (NOLOCK) ON  DF.FORM_ID = PD.FORM_ID
					WHERE PD.PRIVILAGE_ID = @PRIVILEGE_ID AND DF.FORM_NAME = @FORM_NAME 
					--AND DF.FORM_ID > 6000 AND DF.FORM_ID < 7000 
					  AND DF.Page_Flag in ('AP','AR','HP','IP','DA')
				End
			Else
				BEGIN
					SELECT PD.*,DF.FORM_NAME FROM T0050_PRIVILEGE_DETAILS PD WITH (NOLOCK)
					INNER JOIN T0000_DEFAULT_FORM DF WITH (NOLOCK) ON  DF.FORM_ID = PD.FORM_ID
					WHERE PD.PRIVILAGE_ID = @PRIVILEGE_ID AND DF.FORM_NAME = @FORM_NAME
					--AND DF.FORM_ID > 6000 AND DF.FORM_ID < 7000 
					--Ronakb160124 add flag
					AND DF.Page_Flag in ('AP','AR','HP','IP','DA','EP')
				    AND isnull(DF.Form_url,'home.aspx') <> 'home.aspx'
				END
		end
	else
		begin			
			SELECT PD.*,DF.FORM_NAME FROM T0050_PRIVILEGE_DETAILS PD WITH (NOLOCK)
			INNER JOIN T0000_DEFAULT_FORM DF WITH (NOLOCK) ON  DF.FORM_ID = PD.FORM_ID
			WHERE PD.PRIVILAGE_ID = @PRIVILEGE_ID AND DF.FORM_NAME = @FORM_NAME 
			--AND DF.FORM_ID > 7000
			AND DF.Page_Flag in ('ER','DA','EP','DE')
		end

	RETURN
