


---22/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0050_Bind_Emp_Hierarchy_DDL]
	@CmpID NUMERIC(18,0)
	, @EmpID NUMERIC(18,0)
	, @TransType CHAR(1) = 'A'
	
AS 
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	IF @TransType = 'A'
		BEGIN
			;WITH Q(CMP_ID,EMP_ID, R_EMP_ID, R_LEVEL,Alpha_Emp_Code,Emp_Full_NAME) AS
					(
					SELECT	EM.CMP_ID,EM.Emp_ID,CAST(0 AS NUMERIC) as R_Emp_ID, CAST(1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name
					FROM T0080_EMP_MASTER EM WITH (NOLOCK) --ON EM.Emp_ID = RD.Emp_ID
					WHERE	EM.Emp_ID = @EmpID AND(EM.Emp_Left_Date IS NULL or EM.Emp_Left <> 'Y')
					
					UNION ALL
					
					SELECT	RD.CMP_ID,RD.Emp_ID,RD.R_Emp_ID, CAST(Q.R_LEVEL + 1 AS NUMERIC) AS R_LEVEL,EM.Alpha_Emp_Code,EM.Emp_Full_Name
					FROM T0090_EMP_REPORTING_DETAIL RD WITH (NOLOCK)
					INNER JOIN V0090_EMP_REP_DETAIL_MAX EMP_SUP ON RD.EMP_ID = EMP_SUP.EMP_ID AND RD.EFFECT_DATE = EMP_SUP.EFFECT_DATE AND RD.Row_ID = EMP_SUP.Row_ID
					INNER JOIN Q ON RD.R_Emp_ID=Q.Emp_ID	
					INNER JOIN T0080_EMP_MASTER EM WITH (NOLOCK) ON EM.Emp_ID = RD.Emp_ID
				)
							
			SELECT EMP_ID,Alpha_Emp_Code + ' - ' + Emp_Full_NAME AS 'Employee' FROM Q
			ORDER BY Alpha_Emp_Code,Emp_Full_NAME
		END
END


