

---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0055_INCENTIVE_SCHEME_PARA]
    @SCHEME_ID NUMERIC(18,0) 
   --,@ROW_ID NUMERIC(18,0)
   ,@PARA_ID NUMERIC(18,0)
   ,@PARA_NAME	VARCHAR(MAX)
   ,@FROM_SLAB NUMERIC(18,2)
   ,@TO_SLAB NUMERIC(18,2)
   ,@SLAB_VALUE NUMERIC(18,2)
   ,@FORMULA NVARCHAR(MAX)
   ,@PARA_FOR VARCHAR(50) --ADDED ON 31012018
   ,@TRAN_TYPE	Char(1)
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
  
 	DECLARE @ROW_ID NUMERIC(18,0)
 IF @TRAN_TYPE  = 'I'
	BEGIN	 

	
		IF EXISTS(SELECT 1 FROM dbo.T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK) WHERE SCHEME_ID=@SCHEME_ID)
			BEGIN
				IF @SCHEME_ID <> 0
					BEGIN
						SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK)
						INSERT INTO dbo.T0055_INCENTIVE_SCHEME_PARA(SCHEME_ID,ROW_ID,PARA_ID,PARA_NAME,FROM_SLAB,TO_SLAB,SLAB_VALUE,P_FORMULA,PARA_FOR)
						VALUES(@SCHEME_ID,@ROW_ID,@PARA_ID,@PARA_NAME,@FROM_SLAB,@TO_SLAB,@SLAB_VALUE,@FORMULA,@PARA_FOR) 
					END
			END 
		ELSE
			BEGIN 	
				
				IF EXISTS(SELECT 1 FROM DBO.T0050_INCENTIVE_SCHEME WITH (NOLOCK) WHERE SCHEME_ID=@SCHEME_ID) --ADDED ON 14022018 FOR PARAMETER ADD IN OTHER SCHEME ID 
					BEGIN 
					
						IF NOT EXISTS(SELECT 1 FROM dbo.T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK) WHERE SCHEME_ID=@SCHEME_ID AND PARA_FOR=@PARA_FOR AND PARA_NAME=@PARA_NAME)
							BEGIN
							
								IF NOT EXISTS(SELECT 1 FROM dbo.T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK) WHERE INCENTIVE_NAME=@PARA_NAME) -- CHECK PARA NAME SHOULD NOT DUPLICATE RESTRICTION
									BEGIN	
										SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK)
										INSERT INTO dbo.T0055_INCENTIVE_SCHEME_PARA(SCHEME_ID,ROW_ID,PARA_ID,PARA_NAME,FROM_SLAB,TO_SLAB,SLAB_VALUE,P_FORMULA,PARA_FOR)
										VALUES(@SCHEME_ID,@ROW_ID,@PARA_ID,@PARA_NAME,@FROM_SLAB,@TO_SLAB,@SLAB_VALUE,@FORMULA,@PARA_FOR) 
									END
								ELSE
									BEGIN
										RAISERROR('@@ Invalid Parameter ! This Parameter Name Already Exist In Incentive. @@',16,2)
										RETURN
									END
							END
					END
				ELSE
				BEGIN
						SELECT @SCHEME_ID= MAX(SCHEME_ID) FROM dbo.T0050_INCENTIVE_SCHEME WITH (NOLOCK)
						SET @SCHEME_ID=@SCHEME_ID
						
						IF NOT EXISTS(SELECT 1 FROM dbo.T0055_INCENTIVE_SCHEME_INC WITH (NOLOCK) WHERE SCHEME_ID=@SCHEME_ID AND INCENTIVE_NAME=@PARA_NAME AND INCENTIVE_FOR=@PARA_FOR) -- CHECK PARA NAME SHOULD NOT DUPLICATE RESTRICTION
							BEGIN	
								IF @SCHEME_ID <> 0
									BEGIN
										SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_PARA WITH (NOLOCK)
										INSERT INTO dbo.T0055_INCENTIVE_SCHEME_PARA(SCHEME_ID,ROW_ID,PARA_ID,PARA_NAME,FROM_SLAB,TO_SLAB,SLAB_VALUE,P_FORMULA,PARA_FOR)
										VALUES(@SCHEME_ID,@ROW_ID,@PARA_ID,@PARA_NAME,@FROM_SLAB,@TO_SLAB,@SLAB_VALUE,@FORMULA,@PARA_FOR) 
									END
							END			
						ELSE
						
							RAISERROR('@@ Invalid Parameter ! This Parameter Name Already Exist In Incentive. @@',16,2)
							RETURN
							
						END
				END
			END
 	
END
