


CREATE PROCEDURE [dbo].[P0050_INCENTIVE_SCHEME]
    @SCHEME_ID NUMERIC(18,0) OUTPUT
   ,@CMP_ID NUMERIC(18,0)
   ,@EFFECTIVE_DATE DATETIME
   ,@LOGIN_ID	NUMERIC(18,0)
   ,@DESIG_ID VARCHAR(MAX)
   ,@BRANCH_ID VARCHAR(MAX)
   ,@SYSTEM_DATE DATETIME
   ,@TRAN_TYPE	Char(1)
AS

        SET NOCOUNT ON 
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
		SET ARITHABORT ON

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	
	--IF(@FOR_DATE='1900-01-01')
	--	SET @FOR_DATE=NULL	
		
			
	IF ISNULL(@CMP_ID,0) = 0
		BEGIN 
			RAISERROR('@@ Company ID must be specified @@',16,2) 
			RETURN
		END
		
	--IF (ISNULL(@BRANCH_ID,0) = 0 AND ISNULL(@DESIG_ID,0)=0)
	--	BEGIN 
	--		RAISERROR('@@ Atleast One Branch OR Designation must be specified @@',16,2) 
	--		RETURN
	--	END
	--ELSE IF NOT EXISTS(SELECT 1 FROM T0030_BRANCH_MASTER WHERE Cmp_ID=@CMP_ID AND Branch_ID = @BRANCH_ID)
	--	BEGIN 
	--		RAISERROR('@@ Branch does not exist in selected company @@',16,2) 
	--		RETURN
	--	END
	IF (IsNull(@EFFECTIVE_DATE,'1900-01-01') ='1900-01-01' )  	
		BEGIN
			RAISERROR('@@ For Date must be specified  @@',16,2)  		
			RETURN
		END
			
			
 IF @TRAN_TYPE  = 'I' OR @TRAN_TYPE  = 'U'
	BEGIN		
	
		DECLARE @ROW_ID NUMERIC(18,0)
		IF EXISTS(SELECT 1 FROM DBO.T0050_INCENTIVE_SCHEME WITH (NOLOCK) WHERE EFFECTIVE_DATE=@EFFECTIVE_DATE AND CMP_ID=@CMP_ID AND SCHEME_ID=@SCHEME_ID)
			BEGIN
				
				UPDATE dbo.T0050_INCENTIVE_SCHEME SET LOGIN_ID=@LOGIN_ID,SYSTEM_DATE=GETDATE(),BRANCH_ID=@BRANCH_ID,DESIG_ID=@DESIG_ID WHERE 
				SCHEME_ID=@SCHEME_ID AND EFFECTIVE_DATE=@EFFECTIVE_DATE AND CMP_ID=@CMP_ID
				
				DELETE FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WHERE  SCHEME_ID=@SCHEME_ID
				DELETE FROM dbo.T0055_INCENTIVE_SCHEME_PARA WHERE  SCHEME_ID=@SCHEME_ID
				DELETE FROM dbo.T0055_INCENTIVE_SCHEME_INC WHERE  SCHEME_ID=@SCHEME_ID
				
				SELECT	@ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WITH (NOLOCK)
				INSERT	INTO dbo.T0055_INCENTIVE_SCHEME_DETAIL(SCHEME_ID,ROW_ID,DESIG_ID)
				SELECT	@SCHEME_ID, @ROW_ID + ROW_NUMBER() OVER(ORDER BY ID) AS ROW_ID, CAST(DATA AS NUMERIC)
				FROM	dbo.Split(@DESIG_ID, '#') T 
				WHERE	T.Data <> ''
				
				SELECT	@ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WITH (NOLOCK)
				INSERT	INTO dbo.T0055_INCENTIVE_SCHEME_DETAIL(SCHEME_ID,ROW_ID,Branch_ID)
				SELECT	@SCHEME_ID, @ROW_ID + ROW_NUMBER() OVER(ORDER BY ID) AS ROW_ID, CAST(DATA AS NUMERIC)
				FROM	dbo.Split(@BRANCH_ID, '#') T 
				WHERE	T.Data <> ''
				--VALUES(@SCHEME_ID,@ROW_ID,@DESIG_ID,@BRANCH_ID)
				
			END	
		ELSE 
			BEGIN
				--SELECT @SCHEME_ID = ISNULL(MAX(SCHEME_ID),0) + 1  FROM dbo.T0050_SCHEME
			    INSERT INTO dbo.T0050_INCENTIVE_SCHEME(CMP_ID,EFFECTIVE_DATE,LOGIN_ID,BRANCH_ID,DESIG_ID,SYSTEM_DATE)
				VALUES(@CMP_ID,@EFFECTIVE_DATE,@LOGIN_ID,@BRANCH_ID,@DESIG_ID,GETDATE())
				
				SELECT @SCHEME_ID=SCHEME_ID FROM dbo.T0050_INCENTIVE_SCHEME WITH (NOLOCK)
				
				DELETE FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WHERE  SCHEME_ID=@SCHEME_ID
				SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WITH (NOLOCK)
				
				
				INSERT	INTO dbo.T0055_INCENTIVE_SCHEME_DETAIL(SCHEME_ID,ROW_ID,DESIG_ID)
				SELECT	@SCHEME_ID, @ROW_ID + ROW_NUMBER() OVER(ORDER BY ID) AS ROW_ID, CAST(DATA AS NUMERIC)
				FROM	dbo.Split(@DESIG_ID, '#') T 
				WHERE	T.Data <> ''
				
				SELECT	@ROW_ID = ISNULL(MAX(ROW_ID),0) + 1  FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WITH (NOLOCK)
				INSERT	INTO dbo.T0055_INCENTIVE_SCHEME_DETAIL(SCHEME_ID,ROW_ID,Branch_ID)
				SELECT	@SCHEME_ID, @ROW_ID + ROW_NUMBER() OVER(ORDER BY ID) AS ROW_ID, CAST(DATA AS NUMERIC)
				FROM	dbo.Split(@BRANCH_ID, '#') T 
				WHERE	T.Data <> ''
			
				--INSERT INTO dbo.T0055_INCENTIVE_SCHEME_DETAIL(SCHEME_ID,ROW_ID,DESIG_ID,BRANCH_ID)VALUES(@SCHEME_ID,@ROW_ID,@DESIG_ID,@BRANCH_ID)
				
			END
	END 
 ELSE IF @TRAN_TYPE='D'
 BEGIN
	IF EXISTS(SELECT 1 FROM dbo.T0050_INCENTIVE_SCHEME WITH (NOLOCK) WHERE SCHEME_ID=@SCHEME_ID AND CMP_ID=@CMP_ID)
		BEGIN
			DELETE FROM dbo.T0055_INCENTIVE_SCHEME_PARA WHERE  SCHEME_ID=@SCHEME_ID
			DELETE FROM dbo.T0055_INCENTIVE_SCHEME_INC WHERE  SCHEME_ID=@SCHEME_ID
			DELETE FROM dbo.T0055_INCENTIVE_SCHEME_DETAIL WHERE  SCHEME_ID=@SCHEME_ID
			DELETE FROM dbo.T0050_INCENTIVE_SCHEME WHERE  SCHEME_ID=@SCHEME_ID
		END
		
 END
 ELSE 
	BEGIN
		IF EXISTS(SELECT 1 FROM dbo.T0050_INCENTIVE_SCHEME WITH (NOLOCK))
			BEGIN
			
			SELECT * FROM T0050_INCENTIVE_SCHEME WITH (NOLOCK)
			--	SELECT SCHE.SCHEME_ID,CONVERT(VARCHAR(10),SCHE.EFFECTIVE_DATE,103) AS EFFECTIVE_DATE,BRCH.BRANCH_NAME FROM T0050_SCHEME AS SCHE
			--	INNER JOIN T0030_BRANCH_MASTER AS BRCH ON BRCH.Branch_ID=INC.BRANCH_ID WHERE INC.CMP_ID=@CMP_ID AND INC.BRANCH_ID=@BRANCH_ID
			END
	END
 
END




