

---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0050_INCENTIVE_CALCULATE_PARAMETER_VALUES]
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
	
	CREATE TABLE #RESULT(PARA_NAME VARCHAR(500))
				
	DECLARE @BRANCH_ID AS  NUMERIC(18,0)
	DECLARE @DESIG_ID AS NUMERIC(18,0)
	DECLARE @SCHEME_ID AS NUMERIC(18,0)
	DECLARE @EMP_ID AS NUMERIC(18,0)
	DECLARE @CMP_ID AS NUMERIC(18,0)
	DECLARE @LOGIN_ID AS NUMERIC(18,0)
	DECLARE @FOR_DATE AS DATETIME
	
	DECLARE @EMP_CODE AS NVARCHAR(100) -- ADDED ON 05022018 AFTER IMPLEMENT DEDUCTION WORK
	DECLARE @Log_Status int  = 0 
	DECLARE @Row_No as Int = 0 
	DECLARE @GUID Varchar(256) = ''
	DECLARE @W_ERROR VARCHAR(MAX) 

	SELECT	@EMP_ID=EMP_ID,@CMP_ID=CMP_ID,@BRANCH_ID=BRANCH_ID,@DESIG_ID=DESIG_ID,@LOGIN_ID=LOGIN_ID,@EMP_CODE=EMP_CODE,@Row_No=ROW_NO,@GUID=GUID,
			--			@FOR_DATE=DATEADD(d, -1, DATEADD(m, DATEDIFF(m, 0, FOR_DATE) + 1, 0)) -- ADDED ON  DATEADD(d, -1, DATEADD(m, DATEDIFF(m, 0, FOR_DATE) + 1, 0)) 03012018 DUE TO T0050_INCENTIVE_SCHEME EFFECTIVE DATE IS 14042017 AND FOR_DATE TAKE 01042017 SCHEME ID NOT GET
			@FOR_DATE = For_Date
	FROM	#XML
	
	
	
	SELECT 	TOP 1 @SCHEME_ID=S.SCHEME_ID
	FROM	T0050_INCENTIVE_SCHEME S WITH (NOLOCK)			
	WHERE	EXISTS(SELECT 1 FROM T0055_INCENTIVE_SCHEME_DETAIL SD WITH (NOLOCK) WHERE S.SCHEME_ID=SD.SCHEME_ID AND SD.BRANCH_ID=@BRANCH_ID)
			AND EXISTS(SELECT 1 FROM T0055_INCENTIVE_SCHEME_DETAIL SD WITH (NOLOCK) WHERE S.SCHEME_ID=SD.SCHEME_ID AND SD.DESIG_ID=@DESIG_ID)
			AND EFFECTIVE_DATE <= @FOR_DATE 
			AND EFFECTIVE_DATE <= @FOR_DATE 
			
	ORDER BY EFFECTIVE_DATE DESC

	
	SELECT	LTRIM(replace(colName, 'FM','')) As colName, colValue 
	INTO	#FORMULA_VALUE
	FROM	#XML	
	WHERE	ISNUMERIC(COLVALUE)=1
	
	DECLARE @PARA_ID AS NUMERIC(18,0)
	DECLARE @PARA_NAME AS VARCHAR(128)
	DECLARE @SCH_ID AS NUMERIC(18,0)
	DECLARE @FORMULA AS VARCHAR(MAX)
	DECLARE @RESULT AS NUMERIC(18,2)
	DECLARE @SQL NVARCHAR(MAX)	
	DECLARE @ACTUAL_FORMULA NVARCHAR(MAX)
	IF (@SCHEME_ID <> 0)
		BEGIN
				
		DECLARE CURFORMULA CURSOR FAST_FORWARD FOR                    
		SELECT	DISTINCT PARA_ID,PARA_NAME,SCHEME_ID,P_FORMULA
		FROM	DBO.T0055_INCENTIVE_SCHEME_PARA IE WITH (NOLOCK)
		WHERE	SCHEME_ID=@SCHEME_ID AND P_FORMULA <> ''
		ORDER BY SCHEME_ID
		OPEN CURFORMULA
		FETCH NEXT FROM CURFORMULA INTO  @PARA_ID,@PARA_NAME,@SCH_ID,@FORMULA
		WHILE @@FETCH_STATUS = 0                    
		BEGIN                    
			
			
			IF(@FORMULA <> '')
			
				BEGIN
					SET @ACTUAL_FORMULA=@FORMULA
					
					IF EXISTS(SELECT 1 FROM T0190_EMP_INCENTIVE_IMPORT WITH (NOLOCK) WHERE Emp_ID=@EMP_ID AND Cmp_ID=@CMP_ID AND For_Date = @FOR_DATE AND Para_Name=@PARA_NAME) -- ADDED ON 05022018 DUPLICATE ROW WAS FOR FORMULA BASED 
						BEGIN
							IF EXISTS(SELECT 1 FROM T0220_INCENTIVE_PROCESS WITH (NOLOCK) WHERE Emp_ID=@EMP_ID AND Cmp_ID=@CMP_ID AND For_Date=@FOR_DATE)
								BEGIN
									SET @w_error = 'Incentive Process Exists ' + ' Emp_Code='+@EMP_CODE
									INSERT INTO dbo.t0080_import_log 
									VALUES	(@ROW_NO,@CMP_ID,@EMP_CODE,@w_error,@EMP_CODE, 
											@w_error,Getdate(),'INCENTIVE IMPORT',@GUID) 
											
									RAISERROR(@w_error,16,2) 
									SET @LOG_STATUS=-1 
								END
							ELSE
								DELETE FROM T0190_EMP_INCENTIVE_IMPORT WHERE Emp_ID=@EMP_ID AND Cmp_ID=@CMP_ID AND For_Date = @FOR_DATE AND Para_Name=@PARA_NAME
						END
					
					
					--SELECT ID, SUBSTRING(DATA, CHARINDEX('{',DATA)+1, LEN(DATA)) AS FIELD_NAME
					--FROM DBO.SPLIT(@FORMULA, '}') WHERE CHARINDEX('{', DATA) > 0															
					SELECT @FORMULA = REPLACE(@FORMULA, '{' + colName + '}',  colValue) FROM #FORMULA_VALUE
					
					
					SET @SQL ='SELECT  @cnt = ' + @FORMULA +''
					
					EXECUTE sp_executesql @SQL, N'@cnt NUMERIC(18,2) OUTPUT', @cnt = @RESULT OUTPUT
			
					
					INSERT INTO DBO.T0190_EMP_INCENTIVE_IMPORT 
								(EMP_ID, 
								 CMP_ID, 
								 BRANCH_ID, 
								 DESIG_ID, 
								 PARA_NAME, 
								 PARA_VALUE, 
								 PARA_TYPE, 
								 PARA_ID, 
								 FOR_DATE, 
								 LOGIN_ID, 
								 SYSTEM_DATE,
								 FORMULA) 
					VALUES      ( @EMP_ID, 
								  @CMP_ID, 
								  @BRANCH_ID, 
								  @DESIG_ID, 
								  @PARA_NAME, 
								  CAST(@RESULT AS NUMERIC(18, 2)), 
								  'PM', 
								  @PARA_ID, 
								  @FOR_DATE, 
								  @LOGIN_ID, 
								  GETDATE(),
								  @ACTUAL_FORMULA) 
								  
					END
				
			
			FETCH NEXT FROM CURFORMULA INTO  @PARA_ID,@PARA_NAME,@SCH_ID,@FORMULA
	    END                    
		CLOSE CURFORMULA                    
		DEALLOCATE CURFORMULA
			
		END
	
		
	
END




