

---27/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0060_EMP_MASTER_APP_Copy_Approve_Data]
	-- Add the parameters for the stored procedure here
	 @Emp_Tran_ID bigint output,
	 @Approve_By_Emp_ID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

    -- Insert statements for procedure here
	
	Declare @Rpt_Level int=1

	IF EXISTS(SELECT 1 FROM  T0060_EMP_MASTER_APP WITH (NOLOCK) WHERE Emp_Tran_ID = @Emp_Tran_ID)
	Begin
	
			--select Old Report level for update after insert new entry
			set @Rpt_Level =(SELECT Rpt_Level FROM  T0060_EMP_MASTER_APP WITH (NOLOCK) WHERE Emp_Tran_ID = @Emp_Tran_ID)
	
			SELECT * INTO #T0060_EMP_MASTER_APP_INSERTED FROM T0060_EMP_MASTER_APP WITH (NOLOCK) WHERE Emp_Tran_ID=@Emp_Tran_ID
			
			Set @Emp_Tran_ID=(SELECT Max(Emp_Tran_ID) FROM T0060_EMP_MASTER_APP WITH (NOLOCK)) + 1
			
			SELECT @Emp_Tran_ID = Max(Emp_Tran_ID) FROM T0060_EMP_MASTER_APP WITH (NOLOCK)
			SET @Emp_Tran_ID =  IsNull(@Emp_Tran_ID,0) + 1
			
			
			
			UPDATE	#T0060_EMP_MASTER_APP_INSERTED 
			SET		Emp_Tran_ID=@Emp_Tran_ID,Rpt_Level = Rpt_Level + 1, 
					Approved_Emp_ID=@Approve_By_Emp_ID,Approved_Date=getdate()
			
			Insert INTO T0060_EMP_MASTER_APP SELECT * from #T0060_EMP_MASTER_APP_INSERTED
			
			----update reporting level and Approved information
			
			--    Update T0060_EMP_MASTER_APP 
			--	set Rpt_Level= @Rpt_Level, Approved_Emp_ID=@Approve_By_Emp_ID,Approved_Date=getdate()
			--	where Emp_Tran_ID = @Emp_Tran_ID
			----end update
			
			--select  * from T0065_EMP_SHIFT_DETAIL_APP
			
			DECLARE @SQL AS NVARCHAR(MAX)
			SET @SQL = 'IF EXISTS(SELECT 1 FROM  @@TABLE_NAME WHERE Emp_Tran_ID = @Emp_Tran_ID)
							Begin
								SET @Max_Tran_ID=0
								SELECT @Max_Tran_ID = Max(@@Column_Name) FROM @@TABLE_NAME
								SET @Max_Tran_ID =  IsNull(@Max_Tran_ID,0) + 1
								
								SELECT * INTO #@@TABLE_NAME FROM @@TABLE_NAME WHERE Emp_Tran_ID=@Emp_Tran_ID
								INSERT INTO @@TABLE_NAME SELECT * from #@@TABLE_NAME
							END'
				--Select * from T0075_EMP_EARN_DEDUCTION_APP
							
			CREATE TABLE #CHILD_TABLES
			(
				ID INT,
				Table_Name Varchar(256),
				Column_Name		Varchar(256)
			)
			
			INSERT INTO #CHILD_TABLES 
			SELECT 1, 'T0065_EMP_REPORTING_DETAIL_APP', 'Row_ID' UNION ALL
			SELECT 1, 'T0065_EMP_SHIFT_DETAIL_APP', 'Shift_Tran_ID' UNION ALL
			SELECT 1, 'T0065_EMP_CHILDRAN_DETAIL_APP', 'Row_ID' UNION ALL
			SELECT 1, 'T0065_EMP_CONTRACT_DETAIL_APP', 'Tran_ID' UNION ALL
			SELECT 1, 'T0065_EMP_DEPENDANT_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_DOC_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_EMERGENCY_CONTACT_DETAIL_APP', 'Row_ID' UNION ALL
			SELECT 1, 'T0065_EMP_EXPERIENCE_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_IMMIGRATION_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_LANGUAGE_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_LICENSE_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_QUALIFICATION_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_SKILL_DETAIL_APP', 'Row_ID' UNION ALL			
			SELECT 1, 'T0065_EMP_REFERENCE_DETAIL_APP', 'Reference_ID' UNION ALL			
			SELECT 1, 'T0070_WEEKOFF_ADJ_APP', 'W_Tran_ID' UNION ALL			
			SELECT 1, 'T0070_EMP_SCHEME_APP', 'Tran_ID' UNION ALL			
			SELECT 1, 'T0070_EMP_INCREMENT_APP', 'Increment_ID' UNION ALL
			SELECT 1, 'T0075_EMP_EARN_DEDUCTION_APP', 'AD_TRAN_ID'

			
			
			DECLARE @EXECUTOR NVARCHAR(MAX)
			
			
			SELECT	@EXECUTOR = COALESCE(@EXECUTOR +';', '') + REPLACE(REPLACE(@SQL, '@@Table_Name', Table_Name), '@@Column_Name', Column_Name)
			FROM	#CHILD_TABLES
			
			SET @EXECUTOR = 'DECLARE @Max_Tran_ID INT ' + @EXECUTOR
			
			--print @EXECUTOR
			--select @EXECUTOR as EXECUTOR
			EXEC sp_executesql @EXECUTOR, N'@Emp_Tran_ID  BIGINT', @Emp_Tran_ID
			
			/*
			IF EXISTS(SELECT 1 FROM  T0065_EMP_REPORTING_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
			   SELECT * INTO #T0065_EMP_REPORTING_DETAIL_APP FROM T0065_EMP_REPORTING_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM  T0065_EMP_SHIFT_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
			   SELECT * INTO #T0065_EMP_SHIFT_DETAIL_APP FROM T0065_EMP_SHIFT_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_CHILDRAN_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_CHILDRAN_DETAIL_APP FROM T0065_EMP_CHILDRAN_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_CONTRACT_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_CONTRACT_DETAIL_APP FROM T0065_EMP_CONTRACT_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_DEPENDANT_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_DEPENDANT_DETAIL_APP FROM T0065_EMP_DEPENDANT_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_DOC_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_DOC_DETAIL_APP FROM T0065_EMP_DOC_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_EMERGENCY_CONTACT_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_EMERGENCY_CONTACT_DETAIL_APP FROM T0065_EMP_EMERGENCY_CONTACT_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_EXPERIENCE_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
			    SELECT * INTO #T0065_EMP_EXPERIENCE_DETAIL_APP FROM T0065_EMP_EXPERIENCE_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_IMMIGRATION_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_IMMIGRATION_DETAIL_APP FROM T0065_EMP_IMMIGRATION_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_LANGUAGE_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_LANGUAGE_DETAIL_APP FROM T0065_EMP_LANGUAGE_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_LICENSE_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_LICENSE_DETAIL_APP FROM T0065_EMP_LICENSE_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_QUALIFICATION_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_QUALIFICATION_DETAIL_APP FROM T0065_EMP_QUALIFICATION_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_SKILL_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_SKILL_DETAIL_APP FROM T0065_EMP_SKILL_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0065_EMP_REFERENCE_DETAIL_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0065_EMP_REFERENCE_DETAIL_APP FROM T0065_EMP_REFERENCE_DETAIL_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0070_WEEKOFF_ADJ_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0070_WEEKOFF_ADJ_APP FROM T0070_WEEKOFF_ADJ_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0070_EMP_SCHEME_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0070_EMP_SCHEME_APP FROM T0070_EMP_SCHEME_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0070_EMP_INCREMENT_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0070_EMP_INCREMENT_APP FROM T0070_EMP_INCREMENT_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END
			
			IF EXISTS(SELECT 1 FROM T0075_EMP_EARN_DEDUCTION_APP WHERE Emp_Tran_ID = @Emp_Tran_ID)
			Begin
				SELECT * INTO #T0075_EMP_EARN_DEDUCTION_APP FROM T0075_EMP_EARN_DEDUCTION_APP WHERE Emp_Tran_ID=@Emp_Tran_ID
			END

			
*/		
	END 
END


