-- EXEC P0100_DELETE_TASK_ASSIGN
-- DROP PROCEDURE P0100_DELETE_TASK_ASSIGN
CREATE PROCEDURE P0100_DELETE_TASK_ASSIGN
@rMainId INT
AS
BEGIN
	DELETE FROM T0110_Task_Detail WHERE Task_Id = @rMainId
	DELETE FROM T0110_Task_Watcher WHERE Task_Id = @rMainId
	DELETE FROM T0110_Task_Images WHERE Task_Id = @rMainId
	DELETE FROM T0110_Task_Audit WHERE Task_Id = @rMainId
	DELETE FROM T0100_Task_Assign WHERE Task_Id = @rMainId
	DELETE FROM T0100_Task_Assign WHERE Task_ParentId = @rMainId
	SELECT 1 AS Res
END