
---21/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0100_EMP_COMPANY_BOND_TRANSFER]
	 @Row_ID 		Numeric output
	,@Bond_Tran_ID 	Numeric
	,@Tran_Id		Numeric
	,@Cmp_ID		Numeric
	,@Emp_ID		Numeric
	,@Bond_Id		Numeric
	,@Old_Balance   Numeric
	,@Curr_Emp_ID	Numeric
	,@Curr_Cmp_ID	Numeric
	,@Curr_Bond_Id  Numeric
	,@New_Balance	Numeric
	,@For_Date		DateTime
	,@Bond_Row_ID	Numeric
	,@New_Bond_Apr_Id Numeric
	,@Tran_Type		varchar(1)
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON 
	
	--Old Detail
	DECLARE @BOND_APR_ID		NUMERIC
	DECLARE @BOND_APR_DATE		DATETIME
	DECLARE @BOND_APR_CODE		VARCHAR(20)
	DECLARE @BOND_APR_AMOUNT	NUMERIC
	DECLARE @BOND_APR_NO_OF_INSTALLMENT		NUMERIC
	DECLARE @BOND_APR_INSTALLMENT_AMOUNT	NUMERIC(18,2)
	DECLARE @BOND_APR_DEDUCT_FROM_SAL	NUMERIC
	DECLARE @BOND_APR_PENDING_AMOUNT	NUMERIC(18,2)
	DECLARE @DEDUCTION_TYPE				VARCHAR(20)


	DECLARE @BOND_RETURN_MODE	VARCHAR(1)
	DECLARE @BOND_RETURN_MONTH	INT
	DECLARE @BOND_RETURN_YEAR	INT
	DECLARE @BOND_RETURN_STATUS VARCHAR(5)
	DECLARE @BOND_RETURN_DATE	DATETIME
	DECLARE @PAYMENT_PROCESS_ID INT
	DECLARE @INSTALLMENT_START_DATE	DATETIME
	DECLARE @BOND_PAID_AMOUNT	NUMERIC(18,2) = 0
	DECLARE @NO_OF_INSTALLMENT_PAID	INT
	DECLARE @ATTCHMENT_PATH VARCHAR(128)

 
	SELECT @BOND_APR_ID = BOND_APR_ID ,@BOND_APR_NO_OF_INSTALLMENT =  BOND_APR_NO_OF_INSTALLMENT,@BOND_APR_INSTALLMENT_AMOUNT = BOND_APR_INSTALLMENT_AMOUNT,
		   @BOND_APR_DEDUCT_FROM_SAL = BOND_APR_DEDUCT_FROM_SAL,@BOND_APR_PENDING_AMOUNT = BOND_APR_PENDING_AMOUNT,
		   @DEDUCTION_TYPE = DEDUCTION_TYPE,
		   @BOND_RETURN_MODE = BOND_RETURN_MODE,@BOND_RETURN_MONTH=BOND_RETURN_MONTH,@BOND_RETURN_YEAR=BOND_RETURN_YEAR,
		   @BOND_RETURN_STATUS=BOND_RETURN_STATUS,@BOND_RETURN_DATE =BOND_RETURN_DATE,@PAYMENT_PROCESS_ID=PAYMENT_PROCESS_ID,
		   @INSTALLMENT_START_DATE=INSTALLMENT_START_DATE,@BOND_PAID_AMOUNT=BOND_PAID_AMOUNT,@NO_OF_INSTALLMENT_PAID=NO_OF_INSTALLMENT_PAID,
		   @ATTCHMENT_PATH = ATTACHMENT_PATH
	FROM   T0120_BOND_APPROVAL WITH (NOLOCK)
	WHERE  EMP_ID = @CURR_EMP_ID AND CMP_ID = @CURR_CMP_ID AND BOND_ID =@CURR_BOND_ID
	
	
	DECLARE @OLD_CMP_PAID_INSTALLMENT	NUMERIC
	DECLARE @OLD_CMP_PAID_AMOUNT	NUMERIC
	
	SELECT @OLD_CMP_PAID_INSTALLMENT = COUNT(BOND_APR_ID) , @OLD_CMP_PAID_AMOUNT = SUM(Bond_Pay_Amount)  FROM T0210_MONTHLY_BOND_PAYMENT WITH (NOLOCK) WHERE BOND_APR_ID = @BOND_APR_ID
	
	--Adding Import and Old Company Data
	SET @NO_OF_INSTALLMENT_PAID = @NO_OF_INSTALLMENT_PAID + @OLD_CMP_PAID_INSTALLMENT
	SET @BOND_PAID_AMOUNT = @BOND_PAID_AMOUNT + @OLD_CMP_PAID_AMOUNT
	
	
	IF @INSTALLMENT_START_DATE < @For_Date
		SET @INSTALLMENT_START_DATE = @For_Date
		
	
	IF @BOND_APR_NO_OF_INSTALLMENT > 0
		SET @BOND_APR_INSTALLMENT_AMOUNT = @NEW_BALANCE / @BOND_APR_NO_OF_INSTALLMENT
		
	
	
	SET @BOND_APR_DATE = @FOR_DATE
	--SET @BOND_APR_PAYMENT_DATE = @FOR_DATE
	
	--Old Detail
	
	If @Tran_Type ='I' 
			Begin
				
				SELECT @NEW_BOND_APR_ID = ISNULL(MAX(BOND_APR_ID),0) + 1 	FROM T0120_BOND_APPROVAL WITH (NOLOCK)
				
				SET @BOND_APR_CODE = CAST(@NEW_BOND_APR_ID AS VARCHAR(20))
				
				
				INSERT INTO T0120_BOND_APPROVAL
					(
						
						 BOND_APR_ID
						,CMP_ID
						,EMP_ID
						,BOND_ID
						
						,BOND_APR_DATE
						,BOND_APR_CODE
						,BOND_APR_AMOUNT
						,BOND_APR_NO_OF_INSTALLMENT
						
						,BOND_APR_INSTALLMENT_AMOUNT
						,BOND_APR_DEDUCT_FROM_SAL
						,DEDUCTION_TYPE
						,INSTALLMENT_START_DATE
						
						,BOND_PAID_AMOUNT
						,NO_OF_INSTALLMENT_PAID
						,BOND_APR_PENDING_AMOUNT
						,BOND_APPROVAL_REMARKS
						
						,ATTACHMENT_PATH
						,BOND_RETURN_MODE
						,BOND_RETURN_MONTH
						,BOND_RETURN_YEAR
						,BOND_RETURN_STATUS
						,BOND_RETURN_DATE
						,PAYMENT_PROCESS_ID
						
					
					 )

				VALUES   
					(
						 @NEW_BOND_APR_ID
						,@CMP_ID
						,@EMP_ID
						,@BOND_ID
						
						,@BOND_APR_DATE
						,@BOND_APR_CODE
						,@NEW_BALANCE
						,@BOND_APR_NO_OF_INSTALLMENT
						
						,@BOND_APR_INSTALLMENT_AMOUNT
						,@BOND_APR_DEDUCT_FROM_SAL
						,@DEDUCTION_TYPE
						,@INSTALLMENT_START_DATE
						
						,isnull(@BOND_PAID_AMOUNT,0)
						,@NO_OF_INSTALLMENT_PAID
						,@BOND_APR_PENDING_AMOUNT
						,'Company Transfer'
						
						,@ATTCHMENT_PATH
						,@BOND_RETURN_MODE
						,@BOND_RETURN_MONTH
						,@BOND_RETURN_YEAR
						,@BOND_RETURN_STATUS
						,@BOND_RETURN_DATE
						,@PAYMENT_PROCESS_ID
					 )

		
					IF EXISTS(SELECT 1 FROM T0140_BOND_TRANSACTION WITH (NOLOCK) WHERE  EMP_ID = @CURR_EMP_ID AND CMP_ID = @CURR_CMP_ID AND BOND_ID = @CURR_BOND_ID
								   AND FOR_DATE = (SELECT MAX(FOR_DATE) FROM T0140_BOND_TRANSACTION WITH (NOLOCK)
													WHERE EMP_ID = @CURR_EMP_ID AND CMP_ID = @CURR_CMP_ID AND BOND_ID = @CURR_BOND_ID))
						BEGIN
							UPDATE T0140_BOND_TRANSACTION
							SET    BOND_CLOSING = 0
							WHERE  EMP_ID = @CURR_EMP_ID AND CMP_ID = @CURR_CMP_ID AND BOND_ID = @CURR_BOND_ID
								   AND FOR_DATE = (SELECT MAX(FOR_DATE) FROM T0140_BOND_TRANSACTION WITH (NOLOCK)
												WHERE EMP_ID = @CURR_EMP_ID AND CMP_ID = @CURR_CMP_ID AND BOND_ID = @CURR_BOND_ID)
						END
				
			
						SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1 	FROM T0100_EMP_COMPANY_BOND_TRANSFER WITH (NOLOCK)
																
						INSERT INTO T0100_EMP_COMPANY_Bond_TRANSFER
							(
								 ROW_ID
								,TRAN_ID
								,CMP_ID
								,EMP_ID
								,BOND_ID
								,OLD_BALANCE
								,NEW_CMP_ID
								,NEW_EMP_ID
								,NEW_BOND_ID
								,NEW_BALANCE
								,BOND_ROW_ID
								,NEW_BOND_APR_ID
							)
						VALUES   
							(
								 @ROW_ID
								,@TRAN_ID
								,@CURR_CMP_ID
								,@CURR_EMP_ID
								,@CURR_BOND_ID
								,@OLD_BALANCE
								,@CMP_ID
								,@EMP_ID
								,@BOND_ID
								,@NEW_BALANCE
								,@BOND_ROW_ID
								,@NEW_BOND_APR_ID
							)	
			END
	else if @Tran_Type ='U' 
			begin
				
				DELETE FROM T0100_EMP_COMPANY_BOND_TRANSFER WHERE TRAN_ID=@TRAN_ID
				
				SELECT @ROW_ID = ISNULL(MAX(ROW_ID),0) + 1 	FROM T0100_EMP_COMPANY_BOND_TRANSFER WITH (NOLOCK)
				
					
					INSERT INTO T0100_EMP_COMPANY_BOND_TRANSFER
						(ROW_ID
						,TRAN_ID
						,CMP_ID
						,EMP_ID
						,BOND_ID
						,OLD_BALANCE
						,NEW_CMP_ID
						,NEW_EMP_ID
						,NEW_BOND_ID
						,NEW_BALANCE
						,BOND_ROW_ID
						,NEW_BOND_APR_ID
						)
					VALUES   
						(@ROW_ID
						,@TRAN_ID
						,@CURR_CMP_ID
						,@CURR_EMP_ID
						,@CURR_BOND_ID
						,@OLD_BALANCE
						,@CMP_ID
						,@EMP_ID
						,@BOND_ID
						,@NEW_BALANCE
						,@BOND_ROW_ID
						,@NEW_BOND_APR_ID
						)	
					
					UPDATE   T0120_BOND_APPROVAL
					SET		 BOND_APR_AMOUNT = @NEW_BALANCE,
							 BOND_APR_NO_OF_INSTALLMENT=@BOND_APR_NO_OF_INSTALLMENT,
							 BOND_APR_INSTALLMENT_AMOUNT = @BOND_APR_INSTALLMENT_AMOUNT
					WHERE    BOND_APR_ID = @NEW_BOND_APR_ID AND EMP_ID = @EMP_ID AND CMP_ID = @CMP_ID
					
					
			End
	Else If @Tran_Type ='D'
			Begin
				DELETE FROM T0140_BOND_TRANSACTION WHERE BOND_TRAN_ID = @BOND_TRAN_ID
				DELETE FROM T0100_EMP_COMPANY_BOND_TRANSFER WHERE ROW_ID = @ROW_ID AND TRAN_ID=@TRAN_ID
			End
			
RETURN

