

-- =============================================
-- Author:		Nimesh Parmar
-- Create date: 27-Jul-2015
-- Description:	To update the total calculated interest on GPF Interest
---29/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0100_EMP_GPF_INTEREST_CREDIT_UPDATE]
	@Cmp_ID		NUMERIC,
	@Tran_ID	NUMERIC OUTPUT,
	@EMP_ID		NUMERIC,
	@AD_ID		NUMERIC,
	@MONTH		NUMERIC,
	@YEAR		NUMERIC,	
	@AMOUNT		NUMERIC(18,4),
	@Tran_Type	TINYINT = 1
AS
BEGIN	
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	DECLARE @FROM_DATE		DATETIME;
	DECLARE @TO_DATE		DATETIME;	
	DECLARE @YEAR_ST_DATE	DATETIME;
	DECLARE @YEAR_END_DATE	DATETIME;
	DECLARE @GPF_INT_PERC	NUMERIC(18,4);
    	
	IF @MONTH > 3 
		BEGIN
			SET	@YEAR_ST_DATE	= CAST(CAST(@YEAR - 1 AS varchar) + '-04-01' AS DATETIME);
			SET	@YEAR_END_DATE  = CAST(CAST(@YEAR AS varchar) + '-03-31 23:59:59' AS DATETIME);						
			SET	@FROM_DATE	= CAST(CAST(@YEAR AS varchar) + '-' + CAST(@MONTH AS varchar) + '-01' AS DATETIME);
		END
	ELSE
		BEGIN
			SET	@YEAR_ST_DATE	= CAST(CAST(@YEAR AS varchar) + '-01-01' AS DATETIME);
			SET	@YEAR_END_DATE  = CAST(CAST(@YEAR AS varchar) + '-12-31 23:59:59' AS DATETIME);
			SET	@FROM_DATE	= CAST(CAST(@YEAR - 1 AS varchar) + '-' + CAST(@MONTH AS varchar) + '-01' AS DATETIME);
		END
		
	--SET	@TO_DATE  = CAST(CAST(DATEADD(D, -1, DATEADD(M, 1, @FROM_DATE)) As varchar) + ' 23:59:59' AS DATETIME);
	SET	@TO_DATE  = CONVERT(DATETIME, CONVERT(VARCHAR(10), DATEADD(D, -1, DATEADD(M, 1, @FROM_DATE)) , 103) + ' 23:59:59', 103);
		
	IF (@Tran_Type = 2)	--For Delete
		BEGIN
			DELETE	FROM	T0100_EMP_GPF_INTEREST_CREDIT
			WHERE	Tran_ID=@TRAN_ID AND CMP_ID=@CMP_ID
			
			RETURN;
		END
	
	--For Insert/Update
	SELECT	@TRAN_ID=TRAN_ID
	FROM	T0100_EMP_GPF_INTEREST_CREDIT CR WITH (NOLOCK)
	WHERE	CR.Emp_ID=@EMP_ID AND CR.AD_ID=@AD_ID AND CR.Cmp_ID=@CMP_ID
			AND MONTH(CR.Year_END_Date)=MONTH(@YEAR_END_DATE)
			AND YEAR(CR.Year_END_Date)=YEAR(@YEAR_END_DATE)
			
	IF ISNULL(@TRAN_ID,0) > 0
		BEGIN
			UPDATE	T0100_EMP_GPF_INTEREST_CREDIT
			SET		Amount=@AMOUNT
			WHERE	Tran_ID = @TRAN_ID
		END
	ELSE
		BEGIN
			SELECT	@TRAN_ID=ISNULL(MAX(TRAN_ID),0) + 1 
			FROM	T0100_EMP_GPF_INTEREST_CREDIT WITH (NOLOCK)			
			
			print @TRAN_ID
			INSERT INTO T0100_EMP_GPF_INTEREST_CREDIT
				(Cmp_ID,Tran_ID,Emp_ID,AD_ID,From_Date,To_Date,Year_St_Date,Year_End_Date,Amount,SystemDate)
			VALUES
				(@CMP_ID,@TRAN_ID,@EMP_ID,@AD_ID,@FROM_DATE,@TO_DATE,@YEAR_ST_DATE,@YEAR_END_DATE,@AMOUNT,GETDATE());
		END
		
END

