

---02/2/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0110_EMP_LEFT_JOIN_TRAN]
	@EMP_ID			NUMERIC,
	@CMP_ID			NUMERIC,
	@JOIN_DATE		DATETIME,
	@OLD_JOIN_DATE	DATETIME  = NULL,
	@LEFT_DATE		DATETIME  = NULL,
	@LEFT_ID		NUMERIC   = NULL
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
			
	DECLARE @LJ_TRAN_ID AS NUMERIC 
	
	IF @LEFT_ID = 0
		SET @LEFT_ID  = NULL
		
	IF @LEFT_DATE = ''
		SET @LEFT_DATE = NULL
	
	IF @OLD_JOIN_DATE = ''
		SET @OLD_JOIN_DATE = NULL
		
		
	IF ISNULL(@LEFT_ID,0) > 0 
		BEGIN
			UPDATE	T0110_EMP_LEFT_JOIN_TRAN
			SET		LEFT_DATE = @LEFT_DATE ,
					LEFT_ID		= @LEFT_ID 
			WHERE	EMP_ID = @EMP_ID AND JOIN_DATE = @JOIN_DATE
		END
	ELSE IF ISNULL(@OLD_JOIN_DATE,'') <> ''
		BEGIN
			IF EXISTS(SELECT EMP_ID FROM T0110_EMP_LEFT_JOIN_TRAN WITH (NOLOCK) WHERE EMP_ID = @EMP_ID AND JOIN_DATE = @OLD_JOIN_DATE)
				BEGIN
					UPDATE	T0110_EMP_LEFT_JOIN_TRAN
					SET		JOIN_DATE = @JOIN_DATE 
					WHERE	EMP_ID = @EMP_ID AND JOIN_DATE = @OLD_JOIN_DATE
				END
			ELSE
				BEGIN
					SELECT 	@LJ_TRAN_ID = ISNULL(MAX(LJ_TRAN_ID),0 )+1 FROM T0110_EMP_LEFT_JOIN_TRAN WITH (NOLOCK)
					
					INSERT INTO T0110_EMP_LEFT_JOIN_TRAN
										  (LJ_Tran_ID, Emp_ID, Cmp_ID, Join_Date, Left_Date, Left_ID)
					VALUES     (@LJ_Tran_ID, @Emp_ID, @Cmp_ID, @Join_Date, @Left_Date, @Left_ID)
				END
		END
	ELSE
		BEGIN
			SELECT 	@LJ_TRAN_ID = ISNULL(MAX(LJ_TRAN_ID),0 )+1 FROM T0110_EMP_LEFT_JOIN_TRAN WITH (NOLOCK)
			
			INSERT INTO T0110_EMP_LEFT_JOIN_TRAN
								  (LJ_Tran_ID, Emp_ID, Cmp_ID, Join_Date, Left_Date, Left_ID)
			VALUES     (@LJ_Tran_ID, @Emp_ID, @Cmp_ID, @Join_Date, @Left_Date, @Left_ID)
			
		END
		
	
	
	RETURN




