

---30/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0120_BOND_APPROVAL]
	 @BOND_APR_ID			NUMERIC = 0 OUTPUT
	,@CMP_ID				NUMERIC
	,@EMP_ID				NUMERIC
	,@BOND_ID				NUMERIC
	,@BOND_APR_DATE			DATETIME
	,@BOND_APR_CODE			VARCHAR(20)
	
	,@BOND_APR_AMOUNT				NUMERIC
	,@BOND_APR_NO_OF_INSTALLMENT	NUMERIC
	,@BOND_APR_INSTALLMENT_AMOUNT	NUMERIC(18,2)
	,@BOND_APR_DEDUCT_FROM_SAL		NUMERIC
	--,@BOND_APR_INTREST_TYPE			VARCHAR(20)
	
	,@DEDUCTION_TYPE				VARCHAR(20)
	,@INSTALLMENT_START_DATE		DATETIME
	,@BOND_PAID_AMOUNT				NUMERIC(18,2) = 0
	,@NO_OF_INSTALLMENT_PAID		NUMERIC(18,0)  = 0
	--,@BOND_RETURN_MODE						CHAR(5)
	,@BOND_APPROVAL_REMARKS			VARCHAR(250)
	,@ATTACHMENT_PATH				NVARCHAR(MAX)= ''
    ,@USER_ID NUMERIC(18,0) = 0 
	,@IP_ADDRESS VARCHAR(30)= ''
	,@INST_ID NUMERIC = 0
	,@BOND_RETURN_MODE				CHAR(1)
	,@BOND_RETURN_MONTH INTEGER -- = 0
	,@BOND_RETURN_YEAR INTEGER -- = 0
	,@TRAN_TYPE						VARCHAR(1)
	
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
		
	IF @INSTALLMENT_START_DATE = ''
		SET @INSTALLMENT_START_DATE = NULL
		
	DECLARE @CF_LOAN_AMT NUMERIC;
	DECLARE @CF_LOAN_APR_ID NUMERIC;
	SET @CF_LOAN_AMT = 0;
	SET @CF_LOAN_APR_ID = 0;

	DECLARE @OLDVALUE AS  VARCHAR(MAX)
	DECLARE @STRING AS VARCHAR(MAX)
	SET @STRING=''
	SET @OLDVALUE =''

	
	IF @TRAN_TYPE ='I' 
		BEGIN	
		
			SELECT @BOND_APR_ID = ISNULL(MAX(BOND_APR_ID),0) + 1 FROM T0120_BOND_APPROVAL WITH (NOLOCK) 
			
		
			SET	@BOND_APR_CODE = CAST(@BOND_APR_ID AS VARCHAR(20))
		
			IF EXISTS (SELECT 1 FROM T0120_BOND_APPROVAL WITH (NOLOCK) WHERE BOND_ID = @BOND_ID AND EMP_ID = @EMP_ID AND BOND_APR_DATE = @BOND_APR_DATE AND INSTALLMENT_START_DATE =  @INSTALLMENT_START_DATE )
			BEGIN 
				RAISERROR ('@@Bond With Same Details Already Exists@@' , 16 , 2)
				RETURN 0;
			END


			INSERT INTO T0120_BOND_APPROVAL
			(
				 BOND_APR_ID
				,CMP_ID		
				,EMP_ID		
				,BOND_ID		
				,BOND_APR_DATE	
				,BOND_APR_CODE	
				
				,BOND_APR_AMOUNT	
				,BOND_APR_NO_OF_INSTALLMENT	
				,BOND_APR_INSTALLMENT_AMOUNT	
				,BOND_APR_DEDUCT_FROM_SAL		
				--,BOND_APR_INTREST_TYPE			
				
				,DEDUCTION_TYPE				
				,INSTALLMENT_START_DATE		
				,BOND_PAID_AMOUNT				
				,NO_OF_INSTALLMENT_PAID	
				,BOND_APR_PENDING_AMOUNT
				--,BOND_MODE	
				,BOND_APPROVAL_REMARKS	
				,ATTACHMENT_PATH
				,BOND_RETURN_MODE
				,BOND_RETURN_MONTH
				,BOND_RETURN_YEAR
				
			)	

			VALUES   
			(
				 @BOND_APR_ID
				,@CMP_ID		
				,@EMP_ID		
				,@BOND_ID		
				,@BOND_APR_DATE	
				,@BOND_APR_CODE	
				
				,@BOND_APR_AMOUNT	
				,@BOND_APR_NO_OF_INSTALLMENT	
				,@BOND_APR_INSTALLMENT_AMOUNT	
				,@BOND_APR_DEDUCT_FROM_SAL	
				--,'Fix'	
				--,@BOND_APR_INTREST_TYPE			
				
				,@DEDUCTION_TYPE				
				,@INSTALLMENT_START_DATE		
				,@BOND_PAID_AMOUNT				
				,@NO_OF_INSTALLMENT_PAID		
				,@BOND_APR_AMOUNT
				--,@BOND_MODE
				,@BOND_APPROVAL_REMARKS	
				,@ATTACHMENT_PATH
				,@BOND_RETURN_MODE
				,@BOND_RETURN_MONTH
				,@BOND_RETURN_YEAR
				
			)
		
			---- INSTALLMENT DETAILS FIRST TIME ADD ----
			
			IF NOT EXISTS(SELECT 1 FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK) WHERE CMP_ID=@CMP_ID AND BOND_APR_ID=@BOND_APR_ID AND EFFECTIVE_DATE=@INSTALLMENT_START_DATE)
				BEGIN
					DECLARE @INSTALLMENT_ID AS NUMERIC(18,0)
					SELECT @INSTALLMENT_ID = ISNULL(MAX(INSTALLMENT_ID),0) + 1 FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK)
					
					INSERT INTO T0130_BOND_INSTALLMENT_DETAIL(INSTALLMENT_ID,CMP_ID,EMP_ID,BOND_ID,BOND_APR_ID,EFFECTIVE_DATE,INSTALLMENT_AMT,SYSTEM_DATE)
					VALUES(@INSTALLMENT_ID,@CMP_ID,@EMP_ID,@BOND_ID,@BOND_APR_ID,@INSTALLMENT_START_DATE,@BOND_APR_INSTALLMENT_AMOUNT,GETDATE())
					
				END
			
			---- END ----
		
			
			EXEC P9999_AUDIT_GET @TABLE = 'T0120_BOND_APPROVAL' ,@KEY_COLUMN='BOND_APR_ID',@KEY_VALUES=@BOND_APR_ID,@STRING=@STRING OUTPUT
			SET @OLDVALUE = @OLDVALUE + 'NEW VALUE' + '#' + CAST(@STRING AS VARCHAR(MAX))	 
		
		END 
	ELSE IF @TRAN_TYPE ='U' 
				BEGIN			
				
	
						EXEC P9999_AUDIT_GET @TABLE='T0120_BOND_APPROVAL' ,@KEY_COLUMN='BOND_APR_ID',@KEY_VALUES=@BOND_APR_ID,@STRING=@STRING OUTPUT
						SET @OLDVALUE = @OLDVALUE + 'OLD VALUE' + '#' + CAST(@STRING AS VARCHAR(MAX))
					
						
						UPDATE   T0120_BOND_APPROVAL
						SET		 BOND_APR_INSTALLMENT_AMOUNT = @BOND_APR_INSTALLMENT_AMOUNT	
								,INSTALLMENT_START_DATE = @INSTALLMENT_START_DATE		
								,BOND_APPROVAL_REMARKS = @BOND_APPROVAL_REMARKS	
								,ATTACHMENT_PATH = @ATTACHMENT_PATH
								,BOND_RETURN_MODE = @BOND_RETURN_MODE
								,BOND_RETURN_MONTH = @BOND_RETURN_MONTH
								,BOND_RETURN_YEAR = @BOND_RETURN_YEAR
						WHERE BOND_APR_ID = @BOND_APR_ID 				
						
							  
						
						EXEC P9999_AUDIT_GET @TABLE = 'T0120_BOND_APPROVAL' ,@KEY_COLUMN='BOND_APR_ID',@KEY_VALUES=@BOND_APR_ID,@STRING=@STRING OUTPUT
						SET @OLDVALUE = @OLDVALUE + 'NEW VALUE' + '#' + CAST(@STRING AS VARCHAR(MAX))	 
					
				END
	ELSE IF @TRAN_TYPE ='D'
		BEGIN
		
			--IF  @BOND_RETURN_MODE = 'A' 
			--	BEGIN 
			
					EXEC P9999_AUDIT_GET @TABLE='T0120_BOND_APPROVAL' ,@KEY_COLUMN='BOND_APR_ID',@KEY_VALUES=@BOND_APR_ID,@STRING=@STRING OUTPUT
					SET @OLDVALUE = @OLDVALUE + 'OLD VALUE' + '#' + CAST(@STRING AS VARCHAR(MAX))
		
					
					DELETE FROM T0130_BOND_INSTALLMENT_DETAIL where BOND_APR_ID = @BOND_APR_ID
					DELETE FROM T0120_BOND_APPROVAL where BOND_APR_ID = @BOND_APR_ID
					
			--End
			
		End	
		
			
	EXEC P9999_AUDIT_TRAIL @CMP_ID,@TRAN_TYPE,'BOND APPROVAL',@OLDVALUE,@EMP_ID,@USER_ID,@IP_ADDRESS,1
RETURN

