
CREATE PROCEDURE [dbo].[P0120_HRMS_TRAINING_SCHEDULE_INSERT]
@SCHEDULE_ID NUMERIC(18,0),
@TRAINING_APP_ID NUMERIC(18,0),
@FROM_DATE DATETIME,
@TO_DATE DATETIME,
@FROM_TIME NVARCHAR(20),
@TO_TIME NVARCHAR(20),
@Cmp_Id	 Numeric(18,0)
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
 --IF NOT EXISTS(SELECT 1 FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) WHERE FROM_DATE= @FROM_DATE and To_date = @TO_DATE and Training_App_ID = @Training_App_ID)--commented by mansi
 IF NOT EXISTS(SELECT 1 FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) WHERE FROM_DATE= @FROM_DATE and To_date = @TO_DATE and Training_App_ID = @Training_App_ID and @FROM_TIME=From_Time and @TO_TIME=To_Time)--added by mansi
	--IF NOT EXISTS(SELECT 1 FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK) WHERE Training_App_ID = @Training_App_ID)
		BEGIN
		print 111
			SELECT @SCHEDULE_ID = ISNULL(MAX(SCHEDULE_ID),0) + 1 FROM T0120_HRMS_TRAINING_SCHEDULE WITH (NOLOCK)
			INSERT INTO T0120_HRMS_TRAINING_SCHEDULE(SCHEDULE_ID,TRAINING_APP_ID,FROM_DATE,TO_DATE,FROM_TIME,TO_TIME,Cmp_Id)
			VALUES(@SCHEDULE_ID,@TRAINING_APP_ID,@FROM_DATE,@TO_DATE,@FROM_TIME,@TO_TIME,@Cmp_Id)
		END
	ELSE
		BEGIN
		print 2222
			RETURN 0
		END
	---added on 21/02/2017 generate training code based on the training date--
	DECLARE @Training_Code as varchar(50)
	DECLARE @Min_Trainingdate as DATETIME
	
	SELECT @Min_Trainingdate = MIN(From_date) FROM T0120_HRMS_TRAINING_Schedule WITH (NOLOCK) WHERE Training_App_ID= @TRAINING_APP_ID
	
	SELECT @Training_Code = isnull(count(Training_Apr_ID),0)+1 
	FROM T0120_HRMS_TRAINING_APPROVAL WITH (NOLOCK) INNER JOIN
	(
		SELECT MIN(From_date)from_date,Training_App_ID
		FROM T0120_HRMS_TRAINING_Schedule  WITH (NOLOCK)
		WHERE cmp_id = @Cmp_Id
		GROUP by Training_App_ID
	)TS on TS.Training_App_ID = T0120_HRMS_TRAINING_APPROVAL.Training_App_ID
	WHERE T0120_HRMS_TRAINING_APPROVAL.Training_App_ID <> @TRAINING_APP_ID and TS.from_date = @Min_Trainingdate
	 
	SET @Training_Code = REPLACE(CONVERT(char,@Min_Trainingdate,5),'-','') +'00' + @Training_Code 
	print @Training_Code
	UPDATE T0120_HRMS_TRAINING_APPROVAL SET Training_Code = REPLACE(@Training_Code,' ','') where Training_App_ID = @TRAINING_APP_ID
END

