

---20/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
CREATE PROCEDURE [dbo].[P0130_BOND_INSTALLMENT_DETAIL]
	 @BOND_APR_ID					NUMERIC = 0 OUTPUT
	,@CMP_ID						NUMERIC
	,@EMP_ID						NUMERIC
	,@BOND_ID						NUMERIC
	,@BOND_APR_INSTALLMENT_AMOUNT	NUMERIC(18,2)
	,@INSTALLMENT_START_DATE		DATETIME
	,@INSTALLMENT_ID				NUMERIC = 0 
	,@TRAN_TYPE						VARCHAR(1)
	
	
AS
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON
		
		
	--IF ISNULL(@INSTALLMENT_ID,0) = 0 
	--	BEGIN
	--		RAISERROR('@@ Installment Id must be specified @@',16,2)
	--		RETURN
	--	END
	    
		IF @TRAN_TYPE ='I'
			BEGIN
				IF  EXISTS(SELECT 1 FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK) WHERE EFFECTIVE_DATE = @INSTALLMENT_START_DATE AND CMP_ID = @CMP_ID AND EMP_ID = @EMP_ID)
					BEGIN
						RAISERROR('@@ Installment amount already exist on this effective date @@',16,2)
						RETURN
					END
				
				
				SELECT @INSTALLMENT_ID = ISNULL(MAX(INSTALLMENT_ID),0) + 1 FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK)
			
				INSERT INTO T0130_BOND_INSTALLMENT_DETAIL
				(	
					INSTALLMENT_ID,
					CMP_ID,
					EMP_ID,
					BOND_ID,
					BOND_APR_ID,
					EFFECTIVE_DATE,
					INSTALLMENT_AMT,
					SYSTEM_DATE
				)
				VALUES
				(
					@INSTALLMENT_ID,
					@CMP_ID,
					@EMP_ID,
					@BOND_ID,
					@BOND_APR_ID,
					@INSTALLMENT_START_DATE,
					@BOND_APR_INSTALLMENT_AMOUNT,
					GETDATE()
				)
			END
			
		ELSE IF @TRAN_TYPE ='U'
			BEGIN
				UPDATE T0130_BOND_INSTALLMENT_DETAIL
				SET INSTALLMENT_AMT = @BOND_APR_INSTALLMENT_AMOUNT,
					SYSTEM_DATE = GETDATE()
				WHERE INSTALLMENT_ID = @INSTALLMENT_ID AND CMP_ID = @CMP_ID AND BOND_APR_ID = @BOND_APR_ID AND BOND_ID = @BOND_ID
			END
			
		ELSE IF @TRAN_TYPE ='E'
			BEGIN
				 SELECT EM.WORK_EMAIL, EM.MOBILE_NO, DESM.DESIG_NAME,
				 DM.DEPT_NAME,VS.VERTICAL_NAME,VSV.SUBVERTICAL_NAME,
				 BM.BRANCH_NAME, INC.CTC, INC.GROSS_SALARY,EM.DATE_OF_JOIN,
				 INC.BASIC_SALARY,QRY_REPORTING.EMP_FULL_NAME AS REFERENCE_NAME FROM  DBO.T0080_EMP_MASTER EM WITH (NOLOCK)
				 INNER JOIN DBO.T0095_INCREMENT INC WITH (NOLOCK)
				 LEFT OUTER JOIN DBO.T0040_DEPARTMENT_MASTER DM WITH (NOLOCK) ON INC.DEPT_ID = DM.DEPT_ID 
				 LEFT OUTER JOIN DBO.T0040_VERTICAL_SEGMENT VS WITH (NOLOCK) ON INC.VERTICAL_ID = VS.VERTICAL_ID 
				 LEFT OUTER JOIN DBO.T0050_SUBVERTICAL VSV WITH (NOLOCK) ON INC.SUBVERTICAL_ID = VSV.SUBVERTICAL_ID 
				 LEFT OUTER JOIN DBO.T0030_BRANCH_MASTER BM WITH (NOLOCK) ON INC.BRANCH_ID = BM.BRANCH_ID 
				 INNER JOIN DBO.T0040_DESIGNATION_MASTER DESM WITH (NOLOCK) ON INC.DESIG_ID = DESM.DESIG_ID ON EM.INCREMENT_ID = INC.INCREMENT_ID 
				 LEFT OUTER JOIN  (
				 
								  SELECT	R1.EMP_ID, R1.FOR_DATE, R1.R_EMP_ID, (EM.ALPHA_EMP_CODE + ' - ' + EM.EMP_FULL_NAME)AS EMP_FULL_NAME,R1.SOURCE_TYPE
								  FROM      dbo.T0090_EMP_REFERENCE_DETAIL AS R1 WITH (NOLOCK)
											INNER JOIN (
														
														SELECT	MAX(R2.REFERENCE_ID) AS ROW_ID, R2.R_Emp_ID
														FROM    dbo.T0090_EMP_REFERENCE_DETAIL AS R2 WITH (NOLOCK)
																INNER JOIN (
																
																				SELECT     MAX(FOR_DATE) AS Effect_Date, R_Emp_ID
																				FROM          dbo.T0090_EMP_REFERENCE_DETAIL AS R3 WITH (NOLOCK)
																				WHERE      (FOR_DATE < GETDATE())
																				GROUP BY R_Emp_ID
																				
																			) AS R3_1 ON R2.R_Emp_ID = R3_1.R_Emp_ID AND R2.FOR_DATE = R3_1.Effect_Date
															GROUP BY R2.R_Emp_ID
															
														) AS R2_1 ON R1.REFERENCE_ID = R2_1.ROW_ID AND R1.R_Emp_ID = R2_1.R_Emp_ID 
														INNER JOIN dbo.T0080_EMP_MASTER AS Em WITH (NOLOCK) ON R1.R_Emp_ID = Em.Emp_ID
														
								) AS Qry_Reporting ON EM.Emp_ID = Qry_Reporting.Emp_ID AND Qry_Reporting.SOURCE_TYPE = 2
								WHERE EM.EMP_ID=@EMP_ID
			END
			
		ELSE IF @TRAN_TYPE ='D'	--Added By Ramiz on 22/10/2018
			BEGIN
				
				DECLARE @Installment_Records as NUMERIC
				SET @Installment_Records = 0	
				
				SELECT @EMP_ID = Emp_ID , @BOND_APR_ID = Bond_Apr_ID 
				FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK)
				WHERE INSTALLMENT_ID = @INSTALLMENT_ID AND CMP_ID = @CMP_ID
 
				SELECT @Installment_Records = COUNT(1) 
				FROM T0130_BOND_INSTALLMENT_DETAIL WITH (NOLOCK)
				WHERE Emp_ID = @EMP_ID AND Bond_Apr_ID = @BOND_APR_ID
				
				IF @Installment_Records > 1
					BEGIN
						DELETE FROM T0130_BOND_INSTALLMENT_DETAIL
						WHERE INSTALLMENT_ID = @INSTALLMENT_ID AND CMP_ID = @CMP_ID
						
						SELECT 'Deleted Successfully' AS Rules_Violate_msg
					END
				ELSE
					BEGIN
						SELECT  'You cannot delete the Last Record' as Rules_Violate_msg
					END
				

			END
RETURN

