
CREATE PROCEDURE [dbo].[P0130_CLAIM_SUBDETAIL_Backup_Tejas(30March2024)]
	  @CLAIM_APPLICATION_ID NUMERIC(18) OUTPUT
	 ,@CLAIM_ID NUMERIC(18) 
	 ,@EMP_ID NUMERIC(18,0)
	 ,@CMP_ID NUMERIC(18,0)
	 ,@DATE DATETIME
	 ,@CLAIM_LIMIT_TYPE CHAR(1) = 'D'
	 ,@TRAN_TYPE CHAR(5)
	 ,@RPT_LEVEL INT = 0 -- ADDED BY RAJPUT ON 22052018
	 ,@Claim_Apr_Id numeric(18,0) = 0  --Added by Jaina 9-10-2020
AS
	DECLARE @TRAN_ID	NUMERIC
	DECLARE @DESI_ID	NUMERIC(18,0)
	DECLARE @GRADE_ID	NUMERIC(18,0)
	DECLARE @BRANCH_ID	NUMERIC(18,0)
   
	
	SET @TRAN_ID = 0
	SET @DESI_ID = 0 
	SET @GRADE_ID = 10 
	SET @BRANCH_ID = 0
	
	IF @TRAN_TYPE ='E' 
		BEGIN
			--SELECT EMP_FULL_NAME,GRD_ID,EMP_SUPERIOR,WORK_EMAIL,DESIG_ID,GRD_ID,BRANCH_ID 
			--FROM T0080_EMP_MASTER WHERE EMP_ID = @EMP_ID AND CMP_ID = @CMP_ID
			
			SELECT E.EMP_FULL_NAME,I.GRD_ID,E.EMP_SUPERIOR,E.WORK_EMAIL,I.DESIG_ID,I.BRANCH_ID,E.Emp_ID,E.Alpha_Emp_Code FROM T0080_EMP_MASTER E INNER JOIN 
			T0095_INCREMENT I ON E.EMP_ID=I.Emp_ID
	 		INNER JOIN 
				( 
				
					SELECT MAX(I.INCREMENT_ID) AS INCREMENT_ID, I.EMP_ID 
					FROM T0095_INCREMENT I 
					INNER JOIN 
					(
							SELECT MAX(I3.INCREMENT_EFFECTIVE_DATE) AS INCREMENT_EFFECTIVE_DATE, I3.EMP_ID
							FROM T0095_INCREMENT I3
							WHERE I3.INCREMENT_EFFECTIVE_DATE <= GETDATE()
							GROUP BY I3.EMP_ID  
							
					) I3 ON I.INCREMENT_EFFECTIVE_DATE=I3.INCREMENT_EFFECTIVE_DATE AND I.EMP_ID=I3.EMP_ID	
					WHERE I.INCREMENT_EFFECTIVE_DATE <= GETDATE() AND I.CMP_ID = @CMP_ID 
				    GROUP BY I.EMP_ID  
				) QRY ON I.EMP_ID = QRY.EMP_ID	AND I.INCREMENT_ID = QRY.INCREMENT_ID 
				WHERE E.CMP_ID = @CMP_ID AND I.EMP_ID = @EMP_ID
					
		END
	ELSE IF @TRAN_TYPE='AD' -- CLAIM APPROVAL DETAILS 
		BEGIN
					
					DECLARE @APPLICATION_EMP_ID AS NUMERIC(18,0)
					
					if @Claim_Apr_Id = 0
						Begin
							SELECT	TAP.CMP_ID,TAP.CLAIM_AMOUNT AS AMOUNT,TAP.APPLICATION_AMOUNT AS TOTALAMOUNT,TAP.CLAIM_ID,
							TAP.APPLICATION_AMOUNT AS TOTALAMOUNT_ONE,TAP.CLAIM_DESCRIPTION AS DESCRIPTION,TAP.CURR_RATE AS EXCHANGE_RATE,CLM.CLAIM_NAME,
							CRD.CURR_NAME AS CURRENCY,PETROL_KM AS APPROVED_PETROL_KM,CLAIM_APP_DETAIL_ID,CLAIM_APP_ID,FOR_DATE,APPLICATION_AMOUNT,CLAIM_MAX_LIMIT,
							GRADE_WISE_LIMIT,DESIG_WISE_LIMIT,BRANCH_WISE_LIMIT,CLAIM_LIMIT_TYPE,CLAIM_TYPE,PETROL_KM,TAP.Curr_ID,CLAIM_ATTACHMENT,CLM.CLAIM_ALLOW_BEYOND_LIMIT,
							(CASE WHEN CLM.CLAIM_APR_DEDUCT_FROM_SAL = 1 THEN 'Yes' ELSE 'No' END) AS CLAIM_APR_DEDUCT_FROM_SAL,
							'' as Claim_Status,
							isnull(TAP.Claim_Model,'') as Model,isnull(TAP.Claim_IMEI,'') as IMEI,isnull(TAP.Claim_NoofPerson,'') as NoofPerson,isnull(convert(varchar,Claim_DateOfPurchase,103),'') as DateOfPurchase,
							ISNULL(tap.Claim_BookName,'') as BookName,ISNULL(tap.Claim_Subject,'') as Subject,ISNULL(tap.Claim_ActualPrice,0) as ActualPrice,ISNULL(tap.Claim_PriceAfterDiscount,0) as PriceAfterDiscount,
							isnull(TAP.Claim_FamilyMember,'') as FamilyMember,isnull(Claim_Relation,'') as Relation,isnull(Claim_Age,0) as Age,isnull(Claim_Limit,0) as Limit,isnull(Claim_FamilyMeberId,0) as RowId,
							isnull(Claim_UnitName,'') as UnitName,isnull(Claim_UnitFlag,0) as UnitFlag,isnull(Claim_ConversionRate,0) as ConversionRate, '' as Claim_Comments,'' as Claim_Apr_Comments,'' as Purpose
							INTO #TABLE_CLAIM_APPROVAL_DETAILS
							FROM T0110_CLAIM_APPLICATION_DETAIL TAP WITH(NOLOCK)
							LEFT OUTER JOIN T0040_CLAIM_MASTER CLM WITH(NOLOCK) ON CLM.CLAIM_ID=TAP.CLAIM_ID 
							LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD WITH(NOLOCK) ON TAP.CURR_ID =CRD.CURR_ID 
							WHERE CLAIM_APP_ID=@CLAIM_APPLICATION_ID ORDER BY FOR_DATE ASC, CLAIM_NAME DESC
					
							SELECT * FROM #TABLE_CLAIM_APPROVAL_DETAILS order by CLAIM_ID,FOR_DATE
						END
					ELSE
					BEGIN
							--Added by Jaina 9-10-2020
							SELECT	TAP.CMP_ID,TAP.Claim_Apr_Amount AS AMOUNT,TAP.Claim_App_Amount AS TOTALAMOUNT,TAP.CLAIM_ID,
							TAP.Claim_App_Ttl_Amount AS TOTALAMOUNT_ONE,TAP.Purpose AS DESCRIPTION,TAP.CURR_RATE AS EXCHANGE_RATE,CLM.CLAIM_NAME,
							CRD.CURR_NAME AS CURRENCY,TAP.PETROL_KM AS APPROVED_PETROL_KM,Claim_Apr_Dtl_ID as CLAIM_APP_DETAIL_ID,CAD.CLAIM_APP_ID,Claim_Apr_Date As FOR_DATE,Claim_Apr_Amount as APPLICATION_AMOUNT,CLAIM_MAX_LIMIT,
							GRADE_WISE_LIMIT,DESIG_WISE_LIMIT,BRANCH_WISE_LIMIT,CLAIM_LIMIT_TYPE,CLAIM_TYPE,TAP.PETROL_KM,TAP.Curr_ID,CLAIM_ATTACHMENT,CLM.CLAIM_ALLOW_BEYOND_LIMIT,
							(CASE WHEN CLM.CLAIM_APR_DEDUCT_FROM_SAL = 1 THEN 'Yes' ELSE 'No' END) AS CLAIM_APR_DEDUCT_FROM_SAL,
							'' as Claim_Status,
							isnull(CAD.Claim_Model,'') as Model,isnull(CAD.Claim_IMEI,'') as IMEI,isnull(CAD.Claim_NoofPerson,'') as NoofPerson,isnull(convert(varchar,TAP.Claim_DateOfPurchase,103),'') as DateOfPurchase,
							ISNULL(tap.Claim_BookName,'') as BookName,ISNULL(tap.Claim_Subject,'') as Subject,ISNULL(tap.Claim_ActualPrice,0) as ActualPrice,ISNULL(tap.Claim_PriceAfterDiscount,0) as PriceAfterDiscount,
							isnull(TAP.Claim_FamilyMember,'') as FamilyMember,isnull(TAP.Claim_Relation,'') as Relation,isnull(TAP.Claim_Age,0) as Age,isnull(TAP.Claim_Limit,0) as Limit,isnull(TAP.Claim_FamilyMeberId,0) as RowId,
							isnull(TAP.Claim_UnitName,'') as UnitName,isnull(TAP.Claim_UnitFlag,0) as UnitFlag,isnull(TAP.Claim_ConversionRate,0) as ConversionRate, '' as Claim_Comments, '' as Claim_Apr_Comments,'' as Purpose
							INTO #TABLE_CLAIM_APPROVAL_DETAILS_New
							FROM T0130_CLAIM_APPROVAL_DETAIL TAP WITH(NOLOCK)
							LEft outer join T0110_CLAIM_APPLICATION_DETAIL CAD WITH(NOLOCK) on TAP.Claim_App_ID = CAD.Claim_App_ID
							LEFT OUTER JOIN T0040_CLAIM_MASTER CLM WITH(NOLOCK) ON CLM.CLAIM_ID=TAP.CLAIM_ID 
							LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD WITH(NOLOCK) ON TAP.CURR_ID =CRD.CURR_ID 
							WHERE Claim_Apr_ID= @Claim_Apr_Id ORDER BY Claim_Apr_Date ASC, CLAIM_NAME DESC

							SELECT * FROM #TABLE_CLAIM_APPROVAL_DETAILS_NEW
					END
					
		END
	ELSE IF @TRAN_TYPE='CLD' -- CLAIM LEVEL WISE APPROVAL DETAILS
		BEGIN
			
			IF(@CLAIM_LIMIT_TYPE = 'D')
				BEGIN
					--SELECT	SUM(TAP.APPLICATION_AMOUNT) AS TOTAL_AMOUNT,TAP.CLAIM_ID,FOR_DATE FROM T0110_CLAIM_APPLICATION_DETAIL TAP 
					--WHERE --CLAIM_APP_ID=@CLAIM_APPLICATION_ID and 
					--CLAIM_ID=@CLAIM_ID AND FOR_DATE=@DATE GROUP BY CLAIM_ID,FOR_DATE

					--Added by Mukti(18122020)
					SELECT	SUM(TAP.APPLICATION_AMOUNT) AS TOTAL_AMOUNT,TAP.CLAIM_ID,FOR_DATE 
					FROM T0110_CLAIM_APPLICATION_DETAIL TAP 
					INNER JOIN T0100_CLAIM_APPLICATION CA ON CA.Claim_App_ID=TAP.Claim_App_ID AND Emp_ID=@EMP_ID and Claim_App_Status='A'
					INNER JOIN T0130_CLAIM_APPROVAL_DETAIL CAD ON CAD.Claim_App_ID=TAP.Claim_App_ID
					WHERE TAP.CLAIM_ID=@CLAIM_ID AND cad.Claim_Apr_Date=@DATE and TAP.Cmp_ID=@CMP_ID GROUP BY TAP.CLAIM_ID,FOR_DATE
				END	
			ELSE
				BEGIN				
					--SELECT	SUM(TAP.APPLICATION_AMOUNT) AS TOTAL_AMOUNT,TAP.CLAIM_ID,MONTH(FOR_DATE) AS MONTH_LIMIT FROM T0110_CLAIM_APPLICATION_DETAIL TAP 
					--WHERE --CLAIM_APP_ID=@CLAIM_APPLICATION_ID and 
					--CLAIM_ID=@CLAIM_ID AND MONTH(FOR_DATE)=MONTH(@DATE) GROUP BY CLAIM_ID,MONTH(FOR_DATE)

					--Added by Mukti(18122020)
					SELECT	SUM(TAP.APPLICATION_AMOUNT) AS TOTAL_AMOUNT,TAP.CLAIM_ID,MONTH(FOR_DATE) AS MONTH_LIMIT FROM T0110_CLAIM_APPLICATION_DETAIL TAP 
					INNER JOIN T0100_CLAIM_APPLICATION CA ON CA.Claim_App_ID=TAP.Claim_App_ID AND Emp_ID=@EMP_ID
					WHERE TAP.CLAIM_ID=@CLAIM_ID AND MONTH(FOR_DATE)=MONTH(@DATE) and TAP.Cmp_ID=@CMP_ID GROUP BY TAP.CLAIM_ID,MONTH(FOR_DATE)
					
				END	
		END
		
	ELSE IF @TRAN_TYPE='LA'
		BEGIN
			--SELECT TAP.CLAIM_APP_ID,ROW_NUMBER() OVER (ORDER BY TRAN_ID) AS SR_NO,CLMD.CLAIM_APP_AMNT AS AMOUNT,CLMD.CLAIM_APR_AMNT AS TOTALAMOUNT,
			--CLMD.CLAIM_APP_TOTAL_AMNT AS TOTALAMOUNT_ONE,CLMD.PURPOSE AS DESCRIPTION,CLMD.CURR_RATE AS EXCHANGE_RATE,CLM.CLAIM_NAME AS CLAIM_NAME,CLM.CLAIM_TYPE, -- Added on 23052018 CLM.CLAIM_TYPE
			--CRD.CURR_NAME AS CURRENCY,CLMD.FOR_DATE,CLMD.PETROLKM AS APPROVED_PETROL_KM,CAD.PETROL_KM AS PETROL_KM ,CLAIM_MAX_LIMIT,CAD.CLAIM_ATTACHMENT,CLM.CLAIM_ALLOW_BEYOND_LIMIT,
			--(CASE WHEN CLM.CLAIM_APR_DEDUCT_FROM_SAL = 1 THEN 'Yes' ELSE 'No' END) AS CLAIM_APR_DEDUCT_FROM_SAL,isnull(CAD.Claim_Model,'') AS Model,ISNULL(CAD.Claim_IMEI,'') AS IMEI,ISNULL(CAD.Claim_NoofPerson,'') AS NoofPerson,
			--isnull(CONVERT(varchar,CAD.Claim_DateOfPurchase,103),'') as DateOfPurchase,isnull(CAD.Claim_BookName,'') As BookName,isnull(CAD.Claim_Subject,'') As Subject,isnull(CAD.Claim_ActualPrice,'') As ActualPrice,
			--isnull(CAD.Claim_PriceAfterDiscount,'') As PriceAfterDiscount,isnull(TAP.Claim_FamilyMember,'') as FamilyMember,isnull(TAP.Claim_Relation,'') as Relation,isnull(TAP.Claim_Age,0) as Age,isnull(TAP.Claim_Limit,0) as Limit,
			--CLMD.* 
			--FROM T0115_CLAIM_LEVEL_APPROVAL TAP LEFT OUTER JOIN 
			--	 T0115_CLAIM_LEVEL_APPROVAL_DETAIL CLMD ON CLMD.CLAIM_APR_ID=TAP.TRAN_ID INNER JOIN
			--	 T0110_CLAIM_APPLICATION_DETAIL CAD ON CAD.CLAIM_APP_ID=CLMD.CLAIM_APP_ID
			--	 --AND CAD.Claim_ID=CLMD.Claim_ID
			--	 AND CAD.FOR_DATE=CLMD.FOR_DATE
			--	 AND isnull(CAD.CLAIM_DESCRIPTION,'') = isnull(CLMD.PURPOSE ,'')
			--	 LEFT OUTER JOIN  -- LINE ADDED ON 22052018
			--     T0040_CLAIM_MASTER CLM ON CLM.CLAIM_ID=CAD.CLAIM_ID
			--	 LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD ON TAP.CURR_ID =CRD.CURR_ID  
			--WHERE CLMD.CLAIM_APP_ID=@CLAIM_APPLICATION_ID AND TAP.RPT_LEVEL=@RPT_LEVEL 	
			
			select * from
			(

			--declare @tbl table(tid int identity(1,1),t_tranId int,t_rn int)
			--insert into @tbl
			--select CLMD.Claim_Tran_ID,ROW_NUMBER() OVER (PARTITION BY Claim_Tran_Id ORDER BY TAP.tran_id DESC) AS rn
			--FROM T0115_CLAIM_LEVEL_APPROVAL TAP
			--LEFT JOIN T0115_CLAIM_LEVEL_APPROVAL_DETAIL CLMD ON CLMD.CLAIM_APR_ID=TAP.TRAN_ID and CLMD.Claim_App_ID =TAP.Claim_App_ID
			--INNER JOIN T0110_CLAIM_APPLICATION_DETAIL CAD ON CAD.CLAIM_APP_ID=CLMD.CLAIM_APP_ID and CAD.CLAIM_APP_ID=TAP.CLAIM_APP_ID AND CAD.Claim_ID=CLMD.Claim_ID AND CAD.FOR_DATE=CLMD.FOR_DATE	AND isnull(CAD.CLAIM_DESCRIPTION,'') = isnull(CLMD.PURPOSE ,'')
			--LEFT JOIN  T0040_CLAIM_MASTER CLM ON CLM.CLAIM_ID=CAD.CLAIM_ID and clm.Claim_ID = CLMD.Claim_ID
			--LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD ON TAP.CURR_ID =CRD.CURR_ID  
			--WHERE CLMD.CLAIM_APP_ID=@CLAIM_APPLICATION_ID AND TAP.RPT_LEVEL=@RPT_LEVEL and CAD.Claim_App_ID = @CLAIM_APPLICATION_ID and tap.Claim_App_ID = @CLAIM_APPLICATION_ID

			--select * from @tbl

			SELECT TAP.CLAIM_APP_ID as App_Id,ROW_NUMBER() OVER (ORDER BY TRAN_ID) AS SR_NO,ROW_NUMBER() OVER (PARTITION BY Claim_Tran_Id ORDER BY TAP.tran_id DESC) AS rn,
			CLMD.CLAIM_APP_AMNT AS AMOUNT,CLMD.CLAIM_APR_AMNT AS TOTALAMOUNT,
			CLMD.CLAIM_APP_TOTAL_AMNT AS TOTALAMOUNT_ONE,CLMD.PURPOSE AS DESCRIPTION,CLMD.CURR_RATE AS EXCHANGE_RATE,CLM.CLAIM_NAME AS CLAIM_NAME,CLM.CLAIM_TYPE, -- Added on 23052018 CLM.CLAIM_TYPE
			CRD.CURR_NAME AS CURRENCY,CLMD.FOR_DATE as For_date1,CLMD.PETROLKM AS APPROVED_PETROL_KM,CAD.PETROL_KM AS PETROL_KM ,CLAIM_MAX_LIMIT,CAD.CLAIM_ATTACHMENT,CLM.CLAIM_ALLOW_BEYOND_LIMIT,
			(CASE WHEN CLM.CLAIM_APR_DEDUCT_FROM_SAL = 1 THEN 'Yes' ELSE 'No' END) AS CLAIM_APR_DEDUCT_FROM_SAL,
			isnull(CAD.Claim_Model,'') AS Model,ISNULL(CAD.Claim_IMEI,'') AS IMEI,ISNULL(CAD.Claim_NoofPerson,'') AS NoofPerson,
			isnull(CONVERT(varchar,CAD.Claim_DateOfPurchase,103),'') as DateOfPurchase,isnull(CAD.Claim_BookName,'') As BookName,isnull(CAD.Claim_Subject,'') As Subject,isnull(CAD.Claim_ActualPrice,'') As ActualPrice,
			isnull(CAD.Claim_PriceAfterDiscount,'') As PriceAfterDiscount,isnull(CAD.Claim_FamilyMember,'') as FamilyMember,isnull(CAD.Claim_Relation,'') as Relation,isnull(CAD.Claim_Age,0) as Age,isnull(CAD.Claim_Limit,0) as Limit,
			isnull(TAP.Claim_FamilyMeberId,0) as RowId,isnull(TAP.Claim_UnitName,'') as UnitName,isnull(TAP.Claim_UnitFlag,0) as UnitFlag,isnull(TAP.Claim_ConversionRate,0) as ConversionRate,
			Tap.Claim_Apr_Comments,Tap.Claim_Comments
			,CLMD.*
			--FROM T0115_CLAIM_LEVEL_APPROVAL TAP
			--LEFT OUTER JOIN T0115_CLAIM_LEVEL_APPROVAL_DETAIL CLMD ON CLMD.CLAIM_APR_ID=TAP.TRAN_ID 
			--INNER JOIN T0110_CLAIM_APPLICATION_DETAIL CAD ON CAD.CLAIM_APP_ID=CLMD.CLAIM_APP_ID AND CAD.Claim_ID=CLMD.Claim_ID AND CAD.FOR_DATE=CLMD.FOR_DATE AND CAD.CLAIM_DESCRIPTION = CLMD.PURPOSE  -- LINE ADDED ON 22052018
			--LEFT OUTER JOIN T0040_CLAIM_MASTER CLM ON CLM.CLAIM_ID=CLMD.CLAIM_ID
			--LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD ON TAP.CURR_ID =CRD.CURR_ID  
			--WHERE CLMD.CLAIM_APP_ID=@CLAIM_APPLICATION_ID AND TAP.RPT_LEVEL=@RPT_LEVEL
			
			FROM T0115_CLAIM_LEVEL_APPROVAL TAP
			left JOIN T0115_CLAIM_LEVEL_APPROVAL_DETAIL CLMD ON CLMD.CLAIM_APR_ID=TAP.TRAN_ID and CLMD.Claim_App_ID =TAP.Claim_App_ID 
			--left JOIN @tbl ON CLMD.Claim_Tran_ID = t_tranId and t_rn = 1
			INNER JOIN T0110_CLAIM_APPLICATION_DETAIL CAD ON CAD.CLAIM_APP_ID=CLMD.CLAIM_APP_ID and CAD.CLAIM_APP_ID=TAP.CLAIM_APP_ID 
			AND CAD.Claim_ID=CLMD.Claim_ID AND CAD.FOR_DATE=CLMD.FOR_DATE	AND isnull(CAD.CLAIM_DESCRIPTION,'') = isnull(CLMD.PURPOSE ,'')
			LEFT JOIN  T0040_CLAIM_MASTER CLM ON CLM.CLAIM_ID=CAD.CLAIM_ID and clm.Claim_ID = CLMD.Claim_ID
			LEFT OUTER JOIN T0040_CURRENCY_MASTER CRD ON TAP.CURR_ID =CRD.CURR_ID
			WHERE CLMD.CLAIM_APP_ID=@CLAIM_APPLICATION_ID AND TAP.RPT_LEVEL=@RPT_LEVEL and CAD.Claim_App_ID = @CLAIM_APPLICATION_ID and tap.Claim_App_ID = @CLAIM_APPLICATION_ID
			--and t_rn = 1
			
			) tt where 	tt.rn = 1
					
		END
		
RETURN




