



-- =============================================
-- AUTHOR:		<AUTHOR,,GADRIWALA MUSLIM>
-- CREATE DATE: <CREATE DATE,,29082016>
-- DESCRIPTION:	<DESCRIPTION,, INTERVIEW SCHEDULER DATE SET>
---29/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0200_EXIT_INTERVIEW_SCHEDULER_SET]
@EXIT_ID AS NUMERIC(18,0),
@CMP_ID	AS NUMERIC(18,0),
@INTERVIEW_DATE AS DATETIME,
@INTERVIEW_TIME AS DATETIME,
@STATUS AS CHAR(1)
AS
BEGIN
SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

	
	IF NOT EXISTS(SELECT 1 FROM T0200_EMP_EXITAPPLICATION WITH (NOLOCK)  WHERE EXIT_ID = @EXIT_ID)
	BEGIN
		RAISERROR('@@Exit Application not available,Interview Scheduler date can''t be set@@',18,2)
		RETURN 
	END
	
	UPDATE T0200_EMP_EXITAPPLICATION
			SET INTERVIEW_DATE = @INTERVIEW_DATE,
			 INTERVIEW_TIME = @INTERVIEW_TIME,
			STATUS = @STATUS
			WHERE CMP_ID = @CMP_ID AND EXIT_ID = @EXIT_ID 

	
END

