


-- =============================================
-- AUTHOR:		SNEHA
-- ALTER DATE: 08/09/2011
-- DESCRIPTION:	EXIT INTERVIEW FEEDBACK
---19/1/2021 (EDIT BY MEHUL ) (SP WITH NOLOCK)---
-- =============================================
CREATE PROCEDURE [dbo].[P0200_Exit_Feedback]
@EXIT_FEEDBACK_ID AS NUMERIC(18,0) OUTPUT,
@EMP_ID AS NUMERIC(18,0),
@EXIT_ID AS NUMERIC(18,0),
@CMP_ID AS NUMERIC(18,0),
@QUESTION_ID AS NUMERIC(18,0),
@ANSWER_RATE AS NUMERIC(18,0),
@COMMENTS AS VARCHAR(MAX),   --Change by Jaina 25-05-2018
@FEED_STATUS AS CHAR(1),
@TRANTYPE AS VARCHAR(1),
@Is_Draft as tinyint = 0  --Added by Jaina 21-08-2018
AS

SET NOCOUNT ON 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET ARITHABORT ON

BEGIN
	
	-- ADDED BY GADRIWALA MUSLIM 01092016	
	IF EXISTS(SELECT 1 FROM T0200_EXIT_FEEDBACK WITH (NOLOCK) WHERE EMP_ID = @EMP_ID AND EXIT_ID = @EXIT_ID AND QUESTION_ID = @QUESTION_ID)
		BEGIN
				SELECT @EXIT_FEEDBACK_ID = EXIT_FEEDBACK_ID FROM T0200_EXIT_FEEDBACK WITH (NOLOCK) 
				WHERE EMP_ID = @EMP_ID AND EXIT_ID = @EXIT_ID AND QUESTION_ID = @QUESTION_ID
				
				UPDATE T0200_EXIT_FEEDBACK
				SET ANSWER_RATE = @ANSWER_RATE,
				COMMENTS = @COMMENTS,
				FEED_STATUS = @FEED_STATUS,
				Is_Draft = @Is_Draft
				WHERE EMP_ID = @EMP_ID AND EXIT_ID = @EXIT_ID AND QUESTION_ID = @QUESTION_ID 
		END
	ELSE
		BEGIN
			SELECT @EXIT_FEEDBACK_ID = ISNULL(MAX(EXIT_FEEDBACK_ID),0) + 1 FROM DBO.T0200_EXIT_FEEDBACK WITH (NOLOCK)
				
				INSERT INTO T0200_EXIT_FEEDBACK(
					EXIT_FEEDBACK_ID,
					EMP_ID,
					EXIT_ID,
					CMP_ID,
					QUESTION_ID,
					ANSWER_RATE,
					COMMENTS,
					FEED_STATUS,
					Is_Draft
				)
				VALUES
				(
					@EXIT_FEEDBACK_ID,
					@EMP_ID,
					@EXIT_ID,
					@CMP_ID,
					@QUESTION_ID,
					@ANSWER_RATE,
					@COMMENTS,
					@FEED_STATUS,
					@Is_Draft
				)
		END
		
	--COMMENTED BY GADRIWALA MUSLIM 01092016 
	--if Upper(@trantype) ='I' 
	--	begin
	--		SELECT @EXIT_FEEDBACK_ID = ISNULL(MAX(EXIT_FEEDBACK_ID),0) + 1 FROM DBO.T0200_EXIT_FEEDBACK
				
	--			INSERT INTO T0200_EXIT_FEEDBACK(
	--				EXIT_FEEDBACK_ID,
	--				EMP_ID,
	--				EXIT_ID,
	--				CMP_ID,
	--				QUESTION_ID,
	--				ANSWER_RATE,
	--				COMMENTS,
	--				FEED_STATUS
	--			)
	--			VALUES
	--			(
	--				@EXIT_FEEDBACK_ID,
	--				@EMP_ID,
	--				@EXIT_ID,
	--				@CMP_ID,
	--				@QUESTION_ID,
	--				@ANSWER_RATE,
	--				@COMMENTS,
	--				@FEED_STATUS
	--			)
	--	end
		
		--if UPPER (@trantype) ='U' 
		--	begin
		--		update T0200_Exit_Feedback set
		--		feed_status = @feed_status
		--		where
		--		emp_id = @emp_id and cmp_id = @cmp_id
		--	end
		IF EXISTS(SELECT FEED_STATUS FROM T0200_EXIT_FEEDBACK WITH (NOLOCK) WHERE FEED_STATUS =@FEED_STATUS AND EMP_ID=@EMP_ID )
			BEGIN
				UPDATE T0200_EXIT_INTERVIEW SET INT_STATUS = @FEED_STATUS WHERE EMP_ID=@EMP_ID
				/*UPDATE T0200_EMP_EXITAPPLICATION SET STATUS = @FEED_STATUS WHERE EMP_ID=@EMP_ID*/
				IF EXISTS(SELECT INT_STATUS  FROM  T0200_EXIT_INTERVIEW WITH (NOLOCK) WHERE EMP_ID=@EMP_ID AND INT_STATUS='R')
					BEGIN
						UPDATE T0200_EMP_EXITAPPLICATION SET STATUS = 'R' WHERE EMP_ID=@EMP_ID
					END
					
			END
	END




